### ISSUE TITLE
Add option to toggle list view or tree view

### ISSUE THREAD

**Issue by carlos-algms** [Gruntfuggly/todo-tree#1]
It would be great if we have the option to show all the tasks as a flat list

**Comment by Gruntfuggly** [comment]
Do you mean with full filenames and the todo's expandable underneath them? Might be difficult to fit them in - or do you mean just the filename without the path?

**Comment by carlos-algms** [comment]
Just the filename without the path, something like intelliJ does:

![image](https://user-images.githubusercontent.com/4634613/34020432-5b953814-e11b-11e7-8c5a-04e35e783499.png)

And if it is possible, the full path on the hover event.

**Comment by Gruntfuggly** [comment]
I can do the filename no problem. Unfortunately tooltips aren't controllable at the moment (see [issue 23012](https://github.com/Microsoft/vscode/issues/32012)).

**Comment by carlos-algms** [comment]
I see, looking forward to use this feature. 
Please, remember to create a toggle for it, one may don't like this change ;)

**Comment by Gruntfuggly** [comment]
Try the latest version - there's a button next to the refresh button to swap between flat and tree view. I've put the path in brackets after the filename - if tooltips get implemented, I'll remove the path.

**Comment by carlos-algms** [comment]
It is a great news! Looking forward to test it.
But unfortunately it seems to not be published to VScode plugins yet, it is currently showing 0.0.9.

**Comment by Gruntfuggly** [comment]
Try now - publish failed and I hadn't noticed! Try it now...

**Comment by carlos-algms** [comment]
Cool, it is looking great!! Congratulations!!! 🎉 

Also, it would be a plus if you could change the TODOs color to make it visually different than the file name to create a visual step. 

But I'm completely satisfied with the result, and thanks for you fast response!

**Comment by Gruntfuggly** [comment]
Sorry - there's no way to change the colour. 8-(
Hopefully the vscode team will make some improvements to the tree API. Certainly tooltips should be properly implemented, but they might make icons available too...
