### ISSUE TITLE
Offer lua support by default

### ISSUE THREAD

**Issue by Therzok** [Gruntfuggly/todo-tree#103]
Lua has two kinds of comments:

```
-- Single line comment
--[[
multiline
comment
]]--
```

It is possibly easy to add support for it, but I didn't go first and open a PR for one reason, and that is the `--` operator exists in some languages, thus in a scenario like below. we have a false positive:

```
int x = i-- TODOList.Count;
```

Not a blocker, as it is possible to add workspace regex, just a mention. Maybe an extension <-> regex mapping for languages with uncommon syntax?

**Comment by Gruntfuggly** [comment]
You could change the default regex to something like `$\s*--($TAGS)` to match "--" at the start of a line.

Multiline matches are not currently properly supported though...

**Comment by Gruntfuggly** [comment]
`\s*` should match any or no whitespace? Can you add an example of what you would expect to match so I can try it out?

**Comment by Gruntfuggly** [comment]
Hi - is this still an issue for you?

**Comment by thedaniel** [comment]
In case anyone else comes across this and has a similar use case to mine... I have a mixed codebase of lua and supercollider (which uses `//`) and I just write my lua todos like `-- # TODO:` - ugly, but it works and i don't have to write a regex that matches lua and SC at the same time :)

**Comment by BenjaminHoegh** [comment]
> In case anyone else comes across this and has a similar use case to mine... I have a mixed codebase of lua and supercollider (which uses `//`) and I just write my lua todos like `-- # TODO:` - ugly, but it works and i don't have to write a regex that matches lua and SC at the same time :)

While that is a good workaround I think the package still need real LUA support
