### ISSUE TITLE
Regression in todo-tree.showTagsFromOpenFilesOnly

### ISSUE THREAD

**Issue by vphantom** [Gruntfuggly/todo-tree#104]
Hello,

I'm not sure when it happened, but I no longer get the expected behavior out of `todo-tree.showTagsFromOpenFilesOnly` set to `true`.  I'm dealing with a large project with TODO tags everywhere (not my doing…) and to weed out the noise I need to see only the tags in open files.

When I have multiple files open, the sidebar shows tags for the current file, and only after a forced refresh.  If I switch to another tab and click Todo-Tree's "refresh" button, then I will instead get that other tab's tags.  This also means that I frequently lose the explorer section entirely when it thinks there's nothing to display.  Here's my configuration:

```json
    "todo-tree.expanded": true,
    "todo-tree.flat": true,
    "todo-tree.grouped": false,
    "todo-tree.tags": [
        "FIXME",
        "XXX",
        "TODO",
        "BUG",
        "HACK",
        "NOTE"
    ],
    "todo-tree.highlightDelay": 0,
    "todo-tree.showTagsFromOpenFilesOnly": true,
    "todo-tree.showInExplorer": true,
    "todo-tree.defaultHighlight": {
        "type": "tag"
    },
    "todo-tree.customHighlight": {
        "FIXME": {
            "icon": "alert",
            "background": "#dd0000"
        },
        "XXX": {
            "icon": "eye",
            "background": "#2266ff"
        },
        "TODO": {
            "icon": "verified",
            "background": "#ff8800"
        },
        "BUG": {
            "icon": "flame",
            "background": "#dd0000"
        },
        "HACK": {
            "icon": "alert",
            "background": "#eecc00"
        },
        "NOTE": {
            "icon": "eye",
            "background": "#77dd77"
        }
    },
    "todo-tree.autoRefresh": true,
    "todo-tree.trackFile": true
```

Is this a regression or an improper configuration?

Thank you!

**Comment by Gruntfuggly** [comment]
Sounds like a bug - the intended behaviour is that with showTagsFromOpenFilesOnly set to true the tree should only contain todos from files actually opened - ie. no searching. They shouldn't disappear though unless a file is closed...

**Comment by vphantom** [comment]
That's what it used to do indeed. And thanks again for Todo-Tree btw, it has a big impact on my workflow. :)

**Comment by Gruntfuggly** [comment]
OK, I've got a fix. Just doing a bit of testing before releasing...

**Comment by Gruntfuggly** [comment]
Please try the latest version and let me know if it behaves correctly.

**Comment by vphantom** [comment]
Success! Thank you for your help!
