### ISSUE TITLE
Add option to show line number in results

### ISSUE THREAD

**Issue by cyberbit** [Gruntfuggly/todo-tree#105]
My current TODO workflow makes the tree look like this:

![image](https://user-images.githubusercontent.com/7350183/49887073-fb0a2000-fe00-11e8-8880-d482f675c984.png)

It's hard to know exactly where each TODO will take me. When in the context of a file list, having some kind of line indicator on the label would be nice. I know that the tooltip has it already, but it's pretty slow to appear and doesn't persist while coding.

This seems like an easy add, I may be able to work on a PR for this myself :)

**Comment by cyberbit** [comment]
Yes these are all in the same file. This particular workflow is used to quickly mark lines of code in a repeatable way for later review. The tag itself has implied context to the developer working the task and doesn't usually need more detail than itself.

The format string could work. That would allow wider configuration for others.

On Wed, Dec 12, 2018 at 2:04 PM Nigel Scott <notifications@github.com<mailto:notifications@github.com>> wrote:

if those are all in the same file, I can see what you mean. Is there nothing after the tag on the line in each case?

It might be quite useful to have a sort of 'format' string for the labels, with placeholders for line number, text after the tag, etc. It might be easier that having more options...

**Comment by cyberbit** [comment]
Thanks for your work on this! One minor thing, the line number seems to be a zero-based index rather than the actual line number that shows in the editor:

![screen shot 2018-12-28 at 11 29 58 am](https://user-images.githubusercontent.com/7350183/50523133-02355d00-0a94-11e9-8bce-d66edf67558c.png)

For reference, I'm using the pattern `(${line}) ${tag} ${after}`.

**Comment by Gruntfuggly** [comment]
Oops - Will sort it in the next couple of days...

**Comment by Gruntfuggly** [comment]
Done.
