### ISSUE TITLE
todo-tree.excludeGlobs is not working

### ISSUE THREAD

**Issue by luqiudi** [Gruntfuggly/todo-tree#106]
i config todo-tree like this：
 "todo-tree.excludeGlobs": [
    "node_modules"
  ],
without this config，my todo-tree will list a lot of todo item with node_modules.
could you give me some suggestion？
By the way，there are not error in console

**Comment by Gruntfuggly** [comment]
Hi - are you saying it is not working when you set it like that?

Please try:
```
"todo-tree.excludeGlobs": [
   "**/node_modules/*"
],
```

**Comment by udondan** [comment]
Yeah, it looks like I can confirm that. I used to have in my config this setting:

```
"todo-tree.globs": [
    "!**/vendor"
],
```

For some time now VSC always told me this is deprecated and asked if I would like to auto-migrate. I always said yes but the migration never worked. 

Today I finally wanted to fix this and tried to manually migrate to the new format. I found the new key actually was created but the old one was not removed. Which is the cause for the daily reminder. The new setting looks like this:

```
"todo-tree.excludeGlobs": [
    "**/vendor"
],
```

As soon as I remove the old key `todo-tree.globs` the plugin lists all todos inside the vendor folder. So it looks like it's not working. Also with a trailing wildcard like in your above example it is the same.

Interestingly, the settings show me a validation error on the old key. Though this is the one actually working.

![todo-settings](https://user-images.githubusercontent.com/6443408/50349067-ea615480-053a-11e9-96cd-f9a65c8a1927.png)

**Comment by udondan** [comment]
> So if you remove the old setting and use 'excludeGlobs' as `**/vendor/*` it still matches them?

Yes, that is correct. With the settings as seen in the screenshot above it works. When I remove the old block and hit reload in the TODO pane, all the TODOs from the vendor folder show up. If I add the old block again and push the reload button, they're gone again.

> Could you copy and paste the contents of the "todo-tree" debug console (from the output view) please.

I would love to, but couldn't figure it out within 10 minutes. I believe you ask me to switch to the output console and then on the right side select the todo-tree extension, but there ain't no entry like that. 😕 

![bildschirmfoto 2018-12-21 um 16 51 50](https://user-images.githubusercontent.com/6443408/50350952-f94b0580-0540-11e9-97cd-c275ac58c535.png)

> I might need to get you to do some remote debugging too if that's OK.

Absolutely!

**Comment by udondan** [comment]
I also just uninstalled and reinstalled Todo Tree to see if that helps. Same behaviour.

**Comment by Gruntfuggly** [comment]
Sorry - I should have asked you to turn on debug first - set `todo-tree.debug` to true.

Just to make sure I understand - it works correctly (filters out the matches) with 
```
"todo-tree.globs": {
    "!**/vendor/"
},
"todo-tree.excudeGlobs": {
   "**/vendor/*"
}
```
but if you remove
```
"todo-tree.globs": {
    "!**/vendor/"
},
```
It doesn't filter them out?

What does it do if you remove?
```
"todo-tree.excudeGlobs": {
   "**/vendor/*"
}
```

I think the debug log would be useful...

**Comment by udondan** [comment]
Yeah, now it looks better. Sorry, I never worked on plugins themselves before.

> Just to make sure I understand...

Yes, correct.

Here is the output, once with the old config in place and once without.

This config:

```
    "todo-tree.globs": [
        "!**/vendor"
    ],
    "todo-tree.includeGlobs": [],
    "todo-tree.excludeGlobs": [
        "**/vendor"
    ],
```

produces this debug output:

```
Searching /project/path...
Command: /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg --no-messages --vimgrep -H --column --line-number --color never  -e "((//|#|<!--|;|/\*|^)\s*(TODO|FIXME)|^\s*- \[ \])" -g "!**/vendor" "/project/path"
*** SNIP - all the matches ***
Found 18 items
Applying globs to 18 items...
Remaining items: 18

```

---

This config:

```
    //"todo-tree.globs": [
    //    "!**/vendor"
    //],
    "todo-tree.includeGlobs": [],
    "todo-tree.excludeGlobs": [
        "**/vendor"
    ],
```

produces this debug output:

```
Searching /project/path...
Command: /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg --no-messages --vimgrep -H --column --line-number --color never  -e "((//|#|<!--|;|/\*|^)\s*(TODO|FIXME)|^\s*- \[ \])" "/project/path"
*** SNIP - all the matches ***
Found 235 items
Applying globs to 235 items...
Remaining items: 235

```

At the end it says _Applying globs to 235 items..._ but all 235 remain. The pattern is not shown in the debug output.

I also tried it the other way around. This config:

```
    //"todo-tree.globs": [
    //    "!**/vendor"
    //],
    "todo-tree.includeGlobs": [
        "**/vendor"
    ],
    "todo-tree.excludeGlobs": [],
```

filters out everything. I would have expected to only see the results inside the vendor dir, but 0 remain:

```
Searching /project/path...
Command: /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg --no-messages --vimgrep -H --column --line-number --color never  -e "((//|#|<!--|;|/\*|^)\s*(TODO|FIXME)|^\s*- \[ \])" "/project/path"
Found 235 items
Applying globs to 235 items...
Remaining items: 0
```

**Comment by udondan** [comment]
And I just figured it out the second I send the previous reply!

I tried `**/vendor` and `**/vendor/*`. Both don't work.

**But this does works:** `**/vendor/**`

And looking at the [linked documentation](https://www.npmjs.com/package/glob#glob-primer), it actually makes perfect sense.

`*` expands only to a single path segment and of course all the results in the vendor dir are in nested directories.

I assume, the reason why it worked before with `!**/vendor` is that this pattern was passed to [ripgrep](https://github.com/BurntSushi/ripgrep) which applies the glob on each directory while it moves through the tree. The glob from the new setting instead is applied on the whole filepath of every match.

User error. Case closed :) Thanks for looking into it!

**Comment by Gruntfuggly** [comment]
I'm glad it's sorted. Not sure why you had problems with the migration though...

**Comment by punkyard** [comment]
## Comprehensive Testing Confirms excludeGlobs/includeGlobs Bug

I can confirm this bug still exists after extensive testing with multiple configuration approaches. Here's a summary of my testing:

### Goal
Configure TODO Tree to exclude `.sh` and `.json` files while including all `.md` files from the entire workspace (including subdirectories like `.github/conversations/`, `.github/documentation/`, etc.).

### Test Environment
- VS Code with latest TODO Tree extension
- Test files created in various locations:
  - Root workspace: `test-todo.md`, `test-script.sh`, `test-config.json`
  - `.github/` subdirectories: `test-github.md`, `test-nested-github.md`

### Configurations Tested (All Failed)

**1. Modern filtering approach:**
```json
{
  "todo-tree.includeGlobs": ["**/*.md"],
  "todo-tree.excludeGlobs": ["**/*.sh", "**/*.json"]
}
```

**2. With built-in excludes disabled:**
```json
{
  "todo-tree.includeGlobs": ["**/*.md"],
  "todo-tree.excludeGlobs": ["**/*.sh", "**/*.json"],
  "todo-tree.useBuiltInExcludes": "none"
}
```

**3. Various pattern combinations:**
```json
{
  "todo-tree.excludeGlobs": ["*.sh", "*.json", "**/*.sh", "**/*.json"]
}
```

**4. Legacy filtering approaches:**
```json
{
  "todo-tree.filtering.excludeGlobs": ["**/*.sh", "**/*.json"],
  "todo-tree.filtering.includeGlobs": ["**/*.md"]
}
```

### Results
- **All filtering configurations were completely ignored**
- TODOs from `.sh` and `.json` files continued to appear
- No difference between using `includeGlobs`, `excludeGlobs`, or both together
- Debug mode enabled showed no filtering patterns being applied
- The only working approach was using the deprecated `todo-tree.globs` setting

### Working Workaround
The only configuration that actually worked was the deprecated approach:
```json
{
  "todo-tree.globs": ["**/*.md"]
}
```
This successfully limited scanning to only `.md` files.

### Conclusion
This confirms the bug reported in this issue. The `excludeGlobs` and `includeGlobs` settings appear to be completely non-functional, while the deprecated `globs` setting still works correctly. This suggests a regression was introduced when the new filtering system was implemented.

The filtering functionality needs a complete review and fix, as it's a core feature that many users rely on for managing large codebases.
