### ISSUE TITLE
Why don't support the "@todo" (jsDoc style)

### ISSUE THREAD

**Issue by roboooots** [Gruntfuggly/todo-tree#107]
I used the JsDoc, and I add "@todo" to "todo-tree.tags" like this:
    "todo-tree.tags": [
        "TODO",
        "FIXME",
        "@todo"
    ],
but it dose not works.

my comments like this : 
 /**
     * @param {Object} obj1 
     * @param {Object} obj2 
     * @returns {number} 
     * @todo need to confirm
     */

**Comment by roboooots** [comment]
> I used the JsDoc, and I add "@todo" to "todo-tree.tags" like this:
> "todo-tree.tags": [
> "TODO",
> "FIXME",
> "@todo"
> ],
> but it dose not work.

**Comment by Gruntfuggly** [comment]
You'll need to modify the regex too. Try 
`((\* //|#|<!--|;|/\*|^)\s*($TAGS)|^\s*- \[ \])`
I've added "\* " to match the comment.

**Comment by roboooots** [comment]
I got it, also understand the principle of this configuration.  thank u very much~!

**Comment by jabacchetta** [comment]
@Gruntfuggly Thanks! This was the magic regex I needed to get everything working as desired, with strikethroughs and TODOs inside of JSDoc comments. Not sure if it'd be worth adding this regex to the docs, but just an FYI.

My setup, for reference:

```jsonc
    /* Todo Tree */

    "todo-tree.highlights.customHighlight": {
      "TODO": {
        "foreground": "#FFEB95",
      },
      "NOTE": {
        "foreground": "#FFEB95",
        "icon": "note",
      },
      "FIXME": {
        "foreground": "#FFEB95",
        "icon": "alert",
      },

      // Clearly mark comments that belong to disabled (commented-out) code.
      "// //": {
        "textDecoration": "line-through",
        "type": "text",
        "hideFromTree": true,
      },
    },

    "todo-tree.tree.grouped": true,
    "todo-tree.tree.hideIconsWhenGroupedByTag": true,
    "todo-tree.tree.labelFormat": "∙ ${after}",
    "todo-tree.tree.showCountsInTree": true,
    "todo-tree.tree.showInExplorer": false,
    "todo-tree.tree.showScanOpenFilesOrWorkspaceButton": true,
    "todo-tree.tree.tagsOnly": true,
    "todo-tree.highlights.highlightDelay": 0,
    "todo-tree.general.tags": [
      "TODO",
      "FIXME",
      "NOTE",
      "// //",
    ],

  "todo-tree.highlights.schemes": [
    "file",
    "untitled",
    "vscode-userdata",
  ],

  "todo-tree.regex.regex": "((\\*|//|#|<!--|;|/\\*|^)\\s*($TAGS)|^\\s*- \\[ \\])",
```

**Comment by VideoPlayerCode** [comment]
Just a warning for anyone finding this old ticket: `\*` is very generic and will also match `1 * 2` etc... There is a better regex and JavaScript setup here: https://github.com/Gruntfuggly/todo-tree/wiki/Configuration-Examples#javadoc
