### ISSUE TITLE
Add dates and priority?

### ISSUE THREAD

**Issue by SeaDude** [Gruntfuggly/todo-tree#108]
Hello,

**Feature request here:** I use this tool to create ToDo items in my notes (Markdown). Would be awesome to assign a date and priority to each ToDo item.

Thank you

**Comment by Gruntfuggly** [comment]
Hi - this extension doesn't provide any facilities for creating todo items - it just searches for them.

If you create your todo like this:

` - [ ] TODO 25/12/18 (high): Buy shopping`

Then you should see the date in the tree?

**Comment by SeaDude** [comment]
Hm. Ok, thank you. 
What I'm looking for in a ToDo tool:
`- [ ] TODO <dueDate in mm/dd/yyyy format> <priority selection> : <ToDo Item>` I used to use Emacs Orgmode for this type of thing. I'm sure someone will come up with it. 
Take care

**Comment by Gruntfuggly** [comment]
You could probably do that with vscode's snippets:
https://code.visualstudio.com/docs/editor/userdefinedsnippets
You could define one to automatically insert the date, provide a choice for the priority and then put the cursor in the right place for the todo part.
