### ISSUE TITLE
Support for twig comments

### ISSUE THREAD

**Issue by terryupton** [Gruntfuggly/todo-tree#109]
Can you help me add support for Twig comments?
Twig comments start with `{#` and I understand you need to edit the regex config but I cannot seem to get this to work, it keeps throwing up a mis-match error in VScode. Here is what I tried.
`((//|{#|#|<!--|;|/\\*)\\s*($TAGS)|^\\s*- \\[ \\])` 

At the moment the first { gets missed off the higlhighting as I guess it is picking up the # from the default regex command.

Thanks.

**Comment by terryupton** [comment]
Doh. As soon as I posted this, I managed to resolve it. The curly bracket needed to be escaped. 
So here is the fixed regex.
`((//|\\{#|#|<!--|;|/\\*)\\s*($TAGS)|^\\s*- \\[ \\])`

Feel free to close this thread.

**Comment by Gruntfuggly** [comment]
Glad you got it sorted!

**Comment by omnichronous** [comment]
> Doh. As soon as I posted this, I managed to resolve it. The curly bracket needed to be escaped.
> So here is the fixed regex.
> `((//|\\{#|#|<!--|;|/\\*)\\s*($TAGS)|^\\s*- \\[ \\])`
> 
> Feel free to close this thread.

This one didn't work for me, the problem was the extra backslash at position 7. Works fine when I removed it. I also added another bit which recognizes `{{--` comments:

`((//|\{#|#|\{\{--|<!--|;|/\*|^)\s*($TAGS)|^\s*- \[ \])`

**Comment by Gruntfuggly** [comment]
That's because the original poster was posting his settings from the `settings.json` where the backslashes need to escaped too.  It looks like you've copied yours from the settings GUI which automatically escapes the backslashes for you.
