### ISSUE TITLE
ripgrep Error

### ISSUE THREAD

**Issue by afmicc** [Gruntfuggly/todo-tree#11]
After install the extension, show this message:

> todo-tree: Failed to find vscode-ripgrep - please install ripgrep manually and set 'todo-tree.ripgrep' to point to the executable

vs code version 1.21.1

Also I tried to uninstall and install ripgrep, but there weren't changes
```
cd C:\Users\xxx\.vscode\extensions\Gruntfuggly.todo-tree-0.0.30
npm uninstall vscode-ripgrep
npm install vscode-ripgrep
```

**Comment by Gruntfuggly** [comment]
Recent updates mean that it now looks for vscode-ripgrep in a slightly different place. Can you try removing "todo-tree.ripgrep" from your User or Workspace settings and see if it can find it?
Are you using Windows?

**Comment by Frikki** [comment]
Looking at the `.vscode` path, @afmicc is on a Windows platform.

**Comment by afmicc** [comment]
How says @Frikki, I'm using Windows platform.

If I add the following line, fix the error.

```
function getRgPath()
{
    ...

    rgPath = exePathIsDefined( path.join( path.dirname( path.dirname( require.main.filename ) ), "node_modules.asar.unpacked/vscode-ripgrep/bin/rg.exe" ) );
    if( rgPath ) return rgPath;
    
    ...
}
```
Does this make sense to you, @Gruntfuggly?

**Comment by Gruntfuggly** [comment]
Ah - OK I see what's happened. The last change didn't include the correct check for the filename. Should now be fixed.

**Comment by afmicc** [comment]
Great! Now works

**Comment by MohdElBasyouni** [comment]
Is this seems to be coming back again ?

**Comment by Theneas** [comment]
Setting Todo-tree.Rpgrep Args to 
C:\Users\USERNAME\\.vscode\extensions\jimmyzjx.ripgrep-0.4.2 (no quotes, except if editing directly in settings.json)
did the trick for me, but it'll have to be manually edited every ripgrep update I guess

**Comment by d1820** [comment]
this is back with latest VSCode 6.1.2026
Todo-Tree: Failed to find vscode-ripgrep - please install ripgrep manually and set 'todo-tree.ripgrep' to point to the executable

**Comment by bjornnorberg** [comment]
> this is back with latest VSCode 6.1.2026 Todo-Tree: Failed to find vscode-ripgrep - please install ripgrep manually and set 'todo-tree.ripgrep' to point to the executable

Yes same for me

**Comment by cyraid** [comment]
Same here. Every time I open vscode, even before I select a project, I'm bombarded with a popup error.

**Comment by zhang00956** [comment]
https://github.com/BurntSushi/ripgrep/releases 手动下载ripgrep，然后在插件里面配置rg.exe路径，一劳永逸

<img width="908" height="178" alt="Image" src="https://github.com/user-attachments/assets/1dc63b18-5a19-4289-a76d-117c4b930078" />

**Comment by LvnRtg** [comment]
@zhang00956's solution also works on Linux:
- Install ripgrep via `sudo apt install ripgrep`
- Determine the location where it was installed with `dpkg -L ripgrep` (typically, this location is `/usr/bin/rg`)
- In VS Code, open your settings and find "Todo-Tree > Ripgrep: Ripgrep`; enter you installation location there:

<img width="450" height="95" alt="Image" src="https://github.com/user-attachments/assets/f9c4876a-479f-4850-bbd5-a694cf177527" />

- Restart your extensions and everything works again.

**Comment by NafiurSiddiqui** [comment]
> [@zhang00956](https://github.com/zhang00956)'s solution also works on Linux:
> 
> * Install ripgrep via `sudo apt install ripgrep`
> * Determine the location where it was installed with `dpkg -L ripgrep` (typically, this location is `/usr/bin/rg`)
> * In VS Code, open your settings and find "Todo-Tree > Ripgrep: Ripgrep`; enter you installation location there:
> 
> <img alt="Image" width="450" height="95" src="https://private-user-images.githubusercontent.com/237723862/601494648-f9c4876a-479f-4850-bbd5-a694cf177527.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODAzOTY3MDMsIm5iZiI6MTc4MDM5NjQwMywicGF0aCI6Ii8yMzc3MjM4NjIvNjAxNDk0NjQ4LWY5YzQ4NzZhLTQ3OWYtNDg1MC1iYmQ1LWE2OTRjZjE3NzUyNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwNjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDYwMlQxMDMzMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YzBmOTQyYWE4Mjk3ZTYwOThiMzI1N2YyYjA5YTk0YzIzMWVjNmY0ZDZkZjE4YjI4YzJkN2I4NzQwNDA2YWU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZyZXNwb25zZS1jb250ZW50LXR5cGU9aW1hZ2UlMkZwbmcifQ.C4L8CiocoALoWTeLftZVmkRiSrJkY5m9ONI_TCrR9iQ">
> * Restart your extensions and everything works again.

This works perfectly again.

**Comment by MateusPitura** [comment]
Complementing @LvnRtg comment for Linux, in the user's `settings.json` add:
```
"todo-tree.ripgrep.ripgrep": "/usr/bin/rg",
```

**Comment by PwrSrg** [comment]
**Same issue here**.  (Windows 11)  Searched my system for `rg.exe` and found a _bunch_ of them.  Added `C:\Users\USERNAME\AppData\Local\Programs\cursor\resources\app\node_modules\@vscode\ripgrep\bin\rg.exe` to the `ripgrep` location setting in VSCode and all is well again.

**Comment by FabianMontoya** [comment]
Same error again here, I'm using Windows 11 Pro and the extension is installed into VS Code v1.122.1

<img width="585" height="198" alt="Image" src="https://github.com/user-attachments/assets/082c8d92-aa07-41d9-b72c-2a56578eeeec" />
<img width="486" height="381" alt="Image" src="https://github.com/user-attachments/assets/f205ef23-7aa4-459b-b742-6f75a6f5767f" />

**Comment by Viroxken** [comment]
Same here, since today I've noticed the following popup, tried reinstalling the extension but no success.

<img width="398" height="134" alt="Image" src="https://github.com/user-attachments/assets/b015d70b-410a-4190-a8d8-da79519063c0" />

<img width="373" height="293" alt="Image" src="https://github.com/user-attachments/assets/8a4a1f5e-07dd-4cbf-8356-abed84ec16c4" />

**Comment by FabianMontoya** [comment]
CC: @afmicc

**Comment by AnaelBonnafous** [comment]
On Windows, I had already installed ripgrep locally using Winget, so I just added this line to my VSCode settings.json file.

```json
{
  ...
  "todo-tree.ripgrep.ripgrep": "C:\\Users\\xxx\\AppData\\Local\\Microsoft\\WinGet\\Links\\rg.exe",
}
```

**Comment by mila411** [comment]
I'm using the Mac version. Has anyone figured out how to fix this?
I installed ripgrep via Homebrew, but when I run:

```bash
$ which ripgrep                                                             
it returns “ripgrep not found.”
```

**Comment by AnaelBonnafous** [comment]
> I'm using the Mac version. Has anyone figured out how to fix this?
> I installed ripgrep via Homebrew, but when I run:
> 
> ```bash
> $ which ripgrep                                                             
> it returns “ripgrep not found.”
> ```

The command for ripgrep is `rg` not `ripgrep` so you should try `which rg`.

**Comment by Sladerix** [comment]
On macOS fixed by

1. installing rigrep
```bash
brew install rg
```
2. Get the path
```bash
which rg
```
3. Copy paste the output path in the VS Settings of TodoTree extension as showed by @LvnRtg 
<img width="728" height="848" alt="Image" src="https://github.com/user-attachments/assets/1cb6d9ac-755f-4701-95be-9c54c0d80a2c" />

4. Disable - Enable the extension

**Comment by ciscoheat** [comment]
An alternative is switching to https://github.com/FanaticPythoner/better-todo-tree which is a maintained fork.

**Comment by cathalmoloney** [comment]
On Windows 11, I found ripgrep installed locally and added the following to my VSCode settings.json file:

```
"todo-tree.ripgrep.ripgrep": "C:\\Users\\USERNAME\\AppData\\Local\\Programs\\Microsoft VS Code\\6a44c352bd\\resources\\app\\extensions\\copilot\\node_modules\\@github\\copilot\\sdk\\ripgrep\\bin\\win32-x64\\rg.exe"
```

**Comment by MartinKirkley-Rogers** [comment]
For Windows 11:

I used chocolatey to install ripgrep (choco install ripgrep) and it gives the install location in the output:

Deployed to 'C:\ProgramData\chocolatey\lib\ripgrep\tools'

Open the location in Explorer and you will see a subfolder named something like "ripgrep-14.1.0-x86_64-pc-windows-msvc", the rg.exe is in there, so copy the full path, eg:

C:\ProgramData\chocolatey\lib\ripgrep\tools\ripgrep-14.1.0-x86_64-pc-windows-msvc

In VSCode click Settings > Settings and expand Extensions.

Scroll down to "ripgrep" and put the path you copied followed by rg.exe:

C:\ProgramData\chocolatey\lib\ripgrep\tools\ripgrep-14.1.0-x86_64-pc-windows-msvc\rg.exe

Restart VSCode.

**Comment by FabianMontoya** [comment]
I solved the error installing locally `ripgrep`, but I'm using Windows and MacOS VS Code with my settings sync, so, I have to install `ripgrep` using homebrew (MacOS) and using Winget (Windows), both, following the solution purpose in this thread, search the path where it is installed and disable the sync of the `ripgrep` path property from todo three:

`setting.json`

```
"settingsSync.ignoredSettings": ["todo-tree.ripgrep.ripgrep"]
```

**Comment by carpaltunnelsurgery** [comment]
I fixed this by [downloading and extracting ripgrep](https://github.com/BurntSushi/ripgrep/releases/tag/15.1.0) and adding `"todo-tree.ripgrep.ripgrep": "C:\\path\\to\\rg.exe"` to settings.json. Then restart VSCode and it'll be fixed.

It stopped working because [VSCode changed the location of the bundled ripgrep](https://github.com/microsoft/vscode/issues/318691) in 1.122.0
