### ISSUE TITLE
Default colour used in documentation is not defined in highlights.js

### ISSUE THREAD

**Issue by nveenjain** [Gruntfuggly/todo-tree#110]
White colour is used in foreground property of defaultHighlight, however there is no such colour in highlight.js and it renders to a black background instead.
```js
"todo-tree.defaultHighlight": {
    "icon": "alert",
    "type": "text",
    "foreground": "red",
    "background": "white", //white is used here
    "iconColour": "blue"
},
"todo-tree.customHighlight": {
    "TODO": {
        "icon": "check",
        "type": "line"
    },
    "FIXME": {
        "foreground": "black",
        "iconColour": "yellow"
    }
}
```

**Comment by Gruntfuggly** [comment]
Good spot - that's a bit stupid! I'll add white and black to the available colours.

**Comment by Gruntfuggly** [comment]
Sorted in the latest version.

**Comment by bhack** [comment]
Is this only a problem related to the documentation? Cause I see this problem also using the default delivered values.

**Comment by bhack** [comment]
Sorry I meant that with default installation the Highlight background is black on the default dark vscode theme.

**Comment by Gruntfuggly** [comment]
Yes - that's not quite right though. The last update fixed the problem with black and white, but not specifying the colour at all shouldn't default to black/white.

Fix on it's way...
