### ISSUE TITLE
adding a background color defeats selection

### ISSUE THREAD

**Issue by ajoslin103** [Gruntfuggly/todo-tree#112]
_note: I'm using the l theme (don't know if it matters)_

When I enable the backgroundColor then I can no longer determine which text within the TODO I have highlighted. (IOW: selected TODO text is not highlighted )

 ```
 "workbench.colorTheme": "Cobalt0",
  "todo-tree.defaultHighlight": {
    "type": "text",
    "foreground": "yellow",
    // "background": "blue",
    "iconColour": "darkblue",
  },

```

**Comment by Gruntfuggly** [comment]
I see what you mean. I'll add an option to reduce the background opacity...

**Comment by ajoslin103** [comment]
thanks!
