### ISSUE TITLE
native charset support

### ISSUE THREAD

**Issue by wjx0912** [Gruntfuggly/todo-tree#114]
http://98.142.142.53/todo_trees.png

it looks like only support utf8, can  auto  detect  the charset?
thanks

**Comment by Gruntfuggly** [comment]
Sounds similar to https://github.com/Gruntfuggly/todo-tree/issues/63

If you enable the `todo-tree.debug` option and look in the debug channel in the output window, what do you see in the ripgrep search results?

**Comment by wjx0912** [comment]
@Gruntfuggly 
hi, thanks for your reply.
the ripgrep output also uncorrect charset, so it's ripgrep bug?

**Comment by Gruntfuggly** [comment]
Maybe, but it may just be a limitation on ripgrep. See the ripgrep author's comment here: https://github.com/Gruntfuggly/todo-tree/issues/63#issuecomment-414097844

**Comment by wjx0912** [comment]
@Gruntfuggly 
thank you~
