### ISSUE TITLE
todo-tree.debug not available

### ISSUE THREAD

**Issue by bruceauyeung** [Gruntfuggly/todo-tree#115]
I saw you mentioned `todo-tree.debug` config in other issues, but i can not find it in version `0.0.112`,
and  there isn't nothing in output panel even when i have set  `todo-tree.debug` to `true` manually in user settings

**Comment by bruceauyeung** [comment]
its my mistake.
the preferences here indeed just looks like yours, and there is a `DEBUG CONSOLE` at the right side of `OUTPUT` tab. but there is nothing displayed in debug console when i opened todo-tree view which have some todos displayed .

**Comment by Gruntfuggly** [comment]
If you open the OUTPUT tab, you should see a drop down on the right - you should be able to find 'todo-tree' in there.

**Comment by Gruntfuggly** [comment]
That's wierd - it's a normal dependency. Could you try uninstalling and reinstalling it?

**Comment by tuur29** [comment]
Oh that's weird. I see you just pushed an update, so when I opened my Visual Studio Code it updated the app immediately and everything seems to work again. I did however reinstall a few days ago but it didn't help then.

Perhaps it had something to do with the version number increasing?

**Comment by Gruntfuggly** [comment]
Very odd. I'll leave this open for a while in case it happens again...
