### ISSUE TITLE
do i have to install ripgrep manually?

### ISSUE THREAD

**Issue by bruceauyeung** [Gruntfuggly/todo-tree#116]
i encounted some performance problems with todo-tree. i have already excluded `node_modules`, 'dist` directories, but there is a directory `vendor` which  i don't want to exclude brings performance penalty, this `vendor` directory is Golang vendor directory and of course, it's a little large, but not large as node_modules, i am wandering there is no warning/error even if there is no ripgrep installed in my machine, right ?

**Comment by bruceauyeung** [comment]
after i installed ripgrep manually and configure `todo-tree.ripgrep` to the path, the performance problem is gone.

**Comment by bruceauyeung** [comment]
should todo-tree install ripgrep as its dependency automatically ?

**Comment by Gruntfuggly** [comment]
By default it uses a version of ripgrep that is provided with vscode. For example, on my Ubuntu machine, it's found here:
`/usr/share/code/resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg`

**Comment by Gruntfuggly** [comment]
Hi - do you need any further support on this?
