### ISSUE TITLE
Don't color whitespace

### ISSUE THREAD

**Issue by tuur29** [Gruntfuggly/todo-tree#118]
I'm using this in my settings file:

```
"todo-tree.defaultHighlight": {
  "type": "line",
  "foreground": "#BA68C8",
},
```

And have the option "Render whitespace" in Visual Studio code enabled.

The result is this:

![image](https://user-images.githubusercontent.com/2472626/51438607-a767dd80-1cae-11e9-896c-119d5ba26168.png)

My normal coloring of the whitespace is very similar to the background so it's not distracting. But as you can see the TODO text is harder to read because of the uniform color. 
Would it be possible to have a setting so the extension doesn't color the whitespaces, or perhaps colors them darker / lighter?

**Comment by moymike** [comment]
Within the source view, the highlighted TODO items are displaying characters.  My default for the editor is set to 'none', but the 'todo tree' is showing rendering characters.
I have settings ->  "editor.renderWhitespace": "none"

![image](https://user-images.githubusercontent.com/5559628/51544356-56c6c080-1e25-11e9-9e0c-705fae9d8e57.png)

**Comment by Gruntfuggly** [comment]
I'm not sure what is going on here - the extension just creates a highlight range. It doesn't know anything about whitespace. If I set renderWhitespace to none, it doesn't show it.

Is it possible your settings are different in workspaceSettings?

**Comment by Gruntfuggly** [comment]
@tuur29 I'm not sure it's possible to show the whitespace differently - the highlight has a foreground and background colour. There may be something in the css that can be applied though. I'll investigate...

**Comment by tuur29** [comment]
@moymike I might be misunderstanding your problem, but I can see the same 'tab arrows' and 'space bullets' on the lines above and below your TODO. They are very dark though (same color as your indent guides).

@Gruntfuggly I've just discovered you had a `"type": "text"` option, which helps a bit and started using a background color instead. But thanks for looking into it anyway.

**Comment by Gruntfuggly** [comment]
@tuur29 I was going to suggest trying the 'text' option. There doesn't seem to be any way to style the text differently to the whitespace - the only other option I can think of is to create multiple highlights, but that might incur a performance hit.

There are a bunch of other options for highlighting ranges: 
https://code.visualstudio.com/api/references/vscode-api#DecorationRenderOptions

Does anything there sound useful?

One other thing - have you tried setting renderWhitespace to boundary? I've only just discovered the setting and it works much better for me...

**Comment by moymike** [comment]
> @tuur29 I might be misunderstanding your problem, but I can see the same 'tab arrows' and 'space bullets' on the lines above and below your TODO. They are very dark though (same color as your indent guides).> 

YES, was so dark I didn't realize it.  I thought that Todo-Tree was rendering the whitespace.  

Just tested 
"type": "text" and "editor.renderWhitespace": "boundary", 

It appears to fix the issue for me.
