### ISSUE TITLE
Open Editors

### ISSUE THREAD

**Issue by scotthardwick** [Gruntfuggly/todo-tree#12]
Great extension!

Would it be possible for it to also look at files in the "Open Editors" pane as well as those in the "Workspace" folder?

Much thanks!

**Comment by Gruntfuggly** [comment]
8-) I was thinking the same thing myself yesterday.

**Comment by scotthardwick** [comment]
Nigel,
That's awesome! Thanks for considering the enhancement!

I am curious, do you use any additional TODO extensions in your personal VSCode setup alongside the TODO Tree?  I have been using it paired with vscode-todo-highlight which gives extra highlighting to the words in the open editor window.
