### ISSUE TITLE
Independ color-setting for the markers

### ISSUE THREAD

**Issue by McPowerX** [Gruntfuggly/todo-tree#121]
Own, independ color-setting for the markers in the right gutter. I use Todos/fixme/notes with different background-color for better visibility. the foreground-color is always black. so in the gutter there are only black marks. It would be nice, to set the color for the marker independ from the other colors like:
"markerColor": "#09f"
or say from where the color to use e.g:
"markerColor": "background"
(possible values "background", "foreground", "icon")

**Comment by Gruntfuggly** [comment]
Good idea - I'll add it to the configuration. I'll add a choice of the three lanes too.

**Comment by Gruntfuggly** [comment]
Just uploaded a new version with "rulerColour" and "rulerLane" configuration.

**Comment by McPowerX** [comment]
This works so pretty nice! Thank you!
