### ISSUE TITLE
NOT highlight the tag

### ISSUE THREAD

**Issue by fengscript** [Gruntfuggly/todo-tree#123]
this extension is awesome, but I don't know whether it's a bug or sth I had a wrong configure, my tag like 
`// TODO 123`

NOT highlight in code file....

my defaultColor configure like this:
```json
  "todo-tree.defaultHighlight": {
    "icon": "alert",
    "type": "line",
    "foreground": "red",
    "background": "white",
  },
```

**Comment by nikhil93uf** [comment]
Yup. I am not noticing this too. All my custom highlights stopped working. This is only in v0.0.117. Reverting back to 0.0.116 fixed it for me

**Comment by Gruntfuggly** [comment]
Sorry - not enough testing! Should now be fixed...

**Comment by fengscript** [comment]
> Sorry - not enough testing! Should now be fixed...

Sorry I can't supply more detail info, but I can give you some message about my vscode with this bug:

```
Version: 1.31.0 (user setup)
Commit: 7c66f58312b48ed8ca4e387ebd9ffe9605332caa
Data: 2019-02-05T22:35:56.624Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
```

**Comment by Gruntfuggly** [comment]
Can you confirm if this is still a problem with version 0.0.118 of the extension?

**Comment by fengscript** [comment]
> Can you confirm if this is still a problem with version 0.0.118 of the extension?

YOU DIRTY BOY! It's WORKING now!!!
WHAT DID DO....
AWESOME!
