### ISSUE TITLE
Add word-boundary to regular expression

### ISSUE THREAD

**Issue by adityabhaskar** [Gruntfuggly/todo-tree#126]
Current Regex: `((//|#|<!--|;|/\\*|^)\\s*($TAGS)|^\\s*- \\[ \\])`

Proposed change: `((//|#|<!--|;|/\\*|^)\\s*($TAGS)\b|^\\s*- \\[ \\])`

Difference is the added `\b` after `($TAGS)`.

This makes sure stuff like `TodoFileName` doesn't get picked up as a task.

Thanks for the great extension.

Cheers!

Adi

**Comment by Gruntfuggly** [comment]
Hi - I added this the the last version, but unfortunately it seems to cause other people problems, so I've removed it again. Sorry!
