### ISSUE TITLE
Constant path errors in Windows version path must be of type string

### ISSUE THREAD

**Issue by crankedguy** [Gruntfuggly/todo-tree#128]
Hi,

I just installed a fresh copy of vscode yesterday and reinstalled my extensions. I did a system install, no user install.
Todo Tree does not work as I constantly get "The path argument must be of type string. Received type undefined".

My settings are nothing special at all
"todo-tree.customHighlight": {
        "TODO": {
            "type": "text",
            "background": "#80dfff",
            "foreground": "#000",
            "rulerColour": "#80dfff"
        },
        "FIXME": {
            "type": "text",
            "background": "#ff8553",
            "foreground": "#000",
            "rulerColour": "#ff8553"
        }
    },
    "todo-tree.statusBar": "total"

Can you please help on that? Thanks!

*EDIT* It seems to have something to do with the icons generation in the tree view as this error always occurs when refreshing. And there is only the file shown in the tree but no line with an icon or reference to the actual markup
Please help as this is a great addon otherwise

**Comment by Gruntfuggly** [comment]
Could you have a look in the console (Help->Toggle Developer Tools) and see if there is a call stack with the error?

**Comment by ghubusr01** [comment]
If I have no icons in the settings set I get the following error 
`notificationsAlerts.ts:38 Error: The "path" argument must be of type string. Received type undefined
	at assertPath (path.js:39:11)
	at Object.join (path.js:434:7)
	at Object.getIcon (C:\Users\Deus\.vscode\extensions\gruntfuggly.todo-tree-0.0.118\icons.js:48:37)
	at TreeNodeProvider.getTreeItem (C:\Users\Deus\.vscode\extensions\gruntfuggly.todo-tree-0.0.118\tree.js:386:43)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:469:761
	at t.asPromise (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:50:385)
	at new Promise (<anonymous>)
	at Object.t.asPromise (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:50:353)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:469:718
	at Array.map (<anonymous>)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:469:693`

And if  I set an icon with like "icon": "alert" you get the following error
`Error: The "path" argument must be one of type string, Buffer, or URL. Received type undefined
	at fs.mkdirSync (fs.js:867:3)
	at Object.exports.wrapFsWithAsar.fs.mkdirSync (ELECTRON_ASAR.js:727:16)
	at Object.getIcon (C:\Users\Deus\.vscode\extensions\gruntfuggly.todo-tree-0.0.118\icons.js:28:16)
	at TreeNodeProvider.getTreeItem (C:\Users\Deus\.vscode\extensions\gruntfuggly.todo-tree-0.0.118\tree.js:386:43)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:469:761
	at t.asPromise (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:50:385)
	at new Promise (<anonymous>)
	at Object.t.asPromise (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:50:353)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:469:718
	at Array.map (<anonymous>)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:469:693`

**Comment by Gruntfuggly** [comment]
I think this is similar to #99.  For some reason, `context.storagePath` is not defined, when according to the documents, should always exist. https://code.visualstudio.com/api/references/vscode-api#ExtensionContext

A temporary fix is to change all occurrences of `context.storagePath` to `context.extensionPath` in .vscode/extensions/Gruntfuggly.todo-tree-118.0.0/icon.js`

I'll add a permanent fix...

**Comment by ghubusr01** [comment]
oh yes, this indeed seems to work. thanks for the quick answer

**Comment by Gruntfuggly** [comment]
Could you try something? Instead of using `context.extensionPath` can you try `context.globalStoragePath`. I think there is a mistake in the documentation - but looking at what `globalStoragePath` seems to resolve too, I think it should always work.

**Comment by ghubusr01** [comment]
this seems to work, too. but with different behaviour. if aou use extension patch and use a "new" icon in the settings a file todo-<icon-name>.svg is created in the extension folder
if you use globalStoragePath i have yet to find where the icon then is :)

**Comment by ghubusr01** [comment]
oh yes, it is in C:\Users\<Username>\AppData\Roaming\Code\User\globalStorage\gruntfuggly.todo-tree\<svg-name> then

**Comment by Gruntfuggly** [comment]
The globalStoragePath is in the config for vscode - not too sure where that is on windows, but in linux it ends up in `.config/Code/User/workspaceStorage/<some hash>Gruntfuggly.todo-tree/` so I expect it will be somewhere similar

**Comment by Gruntfuggly** [comment]
Thanks - it might aswell use global storage anyway - it's just a cache for the icon files, so it would be the same in each workspace.

**Comment by ghubusr01** [comment]
no problem, ok then i leave it on global storage, too now, so the next update from you uses the same location
