### ISSUE TITLE
TODOs missing from explorer pane

### ISSUE THREAD

**Issue by onetrev** [Gruntfuggly/todo-tree#131]
Unfortunately this is a really random issue that is not chucking any errors in Developer Tools console... 

Basically Todo-Tree is only showing Todo's from a single file when scanning my project. Unless I open other files with Todos, they do not show up in my Todo list in explorer pane. However, once I close any of the other files with Todos and run "Refresh Todos" command, then the ones I opened disappear and again I'm back to just the Todos from the one file that seems to work.

But it's super random, I can mess around with Refreshing Todos, hitting it a bunch of times and then suddenly the other Todos show up. But then another Refresh and they are gone. Or sometimes when I open another file with Todos, **all the other** Todos in my workspace appear. But then a refresh and boom we're back to just the original Todos from just the one file.

NOTES: 
- All the files are within my current workspace.
- I have not enabled "Disable scanning of Workspace TODOs".
- I actually have tried messing around with this for quite some time to try and find something that triggers this -- because I know this issue sounds impossible to troubleshoot. :( Sorry. Anything I can do to assist I'm happy to do, including a screen recording cause this sounds crazy I know.

VSCode 1.31.1
Windows 10 Pro
Todo Tree 0.0.119

**Comment by Gruntfuggly** [comment]
Could you set `todo-tree.debug` to true and then restart. Once the extensions have all loaded, open the Output window (View->Output), and you should find an output window in the list called *Todo Tree*. Please attach the contents (unless it's immediately obvious what has gone wrong) so I can have a look.

**Comment by onetrev** [comment]
Awesome, can do. See attached. Thank you! I can't say for sure, but seems to be something with my SCSS file TODOs. Maybe it's just how it looks in the debug output, but they end up being crazy long.

[Todo Debug Output.txt](https://github.com/Gruntfuggly/todo-tree/files/2893669/Todo.Debug.Output.txt)

**Comment by Gruntfuggly** [comment]
Yes, it looks like it's finding them in your source map files, which don't have 'lines' (it looks like they're escaped), so it looks like one massive long line. You probably need to exclude them as it wouldn't be possible to generate a sensible TODO in the tree for them as there is no line number.

You can configure `todo-tree.excludes` to ignore files - I would try `**/*.map` and see it it helps.

**Comment by onetrev** [comment]
Thanks for the follow up! Unfortunately the same issue exists. But what's odd is I realise now there shouldn't be any `.map` files in there anyway. My entire distribution folder is excluded, `"**/dist/*.*"`. But just for testing I also excluded all map file too, and still in the debug output the map files are there. Odd right?

So as before, once we hit a `.scss` file with a TODO I don't see any more TODOs in my global list. If I remove the todo from the `.scss` file, then boom I get all the Todo's that follow that file (in other words, if there is a Todo in a PHP file that comes after the .scss file in my project folder structure then I now see it).

**Comment by Gruntfuggly** [comment]
Ah - I think I know what might be happening - the excludes are applied *after* the search because it's a lot simpler than trying to tell ripgrep what files to search. That means it still fails.

I'll add some exception handling and see if there is a way to tell ripgrep to limit the output in a more controlled way.

In the short term there are a bunch of options you can try passing to ripgrep using `todo-tree.ripgrepArgs`:

You could try:
`--max-columns 1000` 
`--max-filesize 1M`
`--null-data` (not sure if this will work with .map files though)

**Comment by Gruntfuggly** [comment]
Any luck? If the `max-columns` works, I think I'll add that as a configurable default...

**Comment by onetrev** [comment]
Heyo, sorry about the delay, caught up in a project. Did some testing, and ya `max-columns` works perfectly! Wicked stuff. Thanks!

**Comment by Gruntfuggly** [comment]
Added to the latest version.

**Comment by onetrev** [comment]
Hmm.... Well I just updated, removed the max-columns setting, but now I have no TODOs. At all. Bummer. Did a total removal of the extension folder and re-install, still nothing. Some other bug creep into the latest release? Hopefully nothing that will take more of your time.

**Comment by Gruntfuggly** [comment]
Can you try enabling the debug channel `todo-tree.debug` and see if there is anything in there? If it doesn't appear, or there is nothing in it, could you check the developer tools console?

**Comment by Gruntfuggly** [comment]
Ah - found it. The default regex was broken and I had it overridden (need to add more tests!).

**Comment by Gruntfuggly** [comment]
You can fix it temporarily by modifying the regex yourself in the .json file 
Change `\b` to `\\b`.
I'll fix it now though...

**Comment by onetrev** [comment]
Sure thing. Debug channel just says...
```Searching c:\websites\hmp\wp-content\themes\hmptheme...
Command: "c:\Users\xxxxx\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg.exe" --no-messages --vimgrep -H --column --line-number --color never --max-columns=1000 -e "((//|#|<!--|;|/\*|^)\s*(TODO|FIXME|BUG|HACK|NOTE)|^\s*- \[ \])" "c:\websites\hmp\wp-content\themes\hmptheme"
Found 0 items
Applying globs to 0 items...
Remaining items: 0
```

**Comment by Gruntfuggly** [comment]
Try the latest version - hopefully nobody else will notice :fearful:

**Comment by onetrev** [comment]
Haha, indeed. Good to go now though.
