### ISSUE TITLE
Extension host terminated unexpectedly.

### ISSUE THREAD

**Issue by plylrnsdy** [Gruntfuggly/todo-tree#132]
I open a workspace with 6 projects in vscode, and then vscode show a message: `Extension host terminated unexpectedly`.

```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```

```
1: node::DecodeWrite
 2: node::get_builtin_module
 3: v8::internal::FatalProcessOutOfMemory
 4: v8::internal::FatalProcessOutOfMemory
 5: v8::internal::Heap::MaxHeapGrowingFactor
 6: v8::internal::Factory::NewRawTwoByteString
 7: v8::internal::Smi::SmiPrint
 8: v8::internal::HashTableBase::NumberOfElements
 9: v8::internal::RegExpMatchInfo::ReserveCaptures
10: v8::internal::RegisterConfiguration::AreAliases
11: 0000000706E04481

<--- Last few GCs --->

[12704:000001781A99BB30]   396054 ms: Mark-sweep 1393.1 (1408.4) -> 1393.1 (1408.4) MB, 59.1 / 0.0 ms  allocation failure GC in old space requested
[12704:000001781A99BB30]   396111 ms: Mark-sweep 1393.1 (1408.4) -> 1393.1 (1402.9) MB, 56.3 / 0.0 ms  last resort GC in old space requested
[12704:000001781A99BB30]   396149 ms: Mark-sweep 1393.1 (1402.9) -> 1393.1 (1402.9) MB, 38.5 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0000000706E04481]
Security context: 000001C1F29A5709 <JSObject>
    1: trim(this=000003491E0CCEF1 <Very long string[679291966]>)
    2: formatResults(aka formatResults) [c:\Users\plylrnsdy\.vscode\extensions\gruntfuggly.todo-tree-0.0.119\ripgrep.js:25] [bytecode=00000086BE938FC9 offset=7](this=0000033EE4F022E1 <undefined>,stdout=000003491E0CCEF1 <Very long string[679291966]>)
    3: /* anonymous */ [c:\Users\plylrnsdy\.vscode\...
```

```
Extension host terminated unexpectedly. Code:  134  Signal:  null
```

Here is my configuration:
```json
    "todo-tree.defaultHighlight": {
        "foreground": "green",
        "type": "tag"
    },
    "todo-tree.customHighlight": {
        "TODO": {
            "iconColour": "green",
        },
        "FIXME": {
            "iconColour": "red",
        },
        "XXX": {
            "iconColour": "yellow",
        },
        "NOTE": {
            "iconColour": "grey",
        },
    },
    "todo-tree.excludeGlobs": [
        "**/node_modules/**",
        "**/out/**",
        "**/refs/**"
    ],
    "todo-tree.expanded": true,
    "todo-tree.tags": [
        "TODO",
        "FIXME",
        "XXX",
        "NOTE",
    ],
```

- VSCode User Setup 1.31.1
- Tode Tree 0.0.119

**Comment by Gruntfuggly** [comment]
It looks like your search is returning a huge amount of results. If you set `todo-tree.debug` to true and open the Todo Tree output window, you should see the command it generates for the search.
Can you try the search in a terminal window and see what happens?

**Comment by plylrnsdy** [comment]
I found workspace with repo:  [Full-stack-Blog](https://github.com/Sunshine168/Full-stack-Blog) (no install dependencies), and then vscode show `Extension host terminated unexpectedly.` or crash. 

Before crash:
```
Searching d:\Users\Desktop\Projects\.reference\node\Full-stack-Blog...
Command: "c:\Users\plylrnsdy\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg.exe" --no-messages --vimgrep -H --column --line-number --color never  -e "((//|#|<!--|;|/\*|^)\s*(TODO|FIXME|XXX|NOTE)|^\s*- \[ \])" "d:\Users\Desktop\Projects\.reference\node\Full-stack-Blog"
d:\Users\Desktop\Projects\.reference\node\Full-stack-Blog\README.md:42:1:TODO
```

**Comment by Gruntfuggly** [comment]
I cloned the repo and opened code, and it found the TODO:
![image](https://user-images.githubusercontent.com/376658/53342792-b7568b00-3906-11e9-89a4-48c9bc754c97.png)

Is there something else I need to do? 

It might be a similar problem to #131...

**Comment by plylrnsdy** [comment]
Screenshot:

![snipaste_2019-02-26_00-03-34](https://user-images.githubusercontent.com/18095255/53354843-a9365800-3962-11e9-9e9f-e664d3741bb7.png)

Simple statistics:

| date | projects                                                     | extensions    | vscode  | open other program<br/>(FireFox & ...) | error/test times |
| ---- | ------------------------------------------------------------ | ------------- | ------- | -------------------------------------- | ---------------- |
| 2/23 | 6                                                            | ?             | reload  | Yes                                    | all of ?         |
|      | 6                                                            | 1             | reload  | Yes                                    | 1/1              |
|      | 5                                                            | ?             | reload  | Yes                                    | 1/1              |
|      | 4                                                            | ?             | reload  | Yes                                    | 1/1              |
|      | 2                                                            | ?             | reload  | Yes                                    | 1/1              |
|      | 1 ([Full-stack-Blog](https://github.com/Sunshine168/Full-stack-Blog)) | ?             | reload  | Yes                                    | 1/1              |
| 2/24 | 4                                                            | 13            | restart | Yes                                    | 0                |
| 2/25 | 4                                                            | 13            | restart | Yes                                    | 0                |
| 2/26 | 4                                                            | 13            | restart | Yes                                    | 0                |
|      | 1 ([Full-stack-Blog](https://github.com/Sunshine168/Full-stack-Blog)) | 1 (todo-tree) | restart | Yes                                    | 0/1              |
|      | 6                                                            | 13            | restart | Yes                                    | 2/3              |
|      | 6                                                            | 13            | reload  | No                                     | 0/3              |

Output in normal situation:

![snipaste_2019-02-26_01-08-18](https://user-images.githubusercontent.com/18095255/53355031-1b0ea180-3963-11e9-9b53-ed31e1531112.png)

I found the extension match the files in `node_modules`, but I config that:

```json
"todo-tree.excludeGlobs": [
     "**/node_modules/**",
     "**/out/**",
     "**/refs/**"
],
```

Is it work normally?

- System: Windows 10 Pro
- Memory: 4GB

**Comment by Gruntfuggly** [comment]
When I tried the repo you linked, there was only one TODO found. How are you finding 507?

**Comment by plylrnsdy** [comment]
| date | projects                                                     | dir in node_modules | match | error |
| ---- | ------------------------------------------------------------ | ------------------- | ----- | ----- |
| 2/23 | 6                                                            | 72 + 1095 + 502     |       | Yes   |
|      | 1 ([Full-stack-Blog](https://github.com/Sunshine168/Full-stack-Blog)) | 0                   | 1     | Yes   |
| 2/26 | 1 ([Full-stack-Blog](https://github.com/Sunshine168/Full-stack-Blog)) | 0                   | 1     | No    |
|      | 6                                                            | 72 + 1095 + 502     | 507   | No    |

I also found one TODO in the repo [Full-stack-Blog](https://github.com/Sunshine168/Full-stack-Blog) in 2/26, but vscode will go wrong in 2/23 before it reports how many TODO found.

Maybe vscode found too much TODO in `node_modules` and my computer memory not enough.

**Comment by Gruntfuggly** [comment]
Could you try passing one of the arguments I've suggested in #131 - and see if that helps?

**Comment by Gruntfuggly** [comment]
Hi - did you have any luck with the ripgrep arguments?

**Comment by Gruntfuggly** [comment]
I've added a default value for max-columns in the latest version, which should help with this.

**Comment by plylrnsdy** [comment]
I use it with fewer projects, and it not crashes any more.
