### ISSUE TITLE
Don't use `new vscode.Uri.file`

### ISSUE THREAD

**Issue by jrieken** [Gruntfuggly/todo-tree#133]
The `vscode.Uri.file`-function is a static member of the `Uri`-class. Calling it with `new` was only possible because vscode used to compile its TypeScript sources to ES5, not ES6. Now calling a static class function using the `new`-keyword isn't possible anymore and results in an error ([Microsoft/vscode#69533](https://github.com/Microsoft/vscode/issues/69533)).

Please update and use `vscode.Uri.file` without the `new` keyword.

Thanks and HappyCoding!

**Comment by Gruntfuggly** [comment]
Fixed in the latest version.
