### ISSUE TITLE
[Feature Request] Add filename macro

### ISSUE THREAD

**Issue by lonix1** [Gruntfuggly/todo-tree#134]
Please add `${filename}` macro, so we can do something like this:

````
"todo-tree.labelFormat": "[${filename}] ${after}"
````

Which would work well when tags are grouped:

````
TODO
  [foo.ts] Some text
  [foo.component.ts] Some text
  [bar.ts] Some text
FIXME
  [foo.ts] Some text
  [foo.component.ts] Some text
  [bar.ts] Some text
````

**Comment by Gruntfuggly** [comment]
This probably only makes sense in 'tags only' view because the filename would normally be a parent node, but it makes sense if you want a very flat view.

**Comment by lonix1** [comment]
Yep that's exactly how I'm doing it
I find the default view is too noisy
The only thing missing from a "clean" view is the filename

**Comment by Gruntfuggly** [comment]
Added to the latest version.

**Comment by lonix1** [comment]
Awesome!
