### ISSUE TITLE
Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by Venryx** [Gruntfuggly/todo-tree#135]
I'm getting the following error when enabling TODO Tree in one of my projects:
![](https://i.imgur.com/jkARH3j.png)

Text version:
```
Extension Host
extensionHost.ts:232 Node.js[5760]: d:\_vsts\3\s\vendor\node\src\node_buffer.cc:415: Assertion `length <= kMaxLength' failed.
	extensionHost.ts:231 Extension Host
	extensionHost.ts:232
		1: node::DecodeWrite
		2: node::DecodeWrite
		3: node::Buffer::New
		4: v8::internal::compiler::Type::Any
		5: icu_60::RegexMatcher::regionEnd
		6: uv_pipe_connect
		7: uv_dlerror
		8: uv_run
		9: 00007FF638EB4C69
		10: 00007FF638EB3AA9
		11: IsSandboxedProcess
		12: BaseThreadInitThunk
		13: RtlUserThreadStart

extensionService.ts:457 Extension host terminated unexpectedly. Code:  134  Signal:  null
	t._onExtensionHostCrashed @ extensionService.ts:457
	(anonymous) @ extensionService.ts:451
	e.fire @ event.ts:567
	t._onExtHostProcessExit @ extensionHost.ts:487
	(anonymous) @ extensionHost.ts:246
	emit @ events.js:182
	ChildProcess._handle.onexit @ internal/child_process.js:237

notificationsAlerts.ts:40 Extension host terminated unexpectedly.
```

I know it's caused by this extension because it goes away when I disable it. Also, the error shows shortly after the "TODO Tree: scanning" message shows in status-bar.

An important thing to note is that the error is only occurring in one of my projects. I will move folders/files out and try to find what file specifically is causing todo tree to break.

**Comment by Venryx** [comment]
Okay, found the issue. The extension is just failing on a really large file in my project: `app.js.map`

It is 13.7mb in size. The error occurs when opening an otherwise empty folder, containing just that one file. (does not occur when opening just the file directly, as todo-tree seems to only activate when vscode opens a project/folder)

So the solution would seem to be, have todo-tree cancel scanning of any files that are over 10 or 12 mb in size. (it doesn't break on `app.js` which is 12.6mb)

**Comment by Gruntfuggly** [comment]
Yes, this is the same problem as in previous issues. In the short term you can add a parameter to `ripgrepArgs` as per here https://github.com/Gruntfuggly/todo-tree/issues/131#issuecomment-467349830

I've got a change ready which sets the max-columns by default which should hopefully stop it happening in the future.

**Comment by Gruntfuggly** [comment]
I've just uploaded the update. Let me know if it works.

**Comment by Venryx** [comment]
It seems to have fixed it, yes. I'll let you know if it comes up again.
