### ISSUE TITLE
group tags for list/treeview

### ISSUE THREAD

**Issue by Somberland** [Gruntfuggly/todo-tree#136]
would love to see a "tagGroup"-feature to group tags with different writing-style or for different languages by one "main"-tag.

![bildschirmfoto 2019-03-07 um 10 47 29](https://user-images.githubusercontent.com/5808345/53949567-97735400-40ca-11e9-9c41-69a714439b9d.png)

Something like this (the group **TODO** will show all tags with _TODO_, _todo_ etc.):
```
"todo-tree.tagGroups": {
	"TODO": [
		  "TODO", 
		  "@TODO", 
		  "@todo", 
		  "todo"
		  ],
	"FIXME": [
		  "FIXME", 
		  "@FIXME",
		  "@fixme",
		  "fixme"
		  ]
	}
```

**Comment by Gruntfuggly** [comment]
You could get closer to this by disabling `todo-tree.regexCaseSensitive`. Does the `@` need to be part of the tag, or could you modify the regex to have the `@` optional in the earlier part of the regex?

**Comment by Somberland** [comment]
Thanks for the reply. "fixed" it via `((\/\/|#|\\{\\{!--|<!--|;|/\\*|^)\\s*(?:@|\\s)?($TAGS)|^\\s*- \\[ \\])` to prevent some false-positives / broken `${after} `.

Hopefully soon we can use *empty sub-expressions* with *ripgrep* :)

**Comment by Gruntfuggly** [comment]
Nice regex skills!

If ripgrep gets updated, you can tell the extension to use your own installation if you want.
