### ISSUE TITLE
No longer matching "TODO:" and "FIXME:"

### ISSUE THREAD

**Issue by garu57** [Gruntfuggly/todo-tree#138]
I have a project where  the keywords `TODO` and `FIXME` are mentioned many times in included doc so, since as far as I know colon has no special meaning in regex'es, to avoid false positives I set tags like this:
```
    "todo-tree.tags": [
        "TODO:",
        "FIXME:",
        "LOOK:",
    ],
```

It has always worked without problems at least since version 0.0.94 that was when I started using it, but today i reopened the project and tags with colon are no longer matching.

It was since November or December last year that I wasn't working on that project so I don't know exactly in which version it stopped working.

**Comment by garu57** [comment]
I saw that the problem happens only if I append the colon to the letters. If I prepend it like this `:TODO` it is correctly matched.

**Comment by garu57** [comment]
I dont know if this is related to #126, but considering the regex expression:
`"todo-tree.regex": "((//|#|<!--|;|/\\*|^)\\s*($TAGS)\\b|^\\s*- \\[ \\])"`
I saw that there are two ways to restore the old behavior
- remove the word boundary flag `\\b` after `($TAGS)` **or**
- write tags like this
```
    "todo-tree.tags": [
        "TODO: ",
        "FIXME: ",
        "LOOK: ",
    ],
```
Sincerely i do not understand yet why forcing tags matching on word boundary has problems with colon. May be that the colon, being it a punctuation, is not considered part of a word, but then why if I put a space after it, is it matched?

**Comment by garu57** [comment]
After further tests, removing the word boundary constraint `\b` restores exactly the previous behavior, ie 
`// TODO:` (without blank) immediately triggers the match.

Putting a blank in the  tag definition like `"TODO: "`, does not match  `// TODO: ` (the tag is followed by a blank).
To trigger the matching, the blank must be followed by at least one character like  `// TODO: a` .

**Comment by garu57** [comment]
I think that `\b` is too much restrictive.
```
\b    a Unicode word boundary (\w on one side and \W, \A, or \z on other)
```
Could instead be possible to let use regex flags in tags declaration so that one can use `"TODO\\b"` if he doesn't want to match `todoFile` or `"TODO:"` if he wants to include punctuation in tags definition, which by the way also avoids matching `todoFile`?

**Comment by Gruntfuggly** [comment]
Thanks for the detailed report - looks like you're right about `\b` being too restrictive.

I probably shouldn't have added `\b` to the default regex. Everybody needs something different, which is why it's configurable. I normally resist changing it, but in this case it seemed reasonable.

I'll remove it in the next version. From now on, I'm only going to change the default regex if there are errors...

**Comment by Gruntfuggly** [comment]
I've removed the work boundary from the default regex.
