### ISSUE TITLE
Add `/*`

### ISSUE THREAD

**Issue by doogood** [Gruntfuggly/todo-tree#14]
Hello :) Thank you for the very useful extension! 
I wanted to suggest add symbols `/*` in the new version. 
The symbols `/* */` are comments in CSS-files. And TODO-TREE doesn't see them. 
I already added them in my settings:
`"todo-tree.regex" :  "(//|#|<!--|;|/*)\\s*(TODO|FIXME|NOTE)"`
I think it will be useful, that people don't search solution to this problem. 
![settings json - - visual studio code_2018_04_08 18 06 16](https://user-images.githubusercontent.com/36864125/38469087-c495bf6e-3b57-11e8-84f3-9b72893d19f4.jpg)
![settings json - - visual studio code_2018_04_08 18 06 33](https://user-images.githubusercontent.com/36864125/38469085-babd9bec-3b57-11e8-9ca8-41350beb9e81.jpg)

**Comment by Gruntfuggly** [comment]
Hi - thanks for the suggestion. I originally didn't want to put too many defaults into the regex as I feel it could be a never ending task, but as I have already included the HTML comment, it does make sense to include the CSS comment. 8-)

**Comment by Gruntfuggly** [comment]
I've added /* comments to the latest version. 8-)

**Comment by doogood** [comment]
Thank you :-)

2018-04-26 16:35 GMT+03:00 Nigel Scott <notifications@github.com>:
