### ISSUE TITLE
Multiline TODOs

### ISSUE THREAD

**Issue by Thiht** [Gruntfuggly/todo-tree#140]
Hi, great work with this extension :)

I noticed a tweet from Intellij showing how they handle multiline TODOs: https://twitter.com/intellijidea/status/1107664485177794560

Is there any chance for supporting something like this in todo-tree?

FWIW, ripgrep now supports multiline matching, I think it prevented adding a similar feature in the past

**Comment by Gruntfuggly** [comment]
Do you just want to grab the entire text of the todo for showing in the tree, or is just for the highlighting?

**Comment by Gruntfuggly** [comment]
Ah OK - I'll see what I can do. Multipline might be possible, depending on the output of ripgrep.

**Comment by CristoAMH** [comment]
I would love this feature @Gruntfuggly . There is no news about this, right?

**Comment by Gruntfuggly** [comment]
@CristoAMH - I'm trying to get something working at the moment. Hopefully not too long. :grin: 

@Thiht - do you have a regex that finds your multiline todos?

**Comment by Thiht** [comment]
@Gruntfuggly You could try something like this (simplified version with only the `//` comments and only the `TODO` keyword): `//\s*TODO.*(\n//\s{2,}.*)+`

The important part would be the `(\n//\s{2,}.*)+`, which matches a line break, a `//`comment (note this doesn't work for other comment styles), at least 2 whitespaces (this is to match Intellij's behavior which is nice), some text, and repeat

Feel free to ping me if you need help making the regex prod ready with support for other comments styles :)

**Comment by Gruntfuggly** [comment]
OK - I've been using something very similar. It finds the matches OK. The problem at the moment is working out that the results are part of the same todo.

Thanks for the offer of help with the regex. At the moment, I think it may be simplest to add the support for decoding the results as multiline TODOs, but leaving the standard regex as it is. If people want to use multiline TODOs, they'll have to set up the regex themselves (I'm planning to add a bunch of examples to a wiki page), as it will be easier than trying to cope with different comment styles.

**Comment by Thiht** [comment]
> The problem at the moment is working out that the results are part of the same todo.

This is why Intellij requires using 2 spaces at the start of the lines after the first one. It's not very pretty but clever 

>Thanks for the offer of help with the regex. At the moment, I think it may be simplest to add the support for decoding the results as multiline TODOs, but leaving the standard regex as it is. If people want to use multiline TODOs, they'll have to set up the regex themselves (I'm planning to add a bunch of examples to a wiki page), as it will be easier than trying to cope with different comment styles.

Sounds like a good alternative for now! Do you think it would be possible to have the alternative regexes directly in the Settings of VSCode (with a dropdown or something like that)?

**Comment by Gruntfuggly** [comment]
> Do you think it would be possible to have the alternative regexes directly in the Settings of VSCode (with a dropdown or something like that)?

I don't think that's possible with the current settings API. I could add a command which allows selection from predefined regexs?

**Comment by Gruntfuggly** [comment]
New version supports multiline TODOs. Let me know if you find any issues.

https://github.com/Gruntfuggly/todo-tree#multiline-todos

You'll still need to configure your own regex, but it should detect multiline automatically.

**Comment by emme1444** [comment]
Hi @Gruntfuggly, great work on this extension!

I was playing around modifying the regex string `((//)\s*($TAGS).*(\n\s*//(\s{3,}|\s\t+|\t+\s).*)*)` that @Thiht suggested. I was wondering if there are anyway to remove the slashes, and maybe the whitespace on the lines from the trailing multiline comments from the output. Basically, these: 
![an illustration of the problem I want alleviate](https://i.ibb.co/N65j2Cg/Screenshot-2020-04-12-at-21-15-53.png)

If there are anyone skilled enough to come up with a regex that fits, or maybe there just needs to be some modification of the code for the extension, that would be awesome either way!

If you want me to create a new Issue for this (which I probably should have) let me know, and I'll fix that immediately!  

Thanks!

**Comment by Gruntfuggly** [comment]
The next version will remove leading comments from multiline todos.

**Comment by Gruntfuggly** [comment]
The latest version should now strip the comments. Please let me know if it works as expected.
