### ISSUE TITLE
[WIKI REQUEST] add a list of all available icons

### ISSUE THREAD

**Issue by norilt** [Gruntfuggly/todo-tree#141]
I installed your extension and it's very nice! I just wanted to configure it and saw that you can choose between different icons. But I didn't found a list which icons are available (issues and readme). So far I found:
- breaker
- bug
- tick
- alert

Are there more? A list in the README like the one of the colors would be nice.

**Comment by Gruntfuggly** [comment]
The available icons are the https://octicons.github.com/ set. The readme does say that it needs to be a valid octicon, but you're right that a link to the set would be useful.
