### ISSUE TITLE
Unable to detect TODOs in Ocaml Files

### ISSUE THREAD

**Issue by varunpatro** [Gruntfuggly/todo-tree#143]
Hello,

OCaml and other ML languages use `(* comment *)` style comments. I believe this extension is unable to pick up comments that are enclosed in such comment blocks.

**Comment by Gruntfuggly** [comment]
You'll need to modify the regex - try something like this:

`((//|#|<!--|;|/\*|^|\(\*)\s*($TAGS)|^\s*- \[ \])`

I added `|(\*` in the first group, so it finds TODOs like:

![image](https://user-images.githubusercontent.com/376658/54811784-5f9b0d80-4c81-11e9-841d-26ffcfe3352c.png)
![image](https://user-images.githubusercontent.com/376658/54811809-7477a100-4c81-11e9-9042-2ee087a928e0.png)

I don't think that the block comment detection supports ocaml at the moment. I'll see if I can add it...

**Comment by varunpatro** [comment]
> You'll need to modify the regex - try something like this:

> ((//|#|<!--|;|/\*|^|\(\*)\s*($TAGS)|^\s*- \[ \])

Thanks! Would it be okay if you add this to the default regex? So other users can also benefit without any extra configs?

**Comment by Gruntfuggly** [comment]
The last time I updated the default regex it broke for some other users, so I am trying to avoid it. 

However, there are quite a few things that would be useful for people to know, so I'm going to add a wiki with some other example regexes - I'll add this one to it.
