### ISSUE TITLE
[feature request] "showInExplorer" for certain tags

### ISSUE THREAD

**Issue by RayPS** [Gruntfuggly/todo-tree#144]
I really love the highlighting feature, but sometime I don't want certain tags like a serious comment be listed in the tree, grouping and filtering does not help.
```diff
  "todo-tree.customHighlight": {
      "[?]": {
          "foreground": "black",
          "iconColour": "yellow",
+         "showInExplorer": false
      }
  }
```

**Comment by Gruntfuggly** [comment]
To clarify - you want the highlight in the editor,  but *not* the entry in the tree view?

**Comment by RayPS** [comment]
That's correct

**Comment by Gruntfuggly** [comment]
I've added the option 'hideFromTree'. Let me know if it does what you need.

**Comment by RayPS** [comment]
Awesome!
