### ISSUE TITLE
todo-tree: regex parse error if i add tag "?"

### ISSUE THREAD

**Issue by okerivy** [Gruntfuggly/todo-tree#146]
If I want to add a tag like this, To match such comments
`//?` or `//*` or `//!`
But the match is incorrect.

```
"todo-tree.tags": [
        "TODO",
        "FIXME",
        "?",
        "!",
        "*",
    ],
```

```
todo-tree: regex parse error:
 ((//|#|<!--|;|/\*|^)\s*(TODO|FIXME|?|!|*)|^\s*- \[ \]) ^ 
error: repetition operator missing expression
```

Thanks in advance

**Comment by Gruntfuggly** [comment]
Hi - this is a bit tricky because the characters you're trying to match are special characters for the regex. The extension normally tries to do something sensible when it constructs the regex, but in this case the only way I could get it to work, was to set the regex to this:
```
"todo-tree.regex": "(//)\\s*(TODO|FIXME|\\?|!|\\*)"
```
which then ignores the *tags* setting for the search.
The highlights should still work if you set tags to 
```
"todo-tree.tags": [
        "TODO",
        "FIXME",
        "\\?",
        "!",
        "\\*",
    ]
```

**Comment by okerivy** [comment]
Thank you

Because I don't want to match three or four / , for example `/// TODO` 
so I changed this expression , added one `([^/]|^)`

If i use this regular expression,
`"todo-tree.regex": "(([^/]|^)//)\\s*(TODO|FIXME|\\?|!|\\*)",`

Then it will match `a// TODO`, this is correct, but I just want `// TODO` to be highlighted, not to make `a` highlight

You can see the results of the match.
https://rubular.com/r/0Dph8Ull51QS1L

----

If I changed this expression , added one `(?<!/)`
If I use this regular expression,
`"todo-tree.regex": "(?<!/)(//)\\s*(TODO|FIXME|\\?|!|\\*)"`

Good, This matches the results I want.
This regex is available at: https://rubular.com/r/U0hIX1O2uGUA0e

But In macos vscode , here will give an error

```
todo-tree: regex parse error:
    (?<!/)(//)\s*(TODO|FIXME|\?|!|\*)
    ^^^^
error: look-around, including look-ahead and look-behind, is not supported

Consider enabling PCRE2 with the --pcre2 flag, which can handle backreferences
and look-around.
```
This error at this link
https://github.com/Microsoft/vscode/issues/60553

----

I sincerely need your help, thank you

**Comment by Gruntfuggly** [comment]
Can you try adding '--pcre2' flag to `todo-tree.ripgrepArgs` and see if it works?

**Comment by okerivy** [comment]
Perfect work, thank you

The final configuration is
```
"todo-tree.tags": [
        "TODO",
        "FIXME",
        "\\?",
        "!",
        "\\*"
],

"todo-tree.ripgrepArgs": "--max-columns=1000 --pcre2",
"todo-tree.regex": "(?<!/)(?:([^/]|^)//)(?:(\\s*(TODO|FIXME))|(?:(\\?|!|\\*)\\s+))",
```

**Comment by okerivy** [comment]
Found that if you modified "todo-tree.regex"
Inside the code `// TODO` is not highlighted
Looking for a long time, found that the problem is `0.0.127`, restore to `0.0.126` just fine
`0.0.127` There may be some problems, please take a look  : )

**Comment by unai-ndz** [comment]
Can confirm, `0.0.126` works fine but `0.0.127` doesn't highlight anything depending on what changes I make to the regex. Adding `--` like this `(//|#|<!--|;|/\\*|^|--)` is fine but for example replacing `$TAGS` with `TODO` brokes it.

**Comment by Gruntfuggly** [comment]
127 added multiline TODO support, so it might have affected the regex. I'll investigate...

**Comment by Gruntfuggly** [comment]
Please can you post your current regex and an example of something it should match.

**Comment by unai-ndz** [comment]
Just to confirm, they appear on the tree but they are not highlighted in the editor. 

```json
"todo-tree.tags": [
  "TODO",
  "FIXME",
  " !",
  " \\?",
  " \\^",
  " \\*",
],
"todo-tree.regex": "((//|#|<!--|;|/\\*|^|--)\\s*(TODO|FIXME| !| \\?| \\^| \\*)|^\\s*- \\[ \\])",
```

```
// TODO: Some comment
// ? Some comment
// ^ Some comment
// * Some comment
```

**Comment by Gruntfuggly** [comment]
I found the problem - please try the latest version and let me know if it works again.

**Comment by unai-ndz** [comment]
No, I still can't get it to work.

**Comment by Gruntfuggly** [comment]
That's odd - if I used your regex and the sample code, they got highlighted. What value to you have for `todo-tree.defaultHighlight` ?

**Comment by unai-ndz** [comment]
You are right. Using `todo-tree.defaultHighlight` works, I was trying with this:
```
"todo-tree.customHighlight": {
        "TODO": {
          "icon": "alert",
          "type": "tag",
          "foreground": "yellow",
          "background": "#00000",
        },
        " \\?": {
          "icon": "alert",
          "type": "tag",
          "foreground": "black",
        },
```
And neither of them get highlighted. Using `" ?": {` on the other hand works but of course highlighting every tag while the simple TODO tag doesn't highlight anything.

**Comment by Gruntfuggly** [comment]
With your config above, for me, it partially works - the icon for example is being set. I'll see if I can work out what's going on with the colours...

**Comment by Gruntfuggly** [comment]
Argh. I made a stupid mistake in the last change - please try the latest version.

**Comment by unai-ndz** [comment]
Thanks a lot. Tested it lightly and is working as expected.
