### ISSUE TITLE
Toggle button for showing tags only from open files?

### ISSUE THREAD

**Issue by acdha** [Gruntfuggly/todo-tree#147]
I love having `todo-tree.showTagsFromOpenFilesOnly` from #31 available to stay focused on big projects but it'd be really nice if there was a UI toggle for it so I could have that on by default but easily see everything without having to change my settings.

**Comment by Gruntfuggly** [comment]
Would this be easier as a button on the status bar, or a button on the tree view title?

**Comment by acdha** [comment]
I had been thinking about a button in the row with the collapse & ordering options since I think of it as a filtering operation.

**Comment by Gruntfuggly** [comment]
OK - got any ideas for what icon to use? I'm struggling to think of one! 😁

**Comment by acdha** [comment]
Good question — I wanted to use the filter icon but that's already taken. I'm wondering whether it should just be a toggle between the [file-directory](https://octicons.github.com/icon/file-directory/) and [file](https://octicons.github.com/icon/file/) icons (although I really would like a multi-file icon for that).

**Comment by Gruntfuggly** [comment]
How about the [file-submodule](https://octicons.github.com/icon/file-submodule/) and the [browser](https://octicons.github.com/icon/browser/) icons?

**Comment by acdha** [comment]
Sure — I think with a tooltip it'll be discoverable enough that people will learn to recognize just about anything.

**Comment by Gruntfuggly** [comment]
I've added it to the latest version - you need to set `todo-tree.showScanOpenFilesOrWorkspaceButton` to enable the button. I've disabled it by default because the button bar is getting a bit crowded - I think I'll add an option to allow more of the buttons to be configurable...

**Comment by acdha** [comment]
Awesome, thanks!

**Comment by acdha** [comment]
The only downside I see is that if you click that button when no files are open the entire Todos section of the explorer goes away but it's also not hard to open something and get it back.

**Comment by Gruntfuggly** [comment]
You can also use the dedicated tree view from the *View->Open View...* command.

I could add an option to prevent the tree view from being hidden if it's empty. The nicest thing would be if vscode had an API to allow the view to be expanded/collapsed.

**Comment by acdha** [comment]
Yeah, I wouldn't worry about it

**Comment by acdha** [comment]
@Gruntfuggly this reminded me: thanks, this has been working great!

**Comment by Gruntfuggly** [comment]
LMK if the disappearing tree ever becomes a problem. :smiley:
