### ISSUE TITLE
[Feature Request] Support non-word keywords

### ISSUE THREAD

**Issue by lonix1** [Gruntfuggly/todo-tree#148]
I would like to highlight a todo list within my code, e.g.:

````
// [x] this needs to be done           <--- done: shown in green
// [ ] this needs to be done           <--- not done: shown in red
// [ ] this needs to be done
````

So I created entries in my config for `[ ]` and `[x]`.

But that doesn't work. Those lines in my code do not get highlighted, not do they appear in the sidebar.

**Comment by Gruntfuggly** [comment]
You can get these to show up in the tree by modifying the regex something like:
`"todo-tree.regex": "((//|#|<!--|;|/\\*|^)\\s*($TAGS)|^//\\s*\\[x\\]|^//\\s*\\[ \\])"`

Highlighting them in different colours will be more tricky...

**Comment by lonix1** [comment]
The highlighting would be the killer feature, whereas the tree is a nice to have but not that important.

So... "tricky" as in it's unsupported, or as in the regex involved would be messy?

**Comment by Gruntfuggly** [comment]
It should be as easy as adding "[ ]" and "[x]" to the tags, but there will need to be some escaping and stuff. I think it's partially handled already, but I'll investigate...

**Comment by Gruntfuggly** [comment]
You can set the colours like this:
```
    "todo-tree.customHighlight": {
        "\\[x\\]":{
            "background":"#008800"
        },
        "\\[ \\]":{
            "background":"#ff0000"
        }
    }
```

**Comment by lonix1** [comment]
Thanks for looking into this!

I edited my config to include this:

````json
// from your comment at the top of the page:
"todo-tree.regex": "((//|#|<!--|;|/\\*|^)\\s*($TAGS)|^//\\s*\\[x\\]|^//\\s*\\[ \\])",

// from your new comments:
"todo-tree.tags": [
  "\\[x\\]",
  "\\[ \\]",
],
"todo-tree.customHighlight": {
  "\\[x\\]":{
    "background":"#008800"
  },
  "\\[ \\]":{
    "background":"#ff0000"
  },
}
````

**The result is the highlighting works... awesome!**

But the downside is that the todo tree in the panel is now very weird, it adds the entries in-between other stuff, quite a mess. I guess the regex is the cause for that.

**Comment by Gruntfuggly** [comment]
Can you take a screenshot? It seemed OK for me. I think the problem is the `|^` in the regex. Can you try removing it?

**Comment by lonix1** [comment]
## Background
I don't have a screenshot tool on linux, but it's quite simple so I'll type it out.

My config includes these lines:
````
"todo-tree.labelFormat": "${filename} | ${after}",
"todo-tree.excludeGlobs": [".git/**", "**/node_modules/**", ".vscode/**", "settings.json"],
"todo-tree.regex": "((//|#|<!--|;|/\\*|^)\\s*($TAGS)|^//\\s*\\[x\\]|^//\\s*\\[ \\])",
````

## Failing example
Suppose the file `Controller.cs` has these:
````csharp
// [x] foo
// [ ] bar
````

Then the sidebar looks like this (nodes are collapsed):

````
> BUG 2
settings.json | //\\s*\\[\\])",       <--- it picked up the regex line from settings.json
> HACK 3
Controller.cs | foo                   <--- ?
Controller.cs | bar                   <--- ?
settings.json | //\\s*\\[x\\]|^       <--- it picked up the regex line from settings.json
> REFACTOR 12
> TODO 25
````

## Notes
Problems:
- the regex should not cause the `settings.json` file to appear in the sidebar... and strangely enough, I excluded it in the config (see above)
- the `[ ]` and `[x]` appear in the sidebar but not under a node
- every time I resave/refresh, those erroneous items *move up and down the list* - they don't appear in a predictable location within the list

**Also - please don't waste time on this unless others complain! All I wanted was highlighting in the documents, and now that I have that I'm very happy! :smile:**

**Comment by Gruntfuggly** [comment]
That's weird - if I set it up the same here it seems to work fine!?

Can you attach the output from the debug window? Set `todo-tree.debug:true` and select "Todo Tree" from the dropdown in the Output view.

**Comment by lonix1** [comment]
The logs don't seem to have any errors in them. Just many lines with `Match: {"file":....`.

But anyway I don't want to waste your time any more! :smile: If it works for you then there must be a conflict on my system with other addons, or something like that.

Maybe we could revisit this if more people have this problem?

Gonna close until then... Thank you for helping me with the regex, that was the bit that really helped - and thanks for this awesome extension!

**Comment by Gruntfuggly** [comment]
There may not be an erorrs, but the log entries starting with `Match: {"file":...` would be useful if you still have them, as they describe the entry being extracted and inserted into the tree. I could also populate my tree from your results.

I'm happy to continue looking at it as there may be an underlying problem.

**Comment by lonix1** [comment]
I don't know what changed between back then and now, but it now works flawlessly.

You might want to add it to the docs, as it's very useful. It makes it so easy to have markdown-style checklists with coloring!

Thanks for this great extension.

**Comment by Gruntfuggly** [comment]
OK - there have been quite a few bug fixes and improvements since this issue cropped up, so hopefully it's been fixed by accident along the way.

I'll add your config to the wiki - thanks!
