### ISSUE TITLE
Default filter

### ISSUE THREAD

**Issue by abrunenko** [Gruntfuggly/todo-tree#149]
Add option for default filter? Currently i changed function clearFilter... :)
```
function clearFilter()
{
    currentFilter = 'default_filter';
    context.workspaceState.update( 'filtered', true );
    provider.filter( currentFilter );
    refreshTree();
}
```

**Comment by Gruntfuggly** [comment]
How would you use it? Would it be instead of "no filter"?

**Comment by abrunenko** [comment]
I'm working on a big project and have a lot of TODO from different people. I would like to filter only my own. But unfortunately filter is not saved when reopen the editor.

**Comment by Gruntfuggly** [comment]
Ah OK - saving the filter was one of the things on my list that I keep forgetting to do.

**Comment by Gruntfuggly** [comment]
New version should now retain the filter between runs.

**Comment by abrunenko** [comment]
Oh! You're the best!!! Saving works great! Thanks:)
