### ISSUE TITLE
Add GitHub Markdown tasks

### ISSUE THREAD

**Issue by leejoramo-d51** [Gruntfuggly/todo-tree#15]
Provide support for [GitHub flavored Markdown tasks](https://blog.github.com/2014-04-28-task-lists-in-all-markdown-documents/). The current todo-tree regex can be changed to:

`"todo-tree.regex": "((//|#|<!--|;)\\s*(TODO|FIXME)|^\\s*- \\[ \\])",`

Elsewhere you have commented that you prefer not to add too many defaults in the regex. I understand this feeling. I do think that Markdown tasks are widely used, and it would be a good thing to document how to add support. Many people (even long time programmers) don't understand regular expressions.

**Comment by Gruntfuggly** [comment]
The latest version now supports markdown tasks. 8-)

**Comment by samael205** [comment]
¿How does work this functionality?

**Comment by Gruntfuggly** [comment]
If you include 
` - [ ] <some text>`
in your files it will show up in the TODOs tree. (note the space before the dash and inside the square brackets).
It doesn't do anything clever. If you put an 'x' in between the square brackets to show the task is complete, it won't find the TODO anymore (once the file is saved).

**Comment by samael205** [comment]
It is a very good functionality for .md files. Great!
