### ISSUE TITLE
todo tree is broken if new lines are before a task

### ISSUE THREAD

**Issue by alexwall** [Gruntfuggly/todo-tree#150]
![C6165BB4-762C-4E2F-8138-AEE075D076DD](https://user-images.githubusercontent.com/316469/56291118-ef1ec980-6124-11e9-8bc1-f036c19ee378.png)

Here the example file:

```markdown
# Headline

- [ ] task 1
- [ ] task 2




TODO: task a
TODO: task b
```

**Comment by Gruntfuggly** [comment]
Hi - I have a fix for this if you want to try it before I update the extension:

Edit `.vscode/extensions/gruntfuggly.todo-tree-0.0.128/extension.js`

and add 
`match[ 0 ] = match[ 0 ].substring( 1 );`
at line 453, like this:

```
while( text[ match.index ] === '\n' || text[ match.index ] === '\r' )
{
    match.index++;
    match[ 0 ] = match[ 0 ].substring( 1 );                                                                 
}
```

**Comment by alexwall** [comment]
Hi, 

it was actually the extension version `0.0.129` i.e. `.vscode/extensions/gruntfuggly.todo-tree-0.0.129/extension.js` but yes, it fixed the problem!

Thanks, I'd be happy to see this fix in the next version asap

**Comment by Gruntfuggly** [comment]
Great - thanks for confirming. There should be a new version today.

**Comment by alexwall** [comment]
Hi @Gruntfuggly,

Did you postpone the release? The extension version is still at `0.0.129` in vscode 

Best 
Alex

**Comment by Gruntfuggly** [comment]
Hi - yes, sorry. Things got on top of me over the weekend. There's a few more changes to add, so it will be in the next few days now.

**Comment by Gruntfuggly** [comment]
Just uploaded a new version including the fix.
