### ISSUE TITLE
New Ideas

### ISSUE THREAD

**Issue by Highter87** [Gruntfuggly/todo-tree#154]
1. Ability to create a task in Trello. Select item, right menu button -> "create a task in Trello"
2. Select item, right menu button -> "remove item". Delete comment in code

**Comment by Gruntfuggly** [comment]
Hi - how would it be able to create a task in trello? Wouldn't it need account details, etc.? Or can it be be done with a local file or something? I don't use trello unfortunately (but I know what it is).

The second idea is feasible, but I feel it might be a lot of work when you can already  just click to show the item in the file and delete it manually - I could add an option to select the item in the file when clicking - then you would just have to click delete if you wanted to.

**Comment by Highter87** [comment]
You can find ready-made code for both items in this extension: 
https://marketplace.visualstudio.com/items?itemName=TzachOvadia.todo-list

But I like your functionality more!

**Comment by Gruntfuggly** [comment]
Hi - the latest version now supports an option to highlight the todo when it is clicked in the tree. Although it's not exactly what you wanted for suggestion 2, it does mean you can just click the item and then press "delete" to remove it.

**Comment by Gruntfuggly** [comment]
Sorry, but I'm going to close this as Trello support is covered by other extensions and nobody else has asked for it.

**Comment by Highter87** [comment]
sadly

**Comment by LeuschkeTressa** [comment]
> Hi - the latest version now supports an option to highlight the todo when it is clicked in the tree. Although it's not exactly what you wanted for suggestion 2, it does mean you can just click the item and then press "delete" to remove it.

What's the name of this option? I really want to use it, but can't seem to find it.

I would expect something like a `select` option to `todo-tree.general.revealBehaviour`.

(My use case: I prefer to have TODOs in code not highlighted/not stand out very much. After having double-clicked a TODO in the Tree View it takes some time to visually find the cursor - i.e., find the TODO in the code - or, as a workaround, I hit a keyboard shortcut to select the line.)
