### ISSUE TITLE
customHighlight doesn't work when using with markdown task - [ ]

### ISSUE THREAD

**Issue by alexwall** [Gruntfuggly/todo-tree#156]
Hi, 

here the example:

![267FC73A-19AB-4FA5-94EB-ED4C14BE0F4C](https://user-images.githubusercontent.com/316469/56604579-8fcc2800-6602-11e9-90f1-465bd13ee5d8.png)

`settings.json:`
```json
        "@backlog": {
            "icon": "book",
            "type": "text",
            "foreground": "#7c7c7c",
            "iconColour": "grey"
        }
```
```markdown
@backlog this task has grey customHighlight (reduced focus due to grey colour), but structuring text is not possible 
    @backlog like this subtask, the indentation of this task is ignored 
- [ ] @backlog this task is assigned correctly[^1], but grey customHighlight doesn't work
    - [ ] cascading subtasks is possible  
- [ ] this is an example for an active task, with white foreground colour --> focus


[^1]: (see tag outline on the left side)
```

**Comment by alexwall** [comment]
small correction from my side...

`icon` and `iconColour` are working just the `foreground` and `background` is not working in `customHighlight` when combine it with `- [ ]`

**Comment by Gruntfuggly** [comment]
What are your settings for `todo-tree.regex` and `todo-tree.tags`?

**Comment by alexwall** [comment]
`regex` is default (no changes) and `tag` is the same

**Comment by alexwall** [comment]
I mean todo-tree.tags is also `@backlog`

**Comment by Gruntfuggly** [comment]
I think to make it work you will need to change the regex. The way it finds markdown todos with the default regex is very simple and doesn't suport tags.

You could try something like:
```
"todo-tree.regex": "(^\\s*- \\[ \\])\\s*($TAGS).*"
```

**Comment by alexwall** [comment]
Thank you @Gruntfuggly 

this works fine for me

I use a slightly different regex, because AFAIK `todo-tree` expects/supports just one tag per line.
Maybe this regex is more efficient 😉

```json
  "todo-tree.regex": "(^\\s*- \\[ \\])\\s*($TAGS)?.*"
```

**Comment by Gruntfuggly** [comment]
Not sure what behaviour you would expect with multiple tags, but if it works for you then great! :grin:

**Comment by alexwall** [comment]
I see, 

here just one example:

```markdown
- [ ] @today @high hotfix of prod bug
- [ ] @today finalise feature x
- [ ] @backlog @medium create concept v2
```

So you would be able to cluster by different aspects e.g. priorities (`@high, @medium`) or time (`@today, @backlog` = later) etc.

**Comment by alexwall** [comment]
Just imagine the possibilities 🤯 
😬
