### ISSUE TITLE
Tags matching erroneously in .sh files

### ISSUE THREAD

**Issue by lonix1** [Gruntfuggly/todo-tree#157]
Tags are matched in `.sh` (linux scripts) files, even when they shouldn't be, and even without a comment designator.

So for example, if I have the tags `TODO` and `TEMP` then these should be detected:

````bash
#TODO foo
#TEMP bar
````

However these are also detected:
````bashTODO foo
TODO foo
TODO
TEMP bar
TEMP
TEMP_DIRECTORY=/temp
TEMPORARY_FILE=foo.tmp
````

**Comment by Gruntfuggly** [comment]
The default regex matches tags at the start of the line, so you should remove `|^` from the first group. I.e., change it from:
```
((//|#|<!--|;|/\*|^)\s*($TAGS)|^\s*- \[ \])
```
to
```
((//|#|<!--|;|/\*)\s*($TAGS)|^\s*- \[ \])
```
