### ISSUE TITLE
Not finding all TODOs

### ISSUE THREAD

**Issue by krisbaehr** [Gruntfuggly/todo-tree#159]
For some reason, not many todo's are being found. I'm running windows 10, vs code 1.33.1 and Todo Tree version 0.0.130.

If I use vs code's search I find all of this...
![image](https://user-images.githubusercontent.com/33702300/57024884-4e87d980-6bfb-11e9-8cd9-458214c61d83.png)

But Todo Tree finds this...
![image](https://user-images.githubusercontent.com/33702300/57024924-665f5d80-6bfb-11e9-9b25-7acff54410b9.png)

Also, when I open up a file it finds the todo and it automatically appears in the tree...
![image](https://user-images.githubusercontent.com/33702300/57025025-aaeaf900-6bfb-11e9-853b-4ff6945f5c4d.png)

Then when I close the file and refresh, the entry (logbook-audit.dfata.ts) is no longer found. Actually, the first time I clicked refresh, it said nothing found. The second time it finds stuff.

Here are my settings:
    "todo-tree.customHighlight": {
        "TODO":{"foreground":"black", "background":"yellow", "type":"tag", "icon":"pin"},
        "FIXME":{"foreground":"white", "background":"red", "type":"tag", "icon":"issue-opened"},
    },
    "todo-tree.defaultHighlight": {
        "foreground": "green",
        "type": "none"
    },
    "todo-tree.excludeGlobs": [
        "**/*.d.ts",
        "**/*.js",
        "**/*.js.map",
        "**/*.md",
        "**/*.h",
        "**/*.xml",
        "**/*mocha",
        "**/*xdg-open",
    ],
    "todo-tree.showScanOpenFilesOrWorkspaceButton": true,
    "todo-tree.flat": true,
    "todo-tree.expanded": true,

Thanks for your help!

**Comment by Gruntfuggly** [comment]
It searches open files separately from searching the workspace, so it sounds like the workspace search is not working as expected. 

If you enable `todo-tree.debug` you should find a debug window in the Output Window (View->Output). You'll need to select it from the dropdown on the right.

It should show the command used for the search and any results it finds. Can you cut and paste it here so I can have a look?

**Comment by krisbaehr** [comment]
[todo-tree-debug-log.txt](https://github.com/Gruntfuggly/todo-tree/files/3135426/todo-tree-debug-log.txt)
![image](https://user-images.githubusercontent.com/33702300/57032579-5736da80-6c10-11e9-90ba-719f4183bccb.png)

**Comment by Gruntfuggly** [comment]
That's not the debug console - it should be in the output window:

![image](https://user-images.githubusercontent.com/376658/57035764-b9accc80-6c4a-11e9-88dc-2d91c13b0924.png)

**Comment by krisbaehr** [comment]
Sorry about that. I just copied everything from this Todo Tree Output window in a text file:
![image](https://user-images.githubusercontent.com/33702300/57036327-9a497b80-6c19-11e9-8ce2-dc5d5e756902.png)

**Comment by krisbaehr** [comment]
@Gruntfuggly - let me know if you need anything else. The text file above contains the search command you mentioned:

Command: "c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg.exe" --no-messages --vimgrep -H --column --line-number --color never --max-columns=1000 -e "((//|#|<!--|;|/\*|^)\s*(TODO|FIXME)|^\s*- \[ \])" "c:\_rad\app"

If there is another output window in vs code, you may have to tell me exactly  how to open it. I selected View > Output like you said, then selected Todo Tree from the dropdown on the right.

**Comment by Gruntfuggly** [comment]
Looking at your output, it looks like it's finding them all, but they are getting removed by the globs.

I would try commenting them out and then add them back in one at a time to see which one causes the results to be hidden.

One that looks suspicious is `/.js`. I wouldn't expect that to match anyway, but were you expecting to hide all results from .js files?

**Comment by krisbaehr** [comment]
@Gruntfuggly  Pretty much all of our code is Typescript, so the .js files are the "transpiled." In my case I really only need .ts files so I've changed the globs like so:
    "todo-tree.includeGlobs": [
        "**/*.ts",
    ],
    "todo-tree.excludeGlobs": [
        "**/*.d.ts",
    ],

I tried commenting out all of the globs and these TODOs are not being displayed. I also scanned the log for those that are missing but I'm not seeing any of them. I'm not sure what the last entry in the log means (Remaining items: 4), but could it be that it's not finished scanning everything? We do have some symbolic link magic going in a few places.

**Comment by Gruntfuggly** [comment]
The last line is saying how many items are left to display after applying the globs. If you have no globs defined, then the number remaining should be the same as the number found from the line above.

I don't think your globs will work quite right at the moment - you probably want to set then to something like `**/*.ts` which will match all the files in all folders.

**Comment by krisbaehr** [comment]
For some reason when pasting the text the other asterisk is getting blown away. Here's what they look like.
![image](https://user-images.githubusercontent.com/33702300/57108540-b07a3900-6cf8-11e9-861a-432c931aac0c.png)

These directories all have TODO's but they are not found in the log.
c:\_rad\app\shared-server\src
c:\_rad\app\shared\src\services
c:\_rad\app\work-order-server\src

Out of curiosity, I tried removing all leading tabs in one of them but that didn't help. I also copied a nested file with a TODO and moved it up to it's parent directory, and it was found.

**Comment by Gruntfuggly** [comment]
What is the path to your workspace folder? I can see from your earlier log that it is searching `c:_rad\app\erp_server` - does it show any from there?

Could you copy the actual content of the todo-tree debug log window instead of a screen grab?

And just to confirm - if you don't define any globs (include or exclude), does the "found" number match the "remaining" number?

**Comment by krisbaehr** [comment]
The workspace folder is c:\_rad\app. The erp-server didn't have any todo's but I copied a file there and it did show up (it's in the provided log file as well): 
![image](https://user-images.githubusercontent.com/33702300/57141980-16120800-6d81-11e9-8232-e319b1af0c0c.png)

I removed all globs and there were no remaining items:
![image](https://user-images.githubusercontent.com/33702300/57142252-b49e6900-6d81-11e9-900a-d535b4f9ab7f.png)

TODOs Not found:
C:\_rad\app\shared-server\src\data\work-order\attachments\attachment-gallery.data.ts
C:\_rad\app\shared-server\src\data\work-order\squawk\logbook-audit.data.ts
C:\_rad\app\shared-server\src\data\work-order\squawk\squawk-validator.ts
C:\_rad\app\shared-server\src\data\work-order\squawk\squawk.data.ts
C:\_rad\app\shared-server\src\data\work-order\sub-squawk-validation\check-work-order-squawk-validator.ts
C:\_rad\app\shared-server\src\data\work-order\sub-squawk-validation\sub-squawk-validator.ts
C:\_rad\app\shared-server\src\data\work-order\sub-squawk\sub-squawk.data.ts
C:\_rad\app\shared-server\src\data\work-order\task-inspection\task-inspection.data.ts
C:\_rad\app\shared-server\src\data\work-order\work-order-times-cycles.data.ts
C:\_rad\app\shared\src\services\work-order\task-inspection\task-inspection.metadata.ts
C:\_rad\app\work-order-server\src\routes\work-order\logbook-audit.tester.ts

TODOs Found:
C:\_rad\app\shared\src\services\stats\daily-stat.ts

[todo-tree-debug-log2.txt](https://github.com/Gruntfuggly/todo-tree/files/3142281/todo-tree-debug-log2.txt)

**Comment by Gruntfuggly** [comment]
Hi - sorry, I've only just had a chance to look again at this.

The log you've attached shows that the globs are still being applied - it says there are 4 remaining items?

**Comment by krisbaehr** [comment]
Sorry about that, it looks like it was just an FYI in a screenshot. Here is the latest without globs, and the latest search.

[log-without-globs.txt](https://github.com/Gruntfuggly/todo-tree/files/3177762/log-without-globs.txt)
![image](https://user-images.githubusercontent.com/33702300/57700059-c81dbf80-761e-11e9-9f8e-9f8c2e2aa0e0.png)

**Comment by Cloud7050** [comment]
Hello, recently I’ve noticed the extension seems to have stopped showing my TODOs in the sidebar. They are highlighted just fine in the editor, and reverting to a version of this extension from a month ago made them show up in the sidebar again.

Reading through this thread, I’ve disabled all my custom settings (such as globs) and checked the output logs, where it says there are 150 matches, yet the sidebar remains empty, saying there’s nothing found, even after waiting several minutes and refreshing a few times. I’ve also tried disabling all other extensions except this one to no avail. I’m on the latest version of VSC.

**Comment by Gruntfuggly** [comment]
@Cloud7050 - do you mind creating a separate issue and uploading your config and the output of the debug channel? I'll get too confused looking into two lots of debug! :grin:

**Comment by Gruntfuggly** [comment]
@krisbaehr - sorry, but your log shows 1411 found items, but your search screenshot shows 21? What is displayed in the tree with this configuration? If it's not confidential, is it feasible to zip up your workspace and email it to me so I could try it out?

**Comment by krisbaehr** [comment]
@Gruntfuggly The 1411 found items are every TODO or FIXME found in my workspace. The search is a simple VS Code search from the same time. Yes, 1411 items were found but few if any of the items in the VS Code Search are in the 1411. You can look for them in the log and they just aren't being found.

Through troubleshooting, I believe it isn't a problem with the algorithm. The problem appears to be that not every folder and/or file is being scanned. If you had a version of the plugin that would log every file/directory being scanned, whether a todo was found or not, that would answer that question.

I wouldn't feel comfortable sending the whole workspace but I'm willing to assist in troubleshooting. Thanks!

**Comment by Gruntfuggly** [comment]
If you're happy to do a bit of hacking, open `.vscode/extensions/gruntfuggly.todo-tree-0.0.132/ripgrep.js` and comment out lines 121 to 124:
```
    // if( options.regex )
    // {
    //     execString = `${execString} -e ${options.regex}`;
    // }
```
Then add '--files' to `todo-tree.ripgrepArgs' and reload the workspace.

It should then list all the files that it is scanning in the output window. It will also match and create a TODO for each file, but just ignore those - the top section should be the list of scanned files.

Let me know if that explains anything.

One thing - are any of your folders symlinks? By default ripgrep doesn't follow symlinks...

**Comment by Gruntfuggly** [comment]
You could also try adding `--no-ignore` to `todo-tree.ripgrepArgs`. Maybe it's ignoring folders for some reason?

**Comment by krisbaehr** [comment]
Some of the files are in symlinks but only for the purpose of sharing them with other projects, so they can be ignored in our case. I will try to do some hacking tomorrow or Friday and let you know what I find.

**Comment by krisbaehr** [comment]
> Some of the files are in symlinks but only for the purpose of sharing them with other projects, so they can be ignored in our case. I will try to do some hacking tomorrow or Friday and let you know what I find.

**Comment by krisbaehr** [comment]
Sorry, I haven't had the chance to do any further testing. I've just been very busy. I hope to get to it soon.

**Comment by krisbaehr** [comment]
Sorry, I haven't had the chance to do any further testing. I've just been very busy. I hope to get to it soon.

**Comment by Gruntfuggly** [comment]
Any further information on this? If not, I'm going to close the issue. Feel free to re-open it if you do find something.

**Comment by krisbaehr** [comment]
@Gruntfuggly I haven't a chance to test. If I have more time later and can still recreate the issue, I can re-open it. Thanks!

**Comment by 2metres** [comment]
Not sure if this helps anyone but I came across this issue and noticed that when TODOs, etc were inside a typescript file the type of comment made it show up.

**Not detected:**
```typescript
/*
 * TODO
 * FIXME
 * BUG
 */
```

**Detected:**
```typescript
//
// TODO
// FIXME
// BUG
//
```
