### ISSUE TITLE
Configuration does not respect ${workspaceFolder} substitution

### ISSUE THREAD

**Issue by prokher** [Gruntfuggly/todo-tree#16]
Unfortunately, it is impossible to use relative paths or `${workspaceFolder}` in the `rootFolder` configuration setting. Only absolute paths work there.

I added the following line to the configuration:
```
    "todo-tree.rootFolder": "${workspaceFolder}/demo",
```
but it continuously complains:
```
todo-tree: root folder not found (${workspaceFolder}/demo)
e.onDidNotificationChange @ notificationsAlerts.ts:39
(anonymous) @ notificationsAlerts.ts:28
e.fire @ event.ts:140
e.notify @ notifications.ts:127
e.notify @ notificationService.ts:65
e._showMessage @ mainThreadMessageService.ts:86
e._showMessage @ mainThreadMessageService.ts:47
e.$showMessage @ mainThreadMessageService.ts:41
e._doInvokeHandler @ rpcProtocol.ts:174
e._invokeHandler @ rpcProtocol.ts:159
e._receiveRequest @ rpcProtocol.ts:108
e._receiveOneMessage @ rpcProtocol.ts:90
(anonymous) @ rpcProtocol.ts:33
(anonymous) @ rpcProtocol.ts:213
e.fire @ event.ts:140
(anonymous) @ ipc.net.ts:81
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
```

**Comment by Gruntfuggly** [comment]
You can use relative paths from your home folder, but I guess that's not really what you want.
I don't think there is a way to expand vscode's environment variables within an extension (might be worth keeping an eye on https://github.com/Microsoft/vscode/issues/46471)
I could try it manually though...

**Comment by prokher** [comment]
Dear @Gruntfuggly, thanks for quick response. Looks like you are right, other guys do this manually. For example like [here](https://github.com/thisboyiscrazy/vscode-rsync/blob/e8e2c2e868628599a851b8129b10288294726ae3/src/Config.ts#L87). Anyway, it would be great to have this.

**Comment by rozzzly** [comment]
I wrote a generic solution for this  functionally.
 https://github.com/rozzzly/vscode-prompt-debug/blob/e3fe595f6aecbf63dfa4a3edc0c0f27fb9862b1c/src/substitution.ts

It's async so it supports things like `${command:someCommand}`

It allows you to define custom handlers (sync or async) which can be a simple string or RegExp. It will also expand `~/dir/file.xyz` to `/home/rozzzly/dir/file.xyz` (or c:\Users\rozzzy\dir\file.xyz` if on Windows)

While it is robust and flexable, it's currently intergrated into my extension, but I plan on eventually extracting it into a separate package.

**Comment by Gruntfuggly** [comment]
I've just uploaded a new version with a quick and dirty variable substitution. Works with environment variables and also ${workspaceFolder}.

@rozzzly - a separate package sounds useful (until it gets implemented natively). Unfortunately my typescript knowledge is virtually zero, so helping out is probably not on the cards, sorry.
