### ISSUE TITLE
Highlighting not the complete line but `//`

### ISSUE THREAD

**Issue by sidpagariya** [Gruntfuggly/todo-tree#163]
Hi,
I was trying to highlight the `//` the precedes the tag in, say, `//INFO: [some text here]`. I want to highlight and I see that for the `TODO` tag in a line like `//TODO: [some text here]` this happens automatically, but not for my other tags. Is there a way to activate this feature for all the other tags as well?

EDIT: Version 0.0.126 did this and ever since 0.0.127, it stopped...

Thanks!

**Comment by Gruntfuggly** [comment]
Sorry, I don't understand - can you attach a screenshot of the difference?

**Comment by Gruntfuggly** [comment]
In 0.0.126, when `type` was set to `tag` it highlighted the comment too. This was never the intention, but are you saying you would prefer this? If so I can add another setting.

Currently:

code(); // ~TODO~ text

but you would prefer:

code(); ~// TODO~ text

**Comment by sidpagariya** [comment]
Hi, sorry for the late response!
So in versions 0.0.126 and earlier, we saw:
<img width="120" alt="Screen Shot 2019-05-13 at 12 32 37 PM" src="https://user-images.githubusercontent.com/10685754/57638223-53de1000-757b-11e9-9cfb-ec22967b4be0.png">
And in 0.0.127 we now see:
<img width="120" alt="Screen Shot 2019-05-13 at 12 31 57 PM" src="https://user-images.githubusercontent.com/10685754/57638245-5fc9d200-757b-11e9-97f0-f65608303923.png">

The one thing is that the `TODO` tag is still the same highlighted for even 0.0.127 and up:
<img width="180" alt="Screen Shot 2019-05-13 at 12 29 59 PM" src="https://user-images.githubusercontent.com/10685754/57638278-75d79280-757b-11e9-8dd9-7ba98d001a0a.png">
It would be great if you could add that as well, it would be really nice!

Thanks!

**Comment by Gruntfuggly** [comment]
I've added another "type" option for for the highlight - "comment-and-tag" which reverts to the 0.0.126 behaviour.

> The one thing is that the TODO tag is still the same highlighted for even 0.0.127 and up:

Sorry, I don't understand?

**Comment by sidpagariya** [comment]
It's all good, I just saw that! I also pushed #164 for another option, `text-and-comment` if that's okay with you!

**Comment by Gruntfuggly** [comment]
:grin: I thought that ought to be an option. Thanks.

**Comment by sidpagariya** [comment]
Awesome! 😄
