### ISSUE TITLE
Is there a way to hightlight the whole line after a tag?

### ISSUE THREAD

**Issue by norman123123** [Gruntfuggly/todo-tree#166]
Is there a way to hightlight the whole line after a tag? 
Maybe half a line or a pre defined number of spaces?

**Comment by Gruntfuggly** [comment]
You can highlight:
- tag 
- tag and following text
- leading comment and the tag
- leading comment and the tag and the following text
- the whole line

Full details are here: https://github.com/Gruntfuggly/todo-tree#highlighting

**Comment by Gruntfuggly** [comment]
I've just realised - do you mean highlighting the entire line on the screen, regardless of it's content?

**Comment by Gruntfuggly** [comment]
Latest version adds a new highlight option - `whole-line`

**Comment by norman123123** [comment]
@Gruntfuggly I think so, I'm not sure about what you mean by "regardless of its content" but I meant making it look like this:

<img width="980" alt="Screenshot 2019-06-28 at 17 33 19" src="https://user-images.githubusercontent.com/8712696/60372530-dce5c500-99ca-11e9-83e3-81b13c6188b4.png">

I did that by adding spaces but I was wondering if there was a way to make it so that the color highlight is visible across the editor screen.

Also I tried setting
`"todo-tree.whole-line": true`
but nothing happened

**Comment by Gruntfuggly** [comment]
You need to set it in the highlight settings, something like:
```
"todo-tree.defaultHighlight":{
  "background":"red",
  "type":"whole-line"
}
```
See https://github.com/Gruntfuggly/todo-tree#highlighting
