### ISSUE TITLE
0.0.132 broke support for excluding directories recursively

### ISSUE THREAD

**Issue by unai-ndz** [Gruntfuggly/todo-tree#167]
Since then it throws this error: `todo-tree: error parsing glob '!**/(.*|**)/--misc/**': invalid use of **; must be one path component`

My config:
```json
		"todo-tree.excludeGlobs": [
			"**/(.*|**)/--misc/**",
			"**/(.*|**)/unused/**",
			"**/(.*|**)/(OLD|old)/**"
		],
```
This works fine on `0.0.131`.

**Comment by Gruntfuggly** [comment]
OK - I guess it's down to differences between ripgrep's globbing engine and vscode's. I'l have to add a config option.

**Comment by Gruntfuggly** [comment]
I've just updated a version with an option `todo-tree.passGlobsToRipgrep` which you can set to false to revert back to the pre-132 behaviour.

**Comment by unai-ndz** [comment]
Thanks
