### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by lukevp** [Gruntfuggly/todo-tree#168]
What license is this code under? I did not see a LICENSE file and couldn't find it on GitHub. it can be set on the repository level and will then display next to the contributors.

**Comment by Gruntfuggly** [comment]
I've never really thought about the license. I'll add an MIT license.

**Comment by lukevp** [comment]
Thanks for updating the license!

**Comment by Gruntfuggly** [comment]
Thanks for the suggestion!
