### ISSUE TITLE
highlighting the variables and consts

### ISSUE THREAD

**Issue by tondar20** [Gruntfuggly/todo-tree#169]
Is there any setting for highlighting the variables and consts? For example I want to see "DEBUG" highlighted:

    #if DEBUG
    #include <MyDebug.h>
    #endif

Or highlight the tags in all comment text? For example highlight "TODO" in this comment:

    // I tried more than 100 times to resolve this TODO

Thanks

**Comment by Gruntfuggly** [comment]
You would need to alter the regular expression. Your first case would be fairly simple - you could use something like:
`"todo-tree.regex":"(#if)\s*($TAGS)"`
and the add DEBUG to the tags.

You could simplify the regex to just `\s*($TAGS)` for your second case.
