### ISSUE TITLE
No Todo (etc) in Explorer ?

### ISSUE THREAD

**Issue by SheepDomination** [Gruntfuggly/todo-tree#17]
When the extension is installed, and I type `// TODO <comment>` explorer within vs code should automatically display `TODO` within the explorer tree, correct ? If this is the case, nothing is showing up within vs code explorer ?

**Comment by Gruntfuggly** [comment]
Hi there - it won't show until you save the file. It should then open a new view under the explorer with the todo in it. Also, the file needs to be inside the current workspace. I'm currently working on showing TODOs in files that are outside the workspace.

If you're still not seeing any, could you post a screenshot?

**Comment by SheepDomination** [comment]
Hi, this is the screenshot;
https://s5.postimg.cc/4sqs6n0uf/2018-04-23_09-53-10.png

**Comment by SheepDomination** [comment]
I see what you mean. It's cleaner when it's within a workspace but as you mentioned you haven't implemented where it works outside of a workspace; don't know which is better ;)

**Comment by Gruntfuggly** [comment]
I've just released a new version. It should show TODOs from files outside the current workspace now. You'll need to actually view the file in vscode (i.e. select it in the explorere view) before they show up due to the way vscode populates it's list of open documents.

Let me know how you get on with it.

**Comment by xieshuaix** [comment]
I experience the same issue. All todotree settings are by default. My TODOs are typed as: "// TODO: <comment>". No todo shows up in explorer. All files are within my only workspace and are saved. Viewing the files or not does not make a difference. I wonder what could goes wrong? Thanks!

**Comment by Gruntfuggly** [comment]
@xieshuaix Please could you update to the latest version and set "todo-tree.debug" to true. There should now be a new output channel available in the drop down of the output window called "todo-tree". Can you open this and copy it's contents?

**Comment by xieshuaix** [comment]
@Gruntfuggly Hi, I tried what you suggested and below is the debug log, thanks for your help!

Search: {"folder":"/home/shuai/Work"}
Command:/snap/vscode/27/usr/share/code/resources/app/node_modules/vscode-ripgrep/bin/rg --no-messages -H --column --line-number --color never  -e "((//|#|<!--|;|/\*)\s*(TODO|FIXME)|^\s*- \[ \])" "/home/shuai/Work"

 Match {"file":"/home/shuai/Work/test/test_data.cpp","line":79,"column":5,"match":"    // TODO: to be corrected here!"}
 Match: {"file":"/home/shuai/Work//test/test_map.cpp","line":429,"column":2,"match":"\t// TODO: should be further modified!"}

onDidChangeActiveTextEditor (uri:{"$mid":1,"fsPath":"extension-output-#2","external":"output:extension-output-%232","path":"extension-output-#2","scheme":"output"})
Search: {"file":"extension-output-#2"}
Command:/snap/vscode/27/usr/share/code/resources/app/node_modules/vscode-ripgrep/bin/rg --no-messages -H --column --line-number --color never  -e "((//|#|<!--|;|/\*)\s*(TODO|FIXME)|^\s*- \[ \])" "extension-output-#2"

**Comment by xieshuaix** [comment]
@Gruntfuggly I updated VSCode (On Ubuntu) to latest version and your extension works again!
