### ISSUE TITLE
[Feature Request] Copy TODOs to clipboard

### ISSUE THREAD

**Issue by CuddleBunny** [Gruntfuggly/todo-tree#170]
It would be pretty handy if there was a way to add TODOs to the clipboard and/or export them to a document of some sort.

**Comment by Gruntfuggly** [comment]
How do you mean by adding them to the clipboard? Do you mean from the tree?

It's not very neat, but if you want an export of all the TODOs you can copy them from the output channel if you enable `todo-tree.debug`.

**Comment by CuddleBunny** [comment]
Thanks, the log will suffice for my needs. I like the JSON output. 

To elaborate, since I still believe this could be a nice feature. It would be nice to export a text only version of the TODOs as a flat list and/or tree view (perhaps formatted like unix tree command?). The additional metadata I see in output could also be handy exported as a JSON file.

Rather than straight to clipboard or file export, a new editor tab with the output from the above would probably be optimal.

**Comment by Gruntfuggly** [comment]
I've just uploaded a new version which allows export (as linux tree or JSON) to a text file.

**Comment by Gruntfuggly** [comment]
Many thanks for the donation!
