### ISSUE TITLE
.vue files

### ISSUE THREAD

**Issue by ricky11** [Gruntfuggly/todo-tree#171]
does it nativity work with .vue files?  I am unable to get any highlighting in vue

**Comment by Gruntfuggly** [comment]
By default highlighting is not enabled, but there is no reaso why it shouldn't work with .vue files once it it.

To enabled it, update `todo-tree.defaultHighlight`. See https://github.com/Gruntfuggly/todo-tree#highlighting

**Comment by ricky11** [comment]
Thanks, sorry where do i add this in settings.json?  do i set it to true?

**Comment by Gruntfuggly** [comment]
Yes - see the examples in the link I posted. Unfortunately it's too complex to set the configuration via the GUI, but if you click the setting link in the GUI it should take you to the `settings.json` file.
