### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by denOldTimer** [Gruntfuggly/todo-tree#173]
A small .excludeGlobs list

```
"todo-tree.excludeGlobs": [
        "**/vendor/**",
        "**/node_modules/**",
        "**/dist/**",
        "**/bower_components/**",
        "**/build/**",
        "**/.vscode/**",
        "**/.github/**",
        "**/_output/**",
        "**/*.min.*",
        "**/*.map"
    ]
```

Maybe add it to the wiki, Readme or in the extension that someone can find it...
Thanks

**Comment by Gruntfuggly** [comment]
Thanks - the wiki is at the top of my todo list (excuse the pun).

**Comment by ShinobiWPS** [comment]
Instead of opening a new Issue I wanted to extend this one:
the suggestion is to set "**/node_modules" as part of the default glob.
