### ISSUE TITLE
Laravel Blade

### ISSUE THREAD

**Issue by NeptuneDesign** [Gruntfuggly/todo-tree#174]
Hello can you set up blade comment support
`{{-- TODO: How --}}`
I tried to change the configuration but it doesn't work, thank you.
`"todo-tree.regex":""((//|#|<!--|{{--|;|/\\*)\\s*($TAGS)|^\\s*- \\[ \\])"`

**Comment by Gruntfuggly** [comment]
You just need to escape the '{' characters because they have a special meaning.

So, something like:
`"todo-tree.regex":""((//|#|<!--|\\{\\{--|;|/\\*)\\s*($TAGS)|^\\s*- \\[ \\])"`

**Comment by NeptuneDesign** [comment]
Good morning, thank you.
I had tried with only one antislash but with two it works.
Thank you again ;)

**Comment by Gruntfuggly** [comment]
No problem - I think you can get away with a single backslash if you modify through the settings GUI, but not directly in the JSON.
