### ISSUE TITLE
Unable to exclude folders from search

### ISSUE THREAD

**Issue by CostachescuCristinel** [Gruntfuggly/todo-tree#175]
Hi,

I have a folder in my project where there are some external libraries, which I can't seem to exclude from the searched paths. I want to exclude both the main plugins folder and it's subfolders.
The plugins folder is in [project root]/public/js/plugins.
In settings.json I have tried all of the following:
"excludeGlobs": [ "see strings below" ]
```
"/public/js/plugins/*"
"/public/js/plugins/**"
"**/public/js/plugins/**"
"**/plugins/**"
"**/js/plugins/**"
...many more variants that I may have forgotten
```

I am unfamiliar with the syntax used here, maybe I'm doing it wrong.
Can you help me figure it out?

**Comment by CostachescuCristinel** [comment]
Hi, sorry for troubling you, I got it fixed. It seems I was using just "excludeGlobs" instead of "todo-tree.excludeGlobs" which made the setting unavailable to the extension.

**Comment by Gruntfuggly** [comment]
No problem - glad you got it sorted.
