### ISSUE TITLE
Filter on directory/path rather than TODO content

### ISSUE THREAD

**Issue by tunnij** [Gruntfuggly/todo-tree#176]
It would be nice to be able to restrict the view to a subset of the repo/folder you're looking at. This is especially useful for large and shared repos.

**Comment by Gruntfuggly** [comment]
You could use the include/exclude globs:
https://github.com/Gruntfuggly/todo-tree#excluding-files-and-folders
If you wanted to do it through the GUI, what sort of interface would you be after - something similar to the current content filter entry?

**Comment by tunnij** [comment]
Yeah I think something very similar as the current input. I initially
thought it was a filter on folders/files. Or maybe you just right click on
a folder and there's an 'Only in this folder' option?

**Comment by Gruntfuggly** [comment]
I could add a couple of options context menu options
**exclude this folder** and **show only this folder**
which could automatically update the glob patterns.

**Comment by tunnij** [comment]
That sounds good along with an option to clear the filter.

**Comment by Gruntfuggly** [comment]
Try the latest version and let me know what you think.

**Comment by tunnij** [comment]
I think it just needs to include subfolders of the folder you select as
well. Other than that I like the access method.

**Comment by Gruntfuggly** [comment]
Sorry, I'm not sure I understand. There is "Only Show This Folder" and "Only Show This Folder And Subfolders" - I thought that would cover both, or am I missing something?

**Comment by tunnij** [comment]
Sorry, I missed that. It looks great! Something I’ve just noticed is that
the sort looks completely alphabetical. It would be nice to sort folders
first and then files underneath like the file explorer.

Thanks for the work!

**Comment by Gruntfuggly** [comment]
No problem - would you mind creating a separate issue for the sorting - I'm going on holiday for a few days and I might forget!

**Comment by tunnij** [comment]
Done #182 

Have a good holiday
