### ISSUE TITLE
Can't seem to get multiline TODO to highlight

### ISSUE THREAD

**Issue by ctcuff** [Gruntfuggly/todo-tree#178]
So I've looked at [#140 ](urlhttps://github.com/Gruntfuggly/todo-tree/issues/140) and saw that multiline todos should work out of the box. I might be doing something wrong, but I can't seem to get the plugin to highlight more than just the first line. Take this screenshot for example:

![vscode-todo](https://user-images.githubusercontent.com/7400747/60388266-fba49400-9a7c-11e9-8920-2fba88fc29f8.PNG)

Only the first line is highlighted as well as shown in the left sidebar.
I'm wondering if I can achieve something like this:

![webstorm-todo](https://user-images.githubusercontent.com/7400747/60388280-21ca3400-9a7d-11e9-8833-7e6b2e1a4ad5.PNG)

Where each todo is shown:

![webstorm-todo-navigation](https://user-images.githubusercontent.com/7400747/60388284-327aaa00-9a7d-11e9-81b4-d2245957aaec.PNG)

Again, this might just be a problem specific to me, so here's my config is case that's true:

```
{
  . . .
  "todo-tree.regex": "(//)\\s*($TAGS).*(\\n\\s*//\\s{2,}.*)*",
  "todo-tree.customHighlight": {
    "TODO": {
      "icon": "pencil",
      "type": "line",
      "foreground": "yellow"
    },
    "FIXME": {
      "foreground": "black",
      "iconColour": "yellow"
    },
  . . .
}
```

**Comment by Gruntfuggly** [comment]
I don't think I ever implemented highlighting for the whole of multi-line TODOs. I could probably extend the highlight to the end, but it might be tricky to not highlight the comment parts.

**Comment by Gruntfuggly** [comment]
Latest version should work a bit better. Let me know what you think.

**Comment by ctcuff** [comment]
Awesome, it works! Just a _tiny_ issue, the line under the last comment is highlighted as well:
![lit-from-bottom](https://user-images.githubusercontent.com/7400747/60458432-9a132f80-9c0c-11e9-8435-afba598903bd.PNG)

Although, this isn't really too big of a deal because it can be fixed with an empty comment like so:
![not-lit](https://user-images.githubusercontent.com/7400747/60458536-e3637f00-9c0c-11e9-9abf-439c239d5e0d.PNG)

**Comment by Gruntfuggly** [comment]
OK - have another try. 8-)

**Comment by ctcuff** [comment]
Perfect!

![working](https://user-images.githubusercontent.com/7400747/60460292-4f47e680-9c11-11e9-96b1-21bba93c59cc.PNG)

**Comment by umang1995** [comment]
@Gruntfuggly  How to achieve this for python TODO's ? I had a look at this and #140  both.
