### ISSUE TITLE
"magenta" not working as background for customHighlight

### ISSUE THREAD

**Issue by beebase** [Gruntfuggly/todo-tree#179]
version: 0.0.136 (but already noticed this a couple of months ago)

For some reason I can't get background: "magenta" to work.
iconColour: "magenta" works ok for the tree-view icons.

All other colours work fine for both iconColour and background.

Can someone reproduce this behaviour?
```
"todo-tree.customHighlight": {
    "backlog1>": {
      "iconColour": "magenta",
      "background": "magenta"
    }
```

**Comment by Gruntfuggly** [comment]
That's weird - but I can reproduce it.

**Comment by Gruntfuggly** [comment]
I had a flawed isHex function - basically it stripped non A-F characters out of the string and checked the length. Magenta -> 'aea' which looks like valid hex.

Should work properly now.

**Comment by beebase** [comment]
Could it be, this bug is reappearing in 0.0.141 ?
setting iconColour to 'magenta' results to white icons in the tree. 'red' for instance, does work.
![image](https://user-images.githubusercontent.com/446089/63096554-80d10300-bf6e-11e9-9e62-47a6daf6650a.png)

**Comment by Gruntfuggly** [comment]
It's because the icons were updated to match the new vscode style. Looks like the magenta ones were given the wrong colour.

Why is it always the magenta one?! :grin:

**Comment by beebase** [comment]
According to aviation psychologists, magenta is very well suited for drawing human attention in the cockpit...I hope they double checked 😐

**Comment by Gruntfuggly** [comment]
New version with the magenta icon reinstated.
