### ISSUE TITLE
Add expand all/collapse all button

### ISSUE THREAD

**Issue by jesusfer** [Gruntfuggly/todo-tree#18]
Would it be possible to have a collapse/expand all button? I think that would be very helpful if you have a long list of tasks and want to have a quick look at everything that needs to be done. It'd be specially helpful when you use the tree view and have 2/3 levels of folders.

**Comment by Gruntfuggly** [comment]
I was already thinking of doing this - I am hoping that the VScode team extend the API for tree views to allow this to be done properly, but for now it will have to rebuild the tree.  Watch this space...

**Comment by Gruntfuggly** [comment]
Sorry it's taken a while, but I've just uploaded a version with expand and collapse buttons.
