### ISSUE TITLE
Update icons

### ISSUE THREAD

**Issue by johnletey** [Gruntfuggly/todo-tree#181]
With the new vscode icons being released soon 🎉 (https://github.com/microsoft/vscode/issues/8017) ... your extension sidebar icon looks a little weird:

<img width="40" alt="Screen Shot 2019-07-10 at 6 58 29 AM" src="https://user-images.githubusercontent.com/30328854/60939402-2f36b800-a2e0-11e9-8b9b-5f18b9cc577d.png">

> Picture taken in Visual Studio Code - Insiders (which already has the new icons)

 I will open a PR with my updated icons throughout this project to follow the new icon styles

**Comment by johnletey** [comment]
@Gruntfuggly What do you think of this:

![Screen Shot 2019-07-10 at 7 13 31 AM](https://user-images.githubusercontent.com/30328854/60939927-4ecee000-a2e2-11e9-82c0-3ed919a0fe0a.png)

**Comment by Gruntfuggly** [comment]
Thanks! I think I prefer the thicker one. Let me know when it's ready and I'll update.

**Comment by kanlukasz** [comment]
Version 1.37 with new icons is already official released, so you can update icon i think :)

**Comment by kanlukasz** [comment]
by the way, maybe it's a good moment to change the green "Ok" icon, for example :
![obraz](https://user-images.githubusercontent.com/30685349/62858814-a5717480-bcfb-11e9-88ab-bee69b5de579.png)
i can send you png or vector if you like it

**Comment by johnletey** [comment]
@Gruntfuggly @kanlukasz Just opened up a draft PR
