### ISSUE TITLE
Clean up sidebar view

### ISSUE THREAD

**Issue by jabacchetta** [Gruntfuggly/todo-tree#184]
In the following screenshot, I'd love the ability to:

- Remove icons from the entries (icons only show for the tag type headings)
- Remove the tag text from the entries (so that the comment shows without the repetitive tags)
- In place of the repetitive icons and tags, have a small, simple visual indicator that separates each entry (e.g. bullet point)

<img width="1280" alt="Screen Shot 2019-07-14 at 6 02 51 PM" src="https://user-images.githubusercontent.com/12591890/61190421-9eeecf00-a661-11e9-84ca-37728524fcf8.png">

**Comment by Gruntfuggly** [comment]
There is a configuration setting `todo-tree.labelFormat` that allows you to modify the format. The default is `"${tag} ${after}"` but you can use the following placeholders: ${line}, ${column}, ${tag}, ${before} (text from before the tag), ${after} (text from after the tag) and ${filename}.

I could add an option to hide the icon for the entries when using the 'group by tag' view.

**Comment by Gruntfuggly** [comment]
I've added a setting `todo-tree.hideIconsWhenGroupedByTag`.

**Comment by jabacchetta** [comment]
Perfect, appreciate the fast response and update!

**Comment by Gruntfuggly** [comment]
Thanks for the donation - much appreciated!
