### ISSUE TITLE
Option of Disable Ruler

### ISSUE THREAD

**Issue by HaoQChen** [Gruntfuggly/todo-tree#185]
Can there be an option of disable ruler? The rulers are making me crazy. And when I  find some word, it will be mixed.

**Comment by Gruntfuggly** [comment]
In the short term, you can set the colour to have minimum alpha, e.g.
```
    "todo-tree.defaultHighlight": {
        "rulerColour": "#00000000"
    },
```

I'll update the extension so that you can specify
```
    "todo-tree.defaultHighlight": {
        "rulerLane": "none"
    },
```
to make it more explicit.

**Comment by HaoQChen** [comment]
> In the short term, you can set the colour to have minimum alpha, e.g.
> 
> ```
>     "todo-tree.defaultHighlight": {
>         "rulerColour": "#00000000"
>     },
> ```
> 
> I'll update the extension so that you can specify
> 
> ```
>     "todo-tree.defaultHighlight": {
>         "rulerLane": "none"
>     },
> ```
> 
> to make it more explicit.

Thanks

**Comment by Gruntfuggly** [comment]
Fixed in the latest version - let me know if it works OK.

**Comment by HaoQChen** [comment]
> Fixed in the latest version - let me know if it works OK.

By setting `"rulerLane": "none"`. It is disable. Thank you~~~
