### ISSUE TITLE
[Need help] Regex for block comments

### ISSUE THREAD

**Issue by kanlukasz** [Gruntfuggly/todo-tree#186]
Hello
Can you help me with a regular expression for block comments?
To be honest regex are not my strong side 😞 

I often use comments like this:

```
/**
 * TODO: test1
 * TODO: test2
 * TODO: test3
 * TODO: test4
 */
```
or just
```
/**
 * TODO: test
 */
```

**Comment by Gruntfuggly** [comment]
Try this if you update the settings via the GUI:
`(/\*\*)\s*($TAGS).*(\n\s*\*\s.*)*`
or this if you edit in the JSON:
`(/\\*\\*)\\s*($TAGS).*(\\n\\s*\\*\\s.*)*`
This should match multiple lines as long as they start with a single star, and the first line should have two stars.

**Comment by kanlukasz** [comment]
Unfortunately your proposition not working but i found this https://github.com/Gruntfuggly/todo-tree/issues/111#issuecomment-457991437 and that work awesome!

Thanks for quick reply anyway

**Comment by Gruntfuggly** [comment]
I'm not sure why it didn't work because I tested it with your sample code. Glad you've got it working though! :grin:
