### ISSUE TITLE
[Future request]  Add link to the TODO panel from status bar

### ISSUE THREAD

**Issue by kanlukasz** [Gruntfuggly/todo-tree#188]
Hey,
I have one small FR. 
This is really detailed, but you may find it useful

#### Add link to the TODO panel from status bar

---

I talk about this:
1. I clik this:
![obraz](https://user-images.githubusercontent.com/30685349/62872952-c6978c80-bd1e-11e9-84d0-e810567aa51d.png)

2. VS shows me this:
![obraz](https://user-images.githubusercontent.com/30685349/62873189-3efe4d80-bd1f-11e9-8460-a4185838b47a.png)

**Comment by Gruntfuggly** [comment]
Fixed in the latest version. The old behaviour is still the default, but you can now change `todo-tree.statusBarClickBehaviour` to `reveal`.

**Comment by kanlukasz** [comment]
Yes, this is it. Thank you so much! 🍺
