### ISSUE TITLE
Nothing happens when I try to show a flat/tree view

### ISSUE THREAD

**Issue by marmistrz** [Gruntfuggly/todo-tree#19]
I can't see any error message either. VSCode 1.22.2-1, Arch Linux

**Comment by Gruntfuggly** [comment]
If you files containing your TODOs are in the top folder of your workspace, then you won't see any difference. To check it's working, try putting a TODO in a subfolder. If that doesn't work, can you attach a screenshot?

**Comment by marmistrz** [comment]
The todo is located in the file `src/main.rs`, line 47, attaching the surrounding lines.

```
    let mut config: Config = toml::from_str(&cfgstr).expect("Failed to load configuration");

    // TODO add some more robust default value handling
    if config.smtp == "" {
```

**Comment by Gruntfuggly** [comment]
Is the full path of the file?
/home/marcin/proj/poomas/src/main.rs 

Do you see any tree view at all? I thought the problem was that swapping between tree/flat wasn't changing anything, but it sounds like your not seeing the TODO in the first place

**Comment by Gruntfuggly** [comment]
Does this files exist?
/usr/share/code/resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg

**Comment by marmistrz** [comment]
No, `visual-studio-code-bin` from AUR installs the editor into `/opt`:
```
/opt/visual-studio-code/resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg
```

**Comment by Gruntfuggly** [comment]
OK - it should still find it though, so I don't think that is the problem.

Are you using the default configuration?

**Comment by marmistrz** [comment]
I didn't change the todo-tree configuration, if that's what you mean.

**Comment by Gruntfuggly** [comment]
Did you have any luck with this? Since my previous suggestion I've added a debug channel to the output window which will be much more useful if this is still an issue.
