### ISSUE TITLE
TypeScript files identified as js

### ISSUE THREAD

**Issue by crystalfp** [Gruntfuggly/todo-tree#190]
Issue Type: <b>Bug</b>

Look at a ts file with various Todo Tree formatted comments.

In the Tree view the file is identified as js. See image.

![Annotation 2019-08-19 155718](https://user-images.githubusercontent.com/865866/63271283-184d9300-c29a-11e9-9359-173571d86e91.jpg)

Bug or feature?
Thanks for looking!
mario

Extension version: 0.0.141
VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (5.79GB free)|
|Process Argv|--file-uri file:///d%3A/Montessori/Libro%20-%20Tecnologia%20in%20famiglia/Tecnologia%20in%20famiglia.code-workspace|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Gruntfuggly** [comment]
Looks like you're viewing the tree in 'flat' mode, which means the '(js)' is the path of the folder that the file is in.  If you click the view button (the one with two boxes with lines next to them) it will cycle through tree view, flat view and todo only view.

**Comment by crystalfp** [comment]
I said a stupid thing facepalm like... Yes the directory is called js.
Sorry for the noise
mario

**Comment by Gruntfuggly** [comment]
No probs. :grin:
