### ISSUE TITLE
Tags Only View shows less todos

### ISSUE THREAD

**Issue by eenpadvinder** [Gruntfuggly/todo-tree#191]
Hi! Thanks for the great work! 

I've got a problem when using Tags Only view: it doesn't find all todos. 

Flat shows 11 `@next`-todos

![afbeelding](https://user-images.githubusercontent.com/47245286/63340500-7c7a6080-c347-11e9-9894-a98639c9f829.png)

Tags Only shows 6 `@next`-todos

![afbeelding](https://user-images.githubusercontent.com/47245286/63340526-8a2fe600-c347-11e9-9d8d-8e7b32d2e07e.png)

Here's an example of a file that misses todos in Tags Only view

```md
# Projectloos

- [ ] Home-map leegmaken @next @today
- [ ] FW testomgeving fixen @next
- [x] Controleren welke issues nodig zijn VOOR conversie @today @done(2019-08-20)
- [ ] NS kosten declareren @next 
- [ ] BUCH multisignaal debuggen @next @today
```

Below are my json-settings. 

```json
    "todo-tree.hideTreeWhenEmpty": false,
    "todo-tree.statusBar": "tags",
    "todo-tree.showCountsInTree": true,
    "todo-tree.trackFile": false,
    "todo-tree.flat": true,
    "todo-tree.hideIconsWhenGroupedByTag": true,
    "todo-tree.tags": [
        "today",
        "next",
        "waiting",
        "someday"
    ],
    "todo-tree.regex": "((@|<!--|;|/\\*|^)\\s*($TAGS))",
    "todo-tree.labelFormat": "${before}  |  ${filename}",
    "todo-tree.excludeGlobs": [
        "*/Archief/*",
        "**/*.ahk"
    ],
```

Hope you can help! Let me know if you need anything else!

**Comment by eenpadvinder** [comment]
It appears to have something to do with the fact that I use the tags at the end (instead of the beginning) of the task. When I add some random text after the tags they show up

**Comment by Gruntfuggly** [comment]
With your config I see:
flat/tree view:
![image](https://user-images.githubusercontent.com/376658/63355445-09c8af80-c35e-11e9-9d7a-300df8602614.png)
tags only view:
![image](https://user-images.githubusercontent.com/376658/63355536-31b81300-c35e-11e9-82ba-ec8de66a5353.png)


or with grouping by tag enabled:
flat/tree view:
![image](https://user-images.githubusercontent.com/376658/63355691-73e15480-c35e-11e9-9503-d6f1e1dfe26a.png)
tags only view:
![image](https://user-images.githubusercontent.com/376658/63355734-878cbb00-c35e-11e9-886a-0356b7f9f80f.png)


Is that different to what you see?

**Comment by eenpadvinder** [comment]
I see the same. With one file it appears to work. Try these two:

[project.zip](https://github.com/Gruntfuggly/todo-tree/files/3523791/project.zip)

**Comment by Gruntfuggly** [comment]
OK - I can reproduce it now. Will investigate...

**Comment by Gruntfuggly** [comment]
Try the latest version - it as previously assuming that any text would be to the right of the tags. If it find the tag at the end of the line if now uses the text from before the tag.

**Comment by eenpadvinder** [comment]
Thanks! It's better but it seems it still only lists todos only once if they have the same name, even when they're in different files. 

Example: 
[project.zip](https://github.com/Gruntfuggly/todo-tree/files/3544908/project.zip)

**Comment by Gruntfuggly** [comment]
Found the bug - I'm amazed nobody found this one before!

**Comment by eenpadvinder** [comment]
Yep, fixed! Thanks so much!
