### ISSUE TITLE
Not working for multi line comments

### ISSUE THREAD

**Issue by ShadabFaiz** [Gruntfuggly/todo-tree#192]
Like the title says...it is not working with multi line comments
![Todo](https://user-images.githubusercontent.com/8160121/63409244-6be0ed80-c40e-11e9-929d-ee1e23ec31f4.png)

**Comment by Gruntfuggly** [comment]
Have you modified the regex to look for multi-line comments?
https://github.com/Gruntfuggly/todo-tree#multiline-todos

**Comment by Gruntfuggly** [comment]
Hi - have you got an update on this?

**Comment by ShadabFaiz** [comment]
@Gruntfuggly  Yeah, I found the solution. Since I mainly work on Front End and uses jsdoc styling, this works for both single line and multi-line:
`    "todo-tree.regex": "((.*\\*)|(//) )\\s*($TAGS).*(\\n\\s*(//|/\\*|\\*\\*)\\s{2,}.*)*",
`.
For another type of comment style, all you need to edit was **((.*\\*)|(//)** part.
I wonder why they don't offer functionality to set different comment style.

**Comment by Gruntfuggly** [comment]
> I wonder why such functionality is not available to set different comment style such for jsdoc/ C style doc etc.

Do you mean different regexes for different lanaguages?

**Comment by ShadabFaiz** [comment]
Yes.

**Comment by Gruntfuggly** [comment]
It's too difficult unfortunately - the way it currently works is to pass the regex to all files (using ripgrep). To have different regex's per language would require the search to be run multiple times. 

Its something I have thought about, but it would add quite a bit of complexity and would affect performance.

**Comment by Gruntfuggly** [comment]
Now you have the regex working, are you happy for me to close this issue?

**Comment by ShadabFaiz** [comment]
Yeah
