### ISSUE TITLE
Add border-radius option

### ISSUE THREAD

**Issue by kaykayehnn** [Gruntfuggly/todo-tree#193]
Currently the background decorations have rounded corners like this
![image](https://user-images.githubusercontent.com/19822240/63604493-941a4900-c5d4-11e9-851e-6e004566cf4e.png)

I think it would be useful to add a configuration option for the border radius, for example to make it 0 so that the boxes are rectangular
![image](https://user-images.githubusercontent.com/19822240/63604435-62a17d80-c5d4-11e9-9960-f6ae5e952a87.png)

I can make a PR for this if that's okay

**Comment by Gruntfuggly** [comment]
Hi - don't worry it will be easy enough to add.

**Comment by kaykayehnn** [comment]
Works great, thanks!
