### ISSUE TITLE
Not finding todos on 1.38.0-insider

### ISSUE THREAD

**Issue by misolori** [Gruntfuggly/todo-tree#195]
Issue Type: <b>Bug</b>

<img width="909" alt="image" src="https://user-images.githubusercontent.com/35271042/63715072-e1c2cb80-c7f7-11e9-9b8d-20d130bd15ab.png">

<img width="909" alt="image" src="https://user-images.githubusercontent.com/35271042/63715078-e2f3f880-c7f7-11e9-9d78-d491874e11ea.png">

This works on Stable (1.37) but not on Insiders.

Extension version: 0.0.142
VS Code version: Code - Insiders 1.38.0-insider (185308c0dd317d73fe4c19dea347582dee9650de, 2019-08-26T09:43:06.818Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Gruntfuggly** [comment]
Please could you set `"todo-tree.debug"` to true and see what comes out on the output window?

**Comment by Gruntfuggly** [comment]
I've just tried it in insiders (Ubuntu and Windows) and it seems to be OK for me. 

Hopefully there is something in the Output Window or maybe int the Developer Tools console log.

**Comment by misolori** [comment]
I tested this on my Windows machine and didn't see this happening (same repo) so this might be a Mac bug. Here's the output:

```log
Searching /Users/misolori/Projects/vscode...
Command: /Applications/Visual\ Studio\ Code\ -\ Insiders.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg --no-messages --vimgrep -H --column --line-number --color never --max-columns=1000 -e "((//|#|<!--|;|/\*|^)\s*(TODO|FIXME)|^\s*- \[ \])" -g "undefined/**/*" "/Users/misolori/Projects/vscode"
Found 0 items
Searching /Users/misolori/Projects/vscode...
Command: /Applications/Visual\ Studio\ Code\ -\ Insiders.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg --no-messages --vimgrep -H --column --line-number --color never --max-columns=1000 -e "((//|#|<!--|;|/\*|^)\s*(TODO|FIXME)|^\s*- \[ \])" -g "undefined/**/*" "/Users/misolori/Projects/vscode"
Found 0 items
Searching /Users/misolori/Projects/vscode...
Command: /Applications/Visual\ Studio\ Code\ -\ Insiders.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg --no-messages --vimgrep -H --column --line-number --color never --max-columns=1000 -e "((//|#|<!--|;|/\*|^)\s*(TODO|FIXME)|^\s*- \[ \])" -g "undefined/**/*" "/Users/misolori/Projects/vscode"
Found 0 items
```

**Comment by Gruntfuggly** [comment]
I've got a mac at home, so I'll try it out. Could you post your todo-tree settings?

**Comment by Gruntfuggly** [comment]
Hmm - seems to be OK on my mac. Can you send me a sample of the code containing some todos and your settings? Maybe your regex is not quite right?

**Comment by misolori** [comment]
Still having this issue, upon further inspecting it appears that it may be tied to the [`vscode`](http://github.com/microsoft/vscode) repo. I tried it in other repos and it's working.

Here's a sample of the type of ToDos we have:
<img width="341" alt="image" src="https://user-images.githubusercontent.com/35271042/65057528-98155e80-d927-11e9-9a75-a0eab1e58aa4.png">

**Comment by Gruntfuggly** [comment]
Just looking at your output above - it looks like you have an include glob defined:
`-g "undefined/**/*"`
Is that expected?

**Comment by misolori** [comment]
Where would I see this defined? I don't think I've ever explicitly set this.

**Comment by Gruntfuggly** [comment]
There are some settings: `todo-tree.filtering.includeGlobs` and `todo-tree.filtering.excludeGlobs`. It's possible they are defined in your workspace settings if they aren't visible in the user settings. There is also `todo-tree.ripgrepArgs` which could be defined, but that seems less likely.

**Comment by misolori** [comment]
That's odd, I searched for `todo-tree` in both my local user settings and in our workspace settings and don't see anything mentioned or set. Anywhere else I can look?

**Comment by Gruntfuggly** [comment]
Did you check the settings.json or just the GUI? It may not be noticeable in the GUI as the setting is an array which needs to be modified in the settings.json.
Settings which are modified should have a blue bar next to them in the GUI.

**Comment by misolori** [comment]
I searched in the json

**Comment by Gruntfuggly** [comment]
In the GUI, is **includeGlobs ** or **ripgrepArgs** highlighted as modified?

**Comment by Gruntfuggly** [comment]
Hang on - I know whats happened! In the tree view, right click on "Nothing found" and select **Reset Folder Filter**".

I don't know how it became `undefined/**/*` but it looks like at some point you have selected **Only Show This Folder and Subfolders**

**Comment by misolori** [comment]
I didn't even know you could right-click that, thanks! It now works as expected, not sure how I got to that state to begin with. But thanks!
