### ISSUE TITLE
excludeGlobs somewhat working

### ISSUE THREAD

**Issue by TheCrether** [Gruntfuggly/todo-tree#196]
so i wanted to exclude node_modules with this:
`"todo-tree.excludeGlobs": ["**/node_modules/**"],`

but i tried `node_modules/**` before and now todo tree thinks that this one is still active and i just keep getting errors though the debug logs says everything is ok and matches everything right and because of that i now dont have the todo output anymore

last three versions (143, 142, 141) don't work and uninstall also didnt help.

**Comment by Gruntfuggly** [comment]
I don't really understand what the problem is - Can you post your todo-tree config settings?

**Comment by TheCrether** [comment]
i had that problem at work, will send the config and the output of the debug window when im at work again

**Comment by Gruntfuggly** [comment]
Any luck?
