### ISSUE TITLE
Filename and Line Number (unclickable todos, Line NaN)

### ISSUE THREAD

**Issue by Quacky2200** [Gruntfuggly/todo-tree#197]
Due to how the line number is parsed in the filename, the extension breaks.

When using gvfs-samba/gvfs-sftp with nautilus, the colon is mistaken for a line number when it's still a valid path, this then generates a tooltip stating: `/run/user/1000/gvfs/sftp, Line: NaN`. I suspect this is due to how the colon is detected which is typically used to declare the line number. There should be a better way around this. For example with the below 'grep' command, a line number could be provided in a regex format of `:(\d+):\/\/ ?(?:todo[: ]*)(.*)`. I expect implementation will differ as this only retrieves the line number and TODO comment, etc. 

```
fred@host:~$ grep -Enor '// TODO(.*)' /run/user/1000/gvfs/sftp:host=127.0.0.1,port=2222,user=bob/home/bob/project1
/run/user/1000/gvfs/sftp:host=127.0.0.1,port=2222,user=bob/home/bob/project1/test.php:10:// TODO: This is a TODO
```

Unlike Windows; Linux (ext3/4 filesystems AFAIK) can allow more characters for file paths which is likely why this has not been seen as an issue. A person would usually escape unusual characters in bash (e.g. a colon unescaped would likely be used for a hostname and port number `curl "http://localhost:81/"`)
```
fred@host:~$ ls /run/user/1000/gvfs/sftp\:host\=127.0.0.1\,port\=2222\,user\=bob/
```

This bug also prevents a user from viewing a TODO when clicking on an TODO view item

Instead I would expect the tooltip to show `[workspace_dir]/folder1/file.ext, Line 10`. I would also expect that the TODO is clickable and takes me directly to the line number in the file.

Environment to reproduce:
- Gnome-shell environment with Nautilus and gvfs-sftp/gvfs-samba
- Mount location using Nautilus, use different port number & optionally specify a username in the connection field (e.g. `sftp://bob@127.0.0.1:2222/home/bob/`)
- Visual Studio Code + todo-tree extension

**Comment by Gruntfuggly** [comment]
Hi - I don't think I can easily reproduce this, however, if you can capture the output from the search in the todo tree output window, I can run it through and hopefully fix this.

**Comment by Quacky2200** [comment]
Hey,

First time debugging vscode extensions but turned out to be somewhat easy. I added a console log to the ripgrep Match and this was returned:
```
[Extension Host] Match constructor text:- /run/user/1000/gvfs/sftp:host=127.0.0.1,port=2222,user=bobo/home/bob/file.js:50:3:		// TODO: Implement
console.ts:137 [Extension Host] Match constructed obj:- {file: "/run/user/1000/gvfs/sftp", line: null, column: 50, match: "3:		// TODO: Implement"}
```

I decided to make a fix for this which is working for me and have created a pull-request as referenced above by GitHub

**Comment by Gruntfuggly** [comment]
Thanks for your work on this. :grin: 👍
