### ISSUE TITLE
ripgrep executable not found after update to 1.19.2

### ISSUE THREAD

**Issue by carlos-algms** [Gruntfuggly/todo-tree#2]
`todo-tree: ripgrep executable not found (C:\Users\Carlos\.vscode\extensions\Gruntfuggly.todo-tree-0.0.12\node_modules\vscode-ripgrep\bin\rg.exe)`

**Comment by Gruntfuggly** [comment]
There was an update to vscode-ripgrep and it stopped working with the latest version, so I tried to pick a specific version that was working. 
As a workaround, try the following (assuming you have node installed?):
```
cd C:\Users\Carlos\.vscode\extensions\Gruntfuggly.todo-tree-0.0.12
npm uninstall vscode-ripgrep
npm install vscode-ripgrep
```
Alternatively, you can manually install ripgrep and then point the preference `todo-tree.ripgrep` to point to it - that will prevent any future problems too.

**Comment by Gruntfuggly** [comment]
I've uploaded a new version which looks for the ripgrep executable that comes with vscode. This should be a bit more reliable (unless vscode is installed in a custom location).

**Comment by carlos-algms** [comment]
there is no way to identify vscode installation path ?

**Comment by Gruntfuggly** [comment]
There may be - I'll see if there is a way.

**Comment by Gruntfuggly** [comment]
The latest version should now be able to determine the path from the installation if it's not found in the default location.

**Comment by matthijs73** [comment]
Latest version 1.21.0 has the same problem again because they now use asar. Solution is to change it to (for Mac) "todo-tree.ripgrep": "/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg",

**Comment by Gruntfuggly** [comment]
Thanks - same problem for Ubuntu. I've updated the search paths.
