### ISSUE TITLE
How to get started?

### ISSUE THREAD

**Issue by kobi2187** [Gruntfuggly/todo-tree#20]
Sorry for the silly question, but on my vscode (version 1.23.0), your extension doesn't show up in the side bar.
How do I toggle it, or enable? I installed ripgrep and set its path in the settings.
The sidebar shows Explorer, search, scm, debug, and extensions.
within explorer I can see the gitlens sidebar, but nothing else.
Maybe update the docs if there's a really obvious step that I'm missing
I also tried the commands like todo-tree show tree view, but nothing seems to happen on screen.

**Comment by Gruntfuggly** [comment]
It will only appear when it finds TODOs in your files. If you create a new empty file and put 
`// TODO`
in it, when you save it the view should appear. If not, please let me know.

**Comment by kobi2187** [comment]
Thanks! it all works now. I wrote 'todo' lowercase, so it didn't trigger.
sorry for the false alarm. A short explanation in the docs would be nice though.

**Comment by Gruntfuggly** [comment]
Hi - I'm glad it's working 8-)

What would you suggest should be added? Just that it needs to be upper case, or that it only becomes visible when a TODO is found? Sometimes its difficult to write stuff from other peoples perspective, so any thoughts would be gratefully received! 8-)

**Comment by kobi2187** [comment]
by the way, you can add "case insensitivity" to the regex, to prevent this use case.
usually it's 'i' flag.

**Comment by Gruntfuggly** [comment]
The reason I didn't add case insensitivity by default is that I wanted to avoid false positives when searching.  The next release will have an option to pass extra parameter to ripgrep, so you could pass '-i' to  make it case insensitive.

I'll update the README.md with some extra information with the next release. 8-)

**Comment by kobi2187** [comment]
cool.  
if I remember correctly, `\b` matches word boundaries. maybe that helps.
