### ISSUE TITLE
Tree error: Only path et no ${after}

### ISSUE THREAD

**Issue by GrCOTE7** [Gruntfuggly/todo-tree#205]
Hi all,

I appreciate a lot this very helpfull plugin, but since yesterday, there is a trouble:

Now, I get in the tree the text of my Todo line only for the todo I already clicked...

For the other, I see the path (not very usefull...)

A picture is better as a long text:

http://prntscr.com/p41a9i

Is it a solution for that ?

Thanks.

**Comment by Gruntfuggly** [comment]
Please can you post me your `todo-tree.regex` setting if it is changed. Also, can you enable `todo-tree.debug` and copy the contents of the todo-tree output window so I can recreate it.

**Comment by Gruntfuggly** [comment]
Please try the latest version and let me know if it fixes this.
