### ISSUE TITLE
TODO only shows file path

### ISSUE THREAD

**Issue by WORMSS** [Gruntfuggly/todo-tree#206]
So today, I updated VSCode to the latest version, there was a quick flash of "TODO settings have moved" (or something to that, I didn't have time to read it)
I returned to my normal settings, "Flat List" "Group By Tag", 
And I am greeted with a wall of file paths, not very useful.

![image](https://user-images.githubusercontent.com/1384537/64602385-a1964800-d3b6-11e9-8a09-22afa612d0bc.png)

but also "Ungrouped by tag" does the same thing.

If I start clicking on a file, it flashes the panel and loads it into panel. But I am not gonna go through and start clicking on each file individually.

Does anyone know how to get back to the old VS code version and/or old version of this extension to get the thing working again quickly?

**Comment by Gruntfuggly** [comment]
If you go to the extensions view you can click the 'cog' icon and install a previous version of the extension - you should probably go back to version 0.0.145.

Please could you post your `todo-tree` settings so I can try to recreate the problem.

**Comment by Gruntfuggly** [comment]
Ah - it's OK - I've recreated it.

**Comment by WORMSS** [comment]
```jsonc
{
  // My obsolete ones
  "todo-tree.excludeGlobs": ["**/node_modules/**", "**/dist/**", "**/dist_electron/**"],
  "todo-tree.defaultHighlight": {
    "foreground": "green",
    "type": "none"
  },
  "todo-tree.flat": true,
  "todo-tree.grouped": true,
  "todo-tree.statusBar": "top three",
  "todo-tree.showCountsInTree": true,

  // What ever wasn't classed as obsolete
  "todo-tree.tree.flat": true,
  "todo-tree.tree.grouped": true,
  "todo-tree.tree.showCountsInTree": true,
  "todo-tree.general.statusBar": "top three"
}
```

**Comment by Gruntfuggly** [comment]
OK - found the problem.

**Comment by Gruntfuggly** [comment]
Please update to the latest version - hopefully you should be back working again.

**Comment by WORMSS** [comment]
I can confirm this has fixed the issue.. Thank you very much @Gruntfuggly
