### ISSUE TITLE
It stopped working

### ISSUE THREAD

**Issue by LeninZapata** [Gruntfuggly/todo-tree#207]
The extension stopped working, until yesterday it worked correctly but it stopped working, it shows me nothing on the tree panel.
https://i.imgur.com/fJRLPIK.jpg

**Comment by Gruntfuggly** [comment]
Hi - which version is installed? The error message in the bottom right suggests that the extension has not loaded properly - it could be that the extension host has crashed.

**Comment by Gruntfuggly** [comment]
This might be due to a mistake in 0.0.146 - can you update to the latest version 0.0.149 and confirm if it is still not working?

**Comment by CelticMinstrel** [comment]
I had some other cases of failed settings migration regarding the "flat" and "showInExplorer" settings, as well as highlights (both default and custom). It also didn't migrate the workspace settings. I had to fix all of these manually.

**Comment by Gruntfuggly** [comment]
Sorry about that. Hope it's all working again now.

It would be great if there was some support from vscode for migrating settings. :disappointed:

**Comment by CelticMinstrel** [comment]
Yeah, I just had to manually migrate the settings and everything worked again.

**Comment by Gruntfuggly** [comment]
There were a couple of issues with the migration code which should mean it works properly for others. Sorry it affected you!
