### ISSUE TITLE
Add to Activity Bar [feature request]

### ISSUE THREAD

**Issue by onetrev** [Gruntfuggly/todo-tree#21]
Now that VS Code 1.23 allows extensions to have their own view container and their own icon in the Activity Bar, I wondered if you'd considered adding support for this in todo-tree? Definitely would be nice to get it out of the File Explorer view. Thanks either way! Cheers.

Note -- more details here: https://code.visualstudio.com/updates/v1_23#_extension-authoring

**Comment by Gruntfuggly** [comment]
Yes - I was going to make it an option. The only slight wrinkle is that if you decide to keep the tree in the explorer view, the container will be empty - at the moment (AFAIK) the views can be hidden, but not the containers. I'll be trying some stuff out in the next couple of days...

**Comment by Gruntfuggly** [comment]
Please try the latest version. It adds the tree to the activity bar, and there is a new setting to remove the tree from the explorer view.

**Comment by debarbo** [comment]
This new feature was a great addition.
How about add a counter (badge) with how many TODO's or FIXME's are in the document?
Something like this: 
![2018-05-11_17-54-23](https://user-images.githubusercontent.com/9376169/39946615-3bbead4c-5545-11e8-8d56-7cd4f3ece900.png)

**Comment by Gruntfuggly** [comment]
8-) That would be nice, but unfortunately there's API for that yet as far as I know. If the vscode guys make that available I'll definitely add it...

**Comment by onetrev** [comment]
Awesome, works perfectly. Thank you so much. And wow that was fast!
