### ISSUE TITLE
ripgrep color argument error using `RIPGREP_CONFIG_PATH`/*rg.conf*

### ISSUE THREAD

**Issue by rivy** [Gruntfuggly/todo-tree#212]
```shell
todo-tree v0.0.151
VSCode v1.36.0
```

`todo-tree` triggers an error dialog when scanning and fails to function if a `ripgrep` configuration file using a color flag (eg, `--color=always`) is setup for use.

![todo-tree rg error](https://user-images.githubusercontent.com/80132/64749092-f54d8200-d4d9-11e9-9f58-3586723ac9ec.png)

```shell
C:\>ver
Microsoft Windows [Version 10.0.18362.295]

C:\>echo RIPGREP_CONFIG_PATH
RIPGREP_CONFIG_PATH=C:\Users\Roy\.sh\config\rg.conf

C:\>cat C:\Users\Roy\.sh\config\rg.conf
# `rg` (ripgrep) configuration file

--color=always

--smart-case
# kb
--type-add
kb:**/kb-*.{markdown,mkdown,mkdn,mkd,mdown,md,txt}
# markdown type
--type-add
markdown:*.{markdown,mkdown,mkdn,mkd,mdown,md}
--type-add
mkd:*.{markdown,mkdown,mkdn,mkd,mdown,md}
--type-add
md:*.{markdown,mkdown,mkdn,mkd,mdown,md}
```

If the `--color=...` option is removed from the configuration file, `todo-tree` returns to normal functionality.

Using `--no-config` in the custom ripgrep arguments section makes no difference.

**Comment by Gruntfuggly** [comment]
I've added it to the standard command.

**Comment by rivy** [comment]
👍
