### ISSUE TITLE
Respect VSCode "files.exclude"

### ISSUE THREAD

**Issue by JonathanTroyer** [Gruntfuggly/todo-tree#215]
VSCode has a [built-in exclude setting](https://code.visualstudio.com/Docs/editor/codebasics#_advanced-search-options) that is used in both the explorer pane and search pane. It would make sense for this extension to also use either `files.exclude` or `search.exclude` (I would think `files.exclude` would make more sense).

**Comment by Gruntfuggly** [comment]
I've just uploaded a new version with support for the built in `files.exclude`. It's disabled by default as I don't want to surprise any existing users.

Please let me know if it works as you'd expect.

**Comment by Gruntfuggly** [comment]
This should be fixed in the most recent version.

**Comment by JonathanTroyer** [comment]
Fixed. Thanks!!!
