### ISSUE TITLE
Fortran support

### ISSUE THREAD

**Issue by danlub** [Gruntfuggly/todo-tree#216]
Hi, I don't know how to make this work for fortran source files
I'm wondering why I doesn't work for them

**Comment by danlub** [comment]
Just found it
Although I don't know how to do the regex thingy, I got it to work

Just in case anyone arrives here:

`((//|#|<!--|;|!|C||/\*|^)\s*($TAGS)|^\s*- \[ \])`

Closing now

**Comment by Gruntfuggly** [comment]
I'll add it to the wiki page when I pull my finger out and get round to writing it!
