### ISSUE TITLE
Only look on modified file

### ISSUE THREAD

**Issue by eMerzh** [Gruntfuggly/todo-tree#219]
Hey, thanks for this extension!

i tried to activate it on a OLD project, but it was too noisy with many todo/fixme to be usefull

it could be great if i could only activate the tree for modified files only.
(ideally i would have like to filter for my branch pr smth... but i guess it's way harder ;-) )

**Comment by Gruntfuggly** [comment]
When you say modified, I assume you mean uncommitted changes? That might add quite an overhead to the search process because it would need to interrogate git for each file it found.

I'll try adding something.

**Comment by Gruntfuggly** [comment]
Sorry, but I don't think I'm going to get round to trying this - it's potentially quite a large change. As it hasn't been requested by anybody else, I'm going to close it.
