### ISSUE TITLE
Hide / Show folder is not working

### ISSUE THREAD

**Issue by kanlukasz** [Gruntfuggly/todo-tree#220]
Hi,
I see a problem with the folder exclusion option, which generally doesn't work. There are many strange problems.
I'll show you this on the gif below:

![yhhh222](https://user-images.githubusercontent.com/30685349/65258558-6527c200-db03-11e9-9b66-74cd18e4380d.gif)

System info:
```
Version: 1.38.1 (system setup)
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:35:15.005Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
```

**Comment by Gruntfuggly** [comment]
Are you selecting the option before it has had a chance to run the search and rebuild the tree? Maybe it needs a mutex or something.
Can you open the debug in the Output View and see what is happening while you're selecting the options?

**Comment by kanlukasz** [comment]
I waited for everything to run and then saw in the status bar:
![obraz](https://user-images.githubusercontent.com/30685349/65259551-1e3acc00-db05-11e9-959e-370dd8d69761.png)
And then I tried to exclude again, but still nothing.

Options such as:
![obraz](https://user-images.githubusercontent.com/30685349/65259595-33175f80-db05-11e9-9c7f-bff74ed21078.png)
they didn't fix it

Below another gif:
![333](https://user-images.githubusercontent.com/30685349/65260778-33b0f580-db07-11e9-974b-e642430068cf.gif)

Below output debug ( this happened when I try to exclude ):
[out.txt](https://github.com/Gruntfuggly/todo-tree/files/3632201/out.txt)

**Comment by Gruntfuggly** [comment]
When you select those options it basically creates include and exclude gobs. If you look at the command that is generated when you select *Hide This Folder* you should see `-g "!x/y/z/**/*"` added to the command. Can you see that happening?

**Comment by kanlukasz** [comment]
I see this in the debug output:
`-g "!c:\xampp\htdocs\my\website\www\wp-admin\includes/**/*"`

**Comment by Gruntfuggly** [comment]
OK, but you're still seeing TODOs found from in that folder after that command?
Can you post the whole command?

**Comment by kanlukasz** [comment]
Yes, still i can't exclude
Of course, here is the whole command (another example):

`Command: "c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg.exe" --no-messages --vimgrep -H --column --line-number --color never --max-columns=1000 -e "(//|#|<!--|/\*|^\s*\*)\s*(TODO)" -g "!c:\xampp\htdocs\xxxxx\xxxxxx\xxxxxx\wp-admin\includes/**/*" "c:\xampp\htdocs\xxxxxx\xxxxxx\wp-content\plugins\przelewy24"`

**Comment by Gruntfuggly** [comment]
So when the command above is run, do you see the results from being found in the output window, or is it just that they don't get removed from the tree?

**Comment by kanlukasz** [comment]
Unfortunately, it has not been removed from the tree.

_I have an idea - let's try to reproduce this problem together._

To make sure it wasn't my fault, I tried again on a clean portable installation (the latest version of Insider) with no additional plugin except TodoTree, of course

#### Step to reproduce the problem:
1. Run the clear VSCode installation with default settings
2. Install ToDoTree with default settings
3. Download Wordpress from the [official website](https://wordpress.org/latest.zip) to local disk
3. Open the Wordpress folder in VSCode
4. Try to hide the `wp-admin` folder
5. Exclusion does not work 😞 

Did it cause the same problem for you?

**Comment by Gruntfuggly** [comment]
I'll try it and get back to you.

**Comment by Gruntfuggly** [comment]
No - it works fine for me.

Do you have files open which are in the folder? The extension also searches in open files. Does it work if you close all files?

**Comment by kanlukasz** [comment]
Hmm, that's weird 🤔 

May i ask you what operating system are you using?
Is it Windows 10 like mine?

All files are closed - Hiding still not working
The extension finds all TODO correctly and works great, the only problem is excluding folders

Can we test something else?

**Comment by kanlukasz** [comment]
Ps.:
I decided to try again on a more simplified structure to perform such a tests.
I hope this helps you find the problem

---

### All detailed steps:

**1.** I created a simple app structure on the `C` hard drive (root folder)
**2.** I created portable fresh VSCode Insider on hard drive `C` (root folder)
![obraz](https://user-images.githubusercontent.com/30685349/65371711-b3a1a180-dc66-11e9-8c81-c3e84d2a7e5f.png)

---
**3.** I open `VSCode`, install `TodoTree`, open my app folder in `VSCode`
`TodoTree` has found three todos in my app - that's fine
![obraz](https://user-images.githubusercontent.com/30685349/65371751-2f9be980-dc67-11e9-83ba-b28b8d679d3e.png)
**Here's what comes from the debug results:**
```
Searching c:\xapp...
Command: "c:\xvscode\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg.exe" --no-messages --vimgrep -H --column --line-number --color never --max-columns=1000 -e "((//|#|<!--|;|/\*|^)\s*(TODO|FIXME)|^\s*- \[ \])" "c:\xapp"
c:\xapp\public\index.php:5:1:// TODO: index todo
c:\xapp\src\src.php:5:1:// TODO: src todo

c:\xapp\views\views.php:5:1:// TODO: views todo

 Match (File): {"file":"c:\\xapp\\public\\index.php","line":"5","column":"1","match":"// TODO: index todo"}
 Match (File): {"file":"c:\\xapp\\src\\src.php","line":"5","column":"1","match":"// TODO: src todo"}
 Match (File): {"file":"c:\\xapp\\views\\views.php","line":"5","column":"1","match":"// TODO: views todo"}
Found 3 items
```

---

**4.** Run `F1` and type `Todo Tree: Reset Folder Filter` **(to make sure everything has been reset)**
Here's what comes from the debug results:
```
Searching c:\xapp...
Command: "c:\xvscode\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg.exe" --no-messages --vimgrep -H --column --line-number --color never --max-columns=1000 -e "((//|#|<!--|;|/\*|^)\s*(TODO|FIXME)|^\s*- \[ \])" "c:\xapp"
Folder filter include:[]
Folder filter exclude:[]
c:\xapp\src\src.php:5:1:// TODO: src todo
c:\xapp\views\views.php:5:1:// TODO: views todo

c:\xapp\public\index.php:5:1:// TODO: index todo

 Match (File): {"file":"c:\\xapp\\src\\src.php","line":"5","column":"1","match":"// TODO: src todo"}
 Match (File): {"file":"c:\\xapp\\views\\views.php","line":"5","column":"1","match":"// TODO: views todo"}
 Match (File): {"file":"c:\\xapp\\public\\index.php","line":"5","column":"1","match":"// TODO: index todo"}
Found 3 items
```
---

**5.** Now I clearing debug output and trying to hide the `public` folder
Here's what comes from the debug results:
```
Searching c:\xapp...
Command: "c:\xvscode\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg.exe" --no-messages --vimgrep -H --column --line-number --color never --max-columns=1000 -e "((//|#|<!--|;|/\*|^)\s*(TODO|FIXME)|^\s*- \[ \])" -g "!c:\xapp\public/**/*" "c:\xapp"
Folder filter include:[]
Folder filter exclude:["c:\\xapp\\public/**/*"]
c:\xapp\public\index.php:5:1:// TODO: index todo
c:\xapp\src\src.php:5:1:// TODO: src todo

c:\xapp\views\views.php:5:1:// TODO: views todo

 Match (File): {"file":"c:\\xapp\\public\\index.php","line":"5","column":"1","match":"// TODO: index todo"}
 Match (File): {"file":"c:\\xapp\\src\\src.php","line":"5","column":"1","match":"// TODO: src todo"}
 Match (File): {"file":"c:\\xapp\\views\\views.php","line":"5","column":"1","match":"// TODO: views todo"}
Found 3 items
Applying globs to 3 items...
Remaining items: 3

```
**The folder `public` has not hidden and TodoTree still sees 3 todos in my app**
![obraz](https://user-images.githubusercontent.com/30685349/65371826-e4360b00-dc67-11e9-8bd3-00ad9c96eaca.png)


If I try to hide the `public` folder again several times
Here's what comes from the debug results:
```
Folder filter include:[]
Folder filter exclude:["c:\\xapp\\public/**/*"]
Folder filter include:[]
Folder filter exclude:["c:\\xapp\\public/**/*"]
Folder filter include:[]
Folder filter exclude:["c:\\xapp\\public/**/*"]
```
but still not working

---

**6.** Now (for example) if i try to use `Only Show This Folder` - **Everything in TODO has disappeared**:
![obraz](https://user-images.githubusercontent.com/30685349/65372062-36c4f680-dc6b-11e9-95f5-27e80de3ea83.png)
Here's what comes from the debug results:
```
Searching c:\xapp...
Command: "c:\xvscode\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg.exe" --no-messages --vimgrep -H --column --line-number --color never --max-columns=1000 -e "((//|#|<!--|;|/\*|^)\s*(TODO|FIXME)|^\s*- \[ \])" -g "c:\xapp\src/*" "c:\xapp"
Folder filter include:["c:\\xapp\\src/*"]
Folder filter exclude:[]
Found 0 items
Applying globs to 0 items...
Remaining items: 0

```

## Here is a new gif with everything I described above

![calosc](https://user-images.githubusercontent.com/30685349/65372168-b0a9af80-dc6c-11e9-9163-fec796fea40f.gif)

**Comment by Gruntfuggly** [comment]
I have a windows machine at work so I'll try this tomorrow. Thanks for the detailed steps. 👍

**Comment by kanlukasz** [comment]
OK, many thanks for quick reply. Very professional support 👍

**Comment by Gruntfuggly** [comment]
I've got a fix - needs a little bit more testing before I release though.

**Comment by kanlukasz** [comment]
I did a quick test. Hiding folders works fine, but there is still a problem with the "Show this folder only" option. If I set it, everything disappears. Example gif below:

![wwww](https://user-images.githubusercontent.com/30685349/65713176-eac5e780-e098-11e9-84a2-65786cdca164.gif)

**Comment by Gruntfuggly** [comment]
Can you post the contents of the output window? It should dump the globs that are generated.

**Comment by kanlukasz** [comment]
Yes of course. I reset everything and did the test
Debug results after clicking `Only Show This Folder` 
```
Searching c:\xapp...
Command: "c:\xvscode\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg.exe" --no-config --no-messages --vimgrep -H --column --line-number --color never --max-columns=1000 -e "((//|#|<!--|;|/\*|^)\s*(TODO|FIXME)|^\s*- \[ \])" -g "**xapp/src/*" "c:\xapp"
Folder filter include:["**xapp/src/*"]
Folder filter exclude:undefined
c:\xapp\src\src.php:5:1:// TODO: src todo

 Match (File): {"file":"c:\\xapp\\src\\src.php","line":"5","column":"1","match":"// TODO: src todo"}
Found 1 items
Applying globs to 1 items...
Remaining items: 0

```

**Comment by Gruntfuggly** [comment]
OK - it's malformed the glob because it's the top folder. Could you try a small fix for me? If you edit `.vscode/extensions/gruntfuggly.todo-tree-0.0.154/utils.js` (or whatever your path is) and change line 205 to:
`        return ( "**/" + fp + filter ).replace( /\/\//g, '/' );`
ie - add the "/" after the "**".

Let me know if that works.

**Comment by kanlukasz** [comment]
Line 205 after my change
`return glob = ( "**/" + fp + filter ).replace( /\/\//g, '/' );`

Works OK 😁

**Comment by Gruntfuggly** [comment]
Great - thanks. I'll fix it in the next update!
