### ISSUE TITLE
Second time broken after update

### ISSUE THREAD

**Issue by rlodbrok** [Gruntfuggly/todo-tree#221]
Hi,
Please do not upgrade without some kind of prompt & warning that the customization syntax is changed and setting have to be "moved" changed. All my customization had to be redone with no warning - a big waste of time at the wrong time!

**Comment by Gruntfuggly** [comment]
You should have seen a notification telling you that the settings have changed and it should have automatically migrated your settings?

Can you let me know which settings you had to change?

Sorry for the inconvenience, but there are so many settings now that they needed to be organised.

**Comment by dklotz** [comment]
My settings also where not auto-migrated and I had to change them by hand, thankfully the change was quite short. 

I had to change this:
```
"todo-tree.defaultHighlight": {
    "icon": "alert",
    "foreground": "#FFFFFF",
    "background": "#FFBD2C",
    "type": "text"
},
"todo-tree.customHighlight": {
    "TODO": {},
    "FIXME": {
        "icon": "zap",
        "background": "#F06292"
    }
},
```

... to this:
```
"todo-tree.highlights.defaultHighlight": {
    "icon": "alert",
    "foreground": "#FFFFFF",
    "background": "#FFBD2C",
    "type": "text"
},
"todo-tree.highlights.customHighlight": {
    "TODO": {},
    "FIXME": {
        "icon": "zap",
        "background": "#F06292"
    }
},
```

(Those where the only custom settings I had)

**Comment by dklotz** [comment]
@Gruntfuggly I did as you suggested: Put the old settings back (in addition to the new settings), reset cache, quit VSCode, start VSCode (from the CLI using `code .` in my project folder it that matters) => No notification of any kind.

**Comment by Gruntfuggly** [comment]
Thanks - looks like there is a bug when migrating 'object' settings. Can you just try adding 
`"todo-tree.general.statusBar": "total"`
to your settings and restart - hopefully you should see the warning this time.
