### ISSUE TITLE
Regex fails to evaluate correctly?

### ISSUE THREAD

**Issue by Dan9a7b** [Gruntfuggly/todo-tree#222]
I am trying to use this regex:
```
(?:(?:(\/\/|\#|\;|\^)|(\/\*)|(\<\!\-\-))(?(1).{0,100}?)(?(2)[\s\S]{0,500}?)(?(3)[\s\S]{0,500}?)($TAGS)(?(2)[\s\S]{0,500}?(\*\/))(?(3)[\s\S]{0,500}?(\-\-\>)))
```
([working example on regex101](https://regex101.com/r/hJ2oC9/35))

Unfortunatly, the 2nd and 3rd part (responsible for `/* ... */`, `<!-- ... -->` multiline comments respectvely fail to evaluate (they literatly are ignored)).

My configuration:
```
  "todo-tree.general.tags": [
    "todo",
    "@todo",
    "fixme",
    "@fixme",
  ],
  // Semi-working Single-line: "((?:(?:/\\*|\\*|<!--|!|-)|(?://|#|;|\\^)).*?[@]?($TAGS))[:]?",
  // Semi-working Multi-line:  "((?:(?://|#|;|\\^).*(todo|@todo|fixme|@fixme))|(?:/\\*[\\s\\S]*?(todo|@todo|fixme|@fixme)[\\s\\S]*?\\*/)|(?:<!--[\\s\\S]*?(todo|@todo|fixme|@fixme)[\\s\\S]*?-->))",
  "todo-tree.ripgrep.ripgrepArgs": "--pcre2",
  "todo-tree.regex.regex": "(?:(?:(\\/\\/|\\#|\\;|\\^)|(/\\*)|(\\<\\!\\-\\-))(?(1).{0,100}?)(?(2)[\\s\\S]{0,500}?)(?(3)[\\s\\S]{0,500}?)($TAGS)(?(2)[\\s\\S]{0,500}?(\\*\\/))(?(3)[\\s\\S]{0,500}?(\\-\\-\\>)))",
  "todo-tree.regex.regexCaseSensitive": false,
  "todo-tree.highlights.defaultHighlight": {
    "type": "tag",
  },
  "todo-tree.highlights.customHighlight": {
    "todo": {
      "icon": "arrow-right",
      "iconColour": "green"
    },
    "@todo": {
      "icon": "arrow-right",
      "iconColour": "green"
    },
    "fixme": {
      "icon": "alert",
      "iconColour": "red"
    },
    "@fixme": {
      "icon": "alert",
      "iconColour": "red"
    }
  },
```

**Comment by Dan9a7b** [comment]
ah sorry, `--multiline` solved the problem. 

working configuration:
```
  "todo-tree.general.tags": [
    "todo",
    "@todo",
    "fixme",
    "@fixme",
  ],
  "todo-tree.ripgrep.ripgrepArgs": "--multiline --pcre2",
  "todo-tree.regex.regex": "(?:(?:(\\/\\/|\\#|\\;|\\^)|(/\\*)|(\\<\\!\\-\\-))(?(1).{0,100}?)(?(2)[\\s\\S]{0,2000}?)(?(3)[\\s\\S]{0,2000}?)($TAGS)(?(2)[\\s\\S]{0,2000}?(\\*\\/))(?(3)[\\s\\S]{0,2000}?(\\-\\-\\>)))",
  "todo-tree.regex.regexCaseSensitive": false,
  "todo-tree.highlights.defaultHighlight": {
    "type": "tag",
  },
  "todo-tree.highlights.customHighlight": {
    "todo": {
      "icon": "arrow-right",
      "iconColour": "green"
    },
    "@todo": {
      "icon": "arrow-right",
      "iconColour": "green"
    },
    "fixme": {
      "icon": "alert",
      "iconColour": "red"
    },
    "@fixme": {
      "icon": "alert",
      "iconColour": "red"
    }
  },
```

**Comment by Gruntfuggly** [comment]
Wow - that's a pretty complex regex. Currently the extension only enables `--multiline` automatically if it finds `\n` in the regex. Glad you got it working!

**Comment by Dan9a7b** [comment]
Thank you!
this is the next "version" of the expression: 
```
(?:(?:(\/\/|\#|\;|\^)|(\/\*)|(\<\!\-\-))(?(1).{0,50}?)(?(2)[\s\S]{0,500}?)(?(3)[\s\S]{0,500}?)(TODO)(?(1).*?\n(?:.*?\1.*?\n){0,20})(?(2)[\s\S]{0,500}?(\*\/))(?(3)[\s\S]{0,500}?(\-\-\>)))
```
[Working example on regex101](https://regex101.com/r/hJ2oC9/36)

This regex is quite simple. it consists of only from 4 parts:
1) `(?:(\/\/|\#|\;|\^)|(\/\*)|(\<\!\-\-))`
2) `(?(1).{0,50}?)(?(2)[\s\S]{0,500}?)(?(3)[\s\S]{0,500}?)`
3) `($TAGS)`
4) `(?(1).*?\n(?:.*?\1.*?\n){0,10})(?(2)[\s\S]{0,500}?(\*\/))(?(3)[\s\S]{0,500}?(\-\-\>)))`

(i initially planned to have this same regex in a slightly different version: [something like this](https://regex101.com/r/hJ2oC9/37) but it seemed that having multiple `($TAGS)` was a problem :/ (or at least I thought so before I discovered `--multiline`))

the idea behind the version from the 1st link is to have three capture groups:
`(\/\/|\#|\;|\^)`, `(\/\*)`, `(\<\!\-\-)` and then use regex-if-statments `(?(1)true|false)`, `(?(2)true|false)`, `(?(3)true|false)` to determine what should be between comment start and `($TAGS)` (part #2) as well as between `($TAGS)` and the end of the comment (part #4) 

(in case of single line comments `(?(1).*?\n(?:.*?\1.*?\n){0,10})` means that: (1) finish the line with `.*?\n`, and then (2) allow at most 10 line, that start with the same comment as the one saved inside capture group `\1`)

I believe that his regex is currently "perfect" (i need to debug it a bit more to be sure about that, but so far it behaves correctly in the regex101.com). If you want to use it feel free. 

unfortunately, `ripgrep` have problems with evaluating it...
```
// TODO

/*
```
is interpreted as a single comment block for some reason, and i have no idea what's wrong, but i believe that all i need to do is to find a correct configuration flag and it'll will work.

**Comment by Dan9a7b** [comment]
I think i know why 
```
// TODO

/*
```
is interpreted as a single block, but this is just an assumption. It's possible I am wrong.  

I believe there might be a bug in `todo-tree`'s functionality responsible for displaying multiline comment results. maybe a buggy offset somewhere in the source?
![b2VBV](https://user-images.githubusercontent.com/23025282/65724608-10f78180-e0b1-11e9-8a32-253120eb9186.png)

**Comment by Gruntfuggly** [comment]
If you enable `todo-tree.debug` you should find an Output View (Todo-Tree) which will show you exactly what ripgrep is finding. If you copy and paste the results, I'll see if I can reproduce it.

**Comment by Dan9a7b** [comment]
```
"todo-tree.general.tags": [
    "todo",
    "@todo",
    "fixme",
    "@fixme",
  ],
  "todo-tree.general.debug": true,
  "todo-tree.filtering.excludeGlobs": [
    "${workspaceRoot}/.backup"
  ],
  "todo-tree.ripgrep.ripgrepArgs": "--multiline --pcre2",
  "todo-tree.regex.regex": "(?:(?:(?P<single>\\/\\/|\\#)|(?P<multi_1>\\/\\*)|(?P<multi_2>\\<\\!\\-\\-))(?(single).*?)(?(multi_1)[\\s\\S]{0,500}?)(?(multi_2)[\\s\\S]{0,500}?)($TAGS)(?(single)(?:.*?\\n)(?:.*?((?P=single)).*?\\n){0,10})(?(multi_1)[\\s\\S]{0,500}?(\\*\\/))(?(multi_2)[\\s\\S]{0,500}?(\\-\\-\\>)))",
  "todo-tree.regex.regexCaseSensitive": false,
  "todo-tree.highlights.defaultHighlight": {
    "type": "tag",
    "icon": "kebab-horizontal",
    "iconColour": "gray"
  },
  "todo-tree.highlights.customHighlight": {
    "todo": {
      "icon": "arrow-right",
      "iconColour": "green"
    },
    "@todo": {
      "icon": "arrow-right",
      "iconColour": "green"
    },
    "fixme": {
      "icon": "alert",
      "iconColour": "red"
    },
    "@fixme": {
      "icon": "alert",
      "iconColour": "red"
    }
  },
```
[debug data from `output > todo-tree` for the above configuration](https://pastebin.com/DvVprmb4)

```
  "todo-tree.general.tags": [
    "todo",
    "@todo",
    "fixme",
    "@fixme",
  ],
  "todo-tree.general.debug": true,
  "todo-tree.filtering.excludeGlobs": [
    "${workspaceRoot}/.backup"
  ],
  "todo-tree.ripgrep.ripgrepArgs": "--multiline --pcre2",
  "todo-tree.regex.regex": "((?:(\\/\\/|\\#|\\;|\\^)(?:.{0,50}?)($TAGS)(?:.*\\n)(?:.*?(\\2).*?\\n){0,10})|(?:(\\/\\*)[\\s\\S]{0,500}?($TAGS)[\\s\\S]{0,500}?(\\*\\/))|(?:(\\<\\!\\-\\-)[\\s\\S]{0,500}?($TAGS)[\\s\\S]{0,500}?(\\-\\-\\>)))",
  "todo-tree.regex.regexCaseSensitive": false,
  "todo-tree.highlights.defaultHighlight": {
    "type": "tag",
    "icon": "kebab-horizontal",
    "iconColour": "gray"
  },
  "todo-tree.highlights.customHighlight": {
    "todo": {
      "icon": "arrow-right",
      "iconColour": "green"
    },
    "@todo": {
      "icon": "arrow-right",
      "iconColour": "green"
    },
    "fixme": {
      "icon": "alert",
      "iconColour": "red"
    },
    "@fixme": {
      "icon": "alert",
      "iconColour": "red"
    }
  },
```
[debug data from `output > todo-tree` for the above configuration](https://pastebin.com/Y6jb3gmr)

yup, like I thought, `TODO-TREE` can't handle multiline comments. my guess is, you are using `ripgrep` to search the output from the `ripgrep -e "<custom regex provided in todo-tree.regex.regex>"`, for all occurrences of `TODO`(or other tags), assuming that each `TODO` marks start of the new comment.

**Comment by Gruntfuggly** [comment]
Cool - I look forwards to seeing what you come up with.
