### ISSUE TITLE
trouble with --no-config

### ISSUE THREAD

**Issue by martin127** [Gruntfuggly/todo-tree#225]
Hi, 

I had some trouble with the --no-config option introduced. In fact, my vs.code installation comes with a seemingly older ripgrep version that does not support it, but is used by todo-tree by default if nothing else is specified. When I downloaded a newer ripgrep binary  and configured todo-tree to use that one, it seemed to work.

Could you please work with the team of vs.code to have that version updated? 
Or maybe use that option only if the rigrep version is sufficiently new?

Best Regards,
Martin.

**Comment by Gruntfuggly** [comment]
I didn't realise it was a newer feature of ripgrep. I'll remove it from the default arguments and add it as a default to `todo-tree.ripgrepArgs`. That way it can be removed if necessary.

Sorry for the inconvenience.

**Comment by Gruntfuggly** [comment]
I've uploaded version 0.0.158. You can now remove the `--no-config` from the `todo-tree.ripgrepArgs`.

**Comment by martin127** [comment]
Nigel,

Thank you for the quick response! I’ll give it a try.

Best Regards,
                Martin.
