### ISSUE TITLE
Option to exclude git submodules

### ISSUE THREAD

**Issue by letmaik** [Gruntfuggly/todo-tree#226]
I often include external dependencies via git submodules (in C++ projects) and currently there's no easy way to filter them out as the base folder where submodules are placed into can have different names and possibly extra files as well. It would therefore be great if there was an option to stop recursing if a folder is a submodule.

**Comment by Gruntfuggly** [comment]
How do you know if a folder is a submodule? The recursion is handled by ripgrep itself - the extension just tells it the root path to start the search from. If there is a way to determine how to stop recursing then there may be a way to pass that to ripgrep.

**Comment by letmaik** [comment]
Looks like we would need to implement it in https://github.com/BurntSushi/ripgrep/issues/23 first. A work-around could be to determine submodules ourselves (e.g. by ignoring folders that have a `.git` file) and pass the relevant ignore patterns to ripgrep.

**Comment by Gruntfuggly** [comment]
To be honest, I have similar reservations as BurntSushi has. It feels like quite a specialised feature.

It might be simpler to create a totally separate extension that walks the folder tree, generates the globs and automatically update vscode's `files.exclude` setting. Todo tree now has an option to use the `files.exclude`.

**Comment by letmaik** [comment]
I think `files.exclude` wouldn't be optimal as I don't want to hide the submodules in the explorer, just ignore them during search/TODO/etc., so probably it would have to be `todo-tree.filtering.excludeGlobs`.
Maybe another option would be to allow to use `git grep` instead of `rg` which already filters out submodules. A downside is that `git grep` can only be used inside git repos, so some additional logic would be required.

**Comment by Gruntfuggly** [comment]
I'll have a look at using git grep. I assume there will be a performance drop, but that may not be much of an issue. The only other potential problem is getting the results into a form that I can extract from easily.

**Comment by Gruntfuggly** [comment]
The latest version now has an `todo-tree.filtering.ignoreGitSubmodules` flag. This should hide any folders in the tree containing a `.git` folder.

**Comment by letmaik** [comment]
Hm, submodules have a `.git` file, but not a `.git` folder. Which git version did you use to test this?

**Comment by Gruntfuggly** [comment]
Ah - my mistake. I assumed it was a folder and tested it as such. I'll modify it to check for a file instead.

**Comment by Gruntfuggly** [comment]
OK, try version 0.0.160

**Comment by letmaik** [comment]
Works great, thanks! :)
