### ISSUE TITLE
Glob application removes all results if "filtering.includeGlobs" is empty

### ISSUE THREAD

**Issue by djkeeg** [Gruntfuggly/todo-tree#227]
**Settings**
```{    
"todo-tree.highlights.customHighlight": {
        "NOTE": {
            "icon": "info",
            "foreground": "cyan",
            "iconColour": "cyan",
            "hideFromTree": true
        }
    },
    "todo-tree.highlights.defaultHighlight": {
        "icon": "check",
        "type": "line",
        "foreground": "orange",
        "background": "",
        "opacity": 100,
        "iconColour": "orange"
    },
    "todo-tree.regex.regexCaseSensitive": false,
    "todo-tree.filtering.excludeGlobs": [
        // "node_modules"
    ],
    "todo-tree.filtering.includeGlobs": [
        // "**"
    ],
    "todo-tree.general.tags": [
        "TODO",
        "FIXME",
        "NOTE"
    ],
    "todo-tree.general.debug": true,
    "todo-tree.filtering.passGlobsToRipgrep": false
```
**Log**
```
Found 50 items
Applying globs to 50 items...
Remaining items: 0
```

_After I set includeGlobs to "**"_
```
Found 52 items
Applying globs to 52 items...
Remaining items: 52
```

If `passGlobsToRipgrip` is `true`, then the search finds zero results with out `includeGlobs` set.'

I also verified that there are not 'todo-tree' settings in my workspace settings.

**Comment by djkeeg** [comment]
The issue seems to only be present on one of my projects, even though the configuration is the same.

**Comment by djkeeg** [comment]
```
Searching c:\Users\dylan.keegan\Documents\repositories\Honeycomb...
Command: "c:\Users\dylan.keegan\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg.exe" --no-config --no-messages --vimgrep -H --column --line-number --color never --max-columns=1000 -i  -e "((//|#|<!--|;|/\*|^)\s*(TODO|FIXME|NOTE)|^\s*- \[ \])" -g "c:\Users\dylan.keegan\Documents\repositories\Honeycomb\src\order-entry/*" "c:\Users\dylan.keegan\Documents\repositories\Honeycomb"
Found 0 items
Applying globs to 0 items...
Remaining items: 0
```

Perhaps this is the guilty line `"c:\Users\dylan.keegan\Documents\repositories\Honeycomb\src\order-entry/*" `

What would cause this to be the pattern instead of `"c:\Users\dylan.keegan\Documents\repositories\Honeycomb\*"` (the project root).

**Comment by Gruntfuggly** [comment]
Have you used the folder filter context menu? Try right clicking in the tree and select 'Reset Folder FIlter'.

**Comment by djkeeg** [comment]
Ah, silly me. That did it.

There is no visual indication that something is filtered that I could see when you filter by right click. Would it be possible to change the "filter" icon to the "clear filter" icon like what happens when you filter via the filter icon?

I appreciate the quick response.

**Comment by Gruntfuggly** [comment]
Yes - I've been thinking about that. There should definitely be some indication that filters are active. I'll add something in the next update.

**Comment by Gruntfuggly** [comment]
I've just uploaded a new version which shows if there are active filters at the top of the tree. Should hopefully stop anybody else getting unexpected filtering - you weren't the first! 😁
