### ISSUE TITLE
A way to ignore selected folders ?

### ISSUE THREAD

**Issue by 2f-concept** [Gruntfuggly/todo-tree#23]
Hi,
At first, tank you for sharing this great module, i love it !

I woul'd like to know if there is a solution to ignore folder (plugins) in my project ?

Regards

**Comment by 2f-concept** [comment]
I tried to add something like that:
"todo-tree.globs": ["!src/plugins/**"]
but it don't seem to work...

**Comment by Gruntfuggly** [comment]
Were you trying to ignore the plugins folder? What works for me is
`["!src/plugins"]`
I thought your configuration would work too, but having read some more (ripgrep uses .gitignore globbing rules) from [here](https://www.atlassian.com/git/tutorials/saving-changes/gitignore#git-ignore-patterns) it makes more sense.
I'll change the example in the config as it's misleading.

**Comment by samael205** [comment]
Hi, How to ignore more than one folder?.

For example, Folder Blockly and floder jqueryui?

**Comment by Gruntfuggly** [comment]
It's a list, so you can do:
`["!Blockly", "!jqueryui"]`
