### ISSUE TITLE
"TODO(API)" tag overruled by generic "TODO"

### ISSUE THREAD

**Issue by borekb** [Gruntfuggly/todo-tree#230]
I defined a custom tag, `TODO(API)`, which is more specific than generic `TODO`, but it is still grouped under the generic `TODO`.

I'd say that if there's an exact match with a user-defined tag, it should win.

**Comment by Gruntfuggly** [comment]
I think you can make this work by adjusting the order of tags in `todo-tree.general.tags`. E.g.
```
    "todo-tree.general.tags": [
        "TODO(API)",
        "TODO",
        "FIXME"
    ],
```

**Comment by borekb** [comment]
I also thought this could be a solution (can't try right now..) but in my opinion, if there's an exact match, it should win. I'd argue that that would be a better UX.

**Comment by Gruntfuggly** [comment]
The problem is due to how the regex is used to perform the search. It will stop when it finds a match. I could put something in to automatically order the tags, which would make it simpler for the user.

**Comment by Gruntfuggly** [comment]
The latest version now sorts the tags before the search to that any which are more specific should be found first. Please let me know if it doesn't work as expected.
