### ISSUE TITLE
Option to remove icon from task items

### ISSUE THREAD

**Issue by ryanaltvater** [Gruntfuggly/todo-tree#233]
Visually, it seems a bit much having an icon next to the tag group and also every item. Is there an option (or is it possible to build an option) to opt out of an icon next to each item? I'd personally prefer a standard text hyphen, or even being able to define a separate more subtle icon next to each item. Thanks!

**Comment by Gruntfuggly** [comment]
If you are using the "Group by Tag" view, you can set `"todo-tree.tree.hideIconsWhenGroupedByTag": true` to hide the icons for each item.

**Comment by ryanaltvater** [comment]
How did I miss that?! Thank you. I’ll try that and report back.

Ryan

**Comment by ryanaltvater** [comment]
@Gruntfuggly That was exactly what I was looking for. Sorry about that. Thank you!
