### ISSUE TITLE
Highlight not visible on minimap

### ISSUE THREAD

**Issue by alumni** [Gruntfuggly/todo-tree#234]
The TODOs are shown as regular comments in the minimap, even though I defined a custom style (yellow text on red background).
I would expect to see the custom color (yellow in this case) in the minimap.

This behavior happens regardless of whether the option "render characters" is enabled or disabled.

**Comment by Gruntfuggly** [comment]
The highlights are just decorations and unfortunately decorations aren't currently shown in the minimap. There is an outstanding feature request for this: https://github.com/microsoft/vscode/issues/73140

There should be markers in the ruler though.

**Comment by BMBurstein** [comment]
I don't see any markers in the ruler. Do I need to enable them somehow?

**Comment by Gruntfuggly** [comment]
You should see the markers if you enable highlighting. If you installed the extension a while ago, the highlighting was not  enabled by default.

**Comment by BMBurstein** [comment]
I installed it today. I am assuming we are talking about something similar to the red dots on the right in the attached screenshot. If not, can you post a screenshot so I know what I am looking for?

![image](https://user-images.githubusercontent.com/1149432/69794177-77dd0800-11d2-11ea-8b49-a7133f6adb0a.png)

**Comment by Gruntfuggly** [comment]
Yes - that's odd. You should see markers with the same colour as the highlight (white if you haven't changed it). I'll investigate...

**Comment by Gruntfuggly** [comment]
OK - my mistake. To make them appear you'll need to add:
```
    "todo-tree.highlights.defaultHighlight": {
        "rulerColour": "white"
    },
```
with whatever colour you want.

**Comment by BMBurstein** [comment]
Thank you. That worked. Can I suggest that the default be the background color instead of the foreground color? At least to me that makes more sense.

**Comment by Gruntfuggly** [comment]
Yes, if no other colours are specified, that makes sense.

**Comment by Gruntfuggly** [comment]
The ruler mark colour will now default to the background colour of the highlight in the next release. I'm closing this issue as the highlights in the minimap will be resolved automatically when (if) the vscode issue is resolved.
