### ISSUE TITLE
Detects virtualenv package TODOs

### ISSUE THREAD

**Issue by karipov** [Gruntfuggly/todo-tree#235]
The package seems to detect the TODOs included in one of my packages (mongoengine) that is stored in the .venv directory inside the project directory. I understand there is a filter function that can disable folders; however, I believe it should just be removed at all times.

**Comment by Gruntfuggly** [comment]
There are several ways to ignore things, but it sounds like you should just add an entry to the exclude globs, e.g.
```
"todo-tree.filtering.excludeGlobs":
    [
        "**/.venv"
    ]
```
which should prevent it from searching any `.venv` folders.

**Comment by Gruntfuggly** [comment]
Hi - did you have any luck filtering them out?

**Comment by karipov** [comment]
Yes, it works mostly, but sometimes doesn't load the filters properly. I have not been able to find what causes that.

**Comment by Gruntfuggly** [comment]
How do you mean it doesn't load them properly? Does it not restore them when you reload the window?

**Comment by karipov** [comment]
Sometimes it does, sometimes doesn't. I'm afraid I can't replicate when exactly that happens, so I think it's safe to close this issue. Thanks!

**Comment by Gruntfuggly** [comment]
If you don't mind, please could you just describe the exact symptoms and I can keep an eye open for them too.
