### ISSUE TITLE
[Feature Request] Properties for Tags

### ISSUE THREAD

**Issue by EnochMtzR** [Gruntfuggly/todo-tree#236]
It would be interesting if you could add **_Properties_** for the different _Tags_ . 
e.g.
`// TODO ${importance: 1, autor: "John Doe"} ...`
settings would be like:
`todo-tree.general.tagProperties: ["importance", "author"]`
or even better:
`todo-tree.general.tagProperties: [{ "TODO" : ["importance", "author"]}]`
so that: 
- anything that is surrounded by `${}` immediately after a _$TAG_ is parsed as a **Property**
- any **Property** that is not defined in the _tagProperties_ setting  is just ignored

This feature could help in many areas as:

- **_"Label Formatting"_** 
you could set the **_"labelFormat "_** setting  with the **_Properties_** gathered from the _Tag_.
`${tag} by "${by}" ${after}` which should output: `TODO by "John Doe" ...`
- **_Sorting by Properties_** 
sorting on tree view by multiple **Properties** could be a possiblity and they may be sorted in order of appearance:
`todo-tree.tree.sortTagsByProperties: ["importance", "author"] //first sort by importance and then by author`
or even better:
`todo-tree.tree.sortTagsByProperties: [{"FIXME": ["author", "importance"]}]`

- **_Filter by Properties_** 
`todo-tree.filtering.filterByProperties: ["importance", "author"]`
  - when clicking a _Property Filter_ button, a checkbox list could be open to select the properties to filter by.
  - This could be done not only for all _TAGS_ in general, but for each specific one:
`todo-tree.filtering.filterByProperties: [{"BUG": ["severity", "author"]}]`

- **_Highlighting shades by Properties_**
There could be highlighting rules to set shades of a base color based on the _"severity"_ of a _BUG_ or on the _"importance"_ of a _FIXME_

**Comment by Gruntfuggly** [comment]
I've just uploaded version 0.0.197 which provides some support for sub tags. You can define todo-tree.regex.subTagRegex to extract a sub tag. This can then be used for grouping and custom highlights. Details and examples are in the README.

This isn't a full implementation of your feature request, but I think it goes most of the way.

Please let me know if it's enough to close the issue.
