### ISSUE TITLE
typo in Configuration-Examples

### ISSUE THREAD

**Issue by YNCBearz** [Gruntfuggly/todo-tree#238]
It's about PHP example.
------------------------------------------------------------------
"todo-tree.regex.regex": "(//|#|<!--|;|/?\\*|^)\\s*($TAGS)",            // there are double open parentheses
------------------------------------------------------------------
ʕ •ᴥ•ʔ : nice extension!

**Comment by Gruntfuggly** [comment]
Good spot - there's a few of them actually!
