### ISSUE TITLE
Enable highlight by default

### ISSUE THREAD

**Issue by bitjson** [Gruntfuggly/todo-tree#239]
I see in https://github.com/Gruntfuggly/todo-tree/issues/26 that highlighting is disabled by default:

> The latest version now supports highlighting. It's off by default as I figure most people will be using [todo highlight](https://marketplace.visualstudio.com/items?itemName=wayou.vscode-todo-highlight).

I like to recommend extensions in the `.vscode/extensions.json` file in some of my larger projects, and right now I have to include both for users to see the highlighting without messing with their configuration:
```
"recommendations": [
    "gruntfuggly.todo-tree",
    "wayou.vscode-todo-highlight"
  ],
```

Can I suggest that you enable highlighting by default now? I'd love to switch to recommending todo-tree alone.

**Comment by bitjson** [comment]
For my personal use, the color choices made by `wayou.vscode-todo-highlight` have been great, I've never considered customizing them at all. I think you'd be very safe copying those.

If you have a different color palette you already use personally, that's probably a reasonable option too. 

The only thing I'd add: it would be best if the default was extremely visible. When other developers on my team install TODO Highlight, I know that the TODO comments will almost always be extremely visible for all of us, which is really helpful. (If a user cares enough, they can tone it down in their own settings, or better yet, complete the TODO item. 😆)

**Comment by Gruntfuggly** [comment]
Not currently - should be a simple change though.

**Comment by Gruntfuggly** [comment]
Just uploaded a new version with theme colour support.

**Comment by bitjson** [comment]
Fantastic, thank you! And nice touch with the notice!
<img width="565" alt="Screen Shot 2019-10-31 at 12 59 38 AM" src="https://user-images.githubusercontent.com/904007/67920219-bf438a80-fb79-11e9-8289-d64d21eb2df8.png">
