### ISSUE TITLE
[feature-request] filtering tree by tag ("todo", "fixme" etc..)

### ISSUE THREAD

**Issue by beebase** [Gruntfuggly/todo-tree#24]
This is a great plugin 👍 
Would be awesome to filter the tree by tag (or show tree nodes grouped by tag)

**Comment by Gruntfuggly** [comment]
Grouping by tag would be useful - you wouldn't need the filters because you could just collapse them. I'll add it to the TODO list (pun intended). 8-)

**Comment by beebase** [comment]
> Grouping by tag would be useful - you wouldn't need the filters because you could just collapse them. 

agree.

Or maybe a text search box (like vscode explorer) if that's easier to implement?

**Comment by Gruntfuggly** [comment]
A search box is possible - I did something similar in another extension. Its a little bit more work, but again it might be a useful feature.

**Comment by Gruntfuggly** [comment]
Latest version has filtering - please give it a try and let me know what you think. 8-)

Grouping by tag is ongoing...

**Comment by beebase** [comment]
> Latest version has filtering - please give it a try and let me know what you think. 8-)

Works very well 👍

**Comment by nealot** [comment]
The filter feature works great! The icon isn't very intuitive though -- could it be changed to the ellipsis with a drop down menu? Similar to the outline feature native to VSCode?

**Comment by Gruntfuggly** [comment]
I'm not sure I understand what you mean? There's no API to do a drop down menu at the moment. Hopefully the filter feature from the outline view will be made available to custom views at some point though...

**Comment by voxpelli** [comment]
Would love the grouping as well, the text filter doesn't seems to be persistent.

Would like to add that I would like to be able to show eg. "FIXME" only in the flat list as well, not just the tree list – that would be doable, right?

(Great module btw, it helps a lot 😊)

**Comment by Gruntfuggly** [comment]
Latest version now supports grouping by tag

**Comment by Gruntfuggly** [comment]
I could add a couple of commands to add and remove tags - that would probably be a bit more convenient than modifying the preferences. I'm worried the toolbar is getting a bit full, so I probably won't add it there.

**Comment by Gruntfuggly** [comment]
Commands to add and remove tags have been added to the latest version.
