### ISSUE TITLE
Please add a feature: quickly location the focus file in the todo view

### ISSUE THREAD

**Issue by DFVSQY** [Gruntfuggly/todo-tree#240]
![image](https://user-images.githubusercontent.com/8075421/68098647-d0352880-fef8-11e9-80c5-facc4b22e867.png)

**Comment by Gruntfuggly** [comment]
There is currently a setting `todo-tree.tree.track-file`, which should automatically focus the view when you change file. I could add the button if the setting is disabled?

**Comment by DFVSQY** [comment]
I have a try for `todo-tree.tree.track-file`, it's not a good solution,
I think it will be better if you can add a button to focus the file.

**Comment by Gruntfuggly** [comment]
But the tracking already automatically does what you want. Why is it not a good solution?

If it doesn't work for you please let me know and I will try to fix it. I will also add the button though.

**Comment by DFVSQY** [comment]
I have set `"todo-tree.tree.trackFile": true`, It seems doesn't work, i don't see anything happen, like below:
![image](https://user-images.githubusercontent.com/8075421/68109354-4e0f2900-ff25-11e9-85a6-771355a845c2.png)

For the icon, i think it's a good selection like visual studio:
![image](https://user-images.githubusercontent.com/8075421/68109437-7b5bd700-ff25-11e9-82c6-6d8dadfaeb6a.png)

**Comment by Gruntfuggly** [comment]
I'll need some help understanding why it doesn't work because the button will need to use the same functionality.

In your screenshot, it doesn't look like the `// todo:` is showing in your tree at all? It looks like the file is not saved - can you make sure the file is saved and then check that you can see the file in the tree.

There is an issue with vscode which is that the reveal won't work unless the tree has already been expanded at least once.

**Comment by DFVSQY** [comment]
I have saved the file and don't see anything change, like below:
![image](https://user-images.githubusercontent.com/8075421/68119097-b61d3980-ff3c-11e9-840e-82b70c99efeb.png)

If i select the focus file, `// todo:` is showing in my tree view, like below:
![image](https://user-images.githubusercontent.com/8075421/68119165-f4b2f400-ff3c-11e9-85b7-b713e2ffa899.png)

**Comment by Gruntfuggly** [comment]
Now the file is shown in the tree, does it still not track if you change to other files? You will obviously need other files with 'todo' tags in them.

**Comment by DFVSQY** [comment]
If i add `todo` to other files, they will display in tree view,.
However, what does it have to do with `"todo-tree.tree.trackFile": true` ? I'm confused with the setting.

**Comment by Gruntfuggly** [comment]
When `todo-tree.tree.trackFile` is set to `true` and you open another file (the current file changes), if the file contains 'todo' items, it will be highlighted and selected in the tree.  If you change to a file without any 'todo' items, the tree view selection will not change.

Have I misunderstood what your feature request is? Did you want to show the file inside the tree or literally move the input focus to the file?

**Comment by DFVSQY** [comment]
Well, you are right.
I just want to quickly select the focus file in the todo-tree view, just like below:
![gif](https://user-images.githubusercontent.com/8075421/68136370-1e314700-ff60-11e9-924f-b94c34b774ad.gif)

**Comment by Gruntfuggly** [comment]
OK. If the `todo-tree.tree.trackFile` is set to `true` it should show the file in the tree. It should also expand the tree to show the file.

I think the only thing missing is setting the focus in the tree? However, you might as well just click the file in the tree?

I've added a button which does the same thing which will work when `todo-tree.tree.trackFile` is set to false. Please try the latest version and let me know if it work as you expected.

**Comment by DFVSQY** [comment]
I have a try for the lastest version, it's what i want.
However if the todo-view is fold, the current file will not be selected in the todo-view, I think the view should automatically be unfold and the current file should automatically be selected. Just like visual studio:
![gif](https://user-images.githubusercontent.com/8075421/68172384-477ac300-ffb2-11e9-80e2-e926b207f350.gif)

**Comment by Gruntfuggly** [comment]
As I said at the start - unfortunately there is a known limitation with vscode's tree views. Unless the tree has already been expanded, it can't reveal or filter the nodes.
https://github.com/microsoft/vscode/issues/66971
https://github.com/microsoft/vscode/issues/69352
