### ISSUE TITLE
Default style for the extension

### ISSUE THREAD

**Issue by Kira-Lappo** [Gruntfuggly/todo-tree#241]
Could you please add some default highlights and tags highlights, so users don't have to customize it much (or maybe not at all)? It takes some time to understand how settings affect the behavior of the extension.

That is how it looks like after installation
![image](https://user-images.githubusercontent.com/11411852/68218498-7d8d6680-fff5-11e9-8c83-9301a1f6ef6f.png)

I updated the settings a bit, and it started to look nicer.
![image](https://user-images.githubusercontent.com/11411852/68216578-21751300-fff2-11e9-93c5-5609955e2bac.png)

I know that tastes differ, and my variant is not the best one, but I think most users will prefer to see some icons and predefined colors out of the box.

My settings, just in case:
```json
{
    "todo-tree.general.tags" : ["todo", "bug", "fixme"],
    "todo-tree.regex.regexCaseSensitive": false,
    "todo-tree.highlights.defaultHighlight" : {"foreground":"#F8DE7E", "icon":"file-directory","type":"text"},
    "todo-tree.highlights.customHighlight" : {
        "todo" : {"foreground":"#66D3FA", "icon":"comment"},
        "fixme" : {"foreground":"#FFA500", "icon":"flame"},
        "bug" : {"foreground":"#E84855", "icon":"bug"},
    }
}
```

**Comment by Gruntfuggly** [comment]
Hi - thanks for the suggestion. I'd prefer not to add too much more configuration at the moment. The colours are difficult because it totally depends on what theme people are using. I also don't want to turn on case insensitive matching as it may result in more false positives.

However, adding "BUG" and the icons seems to make sense, so I'll update those.

**Comment by Gruntfuggly** [comment]
I've added BUG and the flame and bug icons in 0.0.163.
