### ISSUE TITLE
Update icon 2

### ISSUE THREAD

**Issue by kanlukasz** [Gruntfuggly/todo-tree#243]
Hi

VSCode has changed the sidebar icons again, so the TodoTree icon is a little different again - it's too thin

![obraz](https://user-images.githubusercontent.com/30685349/68467294-3a5e0e00-0216-11ea-9306-0c3f93a87b96.png)

Previous change: https://github.com/Gruntfuggly/todo-tree/issues/181
CC: @johnletey

**Comment by Gruntfuggly** [comment]
lol. Thanks! Over to @johnletey ... :grin: :pray:

**Comment by johnletey** [comment]
@Gruntfuggly @kanlukasz Let me see what I can do, I'll keep you both posted!

Although, doing some preliminary research, it doesn't look like VSCode has changed the thickness of their icons, but I do indeed see a difference in width 🤔

Hate to do this (as I know you are busy), but do you know why this is happening @misolori?

**Comment by kanlukasz** [comment]
This happen with last update 
```
Version: 1.40.0 (system setup)
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:02:13.381Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362
```

**Comment by Gruntfuggly** [comment]
To be honest, I've updated to 1.40 and I can't actually see a difference (on Ubuntu).
![image](https://user-images.githubusercontent.com/376658/68469118-6fb42d00-0211-11ea-9da6-0372cc036ecc.png)

**Comment by kanlukasz** [comment]
Hmm interesting. My screenshot is from a computer with Windows 10 🤔

**Comment by johnletey** [comment]
The icon looks reasonable on a Mac, maybe this is a per-machine problem?

![Shot 2019-11-08 at 10 27 01](https://user-images.githubusercontent.com/30328854/68469602-62e40900-0212-11ea-9239-9026e7b490ef.jpg)

**Comment by Gruntfuggly** [comment]
I've just updated to 1.40 on Windows and it does look like it's only Windows...
![Capture](https://user-images.githubusercontent.com/376658/68469954-0fbe8600-0213-11ea-854e-df7304dd8561.PNG)

**Comment by johnletey** [comment]
> it does look like it's only Windows

@kanlukasz I would suggest opening an issue in the VSCode repository.

**Comment by kanlukasz** [comment]
Oh, ok, I'm sorry I made a fuss. I will open the problem in the VSCode repository and then let you know what I researched

**Comment by misolori** [comment]
We didn’t change our icons, but we did swap them from image assets to an icon font. We have https://github.com/microsoft/vscode/issues/83316 open for this but it might also be related to a font rendering bug in Electron (https://github.com/microsoft/vscode/issues/84154)
