### ISSUE TITLE
Better default settings

### ISSUE THREAD

**Issue by doggy8088** [Gruntfuggly/todo-tree#244]
There are some languages such as Markdown don't have a TODO concept, but `TODO Tree` make all the `# ` as a comment which is very confusing.  I know I can setup `todo-tree.filtering.excludeGlobs` to exclude all these files, but it'll be much better if there is a right fit defaults.

**Comment by Gruntfuggly** [comment]
You can modify the default regex to remove `#`. It would be impossible to have a default that works for everybody, which is why it is configurable.

Please can you give me an example of where it has gone wrong?

**Comment by doggy8088** [comment]
I understand it's impossible to have a default that works for everybody.  So all I asked is that the default won't bother someone who don't know how to configure this extension.

I'm the author of the [Angular Extension Pack](https://marketplace.visualstudio.com/items?itemName=doggy8088.angular-extension-pack). I was considered to include your extension to my extension pack becuase I really like your extension. But I just stopped. It because the current users of my extension might not aware they are just installed `Todo Tree` extension due to my extension been updated. If something will broken their environment, that will be troublesome.

Here is an example in the `*.md` (Markdown) file in the Visual Studio Code.  All the bullet items are marked as an TODO and listed in the `TODOS` (sidebar).

![image](https://user-images.githubusercontent.com/88981/68573371-8d4bf580-04a2-11ea-9294-3f156d33c940.png)

I will suggest you could white-listed some of the languages you know to support TODO list or Highlight by default.

**Comment by Gruntfuggly** [comment]
That is the format for a markdown TODO - it's expected behaviour?
That was specifically requested as a feature a long time ago (https://github.com/Gruntfuggly/todo-tree/issues/15).

**Comment by Gruntfuggly** [comment]
Could your extension pack override the todo-tree configuration? If you want to remove the support for markdown todos, you can set the regex to
`((//|#|<!--|;|/\*|^)\s*($TAGS))`

**Comment by doggy8088** [comment]
wow, it's my bad. I shouldn't use this example. 😅

There is another example:

![image](https://user-images.githubusercontent.com/88981/68598305-7ecd0080-04d9-11ea-8016-1624dbee9e64.png)

**Comment by doggy8088** [comment]
@Gruntfuggly 
> Could your extension pack override the todo-tree configuration?

Can I? I don't even know it's possible! How to override an existing configuration of the other extension during install my extension?

**Comment by Gruntfuggly** [comment]
Ah, OK, I see what you mean. That's quite tricky because `# TODO` is something I think people would expect to be found in any other file other than markdown.

The main problem is that the search doesn't know anything about the type of files it is searching, so it has to apply the regex to all files. That means there is always the possibility of finding false positives.

How about it on first installation, it prompted you for which languages you wanted to be supported and the built the default regex based on that? That would not change anything for existing users (i.e. those who are using the current default regex), but new users would get a chance to change it.

**Comment by doggy8088** [comment]
Good idea! Thanks. 👍

**Comment by VideoPlayerCode** [comment]
Okay to summarize, the first example is how to make a TODO list in markdown, so of course it should be highlighted. The second example of `# TODO` is how TODO comments look in Python.

But the proposed solution here seems kinda nuts. Changing the regex to hide all markdown-style TODOs and `# TODO`?! That sounds error-prone.

It would be simpler and better to just have an option to ignore `.md` markdown files, if someone doesn't want those included in the search... And there is such an option, @doggy8088 : You can use one of Todo Tree's "ignore paths" settings (I don't know their exact names) to say "ignore *.md". Also... there's another solution... you can use a per-workspace VS Code settings.json file to just ignore .md files in certain projects.

So this ticket is solved/solvable already. @Gruntfuggly :-)

**Comment by Gruntfuggly** [comment]
I don't think I will get time to implement this. I think the default configuration is probably as good as it's going to get. Every time I make changes to the default, it causes further problems, so I don't propose to change anything now.
