### ISSUE TITLE
todo-tree: TCC: Unknown command "\"c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg.exe\""

### ISSUE THREAD

**Issue by AnrDaemon** [Gruntfuggly/todo-tree#245]
Backslash was never an escape character for CMD. Nor it is for TCC.
Please fix construction of the command line.

**Comment by Gruntfuggly** [comment]
Sorry, but what it TCC? 

Please could you post your settings and the output from the console.

**Comment by AnrDaemon** [comment]
TCC is TakeCommand/Console, a CMD compatible shell for Windows. https://jpsoft.com/all-downloads/downloads.html
I do not see any output that is specific to the extension, any pointers?
Configuraton is uninteresting as I did not alter the location of `ripgrep` binary.
```
"todo-tree.general.tags": [
        "TODO",
        "FIXME",
        "FIX",
        "BUGFIX",
        "BUG"
    ],
    "todo-tree.filtering.passGlobsToRipgrep": false,
    "todo-tree.tree.showInExplorer": false,
    "todo-tree.tree.hideTreeWhenEmpty": false,
    "todo-tree.regex.regex": "((//|#|<!--|;|/\\*|^)\\s*@?($TAGS)|^\\s*- \\[ \\])",
    "todo-tree.highlights.defaultHighlight": {
        "foreground": "#dfdf00",
        "background": "#ff0000",
        "opacity": 30,
        "borderRadius": 4,
        "type": "text",
        "rulerLane": "center",
        "iconColour": "blue"
    },
    "todo-tree.highlights.customHighlight": {
        "FIXME": {
            "iconColour": "red",
            "icon": "alert"
        },
        "BUG": {
            "iconColour": "green",
            "icon": "bug"
        }
    },
```

**Comment by Gruntfuggly** [comment]
Ah, OK - so it's running in a different shell.

If you set `todo-tree.debug` to `true` you should find a view in the Output Window (select Todo Tree from the drop down). Can post the contents of that please?

Could you also let me know what the command line *should* be?

**Comment by AnrDaemon** [comment]
```
Searching \\HOSTING64.DARKDRAGON.LAN\wwwroot\ccenter...
Command: "c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg.exe" --no-messages --vimgrep -H --column --line-number --color never --max-columns=1000 --no-config  -e "((//|#|<!--|;|/\*|^)\s*(TODO|FIXME)|^\s*- \[ \])" "\\HOSTING64.DARKDRAGON.LAN\wwwroot\ccenter"
 Match (Editor):{"file":"\\\\HOSTING64.DARKDRAGON.LAN\\wwwroot\\ccenter\\app-core\\CcWeb\\Routers\\CatalogRouter.php","line":56,"column":5,"match":"    // TODO:router rewrite to handle goods in a separate router"}
TCC: Unknown command "\"c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg.exe\""

Found 1 items
```

It appears, the problem might lie in the VS Code itself, as it surfaced after upgrade to 1.40.

**Comment by Gruntfuggly** [comment]
Hi - did you get any further with this?

**Comment by AnrDaemon** [comment]
I've made an override for ComSpec variable in the wrapper script.
Unfortunately, I don't have the capability to debug it any further.

**Comment by Gruntfuggly** [comment]
Is there anything further I can do for this issue? Did you raise an issue on vscode itself?

**Comment by Gruntfuggly** [comment]
Please feel free to reopen this if you need to.
