### ISSUE TITLE
Properly explain "todo-tree.filtering.useBuiltInExcludes"

### ISSUE THREAD

**Issue by VideoPlayerCode** [Gruntfuggly/todo-tree#246]
This extension is insanely good. Thanks a lot for this fantastic tool!

I was confused by `todo-tree.filtering.useBuiltInExcludes` and had to look in the source code to figure out what it does. That's a bad sign. The description should just say something clearer to explain that it tells Todo Tree to take VS Code's own `files.exclude` setting and apply those paths to its ignore paths.

Those paths are basically just database paths for Git, SVN, Mercurial (hg), etc...

Here's a proposal for a better description: `Add VSCode's "files.exclude" list (mainly source-control database directories) to the ignored paths.`

It should also be True (enabled) by default, tbh. Who on earth wants to find TODO files inside their `.git` database folder etc? ;-)

**Comment by Gruntfuggly** [comment]
I'll update the description for the next release. 

I don't want to change the default because it could potentially affect existing users.

**Comment by VideoPlayerCode** [comment]
Fair enough, and thanks for improving the description in the next release! :-)
