### ISSUE TITLE
Improve display of "todo-tree.general.statusBar": "tags"

### ISSUE THREAD

**Issue by VideoPlayerCode** [Gruntfuggly/todo-tree#247]
Noticed a problem: If something lacks a detected "named" tag, the status bar says `:2 TODO:1` for example. The "Colon Two" (`:2`) is the "bug".

Reproduce by saving this as a `.md` file in project:

```
- [ ] Fix stuff
- [ ] Do more
```

And setting `"todo-tree.general.statusBar": "tags",` in your config.

Here's a proposal: Do a whitespace trimming on every tag. And then, if the result is an empty tag, map it to "TODO". So the above example should say  `TODO:3`.

How about it @Gruntfuggly, what do you think?

**Comment by Gruntfuggly** [comment]
Yes, makes total sense. Will add it to the next release.

**Comment by VideoPlayerCode** [comment]
Thanks, that sounds great! And welcome back from the holidays, great to see you back! :-)
