### ISSUE TITLE
Bug: "todo-tree.general.statusBarClickBehaviour": "reveal" not implemented/not working.

### ISSUE THREAD

**Issue by VideoPlayerCode** [Gruntfuggly/todo-tree#248]
I use the following two settings:

```
"todo-tree.general.statusBar": "tags", // Show summary of project's "to-do" related tags in status bar.
"todo-tree.general.statusBarClickBehaviour": "reveal", // Show list of "to-do" tags when statusbar clicked.
```

However, when the statusbar tag list is clicked, nothing happens. I tried everything. The TODO explorer pane does not open. The list of problems in the current file is not expanded either. So the button actually does nothing.

I suspect that its intended behavior is to open the explorer pane, and perhaps highlight the currently active file in that pane. Currently it's broken, possibly due to a VS Code update. I'm on the latest version of the extension and VS Code, on Windows.

**Comment by liangjiancang** [comment]
+1, not working

**Comment by kanlukasz** [comment]
I have same issue

My env:
```
Version: 1.41.1 (system setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363
```

**Comment by Gruntfuggly** [comment]
Please try version 0.0.163.

**Comment by kanlukasz** [comment]
I did a quick test, but from what I see, it works well now 👍

**Comment by kanlukasz** [comment]
Works for me ok
