### ISSUE TITLE
Research: How low can highlightDelay go?

### ISSUE THREAD

**Issue by VideoPlayerCode** [Gruntfuggly/todo-tree#249]
The default is 500ms, which looks very unresponsive when typing or changing buffers. I changed it to 333ms (3 times per second) instead, which is pretty decent. But it made me think about documentation:

1. What does it actually do? I suspect it sets a JavaScript `setInterval`, and that each time the timer is up, it does a JavaScript regex on the open buffers. So it should be pretty fast. But I guess I shouldn't go lower than 333ms, for performance.

2. Does it properly avoid any non-visible buffers? Basically if you have 15 tabs open, I hope that it only scans the visible buffers (anything currently being viewed in a window/split view).

**Comment by VideoPlayerCode** [comment]
Answers:

1. It uses `setTimeout`: https://github.com/Gruntfuggly/todo-tree/blob/05266dd9be603d5549357c3d20d0fda5b634ebd5/highlights.js#L420-L430

2. Not sure. Haven't analyzed that deeply. @Gruntfuggly do you remember? :-)

_PS: With the 2x speedup of the JS regex matching in pull request #251, it will be possible to halve the default timeout thanks to the new speedup._

**Comment by Gruntfuggly** [comment]
It uses `visibleTextEditors` which is the only thing that vscode provides. It only applies the highlights if the file associated with the editor would normally be included in the tree and it can be further limited by matching document urls to the schemes defined by `todo-tree.highlights.schemes` which is `file` and `untitled` by default, so it will ignore settings, files, etc.

**Comment by VideoPlayerCode** [comment]
Ahh I see. Thanks a lot for the answer, that's brilliant, means it will be speedy and won't run unnecessarily for the "background tabs"! :-) Feel free to close this ticket. Thanks again. :-)
