### ISSUE TITLE
Maybe a merge with todo-highlight

### ISSUE THREAD

**Issue by muuvmuuv** [Gruntfuggly/todo-tree#25]
It would be so great to have your extension and this one https://github.com/wayou/vscode-todo-highlight/issues/101 in one together. Maybe name it just `vscode-todos`. Because they are both so similar and both have the pros and cons. Treeview here is great (just filtering is missing in the sidebar pannel) and the other ones highlighting works smoother.

**Comment by Gruntfuggly** [comment]
Interesting idea, but I think It would probably be too big a job to merge them. They seem to work quite nicely together out of the box though?

I have been toying with the idea of adding highlighting, as it would be a fairly simple change, but it's low priority as vscode-todo-highlight already works.

BTW - I intend to add grouping by tag and filtering in the next update.

**Comment by muuvmuuv** [comment]
Yeah it‘s true, they working nicely together, but one plugin for both is always better then two. Anyway it‘s just a personal OCD haha. 

Nice! That‘s a great idea too, I‘m looking forward to the next update

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Gruntfuggly** [comment]
I've created a new issue (#26) to track the highlight enhancement.

**Comment by Gruntfuggly** [comment]
Now highlighting is supported I am going to close this.
