### ISSUE TITLE
Extend the default "todo-tree.general.tags" with some other very common tags

### ISSUE THREAD

**Issue by VideoPlayerCode** [Gruntfuggly/todo-tree#250]
Currently it only matches `FIXME` and `TODO` (edit: And `BUG`). Here are some other extremely common formats, in order of popularity from most to least popular:

- `FIXME`
- `TODO`
- `XXX` (very common)
- `BUG`
- `HACK`

This would give us the following new default, with no downsides that I can think of:

`"todo-tree.general.tags": ["TODO", "FIXME", "XXX", "BUG", "HACK"],`

---

Furthermore, just as food for thought or inspiration for others, I did the following configuration personally:

```
    "todo-tree.general.tags": ["TODO", "FIXME", "XXX", "BUG", "HACK", "NOTE"], // Extend the tag list. Case sensitive. By default, only TODO and FIXME were matched.
    "todo-tree.highlights.defaultHighlight": {
        "icon": "flame", // Valid icons: https://octicons.github.com/
        "iconColour": "orange",
        "type": "tag", // Only highlight the tag itself (not the comment or line) in the text editors.
        "foreground": "white",
        "background": "red",
    },
    "todo-tree.highlights.customHighlight": {
        "NOTE": {
            "hideFromTree": true, // We want NOTE to be highlighted in files but not listed as "problems" in the tree/statusbar.
            "foreground": "black", // Nice highlight without having the glaring "red error" style of the other types.
            "background": "white",
        },
    },
```

The benefit is that I get a clearly visible highlighting of "NOTE:" comments, which are very common for explaining quirks/code details, but they are not treated as "problems".

**Comment by VideoPlayerCode** [comment]
You may also want to add lowercase (case-sensitive) variants by default. It helps since most people write either `// TODO` or `@todo`. See the bottom of this comment on my semi-related pull request for an example of that:

https://github.com/Gruntfuggly/todo-tree/pull/251#issuecomment-558403714

**Comment by Gruntfuggly** [comment]
The extension already has a simple command for adding new tags, so I don't think it's really necessary to add more to the defaults (although BUG has been added relatively recently I have to admit) as it increases the chances of finding false positives, which I'd like to avoid.

I'll add your configuration for notes to the wiki, though as it could be useful for others.

Regarding case sensitivity, there is already a setting `todo-tree.regex.regexCaseSensitive` which hopefully covers it.

**Comment by VideoPlayerCode** [comment]
@Gruntfuggly Ah good to see BUG has been added. I agree that FIXME, TODO and BUG are great defaults. As for HACK, it is very rare, so yeah feel free to avoid it. It's used in some codebases to mean "this is a hack, replace it with better code later". But... XXX is very common, it's a TODO/FIXME for people and codebases who don't want to waste time writing the words TODO and FIXME. A quick `# XXX: ...` is much faster to type, and it is a common code style in companies.

As an example, look at the code of FreeBSD which is splattered with the XXX comment:
http://fxr.watson.org/fxr/search?string=XXX (search results say: "Too many hits, displaying first 10000").

What do you think about adding XXX as default too, so that the final list is FIXME, TODO, BUG and XXX?

**Comment by Gruntfuggly** [comment]
I had a read and am starting to think HACK and XXX could be added. My only concern is I don't want cause existing users to suddenly start finding new items unexpectedly. But maybe I'm being over cautious...

**Comment by Gruntfuggly** [comment]
Latest version now has HACK and XXX as defaults.
