### ISSUE TITLE
[Feature Request] tag icon in gutter

### ISSUE THREAD

**Issue by glics** [Gruntfuggly/todo-tree#252]
It would be great to have in the editor gutter an icon for the highlighted tag, something similar to this (mockup):

![Example of icons in gutter](https://user-images.githubusercontent.com/5410803/69738003-a8bb2f80-1135-11ea-907f-cfaad02223bc.png)

I think it should match the `icon` property defined in `todo-tree.highlights.defaultHighlight` or `customHighlight` and have an extra property for the color, such as `iconColor`, so you make it match the same color as `foreground`, `background` or have it a totally different color.

**Comment by Gruntfuggly** [comment]
Please try 0.0.163. There is a new setting `gutterIcon`. This can be used in the defauitHighlight or customHighlight settings.
