### ISSUE TITLE
show todo view only of current file

### ISSUE THREAD

**Issue by xiaolongGitHub1498** [Gruntfuggly/todo-tree#254]
<img width="1062" alt="WX20191202-153602@2x" src="https://user-images.githubusercontent.com/26108004/69939102-f65ee000-1519-11ea-89f4-9c4fd565a5d8.png">

**Comment by Gruntfuggly** [comment]
Please can you explain what the problem is? Or is this a feature request?

**Comment by xiaolongGitHub1498** [comment]
@Gruntfuggly i think it's a feature request, when i open and focus on this file, it will show the todos content of the current page

**Comment by Kenobi-the-2nd** [comment]
Yes, I would very much like to see this feature added as well. The TODO tree should only show the todo's for the currently active file when it is selected.

**Comment by Gruntfuggly** [comment]
There is an update coming soon. You'll need to enable a button on the titlebar, but it will then let you swap between 'workspace', 'open files' and 'current file'.

**Comment by Gruntfuggly** [comment]
Latest version now supports a new setting `todo-tree.tree.scanMode`. If you enable `todo-tree.tree.showScanModeButton` a button will be added to the title bar allowing you to swap between workspace, open files and current file.
