### ISSUE TITLE
Select “TODO:”s in multi-line JS/TS comments?

### ISSUE THREAD

**Issue by bitjson** [Gruntfuggly/todo-tree#255]
Hi there, something I’ve missed in `gruntfuggly.todo-tree` from `wayou.vscode-todo-highlight` is TODO selection in multi-line comment blocks:

<img width="216" alt="Screen Shot 2019-11-23 at 11 32 45 AM" src="https://user-images.githubusercontent.com/904007/69966872-41aacb80-14e5-11ea-8d1a-f97152354db7.png">

It looks like the current default is:
> ((//|#|<!--|;|/\\*)\\s*($TAGS)|^\\s*- \\[ \\])

https://github.com/Gruntfuggly/todo-tree/issues/192#issuecomment-529437285 mentions the following regex:
> ((.*\\*)|(//) )\\s*($TAGS).*(\\n\\s*(//|/\\*|\\*\\*)\\s{2,}.*)*

And https://github.com/Gruntfuggly/todo-tree/issues/111#issuecomment-457991437 mentions:
> (//|#|<!--|/\\*|^\\s*\\*)\\s*($TAGS)

Any recommendations for which of these is best?

And would it be possible to configure the plugin to use a regex which supports this by default? (I’d love for it to “just work” for other developers working in the same repo.)

Thanks!

**Comment by Gruntfuggly** [comment]
It really depends what language support you need - the part before the `\s($TAGS)` in the regex should match the comment characters you want to find.

From your screen grab, I assume you're using a C type language, so to find the top todo, you could just add `*` as an alternative at the start of the regex, e.g.  `((\*|//)\s($TAGS))`. You don't need the last part if you don't want to match markdown todos.

If you actually want to match multiple lines, I would use `(/\*|\*|//)\s*($TAGS).*(\n\s*(//|/\*|\*\*)\s{2,}.*)**` or something similar. The first section matches the leading comments, e.g. `/*`, `*` or `//`. The last part adds multiple lines.

Having `\n` in the regex will automatically trigger multi-line support.

I don't change the default regex anymore is it causes problems for people still using the default. It's too hard not to break it! The main problem is that the extension doesn't know up front what languages are being used and the search just looks in all files, so it has to cover all of them.

**Comment by tylerbrockett** [comment]
I am not a regex guru in any sense of the word, but this is what I came up with to handle various languages, single and multi-line use. I'm sure there's a better, more optimized regex out there though.

copied from vscode UI if it makes a difference:
`((//|#|;)[ ]*($TAGS)[^\n]*)|(/\*(\*?\s*)*($TAGS)(.|\n|\r)*?\*/)|(<!--\s*($TAGS)(.|\n|\r)*?-->)`

I have seen a few false-positives using it, for example, if there's a semicolon at the end of a line, and a TODO trigger word on the next, but overall works well for me.

[Regex101 example](https://regex101.com/r/7RRG5c/3)

I was the one who made the PR to support multiple `$TAGS` in the regex a few months ago.

**Comment by bruceauyeung** [comment]
i am using vscode + todo-tree to develop TS codes
almost all IDEs / languages support multiline comments and developers add TODOs within them.
i think,  many users(including me) don't realize that todo-tree doesn't support TODOs in multiline comments , and even don't know lots of TODOs don't get found by todo-tree.
people don't read documents until they blocked by or suffered from something.
it's very important that todo-tree support multiline TODOs by default.

regex provided by @tylerbrockett helps me find almost 30 extra TODOs ( before:18, after:46 ), this is a huge percent.

@Gruntfuggly please consider support multiline TODOs by default.

**Comment by bruceauyeung** [comment]
for anyone who may be interested , the following is what i put into `settings.json` to enable multiline TODOs ( escape `\` in special characters such as `\n`  because JS/JSON escape string before todo-tree reading it, tested on windows/linux )
~~~
"todo-tree.regex.regex": "((//|#|;)[ ]*($TAGS)[^\\n]*)|(/\\*(\\*?\\s*)*($TAGS)(.|\\n|\\r)*?\\*/)|(<!--\\s*($TAGS)(.|\\n|\\r)*?-->)"
~~~

**Comment by scambier** [comment]
And here's my version:
```
"todo-tree.regex.regex": "((//|#|;|\\*)[ ]*($TAGS)[^\\n]*)|(/\\*(\\*?\\s*)*($TAGS)(.|\\n|\\r)*?\\*/)|(<!--\\s*($TAGS)(.|\\n|\\r)*?-->)"
```

I just slightly modified @tylerbrockett version to allow this kind of TODO, that I use regularly:
```
/**
 * Some comment
 * TODO here is a test
 */
```

https://regex101.com/r/7RRG5c/5

**Comment by mbomb007** [comment]
> And here's my version:
> 
> ```
> "todo-tree.regex.regex": "((//|#|;|\\*)[ ]*($TAGS)[^\\n]*)|(/\\*(\\*?\\s*)*($TAGS)(.|\\n|\\r)*?\\*/)|()"
> ```
> 
> I just slightly modified @tylerbrockett version to allow this kind of TODO, that I use regularly:
> 
> ```
> /**
>  * Some comment
>  * TODO here is a test
>  */
> ```
> 
> https://regex101.com/r/7RRG5c/5

This is a much simpler regex that does the same thing:

`"todo-tree.regex.regex": "(?:(?://|#|<!--|;|/\\*\\*?|\\*)\\s*($TAGS)|^\\s*- \\[ \\])"`

I made the capturing groups non-matching (except the one that needs to be), and I added `\\*?|\\*` to support multi-line JS-style comments. That's it. The default regex doesn't match the entire comment, since all you need to find is the TODO part. I don't see why you'd need to match to the end of the comment.

https://regex101.com/r/q7VcL3/1

**Comment by Gruntfuggly** [comment]
@bruceauyeung The reason I prefer not to enable multi-line TODOs by default is that they are too many potential formats. The extension searches all files regardless of type, so it really is up to the user to customise the regex to make it work for them. As you've found, the regex can quickly get complicated, so it would be very difficult to try and maintain a default regex that works for everybody.

I've added the regexs above to the wiki page though.
