### ISSUE TITLE
Ocassionally Reads node_modules

### ISSUE THREAD

**Issue by GeorgeWL** [Gruntfuggly/todo-tree#258]
![image](https://user-images.githubusercontent.com/5931248/71084636-a45ec100-218d-11ea-98e0-2d472e52f760.png)

Most other modules which read file trees ignore `node_modules` by default and have it that one should override that setting.

Doesn't happen always though, just occasionally it finds them then on folder change it goes back to ignoring them.

**Comment by Gruntfuggly** [comment]
ripgrep honours your .gitignore file by default, so is it possible you have node_modules excluded in there?

**Comment by GeorgeWL** [comment]
the issue isn't that, it's that very very rarely, the node_modules appear despite being set to be ignored.

possibly a sign of some sort of race condition?

**Comment by GeorgeWL** [comment]
ah....I didn't setup the gitignore for this project and it's not using the more accepted ignore pattern of simply `node_modules` but rather using `/node_modules`
