### ISSUE TITLE
Group tags for a big project

### ISSUE THREAD

**Issue by HsunGong** [Gruntfuggly/todo-tree#259]
Some topics like https://github.com/Gruntfuggly/todo-tree/issues/136#issue-418231327 have talked about it, but there are some other questions.

For example, a project is built by different authors, and they use different type of `tags`.
Here, we assume they use `FIX` and `FIXME` and `FIXIT`, then, I'd like to group then into 1 group in ` "todo-tree.highlights.customHighlight"`
```
"FIX": {
    "all_tags" : [ "FIX", "FIXME", "FIXIT" ],
},
```

**Comment by HsunGong** [comment]
It is not good to change `regex` here.

**Comment by Gruntfuggly** [comment]
Would this be just for the highlighting to save entering multiple configurations, like "aliases"?

**Comment by Gruntfuggly** [comment]
Groups now supported - please try the latest version.

**Comment by HsunGong** [comment]
Some instructions:
(1) tags in "todo-tree.general.tagGroups" must appear in "todo-tree.general.tags" first.
(2) "todo-tree.tree.grouped" seems useless in settings.json, because we can find `Group by tag` button at sidebar(tree view header).
(3) "todo-tree.highlights.customHighlight" set highlight by group name.

**Comment by Gruntfuggly** [comment]
I'll take that as "Thank you"....

BTW, 1) and 3) are covered in the README.md. 2) The value in the settings is used as the default for new trees.
