### ISSUE TITLE
Orange color background didnt work

### ISSUE THREAD

**Issue by AhmadShiddiq** [Gruntfuggly/todo-tree#260]
I want make configuration for FIXME tag background with orange color.
here my configuration : 
```
"todo-tree.highlights.customHighlight": {
        "TODO": {
            "icon": "calendar",
            "foreground": "black",
            "background": "white",
            "iconColour": "white",
        },
        "FIXME": {
            "icon": "rocket",
            "foreground": "white",
            "background": "orange",
            "iconColour": "orange",
        }
    },
```
Here the results : 
![image](https://user-images.githubusercontent.com/53107961/71414637-67616580-268a-11ea-94ce-870589a2fbeb.png)

**Comment by Gruntfuggly** [comment]
"orange" isn't one of the predefined colours, but you can use hex, so try "#ff8000" instead.

**Comment by AhmadShiddiq** [comment]
Its works
I don't know hex its work right here. Thanks

**Comment by AhmadShiddiq** [comment]
Its works well with hex code, thanks :D
