### ISSUE TITLE
If tag text missing, the comment string appears

### ISSUE THREAD

**Issue by crystalfp** [Gruntfuggly/todo-tree#261]
Issue Type: <b>Bug</b>

1. Edit a typescript file
2. Define a tag (in my case "TBD") in `"todo-tree.general.tags"` and give it a foreground color in `"todo-tree.highlights.customHighlight"`. For me this tag signal an empty block I have to fill.
3. Put in the typescript file the line `// TBD` (I have it in a class method, that is after two tabs)
4. Go to the overview
5. Notice the line after the icon is `TBD //`. I think it should contain `TBD` alone, because the comment text is empty. (I use it to mark something obvious to do. Otherwise I have the `TODO` tag that should have an explanation of what to do)

Thanks!
mario

Extension version: 0.0.162
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (4.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Gruntfuggly** [comment]
It's because the default behaviour is that if there is nothing after the tag, it shows the text before the tag in the tree, which is a bit confusing I guess. I'll see if there is a better way...

**Comment by crystalfp** [comment]
Interesting. I don't remember having read this behavior in the documentation, but sure it is my fault. And yes, it is confusing.
Thanks for clarifying!
mario

**Comment by Gruntfuggly** [comment]
It's not documented. It's a throwback to when the extension was simpler - it basically tried to find "something" to display in the tree. When I added support for specifying a format for the tree items, I used the result of extracting the tag from the search match without realising it could match the part before the tag too.

I have a fix: `${after}` (the default tag format) will be changed to show the text after the tag as you would expect. I'll add a new format `${afterOrBefore}` which will exhibit the existing behaviour. I'll change the default to `${afterOrBefore}` as that will have the least impact on existing users, but it will allow you to change the format and see what you would expect.

**Comment by crystalfp** [comment]
Seems a very reasonable fix. Thanks!

**Comment by Gruntfuggly** [comment]
Please try 0.0.163 and let me know if it works as expected. You probably don't even need to change the format as I think I fixed it in a better way.

**Comment by crystalfp** [comment]
Thanks! It works perfectly. And with no changes to the configuration (label format remains at: `${tag} ${after}`). I close the issue.
