### ISSUE TITLE
Click status bar count -> open panel

### ISSUE THREAD

**Issue by dillingham** [Gruntfuggly/todo-tree#262]
Thanks for this great package!

`todo-tree.general.statusBarClickBehaviour` doesn't `reveal` the tree view

Nothing happens when clicked.

**Comment by Gruntfuggly** [comment]
It's a known bug (#248) - will be fixed in the next release (in the next few days).

**Comment by dillingham** [comment]
Ah, sorry didn't come up when I searched.
Thanks again for your work on this package!
