### ISSUE TITLE
Todo Tree list is not refreshed

### ISSUE THREAD

**Issue by kanlukasz** [Gruntfuggly/todo-tree#263]
Hello,

If I close my files where i have TODOs, the list in Sidebar does not refresh
The files are closed but still appear in Sidebar

Can we do something about it?

#### Example:
As shown below, no files are open, but TODOs still exists
![obraz](https://user-images.githubusercontent.com/30685349/72089013-8fe49300-330b-11ea-8c66-8073f0d09873.png)
![obraz](https://user-images.githubusercontent.com/30685349/72089033-9a9f2800-330b-11ea-9d28-8cd041ebbce9.png)

I don't have any project or folder open
![obraz](https://user-images.githubusercontent.com/30685349/72089022-95da7400-330b-11ea-9d34-d1e79191575b.png)

My env:
```
Version: 1.41.1 (system setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363
```

**Comment by Gruntfuggly** [comment]
Do you have `todo-tree.tree.showTagsFromOpenFilesOnly` set to true? Also, is this where you have opened a new window, opened files and then closed them again, i.e. never opened a workspace?

**Comment by kanlukasz** [comment]
I never use Workspaces (Save Workspace As). To be honest, I don't understand the difference between a workspace and a folder, but that's not important at the moment (I think).

Anyway if I set `"todo-tree.tree.showTagsFromOpenFilesOnly": true`, it works fine, but this setting has a conflict because when I open the folder with files nothing will be scanned

If I work with a folder, everything is fine with the default setting, but the problem occurs when I work only with individual files (without an open folder in VSCode).

Hmmm maybe it will be better if I show you this on a GIF video:
![---090](https://user-images.githubusercontent.com/30685349/72169586-b4a23e80-33cf-11ea-9311-e4e61f4f85a4.gif)

**Comment by Gruntfuggly** [comment]
Yes, that's the problem. At the moment it only removes files from the tree when *showTagsFromOpenFilesOnly* is true, as it assumes that the tree would get refreshed normally otherwise. It's a simple change, that I don't think causes any other problems, so I'll add it in the next release. If you want to change it yourself in the meantime, remove the second half of the if statement at line 1107 of `extension.js`.

**Comment by Gruntfuggly** [comment]
One thing to note though, is that there may be a delay of up to 3 minutes before the tree gets refreshed because the editor close event can take up to that long to be generated.

**Comment by Gruntfuggly** [comment]
Please try 0.0.163 and let me know if it works as expected.

**Comment by kanlukasz** [comment]
I did a quick test, but from what I see, it works well now
