### ISSUE TITLE
Todos in html

### ISSUE THREAD

**Issue by Mumcio** [Gruntfuggly/todo-tree#265]
Hi, plugin can not parse todos like <-- TODO: --> in html template.

**Comment by Gruntfuggly** [comment]
Please can you post an example of a TODO you think it should match.

**Comment by mbomb007** [comment]
HTML comments need to start with `<!--`, not `<--`. This issue should be closed.

**Comment by Mumcio** [comment]
Yes @mbomb007 sorry for that typo, you right should be <!-- TODO: but it is still not working.

**Comment by Mumcio** [comment]
Example from html template:

`<!-- TODO: some todo task -->`

**Comment by Mumcio** [comment]
I see extension test, there is method like removeBlockComments. My comment is in angular component, so the name of file is template.component.html, so extension is *.component.html. 

`assert.equal( utils.removeBlockComments( "<!-- a -->", "x.html" ), " a " );`

**Comment by Mumcio** [comment]
I found the reason it was regex in my settings, case close. My bad  ; ) Sorry for rising this ticket.
` "todo-tree.regex.regex": "(//)\\s*($TAGS).*(\\n\\s*//\\s{2,}.*)*"`

**Comment by Gruntfuggly** [comment]
No problem - glad you got it sorted. 😄

**Comment by KyleKing** [comment]
Thanks, this ticket helped me as well!

FWIW, I used this regex for PUG and BAT files: `((//|//-|#|<!--|;|REM|/\*|^)\s*($TAGS)|^\s*- \[ \])`
- PUG comments: `//- TODO: Example TODO`
- BAT comments: `REM TODO: Another example`

**Comment by Gruntfuggly** [comment]
👍  I'll add it to the wiki.

**Comment by KyleKing** [comment]
@Gruntfuggly, I fixed escaping my version of the regex and added support for markdown lists (updated comment above - https://github.com/Gruntfuggly/todo-tree/issues/265#issuecomment-575900040)

Can you update the wiki accordingly or provide me access to edit the wiki? https://github.com/Gruntfuggly/todo-tree/wiki/Configuration-Examples#pug-and-bat-files

**Comment by Gruntfuggly** [comment]
I've opened the wiki for anybody - feel free to update it.
