### ISSUE TITLE
Background Highlight Configuration appears broken in 0.0.163

### ISSUE THREAD

**Issue by walterschell** [Gruntfuggly/todo-tree#266]
This configuration does not work for me.(No highlighting at all is performed, but tags are still identified in tree)
    "todo-tree.highlights.defaultHighlight": {
        "background" : "yellow"
    },
    "todo-tree.general.debug": true

Omitting the configuration, only setting the foreground color and/or the type work for me, but not in conjunction with setting background color.

 Match (Editor):{"file":"/a/path/to/a/file/foo.c","line":1,"column":1,"match":"//TODO: Check this"}

**Comment by Gruntfuggly** [comment]
Yep - I missed a line in a refactor.

**Comment by Gruntfuggly** [comment]
I've just uploaded a new version - please let me know if it works as expected.

**Comment by walterschell** [comment]
Can you post a url. There aren't any releases in github to dl from and when I do "Extensions: Check for Extension Updates" it claims my all my extensions are up to date

**Comment by walterschell** [comment]
Maybe I was just too impatient. Update seems to work. Thanks!

**Comment by Gruntfuggly** [comment]
They take a while to appear sometimes.
