### ISSUE TITLE
Use the new tree with collapsing items

### ISSUE THREAD

**Issue by aNickzz** [Gruntfuggly/todo-tree#269]
The new tree structure in the file explorer allows collapsing single child directories into a single item.

It would be nice if the TODO tree used this new feature.

https://code.visualstudio.com/updates/v1_41#_compact-folders-in-explorer

**Comment by aNickzz** [comment]
Probably worth making it configurable too, if that's an option, I'm not sure of the API.

**Comment by Gruntfuggly** [comment]
I've just uploaded a version which should support compact folders. Please let me know if it works OK. It respects the vscode `explorer.compactFolders` setting, but there is a setting `todo-tree.tree.disableCompactFolders` in case you want to turn it off.

**Comment by aNickzz** [comment]
Thanks! I'll check it out in a few minutes

**Comment by aNickzz** [comment]
Granted its been more than a few minutes 🙄
