### ISSUE TITLE
ignore markdown.json file (VSCode snippets)

### ISSUE THREAD

**Issue by danielschmitz** [Gruntfuggly/todo-tree#27]
Ignore this file: AppData\Roaming\Code\User\snippets\markdown.json

plus: ignore all  "AppData\Roaming\Code\User\snippets\" files

im getting this "false positive" 🤣

![](https://i.imgur.com/4kwUqtD.png)

tks, great extension!

**Comment by Gruntfuggly** [comment]
I'm guessing that the markdown.json file is open in the editor? At the moment the ignore globs are only used when scanning the workspace. Files which are opened in the editor are not excluded - I'll try and add something...

**Comment by Gruntfuggly** [comment]
Just uploaded a version which should apply the globs to other files in the editor too. Let me know if it works as expected.
