### ISSUE TITLE
Deal with OneDrive "Files on Demand"

### ISSUE THREAD

**Issue by yzhang-gh** [Gruntfuggly/todo-tree#270]
Thank you for the nice extension.

I find a "problem" that when I open a OneDrive folder, all the files will be downloaded.
(see more about [Files on Demand](https://support.office.com/en-us/article/save-disk-space-with-onedrive-files-on-demand-for-windows-10-0e6860d3-d9f3-4971-b321-7092438fb38e?ui=en-US&rs=en-US&ad=US))

It would be great to disable auto search for folders under such a path
`C:\Users\<username>\OneDrive\...`

_original microsoft/vscode#89615_

**Comment by Gruntfuggly** [comment]
The extension doesn't download anything - it just runs ripgrep to do the search.

If you want to ignore folders from the search though, you can use `todo-tree.filtering.excludeGlobs`, e.g.
```
"todo-tree.filtering.excludeGlobs": [
    "C:\Users\<username>\OneDrive\"
]
```

**Comment by yzhang-gh** [comment]
That's right. It is ripgrep that triggers the downloading (due to the mechanism of OneDrive).

The `excludeGlobs` option is nice. Thanks for the information.

**Comment by yzhang-gh** [comment]
It looks like the "todo-tree: scanning..." status bar message never disappears (while the `excludeGlobs` works as expected, no search performed).

I have this setting

```json
"todo-tree.filtering.excludeGlobs": [
  "C:\\**\\OneDrive\\"
]
```

and opened `C:\Users\yzhang\OneDrive\Docs\a_folder\`

**Comment by Gruntfuggly** [comment]
Please can you post the contents of the TodoTree debug log from the Output View. You may need to enable `todo-tree.general.debug` first.

**Comment by yzhang-gh** [comment]
Sure.

```
Searching c:\Users\yzhang\OneDrive\Docs\raw...
Command: "c:\Users\yzhang\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg.exe" --no-messages --vimgrep -H --column --line-number --color never --max-columns=1000 --no-config  -e "((//|#|<!--|;|/\*|^|%)\s*(XXX|TODO|HACK|FIXME|BUG)|^\s*- \[ \])" -g "!C:\**\OneDrive\" "c:\Users\yzhang\OneDrive\Docs\raw"
```

I find I have the same issue in any folder now, with this `excludeGlobs` setting.
