### ISSUE TITLE
why my vscode don't show todo-tree?

### ISSUE THREAD

**Issue by linyanyuan** [Gruntfuggly/todo-tree#272]
![image](https://user-images.githubusercontent.com/23653800/74041707-225a7e00-4a01-11ea-9a01-f1e53aa839d8.png)
I installed todo-tree,but it's not show.

**Comment by Gruntfuggly** [comment]
Is what you see the equivalent of this?
![image](https://user-images.githubusercontent.com/376658/74045529-d853a700-49c4-11ea-8e8b-bf33c846792a.png)

**Comment by Gruntfuggly** [comment]
What version of VSCode are you using? Is there anything in the developer tools console log?

**Comment by linyanyuan** [comment]
> What version of VSCode are you using? Is there anything in the developer tools console log?
yes,developer tools show "Activating extension `Gruntfuggly.todo-tree` failed:  vscode.window.createTreeView is not a function".
![image](https://user-images.githubusercontent.com/23653800/74048153-a108e880-4a0c-11ea-98ff-4d9927847c28.png)

**Comment by Gruntfuggly** [comment]
What version of VSCode are you using? 
`vscode.window.createTreeView` is a standard API command, so I don't understand how that can fail.

**Comment by linyanyuan** [comment]
> is a standard API command, so I don't understand how that can fail.

version-1.19.2

**Comment by linyanyuan** [comment]
> What version of VSCode are you using?
> `vscode.window.createTreeView` is a standard API command, so I don't understand how that can fail.

The reason is that the version is too low, and the updated todo-tree is displayed
