### ISSUE TITLE
improve the default highlight style

### ISSUE THREAD

**Issue by tjx666** [Gruntfuggly/todo-tree#273]
The default style of TODOs highlight doesn't look good. Since then, why this extension enables highlight by default?  I think a lot of people should not like tossing configuration like me. It would also be better to show icon in the gutter by default.

Because this extension supports the TODOs highlight, so the uninstall the extension [TODO Highlight](https://marketplace.visualstudio.com/items?itemName=wayou.vscode-todo-highlight). But now, I may consider disabling the hight feature of this extension and reinstall  [TODO Highlight](https://marketplace.visualstudio.com/items?itemName=wayou.vscode-todo-highlight).

![screenshot_2020-02-09_13-23-59](https://user-images.githubusercontent.com/41773861/74096922-525c6b00-4b40-11ea-8a9b-f319458323be.png)

**Comment by Gruntfuggly** [comment]
I'm happy to take suggestions on how to improve the default highlights. What do you suggest?

Judging by the issues over the last few years I think that most people actually do prefer to configure the extension themselves.

Feel free to disable the highlights and use the other extension though.

**Comment by goevexx** [comment]
I also use TODO Highlight and gonna use the gutter icons. But when I disable "todo-tree.highlights.enabled" the icons also disappear. It would be nice to show the icons anyways if "gutterIcon": true for the custom highlight or add another option to enable gutter icons globally.

**Comment by Gruntfuggly** [comment]
If you just want the gutter icons, leave `todo-tree.highlights.enabled` and set 'foreground' and 'background' to '#00000000' in `todo-tree.highlights.defaultHighlight`. E.g.

```
    "todo-tree.highlights.defaultHighlight": {
        "foreground": "#00000000",
        "background": "#00000000",
        "gutterIcon": true
    }
```

I admit it's not very intuitive. It might easier to remove the `todo-tree.highlights.enabled` setting...

**Comment by goevexx** [comment]
![TODO-Tree not working with TODO-Highlight](https://user-images.githubusercontent.com/25805617/74287129-88107800-4d29-11ea-9efb-a465e274ecec.gif)

It seems to override Todo Highlight settings

**Comment by Gruntfuggly** [comment]
OK, try this:
```
    "todo-tree.highlights.defaultHighlight": {
        "background": "#000000",
        "opacity": 0,
        "gutterIcon": true
    }
```

**Comment by goevexx** [comment]
It works. Thank you!

**Comment by tjx666** [comment]
@Gruntfuggly  I try to imitate todo-highlight, some problems:

1. I don't find  a way to color the colon
2. Can I set the padding of the highlighted tag? like ` TODO: `，there are two spaces before and after the tag.
3. I want the comment text except tag keeps their color.  The following screenshot comment text is changed to be orange, but I want it to keep green as before.

![screenshot_2020-02-13_21-27-16](https://user-images.githubusercontent.com/41773861/74440506-152e0b00-4ea9-11ea-8719-7cfb6524756c.png)

**Comment by tjx666** [comment]
my config

```json
"todo-tree.highlights.defaultHighlight": {
    "gutterIcon": true
  },
  "todo-tree.highlights.customHighlight": {
    "TODO": {
      "foreground": "#fff",
      "background": "#ffbd2a",
      "iconColour": "#ffbd2a"
    },
    "FIXME": {
      "foreground": "#fff",
      "background": "#f06292",
      "iconColour": "#f06292"
    }
  },
```

**Comment by Gruntfuggly** [comment]
1. If you want to colour the colon, you could try adding the colon to the tags.
2. Again, probably only by making the spaces part of the tags.
3. The green and orange isn't coming from todo-tree. 

I think you might be better off using an extension which is designed for highlighting, such as this one: https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-highlight

It's not really possible to provide the amount of configuration you want.

**Comment by tjx666** [comment]
Thanks Reply @Gruntfuggly 
I found that the third problem was caused by better comments.
But, I think that highlighting tag includes the colon may be better by default, or just add a configuration option for example `renderColon?`

**Comment by tjx666** [comment]
@goevexx Maybe you need
The following configuration is the same as todo-highlight:

```
"todo-tree.highlights.defaultHighlight": {
    "gutterIcon": true
  },
  "todo-tree.highlights.customHighlight": {
    "TODO:": {
      "foreground": "#fff",
      "background": "#ffbd2a",
      "iconColour": "#ffbd2a"
    },
    "FIXME:": {
      "foreground": "#fff",
      "background": "#f06292",
      "icon": "flame",
      "iconColour": "#f06292"
    }
  },
```

I want to know what is the default icon name? The check icon is a pure check, but the default icon is surrounded by a circle.

**Comment by Gruntfuggly** [comment]
The default icon is the extension icon - it doesn't have a name as it's not part of the octicons set.
