### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by DragonGamesStudios** [Gruntfuggly/todo-tree#275]
1. I write in lua. To try this extension, I wrote `--TODO ...`. Didn't find todo.
2. I accidentaly turned off side panel of extension. Now I am unable to turn it on back.
Am I doing something wrong?

**Comment by Gruntfuggly** [comment]
If you want to find --TODO, you'll need to update the regex.

Try setting **Todo Tree _Regex:Regex_** to:
`((//|#|<!--|;|/\*|^|--)\s*($TAGS)|^\s*- \[ \])`

If you use the json editor, you'll need
`"todo-tree.regex.regex": "((//|#|<!--|;|/\\*|^|--)\\s*($TAGS)|^\\s*- \\[ \\])"`

The easiest way to find the view again, is to either select the view from the activity bar, or untick the setting **Todo Tree _Tree: Hide Tree When Empty_**.

**Comment by Gruntfuggly** [comment]
Hi - any luck getting it working?

**Comment by DragonGamesStudios** [comment]
Works now. Thanks

Pon., 24.02.2020, 16:18 użytkownik Nigel Scott <notifications@github.com>
napisał:
