### ISSUE TITLE
Respect "Search: Exclude" setting

### ISSUE THREAD

**Issue by mrleblanc101** [Gruntfuggly/todo-tree#276]
Hi,
The extension respect `File: Exclude` but not `Search: Exclude`.
I have wordpress plugin that need to be commited to our git repo because they are paid and can't be installed via composer. I want those plugin to be show in the tree view for updating and sometime reference, so I do not add them to `File: Exclude` as that would hide them from the tree view, but only `Search: Exclude` as that remove them from `Quick search` and `Find and Replace (global)`

**Comment by Gruntfuggly** [comment]
Can you post what your Search: Exclude setting is -  Is there a reason you don't want to set `todo-tree.filtering.excludeGlobs` to filter the results?

**Comment by mrleblanc101** [comment]
I guess I did not notice since it doesn't use the same UI element as the native filtering rule from VS  Code. I'll try the option you mentioned, maybe if it's possible, it would be nice to have a way to change this setting in the UI editor and not just the JSON editor. I still think the `Search: exclude` should be used as your extension `search` for TODO in files.
<img width="1309" alt="Capture d’écran, le 2020-02-21 à 19 09 38" src="https://user-images.githubusercontent.com/17392251/75081691-1630ef00-54de-11ea-8e07-c45b951a0613.png">

**Comment by mrleblanc101** [comment]
I understand why I didn't see the option, I had a leftover search in the UI editor so it would only show me option from your plugin that matched this search. But I still think my point stand 😅

**Comment by Gruntfuggly** [comment]
I've also made a change so that the globs can now be modified in the settings GUI.

**Comment by mindplay-dk** [comment]
I added `"todo-tree.filtering.excludeGlobs": ["node_modules/**"]` to my user-settings, and that doesn't seem to have any effect - I'm still seeing TODO items from files in `node_modules`.

I tried restarting as well.

**Comment by Gruntfuggly** [comment]
Try `"**/node_modules/**"`. If that doesn't work, can you enable the debug channel and have a look at the generated search command, and paste it here?

**Comment by Gruntfuggly** [comment]
Latest version now has an option to use the search.excludes too.

**Comment by mindplay-dk** [comment]
Adding `**/node_modules/**` did the trick :+1: 

It hadn't really occurred to me that these were *absolute* file-system paths - I'm coming over to VS Code from various IDEA-based IDEs, where generally most paths are relative to the project root.

**Comment by Gruntfuggly** [comment]
The extension supports multiple workspace roots, so absolute globs makes things easier. I'll add a note to the README.md to make it clearer.
