### ISSUE TITLE
Refresh after deleting a file

### ISSUE THREAD

**Issue by mindplay-dk** [Gruntfuggly/todo-tree#277]
Deleting a file (or entire directly) currently does not refresh the TODO list - any TODO items from within deleted files are still displayed in the list.

Deletion should probably trigger a refresh?

**Comment by Gruntfuggly** [comment]
It's possible to add a file watcher for the current workspace, but I haven't bothered in the past as the tree could easily contain files which are outside the workspace.

I can add it, but there will be limitations.

**Comment by Gruntfuggly** [comment]
Latest version can now watch files in the workspace. It's not enabled by default as I think there may be performance issues when making large changes to git repo's etc. but you can enable it to try:
`todo-tree.general.enableFileWatcher`.
I'll give it some more testing over then next few days to see if it needs more work.

**Comment by Gruntfuggly** [comment]
Yeah, it definitely needs some tweaks. I think it needs a throttle on when the tree is refreshed.

**Comment by mindplay-dk** [comment]
> It's possible to add a file watcher for the current workspace, but I haven't bothered in the past as the tree could easily contain files which are outside the workspace.

How?

Why would you need to scan outside the workspace?

**Comment by Gruntfuggly** [comment]
It's always been a configuration option.  My codebase at work is bigger than the workspaces I have open, but I still want to scan for TODOs to see a complete list.
