### ISSUE TITLE
todo-tree: alternations cannot currently contain empty sub-expressions

### ISSUE THREAD

**Issue by smullitconsulting** [Gruntfuggly/todo-tree#278]
What on earth does this mean? It appeared a while again literally will not go away. I AM NOT using ripgrep for anything all it's values are blank except the buffer which defaults to 200.

This popup is not only annoying, it is disruptive. How do I stop this?
![image](https://user-images.githubusercontent.com/48534889/75545385-cc6b6b80-59eb-11ea-8fb8-2f039fa13658.png)

**Comment by Gruntfuggly** [comment]
The extension uses ripgrep to search for TODOs. 

The error means there is something wrong with the regular expression. Could you post your settings in JSON format so I can try to reproduce it.

**Comment by Gruntfuggly** [comment]
BTW - sorry for the late response - I've been on holiday.

**Comment by Gruntfuggly** [comment]
Ah - I think it's because you have `||` in the regular expression. If you change your setting to
`((//|#|<!--|;|^|\s*\s\s)\s*($TAGS)|^\s*- \[ \])`
It should work.

**Comment by smullitconsulting** [comment]
My apologies, my computer decided to get moody a week ago and I just got it revived and back to development. I am testing this out now. I will advise on the outcome. 

 

Thanks for getting back to quickly! I’ve waited months for similar issues with other extensions and repos!

 

Thank you,

 

Shelby M. Smull

 



 

Schedule a Call:  <https://calendly.com/sitcs> https://calendly.com/sitcs

 

SITCS GitHub:  <https://github.com/smullitconsulting> https://github.com/smullitconsulting

 

SITCS NPM Registry:  <https://www.npmjs.com/~sitcs> https://www.npmjs.com/~sitcs

 

The Company Site Project is currently under very heavy construction. We are almost done with our Angular 9 Schematics Collection. Once that is complete, we’ll ramp up development on the Company Site Project. Thank you for your patience!

**Comment by smullitconsulting** [comment]
This has fixed the issue. Thank so very much @Gruntfuggly!
