### ISSUE TITLE
Extremely long activation time

### ISSUE THREAD

**Issue by BannerBomb** [Gruntfuggly/todo-tree#279]
- Extension Name: `todo-tree`
- Extension Version: `0.0.169`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.42.1`
The extension is displaying an extremely long activation time of 14 seconds.
![image](https://user-images.githubusercontent.com/11788894/75615551-ff5c4f00-5b12-11ea-93d9-179e42d5caaa.png)

**Comment by Gruntfuggly** [comment]
Can you check to see if `todo-tree.general.enableFileWatcher` is set to true? If so, please set it to false. I need to make some tweaks to this function as it's too simple at the moment.

**Comment by BannerBomb** [comment]
I don't have it enabled, these are the settings I have set for it.
![image](https://user-images.githubusercontent.com/11788894/75842474-5d509700-5d9e-11ea-9994-39b3506d8657.png)
![image](https://user-images.githubusercontent.com/11788894/75842482-66d9ff00-5d9e-11ea-9900-fd3ff5b51230.png)
![image](https://user-images.githubusercontent.com/11788894/75842496-71949400-5d9e-11ea-8010-cfe1f5a515f1.png)
![image](https://user-images.githubusercontent.com/11788894/75842509-79eccf00-5d9e-11ea-9fea-04d647c3b3a1.png)

**Comment by Gruntfuggly** [comment]
How big is your workspace? The extension searches at startup so it might just be taking a long time to do the scan.

Another thing to try - can you collapse and expand the tree using the buttons on the view title bar? It's possible that the expanded node cache has built up. You could also try Todo Tree: Reset Cache. This will reset a whole bunch of stuff.

I've also added an option to disable the initial scan which will be in the next release.

**Comment by BannerBomb** [comment]
Sorry for the late response, but my workspace only has about 17,000 files in it including the node_modules folder and about 200 files not including the node_modules. I haven't set any TODO's in any of my files yet. But the extension issue only happened on my desktop which has 4GB ram which is the model I listed as my OS version `OS Version: Windows_NT x64 10.0.18363` once I moved to a better computer with 32GB ram everything loads much quicker.

**Comment by Gruntfuggly** [comment]
OK - the option to disable the scan on startup will be added anyway, so it may be useful if you need it.

**Comment by ctf0** [comment]
> the option to disable the scan on startup will be added anyway

using this option moved the ext from +3sec to 14ms startup activation, i think away around could be checking when the editor is idle or maybe delay the activation of the scan by a few seconds until the editor has passed the startup threshold.

**Comment by Gruntfuggly** [comment]
There is a pending change to start the extension when everything else has finished starting, however, there is a bug in the current version of vscode which causes the extension to fail. It's been fixed in insiders, so once the next release comes out I'll update the extension.

**Comment by Gruntfuggly** [comment]
See https://github.com/microsoft/vscode/issues/112211

**Comment by ctf0** [comment]
there is also an activation event call [`onStartupFinished`](https://code.visualstudio.com/api/references/activation-events#onStartupFinished), maybe that could be an answer

**Comment by Gruntfuggly** [comment]
Yes, that's the change, but at the moment it causes the linked issue.

**Comment by Gruntfuggly** [comment]
Just uploaded v0.0.197 which now uses the "onStartupFinished" setting.
