### ISSUE TITLE
[Suggestion] Auto-Refresh enabler option

### ISSUE THREAD

**Issue by samael205** [Gruntfuggly/todo-tree#28]
Hi,

Can you add an option that allows you to block the automatic refresh every time a file is changed ?. There is a Refresh button, which when you press it refreshes the tree, but I do not see it when the tree automatically refreshes itself with each file change.

With this option, it would improve the speed when the tree does not have to be refreshed every time the documents change

**Comment by Gruntfuggly** [comment]
Sure - there used to be an option to enable/disable auto refresh but I didn't think anybody would need it so I took it out. Does it take a long time to do the refresh?

**Comment by samael205** [comment]
Let's see, really, it does not take a lot of time, but I think it will help the extension's performance, and it's possible to release processing tasks of having to refresh the tree every time the file is changed

**Comment by Gruntfuggly** [comment]
I've just uploaded a new version with autoRefresh configuration. It's enabled by default, but you can now set it to false to  disable it. It disables refresh when saving, closing and changing editors. 

Bare in mind that when you first start vscode, if the open file is not inside the current workspace, or is a temporary file like settings, then the tree won't show anything. You'll need to open a file in the workspace and hit refresh.

**Comment by samael205** [comment]
Thanks
