### ISSUE TITLE
skip external packages eg node_modules

### ISSUE THREAD

**Issue by dcsanx** [Gruntfuggly/todo-tree#281]
I'm looking for a config setting like `ignore` but I can't see that?

when i scan for TODOs i get hundreds of references from all the installed packages in my project [1].
how can I filter that out? I assume the same would happen for a python project.

PLUS this brings my machine to it's knees

do I have to edit the regex filters somewhere?
after adding some tags these are the only `settings.json` relevant things i can see.
also checked other issues for 'ignore'

```
    "todo-tree.tree.showScanModeButton": false,
    "todo-tree.general.tags": [
        "TODO",
        "HACK",
        "FIXME",
        "BUG",
        "RND"
    ],
```

![image](https://user-images.githubusercontent.com/58190733/76181820-bd20b680-617f-11ea-9a08-9d1fe3d55517.png)

**Comment by Gruntfuggly** [comment]
Try
```
"todo-tree.filtering.excludeGlobs":[
   "**/node_modules/**"
] 
```

**Comment by Gruntfuggly** [comment]
Hi did you get this to work?

**Comment by dcsanx** [comment]
not yet, thanks tho. you can close if you like.

**Comment by Gruntfuggly** [comment]
OK, feel free to reopen if you have problems.
