### ISSUE TITLE
Commands not found

### ISSUE THREAD

**Issue by bradypp** [Gruntfuggly/todo-tree#282]
When trying to use this extension with vscode, none of the commands work and no todos are found.
It stopped working for me when I switched from Windows 10 to Manjaro KDE v19.0.2 and installed my vscode settings using the Settings Sync extension.

I've attached an image of the notifications I get when trying any command.

![image](https://user-images.githubusercontent.com/53856442/76207486-c64c6a80-61f5-11ea-8292-541a839ef0d5.png)

**Comment by Gruntfuggly** [comment]
Which version of vscode are you using? Can you open the console window (Help->Toggle Developer Tools) and see if there are any errors in there?

**Comment by Gruntfuggly** [comment]
Also, could you trying uninstalling and reinstalling the extension? It looks like it has failed to install for some reason...

**Comment by Gruntfuggly** [comment]
What was the the problem?

**Comment by bradypp** [comment]
Thanks for your help, I should've posted a reply. Everything's working properly after updating vscode to the latest version.

**Comment by Gruntfuggly** [comment]
No problem - glad it's working!
