### ISSUE TITLE
Version 0.0.168 seems to be working, but not 0.0.169 (currently latest).

### ISSUE THREAD

**Issue by joafii** [Gruntfuggly/todo-tree#284]
I'm a newbie using VS Code 1.43.0 on OS X. The current latest version (0.0.169) is not working at all, but downgrading to 0.0.168 seem to be on track.

I hope that the info can help improve this handy little extension.

Best,
joafii

**Comment by Gruntfuggly** [comment]
Please can you check the console (Help -> Toggle Developer Tools) and see if there are any errors?
Is "TODOs" listed in the View->Open View... menu?

**Comment by Gruntfuggly** [comment]
What's odd is that 0.0.169 only turns off file watching by default. If anything I would expect 168 to fail (if you have a large workspace) but 169 to work :confused:

**Comment by joafii** [comment]
It doesn't seem to be the file watching that's issue here?

I got these with 0.0.169.

:)

**Comment by Gruntfuggly** [comment]
Did you find any errors in the console window? If you turn debug on, is the Todo Tree view available in the Output window?

**Comment by joafii** [comment]
Ah, I didn't realise that the email reply was ending up here — without the attached images showing. 
![Screenshot 2020-03-11 at 07 39 17](https://user-images.githubusercontent.com/48448296/76520446-357ac680-6463-11ea-9c22-9a9f25ee566e.png)
![Screenshot 2020-03-11 at 07 36 12](https://user-images.githubusercontent.com/48448296/76520458-39a6e400-6463-11ea-83b5-845ee3981f28.png)
![Image 11-03-2020 at 07 35](https://user-images.githubusercontent.com/48448296/76520461-3b70a780-6463-11ea-8c76-4982dac06b18.jpg)

**Comment by Gruntfuggly** [comment]
It looks like the extension hasn't installed properly. Not sure why? Can you try installing 169 again and if the same error happens, go into the extension folder `.vscode/extensions/Gruntfuggly.todo-tree-0.0.169` and do `npm install`.

**Comment by Gruntfuggly** [comment]
Any luck getting this to work?

**Comment by lymims** [comment]
I meet the same problem.

I'm using VS Code in windows 10. The version 0.0.168 is OK, but later versions (0.0.169 - 0.0.171) not work.

> It looks like the extension hasn't installed properly. Not sure why? Can you try installing 169 again and if the same error happens, go into the extension folder `.vscode/extensions/Gruntfuggly.todo-tree-0.0.169` and do `npm install`.

I've tried and still not working.

**Comment by lymims** [comment]
Here is the console info in Developer Tools:

![image](https://user-images.githubusercontent.com/9443706/77872552-d944de80-7279-11ea-822a-ca213c78708b.png)

**Comment by Gruntfuggly** [comment]
What version of vscode are you running? The warning suggests that an API is not available, which sounds like you might be running an older version.

**Comment by Gruntfuggly** [comment]
What doesn't make any sense is that version 169 was literally just a change to a default setting - to turn a feature off!?

**Comment by lymims** [comment]
![image](https://user-images.githubusercontent.com/9443706/77885802-45cfd580-729a-11ea-921a-339fc75d20ac.png)

**Comment by Gruntfuggly** [comment]
That explains it - the current version is 1.43.2. Is there a reason you need to be running an older version?

**Comment by lymims** [comment]
You are right, I don't know when and why I set the update mode of VS Code to none.

After updating to the latest version, the plugin works perfectly.

Thanks a lot!

**Comment by Gruntfuggly** [comment]
You should have a whole bunch of new and cool features as a bonus! 😀
