### ISSUE TITLE
Setting Todo Line Text Style

### ISSUE THREAD

**Issue by sharkweek** [Gruntfuggly/todo-tree#285]
The extension seems to be automatically stylizing the text that immediately follows the text, but I don't seem to have any control over color, font weight, etc. Is it possible to manipulate the style of the text _following_ the TODO (i.e. the actual TODO content)? If not, this would be a really useful feature.

**Comment by Gruntfuggly** [comment]
You can modify the highlights using **todo-tree.highlights.defaultHighlight**, e.g.
```
todo-tree.highlights.defaultHighlight
{
    "foreground": "white",
    "background": "red",
    "icon": "check",
    "type": "text"
}
```
The type can be set to any of: 
tag - highlights just the tag
text - highlights the tag and any text after the tag
tag-and-comment - highlights the comment characters (or the start of the match) and the tag
text-and-comment - highlights the comment characters (or the start of the match), the tag and the text after the tag
line - highlights the entire line containing the tag
whole-line - highlights the entire line containing the tag to the full width of the editor

Does that help? You can also set other styling like text decoration. See https://github.com/Gruntfuggly/todo-tree#highlighting

The only thing you can't do is set _different_ styling for the text after the TODO.

**Comment by sharkweek** [comment]
Ah, okay. I was looking for how to set a different styling for the text after the TODO.

**Comment by Gruntfuggly** [comment]
What sort of thing were you thinking? The difficulty is coming up with a way to specify what it should be.  I could allow some extra formatting "styles" in the label format setting. It might be a bit convoluted though as you can't simply specify CSS to be used - it needs to be converted to JSON....

**Comment by sharkweek** [comment]
I would imagine, it would be specified by everything in the regex except the `$TAGS` variable, but I haven't really thought it out.

**Comment by Gruntfuggly** [comment]
You might be better off using this extension alongside todo-tree:
https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-highlight
It is much more configurable for highlighting.

**Comment by sharkweek** [comment]
That's actually a perfect companion. Thanks!

**Comment by Gruntfuggly** [comment]
Yes, I use it myself to match stuff that's more complicated!
