### ISSUE TITLE
Wrapping / multiline TODO text content in sidebar

### ISSUE THREAD

**Issue by alystair** [Gruntfuggly/todo-tree#289]
Could we get an option to wrap TODO contents a few times in the sidebar so I don't need to open the actual file to quickly review them? Currently they cut off after a single line

![image](https://user-images.githubusercontent.com/159109/77237224-affec100-6b9c-11ea-9831-39690c01c949.png)

**Comment by alystair** [comment]
Could save even more space by having a "Hide Tag When Grouped by Tag" option to go with the current "Hide icon" option :D

**Comment by Gruntfuggly** [comment]
Unfortunately the API doesn't allow for wrapping, and splitting manually would be difficult as there's no way to know how wide the sidebar is.

I could add the TODO content to the tooltip?  At the moment it just shows the location.

Regarding hiding the tag, you could change the label format with `todo-tree.tree.labelFormat`. By default it is set to `${tag} ${after}` so you could remove the `${tag}` part.

**Comment by alystair** [comment]
Thanks for the label format hint! Tooltip could work assuming you can set a sane max-width and have a hard limit ellipses cut off if someone happened to write single-line novel :p

**Comment by alystair** [comment]
Won't be as intuitive as native sidebar but should be sufficient until someone implements API based wrapping

**Comment by Gruntfuggly** [comment]
lol - yeh, there's scope for some runaway cases, but I can't think of another way really. I'll add it in the next release - I'll probably make it configurable like the label so that people can set it up how they want.

**Comment by Gruntfuggly** [comment]
Try the latest version - there's a setting `todo-tree.tree.tooltipFormat` which uses the same placeholders as the label format option. It defaults to `${filepath}, line ${line}` so the existing functionality is changed, but if you change it to something like `${after}` you'll get the content after the tag. 

Let me know what you think, or if you have any further ideas.

**Comment by alystair** [comment]
Just tried the labelFormat trick, can see why it's not a default considering 'empty' TODOs show up as invisible strings - although in my case it forces me to actually give the reason I put in the tags to begin with... documentation is good!

I'll wait for the update to hit the wire as it's not showing up in VSC yet. Your response turnaround time is incredible :D

**Comment by Gruntfuggly** [comment]
Yes, sorry I got delayed with the publish step. Should be there now.

**Comment by alystair** [comment]
This is perfect and well documented - thanks so much again for the active maintenance! Hope others gain functionality from these additions <3
