### ISSUE TITLE
Optimize display of TODOs

### ISSUE THREAD

**Issue by s-albert** [Gruntfuggly/todo-tree#29]
A tiny request:
In the explorer view TODOs are shown like: // TODO:.....
The double slash should be skipped, because it adds no information. Just show it like: TODO:......

**Comment by Gruntfuggly** [comment]
I did think about doing this, but it's not as simple as it might seem at first. I'll see if I can add it though.

**Comment by Gruntfuggly** [comment]
I've just uploaded a new version which will remove the comment parts. It only works if you use the $TAGS form of the regex, but this should be most people anyway.

Please let me know if you see any issues.

**Comment by s-albert** [comment]
It works. Thanks.
