### ISSUE TITLE
Access to CSS Margins for defaultHighlight

### ISSUE THREAD

**Issue by Mochnant** [Gruntfuggly/todo-tree#290]
When highlighting just the tag, it would be nice if I could add some margins to the tag so that the background highlighting would look a bit more like a button/tag.  Currently, the TODO is a little awkward looking to me.  I think the spacing (a few pixels) would help.

An example:

![image](https://user-images.githubusercontent.com/746190/77347898-eeb48880-6d0e-11ea-8ce1-05f9074f8190.png)

Thanks for considering!

**Comment by Gruntfuggly** [comment]
Hi - unfortunately the vscode API doesn't provide any settings for margins or padding.
I tried adjusting some of the border properties but they just end up squashing the text inside the TODO. 

You could raise an issue against vscode to see if they'll extend the API (see https://code.visualstudio.com/api/references/vscode-api#DecorationRenderOptions).

**Comment by Mochnant** [comment]
Thanks for the reply.  Hopefully vscode will be willing.

**Comment by Mochnant** [comment]
Looks like we need 20 upvotes in the next 60 days (less now) to get it into the backlog.  Here's to hoping!

**Comment by Gruntfuggly** [comment]
Sorry the feature request didn't get enough votes!
