### ISSUE TITLE
[Feature Request] Choose which tags to show in status bar

### ISSUE THREAD

**Issue by phatmann** [Gruntfuggly/todo-tree#291]
I have TODOs and FIXMEs, and I want to only show the FIXMEs in status bar to give them my full attention.

I know I can show both and that is fine, but filtering would be ideal.

**Comment by Gruntfuggly** [comment]
I can see how this would be useful, but have you got any suggestions  for how to configure it?

**Comment by phatmann** [comment]
I propose that we add a new `hideFromStatusBar` property to the custom highlight settings. This would affect the "tags" and "top three" `statusBar` settings, but would not affect the "total" setting.

OPTIONAL: we could provide an "all tags" option for the `statusBar` setting. It would show hidden and non-hidden tags in the status bar. It would be particularly useful when `statusBarClickBehaviour` is set to "cycle",  as clicking could be used to reveal hidden tags.

**Comment by Gruntfuggly** [comment]
OK - I've just uploaded a version which allows to set `hideFromStatusBar`. I'm not sure about the all tags option for the status bar as it could become confusing - if you've set `hideFromStatusBar` you probably don't want it to show them again.

The only thing I thought was it could show (Hidden:xx) as an alternative?

**Comment by phatmann** [comment]
Great news! I will give it a whirl. 

Additional statusBar options are always nice, but if it is not clear which ones make sense, it might be better to wait for further feedback. I do not have a strong opinion myself.

**Comment by phatmann** [comment]
Just tried it, works perfectly! This is a nice boon for my workflow on a very crowded status bar. Thanks so much.
