### ISSUE TITLE
[Feature Request] Export via commandline

### ISSUE THREAD

**Issue by erichiller** [Gruntfuggly/todo-tree#293]
Sort of an extension to #170 , I'd really like to be able to export the todos in an automated fashion (build job, etc) from the CLI ( independent of VSCode or add a cli argument to VSCode ). In my case, I'd like to create a pre-commit hook that exports all todos to a central file for easier consumption by people browsing GitHub.
I'm not sure how feasible this is, or if it's outside the scope, but it would be incredibly helpful!

Thanks!

**Comment by Gruntfuggly** [comment]
Would you be calling it from within vscode, like a task or something? Or would it be a completely separate process?

**Comment by erichiller** [comment]
If there is a way to call an extension action on the commandline for VSCode
ie.
```
code.exe --runExtensionAction "exportTodos"
```
that would be great. (but I have no idea if VSCode allows for something
like that).
Otherwise, I guess it would have to be from the system's commandline.

**Comment by Gruntfuggly** [comment]
I did have a look to see if this is possible, and I'm not sure it is. There might be a way to call the native node code from the command line though...

**Comment by erichiller** [comment]
Ya, that'd be great!

**Comment by Gruntfuggly** [comment]
Hi - I'm really sorry, but I don't think I'm ever going to get round to doing this. I think it's probably quite a lot of work, and unfortunately you're the only person who has requested it.

At the end of the day, the extension is just a wrapper for ripgrep, so you might want to just look at scripting that instead.
