### ISSUE TITLE
Strip trailing */

### ISSUE THREAD

**Issue by jens-duttke** [Gruntfuggly/todo-tree#294]
E.g. in JSONC files I'm using `/* @todo */` to indicate that a line (in my case translations), must be revised, like:
```js
"INVALID_NUMBER": "Invalid number", /* @todo */
```
Unfortunately in the tree, the VSCode extension shows:
![todo-tree](https://user-images.githubusercontent.com/4883142/78767573-12bcce80-798b-11ea-8f03-e849629df21d.png)

I would like to get rid of the `*/`, but I can't find a way to adjust the configuration, so that it strips the `*/`.
Is there a way to do that?

My configuration looks like:
```
"todo-tree.filtering.useBuiltInExcludes": "search excludes",
"todo-tree.general.tags": [
	"@todo"
],
"todo-tree.tree.labelFormat": "${after}",
"todo-tree.regex.regex": "(//|#|<!--|/\\*|^\\s*\\*)\\s*($TAGS)",
```

**Comment by Gruntfuggly** [comment]
This is similar to #292 - Todo Tree uses a module 'comment-patterns' to determine if a language uses block type comments and tries to remove them if it can.

I'll see if this should be working in this case.

**Comment by 1o55** [comment]
I have run into a similar issue with CSS files.

Using this as my regex setting:
`"todo-tree.regex.regex": "((//|#|<!--|;|/\*|^)\s*($TAGS)|^\s*- \[ \])"`

Results in this:
![todo-css-trailing](https://user-images.githubusercontent.com/1589115/78938808-e8e5d380-7a80-11ea-8be9-508aeeae4cf6.jpg)

When the todo tag comment is appended to the end of a line of code the trailing `*/` remains but when the comment tag is moved to its own line the trailing `*/` is omitted.

N.B.: I have not messed around with the regex as I have not yet been able to wrap my head around it in general.

**Comment by Gruntfuggly** [comment]
.jsonc is not supported by comment patterns. I'll see if there is a way to extend it and allow configuration through todo-tree.

**Comment by Gruntfuggly** [comment]
@1o55 Looks like this was a bug. Will be fixed in the next version (hopefully tonight).

**Comment by Gruntfuggly** [comment]
@jens-duttke It doesn't look like there is any way to add support for jsonc without submitting a pull request to the <https://github.com/nknapp/comment-patterns> module. If you fancy doing it, then todo-tree will just work once it's updated - let me know what you think.

**Comment by jens-duttke** [comment]
> @jens-duttke It doesn't look like there is any way to add support for jsonc without submitting a pull request to the https://github.com/nknapp/comment-patterns module. If you fancy doing it, then todo-tree will just work once it's updated - let me know what you think.

I didn't know that todo-tree handle the comments differently for different file formats.
I thought it's based on the `todo-tree.regex.regex` setting, which equals for all languages.

Wouldn't it be much easier and faster to work with a simple RegExp, which works for all languages? Like
```
(?<commentType>\/\/|#|<!--|;|\/\*).*?(?<tag>@todo)[\s\n]+(?<comment>.*?)[\s\n]*(?:-->|\*\/|\n|$)
```
https://regex101.com/r/hydyhK/1

**Comment by Gruntfuggly** [comment]
Because that would be much harder to maintain. It's also reinventing the wheel. A regex to handle all the comments supported (https://github.com/nknapp/comment-patterns/blob/master/docs/languages.md) is never going to be simple unfortunately.

`todo-tree.regex.regex` is used to searching for the todos - the processing of the comments after is handled separately. 

I could add another configuration setting to allow a regex to be used in addition to the comments pattern module - that would allow you to add support for jsonc.

I'll add something in and try it out.

**Comment by Gruntfuggly** [comment]
I was going to make this configurable, but it seems overkill. I've simply added a small fix so that jsonc files are treated as javascript when looking up the comment pattern.
