### ISSUE TITLE
Add option to get count of current file in status bar

### ISSUE THREAD

**Issue by maxipaxi** [Gruntfuggly/todo-tree#295]
I want the sidebar to still scan the entire workspace, but I would also like to have the count of todos in the current file in the status bar.

    "todo-tree.general.statusBar": "current file"

Very nice extention, thank you for making it.

**Comment by Gruntfuggly** [comment]
OK - should be a quick one.

**Comment by Gruntfuggly** [comment]
Latest version now supports a new setting `current file`.

**Comment by jhogervorst** [comment]
I came here to suggest this feature, but it’s already implemented

**Comment by Gruntfuggly** [comment]
Good spot - I'll update in the next release.
