### ISSUE TITLE
Option to toggle highlights in minimap

### ISSUE THREAD

**Issue by alystair** [Gruntfuggly/todo-tree#296]
Right now if you turn on highlighting they also appear in the minimap which can be very distracting. I had to turn off highlighting because of this.

Would love a toggle to enable/disable this :)

**Comment by Gruntfuggly** [comment]
Could you attach a screenshot? They don't show in the minimap for me, just the ruler.

**Comment by alystair** [comment]
Maybe I was thinking of the ruler because my current theme is flat... (white is TODO, others are GIT etc)

![image](https://user-images.githubusercontent.com/159109/78817674-810c8b80-79a1-11ea-919e-96088b80bdd3.png)

**Comment by Gruntfuggly** [comment]
You can disable the ruler markers by setting `rulerLane` to `none` in `todo-tree.highlights.defaultHighlight`.

**Comment by alystair** [comment]
Ok great, thanks - didn't think about that!
