### ISSUE TITLE
Using built-in icons

### ISSUE THREAD

**Issue by alystair** [Gruntfuggly/todo-tree#297]
Just curious what the rational was behind not using the built-in 'Codicons'? Were they too limiting?
https://github.com/microsoft/vscode-codicons

**Comment by Gruntfuggly** [comment]
When the extension was first written, codicons weren't available. Somebody had written a node module to generate .pngs from octicons (which vscode was using for the status bar), so I added support for those. I ought to update it to allow theme icons to be used now...

**Comment by alystair** [comment]
Should be pretty low priority, I'm OK with current icons but it'll definitely make things easier for you in the long run, less to manage :)

**Comment by Gruntfuggly** [comment]
Yeh, it makes sense - it's a dependency I can remove and it will keep the look and feel inline with the rest of Code.

**Comment by Gruntfuggly** [comment]
I've added support for codicons too - just use "$(icon)" to specify one. Note, the old octicon support is still present, so you can still use "bug" for example for the octicon or "$(bug)" for the codicon  equivalent.

**Comment by alystair** [comment]
I'll submit a PR for the readme :D

**Comment by Gruntfuggly** [comment]
I've already updated it, but I haven't uploaded the latest release yet.

**Comment by alystair** [comment]
https://github.com/Gruntfuggly/todo-tree/pull/298 welp you're too fast for me ¯\\\_(ツ)_/¯

**Comment by Gruntfuggly** [comment]
Lol - thanks for the contribution though!

**Comment by Gruntfuggly** [comment]
I've just uploaded a new version - give it a try and let me know if it works as expected!

**Comment by alystair** [comment]
Fast as always Grunt, just tested it:
- Icons are a bit smaller, less readable
- sometimes vertically misaligned (ex. question icon), might be the size tho'
- Color setting does not affect them

Also, the link in the readme is broken because of the '.' at the end. Also recommend linking to https://microsoft.github.io/vscode-codicons/dist/codicon.html instead which shows the icon previews.

**Comment by Gruntfuggly** [comment]
Unfortunately there is no control over the size or alignment - it's all handled by Code itself. The colour is controlled by the theme. Might want to stick with octicons! 😁 Can you attach some screen grabs? The ones I tried looked OK.

Good spot on the link - will fix it - thank you.

**Comment by robertrossmann** [comment]
Also, it seems Codicons are not rendered in the editor gutter. My setting for default TODO item is as follows:

```json
{
"todo-tree.highlights.defaultHighlight": {
    "icon": "$(issues)",
    "gutterIcon": true,
    "foreground": "#F9E7C4",
    "background": "badge.background",
    "type": "line",
    "iconColour": "#CC6953",
    "rulerColour": "#CC6953",
    "fontWeight": "bold",
    "fontStyle": "italic"
}
}
```

**Comment by alystair** [comment]
Can't get to my machine right now but I do run at 1 zoom level below default, maybe that's what is causing the issues. 

Now I feel bad for suggesting this, your default icons are way nicer 😅

**Comment by Gruntfuggly** [comment]
@robertrossmann I don't think theme icons are supported in decorations. Looking at the API documentation, it says gutterIconPath is a string or a URL.

@alystair no worries - it's another option people can use if it works for them. To be honest, I don't expect many people will even notice it's available, unless they read the change log! :grin:
