### ISSUE TITLE
Synchronise ripgrep's hidden file search setting

### ISSUE THREAD

**Issue by kanlukasz** [Gruntfuggly/todo-tree#299]
I have file `.todo`:
![obraz](https://user-images.githubusercontent.com/30685349/79541209-b2fcac80-8089-11ea-856b-4dc3d96de094.png)

where i keep some TODOs:
![obraz](https://user-images.githubusercontent.com/30685349/79541304-e2131e00-8089-11ea-9ee8-83ffb623700c.png)

Works fine, but if I close the `.todo` file, then use the refresh icon, TODOs disappear:
![obraz](https://user-images.githubusercontent.com/30685349/79541381-0111b000-808a-11ea-8883-e04b40f8ccf1.png)

Enviroment:
```
Version: 1.44.1 (system setup)
Commit: a9f8623ec050e5f0b44cc8ce8204a1455884749f
Date: 2020-04-11T01:48:12.622Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

Plugin version:
latest

My settings:
```
	"todo-tree.general.revealBehaviour": "highlight todo",
	"todo-tree.tree.showInExplorer": false,
	"todo-tree.general.tags": [
		"TODO"
	],
	"todo-tree.general.debug": true,
	"todo-tree.general.statusBar": "tags",
	"todo-tree.tree.showCountsInTree": true,
	"todo-tree.highlights.defaultHighlight": {
		"background": "#383827",
		"rulerColour": null
	},
	"todo-tree.ripgrep.ripgrepArgs": "--no-ignore",
	"todo-tree.regex.regex": "(//|#|<!--|/\\*|^\\s*\\*)\\s*($TAGS)"

```
_*I tried with default regex but still nothing_

**Comment by Gruntfuggly** [comment]
What does it show in the log window? It sounds like it's only finding them by searching the open editor rather than using ripgrep.

**Comment by kanlukasz** [comment]
After closing this file and clicking `refresh`:

```
Searching c:\xampp\htdocs\www\webproject\dev...
Command: "c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg.exe" --no-messages --vimgrep -H --column --line-number --color never --no-ignore -e "(//|#|<!--|/\*|^\s*\*)\s*(TODO)" -g "!**/node_modules/**" -g "!**/wp-admin/**" -g "!**/wp-includes/**" -g "!**/vendor/**" -g "!**/wp-content/plugins/**" -g "!**/dev/wp-content/themes/mytheme/assets/css/**/*" "c:\xampp\htdocs\www\webproject\dev"
c:\xampp\htdocs\www\webproject\dev\wp-content\themes\mytheme\footer.php:15:5:				<!-- TODO: Nagłówki h3 do weryfikacji -->

c:\xampp\htdocs\www\webproject\dev\wp-content\themes\mytheme\assets\scss\bootstrap.scss:10:1:// TODO: text-body do poprawy

 Match (File): {"file":"c:\\xampp\\htdocs\\www\\webproject\\dev\\wp-content\\themes\\mytheme\\footer.php","line":"15","column":"5","match":"\t\t\t\t<!-- TODO: Nagłówki h3 do weryfikacji -->"}
 Match (File): {"file":"c:\\xampp\\htdocs\\www\\webproject\\dev\\wp-content\\themes\\mytheme\\assets\\scss\\bootstrap.scss","line":"10","column":"1","match":"// TODO: text-body do poprawy"}
Found 2 items
Applying globs to 2 items...
Remaining items: 2
```

It still finds other files, but not this one

**Comment by kanlukasz** [comment]
An interesting observation:
- if i change this file name from `.todo` to eg. `name.todo`, then it works fine

**Comment by Gruntfuggly** [comment]
It's because ripgrep ignores hidden files by default. You could try adding `--hidden` to `todo-tree.ripgrep.ripgrepArgs` but it may find some other stuff you're not expecting. Or you could explicitly add it to the include globs.

**Comment by kanlukasz** [comment]
OK I understand.
It is enough for me to close this issue.
Unless you have other improvement plans

**Comment by Gruntfuggly** [comment]
The reason that the file gets shown in the tree when it's opened is because the extension doesn't use the exact same logic as ripgrep - it would get a bit complicated trying to keep them in sync. I don't think there is really much that can be done about it.

**Comment by kanlukasz** [comment]
OK, so I close it
Thank you for the analysis and explanation

**Comment by Gruntfuggly** [comment]
I could add another config option to include hidden files, which could then automatically use `--hidden`. That might be a better way to do it and not too much effort. It would be more consistent.

**Comment by Gruntfuggly** [comment]
There is now a configuration option to include hidden files.

**Comment by kanlukasz** [comment]
Works fine 👍 Thank you so much
