### ISSUE TITLE
custom globs config not working

### ISSUE THREAD

**Issue by oldschool777** [Gruntfuggly/todo-tree#3]
I get the following error when I try to set a custom glob to exclude my composer packages directory:

`todo-tree: failed to execute search (error parsing glob ''!vendor/'': invalid use of ; must be one path component`

The config parameter I'm using is:
`"todo-tree.globs": ["!vendor/**"]`

From what I can see it follows the example, just with the directory "vendor", instead of "node_modules".

Any help would be greatly appreciated, so I can see just my TODOs, and not everyone elses :)

**Comment by Gruntfuggly** [comment]
Looks like it's a problem in Windows only. I'll investigate...

**Comment by Gruntfuggly** [comment]
Ah OK. I used single quotes where I should have used doubles. I'll upload a fixed versoin.

**Comment by oldschool777** [comment]
Awesome.  Thanks!  I updated to the latest version a couple nights ago and it's working great.  Thanks again for the quick fix!
