### ISSUE TITLE
how to ignore TODO of node_modules ?

### ISSUE THREAD

**Issue by lilijialiang** [Gruntfuggly/todo-tree#30]
how to ignore the TODOs of node_modules ?

**Comment by semenov-k** [comment]
@lijialiang how did you solve this problem?

**Comment by Gruntfuggly** [comment]
You can add `node_modules` to your .gitignore file as ripgrep respects those files by default.
You could also add node_modules to to `todo-tree.excludeGlobs`, e.g.
````
"todo-tree.excludeGlobs":["**/node_modules"]
```

**Comment by Darksoulsong** [comment]
Not working on version 0.0.162

**Comment by Gruntfuggly** [comment]
Yes, the correct setting name is now `todo-tree.filtering.excludeGlobs` (there were too many settings, so I needed to organise them).

Your second setting should work correctly though. Can you enable `todo-tree.general.debug` and see what is shown in the Output View?

**Comment by GeorgeWL** [comment]
don't you think node modules should be hidden by default?

**Comment by Gruntfuggly** [comment]
I don't think the extension should be adding default excludes. Some users may genuinely want to see TODO items from their node modules folder.

**Comment by GeorgeWL** [comment]
> I don't think the extension should be adding default excludes. Some users may genuinely want to see TODO items from their node modules folder.

almost every major extension doesn't read node_modules, as they are a huge blob of data that 90% of users don't need to look at.

**Comment by Gruntfuggly** [comment]
You could make the same argument for other folders that could be ignored, but the extension doesn't know what environment you are developing in, so it seems wrong to arbitrarily start ignoring folders. 

Is there a reason you don't want to add the exclude glob described above? 

Another alternative is if you've configured vscode to ignore node_modules using `"files.exclude"` you can set `todo-tree.filtering.useBuiltInExcludes` to use those too.

**Comment by WarHatch** [comment]
IMO since the huge majority of users will be annoyed by seeing a hundred todos they didn't write, it makes sense to hide them by default BUT allow the small percent of users who do want them to configure the settings to see them

**Comment by abumalick** [comment]
I have `node_modules` in `.gitignore` and it is still showing TODOs in the tree.

Any idea?

**Comment by Gruntfuggly** [comment]
Is it possible the file containing the todos is already open in the editor - those will get included. Otherwise, can you open the Todo Tree output console (enable `todo-tree.general.debug`) and post the contents of the generated command (and the search results if it's not too large)...

**Comment by abumalick** [comment]
Yes you are right I think, the file was probably opened in the editor.

Thank you very much 👍

**Comment by amirmeimari** [comment]
I `"todo-tree.filtering.excludeGlobs": ["**/node_modules"]` in my vscode setting and the problem seems to be fixed.

**Comment by fredriccliver** [comment]
> Not working on version 0.0.162. Vscode complains about an "Unknown Configuration Setting" when I try to set `"todo-tree.excludeGlobs":["**/node_modules"]`.
> 
> There's a `"todo-tree.filtering.excludeGlobs"`, though. But all the todos disappear by using
> 
> ```
> "todo-tree.filtering.excludeGlobs": [
>     "**/node_modules/*"
>   ]
> ```

If it doesn't work, try this.

```
"todo-tree.filtering.excludeGlobs": [
    "**/node_modules/**"
  ]
```

**Comment by jacobedawson** [comment]
Just came across this issue - VSCode smashing the CPU, found out it was Todo Tree searching node_modules. As mentioned by others, common / expected behaviour should be to exclude node_modules to handle the use case of 99% of users, thanks for the extension but yeah, seems like a simple fix to save people trying to diagnose an easily solved (and pretty annoying) issue.

**Comment by kiezosilva** [comment]
> You can add `node_modules` to your .gitignore file as ripgrep respects those files by default.
> You could also add node_modules to to `todo-tree.excludeGlobs`, e.g.
> 
> ```
> "todo-tree.excludeGlobs":["**/node_modules"]
> ```

Thanks!

**Comment by Gruntfuggly** [comment]
I've added `**/node_modules` to the default exclude globs for the next release.

**Comment by LarsOlt** [comment]
> I've added `**/node_modules` to the default exclude globs for the next release.

`**/node_modules` didn't work for me. I had to use `**/node_modules/*`
