### ISSUE TITLE
Cannot be used in a networkless environment

### ISSUE THREAD

**Issue by jcyongqin** [Gruntfuggly/todo-tree#300]
Cannot be used in a networkless environment

**Comment by Gruntfuggly** [comment]
Could you provide some more details? It doesn't make any network calls (as far as I know), so I don't understand why it wouldn't work.

If I disconnect my network it works fine for me.

(Lol - but I couldn't post this comment until I turned the network back on 🤦 )

**Comment by jcyongqin** [comment]
```js
{
username: "w**",
vscodeVersion: "1.43.2",
os: {
    platform: "linux"
    release: "Linux x64 2.6.32_1-16-0-0_virtio"
}
}
```
the system is contos 4.   

I don't know how to open debug log.

**Comment by jcyongqin** [comment]
I have set the 
```
{"todo-tree.filtering.includeGlobs" }
```
in workspace.

issue close
