### ISSUE TITLE
Empty sidebar from 0.0.171 to 0.0.172 (current)

### ISSUE THREAD

**Issue by sadovsf** [Gruntfuggly/todo-tree#301]
Hello, without changing anything in settings sidebar is last 2 versions empty. Debug output shows found todos but they does not get into sidebar list. Highlight works everything else seems to work. When i downgrade back to 0.0.170 sidebar is filled again properly. Maybe something broke in 0.0.171?

**Comment by Gruntfuggly** [comment]
The thing that changed that looks suspicious is the `hideFromTree` setting. Do you use this?

**Comment by Gruntfuggly** [comment]
Could you post all your todo-tree settings and I'll see if I can recreate it.

**Comment by sadovsf** [comment]
```
    "todo-tree.filtering.ignoreGitSubmodules": true,
    "todo-tree.general.debug": true,
    "todo-tree.regex.regexCaseSensitive": false,
    "todo-tree.regex.regex": "((//|#|<!--|;|/\\*)\\s*($TAGS)|^\\s*- \\[ \\])"
```

**Comment by Gruntfuggly** [comment]
If those are your only settings then that's quite wierd. Sorry, but can you also post a section of file with a TODO that it should find.

**Comment by sadovsf** [comment]
```
Match (File): {"file":"/Users/sadovsf/Documents/Projects.nosync/mantis_2_23/plugins/ManagementView/test/0_batch_bug_creation.unit.ts","line":"50","column":"13","match":"            //todo validate that remote parent exists?"}
 Match (File): {"file":"/Users/sadovsf/Documents/Projects.nosync/mantis_2_23/plugins/ManagementView/src/common/task_view_app_base.ts","line":"403","column":"6","match":"\t\t\t\t\t// Bug overlaps vacation and should be linked"}
 Match (File): {"file":"/Users/sadovsf/Documents/Projects.nosync/mantis_2_23/plugins/ManagementView/src/management_view/context_menu_operations.ts","line":"175","column":"2","match":"\t//todo Přidat dotaz jeslti zalogovat nějakou práci před zavřením tasku (když task mě nějaou zbývající ETA)"}
 Match (File): {"file":"/Users/sadovsf/Documents/Projects.nosync/mantis_2_23/plugins/ManagementView/src/common/components/create_tasks_dialog.ts","line":"344","column":"71","match":"        create_tasks_example += \"\\t- Fix issue needed for big feature #bug 1w\\n\";"}
 Match (File): {"file":"/Users/sadovsf/Documents/Projects.nosync/mantis_2_23/plugins/ManagementView/src/common/delta_operations_history/history_change_tasks.ts","line":"50","column":"17","match":"                // todo revert this function as well:"}
 Match (File): {"file":"/Users/sadovsf/Documents/Projects.nosync/mantis_2_23/plugins/ManagementView/src/common/templates/create_tasks_dialog.html","line":"29","column":"46","match":"\t\t\t\t\t\t\t<p>If task summary will contain text \"#bug\" it's task category will be made bug. When \"#wish\" is there category of task will be Wishlist. In case of \"#epic\" category will be Epic. These keywords are then removed from task sumary.</p>"}
 Match (File): {"file":"/Users/sadovsf/Documents/Projects.nosync/mantis_2_23/plugins/ManagementView/src/common/components/edit_task_sidenav/add_tag_button.ts","line":"53","column":"9","match":"        // todo: Optimize if many tags will be there"}
 Match (File): {"file":"/Users/sadovsf/Documents/Projects.nosync/mantis_2_23/plugins/ManagementView/src/common/components/base/sidenav_base.ts","line":"105","column":"5","match":"    //todo optimize this seems to take quite a lot time"}
```

Maybe this will be little better? (Debug output)

**Comment by sadovsf** [comment]
This log remains same across all versions. Only difference is that sidebar is empty after v0.0.170

**Comment by Gruntfuggly** [comment]
And are you just changing the version from the extensions view while code is running?
Also, is the view empty but present? or is there no view at all?
And also (sorry!) are you using the view in the explorer or the dedicated activity bar view?

**Comment by sadovsf** [comment]
* Iam changing version through visual studio itself:
![image](https://user-images.githubusercontent.com/2211533/79561211-409bc480-80a9-11ea-8e9e-2322ad0befcd.png)

* View is there, i can open it from sidebar i see all its buttons on top:
![image](https://user-images.githubusercontent.com/2211533/79561291-65903780-80a9-11ea-9325-4a8797d394e5.png)
![image](https://user-images.githubusercontent.com/2211533/79561309-6de87280-80a9-11ea-84e2-2c67c47875d6.png)

* Iam not sure what is activity bar. Iam using view that is on screenshots

**Comment by sadovsf** [comment]
Essentially
0.0.170
![image](https://user-images.githubusercontent.com/2211533/79561414-9f613e00-80a9-11ea-9a2e-452c53873614.png)

0.0.127-0.0.172
![image](https://user-images.githubusercontent.com/2211533/79561473-b56efe80-80a9-11ea-97c3-572f82e50c5b.png)


Debug output is in both cases same

**Comment by Gruntfuggly** [comment]
Thanks - the screenshots help!

Do you seen anything in the console log? (Help -> Toggle Developer Tools)

I'm clutching at straws a bit here, as it works fine for me with your settings.

**Comment by sadovsf** [comment]
Unresponsive extension host on top looks interesting

![image](https://user-images.githubusercontent.com/2211533/79562091-be140480-80aa-11ea-9271-9c5661dc9111.png)

**Comment by Gruntfuggly** [comment]
No - that's just because it's scanning your folder at startup which takes a while.
There's nothing else though.

The only thing I can think of to try is resetting some stuff.

Try `Todo Tree: Reset Folder Filter`
If that doesn't work, try `Todo Tree: Reset Cache`.

**Comment by sadovsf** [comment]
I did run both, still no luck though :-(
But there is more errors maybe:
![image](https://user-images.githubusercontent.com/2211533/79562756-d2a4cc80-80ab-11ea-9980-1c013de59219.png)

**Comment by sadovsf** [comment]
Interesting, i just did get it to work after i clicked 2-3 times (not sure) on 
![image](https://user-images.githubusercontent.com/2211533/79563025-48a93380-80ac-11ea-98ff-e36088dc16bb.png)
First click opened input box, second (while box was opened) showed in previously empty sidebar something like Empty or No entries essentially something about there not being anything to show. Then suddently todos poped in 😱

**Comment by Gruntfuggly** [comment]
Odd - so it's like there was a filter active? I thought it should show something in the tree if everything was filtered, but I can see it doesn't. That's definitely a bug, so I'll fix that.

**Comment by Gruntfuggly** [comment]
Wierd that it affected 171 and 172 though, although the way filtering works was slightly changed so that probably explains it.

**Comment by sadovsf** [comment]
It looks like so, true is that some time ago i was looking for some specific todos to fix them thus removing them. Maybe somehow filter remained there even after visual studio was closed. In a mean time i did forget about there being some filter and just saw today that list is empty. That sounds quite possible. I would maybe go eve so far to show current filter somewhere 🤔

Anyways, thank you for you help and mainly for this great plugin. Great work 👍

**Comment by Gruntfuggly** [comment]
The filter is preserved after restart. Do you remember if the icon was showing the 'funnel' or the clear filter icon? It should have shown the clear filter if there was a filter active. If you use the folder filters, it puts an entry at the top of the tree so you know. I'll expand this so it shows if the filter button has been used too.

**Comment by sadovsf** [comment]
I'am pretty sure it was funnel... But i cant reproduce it now 🤔 but tree is definitely empty. This is view after setting filter (intentionally such so there are no results) and Restarting VS code:
![image](https://user-images.githubusercontent.com/2211533/79564112-519b0480-80ae-11ea-89f9-7fc37c74149f.png)

**Comment by Gruntfuggly** [comment]
That's what I would expect. It should also say "Nothing found", so I'll get that fixed.

**Comment by sadovsf** [comment]
Great 👍
Maybe even use some more clear icon for clearing that filter but i admit, that can be quite personal problem and for some one else this icon may be crystal clear. Anyway, thank you once more 😊

**Comment by sadovsf** [comment]
I did not ever notice that there is some 😁 i usually work by keyboard shortucts so for me filter clear is escape + they have input visible there so it is 100% visible that you have some filter active. Maybe add such input box into tree as well then? 🤔

**Comment by Gruntfuggly** [comment]
Unfortunately the API doesn't allow that. You can also use the built in filter, but that doesn't work reliably, which is why I kept the toolbar filter. If the built in one worked, I'd just remove it...

**Comment by sadovsf** [comment]
I see, that's a pity anyway, just a fact that it will have text about empty filter result will help a lot 👍

**Comment by Gruntfuggly** [comment]
New version now has information on the current filter in a tooltip. When the global filter is used, this is also shown.

**Comment by sadovsf** [comment]
Awesome, will check it out. Thx 😊

**Comment by sadovsf** [comment]
Works like a charm, great :-) thx again. Good work 👍
