### ISSUE TITLE
Errors activating the extension

### ISSUE THREAD

**Issue by tamj0rd2** [Gruntfuggly/todo-tree#302]
For the last few weeks I've been getting these errors and can't pin down what's causing them:

![image](https://user-images.githubusercontent.com/20561445/79674601-9f158f80-81dc-11ea-9483-ecbafd447e97.png)

Highlights don't work and nothing appears in the left panel. This is version: 0.0.172
I've rolled back to version 0.0.162 and that seems to work

**Comment by Gruntfuggly** [comment]
I think I can see what the problem is, although I'm confused that it's not shown up before.
Would you be prepared to try a fix for me?

**Comment by tamj0rd2** [comment]
Sure, I'll give it a try

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Gruntfuggly** [comment]
Can you open `.vscode/extensions/gruntfuggly.todo-tree-0.0.172/utils.js` and at line 119 add
`var` at the start:
```
            var rightOfTag = text.substr( tagMatch.index + tagMatch[ 0 ].length ).trim().replace( /^:\s*/, "" );
```
and see if that makes any difference?

**Comment by Gruntfuggly** [comment]
Hi - did you have any luck with this?

**Comment by tamj0rd2** [comment]
Sorry, I hadn't had much time to look until now. I've just installed v0.0.174 and it seems to work perfectly again.

**Comment by Gruntfuggly** [comment]
OK - might have to file this one under "Nothing to see here, please move along...". 😬
