### ISSUE TITLE
Highlighting of Keywords

### ISSUE THREAD

**Issue by funnym0nk3y** [Gruntfuggly/todo-tree#304]
Hey, 

I don't know if this is a bug or just some weird configuration issue. Those are my settings for todo-tree: 

```
"todo-tree.general.enableFileWatcher": true,
  "todo-tree.general.tags": [
    "BUG",
    "FIXME",
    "TODO",
    "DONE"
  ],
  "todo-tree.highlights.customHighlight": {
    "BUG": {
      "background": "red",
      "foreground": "black",
      "icon": "bug",
      "iconColour": "red",
      "opacity": "60",
      "type": "text-and-comment"
    },
    "DONE": {
      "background": "#6A9955",
      "foreground": "black",
      "iconColour": "#6A9955",
      "opacity": "70",
      "type": "text-and-comment"
    },
    "FIXME": {
      "icon": "flame"
    },
    "TODO": {
      "background": "#FFAA00",
      "foreground": "black",
      "icon": "pencil",
      "iconColour": "#ffaa00",
      "opacity": "70",
      "type": "text-and-comment"
    }
  },
  "todo-tree.highlights.highlightDelay": 0,
  "todo-tree.regex.regex": "((//|#|<!--|;|/\\*|^|%)\\s*($TAGS)|^\\s*- \\[ \\])",
  "todo-tree.regex.regexCaseSensitive": false,
  "todo-tree.tree.showScanModeButton": false,
```

As far as I understand that configuration should highlight all comments in `.tex` files starting with `%TODO`, right? But TODO gets highlighted with or without the preceeding comment Symbol. My friend is using the same settings as me, but there it works porperly. When he removes the identifier, the highlighting is disabled. 

Thanks for the help!

**Comment by Gruntfuggly** [comment]
Are your TODOs at the start of the line?
Can you post an example one that is highlighted incorrectly?

**Comment by funnym0nk3y** [comment]
Yeah, they are at the beginning of the line. 

Here is a gif:
![725d3533-a2f6-4ecb-a35d-b79d78e2ff9f](https://user-images.githubusercontent.com/41870754/79766054-c167f400-8327-11ea-8382-01d1253680e6.gif)

**Comment by Gruntfuggly** [comment]
They're matching because of the regex - if you remove `|^` (which is 'start of line'), e.g.
```
"todo-tree.regex.regex": "((//|#|<!--|;|/\\*|%)\\s*($TAGS)|^\\s*- \\[ \\])",
```
it should only match them with % (or any of the other 'comment' characters).

**Comment by funnym0nk3y** [comment]
Ohhhh, thank you very much!! Regex are a kind of complicated for me.

**Comment by Gruntfuggly** [comment]
Lol - you're not alone!
