### ISSUE TITLE
Remove "None found" if zero TODOs are found

### ISSUE THREAD

**Issue by inkytonik** [Gruntfuggly/todo-tree#305]
When the extension displays the number of TODOs found in the current file, it appends "None found" in the status bar when the total count is zero. Since the number zero is already displayed, the "None found" is redundant. And it takes up quite a bit of space. I suggest removing the extra text because the number is sufficient.

**Comment by Gruntfuggly** [comment]
Latest version just uses 0 in all cases, to save space.

**Comment by inkytonik** [comment]
Great! Thanks for the update.
