### ISSUE TITLE
Question: Prefix TODO with @ - @TODO

### ISSUE THREAD

**Issue by KDCinfo** [Gruntfuggly/todo-tree#306]
Awesome pragmatic package! Was wondering if there is a way to replicate the `TODO` tag with **`@TODO:`** (simply prefixing TODO with an `@`). I've used `@TODO:` for years and is strewn across all my code. I've tried adding `@TODO` to `general.tags`, and added it as a `customHighlight`, but it still shows as green instead of orange.

```    "todo-tree.highlights.customHighlight": {
        "@TODO": {
            "foreground": "orange",
            "iconColour": "yellow",
            "gutterIcon": true,
            "icon": "check",
            "type": "line"
        }
    },```

Thanks for any thoughts or insights. -Keith

**Comment by Gruntfuggly** [comment]
It's because the orange isn't a recognised colour name. It only supports a small set of named colours (red, green, blue, yellow, magenta, cyan, grey, white and black). You can use hex values though (e.g. #ff8000) or colours from the theme.

**Comment by KDCinfo** [comment]
_That's so awesome._ **Thank you!!** I'm glad I tried a wrong color and asked, because my other problem was I hadn't set `todo-tree.highlights.enabled` to true, which is why it was green instead of white 😮 

Thank you very much for this answer and plug-in. I love @TODOs 🥇

**Comment by Gruntfuggly** [comment]
You're welcome. 😁
