### ISSUE TITLE
Intellisense delays when enabled for Powershell

### ISSUE THREAD

**Issue by spozner** [Gruntfuggly/todo-tree#307]
WIth only the Powershell extension enabled, Intellisense works great and the delay is miniscule.  Adding the Todo-Tree extension causes ~ a 6 second lag before intellisense can finish filling in the commandlets being typed.

**Comment by Gruntfuggly** [comment]
Hi - can you post your todo-tree settings? The only thing that happens when you're typing is the highlighting, and that should only happen half a second after you stop typing.

**Comment by spozner** [comment]
The only setting I have in the settings.json is: "todo-tree.tree.showScanModeButton": false
In looking here, I think I might have found the problem myself in that the plugin 'Better Comments' appears to be the conflict.  Removing the Better Comments extension as well as it's settings from the settings.json appears to have remediated the issue.  If only I could make both work together as that extension has more colorization features...  *Sigh*.  Thanks for leading me down that road!

**Comment by Gruntfuggly** [comment]
That's weird - so it's works OK if either of the extensions are enabled, but not both?

There are some things you could adjust in the todo-tree settings if you want to try and find what the conflict is.

You could try setting `todo-tree.highlights.highlightDelay` to a much higher value (3000) and see what happens.

**Comment by Gruntfuggly** [comment]
Hi - did you get anywhere with this?
