### ISSUE TITLE
Lose filtering when installing new node module while vs code is open.

### ISSUE THREAD

**Issue by RinaldoBenaccetta** [Gruntfuggly/todo-tree#309]
In node.js project, I add **/*/node_modules in settings>Filtering: Exclude Globs to not show the todo's from node_modules folder. That works fine.
But when I install a new node module in my project, all todo's from node modules appears.
A restart of VS Code make the filtering work again, but it's a bit annoying to restart every time you install a new module.

**Comment by RinaldoBenaccetta** [comment]
A look in the wiki showed me that the correct filter for node modules is **/node_modules/**. Problem solved!

**Comment by Gruntfuggly** [comment]
That's good - I was about to say I had no idea what was going on! 😁
