### ISSUE TITLE
Only show issues in open files?

### ISSUE THREAD

**Issue by voxpelli** [Gruntfuggly/todo-tree#31]
Is that currently possible? Else it would be a very neat addition.

On large projects, with many project owners, the list of TODO:s can become fairly large and the relevant TODO:s for ones task at hand might be hard to spot among the rest.

The TODO-plugin I used for Atom (https://github.com/mrodalgaard/atom-todo-show) had the option to eg. just show TODO:s from ones open files – that was a very useful way to get a focused views of one TODO:s (and would be especially so in this project when combined with the "expand all" option)

**Comment by Gruntfuggly** [comment]
It's definitely possible, although it's sort of the opposite reason for writing the extension in the first place. 8-)

It's a fair request though, so I'll add it...

**Comment by bluepowder** [comment]
I use Remote FS (https://github.com/liximomo/vscode-remote-fs) and since there are no files in the local workspace, todo-tree is not able to do its thing. An option to work only on open files may be a way to make todo-tree useful in this use case.

**Comment by Gruntfuggly** [comment]
Just uploaded a new version with a configuration option "showTagsFromOpenFilesOnly". Set this to false to prevent it scanning the workspace.
Let me know if it works!

**Comment by voxpelli** [comment]
Works well so far! Thanks a lot for the quick addition 🙏 🎉
