### ISSUE TITLE
Improvements to the view in the status bar

### ISSUE THREAD

**Issue by kanlukasz** [Gruntfuggly/todo-tree#310]
A small trifle:

![obraz](https://user-images.githubusercontent.com/30685349/80620783-b9563580-8a46-11ea-9f9e-20469e1de8e4.png)

I think it would be better if you remove the colon next to the counting
Now it's look like a emoticon `:O`  😁

So much better without a colon, look:
![obraz](https://user-images.githubusercontent.com/30685349/80621080-14882800-8a47-11ea-8a8b-9329ad6a4111.png)

**Comment by Gruntfuggly** [comment]
Yeah, I agree - it fits better with the problems icons, etc. too.

**Comment by kanlukasz** [comment]
I saw `0.0.174` . Much better 😻
One last thing - maybe add a small margin between `✔` and `0` - that will be 10000% perfect

**Comment by kanlukasz** [comment]
I noticed one more thing - if you have some TODOs, there still exist `TODO` and colon `:`

![obraz](https://user-images.githubusercontent.com/30685349/80701630-fd494900-8adf-11ea-979d-d50f5c3afe2c.png)

**Comment by Gruntfuggly** [comment]
That's expected though, because it is showing the number of "TODO" tags. If you also have "FIXME, for example, they are also counted.

It won't show "TODO:" if it is showing the total number of tags. 

The tooltip should indicate what is currently being shown.

**Comment by kanlukasz** [comment]
Ok, so, now we have something like this:
![obraz](https://user-images.githubusercontent.com/30685349/80703121-7a75bd80-8ae2-11ea-9a74-772b52b31293.png)

And here is my first idea:
![obraz](https://user-images.githubusercontent.com/30685349/80703428-0d165c80-8ae3-11ea-8288-979b70d76cf6.png)

or second idea:
![obraz](https://user-images.githubusercontent.com/30685349/80703512-3636ed00-8ae3-11ea-85f8-e1d0a88a4ba4.png)

**Comment by Gruntfuggly** [comment]
Why do you want to get rid of the colons?

**Comment by kanlukasz** [comment]
From my point of view _(I worked as a designer for many years)_, with colons it is a bit unreadable if you have no any space or margin (too tight)

Maybe adding a space between the colon and numbers is a solution
eg from native Tab Size:
![obraz](https://user-images.githubusercontent.com/30685349/80704763-77c89780-8ae5-11ea-8fe9-028f7049317b.png)

Of course, these are very very very very small details, i know.
Make your choice 😃

**Comment by Gruntfuggly** [comment]
Adding a space makes sense - it's inline with the rest of the status bar. If there are multiple, it would then make sense to comma separate them.

I just thought - another alternative option would be to show the icons, which would save space, but could be confusing with the problems status bar item. What do you think?

As you say small details, but worth getting right - I appreciate your input! 😁

**Comment by kanlukasz** [comment]
Ok, so the final version:

- `3px` or `4px` right margin for the `✔` stamp
- one space after each colon
- comma separation with one space if there is more than one `tag`
- no colon & no comma if there is no any `tag`

I hope I haven't missed anything

Screenshot with all the above improvements:
![obraz](https://user-images.githubusercontent.com/30685349/80714296-0a246780-8af5-11ea-95d8-bd7b5d0616e7.png)

Icons - it's an interesting idea and I thought about it, but I'm afraid that it will be too confusing and users will report it.
if I come up with something interesting about it, I'll give you a new ticket
At the moment, I would implement the above arrangements, which we discussed

Have a nice day 😊

**Comment by Gruntfuggly** [comment]
That's all OK, except there is no control over the width of the separator between the icon and the text. I can put a space in, but that's it unfortunately - it should look correct though.

**Comment by kanlukasz** [comment]
Putting space should be okay. The VSCode developers did it this way, from what i see here:

![obraz](https://user-images.githubusercontent.com/30685349/80717507-507bc580-8af9-11ea-9c91-77f80f5fbf28.png)

**Comment by Gruntfuggly** [comment]
Just uploaded a version with fixes for the spacing and commas.

**Comment by kanlukasz** [comment]
Perfect!
So i think we can close this issue too
