### ISSUE TITLE
Doesn't run on Markdown files?

### ISSUE THREAD

**Issue by jkmacc-LANL** [Gruntfuggly/todo-tree#312]
Hi, 

Thanks for the awesome extension.  It's exactly what I was looking for.  It works perfectly on my `.py` files (the "TODOS" item shows up in the Explorer), but it's completely absent on my markdown `.md` files.  All I'm doing is writing the word "TODO" or "FIXME" somewhere in the markdown file.  If there's a setting I need to tweak, it's not clear to me.  

Is there a way to get it to work for markdown files the same way it seems to be running for Python source files?

Thanks again!

**Comment by Gruntfuggly** [comment]
Normally, it needs "something" as a marker character before the TODO tag. In languages like C++ and javascript, it's the `//` comment. In Python it's `#`. Markdown doesn't really have comments, so you'll need another way to indicated them.

You could simplify the regex to just
```
"todo-tree.regex.regex": "($TAGS)"
```
but that might find lots of things that aren't really TODOs.

Or you could put them in HTML comments:
```
# Do Something <!-- TODO: By friday! -->
```

It already supports markdown todo list style though:
```
 - [ ] Do this
```

**Comment by jkmacc-LANL** [comment]
Ah, I see now that `<!-- TODO -->` shows up in the todo list, but what I'm looking for is the literal `TODO` in the regular text to trigger it, as in `...and it wasn't until TODO in 2010 that initial observations confirmed...`

I think I was able to fix it by doing the following:
1. Go to the preferences, and search for "todo regex".
2. Replace the default regex with just `($TAGS)`, which triggers the todo list to find keywords like FIXME and TODO in any context.  I just wanted to do this for my current workspace, so I made this change in the Workspace tab of the settings.
3. Profit!

Thanks again for this awesome plugin.

**Comment by dufferzafar** [comment]
Before:

![image](https://user-images.githubusercontent.com/1449512/140554167-220fed74-1e81-4673-a791-400fd0abdc0c.png)

After using the updated regex: `"todo-tree.regex.regex": "(//|#|<!--|;|/\\*|^|\\*|^\\s*(-|\\d+.))\\s*($TAGS)",`

![image](https://user-images.githubusercontent.com/1449512/140554633-299267f1-9789-4ca7-8fb1-b72b68a17035.png)
