### ISSUE TITLE
Unexpected behavior when used together with the Glitch extension

### ISSUE THREAD

**Issue by MindfulMinun** [Gruntfuggly/todo-tree#314]
I've been using [the Glitch extension](https://marketplace.visualstudio.com/items?itemName=glitch.glitch) to work on projects uploaded to Glitch within VS Code. The extension doesn't behave as expected within these workspaces. Instead of scanning just the files within my Glitch workspace, the extension seems to scan all files on my machine from root.

![Screenshot](https://user-images.githubusercontent.com/15158256/81487548-d5ff2400-9223-11ea-8b3c-94f753b2e7d2.png)

One workaround is to simply disable scanning by adding a wildcard to my excluded workspaces, but this isn't ideal. I've also tried just filtering this workspace by adding`"todo-tree.filtering.excludedWorkspaces": ["glitchfs://*"]` to my settings.json file, but this doesn't change anything.

**Comment by Gruntfuggly** [comment]
Could you have a look in the debug channel in the output pane (you might need to enable `todo-tree.general.debug` and then select Todo Tree from the drop down.

It should show the command that is being generated and the search results. If you can post the command and the first few results, that would be great.

**Comment by MindfulMinun** [comment]
Here's output after enabling `todo-tree.general.debug`.

```
Searching /...
Command: /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg --no-messages --vimgrep -H --column --line-number --color never --max-columns=1000 --no-config  -e "((//|#|<!--|;|/\*|^)\s*(XXX|TODO|HACK|FIXME|BUG)|^\s*- \[ \])" "/"
/usr/bin/zdiff:89:1:# XXX - assumes there is no optarg
/usr/bin/spfquery5.18:501:21:    'debug!',       # TODO Implement!
/usr/bin/spfquery5.18:502:21:    'sanitize!',    # TODO Implement!
/usr/bin/spfquery5.18:509:21:                    # TODO implement!
/usr/bin/spfquery5.18:510:21:    'tfwl!',        # TODO Implement!
/usr/bin/spfquery5.18:511:21:    'guess=s',      # TODO Implement!
/usr/bin/spfquery5.18:512:21:    'local=s',      # TODO Implement!
/usr/bin/spfquery5.18:513:21:    'override=s%',  # TODO Implement!
/usr/bin/spfquery5.18:514:21:    'fallback=s%',  # TODO Implement!
...
 Match (File): {"file":"/System/Library/Tcl/tcllib1.12/asn/asn.tcl","line":"672","column":"9","match":"        # BUG: improper length. It wastes cycles, and here it can"}
 Match (File): {"file":"/System/Library/Tcl/tcllib1.12/asn/asn.tcl","line":"673","column":"9","match":"        # BUG: cause us trouble, reading more data than there is"}
 Match (File): {"file":"/System/Library/Tcl/tcllib1.12/asn/asn.tcl","line":"674","column":"9","match":"        # BUG: on the channel. Depending on the channel"}
 Match (File): {"file":"/System/Library/Tcl/tcllib1.12/asn/asn.tcl","line":"675","column":"9","match":"        # BUG: configuration an attacker can induce us to block,"}
 Match (File): {"file":"/System/Library/Tcl/tcllib1.12/asn/asn.tcl","line":"676","column":"9","match":"        # BUG: causing a denial of service."}
Found 2204 items
```

**Comment by Gruntfuggly** [comment]
Yes, it's definitely not finding the right workspaces to search. I might need to get you to try some hacking if that's OK? Or alternatively, can you give me a minimal set up, or walk me through the steps to set up a similar set up?

Just out of interest, rather than filtering with excludes, does it work if you use `todo-tree.filtering.includedWorkspaces`?

**Comment by MindfulMinun** [comment]
Here's the minimal setup for reproducing the bug:

1. Make an account on [Glitch][glitch]: click the *Sign In* button on the top right, then *Create an account* near the bottom.
1. Jump to VS Code and install both the [Glitch][vs-glitch] and [Todo Tree][vs-todo] extensions.
1. With the both extensions installed, open the command palette (`Ctrl + Shift + P` on Windows and Linux or `Command + Shift + P` on Mac) and run `Glitch: Sign In`, then choose `Sign in on glitch.com`.
    - After a few seconds, you'll be redirected back to VS Code and a banner should appear in the bottom right indicating you've signed in successfully.
1. Open the command palette again and run `Glitch: New Project`. When prompted, choose any of the base projects.
1. The workspace should be replaced/updated with the Glitch workspace. After about 8-10 seconds, the Todos tab in the Explorer should become filled with Todos outside the workspace. (The default Glitch projects don't contain any Todos iirc.)

And yes, setting 
`"todo-tree.filtering.includedWorkspaces": ["glitchfs://*"]` behaves as expected, only the Todos within the Glitch workspace appear.

[glitch]: https://glitch.com/
[vs-glitch]: https://marketplace.visualstudio.com/items?itemName=glitch.glitch
[vs-todo]: https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree

**Comment by Gruntfuggly** [comment]
OK - thanks for the set up instructions. I'll have a go tonight after work and let you know.

**Comment by Gruntfuggly** [comment]
OK, I've found out why it was searching everywhere - it wasn't checking the scheme of the workspace folder - for the glitch workspace folder, the path is "/". For normal workspace folders, the path is the root folder. I can put a fix in. You'll still need to use the includedWorkspaces setting to search the glitchfs folder though.

```
{    
    "uri": {      
        "$mid": 1,      
        "fsPath": "/",      
        "external": "glitchfs://colorful-summer-spectacles/",
        "path": "/", 
        "scheme": "glitchfs",
        "authority": "colorful-summer-spectacles"    
    },    
    "name": "🎏 colorful-summer-spectacles",
    "index": 0  
}
```
```
{    
    "uri": {
        "$mid": 1,
        "fsPath": "/Users/nige/Projects/vscode-extensions/todo-tree",
        "external": "file:///Users/nige/Projects/vscode-extensions/todo-tree", 
        "path": "/Users/nige/Projects/vscode-extensions/todo-tree",
        "scheme": "file"
    },
    "name": "todo-tree",
    "index": 0  
}
```

**Comment by Gruntfuggly** [comment]
The fix I'm going to try will use the fsPath of the uri if the scheme is file, or use uri.toString() otherwise, which seems to work.

**Comment by Gruntfuggly** [comment]
Actually, I'm not sure using `"todo-tree.filtering.includedWorkspaces": ["glitchfs://*"]` works. It may look like it is working if you already have the files open, but if you close all open editors and reload the window, does it find anything?

**Comment by Gruntfuggly** [comment]
This is fixed in as much as it shouldn't search your root folder anymore. It will still find TODOs in opened files, but it won't scan the glitchfs folder.
