### ISSUE TITLE
extension stopped working: "running the contributed command: 'todo-tree.refresh' failed."

### ISSUE THREAD

**Issue by the-vampiire** [Gruntfuggly/todo-tree#316]
hey thank you for the extension it's incredibly helpful. not sure what changed but i returned to a codebase that i had used custom todo-tree labels in after a month or so. now none of the tags are picked up and when i hit the refresh button the error i get in the bottom corner toaster is:

> running the contributed command: 'todo-tree.refresh' failed.

i have tried:

- uninstall / reinstall extension
- quit vscode completely and reopen
- enable in settings `"todo-tree.general.debug": true` (no output is shown besides the toaster popup)

for the record i havent changed anything else about vscode in recent memory (no updates or new extensions added).

machine data:

> vscode

```
Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:52:45.129Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0
```

> todo-tree extension: 0.0.174, "this extension is enabled globally"

**Comment by Gruntfuggly** [comment]
Your version of vscode is quite out of date, so it maybe that there is an incompatibility. Could you open the developer console (Help -> Toggle Developer Tools) and have a look to see what errors are present?

**Comment by the-vampiire** [comment]
@Gruntfuggly brilliant that did it. didn't realize how far behind i was! i had DNS resolution for the 30+ ms servers to dead end because of all the telemetry which caused the VSC update checks to fail.

**Comment by pcprince** [comment]
I'm having this issue on version 1.46.0 of VS Code. Opening the developer console gives these errors:
`Activating extension 'Gruntfuggly.todo-tree' failed: Cannot find module 'micromatch'`
`Error: command 'todo-tree.refresh' not found`
I've tried reinstalling the extension multiple times and it doesn't work. I can't remember when the extension stopped working as previously it was fine.

**Comment by Gruntfuggly** [comment]
That's odd - it definitely looks like it's failed to install. Can you try:
1. uninstall the extension.
2. restart vscode
3. quit vscode
4. look in .vscode/extensions and check that the extension is definitely gone.
5. restart code
6. reinstall
If that does't work, can you open a terminal window and go into .vscode/extensions/gruntfuggly.todo-tree-0.0.176 and try `npm install` and see what happens?

**Comment by pcprince** [comment]
Typical. This time, reinstalling it fixed the issue. After weeks of that not working.

**Comment by Gruntfuggly** [comment]
Do you have multiple windows open? One thing I've noticed is that Code doesn't actually remove an extension until every window is closed, I guess in case one of them is still using it. It's caught me out a few times, which is why I completely quit and restart when uninstalling.
