### ISSUE TITLE
Display total TODO count in Activity Bar

### ISSUE THREAD

**Issue by jhogervorst** [Gruntfuggly/todo-tree#317]
It would be nice if the total count of TODOs could be displayed in the Activity Bar. This could be similar to the count of changed files that Source Control displays in that bar.

<img width="488" src="https://user-images.githubusercontent.com/304065/82151763-880aa180-985d-11ea-8ac8-b3728c669aa6.png">

**Comment by Gruntfuggly** [comment]
A long standing feature request! see #22
