### ISSUE TITLE
Possibility to choose which buttons to show

### ISSUE THREAD

**Issue by kanlukasz** [Gruntfuggly/todo-tree#319]
Hello,
I have one idea that may be useful.

From some time VSCode offer open search result in Editor 
![obraz](https://user-images.githubusercontent.com/30685349/82788334-8c8c1700-9e68-11ea-95e9-832dfecd5697.png)

Is it possible to run TODOs in the same way?
In the sidebar it is difficult to read all TODO if you have long text there

Eg.:
![obraz](https://user-images.githubusercontent.com/30685349/82788531-eb519080-9e68-11ea-9ca7-82d12a98a2ff.png)

**Comment by Gruntfuggly** [comment]
You can export the todo tree into a file, or you can drag the tree view into the panel at the bottom?

**Comment by kanlukasz** [comment]
Oh, I didn't know about export. This is ok

Maybe it's worth adding icon with an export option here:
![obraz](https://user-images.githubusercontent.com/30685349/82818839-a268fe80-9e9f-11ea-9536-e969d01182d4.png)

What do you think?

**Comment by Gruntfuggly** [comment]
There are quite a few buttons already so I don't want to add one by default, but I could add a configuration item for which buttons to show.

**Comment by kanlukasz** [comment]
Sounds great for me

**Comment by Gruntfuggly** [comment]
The latest version now lets you choose which buttons are shown on the titlebar. The export button is now an option. Also, the path of the exported file can be configured. Let me know if that works as expected.

**Comment by kanlukasz** [comment]
Thank you for the update.
A few things I noticed:

- If you save the export file and then try to use the export button again - an error occurs.
```
console.ts:137 [Extension Host] Unhandled Rejection:  Error: cannot open untitled:c%3A%5CUsers%5CMyUserName%5Ctodo-tree-20200617-0710.txt.
Detail: file already exists
at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6010:738

console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: cannot open untitled:c%3A%5CUsers%5CMyUserName%5Ctodo-tree-20200617-0710.txt.
Detail: file already exists
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:402
_invokeHandler @ rpcProtocol.ts:387
_receiveRequest @ rpcProtocol.ts:303
_receiveOneMessage @ rpcProtocol.ts:230
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:587
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:587
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166

console.ts:137 [Extension Host] stack trace: Error: cannot open untitled:c%3A%5CUsers%5CMyUserName%5Ctodo-tree-20200617-0710.txt.
Detail: file already exists
at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6010:738
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:402
_invokeHandler @ rpcProtocol.ts:387
_receiveRequest @ rpcProtocol.ts:303
_receiveOneMessage @ rpcProtocol.ts:230
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:587
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:587
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
log.ts:197

ERR cannot open untitled:c%3A%5CUsers%5CMyUserName%5Ctodo-tree-20200617-0710.txt.
Detail: file already exists: Error: cannot open untitled:c%3A%5CUsers%5CMyUserName%5Ctodo-tree-20200617-0710.txt.
Detail: file already exists
at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6010:738

```

- I tried to use [Predefined variables](https://code.visualstudio.com/docs/editor/variables-reference#_predefined-variables) to set the export path, such as WorkspaceFolder. It does not work at first glance

- If you set `"todo-tree.general.exportPath": "~/TODO_FILE",` and then save the export, you cannot open export again ( the same error as above occurs )

- Aside from the above:
Can we open this export only as a preview?
In the current situation, when you click Export, but you just want to view the content of the file and close the tab immediately, the "Save / Do not save" dialog box appears
If you open it often, a dialog is displayed each time - it makes it a bit difficult

**Comment by Gruntfuggly** [comment]
What OS are you using?

I don't think it's possible to open the file as a preview - unless you know of a way? I wanted to do the same thing, but nothing I tried worked.

**Comment by Gruntfuggly** [comment]
One option could be save the file automatically when created. Would that work?

**Comment by kanlukasz** [comment]
> What OS are you using?

Microsoft Windows [Version 10.0.18363.900]


>I don't think it's possible to open the file as a preview - unless you know of a way? I wanted to do the same thing, but nothing I tried worked.

I've seen something like this in the [SVG](https://marketplace.visualstudio.com/items?itemName=jock.svg) plugin, but it works with existing files, so I don't think it can help
![obraz](https://user-images.githubusercontent.com/30685349/84884889-90d7d880-b092-11ea-82af-c0ebb8802461.png)


>One option could be save the file automatically when created. Would that work?

I don't want to give hasty advice, so I have to think about it.
Maybe for now leave it as it is, and if I come up with something I will let you know

**Comment by Gruntfuggly** [comment]
OK - I'll do some testing on Windows - I'm not sure why it's an issue. I would have thought vscode should cope if you try to open a document with the same name. 😮 

I think that's a web preview - so you wouldn't be able to save it if you wanted to.

I could try adding an option to save automatically - it would probably make sense if somebody wanted to use a timestamped filename anyway.

**Comment by Gruntfuggly** [comment]
I've just uploaded a new version which does the export in a nicer way. It creates a preview file so it won't prompt to be saved. You can still save it using `File: Save As...` (`File: Save` doesn't work for some reason).

This also gets rid of the error that you were seeing. 

Let me know if it works OK.

**Comment by kanlukasz** [comment]
Sorry for no reply. This was due to a lot of work. From what I can see everything works fine now.

What I catched is the value of `NaN` while exporting
![obraz](https://user-images.githubusercontent.com/30685349/88375637-3837e180-cd9c-11ea-8b70-08d19ee8cb9a.png)

**Comment by Gruntfuggly** [comment]
OK - will check that. Looks like it's adding the '1 filter active' to the export. 🙄
