### ISSUE TITLE
Ignored color for marks superset of other marks

### ISSUE THREAD

**Issue by crystalfp** [Gruntfuggly/todo-tree#32]
I'm trying to simulate the SublimeText ToC functionality by using ToDo tree plus hierarchical marks in this way:
```
"todo-tree.tags": [
        "TODO",
        "FIXME",
        ">>>",
        ">>",
        ">"
    ],
    "todo-tree.iconColours": {
        "TODO": "magenta",
        "FIXME": "red",
        ">>>": "grey",
        ">>": "green",
        ">": "yellow"
    },
```
Before yesterday's update, the entries in the side panel where colored correctly as requested in the `iconColor` configuration. Now they are all yellow independently from the number of ">". What I'm doing wrong?

**Comment by Gruntfuggly** [comment]
I'm surprised the update caused a problem because it was something unrelated, unless you've skipped a release. It was probably the change before.

To be honest I'd not considered what would happen if your tags could contain other tags - might need to tweak the regex to cope.

**Comment by crystalfp** [comment]
1) I'm very new to Code, so I don't think have skipped an update.
2) The regex does its job egregiously. `// > bla bla` and `// >> bla bla` are recognized and the coloring does not depend on the recognition.
3) I tried to change the order of entries in the `iconColours` object but, being an object and not an array, the order is not important and in any case the result does not change.
4) If I change all instance of `>>` to `->` (that is, it is no more a superset of `>`) the coloring works again.

Hope a solution could be found. The SublimeText ToC (table of comments) plugin is the only thing that prevent me to completely switch to Code.

**Comment by crystalfp** [comment]
OK, solution found. I defined iconColours this way:
```
    "todo-tree.iconColours": {
        "TODO": "magenta",
        "FIXME": "red",
        "> ": "yellow",
        ">> ": "green",
        ">>>": "grey"
    },
```
And now the icons are correctly colored. Maybe a comment that the label could be defined with a trailing space could help. Thanks!

**Comment by Gruntfuggly** [comment]
Try the latest version - it now tries an exact match first, then a pattern match. The actual tag wasn't being stored previously as the colouring was done in an earlier change which didn't need it. Now that the tag is stored (in order to remove the comment) it can be matched properly.

Let me know if it works with your original configuration.

**Comment by crystalfp** [comment]
Very good! Thanks. Now it works correctly. You can close this issue.
