### ISSUE TITLE
Feature request: Is it possible to add option to sort the order of tags in the Tree view?

### ISSUE THREAD

**Issue by vnkavali** [Gruntfuggly/todo-tree#323]
Currently, I have tags as { "TODO",  "BUG", "FIXME", HACK", CHECK"}.

When I open the Todo Tree in the side bar, I always see CHECK first then BUG, CHECK, FIXME, HACK, TODO i.e., in alphabetic order.

Is it possible to sort based on my requirement?

**Comment by Gruntfuggly** [comment]
Which view are you using? Are you using "group by tag"?

**Comment by vnkavali** [comment]
I am using Show tag only view. But the order is alphabetic in all the other views (tree view, flat view) too.

EDIT: My tags are  { "TODO", "BUG", "FIXME", "FIX", HACK", CHECK"} and "FIX", "FIXME" are grouped under "FIXME".

**Comment by Gruntfuggly** [comment]
Can you send me a pic - for tags only view it should show them in the order they appear in the file?

**Comment by vnkavali** [comment]
Yes for each tag they are sorted with the Line number but the Tags are sorted alphabetically.

![TODO-tree](https://user-images.githubusercontent.com/58797059/83125407-743f2500-a112-11ea-8a4b-2b11c1e65242.png)

**Comment by Gruntfuggly** [comment]
Do you have `todo-tree.tree.sortTagsOnlyViewAlphabetically` enabled?

**Comment by vnkavali** [comment]
No, It is off, but when I switch it to ON, I can see the items inside the tag are sorted alphabetically.

**Comment by Gruntfuggly** [comment]
OK - I'll apply the setting to both.

**Comment by vnkavali** [comment]
What would be the order for the tags then?

based on the Tags order in the todo-tree.general.tags value?

**Comment by Gruntfuggly** [comment]
Yes

**Comment by vnkavali** [comment]
Also, In the pic, you can see the number beside TODO is 30, but the no of items are less than 30 (I have a filter(Vishnu)).
I think the issue here is that the filter is applied on the items but not used when calculating the count.

Should I post this as a new issue?

**Comment by Gruntfuggly** [comment]
Yes please

**Comment by Gruntfuggly** [comment]
I've just uploaded v0.0.197 which I think should fix the sorting. Can you let me know if it does please?

**Comment by vnkavali** [comment]
Sorry for the late confirmation. I am using v0.0.215 and the sorting is working as expected.
