### ISSUE TITLE
Documentation: suffix-less files

### ISSUE THREAD

**Issue by mcswell** [Gruntfuggly/todo-tree#325]
I was trying to figure out why tags that I put in my makefile didn't get highlighted (nor did they show up in the todo tree in the explorer).  It turns out that they show up if I check the settings box for "Todo-tree > Filtering: Include Hidden Files".  Now makefiles are not hidden files (they don't start with a dot, and they do show up in Linux 'ls' even if you don't do 'ls -a'); but they do lack a filename suffix, and I'm guessing that's why todo tree doesn't notice them by default.

I haven't tried other files that don't have a suffix, but I'm guessing they'd work the same way.

Can I suggest that either todo-tree should handle suffix-less files by default, or possibly the documentation should be changed to mention that todo-tree treats them like hidden files?

**Comment by Gruntfuggly** [comment]
Actually, it's a bug, the test to check if a file is 'hidden' (starts with a dot) isn't robust enough. The hidden files option is a slight red-herring, because ripgrep finds the file, but the extension is incorrectly hiding it.

**Comment by Gruntfuggly** [comment]
Should be fixed in the latest version - please let me know.

**Comment by mcswell** [comment]
Yes, that appears to have fixed it, thank you!  I'm closing this issue.
