### ISSUE TITLE
always showing items when 

### ISSUE THREAD

**Issue by jockrow** [Gruntfuggly/todo-tree#327]
When I open external file with //TODO elements hapend this:
1. I open "DELETE ME.js" file, todo tree refreshing list without problem:
![image](https://user-images.githubusercontent.com/30563443/83923790-8f301b80-a748-11ea-9133-310776c4d8c6.png)

2. I delete file "DELETE ME.js" from file explorer
3. todo tree doesn't refresh list, and stay this way:
![image](https://user-images.githubusercontent.com/30563443/83923883-c999b880-a748-11ea-8c27-2022ad4c1049.png)

**Comment by Gruntfuggly** [comment]
This is a limitation of vscode. Unfortunately the event which says that a file has been closed is not generated immediately - it can take up to 3 minutes for it to happen. If you find it still doesn't get removed after 3 minutes, please let me know.

**Comment by jockrow** [comment]
> This is a limitation of vscode. Unfortunately the event which says that a file has been closed is not generated immediately - it can take up to 3 minutes for it to happen. If you find it still doesn't get removed after 3 minutes, please let me know.

I did process again and I was waiting until 10 minutes, but unfortunately I saw the TODO list not refresh

**Comment by Gruntfuggly** [comment]
I've just noticed that in your screenshot, you still have the file open (even though it's been deleted from the disk). It will continue to show TODOs from open files.

**Comment by jockrow** [comment]
Ok, I tested with another editor this characteristic and result is same. 
Thanks for your time.
