### ISSUE TITLE
ignoring a list in a markdown file

### ISSUE THREAD

**Issue by goofballtech** [Gruntfuggly/todo-tree#328]
i have an example markdown file which includes a list like so:

- [ ] An uncompleted task
- [x] A completed task

~~~
- [ ] An uncompleted task
- [x] A completed task
~~~

as designed it's showing the "uncompleted" tasks in the todo tree. But they are not tasks. They are markdown examples of how to make a list. How can i ignore these specific lines without breaking the example/markdown rendering of them?

I ended up just hiding the folder in the tree. Did not know if there was a better solution to narrow down to the specific line or block of code though.

Thanks for the awesome extension! i use it all the time to make sure i remember where i was in the flow from day to day.

**Comment by Gruntfuggly** [comment]
If you haven't changed the default setting for `todo-tree.regex.regex` it should be:
`((//|#|<!--|;|/\*)\s*($TAGS)|^\s*- \[ \])`
or if you look in the JSON settings file:
`((//|#|<!--|;|/\\*)\\s*($TAGS)|^\\s*- \\[ \\])`
The second part, after the vertical bar is the part which matches markdown TODOs.
You can just remove this and it will stop matching them.
So just:
`((//|#|<!--|;|/\*)\s*($TAGS))`
That will remove all markdown todos though - if you just want to remove them for that specific file, you'll need to use the excludeGlobs.

**Comment by goofballtech** [comment]
Roger all. I'll mess with it. Right now these are the only markdown style todo's in use so i can pull them all but if i ever use them in the future ill have to change tactics. 


Thanks very much for the quick reply.

**Comment by Gruntfuggly** [comment]
No problem. If you do need more fine grained filtering and you have an idea how to do it, let me know.
