### ISSUE TITLE
FR: remove from tree labels the comment debrids

### ISSUE THREAD

**Issue by crystalfp** [Gruntfuggly/todo-tree#33]
If I use old style comments like `/* TODO my text */` they are presented in the Tree as `TODO my text */`

Is it possible to remove the final `*/` from the Tree label?

This basic requirement could be expanded by allowing removing any substring of the label. For example if I use colors to code the type of comment, maybe I could ask to remove TODO, FIXME prefixes.

**Comment by Gruntfuggly** [comment]
8-) I knew this would come up when I added the removal of the leading comments. I'll see what I can do...

**Comment by Gruntfuggly** [comment]
Latest version tidies up trailing block comments where possible. Removing the tag should probably be a configurable option.

**Comment by crystalfp** [comment]
Fantastic! Thanks

**Comment by crystalfp** [comment]
Yes, the new version correctly remove the `*/` at the end of an old-style comment. Thanks!
