### ISSUE TITLE
Feature Request: Support Rust todo!("Message") macro

### ISSUE THREAD

**Issue by paulirotta** [Gruntfuggly/todo-tree#330]
These are used in Rust code to halt operation on unimplemented features

Example:
`
todo!("Implement this feature");
`

**Comment by Gruntfuggly** [comment]
Try setting
```
"todo-tree.regex.regex": "($TAGS)!.*"
```
or if you want them in addition to the standard results
```
"todo-tree.regex.regex": "((//|#|<!--|;|/\\*|^)\\s*($TAGS)|($TAGS)!.*)"
```

**Comment by paulirotta** [comment]
Thanks! Unfortunately this will highight TODO!(“Something”) but not the Rust syntax.

        todo!("Something");


Sometimes I with I knew regex...

**Comment by Gruntfuggly** [comment]
You can either add "todo" to the list of tags (**Todo Tree: Add Tag**), or you can make the regex case insensitive with
```
"todo-tree.regex.regexCaseSensitive": false
```

**Comment by paulirotta** [comment]
Turning off case sensitivity works well. Thanks!

**Comment by thargy** [comment]
Rather than turning off case-insensitivity, and using any tag, I prefer:
```
 "todo-tree.regex.regex": "(//|#|<!--|;|/\\*|^|^\\s*(-|\\d+.))\\s*($TAGS)|(todo!)\\(.*\\)"
```

As `todo!()` is a case-sensitive macro in Rust, and other `$(TAGS)` values or `TODO!` are not valid.  Further I check for opening and closing brackets (naively, doesn't count brackets), so that `todo!` or `todo!(` don't match, but `todo!("My message")` does.

**Comment by cyqsimon** [comment]
Just sharing the regex I use:
```json5
"todo-tree.regex.regex": "((//|#|<!--|;|/\\*|^|^[ \\t]*(-|\\d+.))\\s*($TAGS)|^\\s*- \\[ \\]|(todo|unimplemented)!\\(.*\\))",
```

I got here by combining the [documented default](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree#:~:text=character%20including%20newlines.-,todo-tree.regex.regex) and the actual default (which appear to be different), then appending the two Rust macros (`todo!()` & `unimplemented!()`) to the end.

So this will cover all that the default regex covers, plus Github markdown task lists, plus the two Rust macros. See [here](https://regexr.com/67bhp) for a detailed explanation.
