### ISSUE TITLE
Need some improvements around TODO Tags and other

### ISSUE THREAD

**Issue by ManPython** [Gruntfuggly/todo-tree#332]
The intention of this issue and post is to organize some better conditions to reach some improvements around TODO Tags and other. I'm refering to this post on VSC project: https://github.com/microsoft/vscode/issues/100579
It can be inspiration to some implementation around tags as regex for customHighlight.

**Comment by Gruntfuggly** [comment]
Hi - I'm not sure I understand what this issue is? Can you say explicitly what the problem is or what feature you are asking for?

**Comment by ManPython** [comment]
The idea was to add feature
1. with functions that can add:
TODO: datetime as stamp
TODO: user as on git loged user
TODO: datetime; user as mixed

It's more like parser do indicate more definitions for TODO.
2. Next filters by username and datetime.
3. with show hide line number in code/file next to label of TODO (like in breakpoints)


BTW sometimes whole line after TODO: is not visible to fill size of row/labe of dock window

**Comment by Gruntfuggly** [comment]
1. This feels like a separate extension. Todo-tree doesn't modify files, so this would be something new.
2. I'm currently working on this, but it's difficult due to the amount of regex parsing - stay tuned.
3. You can customise the label in the tree to add the line number. If that's not what you mean, can you add a mock up or something to show it?

Can you add a screenshot of the what you mean when it doesn't show the whole line?

**Comment by ManPython** [comment]
3. Regarding this part, I was in idea of something like this:
https://code.visualstudio.com/assets/docs/editor/debugging/breakpoints.png
- the No 25

About screenshot, curently not due to many projects and commits and hard to find this in history. But it was some strange case with mixin python comment as # and js // in this same eg. #TODO: me, //some js funtion with () and str ""

**Comment by Gruntfuggly** [comment]
Unfortunately the API doesn't allow for that - the best you can do is customise the label to show the line number, e.g.
`"todo-tree.tree.labelFormat": "${tag} [${line}] ${after}"`

**Comment by Gruntfuggly** [comment]
Hi - is there anything I actually need to do for this issue? The linked issue has been closed.

**Comment by ManPython** [comment]
No. The policy of VSC developing is very very strange and don't see perspective to support some solutions here.

**Comment by Gruntfuggly** [comment]
They seem reticent to address quite a few issues which would improve the development experience, but what can you do?
