### ISSUE TITLE
Improve colour validation

### ISSUE THREAD

**Issue by martixy** [Gruntfuggly/todo-tree#338]
When you install this extension you can no longer tell what text you select in the highlited region. This is silly.

![TODO fail](https://user-images.githubusercontent.com/8262590/85987818-d7b0c100-b9f6-11ea-859d-63a6f81d7d20.png)

Sadly, losing such a core feature of text editing is not worth what this extension brings. Please fix, because it is a useful plugin, but it's gonna lose every time as long as it messes with such basic assumptions.

**Comment by Gruntfuggly** [comment]
It looks like you've configure the background colour to be black, or have used an invalid colour. Can you post your configuration so I can check?

If you need to see both selections, you have to configure the colour of the highlight to have some opacity, e.g.
```
   "todo-tree.highlights.defaultHighlight": {
        "opacity": 50
    },
```
Please see https://github.com/Gruntfuggly/todo-tree#highlighting (opacity).

**Comment by martixy** [comment]
Sorry, here is my config, with the added opacity setting:

    "todo-tree.highlights.defaultHighlight": {
        "type": "text",
        "opacity": 0,
        "textStyle": "italic",
        "background": "unset"
    }

Still the same result however.

**Comment by Gruntfuggly** [comment]
`"background": "unset"` is not a valid value for a colour. If you just remove that and keep `"opacity":0` it should stop highlighting.

**Comment by martixy** [comment]
It does not.

![Does not](https://user-images.githubusercontent.com/8262590/85991101-a1297500-b9fb-11ea-9543-ce851581fc35.png)

I just want todos to be italic, unobtrusive, nothing else.

**Comment by Gruntfuggly** [comment]
Sorry - my mistake, it's needs a colour to set the opacity on, so use
```
    "todo-tree.highlights.defaultHighlight": {
        "opacity": 0,
        "background": "#000000"
    },
```

**Comment by martixy** [comment]
This works, and preserves selection highlighting.
Thank you.

Perhaps some clearer documentation on how this works.

Like, for example, I assumed background takes CSS values, therefore tried `unset`. Color was removed, so I figured it was working, but selection was broken.

I suggest the note about opacity obscuring selection be in **very bold text**.

**Comment by Gruntfuggly** [comment]
I have added better support for validating colours in another of my extensions - I just haven't had time to add it to this one yet. I'll try and make sure it's in the next release.

**Comment by Gruntfuggly** [comment]
The latest version now has better colour validation.
