### ISSUE TITLE
searches encoded binary data in Jupyter notebook file

### ISSUE THREAD

**Issue by allefeld** [Gruntfuggly/todo-tree#340]
I have a Jupyter notebook, where apparently a Base64-encoded PNG image contains the sequence "XXX" somewhere in the data stream. This is picked up by the extension and displayed as an XXX item:
![image](https://user-images.githubusercontent.com/1738353/86285232-23708f80-bbdc-11ea-9896-d233e23806b2.png)

Here is part of the code in the file, the "XXX" appears towards the end of the last line:
```
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "output_type": "display_data",
     "data": {
      "text/plain": "<IPython.core.display.HTML object>",
      "text/html": "<div style=\"background-color:#e0e0e0;margin:0\">\n  <div>\n    <img style=\"max-width:47%;padding:10px;float:left\"\n      src=\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAREAAADYCAIAAABDZkARAAASDUlEQVR4nO3dfTjV9x/HcRW/rKvSDZaKNWlNa61bk1ihw5K6dHIzactcTXfrZqqlWFv3upFJSjcuulqiLa2WK9Uid1Gkqx1q4iJqQzc2RVp27PcpXSyTON+P8z3eXo8/ds3xPZ/vG9+n8/2iczr8888/asK8/vrrP//887vvvitwHajz+++///XXX2+++aYS9lVTU+Pj4xMaGnru3DnaX8SUlJRx48YJX6cDmlFBymy
```

The full file is available here: <https://raw.githubusercontent.com/allefeld/pytikz/master/tikz.ipynb>

**Comment by Gruntfuggly** [comment]
To be fair, that's not binary data, so I'm not surprised it's found it. The default regex has optional whitespace between the comment characters (`//` in this case) and the tags, so you could make the whitespace mandatory. 

The other option is to add that type of file to the exclude globs if you never want to search them.

**Comment by allefeld** [comment]
Ah, it only picks it up because of the preceding `//`?

I would like to find TODOs in notebooks, but only where it is in comments in input code cells. But I guess making the extension work that way would be a lot of effort?

Which setting do I have to change and how in order to make the whitespace mandatory?

**Comment by Gruntfuggly** [comment]
You'll have to update `todo-tree.regex.regex`
I would try something like:
```
((//|#|<!--|;|/\*|^)\s+($TAGS)|^\s*- \[ \])
```
I've changed the `*` to  a `+` just before $(TAGS). Or you could remove `//|` from the group at the start. It depends what files you want to search really. 

Note: If you're editing the settings in the JSON editor, the backslashes need to be doubled up, e.g.
```
"todo-tree.regex.regex": "((//|#|<!--|;|/\\*|^)\\s+($TAGS)|^\\s*- \\[ \\])"
```

**Comment by allefeld** [comment]
So the change is from `\s*` to `\s+` – at least one whitespace character?

Seems to work, great!

You could still consider making the extension work properly with notebook files, as outlined above, but for now I'm closing this issue. Thanks!

**Comment by Gruntfuggly** [comment]
> You could still consider making the extension work properly with notebook files

It's just a file search at the end of the day - there is special handling for any particular file types. What do you consider to be "working properly"?

**Comment by allefeld** [comment]
It's more complicated than that. Yes, on the face of it, a Jupyter notebook is just a JSON text file. However, if opened with a suitable program, which VS Code becomes by installing the [Python extension](https://marketplace.visualstudio.com/items?itemName=ms-python.python), this data structure is interpreted as a sequence of input and output 'cells', where input cells can be either of type 'Markdown' or 'code'. "Working properly" would mean that only input code cells are searched. Also, you would have to find a way to make the notebook editor to open at the right line inside of the right input cell, which is currently not the case.

**Comment by Gruntfuggly** [comment]
Unfortunately that's way beyond the capability of the searching aspects of the extension. It sounds like you could create a separate extension which scans notebooks - perhaps todo-tree could provide an API to allow other extensions to add to the tree.
