### ISSUE TITLE
Default`todo-tree.regex.regex` value may be wrong

### ISSUE THREAD

**Issue by munierujp** [Gruntfuggly/todo-tree#341]
Default `todo-tree.regex.regex` value:

```
((//|#|<!--|;|/\*|^)\s*($TAGS)|^\s*- \[ \])
```

[![](https://user-images.githubusercontent.com/20086673/86483589-560eb980-bd8f-11ea-9332-5485e0a89376.png)](https://jex.im/regulex/#!flags=&re=((%2F%2F%7C%23%7C%3C!--%7C%3B%7C%2F%5C*%7C%5C%5E)%5Cs*(%24TAGS)%7C%5E%5Cs*-%20%5C%5B%20%5C%5D))

Perhaps the correct value would be:

```
((//|#|<!--|;|/\*|\^)\s*($TAGS)|^\s*- \[ \])
```

[![](https://user-images.githubusercontent.com/20086673/86483654-763e7880-bd8f-11ea-9d2c-68b9db295f7a.png)](https://jex.im/regulex/#!flags=&re=((%2F%2F%7C%23%7C%3C!--%7C%3B%7C%2F%5C*%7C%5E)%5Cs*(%24TAGS)%7C%5E%5Cs*-%20%5C%5B%20%5C%5D))

(It's escaping `^` symbol)

or...:

```
(^(//|#|<!--|;|/\*)\s*($TAGS)|^\s*- \[ \])
```

[![](https://user-images.githubusercontent.com/20086673/86484226-ba7e4880-bd90-11ea-981d-bfab5da219dc.png)](https://jex.im/regulex/#!flags=&re=(%5E(%2F%2F%7C%23%7C%3C!--%7C%3B%7C%2F%5C*)%5Cs*(%24TAGS)%7C%5E%5Cs*-%20%5C%5B%20%5C%5D))

(It's using `^` as regex's metacharacter which indicates starting position)

**Comment by Gruntfuggly** [comment]
The default regex is intended to match the start of the line or the comment characters, so I think it is correct. It definitely shouldn't be escaped as it isn't intended to match a literal ^.

**Comment by munierujp** [comment]
@Gruntfuggly 

>The default regex is intended to match the start of the line or the comment characters

It seems to be different from the description in the README.

>This defines the regex used to locate TODOs. By default, it searches for tags in comments starting with //, #, ;, <!-- or /*. This should cover most languages.

Which is correct?
If the README is correct, you can use the following value.

```
(^\s*(//|#|<!--|;|/\*)\s*($TAGS)|^\s*- \[ \])
```


This works correctly like this.:

```js
const obj = {
  // TODO: fix prop name
  BUG_TRACKING: true
}
```

**Comment by munierujp** [comment]
@Gruntfuggly 

>The default regex is intended to match the start of the line or the comment characters

It seems to be different from the description in the [README](https://github.com/Gruntfuggly/todo-tree#configuration).

>This defines the regex used to locate TODOs. By default, it searches for tags in comments starting with //, #, ;, <!-- or /*.

Which is correct?
If the README is correct, you can use the following value.

```
(^\s*(//|#|<!--|;|/\*)\s*($TAGS)|^\s*- \[ \])
```

[![](https://user-images.githubusercontent.com/20086673/86567036-a8292800-bfa5-11ea-9a04-dbcc2b1f3af8.png)](https://jex.im/regulex/#!flags=&re=(%5E%5Cs*(%2F%2F%7C%23%7C%3C!--%7C%3B%7C%2F%5C*)%5Cs*(%24TAGS)%7C%5E%5Cs*-%20%5C%5B%20%5C%5D))

This works correctly like this:

![](https://user-images.githubusercontent.com/20086673/86567318-25ed3380-bfa6-11ea-8270-3e16a8f795d6.png)

**Comment by Gruntfuggly** [comment]
The README doesn't describe the entire regex, it just gives an outline of what it does. The regex already matches your two examples, so I don't understand what the issue is?

**Comment by munierujp** [comment]
@Gruntfuggly When `todo-tree.regex.regex` value is `((//|#|<!--|;|/\*|^)\s*($TAGS)|^\s*- \[ \])`, it matches three lines (include 4th line).
Because 4th line starts with spaces and tag name (`TODO`).

**Comment by Gruntfuggly** [comment]
OK - I understand now. I don't think this is necessarily wrong, it just doesn't work for this case. I would expect users would need to tweak the regex to make it work for them anyway - it is impossible to make a default that works perfectly for everybody. 

I don't really want to change the default as there are many users who do still use the default, and when I have changed it in the past it causes expected problems for people.

As long as you can configure it to work for yourself, I would prefer to leave it.

**Comment by munierujp** [comment]
@Gruntfuggly 

> I don't really want to change the default as there are many users who do still use the default, and when I have changed it in the past it causes expected problems for people.

I see.
Thank you 😎
