### ISSUE TITLE
Feature request: Settings to use ignore files

### ISSUE THREAD

**Issue by RotationMatrix** [Gruntfuggly/todo-tree#343]
Would it be possible to add settings similar to the VSCode ignore options so we don't have to repeat ignore patterns in `todo-tree.filtering.excludeGlobs`?

![default VSCode .gitignore options](https://user-images.githubusercontent.com/52428419/86919626-87241c80-c0f6-11ea-800c-aff93ec45e02.png)

**Comment by Gruntfuggly** [comment]
You shouldn't need to exclude those files - ripgrep ignores them by default.

**Comment by RotationMatrix** [comment]
Ah you're right. Looks like my `.gitignore` files were not picked up because they are not in the workspace root. Works fine when they are in the root.

Thanks for pointing that out! This is an awesome extension! 😃
