### ISSUE TITLE
Duplication on Windows when opening a TODO file

### ISSUE THREAD

**Issue by cobey** [Gruntfuggly/todo-tree#344]
# Info

This does not occur on macOS 10.15.x when tested earlier today, though it does easily repro on Windows. No combination of settings seems to resolve the issue

# Steps to Reproduce

1. Create a new todo file (tasks.md or some such)
2. Add a few todos
3. Ensure that the path is listed in todo-tree.general.rootFolder
4. Click on the tree icon
5. Select a todo

# Expected Results

The file which contains the todo should open, and the tree view should not list the file twice

# Actual Results

The file is listed twice

# Video
![dupebug](https://user-images.githubusercontent.com/8754258/86972862-78eef400-c128-11ea-83aa-ef4f0445d8d3.gif)

# Config Details

```json
     //Changing this setting does not seem to impact the behavior described
    "todo-tree.tree.trackFile": false,
    "todo-tree.general.rootFolder": "C:\\Users\\cobey\\Desktop\\Data\\Notes\\Blah",
     //Changing this setting does not seem to impact the behavior described
    "todo-tree.general.enableFileWatcher": false,
    "todo-tree.regex.regex": "((//|#|-|<!--|;|/\\*|^)\\s*($TAGS)|^\\s*- \\[ \\])",
```

# Version Info

TODO Tree Version: v0.0.177

VS Code Version

Version: 1.46.1 (user setup)
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by Gruntfuggly** [comment]
I think you're seeing it twice because one starts with `C:` and the other starts with `c:`. Can you try changing the folder in `todo-tree.general.rootFolder` to use a lower case `c` and see what happens?

**Comment by Gruntfuggly** [comment]
I might need to add some special handling for windows drive letters if code is returning the file paths with lowercase letters.

**Comment by Gruntfuggly** [comment]
BTW, Thanks for the comprehensive issue - makes a change from some that get raised! 😄

**Comment by cobey** [comment]
That fixed it! Thanks for the quick response! 

Apropos of the bug report comment, I really think GitHub should have a bug filing template or several. Along with links to open source tools for making GIFs etc... Pinging @nat 😄

**Comment by cobey** [comment]
I guess I should not have presumed you wanted this closed, in case you want to handle VS Code tolower()ing everything :)

**Comment by Gruntfuggly** [comment]
To be honest, it's probably quite low on the list of priorities so I'm happy to close it at the moment. I'm happy if somebody wants to reopen it.

**Comment by Gruntfuggly** [comment]
Wow - thank you for the donation! Much appreciated. 👍

**Comment by cobey** [comment]
Actually I am going to request this be reopened and I will fix it. I need something to do in quarantine :)

**Comment by Gruntfuggly** [comment]
Go for it, please excuse my code though - some of it has got a bit messy over time. 😬

**Comment by cobey** [comment]
Fixed (in this specific instance) in https://github.com/Gruntfuggly/todo-tree/pull/345

**Comment by Gruntfuggly** [comment]
Fix has now been merged into the latest version - sorry it took so long!
