### ISSUE TITLE
Support COBOL

### ISSUE THREAD

**Issue by GitMensch** [Gruntfuggly/todo-tree#347]
Currently only possible via manual regex, see the [documentation on this in a COBOL extension](https://github.com/spgennard/vscode_cobol#todo-tree-by-gruntfuggly).
It would definitely be nicer to have support for it out-of-the-box.

**Comment by Gruntfuggly** [comment]
Hi - I no longer update the default regex because it was becoming too complex and making changes would cause people using it to have unexpected problems.

I'll add the Cobol regex to the wiki though.
