### ISSUE TITLE
Please minify the extension

### ISSUE THREAD

**Issue by mgholam** [Gruntfuggly/todo-tree#348]
Please minify the extension when publishing and remove the `node_modules` folder

**Comment by Gruntfuggly** [comment]
Hi - latest version is now webpacked.

**Comment by mgholam** [comment]
Great!
PS : you can also remove the `extension.js.map` file to save another 1mb

**Comment by Gruntfuggly** [comment]
Sure. I'm new to the whole bundling/webpack thing, so there may be other improvements too.
