### ISSUE TITLE
Feature Request: list tags in message

### ISSUE THREAD

**Issue by liangjiancang** [Gruntfuggly/todo-tree#350]
ability to set log level for every tag.

```JSON
{
  "TODO": "info",
  "FIXME": "error",
}
```

**Comment by Gruntfuggly** [comment]
Hi - do you mean that you want it to generate diagnostics for the problems view?

**Comment by liangjiancang** [comment]
> Hi - do you mean that you want it to generate diagnostics for the problems view?

Yes, please implement it

**Comment by Gruntfuggly** [comment]
I started looking into this before, but there is quite a lot of work involved. I'm also aware of the issue of extensions not cleaning up their diagnostics properly, so I would need to make sure it is fully working.

I'll see if I can get it working when I get some spare time.

**Comment by Gruntfuggly** [comment]
Sorry, but I don't think I will get time to implement this. I am also worried that it may cause too many issues. It would need to track the TODO's to determine when they are removed in order to tidy the diagnostics and that would be quite a major change.
