### ISSUE TITLE
The Expand Tree icon disappears when you change the View Mode

### ISSUE THREAD

**Issue by kanlukasz** [Gruntfuggly/todo-tree#351]
#### One little thing about UX / UI:

![double](https://user-images.githubusercontent.com/30685349/88376633-18a1b880-cd9e-11ea-96b3-baaea5a8300a.gif)

The expand tree icon ![obraz](https://user-images.githubusercontent.com/30685349/88376131-1c810b00-cd9d-11ea-98c4-ab65691c7abc.png) disappears when you change the view mode.

From what I understand this is due to the fact that there is nothing to expand in the tree view
But maybe it would be a good idea to disable this icon (and make dimmed) in that view mode instead of hiding it? What do you think?

Proposition:
![obraz](https://user-images.githubusercontent.com/30685349/88376512-db3d2b00-cd9d-11ea-86ed-95c2babb976c.png)

**Comment by Gruntfuggly** [comment]
Is that possible with the API? I tried giving the command a when clause, but it didn't seem to work.

**Comment by Gruntfuggly** [comment]
Should now be fixed in the latest version.
