### ISSUE TITLE
Problem with highlights in HTML file

### ISSUE THREAD

**Issue by belauzas** [Gruntfuggly/todo-tree#353]
I have added `"!"` to `"todo-tree.general.tags"`;

And then `"todo-tree.general.tagGroups": { "FIXME": ["FIXME","FIXIT", "FIX", "!"] },`

And because of that, all highlights in a HTML files gutter displays as "FIXME" type, even tho it's `<!-- TODO: some task -->` or  `<!-- BUG: some task -->`

If it's possible, it should ignore "!", as it's part of HTML tag.

**Comment by Gruntfuggly** [comment]
Can you post all your todo-tree settings and a screenshot showing what you see.

When I tried it, it does what I expected.

**Comment by belauzas** [comment]
![image](https://user-images.githubusercontent.com/7464725/89038866-c63a3c00-d349-11ea-8e27-92ec986c60f3.png)

```json
"todo-tree.tree.showScanModeButton": false,
"todo-tree.general.revealBehaviour": "highlight todo",
"todo-tree.tree.labelFormat": "${after}",
"todo-tree.general.tags": [
    "BUG",
    "HACK",
    "FIXME",
    "TODO",
    "FIXIT",
    "FIX",
    "?",
    "!",
    "TRY"
],
"todo-tree.general.tagGroups": {
    "FIXME": ["FIXME","FIXIT", "FIX", "!"]
},
"todo-tree.highlights.customHighlight": {
    "TODO": {
        "icon": "check",
        "type": "line",
        "iconColor": "green",
        "foreground": "green",
        "gutterIcon": false
    },
    "FIXME": {
        "foreground": "black",
        "iconColour": "#07f",
        "gutterIcon": true,
        "gutterColor": "orange"
    },
    "BUG": {
        "icon": "bug",
        "foreground": "red",
        "iconColour": "red",
        "gutterIcon": true,
        "rulerColour": "blue"
    },
    "?": {
        "icon": "question",
        "foreground": "#f93",
        "iconColour": "#f93",
        "gutterIcon": true
    },
    "TRY": {
        "icon": "beaker",
        "type": "line",
        "iconColor": "violet",
        "foreground": "violet"
    }
},
```

**Comment by Gruntfuggly** [comment]
You have put "!" in the tag groups settings, so it considers it to be the same as a FIXME. 

If you take it out, does it work as expected?

**Comment by belauzas** [comment]
![image](https://user-images.githubusercontent.com/7464725/89040115-e834be00-d34b-11ea-844b-dabffe6f18f0.png)

```json
    "todo-tree.general.tags": [
        "BUG",
        "HACK",
        "FIXME",
        "TODO",
        "FIXIT",
        "FIX",
        "?",
        "TRY",
        "!"
    ],
    "todo-tree.general.tagGroups": {
        "FIXME": ["FIXME","FIXIT", "FIX"]
    },
```

Removing from tag group doesn't fix it 🤔

**Comment by Gruntfuggly** [comment]
I don't understand - by adding "!" to the tags, it will find them as I would expect. What do you think it should be doing instead?

**Comment by Gruntfuggly** [comment]
It might be that the default regex matches `<!--`. You could remove that 
e.g. `  "todo-tree.regex.regex": "((//|#|;|/\\*|^)\\s*($TAGS)|^\\s*- \\[ \\])",`
and then it will only find something like

```
// ! BUG: some task
```

but not 

```
<!-- TODO: some task -->
```

**Comment by belauzas** [comment]
Well, it all works fine except for HTML comment tag  which should be skipped.
e.g.
in JS I would like to write something like
```
// ! some task
```
just like in HTML
```
<!-- ! some task -->
```

**Comment by Gruntfuggly** [comment]
You would need to play around with the regex to get it to work. Single character tags are difficult - how can it know when a character is what you expect or not? 

At the moment the regex allows for optional space around the tags. You could force it to have space before and after, e.g.
```
"todo-tree.regex.regex": "((//|#|;|/\\*|^)\\s+($TAGS)\\s+|^\\s*- \\[ \\])",
```

**Comment by belauzas** [comment]
Adding space before symbol " !" works fine 👍

But in general, I believe, there should be two scripts:
- first, that excludes things;
- second, that finds what to highlight.

**Comment by Gruntfuggly** [comment]
I don't know how that could work. The extension uses ripgrep with a single regular expression to find the todos. The highlights are done using the same regular expression otherwise it might find different things, but there is nothing to 'exclude'.

**Comment by belauzas** [comment]
What is interesting, that after pasting `"todo-tree.regex.regex": "((//|#|<!--|;|/\\*)\\s*($TAGS)|^\\s*- \\[ \\])",` (from https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree) into settings.js and restarting VSCode, things started working fine 🤔👍
