### ISSUE TITLE
"hideFromStatusBar": true removes counts from Tree entries

### ISSUE THREAD

**Issue by mlao-pdx** [Gruntfuggly/todo-tree#356]
Focus is on Bookmarks, which is a tagGroup, notice how the count goes from 0 to 1 based on status bar visibility.

Hidden:
![image](https://user-images.githubusercontent.com/21014310/90917713-47f51680-e398-11ea-93da-1d3f55ce2de0.png)

Visible:
![image](https://user-images.githubusercontent.com/21014310/90917741-54796f00-e398-11ea-8dbe-efd86fcc3488.png)

This feels counter to the intuitively expected behavior based on the setting name. I expected it to only affect the status bar, which it does just fine. But I also lose the tag counts in the tree.

My goal is to prevent crowding the status bar with the large number of tagGroups I maintain, and have only to-dos show up on the status bar by hiding all others.

**Comment by Gruntfuggly** [comment]
Should now be working in the latest version.

**Comment by mlao-pdx** [comment]
> Should now be working in the latest version.

Apologies for delay. Working as advertised. Thank you!
