### ISSUE TITLE
Enable "Ignore Git Submodule" cause unresponsive extension host

### ISSUE THREAD

**Issue by boenshao** [Gruntfuggly/todo-tree#358]
When the "Ignore Git Submodule" option is enabled.
![image](https://user-images.githubusercontent.com/65853605/90974375-25f8c100-e55d-11ea-8a0e-526ba45c7211.png)

The extension host would hang for seconds during a todo scan.
![image](https://user-images.githubusercontent.com/65853605/90974416-9273c000-e55d-11ea-88ea-c7baa17db33c.png)

All other settings are stock, this happened on two of my machine.

**Comment by boenshao** [comment]
> Hi - sorry it's been such a long time since updating this. Are you still seeing this problem with the latest version?

Negative, with vscode 1.52.1 and the latest extension, no slow down and no warning message from extension host.

**Comment by Gruntfuggly** [comment]
OK great. I'll close this then. Thanks for letting me know.
