### ISSUE TITLE
Add TODO highlighting in jsx

### ISSUE THREAD

**Issue by justweb1** [Gruntfuggly/todo-tree#359]
This is an example of a TODO inside a NextJS/React project. In this case the TODO does not get highlighted properly. It does show in the tree though.

```javascript
      <AppBar position="static">
        <Toolbar>
          {/* TODO Add logo here */}
```

**Comment by Gruntfuggly** [comment]
Have you changed any of the settings?

**Comment by justweb1** [comment]
I have changed very few settings. Mainly added additional tags. The file extension is .js.

**Comment by justweb1** [comment]
I figured it out... by default under customHighlight TODO settings were blank. I added a foreground and type and it is now working.
```
        "TODO": {
            "foreground": "#f9e64f",
            "type": "text-and-comment"
        },
```

**Comment by Gruntfuggly** [comment]
Try adding 'rulerColour' too.

**Comment by justweb1** [comment]
Here are my settings...

```
    "todo-tree.highlights.customHighlight": {

        "TODO": {
            "foreground": "#f9e64f",
            "type": "text-and-comment"
        },
        "FIXME": {
            "foreground": "red",
            "type": "text-and-comment"
        },
        "ASSIGN": {
            "foreground": "#832561",
            "type": "text-and-comment"
        }
    },
    "todo-tree.highlights.defaultHighlight": {
        "foreground": "green",
        "type": "none"
    },
    "todo-tree.general.tags": [
        "TODO",
        "FIXME",
        "ASSIGN"
    ],
    "todo-tree.filtering.excludeGlobs": [
        "**/node_modules/*"
    ],
    "todo-tree.tree.showScanModeButton": false,
```

**Comment by Gruntfuggly** [comment]
Ah OK - you've got 'type' as 'none' in the default highlight. Makes sense now.

**Comment by justweb1** [comment]
Let me uninstall and reinstall and see if everything works.

**Comment by Gruntfuggly** [comment]
It sounds like it is working as expected though? What is the issue you are seeing?

**Comment by justweb1** [comment]
I think it had gotten messed up when I had 2 different highlighting extensions. I just deleted all the settings uninstalled and reinstalled. We'll go from there. I'm guessing I messed it up. Thanks for the quick and helpful replies.

**Comment by Gruntfuggly** [comment]
No problem - glad you got it working. 🙂

**Comment by justweb1** [comment]
Still on the comments that have opening and closing tags... you should have highlighting end with the closing tag when using the types that include comments.

**Comment by Gruntfuggly** [comment]
Do you mean just highlighting this bit and nothing after it?

```javascript
/* TODO Add logo here */
```

That would be nice, but the whole thing is based on a single regex to keep it fast. It would need to start parsing the code to do it reliably and there are loads of edge cases. There's only so much you can do with regexes!

Does your theme not highlight the comments in some way?

**Comment by justweb1** [comment]
Yeah my theme highlights it with // and /** */ multi-line but not /* */ single line... Your plugin does not recognize the multiline comments like below.

```javascript
/**
 * TODO Add multiline support
 */
```

**Comment by Gruntfuggly** [comment]
You need to update the regex to support multiline comments - have a look at the wiki for some examples.
https://github.com/Gruntfuggly/todo-tree/wiki/Configuration-Examples

**Comment by justweb1** [comment]
Also, kinda weird but not your problem... None of the themes I have installed seem to recognize `/* TODO */` for highlighting.

Thanks again.

**Comment by Gruntfuggly** [comment]
I'm using 'Dark+ (default dark)' which seems to work:
![image](https://user-images.githubusercontent.com/376658/91204798-7e19f980-e6fc-11ea-9dba-2a3446c2993d.png)

**Comment by justweb1** [comment]
@Gruntfuggly I'm using Dark+ and the theme doesn't highlight that in Yellow like the other ones. Your extension highlights it fine.
