### ISSUE TITLE
Cannot find language definition for jsx-file

### ISSUE THREAD

**Issue by evpozdniakov** [Gruntfuggly/todo-tree#36]
Keep having this issue for jsx-files.

![image](https://user-images.githubusercontent.com/1109345/41417315-f183cfba-6fba-11e8-8c48-1cb11d2cceef.png)

Please help to solve. TY!

**Comment by Raydir** [comment]
same here for "flat text files" for which i have a specific language definition myself.
Perhaps its a relevant info: my files encoded cp850.

The problem did not exists bout 5 hours ago should therefore be one of the last commits.

Thanx - i love your extension 🥇

**Comment by Gruntfuggly** [comment]
Yep - I forgot to check the last update for languages it doesn't know about. Sorry! 
New version should be availabe now...

**Comment by Raydir** [comment]
Yo, works like a bomb thanx! 👍
