### ISSUE TITLE
Ignore certain files and/or tags 

### ISSUE THREAD

**Issue by majkinetor** [Gruntfuggly/todo-tree#360]
We have _hide this folder_ now, and it helped quite a lot in hiding irrelevant stuff from repository (such sa todos in vendor stuff), however, I still am not able to hide stuff I am not interested about (owned by other developers for example).

It would be great to have an option to hide specific file and/or todo.

**Comment by Gruntfuggly** [comment]
Hiding individual files should be doable - it would just work in the same way as the folders - it could generate a glob from the filename. 

Individual TODO's would be more tricky as I would have to store them somewhere which could become an issue - if you add a line before the TODO it would move, so how would it be able to track them?

**Comment by majkinetor** [comment]
You would track them by file and content rather then line. This would however ignore all the TODOs with the same content in that file (which is probably OK too, why would you ignore only 1 instance of specific content).

However, that is way less important then hiding files, I included it more for completeness then for real need although there are some TODOs that I need and would really like to ignore on specific projects.

**Comment by Gruntfuggly** [comment]
I can add it, but the one reservation I have is that there would be no simple way to unhide - it would have to just be a reset like the folder filter.

I've just realised there is a massive hole in my implementation of the folder filters - I'll revisit this and find a nicer way to reset, and include the file filters at the same time.

**Comment by majkinetor** [comment]
> I can add it, but the one reservation I have is that there would be no simple way to unhide

Yeah, I was just looking into modifying my current state and notice I can only reset everything which is less then ideal. So perhaps Filter can be redesigned to be similar to CTRL + P (search for files):

![image](https://user-images.githubusercontent.com/85767/91285677-d0572b00-e78d-11ea-83fe-7b31729b010b.png)

**Comment by Gruntfuggly** [comment]
I've just published a new version which has options to hide individual files and also adds a 'remove filter' dialog which allows you to chose individual filters to remove.

**Comment by majkinetor** [comment]
Small nitpick: it still says _remove folder filter_ although it also handles files.

**Comment by Gruntfuggly** [comment]
Yes, I realised that as I was putting it in, but naming it 'Remove folder/file filter' seemed a bit clumsy. I kind of classify them all as folder filters, as opposed to the global filter, so I think it probably works OK.

I'm open to suggestions for alternatives...

**Comment by majkinetor** [comment]
Just _filter_ :)

**Comment by Gruntfuggly** [comment]
The trouble is filter could mean the global filter - if you use the filter button from the title bar (funnel icon) you'll see the menu ends up with:
```
Clear Filter
Hide This Folder
Only Show This Folder
Only Show This Folder And Subfolders
Remove Folder Filter
Reset Folder Filter
```

I should probably rename `Clear Filter` to `Clear Global Filter` for consistency.

**Comment by Gruntfuggly** [comment]
Workspace Filter is a bit too analagous to Global Filter.

**Comment by majkinetor** [comment]
I am not sure what is Global Filter. Searched the docs and the settings, there is nothing that mentions global. :)

**Comment by Gruntfuggly** [comment]
It's the filter available from the title bar:
![image](https://user-images.githubusercontent.com/376658/97593546-b211e380-19f9-11eb-8f32-d86e1858a770.png)
It's not called global filter in the docs, because it was the only filter originally - the folder filters were a later addition.

**Comment by majkinetor** [comment]
LOL

Isn't it called _Filter tree_ like the tooltip shows ? This is more like local filter then global... what is exactly global in it? Is it the moment in which you filter workspace, open files so 'global' is like it doesn't belong to one workspace/project ?

BTW, nice site :)

**Comment by Gruntfuggly** [comment]
I only call it 'global' because it affects the whole tree - you could have multiple workspaces, in which case it applies the filter to all of them. I could rename it to "Tree Filter"?

**Comment by majkinetor** [comment]
Sure, make it happen, revert the words :) Lets make a sense out of it, naming is important.

![image](https://user-images.githubusercontent.com/85767/97595242-ce1a8280-1a03-11eb-8f54-a545b314dfab.png)

**Comment by Gruntfuggly** [comment]
I don't want to change the tooltip - that is describing the 'action' taken when you press the button, but I can change the name in the menu to Clear Tree Filter. Then, I could rename "Remove Folder Filter" to just "Remove Filter" and an option in the remove dialog to remove the Tree Filter too?

**Comment by majkinetor** [comment]
Sounds awesome 🥇

**Comment by Gruntfuggly** [comment]
Latest version now has a friendly remove filter dialog and the text should be a bit clearer in the context menu.
