### ISSUE TITLE
"regex parse error" on startup of VSCode

### ISSUE THREAD

**Issue by jens-duttke** [Gruntfuggly/todo-tree#362]
On startup of VSCode I always get this error message:
![todo-tree-error](https://user-images.githubusercontent.com/4883142/92128361-98da2580-ee02-11ea-85b8-e7c9e641ad02.PNG)

Despite the message, the extension seems to work fine - `@todo` comments are highlighted as expected.

The `todo-tree` related items in my `settings.json`:
```json
"todo-tree.filtering.useBuiltInExcludes": "search excludes",
"todo-tree.general.tags": [
	"@todo"
],
"todo-tree.tree.labelFormat": "${after}",
"todo-tree.regex.regex": "((//|#|<!--|/\\*|^\\s*\\*)\\s*($TAGS))|(\"\\?(\\\\.|[^\"])+\")",
```

I'm using
VSCode: 1.48.2
Todo Tree: 0.0.178

**Comment by Gruntfuggly** [comment]
It looks like something is not escaped properly in the regex. It might be highlighting them in the editor correctly but not finding them in the file search, because there is an extra level of escaping required to do the ripgrep search. Does the tree appear in the sidebar?

What type of todo were you trying to match?

**Comment by Gruntfuggly** [comment]
I think you may just need to escape the backslashes which as escaping the double quotes. E.g.
`"todo-tree.regex.regex": "((//|#|<!--|/\\*|^\\s*\\*)\\s*($TAGS))|(\\\"\\?(\\\\.|[^\\\"])+\\\")"`

**Comment by jens-duttke** [comment]
In the tree, only one file is shown.

The escaping for the double-quote is only done because it's in a double-quoted string. In a regular expression itself, it's shouldn't be required to escape double-quotes.

Anyhow, after changing it to your string, I get an error something like "todo-tree: The system cannot find the given path." (the original german message is "todo-tree: Das System kann den angegeben Pfad nicht finden.").
But there is no information which path it can't match.

What I'm trying to match:
```
// @todo
/* @todo
# @todo
<!-- @todo
"?Some text"
"?Some \"text\""
```

**Comment by Gruntfuggly** [comment]
It's not the double quotes that you're escaping - it's the backslash that is being used to escape the double quotes. It's because the regex is passed to a command line process. 

Can you enable the debug channel (`todo-tree.general.debug: true`), then go to the Output View and select Todo Tree from the drop down and see what is generated?

**Comment by jens-duttke** [comment]
I've activated the debugging now, and see the source of the problem.

With my regexp:
```
Command: "c:\Users\j_duttke\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg.exe" --no-messages --vimgrep -H --column --line-number --color never --max-columns=1000 --no-config  -e "((//|#|<!--|/\*|^\s*\*)\s*(@todo))|("\?(\\.|[^"])+")" "p:\HexEd.it"
regex parse error:
    ((//|#|<!--|/\*|^\s*\*)\s*(@todo))|(\?(\\.
                                          ^
error: unclosed group
Der Befehl "["])+")"" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
```

With your regexp:
```
Command: "c:\Users\j_duttke\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg.exe" --no-messages --vimgrep -H --column --line-number --color never --max-columns=1000 --no-config  -e "((//|#|<!--|/\*|^\s*\*)\s*(@todo))|(\"\?(\\.|[^\"])+\")" "p:\HexEd.it"
Das System kann den angegebenen Pfad nicht finden.
```

But even this command produces the same error:
```
echo "(\"\?(\\.|[^\"])"
Das System kann den angegebenen Pfad nicht finden.
```
Here the command line seems to get confused with the double quotes and the `|` and tries to interprete something there as file path.

**Comment by jens-duttke** [comment]
I've found the source of the problem now.
Even this command doesn't work:
```
echo "\"-|-\"-"
```
The problem here is the `|` which needs to be escaped using `^|`. (See https://stackoverflow.com/questions/1200235/how-to-pass-a-quoted-pipe-character-to-cmd-exe)
I've added that to your regexp, and now it works.

But it can't be the idea, that I need to implement escaping hacks for the underlying command line into the regexp in the settings.json, right?

This behaviour of the command line would also produce an error if your regexp contains `^|` - which would be then replaced by `|`, so that the `^` get lost. In that case you would have to replace that by `^^^|`

**Comment by jens-duttke** [comment]
Since `rg` supports a patternfile, wouldn't it be easier to pass the pattern using a temporary file, instead of messing around with escaping in the command line?

**Comment by Gruntfuggly** [comment]
I'm not sure the `|` is really the the problem - the default regex has contained it almost since day one.

Can you point me to the documentation for ripgrep's pattern file? I'm open to making a change if it improves things, although I have plenty of other issues to fix, and I'm struggling to find the time at the moment...

**Comment by jens-duttke** [comment]
> I'm not sure the `|` is really the the problem - the default regex has contained it almost since day one.

The `|` itself is not the problem, also not the `\"`, but the combination of both (like it's done in my regexp) is the problem (and maybe other character combinations as well):

```
P:\>echo "12|3"
"12|3"

P:\>echo "1"23"
"1"23"

P:\>echo "1"2|3"
"3"" is not recognized as an internal or external command,
operable program or batch file.

P:\>echo "1\"2|3"
"3"" is not recognized as an internal or external command,
operable program or batch file.

P:\>echo "1\"2^|3"
"1\"2|3"

P:\>echo "1"2^|3"
"1"2|3"
```

> Can you point me to the documentation for ripgrep's pattern file?

Simply start the program with the parameter `--help`, it will show the help:
```
    -f, --file <PATTERNFILE>...
            Search for patterns from the given file, with one pattern per line. When this
            flag is used multiple times or in combination with the -e/--regexp flag,
            then all patterns provided are searched. Empty pattern lines will match all
            input lines, and the newline is not counted as part of the pattern.

            A line is printed if and only if it matches at least one of the patterns.
```



I've just tested it, by replacing `-e "PATTERN"` by my original pattern without superfluous escaping, and it works just fine:

The original call (for reference):
```
"c:\Users\jens_duttke\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg.exe" --no-messages --vimgrep -H --column --line-number --color never --max-columns=1000 --no-config  -e "((//|#|<!--|/\*|^\s*\*)\s*(@todo))|(\"\?(\\.^|[^\"])+\")" "p:\HexEd.it"
```

Using a pattern file:
```
"c:\Users\jens_duttke\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg.exe" --no-messages --vimgrep -H --column --line-number --color never --max-columns=1000 --no-config  -f "p:\pattern.txt" "p:\HexEd.it"
```

The content of `p:\pattern.txt`, without superfluous escaping:
```
((//|#|<!--|/\*|^\s*\*)\s*(@todo))|("\?(\\.|[^"])+")
```

For creating a temporary file, you could just use https://github.com/sindresorhus/tempfile
After `rg.exe` is done, don't forget to delete the temporary file (`fs.unlink`).

**Comment by Gruntfuggly** [comment]
Thanks - I'll make that an option.

**Comment by Gruntfuggly** [comment]
The latest version now uses a pattern file. Hopefully that should reduce some of the escaping insanity!

**Comment by jens-duttke** [comment]
For me it works fine now. Thanks!
