### ISSUE TITLE
[feature] TODO count badge in panel

### ISSUE THREAD

**Issue by alumni** [Gruntfuggly/todo-tree#363]
At the moment we can see the TODO count in the statusbar by setting `todo-tree.general.statusBar`.

I usually disable most statusbar widgets because I don't want to put too much information there, I prefer to see in the statusbar only the information that cannot be found anywhere else.

TODO Tree is very similar to vscode's built-in "Problems" view. It would be nice if we could also see the number of all TODOs in a badge on the panel icon (if in sidebar) or next to the panel text (if at the bottom) - this would be similar to how the Problems panel (Source Control too) shows the count.

**Comment by Gruntfuggly** [comment]
This is a long standing feature request (#22), but unfortunately there is no API to do it.
