### ISSUE TITLE
Installing via terminal with deprecation warnings

### ISSUE THREAD

**Issue by scandeiro** [Gruntfuggly/todo-tree#364]
# My setup

**OS:** Ubuntu 20.04.1 LTS x86_64
**Kernel:** 5.4.0-45-generic
**Terminal:** GNOME Terminal 3.36.2 using VTE 0.60.3 +BIDI +GNUTLS +ICU +SYSTEMD
**IDE:** Visual Studio Code Insiders 1.49.0-insider e4256dd1a02339bb1d56647ecd9134bf38bc7c03 x64

# Expected behavior

The extension should be installed, regardless of which source, without alerts or warnings.

# Actual behavior

The extension when installed, via terminal, outputs the following:

`Installing extensions...`

`Installing extension 'gruntfuggly.todo-tree' v0.0.178...`

`(node:93858) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`

`Extension 'gruntfuggly.todo-tree' v0.0.178 was successfully installed.`

# Steps to reproduce

1. Open the terminal
2. Type `code-insiders --install-extension Gruntfuggly.todo-tree`

**Comment by Gruntfuggly** [comment]
Hi - todo-tree doesn't use Buffer anywhere itself. I get this warning when I install any extension this way, so I think it is something to do with Code itself.

**Comment by scandeiro** [comment]
Hey, dude. Okay then. I saw an issue addressed to VS Code's repository about this thing and yes, it seems to be a problem inside code's core package. Thank you for you time and attention, anyway! ;)
