### ISSUE TITLE
VSCode language specific settings

### ISSUE THREAD

**Issue by Anoesj** [Gruntfuggly/todo-tree#365]
Hey, thanks for Todo Tree, using it all the time!

It would be nice if, at least, the `todo-tree.regex.regex` setting can be configured per-language: https://code.visualstudio.com/docs/getstarted/settings#_language-specific-editor-settings

It doesn't work right now. Thank you!

**Comment by Gruntfuggly** [comment]
Hi - the problem with this is I don't think the extension API allows access to language specific settings. I've done it in another extension, but it's a hack and generates warnings in your settings files as far as I remember.

**Comment by Anoesj** [comment]
Ah okay, too bad! Thanks anyway :)

**Comment by tobiasdiez** [comment]
This would indeed be a nice feature.

To enable language-specific settings, one needs to set `"scope": "language-overridable"` , see "scope" under https://code.visualstudio.com/api/references/contribution-points#Configuration-property-schema. Could this feature request be reopened please?

**Comment by Gruntfuggly** [comment]
@tobiasdiez Unfortunately it doesn't make any sense to make the regex language overridable because ripgrep does a file search - it has to be able to find things in any type of file. It could be changed for searching within editors, but that could result in inconsistent behaviour.

I will have another think about it though.

**Comment by freMea** [comment]
Doesn’t extension API allow to only search in comments instead of parsing the whole file ? I’m sure there is an issue on VSCode repo on that if it doesn’t.

**Comment by Gruntfuggly** [comment]
The extension is primarily designed to search files - searching only comments would be a big change and I don't think the API does support it - it would need a language parser to understand the comments, and at that point it might as well be part of a language based extension.

**Comment by freMea** [comment]
There are workarounds like exposed in this [issue](https://github.com/microsoft/vscode/issues/580).

**Comment by Gruntfuggly** [comment]
I'm closing this as it's not something that fits with the way the extension is currently designed.
