### ISSUE TITLE
The case for alphabetical sort in the TODO tree

### ISSUE THREAD

**Issue by mihaibrana** [Gruntfuggly/todo-tree#366]
I'm using your wonderful extension for a very large project :). We have about 100 TODOs, with about 5 generated / week. Of course, we're aware we should be cutting them instead of growing the list, but for now, it is what it is :D.

The issue with this many TODOs is that we tend to lose track of what is important to prune first. So far, we suffix all TODO statements with a number. But since the TODOs are sorted by line number, this is of little use.

Therefore, if you would somehow allow us to sort the tree alphabetically, you would open a new way of using the extension :).

**Comment by Gruntfuggly** [comment]
Probably not really what you want, but if you change the view to 'tags only', then you can sort by alphabetical order.

**Comment by mihaibrana** [comment]
Hey, thanks for answering! :). Actually, I don't really understand from the documentation how to use tags. The tags are "todo" and "fixme"? Then I guess I could add a "TODO1" tag to prioritize?

**Comment by Gruntfuggly** [comment]
You can configure any tags you want - it's just what it looks for to identify a 'todo', so yes, you could priorities them like that.

The 'tags only' view basically gets rid of the tree structure and just shows a list of the TODO's - they're still clickable, and the tooltip will tell you where they are, but it might be a more suitable view for your purposes.

**Comment by mihaibrana** [comment]
Yes, because when we go after removing some of our TODOs, we don't care about the files where the tags are, but the priority ;). 

Going to close this because creating custom tags is a more elegant solution to the problem. Thank you!

But don't worry, I'll be back with another feature request :D. Let me just think carefully how to formulate it :D
