### ISSUE TITLE
Drag and drop between tags

### ISSUE THREAD

**Issue by mihaibrana** [Gruntfuggly/todo-tree#367]
Since we can create custom tags, this could be used to sort TODOs by priority (i.e. TODO1, TODO2, TODO3). This is supported by your extension just fine, and we can customize the way these tags look.

But it would sure be nice if one could drag items from one tag to another, for example to change a high prio TODO to a lower prio TODO. Or to change a TODO into a FIXMENOWANDYOUGETICECREAM ;)

**Comment by Gruntfuggly** [comment]
That would be nice, but there is no drag and drop support in the API for tree views, unfortunately. I think it has been requested though, so it may happen in the future.

**Comment by Gruntfuggly** [comment]
Hi - even if drag and drop support was added to tree views, this would require the extension to start modifying files, which it was never intended to do, so I don't think this will ever be implemented. Sorry.
