### ISSUE TITLE
todo-tree doesn't work: [Gruntfuggly.todo-tree]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api Gruntfuggly.todo-tree

### ISSUE THREAD

**Issue by manolosolalinde** [Gruntfuggly/todo-tree#368]
I'm getting this error in version v0.0.178.

[Gruntfuggly.todo-tree]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api Gruntfuggly.todo-tree

I'm working on javascript.

**Comment by Gruntfuggly** [comment]
What version of vscode are you running?

**Comment by manolosolalinde** [comment]
![image](https://user-images.githubusercontent.com/34798311/93133475-44a62f80-f6a5-11ea-9915-c9dc4f544665.png)

**Comment by manolosolalinde** [comment]
I have just updated vscode to the latest commit (same version) and it is working back again. There is some issue with that previous commit.

**Comment by Gruntfuggly** [comment]
OK - I was just about to say It works fine for me with insiders (2020-09-12) on OSX. What does "(user setup)" mean?

**Comment by manolosolalinde** [comment]
No idea...

**Comment by Gruntfuggly** [comment]
Is it OK to close this now?

**Comment by manolosolalinde** [comment]
Sure... sorry. Thanks for the help!

**Comment by Gruntfuggly** [comment]
No problem.
