### ISSUE TITLE
Delete from the todo tree

### ISSUE THREAD

**Issue by NegassaB** [Gruntfuggly/todo-tree#369]
Abiitlity to delete a completed todo directly from the todo tree would be awesome.

**Comment by Gruntfuggly** [comment]
Hi - currently the extension doesn't modify files in any way, and I would prefer to keep it that way.

This sounds like a good idea for another extension though - I have also thought that it would be nice to have a way of inserting todo's using a template.

It might be possible to write an add-on extension which uses todo-tree as an API.

**Comment by NegassaB** [comment]
Hi -- thanks for the reply.
I'm not versed at all in js or vscode's extension development to do it my self but I will certain be a user of that.
What kind of template are you thinking of? Cause your extension already provides the 'TODO, FIXME, HACK' etc templates.

**Comment by Gruntfuggly** [comment]
I tend to insert todo's in this format:

`// TODO(gruntfuggly@email.com) Fix this`

It would be handy to just type the 'Fix this' and insert it. Or it could be a snippet - I should have a look at that too.

**Comment by NegassaB** [comment]
Hello, sorry for the late reply.
Please do and thanks for this awesome work.
