### ISSUE TITLE
Fails to find todos and throws error

### ISSUE THREAD

**Issue by diminutivesloop** [Gruntfuggly/todo-tree#37]
Recently Todo Tree has been failing to find any Todo's in my project and displays the following error message: "todo-tree: Cannot read property 'length' of undefined". My project definitely has several todo's but even if it didn't the extension shouldn't be throwing errors as a result.

Extension version: 0.0.62
VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 6.1.7601

**Comment by Gruntfuggly** [comment]
Hi - could you do me a favour and open the developer tools and find out what line number the error is coming from?

**Comment by Rittoune** [comment]
Hi - I have same error too : 
<img width="474" alt="screen shot 2018-06-14 at 4 03 15 pm" src="https://user-images.githubusercontent.com/18166426/41435335-7c36f520-6fec-11e8-9ceb-99b05f902bcd.png">

**Comment by Gruntfuggly** [comment]
It's because I didn't check what happens when languages don't have multiline comments. Sorry for the inconvenience! I've just uploaded a version that should fix the problem.
