### ISSUE TITLE
Add Reminders Feature

### ISSUE THREAD

**Issue by HunterFrisby** [Gruntfuggly/todo-tree#370]
Would be nice if we could set follow up reminders, in which we'll get notifications in VSCode.

### Examples:
//TODO: Work out the bugs. REMINDER: 09-24-20 9am
//REMINDER: 09-24-20 9am
//REMINDER: Tomorrow Morning

**Comment by Gruntfuggly** [comment]
It's a nice idea, but I don't think it's really part of this extension. It would be a good idea for a separate extension though.

There are several 'reminder' extensions already - it might be easy to suggest extending one of those?

Alternatively, I wrote another extension that uses google calendar and generated notification reminders in vscode:
https://github.com/Gruntfuggly/calendar
. I could extend that to automatically generate reminders like you've suggested.

**Comment by HunterFrisby** [comment]
Ok, that makes sense. The calendar extension seems great and probably a better solution to extend instead. Do you want me to go ahead and add the request to the calendar extension repository?

**Comment by Gruntfuggly** [comment]
Yes please.
