### ISSUE TITLE
Todo Tree: Invalid colour settings: defaultHighlight.rulerColour (#fa08)

### ISSUE THREAD

**Issue by wenfangdu** [Gruntfuggly/todo-tree#371]
This error popped up after auto-upgrading from v.0.0180 to v0.0181.
My config:
```json
  "todo-tree.highlights.defaultHighlight": {
    "background": "#fa0",
    "foreground": "#fff",
    "icon": "alert",
    "iconColour": "#fa0",
    "opacity": "0.5",
    "rulerColour": "#fa08",
    "rulerLane": "full",
    "type": "tag"
  },
```
Since v.0.0180 doesn't highlight `TODOs` for me, I rolled back to v0.0.178, now everything works well.

**Comment by Gruntfuggly** [comment]
It doesn't think `"rulerColour": "#fa08"` is valid, however you can specify the alpha in the colour like you have done - if that was your intention?

It should work OK if you ignore the warning - I'll fix it for the next update though (later today hopefully).

**Comment by Gruntfuggly** [comment]
Please could you post the rest of you todo-tree configuration so I can see why the highlighting is not working.

**Comment by Gruntfuggly** [comment]
Please can you try the latest version and let me know if the problem still exists?

**Comment by wenfangdu** [comment]
Hi, it's fixed now, thanks! Here's my full config:
```json
{
  "todo-tree.filtering.excludeGlobs": ["**/*.txt"],
  "todo-tree.filtering.useBuiltInExcludes": "file and search excludes",
  "todo-tree.general.tags": ["TODO", "WFTODO", "FIXME", "WFFIXME"],
  "todo-tree.highlights.defaultHighlight": {
    "background": "#fa0",
    "foreground": "#fff",
    "icon": "alert",
    "iconColour": "#fa0",
    "opacity": "0.5",
    "rulerColour": "#fa08",
    "rulerLane": "full",
    "type": "tag"
  },
  "todo-tree.regex.regexCaseSensitive": false,
  "todo-tree.tree.grouped": true,
  "todo-tree.tree.showInExplorer": false,
  "todo-tree.tree.tagsOnly": true
}
```
