### ISSUE TITLE
Using rgba() for color values

### ISSUE THREAD

**Issue by kankaristo** [Gruntfuggly/todo-tree#372]
I've been using rgba() values for todo-tree colors for a while now, but todo-tree has started to complain that the values are invalid.

I'm getting a warning message:
```
Todo Tree: Invalid colour settings: customHighlight.FIXME.foreground (rgba(239, 88, 139, 1.0)), customHighlight.TODO.foreground (rgba(195, 135, 0, 1.0)), customHighlight.TEST.foreground (rgba(102, 72, 77, 1.0)), customHighlight.HACK.foreground (rgba(239, 88, 139, 0.5))
```

My config (the part that gives errors):
```json
"todo-tree.highlights.customHighlight": {
    "TODO": {
        "icon": "check",
        "foreground": "rgba(195, 135, 0, 1.0)"
    },
    "FIXME": {
        "icon": "flame",
        "foreground": "rgba(239, 88, 139, 1.0)"
    },
    "TEST": {
        "icon": "beaker",
        "foreground": "rgba(102, 72, 77, 1.0)"
    },
    "HACK": {
        "icon": "bug",
        "foreground": "rgba(239, 88, 139, 0.5)"
    }
},
```

Despite the warning, the values still seem to work okay. 
It appears that the opacity only affects the icon, and nothing else, but the color value seems to work everywhere.

Should I be using something else instead of rgba(), or should I not be getting a warning?

**Comment by Gruntfuggly** [comment]
Did that work? Wow - I didn't know that was supported. I added some validation in the last update because if invalid definitions where used it just failed silently and ended up black.

Hex codes should work, including the alpha, which should get rid of the warning.

I'll make a change to allow rgb and rgba definitions too.

**Comment by mbomb007** [comment]
I'm getting warnings too, but I'm using the color names:

> Todo Tree: Invalid colour settings: customHighlight.FIXME.iconColour (orange), customHighlight.@FIXME.iconColour (orange)

```json
    "todo-tree.highlights.customHighlight": {
        "FIXME": {
            "icon": "flame",
            "iconColour": "orange",
            "background": "white",
            "foreground": "red",
            "fontWeight": "bold"
        },
    }
```

**Comment by Gruntfuggly** [comment]
That's because 'orange' isn't (wasn't) one of the supported colours. Originally there were only 7 or 8 supported colours, because the icons were pre-coloured, and they were chosen to work with dark and light themes.

You can use #FF8000 to get rid of the warning for now.

I'll update it to allow all the HTML/CSS named colours because they should all work these days.  The original set of valid colours should probably be removed.

**Comment by Gruntfuggly** [comment]
Should now work properly in the latest version.

**Comment by muuvmuuv** [comment]
Is it really implemented? Because with this setting I am getting the "Invalid colour setting..." message:

```json
  "todo-tree.highlights.defaultHighlight": {
    "type": "whole-line",
    "icon": "check-circle",
    "background": "rgba(10,165,152,0.05)",
    "foreground": "rgba(10,165,152,1)"
  },
```

**Comment by mbomb007** [comment]
> Is it really implemented? Because with this setting I am getting the "Invalid colour setting..." message:
> 
> ```json
>   "todo-tree.highlights.defaultHighlight": {
>     "type": "whole-line",
>     "icon": "check-circle",
>     "background": "rgba(10,165,152,0.05)",
>     "foreground": "rgba(10,165,152,1)"
>   },
> ```

It works for me using your settings, though those settings aren't great if you want to see the comment, because your foreground and background are the same color.

**Comment by Gruntfuggly** [comment]
I'm not seeing any invalid settings messages using the settings you've posted.

However, I think the default "opacity" setting is overwriting the value in the rgba.
```
  "todo-tree.highlights.defaultHighlight": {
    "type": "whole-line",
    "icon": "check-circle",
    "opacity": "5",
    "background": "rgba(10,165,152,0.05)",
    "foreground": "rgba(10,165,152,1)"
  },
```

I'll fix it to ignore the opacity if it's not defined.

**Comment by muuvmuuv** [comment]
@mbomb007 it's not the same, see the alpha value, that is the part where it is ignoring the value.
@Gruntfuggly ohh, good catch didn't tried that

**Comment by Gruntfuggly** [comment]
I've just uploaded version 0.0.197 which should ignore the opacity setting if it's not set.

BTW, I like your colour scheme!

**Comment by muuvmuuv** [comment]
Thanks! ^^ its GitHub Dark (or Light, [depending on my location sunset/sunrise](https://marketplace.visualstudio.com/items?itemName=muuvmuuv.vscode-sundial)) with a few adjustments
