### ISSUE TITLE
Colour no longer accepts theme colour

### ISSUE THREAD

**Issue by JP-Ellis** [Gruntfuggly/todo-tree#373]
In the latest couple of release, my configuration has stopped working as it appears I can no longer use theme colours in the `foreground` colour.  My configuration is:

```
  "todo-tree.highlights.customHighlight": {
    "BUG": {
      "foreground": "editorError.background",
      "gutterIcon": true,
      "icon": "bug",
      "iconColour": "#f48771"
    },
    "DEBUG": {
      "foreground": "editorHint.foreground",
      "gutterIcon": true,
      "icon": "info",
      "iconColour": "#eeeeeeb3"
    },
    "FIX": {
      "foreground": "editorWarning.foreground",
      "gutterIcon": true,
      "icon": "flame",
      "iconColour": "#cca700"
    },
    "TODO": {
      "foreground": "editorInfo.foreground",
      "gutterIcon": true,
      "icon": "tasklist",
      "iconColour": "#75beff"
    }
  },
```

In many ways, this is similar to #274, though at the time that issue was restricted to the `iconColour` property, whereas now it appears all colours have the same issue.

**Comment by Gruntfuggly** [comment]
"editorError.background" isn't a valid theme colour. You config works for me if I change it to something else.

**Comment by JP-Ellis** [comment]
Oh, my bad.  It didn't produce an error before but I guess then it wasn't working at the time and was silently failing?  Thanks anyway!
