### ISSUE TITLE
FR: Support "when" clauses when using built in excludes.

### ISSUE THREAD

**Issue by tongjieme** [Gruntfuggly/todo-tree#378]
lets say we have this settings.
```json
"files.exclude": {
        "**/*.js": {
            "when": "$(basename).ts"
        },
        "**/*.map": {
            "when": "$(basename).map"
        },
        "**/node_modules": true
    },
```

![image](https://user-images.githubusercontent.com/1511418/97080702-f08d5400-162f-11eb-92a8-c1d5f4cd9d7b.png)

We expect to ignore js files when search tags.

![Snipaste_2020-10-24_19-32-49](https://user-images.githubusercontent.com/1511418/97080677-bae86b00-162f-11eb-84e5-ae5736cb24af.jpg)

**Comment by Gruntfuggly** [comment]
Sorry, but when clauses are not supported for the built in excludes. Unfortunately, it is not currently possible due to the way the extension works.

It would need some new functionality to ignore the files once the list has been searched.

I'll change this to a feature request.

**Comment by Gruntfuggly** [comment]
Hi - I've looked into this and unfortunately it will require too much extra processing to make it work. Unfortunately VSCode doesn't expose the file exclude functionality via the API, so I would basically have to re-implement it again.

It would also need to perform the search every time the active file changes which could have an impact on performance.

Sorry - I'll add a note to the README.md to say that when clauses are not supported.
