### ISSUE TITLE
Can the comment close string be removed from tree?

### ISSUE THREAD

**Issue by crystalfp** [Gruntfuggly/todo-tree#379]
I confusingly remember that there was a way to remove the comment close string from the tree. Something related to `todo-tree.tree.labelFormat`.
That is: `/* TODO Something */` should be visualized in the tree as: `<ICON> TODO Something` and not as `<ICON> TODO Something */`. Similarly for HTML comments with `-->`.
Really it is a very low priority feature request if my memory is wrong.
I'm using `todo-tree v0.0.183`
Thanks!
mario

**Comment by Gruntfuggly** [comment]
It should remove them automatically, depending on the file type.

With the default labelFormat, In a javascript file, I get:
![image](https://user-images.githubusercontent.com/376658/97082645-2bc55e00-1603-11eb-93e9-0c170706ab8d.png)
![image](https://user-images.githubusercontent.com/376658/97082653-37b12000-1603-11eb-8eaa-4d83c6a0d627.png)

**Comment by crystalfp** [comment]
What I forgot to mention is that the file is in Markdown (extension `.md`).
Here is the result
![image](https://user-images.githubusercontent.com/865866/97098889-7b973a00-1682-11eb-9251-f372c8ed542b.png)

when the file contains:
![image](https://user-images.githubusercontent.com/865866/97098916-ad100580-1682-11eb-900b-2c15fd52c07e.png)

`labelFormat` is the default.
Thanks for looking!
mario

**Comment by Gruntfuggly** [comment]
I've just published a new version which overrides markdown comment detection with HTML comments, so this should now work as you expect.

**Comment by crystalfp** [comment]
It works! Thanks!
