### ISSUE TITLE
Multi-line CSS comment doesn't work

### ISSUE THREAD

**Issue by wheelhot** [Gruntfuggly/todo-tree#38]
I'm familiar with JS Regex, but since the plugin uses Rust Regex, I'm not sure how to fix this

**File Type:** .css

**Example:**
```CSS
/* THIS WORKS */
/* TODO: */
/* FIXME: */

/* THIS DOESN'T WORK */
/*
TODO: 
FIXME: 
*/
```

**Comment by Gruntfuggly** [comment]
There's no support for multi-line comments at the moment as it's not supported by ripgrep:

> ripgrep doesn't have multiline search. (Will happen as an opt-in feature.)
> In other words, if you like fancy regexes or multiline search, then ripgrep may not quite meet your ? needs (yet).

**Comment by wheelhot** [comment]
Awesome! I just tried it and it works!

```CSS
/*
TODO:
FIXME:
*/
```
