### ISSUE TITLE
how to exclude other users todo's in todo tree?

### ISSUE THREAD

**Issue by fotisK69** [Gruntfuggly/todo-tree#381]
Hi,

I am working in a project (using also git) and other users using the same files and may add their to dos!
How can I exclude or hide/show when ever I need them?

Thanks in adv.

**Comment by Gruntfuggly** [comment]
Do you have a standard way of formatting the todos? 
e.g.
`// TODO (gruntfuggly@mail.com) Do something`

**Comment by fotisK69** [comment]
Usually:
// TODO (userId) - text

**Comment by Gruntfuggly** [comment]
OK, in that case your best bet is to modify the regex so that it only finds TODOs with your user id, e.g. something like
`(//)\s*($TAGS)\s*\(userId\)`
Obviously replace "userId" with your user ID.

That's the simplest regex that should work.

**Comment by fotisK69** [comment]
Nice, but i had to use it in this way:
`((//|#|<!--|;|/\*|^)\s*($TAGS)|^\s*\(userId\)- \[ \])`
to be effective!

Thanks again

**Comment by Gruntfuggly** [comment]
Yes, as I said, that was the simplest - if you want to match other stuff it's just a case of modifying the regex. 

Are you happy for me to close this now?
