### ISSUE TITLE
Enhancement: modify default regex

### ISSUE THREAD

**Issue by sogerc1** [Gruntfuggly/todo-tree#382]
I have these comments in my code:

`//////////////////////////////////////// BUGGY DEVICE HANDLING START`

`//////////////////////////////////////// BUGGY DEVICE HANDLING STOP`

They appear rather weirdly because BUG is blacked out, GY is not and in the tree the comment says "GY DEVICE HANDLING ..."
Of course I could correct the regex for myself by adding a word boundary but I think it would make sense to modify the default regex too to avoid such weird situations. So the regex looks like this:
`((//|#|<!--|;|/\*|^)\s*($TAGS)\b|^\s*- \[ \])`

**Comment by Gruntfuggly** [comment]
I try not to make any changes to the default regex anymore because it causes problems for existing users who are still using the default.

Adding the word boundary is a good idea though, and I can't see any real downsides, so I'll update it in the next release.

**Comment by Gruntfuggly** [comment]
HI - sorry, but I'm going to have to back out this change because it breaks the regex when tags end with non-word characters.

I should have followed my own rules! 🙄

**Comment by sogerc1** [comment]
Hehe, okay. Well, I would've never thought someone would put a non-word character into a tag.

**Comment by Gruntfuggly** [comment]
Yeah, I agee- I would have the characters in a group in the regex, but lots of people have asked to have tags like `TODO!`.

**Comment by Gruntfuggly** [comment]
Are you happy for me to close this?

**Comment by sogerc1** [comment]
Yes, I can add the \b for myself, so I have no objections, I just thought this would be something everyone would benefit from.

**Comment by AnrDaemon** [comment]
> I can add the \\b for myself,

I did that myself a while ago to specifically differentiate `FIX` from `FIXME` and `BUG` from `BUGFIX`.
