### ISSUE TITLE
Doubt about a configuration

### ISSUE THREAD

**Issue by alexguidi** [Gruntfuggly/todo-tree#383]
Hi,

Does anyone know if it's possible to show the numbers of TODOs pending in the activity bar as we have for control version (see the picture below)?

![image](https://user-images.githubusercontent.com/7308633/98269458-a8eabe80-1f85-11eb-94c5-75f6a9d148ca.png)

**Comment by Gruntfuggly** [comment]
It's a long standing feature request: https://github.com/Gruntfuggly/todo-tree/issues/22

**Comment by alexguidi** [comment]
Thanks a lot @Gruntfuggly

**Comment by Gruntfuggly** [comment]
As soon as it's available via the API, I'll add it.
