### ISSUE TITLE
Find Todos in Markdown Cells

### ISSUE THREAD

**Issue by brunovollmer** [Gruntfuggly/todo-tree#384]
Hey everybody,

really like this project and would like to contribute. My idea was to add the functionality to also find Todos in Markdown cells of Jupyter notebooks. Two questions I have regarding this at the moment:

1. Is this a functionality that is wanted by the community or is there a reason why not to add it?
2. If wanted, could somebody point me in the right direction where to start with this? 

I'm new to contributing to open source but I'm motivated to learn.

Kind regards,
Bruno

**Comment by Gruntfuggly** [comment]
What is the syntax? You shouldn't need to add any functionality as long as the notebooks are stored in readable files. Sorry - I don't know anything about them.

**Comment by brunovollmer** [comment]
Okay after some investing I found the problem. I did not add # or // before the TODO so it as not detected in the Markdown cell.
Thanks for the fast answer.

Anyways are there some open problems a beginner could help with?

**Comment by Gruntfuggly** [comment]
Well you're welcome to look at any of the open issues - I don't think any of them are particularly easy to fix though.

**Comment by Gruntfuggly** [comment]
I'm not sure my code will be that easy to understand either! 😐
