### ISSUE TITLE
What the list of all supported octicons?

### ISSUE THREAD

**Issue by danikgan** [Gruntfuggly/todo-tree#385]
For instance, octicon "check" works just fine, but "check-circle" or "check-circle-filled" do not work. And there are many other that are not supported. No problems with codices though.

I even installed octicons using `npm install @primer/octicons`. Why not all are supported?

**Comment by Gruntfuggly** [comment]
It's currently limited to octicons 8.5.0. I hadn't noticed that they'd moved the package, so I'll update them to 11.0.0.
