### ISSUE TITLE
0.0.187 version's searching function is not working.

### ISSUE THREAD

**Issue by LighghtEeloo** [Gruntfuggly/todo-tree#386]
[Bug] 0.0.187 version's searching function is not working
- Platform: Win10 Local and WSL.
- VScode Build: 1.51.0
- Problematic version: 0.0.187 (working well on 0.0.186)
- Phenomenon observed:
> When "todo-tree.general.tags" is set by any value, the whole "scan mode" is not working; 
> When "todo-tree.general.tags" is unset, the default scan mode is working. e.g., "TODO" is found.

**Comment by Gruntfuggly** [comment]
Could you post examples of what you set it to? Could you also post your regex setting? In fact all your todo tree settings would probably be useful.

**Comment by LighghtEeloo** [comment]
Sure. See this below:

> todo-tree settings: 
```json
    "todo-tree.general.tags": [
        "FIXME!",
        "TEST!",
        "TODO!",
        "BUG!",
        "FIXIT:",
        "FixMe:",
        "Fixme:",
        "Test:",
        "Todo:",
        "Bug:",
        "FIXME:",
        "TEST:",
        "TODO:",
        "BUG:",
    ],
    "todo-tree.highlights.defaultHighlight": {
        "gutterIcon": true
    },
    "todo-tree.highlights.customHighlight": {
        "TODO!": {
            "foreground": "#fff",
            "background": "#ffbd2a",
            "iconColour": "#ffbd2a"
        },
        "FIXME!": {
            "foreground": "#fff",
            "background": "#f06292",
            "icon": "flame",
            "iconColour": "#f06292"
        },
        "BUG!": {
            "foreground": "#fff",
            "background": "#f06292",
            "icon": "bug",
            "iconColour": "#f06292"
        },
        "TEST!": {
            "foreground": "#fff",
            "background": "#6699ff",
            "icon": "code",
            "iconColour": "#6699ff"
        }
    },
    "todo-tree.general.statusBar": "total",
    "todo-tree.general.tagGroups": {
        "FIXME!": [
            "FIXME:",
            "FIXIT:",
            "FixMe:",
            "Fixme:"
        ],
        "TEST!": [
            "TEST:",
            "Test:"
        ],
        "TODO!": [
            "TODO:",
            "Todo:"
        ],
        "BUG!": [
            "BUG:",
            "Bug:"
        ]
    },
    "todo-tree.tree.showScanModeButton": false,
```

**Comment by LighghtEeloo** [comment]
Also, I tried to temporarily disable everything except for the "todo-tree.general.tags", which still couldn't work.
But as said, by reversing it to everything but "todo-tree.general.tags", the default tags are working.

Hope this helps. :-)

**Comment by Gruntfuggly** [comment]
I think it's because you have '!' at the end of some of your tags. 

For now, you can remove `\b` from the regex, i.e. in the settings.json, change 
```
    "todo-tree.regex.regex": "((//|#|<!--|;|/\\*|^)\\s*($TAGS)\\b|^\\s*- \\[ \\])"
```
to
```
    "todo-tree.regex.regex": "((//|#|<!--|;|/\\*|^)\\s*($TAGS)|^\\s*- \\[ \\])"
```

I think the '!' is negating the word boundary (`\b`) - it probably should escape the tags - I'll look into it.

**Comment by Gruntfuggly** [comment]
I usually resist changing the default regex, precisely because of these sorts of problems. This time I couldn't see a problem - looks like I was wrong. 😞

**Comment by LighghtEeloo** [comment]
I see. The problem seems to be solved for now. Thank you!
And I DO agree that regex is a serious headache. 😢

**Comment by Gruntfuggly** [comment]
My rule of thumb is that regular expressions are almost never the right solution to your problem. 😁

**Comment by Gruntfuggly** [comment]
I've just pushed a new version which reverts the word boundary change to the regex, which should mean you can just use the default again

**Comment by LighghtEeloo** [comment]
Just checked it out. It works just fine. My gratitude. 😄
