### ISSUE TITLE
BUG: some settings do not work

### ISSUE THREAD

**Issue by danikgan** [Gruntfuggly/todo-tree#387]
First of all, thanks for the previous quick response and fix -- much appreciated!:)

Secondly, there's another issue with ToDo Tree -- CSS tags in JSON don't work. For instance, `"textDecoration": "purple"`,  `"borderRadius": 10,` and `"opacity": 50,` have no effect on the highlights. 

Lastly, although a separate issue, `"todo-tree.general.tagGroups": {` doesn't work. It just doesn't do anything 🤷🏼‍♂️

**Comment by Gruntfuggly** [comment]
There is no general support for CSS tags - you need to use the settings as described in the README.md (https://github.com/Gruntfuggly/todo-tree#highlighting)

Please can you post your todo-tree settings so I can see what you have configured?

**Comment by danikgan** [comment]
Alright, so you're not using CSS.

I have the following setting:
<img width="413" alt="CleanShot 2020-11-13 at 20 05 41@2x" src="https://user-images.githubusercontent.com/16155742/99111107-cc4be400-25eb-11eb-9856-ad1fa3aa3461.png">

And this is the result I am getting:
<img width="236" alt="CleanShot 2020-11-13 at 20 06 12@2x" src="https://user-images.githubusercontent.com/16155742/99111112-ceae3e00-25eb-11eb-8223-e802a677f38b.png">

As you can see, both opacity and borderRadius do not work. 

And in this case:
<img width="488" alt="CleanShot 2020-11-13 at 20 08 05@2x" src="https://user-images.githubusercontent.com/16155742/99111232-06b58100-25ec-11eb-98fa-65133271388f.png">
`FIX something` does not work but `FIXME` works as expected.

**Comment by Gruntfuggly** [comment]
You need "10px" for the borderRadius.
The opacity only applies when you specify a hex colour - I should make that clearer in the README.md.
You need to include "FIX" in the tags list to make the groups work - grouping only works with defined tags. Just add "FIX" and "FIXIT" and it should work.

**Comment by danikgan** [comment]
Alright! I've got my two issues fixed, but I am still not getting the desired opacity. Here's the setting (it does exactly nothing):
<img width="355" alt="CleanShot 2020-11-15 at 23 21 02@2x" src="https://user-images.githubusercontent.com/16155742/99198492-453c6e80-2799-11eb-884e-c351ef142e95.png">

**Comment by Gruntfuggly** [comment]
It can only apply the opacity to RGB colours, so instead of "white", try "#ff0000", or you can just use "#ff000080" and not bother with the opacity setting.
