### ISSUE TITLE
[SUGGESTION] Padding left/right for tag

### ISSUE THREAD

**Issue by mcunha98** [Gruntfuggly/todo-tree#389]
I did some tests , my goal is format the tag with spaces/padding on left/right of tag (to see the text clear after the background color).

But the properties to custom on json file cannot do what I want.
Example:
![image](https://user-images.githubusercontent.com/6831010/98950865-4b4ff800-24d8-11eb-8acf-a3a9be07ea3c.png)

The settings:
```
 "BUG": {
            "icon": "bug",
            "type": "tag",
            "foreground": "white",
            "background": "red",
            "iconColour": "red",
            "borderRadius" : "10px", //just test
            "padding" : "10px",  //just test
            "fontWeight" : "bold",
        },

```
OK, I know we don't have a padding parameter, my suggestion is support padding parameters (left/right) to have something like GITHUB:
![image](https://user-images.githubusercontent.com/6831010/98951027-7df9f080-24d8-11eb-8cc5-4014395c0f9d.png)

**Comment by Gruntfuggly** [comment]
Unfortunately this isn't possible - its limited to what the vscode API provides for highlights. 

The only thing you could potentially do is include spaces around the tags and include them, e.g.
```
 // TODO : ...
```
and then set the tags to " TODO ", " FIXME ", etc.

**Comment by mcunha98** [comment]
What a shame...
Thanks again

**Comment by Gruntfuggly** [comment]
If the API is updated to allow it at any point, I will definitely add it because I would like to be able to do it too. 😄
