### ISSUE TITLE
Not working on windows + markdown files

### ISSUE THREAD

**Issue by muichkine** [Gruntfuggly/todo-tree#39]
Straight out of the box:

![image](https://user-images.githubusercontent.com/2428966/42126676-a223f228-7c8b-11e8-9f0b-fa85be4ab918.png)

**Comment by Gruntfuggly** [comment]
It won't pick up TODO on it's own - for markdown it finds `- [ ]`. Or it will also find `# TODO`

You could modify the regex to 
`((//|#|<!--|;|/\\*|^)\\s*($TAGS)|^\\s*- \\[ \\])` 
which will then match TODO at the start of the line

**Comment by muichkine** [comment]
OK got it. Thanks. :)

**Comment by Gruntfuggly** [comment]
Is TODO on it's own a normal thing in markdown? If it is I could add a note in the README.md.

**Comment by Gruntfuggly** [comment]
I could update the default regex - it's seems reasonable to allow the tags to start the line.

**Comment by muichkine** [comment]
Seems reasonable.
Or you introduce a system to differentiate code file formats from text.
I suppose .txt or .html are the same

**Comment by Gruntfuggly** [comment]
Unfortunately to make it as quick as possible, it doesn't do anything clever when searching - it would find C++ style comments in html files, for example. 8-)

**Comment by Gruntfuggly** [comment]
Latest version now has start of line in the regex as default.

**Comment by muichkine** [comment]
Saw that. Awesome. :) Thanks for the tool.
