### ISSUE TITLE
[SUGGESTION] Auto create / batch create the github issue from TODO Tree list

### ISSUE THREAD

**Issue by mcunha98** [Gruntfuggly/todo-tree#390]
Is boring work fast with TODO Tree but need to click on each item and create a ISSUE on github for tracking.
![image](https://user-images.githubusercontent.com/6831010/99147737-166fac80-2662-11eb-83eb-ea7e83f8db4f.png)

I must to click on every item and create manually an ISSUE 
![image](https://user-images.githubusercontent.com/6831010/99147749-2edfc700-2662-11eb-877a-c0ee011d179a.png)
After TODO tree do his job...I need to:
![image](https://user-images.githubusercontent.com/6831010/99147796-82521500-2662-11eb-809a-b0b84e24803e.png)

My suggestion, if is possible to create a checkbox/multiple selection view from todo tree list , and I select the items to create a github ISSUE directly based on extension github.vscode-pull-request-github

Or something that I can sync the TODO tree list with github issues directly

**Comment by Gruntfuggly** [comment]
You can export the tree - `Todo Tree: Export Tree` will create a single file with the contents of the tree.

What extension are you using to create the github issues?

**Comment by mcunha98** [comment]
> You can export the tree - `Todo Tree: Export Tree` will create a single file with the contents of the tree.
> 
> What extension are you using to create the github issues?

Using this one:
https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github

The export not will be the best, because the code when I create an Issue my code automatically gain the issue reference, something like 
`//TODO: resolve this`
will be:
`//TODO: #412 resolve this`

The 2 extensions are amazing 😄 but each work in a way, the best is if you give the power of TODO tree for Git extesion

**Comment by Gruntfuggly** [comment]
Hmm - I can't get it to show the 'Create Github Issue' hover? Do I need some other configuration?

**Comment by mcunha98** [comment]
Hmmm, basically only it.
In my case I just connect the project with a git repository and the extension works fine

**Comment by Gruntfuggly** [comment]
I'm sorry - I can't figure out how to make the create issue extension work from the code. Could you explain the process in steps? Nothing I try gives me the option to create an issue from the TODO.

**Comment by mcunha98** [comment]
https://www.loom.com/share/e88439bbdf204289b36dc949790c7618

**Comment by mcunha98** [comment]
![todotree](https://user-images.githubusercontent.com/6831010/99530245-d3724980-297f-11eb-814b-430d4d1e2d49.gif)
Probably the problem is need to setup a git's repository on project to able the actions.
Check if you need more details and tell me, in this record you'll see that I use the extended version of issue editor, but on simple version you only hit ctrl+enter to create an issue with the same title of your tag content (todo/fixme) and without assign, tags or body

**Comment by kanlukasz** [comment]
Don't you think this is a bit out of scope?
To-do lists have nothing to do with github.
We should to keep very precise direction in feature development. Just my opinion

**Comment by mcunha98** [comment]
@kanlukasz , I believe not, if I can mix the features between both (TODO and GIT) in a singular extension, why not ?

**Comment by Gruntfuggly** [comment]
Sorry, but I am unlikely to have the time to implement this - it would be a major change, which I think probably should be a separate extension.
