### ISSUE TITLE
`CTRL + Shift + D 'should only be deleted console.log (`CTRL + Shift + D ' 应该只删除 console.log)

### ISSUE THREAD

**Issue by zhedream** [Gruntfuggly/todo-tree#391]
v0.0.188 - 2020-11-10
window10

我想保留 `console.warn` ,但是也被删除了
I want to keep it` console.warn `, but it was also deleted

而且提示的是`xx console.logs deleted`
And the prompt is ` 91 console.logs  deleted`

**Comment by Gruntfuggly** [comment]
This extension has nothing to do with console logs? Have you raised this issue in the right repo?

**Comment by Gruntfuggly** [comment]
Do you have any further information? If not, I'm going to close this as I don't think it has anything to do with todo-tree.
