### ISSUE TITLE
LC_ALL: cannot change locale

### ISSUE THREAD

**Issue by Bad3r** [Gruntfuggly/todo-tree#392]
Hi,
After Installing the plug in in VS code i get the following error:
```
todo-tree: /bin/sh: warning: setlocale: LC_ALL: cannot change locale (en-US)
```
The system I am using is Arch Linux:
```
Linux arch 5.9.8-arch1-1
```
I am not sure why is it trying to set the local language also `LC_ALL` is only supposed to be used for testing and trouble shooting based on the [Arch Wiki ](https://wiki.archlinux.org/index.php/Locale#LC_ALL:_troubleshooting) 
> LC_ALL is the only LC_* variable which cannot be set in locale.conf files: it is meant to be used only for testing or troubleshooting purposes, for example in /etc/profile. 

Screenshot of the popup:
![image](https://user-images.githubusercontent.com/25513724/99852012-213cac80-2b4e-11eb-8c1f-b2a2fceb7393.png)
****

**Comment by Gruntfuggly** [comment]
The only thing todo tree uses the locale for is the timestamp in the debug channel, and even then it doesn't set it. Have you enabled `todo-tree.general.debug`? If not, can you enable it and see what is shown in the output channel.

**Comment by Bad3r** [comment]
I believe it could be an electron issue with vscode.
https://github.com/microsoft/vscode/issues/110322
After I enable debugging where can I view the log?

**Comment by Gruntfuggly** [comment]
Select the Output pane (from the View menu) then select Todo Tree from the combo box. Hopefully it should contain the command that is generated to make the search.

**Comment by 1Luc1** [comment]
Don't know if this is somehow related: [Reddit : vscode_issues_with_internal_terminal_locale](https://www.reddit.com/r/vscode/comments/jsdwvl/issues_with_internal_terminal_locale).

They stated a workaround by downgrading electron:
```
curl -O https://archive.archlinux.org/packages/e/electron9/electron9-9.3.3-1-x86_64.pkg.tar.zst
sudo pacman -U electron9-9.3.3-1-x86_64.pkg.tar.zst
```

**Comment by Gruntfuggly** [comment]
Hi - is this still an issue?

**Comment by Gruntfuggly** [comment]
I'm going to close this as I don't think there is anything I can fix in the extension. Please feel free to re-open if necessary.
