### ISSUE TITLE
Extend highlight by regex

### ISSUE THREAD

**Issue by datdotatprotocol** [Gruntfuggly/todo-tree#394]
Hi,

I'm trying to extend the highlight by modifying regex like this
`((\/\/|#|<!--|;|\/\*|^)\s*($TAGS.*:)|^\s*- \[ \])` - This is [regex101 test link](https://regex101.com/r/HB2Abt/2)

In regex101, the regex code above does very well - It highlight all the text until the very first semicolon:
![image](https://user-images.githubusercontent.com/46285472/100538643-90f41b00-3263-11eb-81f4-c6423c7f5647.png)

However, I cannot make this work the same in VSCode Todotree. How can make it work?

**Comment by Gruntfuggly** [comment]
It might be because the extension looks for `($TAGS)` in the regex and replaces it with a list of defined tags.

You could try expanding the list yourself, e.g.
`((\/\/|#|<!--|;|\/\*|^)\s*(TODO.*:|FIXME.*:)|^\s*- \[ \])`

Note - you'll have to repeat the `.*:` for each tag you use.

**Comment by Gruntfuggly** [comment]
Did you get this to work?

**Comment by datdotatprotocol** [comment]
> Did you get this to work?

Hi @Gruntfuggly,

Thanks for your help! Your solution works like a charm!
Is there anyway to mark the correct answer on Github?

![image](https://user-images.githubusercontent.com/46285472/101622895-39676380-3a4a-11eb-8d42-3ea1c09b82cf.png)

**Comment by Gruntfuggly** [comment]
Not sure - I assume anybody with the same problem will find it by search though.

Glad you got it sorted. 😁
