### ISSUE TITLE
Don't duplicate tree between explorer component and sidebar view

### ISSUE THREAD

**Issue by tristan957** [Gruntfuggly/todo-tree#395]
It seems a little weird to duplicate the same exact view in two places within VSCode.

VSCode now supports moving views between the sidebar and components of another view. For instance I can drag the explorer view into the sidebar and now I would have 2 TODO Tree instances in the sidebar.

Currently if you move the explorer view into the sidebar you get a generic explorer sidebar icon and no title for the view. It just shows up as explorer.

The VSCode API allows contributed views to have custom icons and title as noted here which I see you aren't taking advantage of.

https://code.visualstudio.com/api/references/contribution-points#contributes.views

With those attributes added, you could drop the duplicated view in favor of something that can be dragged around, have the same icon, and title anywhere and everywhere.

**Comment by tristan957** [comment]
![image](https://user-images.githubusercontent.com/11936772/100826040-18d25480-341f-11eb-92ce-962ea45048d9.png)
^ The explorer view dragged into the sidebar with the regular TODO Tree sidebar view still showing.

**Comment by tristan957** [comment]
![image](https://user-images.githubusercontent.com/11936772/100826299-a0b85e80-341f-11eb-87d1-6ed464be16ea.png)
Two todo tree views in the explorer view

**Comment by tristan957** [comment]
I now realize there is the showInExplorer option, but I really feel like this is an antipattern with regard to extension development.

**Comment by Gruntfuggly** [comment]
Yes, it's because you couldn't move views around when the extension was first written. It probably doesn't make any sense any more, so I'll simplify it.

**Comment by tristan957** [comment]
Cool. I put up a PR for you to review

**Comment by Gruntfuggly** [comment]
Ah great - thanks!
