### ISSUE TITLE
Dragging to sidebar

### ISSUE THREAD

**Issue by joserubicon** [Gruntfuggly/todo-tree#398]
Hi,

After v0.0.189 the rule showInExplorer is deprecated (as shown in notifications). When I try to drag todo-tree to the sidebar it works fine, showing the icon in the sidebar. But after restarting vscode the icon is gone and the notification appears.

Is it a bug or will it not be allowed to use the sidebar again?

Thank you.

**Comment by Gruntfuggly** [comment]
Did you remove the setting `showInExplorer` setting in your preferences? If not it will keep putting it back into the explorer pane. Unfortunately there is no way to know if you have moved it (as far as I know). But once you've removed the deprecated preference it should stay where you put it.

**Comment by oryon-dominik** [comment]
There is no `showInExplorer` setting in my preferences. I tried to remove every other setting too. But the Icon keeps to disapear at every restart.
That's a pity, because I love this extension and I use it  lot <3.

**Comment by Gruntfuggly** [comment]
Doh! I know what I've done - I left the default of the setting as 'true'! 

If you drag the pane back to the activity bar first, and then click 'Don't Show This Again' it should remember.

I'll make a proper fix.

**Comment by Gruntfuggly** [comment]
I've just uploaded a new version which should remember the setting correctly now. If you've already clicked 'Don't Show This Again' then it won't make any difference, but it should now be fixed for other people.

Sorry for the inconvenience!

**Comment by joserubicon** [comment]
Hi Nigel,

I do not have `showInExplorer ` in settings. I uploaded to the new version without clicking 'Don't Show This Again'. But now I can't see todo-tree under Explorer tab. 

In the other hand I can't drag from status bar the todo-tree elsewhere if this is the method to have todo-tree block under Explorer tab or his own tab. In other words, I can expand the todo List. :-(

Fresh install also doesn't work.

Thank you, pal!

**Comment by Gruntfuggly** [comment]
If you don't have `showInExplorer` anymore then it won't try to move it to the explorer pane automatically. But you should be able to drag it from the Activity Bar into the Explorer pane if you want to. 

It should always be visible somewhere, unless there are no TODOs in your workspace. If you want it to be visible even when it is empty, you can set `todo-tree.tree.hideWhenEmpty` to false.

If I am misunderstanding, could you attach a screenshot?

**Comment by joserubicon** [comment]
OK!!
`hideWhenEmpty ` helped me, also changing to workspace with TODOs. Now I have the todo-tree icon in sidebar.

But when I click to the status bar icon the action takes me to explorer panel. Highlights the working tree and I spect to open todo-tree. `todo-tree.general.statusBarClickBehaviour` is default as reveal.

Thank you Nigel!

**Comment by Gruntfuggly** [comment]
Ah yes - there might be a bug there. I'll investigate. Glad it's working better though now. 😄

**Comment by Gruntfuggly** [comment]
Fixed the status bar click in the latest version (0.0.191)
