### ISSUE TITLE
Todo and Fixme should have different icon.

### ISSUE THREAD

**Issue by vimalraj-a** [Gruntfuggly/todo-tree#40]
For TODO, Tick icon is very good. But, Having Tick icon for fixme confuses me for most times. My different color or different icon will be a big help

**Comment by Gruntfuggly** [comment]
You can change the colour in the preferences.

e.g. 
`"todo-tree.iconColours": { "TODO": "green", "FIXME": "red" }`

Changing the icon would be quite difficult unfortunately...

**Comment by Gruntfuggly** [comment]
Ah - that's a bug. Unless you're using the "group by tags" feature, the folders should come from the icon theme. I'll fix it...

**Comment by Gruntfuggly** [comment]
Latest version should now show the folder icon correctly.

**Comment by Gruntfuggly** [comment]
Latest version now support different icons using the octicon set. See https://github.com/Gruntfuggly/todo-tree/issues/51
