### ISSUE TITLE
The sidebar icon disappears

### ISSUE THREAD

**Issue by meoya** [Gruntfuggly/todo-tree#400]
When I update to 0.190, the sidebar icon disappears and my vscode pops up with the message, "Todo-Tree: 'showInExplorer' has been deprecated. If needed, the view can now be dragged to where you want it."
I only have to reinstall version 0.188 to get back to normal.

**Comment by Gruntfuggly** [comment]
The extension used to have two views (because it was created before you could move views with drag and drop). To simplify it, one of the views has now been removed.

If you want the view in the sidebar (activity bar), just drag it from the explorer pane into the activity bar, then remove `todo-tree.tree.showInExplorer` from your settings, or click **Don't Show This Again**

**Comment by meoya** [comment]
> The extension used to have two views (because it was created before you could move views with drag and drop). To simplify it, one of the views has now been removed.
> 
> If you want the view in to the sidebar (activity bar), just drag it from the explorer pane into the activity bar, then remove `todo-tree.tree.showInExplorer` from your settings, or click **Don't Show This Again**

Thank you, I did a fresh update today as you said and it works. (Yesterday, however, I also auto-updated by dragging the view from the explorer pane to the activity bar and then removing "todo-tree.tree.showInExplorer" from the settings, but when I restarted vscode, the sidebar icon still disappeared.) 
Another problem: Today every time I restart vscode, the todo sidebar icon disappears and is recreated again.

**Comment by Gruntfuggly** [comment]
That's because the extension now delays it's startup until the rest of vscode is activated, which should allow vscode to start up quicker.

**Comment by Gruntfuggly** [comment]
Yes - that's because of how the 'hideTreeWhenEmpty' setting is working, but I agree it's a bit odd.

I have a fix for it in the next release.

**Comment by kanlukasz** [comment]
I can confirm, have same case

**Comment by Gruntfuggly** [comment]
I have a fix, but there is a problem (https://github.com/microsoft/vscode/issues/112211).

I could just remove the `hideWhenEmpty` setting. I don't know if people really use it or not?

**Comment by kanlukasz** [comment]
I have this `todo-tree.tree.hideTreeWhenEmpty` parameter set to  `false` because of this problem.
I have not used this option before. I didn't even know about it :)
In general, I like when the icon is visible all the time 😄

**Comment by Gruntfuggly** [comment]
It would be nice if the API allowed the view to be collapsed programatically (like clicking the titlebar) but it's not currently possible. So the only alternative when you have the view in the Explorer pane and you don't want it taking up loads of room when its empty is to hide it.

If you keep it in the activity bar, then the it's not really relevant and setting `todo-tree.tree.hideTreeWhenEmpty` to `false` make sense.

**Comment by Mysbeario** [comment]
I'm using Linux and I have have same problem.

**Comment by Gruntfuggly** [comment]
Is the todo tree view in the Explorer pane?

**Comment by Gruntfuggly** [comment]
I've just uploaded a new version which should hopefully show the icon properly unless `hideTreeWhenEmpty` is `true`. I've also changed the default of `hideTreeWhenEmpty` to false, which should hopefully be less of a surprise to people. 😁

**Comment by kanlukasz** [comment]
Did some tests, all works fine 👍

**Comment by radiorz** [comment]
maybe you just drag it from the first page.
![image](https://user-images.githubusercontent.com/24271959/102049958-d8aaa300-3e1c-11eb-8ce0-08557c1ffe11.png)

**Comment by LeachZhou** [comment]
To be honest, I don’t know it can be dragged. I have been looking for it for a long time.

**Comment by Gruntfuggly** [comment]
You can drag all the views now, just grab the title bar. They can be moved into the Activity bar, into other panes (Explorer, for example) or down to the lower panel (Terminal, Problems, etc.).
