### ISSUE TITLE
TODOS section is gone in latest version

### ISSUE THREAD

**Issue by josbalcaen** [Gruntfuggly/todo-tree#401]
The TODOS section on the left disappeared with the latest update

**Comment by Gruntfuggly** [comment]
Please see #400. 

Did you get a popup telling you that `showInExplorer` was deprecated?

**Comment by josbalcaen** [comment]
Don’t think so. FYI, I don’t have any settings overridden in a .settings file

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Gruntfuggly** [comment]
OK - it probably didn't show the warning because the default setting used to be to have the view in the Explorer pane, as well as the dedicated view.

Out of interest, do you normally use it in the Explorer pane, or the dedicated view from the activity bar (with the icon)?

**Comment by Gruntfuggly** [comment]
Also, has dragging it back to the Activity Bar worked OK?

**Comment by josbalcaen** [comment]
Oh, I didn't know about the dedicated view!
Yes, dragging it to the explorer pane worked!
Thanks!
