### ISSUE TITLE
[Question] How can we disable highlighting TODOs next to scrollbar

### ISSUE THREAD

**Issue by kanlukasz** [Gruntfuggly/todo-tree#402]
Hello

Maybe I missed something in my settings, but I can't find the option that allows me to turn off the visibility of ToDo's next to the scroll bar
![obraz](https://user-images.githubusercontent.com/30685349/101754615-3913aa80-3ad4-11eb-87d8-c1b281baad7e.png)

Do you have option like this? Or should i change something else?

**Comment by Gruntfuggly** [comment]
You can do it by setting "rulerLane" to "none" in the `todo-tree.highlights.defaultHighlight`.
