### ISSUE TITLE
Need custom colors and icons preset.

### ISSUE THREAD

**Issue by timeneverdie** [Gruntfuggly/todo-tree#403]
The default color and icon set is hard to use.
Even though `todo-tree.highlights.customHighlight` can let users design what they prefer, however, that is too complex and cannot be an out-of-the-box extension.
If there is a preset of colors and icons, that would be fine.

**Comment by Gruntfuggly** [comment]
Can you post a screenshot showing why the defaults are hard to use - the current default of white text on a black background (for light themes) and black text on a white background (for dark themes) should work fine.

You don't need to use `todo-tree.highlights.customHighlight`, you can just change the colours in `todo-tree.highlights.defaultHighlight`. e.g.

```
    "todo-tree.highlights.defaultHighlight": {
        "foreground": "red",
        "background": "blue"
    }
```

I'm not sure how I could make it simpler.

Please explain how I could possibly choose a default set of colours that would work with every colour theme?

**Comment by timeneverdie** [comment]
@Gruntfuggly 

![image](https://user-images.githubusercontent.com/15784314/101759391-8152bd00-3b14-11eb-8c1e-08afa7a9470b.png)

I understand you may want to keep the default style as simple as possible. Maybe the white background and black font color is simple, but that's hard to catch the information of the kinds.

I mean it should give me yellow background when I type `TODO` and red background when I type `FIXME`. I can edit styles in json files, but that's not user-friendly.

Changing the global default style by `"todo-tree.highlights.defaultHighlight"` is not a good idea either, the problem is still there. I need to edit every kinds of styles like `TODO`, `FIXME`, `BUG` one by one in the json file.

**Comment by Gruntfuggly** [comment]
Unfortunately editing the json is the only way to modify those settings.

The only thing I can think of to make things easier would be to allow the colour to be set from the context menu of the tree. It would still have to prompt you for the colour, but it would save editing the json. My worry is that user will then want to change all the settings that way. 😐 

I don't really see how a default set of colours can work. Yellow and red may work for you, but vscode supports thousands of themes, so it is highly unlikely they will work for anybody else.

**Comment by timeneverdie** [comment]
@Gruntfuggly 

The method how to edit the setting is not the point. As the programmer, editing the json file is a must-have skill.

I am just saying to have a preset. Who thinks the colors or icons are not fit for them can edit in json file. It's subtle.

The point is that preset is necessary. Or why you preset the `tags` as `TODO` `FIXME` `BUG` `HACK`? Why you don't let users set their own `tags` from zero to one? That's the point.

The compatibility of themes may be a considerable point. But they can change the unseen colors by themselves, I think the chance of incompatibility is very little because most themes which **are easy to use**  must follow the basic color design, in other words, the common and mostly-used colors.

This is my minds. I can spend some time designing my preferred color preset and sync it with json on the cloud. But for the new user of this extension, they won't see the real feature for them unless they try to edit it. Different colors for different `tags` and different icons before the line number. You have built such a nice tool but many of them don't know it. So using the perset to exhibit the features is important too.

**Comment by Gruntfuggly** [comment]
Sadly the reason that the default is black on white (or white on black) is precisely because people complained about the default colour scheme.

What about a setting where you can specify a list of colours (with some defaults), which would just apply to the tags in the order they are defined?

e.g. 
```
todo-tree.highlights.useColourScheme: true,
todo-tree.highlights.foregroundColourScheme: "red,orange,yellow,green,blue,indigo,violet",
todo-tree.highlights.foregroundColourScheme: "white,black,white,cyan,grey,white,blue",
```
which would also be editable in the settings GUI.

**Comment by timeneverdie** [comment]
@Gruntfuggly 

Maybe only changing the default global color settings is okay. Even though only one style for all kinds of `tags`, but the configuration is easy.
I tried to use bookmark tree panel to track the document and I find I can get used to it. In fact, the real useful part is bookmark tree. Colors and icons just make experience better.
If VSCode can provide the api to get and adapt the theme color directly, maybe the work will be more efficient. Thanks anyway.

**Comment by Gruntfuggly** [comment]
Access to the actual colours form the theme is something a lot of people want, so hopefully it will happen at some point. That will make it much easier to provide colours based on the theme.

I've almost implemented something to provide colours as above. I think I'll add it as it does make it much simpler to specify some colours instead of having to edit the json - it can be done totally through the settings GUI. I think you're right that most people simply want to have different colours for the tags, so although the json settings make it very flexible, it's probably overkill just to set a few colours.
