### ISSUE TITLE
Ability to include specific files that are in ".gitignore"

### ISSUE THREAD

**Issue by kanlukasz** [Gruntfuggly/todo-tree#405]
TODOs are ignored after adding a file to `.gitignore`.
At first glance, it's obvious and right, but sometimes we'd like to include TODOs from files that are ignored by git.

So i thought i would use `todo-tree.filtering.includeGlobs` to disable ignoring specific files but if i use this, all TODOs doesn't work except this one
Eg.
```
    "todo-tree.filtering.includeGlobs": [
        "**/test.txt",
    ],
```
What can we do about it?

**Comment by Gruntfuggly** [comment]
Have you tried adding `--no-ignore` to `todo-tree.ripgrep.ripgrepArgs`. That should stop it using `.gitignore`. You can specify your own ignore rules instead using `--ignore-file`. 

From the ripgrep help:
```
        --ignore-file <PATH>...             
            Specifies a path to one or more .gitignore format rules files. These patterns
            are applied after the patterns found in .gitignore and .ignore are applied
            and are matched relative to the current working directory. Multiple additional
            ignore files can be specified by using the --ignore-file flag several times.
            When specifying multiple ignore files, earlier files have lower precedence
            than later files.
```

**Comment by kanlukasz** [comment]
> Have you tried adding `--no-ignore` to `todo-tree.ripgrep.ripgrepArgs`. That should stop it using `.gitignore`. 



`--no-ignore` works fine, but as you can see, it completely stops using `.gitignore`. 
This has its pros and cons

> You can specify your own ignore rules instead using `--ignore-file`.


From what i see  `--ignore-file` not working. I tried to set it like this
```
"todo-tree.ripgrep.ripgrepArgs": "--max-columns=1000 --no-config --ignore-file=.ignoretest",
```
with the `.ignoretest` content:
```
!test.txt
```
but still have no TODOs from `test.txt`

Have I done it wrong?

**Comment by Gruntfuggly** [comment]
I think you just need `test.txt` in the `.ignoretest`.

If you use `!`, you are saying "don't ignore this".

**Comment by Gruntfuggly** [comment]
In theory you could just copy the `.gitignore` file to `.ignoretest` and it should work the same as before, but then you can tweak `.ignoretest` to work with todo-tree, without it affecting git.

**Comment by kanlukasz** [comment]
It does not work:
![obraz](https://user-images.githubusercontent.com/30685349/102196528-51af0680-3ec0-11eb-9f0f-2ed3f0004bd7.png)

However, when we use the `.ignore` file and negation (`!`), then it works (without any additional settings like `--ignore-file`)
![obraz](https://user-images.githubusercontent.com/30685349/102196738-963aa200-3ec0-11eb-88c8-4ac5c2eb8e07.png)

**Comment by Gruntfuggly** [comment]
`.ignore` is another file ripgrep will use. So it is actually working correctly. If you use `.ignore` you don't need your own ignore file.

**Comment by Gruntfuggly** [comment]
ripgrep has a lot of options for ignore files!

man page: <https://www.mankier.com/1/rg>

**Comment by kanlukasz** [comment]
Yes I know. I'm just wondering why the custom ignoring file isn't working, but it's very low priority issue so i think we can close this as resolved by using `.ignore` file. Thanks for your help

**Comment by Gruntfuggly** [comment]
It would probably be easier to test it directly with ripgrep - it's possible I have misunderstood how it should work too. 🙄

**Comment by kanlukasz** [comment]
Maybe this is because: https://github.com/BurntSushi/ripgrep/issues/969#issuecomment-400336680 
>--ignore-file cannot work because it's specifically designed to have low precedence.

**Comment by Gruntfuggly** [comment]
😁 that would explain it!

**Comment by kanlukasz** [comment]
After digging deeper i found best solution 😸 Described below for other people who will be looking for it

`--glob` does this job best and with no extra files like` .ignore`
https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#configuration-file

So the `todo-tree.ripgrep.ripgrepArgs` setting might look like this:
```
"todo-tree.ripgrep.ripgrepArgs": "--max-columns=1000 --no-config --glob=file-with-todos.txt"
```
