### ISSUE TITLE
[Improvement] Blank space next to information such as "Scan Mode"

### ISSUE THREAD

**Issue by kanlukasz** [Gruntfuggly/todo-tree#408]
Here is unnecessary empty space:
![obraz](https://user-images.githubusercontent.com/30685349/102022747-24ac0800-3d89-11eb-898b-0646fa701fb4.png)

Is it because of VSCode API limitations? If so, maybe an interesting solution would be to insert icons there?
Maybe something like this:

![obraz](https://user-images.githubusercontent.com/30685349/102022995-c2ec9d80-3d8a-11eb-91bd-56ed4aa91c35.png)
Not sure about `Nothing found` icon but it's just a quick suggestion (Maybe I can think of something better)
As we define the look, I will be able to prepare svg😃

**Comment by Gruntfuggly** [comment]
Yes, it's using a tree item without an icon.

It would be easiest to use codicons - how about 'error', 'circle slash' or 'issues' ?

**Comment by Gruntfuggly** [comment]
![image](https://user-images.githubusercontent.com/376658/102024252-e4e52080-3d88-11eb-820d-71c0b5578f08.png)

**Comment by kanlukasz** [comment]
Yes, your idea is very cool.
Is it possible to adjust the size of these icons?

**Comment by Gruntfuggly** [comment]
No, they're very limited unfortunately. The only thing you could do is create custom versions which are smaller, but then the colours would not necessarily match the theme.

**Comment by kanlukasz** [comment]
Ok, so I vote for the implementation of the icons you proposed 👍
