### ISSUE TITLE
ticket numbers?

### ISSUE THREAD

**Issue by daniellacosse** [Gruntfuggly/todo-tree#409]
afaict, there's no way to tell todo-tree about a variable aspect of the tag and have it highlight the whole thing. this would be great for issue tracking tickets, like `TODO-17` or `DEVOPS-899`, for instance. would be amazing to set some kind of url template (`https://myjira.com/issues/$TAG`) to open for when you click on it, too.

**Comment by Gruntfuggly** [comment]
You could set the regex to something like this:
`(//|#|<!--|;|/\*|^)\s*($TAGS)-\d+`
That will apply to all the tags, but it won't highlight the numbers.

Alternatively, you could expand the $TAGS yourself, e.g.
`(//|#|<!--|;|/\*|^)\s*(TODO-\d+|FIXME)`
Which will then highlight the tag and the numbers, but you'll lose some other features.

As you can guess, it's not simple. The main reason is that any special characters in the tags are escaped as most people want them to be interpreted literally - e.g. `FIXME (NOW)` to match the brackets, rather then use them as part of the regex. I could try adding an option to override that behaviour - I'll try some experiments...

**Comment by Gruntfuggly** [comment]
I've just uploaded version 0.0.197 which provides some support for sub tags. You can define todo-tree.regex.subTagRegex to extract a sub tag. This can then be used for grouping and custom highlights. Details and examples are in the README.

This should in theory allow you to extract ticket numbers. There is also an option to set the URL template so you can click on them to visit.

Let me know how you get on with it.

**Comment by daniellacosse** [comment]
best news i've gotten all week - i'll take it for a spin this weekend

**Comment by daniellacosse** [comment]
Thanks a whole bunch, but there's just one issue. I'm struggling to get the subTag to trigger. Does the subTagRegex have to be a subset of the regular regex? If you don't mind sending me an example config of regex, subTagRegex, subTagClickUrl and customHighlight all working together I can drop it into VSCode and play with it further?

**Comment by Gruntfuggly** [comment]
I've left the default setting for the regex, but set
```
"todo-tree.regex.subTagRegex": "\\s*\\((.*)\\)",
"todo-tree.tree.subTagClickUrl": "https://github.com/${subTag}"
    "todo-tree.highlights.customHighlight": {
        "TODO": {
            "icon": "$(account)",
            "background": "grey",
            "foreground": "red",
            "type": "tag-and-subTag"
        },
        "gruntfuggly": {
            "background": "yellow",
            "foreground": "red"
        },
    },
```
Which now matches something like
```
// TODO (gruntfuggly) Fix this!
```
![image](https://user-images.githubusercontent.com/376658/109418855-59ac1c00-79c2-11eb-9dba-f5b7ffa9d3e9.png)
![image](https://user-images.githubusercontent.com/376658/109418880-72b4cd00-79c2-11eb-82a4-7d5d13aa531b.png)

Clicking on `gruntfuggly` will open my github profile.

**Comment by Gruntfuggly** [comment]
I've realised that the docs don't mention setting `tag-and-subTag` for the `type`, which is needed for the highlights.

**Comment by Gruntfuggly** [comment]
There is also a context menu item to toggle grouping by sub tag. I should probably document the options in the context menu too.

**Comment by daniellacosse** [comment]
whoo! got it working:

https://www.loom.com/share/4042c1e1713a4d1dae1fc344733a5451

thanks again!
