### ISSUE TITLE
case sensitivity setting ignored

### ISSUE THREAD

**Issue by zurkoxxx** [Gruntfuggly/todo-tree#41]
Steps to reproduce:
Set `"todo-tree.filterCaseSensitive": false` (default value)

**Expected result:** all variants of "todo" to show up in results.
**Actual result:** only uppercase "TODO"s show up.

![image](https://user-images.githubusercontent.com/12783209/42206210-2492fdce-7eaf-11e8-9377-9b52012a6292.png)

**Comment by Gruntfuggly** [comment]
The `"todo-tree.filterCaseSensitive"` setting only applies when filtering the results - using the filter icon.
If you want case insensitive searches, you can add `"-i"` to ` "todo-tree.ripgrepArgs"`, but be aware that you may get some false results.

**Comment by zurkoxxx** [comment]
my mistake then :)
thanks for clearing that up

**Comment by Gruntfuggly** [comment]
No problem - I'll add a note in the README to make it a bit clearer in the next release.
