### ISSUE TITLE
when i write some todo in comment ,they are not hightlighted?

### ISSUE THREAD

**Issue by radiorz** [Gruntfuggly/todo-tree#411]
![image](https://user-images.githubusercontent.com/24271959/102049728-6639c300-3e1c-11eb-9f65-b801d2a04208.png)

the // comment are  hightlighted correctly.
but /***/ are not.

**Comment by Gruntfuggly** [comment]
To enable multiline todos, you need to modify the regex. This isn't enabled by default as it can potentially affect performance. For details see:

https://github.com/Gruntfuggly/todo-tree#multiline-todos

There are more examples in the [wiki](https://github.com/Gruntfuggly/todo-tree/wiki).

**Comment by radiorz** [comment]
i am using javascript. which reqex should i choose?
- (//)\\s*($TAGS).*(\\n\\s*//\\s{2,}.*)*
- (/\\*)\\s*($TAGS).*(\\n\\s*(//|/\\*|\\*\\*)\\s{2,}.*)*

default ：
((//|#|<!--|;|/\*|^)\s*($TAGS)|^\s*- \[ \])

**Comment by Gruntfuggly** [comment]
If you just want to match your second example, you don't even need multiline - you can just add `\s\*` to the regex, e.g.
```
((//|#|<!--|;|/\*|^|\s\*)\s*($TAGS)|^\s*- \[ \])
                    ^ here
```
If you want to play around with the regex, this site is good:
 <https://regex101.com>

**Comment by sfuerte** [comment]
Why not to simplify the regex? 
I re-configured mine similar to https://github.com/wayou/vscode-todo-highlight (see the last two settings at the bottom):

```
    "todo-tree.highlights.customHighlight": {
        "BUG:": {
            "foreground": "red",
            "background": "white",
            "icon": "bug"
        },
        "TODO:": {
            "foreground": "#fff",
            "background": "#ffbd2a",
            "rulerColor": "rgba(255,189,42,0.8)",
        },
        "FIXME:": {
            "foreground": "#fff",
            "background": "#f06292",
            "iconColour": "red",
            "rulerColor": "rgba(240,98,146,0.8)",
            "icon": "flame"
        }
    },
    "todo-tree.highlights.defaultHighlight": {
        "color": "#2196f3",
        "backgroundColor": "#ffeb3b",
        "rulerColour": "red",
        "type": "tag",
    },
    "todo-tree.general.tags": [
        "BUG:",
        "HACK:",
        "FIXME:",
        "TODO:",
        "XXX:"
    ],
    "todo-tree.regex.regex": "($TAGS)"
```

PS: I do understand consequences that it can be highlighted not only in the comments but in some legit code, but personally I've never seen such cases.

**Comment by Gruntfuggly** [comment]
Well, that's precisely the reason it's not simpler - it's only intended to match tags in comments.

Obviously you can change it to whatever you want - that's why it's configurable, but the idea is to make it work out of the box for most people.

I've also given up changing the default because every time I do it just causes issues. 😁 

Are you happy for me to close this now?

**Comment by sfuerte** [comment]
@Gruntfuggly, I'm glad it's configurable :) thanks for that! 

as for the closing, I guess, it's between you and the original poster, @radiorz

**Comment by Gruntfuggly** [comment]
Sorry - didn't check who was posting!

To be honest, your approach to the regex is a good idea. If I was starting again from scratch, I'd probably do it as you have done.
