### ISSUE TITLE
Allow to make the highlights to use bold text for the tags

### ISSUE THREAD

**Issue by Kreyren** [Gruntfuggly/todo-tree#415]
### Current
// FIXME(Krey): Something

### Expected
// **FIXME(Krey)**: Something

* Notice the usage of bold text for the tag in expected

**Comment by Kreyren** [comment]
Closing as better comments 2 seems to have abstract for this so i decided to let todo tree to handle the tab only.

**Comment by Kreyren** [comment]
Reopenning the better comments handles only the whole comment with option to change lines based on using tag which doesn't work as expected in the issue.

**Comment by Gruntfuggly** [comment]
You can use "fontWeight" to make the text bold. e.g.

```
    "todo-tree.highlights.defaultHighlight": {
        "fontWeight": "bold"
    },
```

**Comment by Kreyren** [comment]
@Gruntfuggly thanks, works as expected!
