### ISSUE TITLE
`$TAGS` is not expanding in `(KEYWORD|KEYWORD|...)`

### ISSUE THREAD

**Issue by Kreyren** [Gruntfuggly/todo-tree#417]
## Terminology
![image](https://user-images.githubusercontent.com/11302521/103243192-f580c380-4950-11eb-9bdf-7c04e01c9ca7.png)

*Provided as image, because GitHub is manipulating spaces

## Issue
Using
```json
  "todo-tree.regex.regex": "(FIXME|DNC|DNM|DNR|TODO|DOCS)((\\-.*|)\\(.*\\))\\:",
  "todo-tree.highlights.enabled": true,
```

Highlights the tags

![image](https://user-images.githubusercontent.com/11302521/103243037-62478e00-4950-11eb-8071-35449365f042.png)

But does not index them:
![image](https://user-images.githubusercontent.com/11302521/103243094-90c56900-4950-11eb-88e6-a642b6165961.png)

Where using:
```json
   "todo-tree.regex.regex": "$TAGS((\\-.*|)\\(.*\\))\\:",
```

Results in error or indexes only the `Keyword`:

![image](https://user-images.githubusercontent.com/11302521/103243359-89528f80-4951-11eb-8213-fcf71111b65c.png)

### Expectation
Ability to use tags with subtags and signatures in a way that highlights them in bold e.g.

// **FIXME-QA(Krey):** Something

### Problematic code
```rs
// FIXME(Krey): Test
// DNC(Krey): Thing
// DNC-QA(Krey): Thing

// FIXME-QA(Krey): Consider implementing SNAFU <https://github.com/shepmaster/snafu> for better errors
// FIXME-BRAINSTORM(Krey): Consult with the torproject how to write software that is friendly to onion-services

/// Function to get userland of Exherbo Linux in specified directory
// TODO(Krey): See chapter in rustbook on slices as `str` is a slice thus we need `&str`
// DNC(Krey): Working on this, contrib of shims appreciated
```

### Example project:
https://github.com/Kreyrock/Kreyrock (issue observed in `src/sysfetch`)

Optimized for gitpod (https://github.com/Kreyrock/Kreyrock) and GitHub Codespaces.

**Comment by Gruntfuggly** [comment]
Can you try adding parenthesis around $TAGS, as that is what is replaced (see **todo-tree.regex.regex** in https://github.com/Gruntfuggly/todo-tree#configuration)
```
"todo-tree.regex.regex": "($TAGS)((\\-.*|)\\(.*\\))\\:"
```
I should also update the info in the `package.json`.

Please let me know if that doesn't work.

**Comment by Kreyren** [comment]
Using

```json
"todo-tree.regex.regex": "($TAGS))((\\-.*|)\\(.*\\))\\:",
```

Results in:

![image](https://user-images.githubusercontent.com/11302521/103388595-c5c4ed80-4b01-11eb-861e-92500f42c564.png)

Note vscodium being restarted after making the change just to make sure it's in affect.

Seems to wrongfully expand in `(TODO|FIXME|...))` instead of `(TODO|FIXME|..)` ?

using

```json
  "todo-tree.regex.regex": "(($TAGS)((\\-.*|)\\(.*\\))\\:",
```

Results in:

![image](https://user-images.githubusercontent.com/11302521/103388675-4d126100-4b02-11eb-8f7a-5e21fea6f197.png)

**Comment by Gruntfuggly** [comment]
I don't think you copied the example correctly.

> ```json
> "todo-tree.regex.regex": "($TAGS))((\\-.*|)\\(.*\\))\\:",
> ```

You have an extra `)` after `($TAGS)`

> ```json
>   "todo-tree.regex.regex": "(($TAGS)((\\-.*|)\\(.*\\))\\:",
> ```

You have an extra `(` before `($TAGS)`

The example I posted above should work, although it still generates an error for me because of the `\\:`. You don't need to escape the `:` so you should be OK with
```
"todo-tree.regex.regex": "($TAGS)((\\-.*|)\\(.*\\)):"
```

**Comment by Kreyren** [comment]
You are right, sorry! Seems to work now.
