### ISSUE TITLE
[Feature Request] Add category or topic to tags. E.g: TODO:UI or TODO:SomeFeature

### ISSUE THREAD

**Issue by MaximS** [Gruntfuggly/todo-tree#419]
It would be convenient to add additional category to a tag to mark specific areas of an application, like UI, model, etc, or some particular feature. Then two-level grouping, sorting and filtering could be used. Categories could be multiple for each tag.
Relates to:
- #313 
- #236 

The #236 probably covers both: this FR as well as #313.

**Comment by Gruntfuggly** [comment]
I've just uploaded version 0.0.197 which provides some support for sub tags. You can define `todo-tree.regex.subTagRegex` to extract a sub tag. This can then be used for grouping and custom highlights. Details and examples are in the README. 

Multiple sub tags becomes too difficult though as items would then need to potentially appear in the tree in multiple places.
