### ISSUE TITLE
Does the group/ungroup tag button actually work?

### ISSUE THREAD

**Issue by schlundus** [Gruntfuggly/todo-tree#42]
I have some tags defined and files with different tags .. but toggle the buttons doesn't make any difference?

**Comment by Gruntfuggly** [comment]
Clicking the tag group button should reorder the tree with the tag names at the top and the files inside. I'll attach some screen shots...

**Comment by Gruntfuggly** [comment]
Non-grouped:
![image](https://user-images.githubusercontent.com/376658/42310221-c16f2850-8032-11e8-9b48-859c1a21f1ad.png)

Grouped by tag:
![image](https://user-images.githubusercontent.com/376658/42310323-0b8ea104-8033-11e8-93f8-03c37cdbc60c.png)

**Comment by schlundus** [comment]
Thanks for the fast replay... but in my setting nothing happens
![image](https://user-images.githubusercontent.com/17083185/42310776-8e44e226-803c-11e8-9658-ba7339e4f8b3.png)

**Comment by Gruntfuggly** [comment]
Could you attach your todo-tree configuration? I would expect the '//' to be hidden too, so something is not right...

**Comment by schlundus** [comment]
"todo-tree.expanded": true,
  "todo-tree.globs": [
    "**/*.ts",
    "**/*.tsx",
    "**/*.less",
    "**/*.handlebars",
    "**/*.html",
    "!typings",
    "!node_modules",
    "!parkinglot",
    "!app/build",
    "!app/www"
  ],
  "todo-tree.grouped": true,
  "todo-tree.highlight": false,
  "todo-tree.iconColours": {
    "todo": "red",
    "maybe": "#ffa500",
    "hint": "green",
    "res1": "yellow",
    "res2": "yellow",
    "res3": "yellow"
  },
  "todo-tree.regex": "(//|#|<!--|;)\\s*(todo|maybe|hint|res1|res2|res3)",
  "todo-tree.showInExplorer": false,

**Comment by Gruntfuggly** [comment]
Can you try replacing 
`(//|#|<!--|;)\s(todo|maybe|hint|res1|res2|res3)`
with 
`(//|#|<!--|;)\s($TAGS)`

**Comment by Gruntfuggly** [comment]
You can probably just remove it - the default should work.

**Comment by Gruntfuggly** [comment]
Actually, you should remove definition of **todo-tree.regex** and put the tag list into **todo-tree.tags**, e.g.
```
"todo-tree.tags": [
  "todo",
  "maybe",
  "hint",
  "res1",
  "res2",
  "res3"
]
```

**Comment by schlundus** [comment]
Ah... i've now defined this
`
"todo-tree.tags": [
    "todo",
    "maybe",
    "hint",
    "res1",
    "res2",
    "res3"
  ],
`

and removed the "todo-tree.regex"-settings...and it works...

**Comment by Gruntfuggly** [comment]
I'll add a note in the README.md for this. I'm guessing you updated the regex a while back...
