### ISSUE TITLE
How to filter on word not being present on a Todo line

### ISSUE THREAD

**Issue by ptournet** [Gruntfuggly/todo-tree#421]
Hi,
It might be an easy thing to do, but haven't been able to figure it out on my own, I'm here to ask for your help :
I would like to be able to filter my todos not on a word being present, but on a word being absent and I wonder how to achieve that.
With the following example :
> // TODO #1- arms, legs, torso
> // TODO #2- arms, torso
> // TODO #3- legs, torso
If I filter on "arms", I get TODO #1 and #2. And I would like to only get TODO #2, by specifying that I don't want "legs" (and "!legs" as a filter isn't the way to go ;) ).
Any idea on how to achieve that (if possible at all) ? Thanks in advance

**Comment by Gruntfuggly** [comment]
Which "filter" are you using? Do you mean the filter button from the titlebar?

**Comment by ptournet** [comment]
Yes, the one labeled "Filter Tree"

**Comment by Gruntfuggly** [comment]
What is entered is used as a regular expression - and unfortunately excluding stuff with regular expressions is hard.

You could try playing around on https://regex101.com and see if you can come up with something that works?

**Comment by ptournet** [comment]
Thanks for your input ! After searching for a while, I've found a way to do so with the following expression :
> ^((?!word).)*$
("word" being the word you want to filter out). Not overly easy to use and I have yet to figure out how to filter out several words, but it's a start ! ;)

**Comment by jerrens** [comment]
@ptournet - If you want to filter out a second word, separate the (?!nextWord) group(s) with a '|' char.

Example:
```
// TODO #1- arms, legs, torso
// TODO #2- arms, torso
// TODO #3- legs, torso, feet
// TODO #4- feet
```

The pattern: `^((?!arms)|(?!torso).)*$` would ignore the first three and only return #4

**Comment by Gruntfuggly** [comment]
@ptournet Are you OK for me to close this now?
