### ISSUE TITLE
[question] using worker thread for file searching

### ISSUE THREAD

**Issue by ctf0** [Gruntfuggly/todo-tree#422]
i was reading about LSP and i found that its using multi thread to do its work, 
i've tried to use node worker_thread vie [threadjs](https://www.npmjs.com/package/threads) but without luck so i wanted to ask if u have any plans for that, have u tried it b4 with vscode ext ?

**Comment by Gruntfuggly** [comment]
todo-tree uses https://github.com/BurntSushi/ripgrep to do the searching which is already multithreaded - it's one of the reasons it's quick. Vscode also uses it for searching, for the same reasons I believe.

**Comment by ctf0** [comment]
oh ok, thanx for the headsup & directing me to it.
