### ISSUE TITLE
falsely identifying markup as tag

### ISSUE THREAD

**Issue by abuxton** [Gruntfuggly/todo-tree#428]
This is probably something i've overlooked in the docs but I tried with no success to look for it
 in my  markdown pages
- [ ] checkbox 
is identified as TODO: and counted as TODO.

**Comment by Gruntfuggly** [comment]
It counts markdown 'todo's by default. If you want to remove them, change the setting:

```
"todo-tree.regex.regex": "((//|#|<!--|;|/\\*|^)\\s*($TAGS)|^\\s*- \\[ \\])"`
```
to 
```
"todo-tree.regex.regex": "(//|#|<!--|;|/\\*|^)\\s*($TAGS)"
```
