### ISSUE TITLE
[Question] Hide tags when shown as grouped in tree

### ISSUE THREAD

**Issue by lonix1** [Gruntfuggly/todo-tree#429]
Hey @Gruntfuggly!

Quick question for you, is it possible to hide the tags when shown in a grouped tree (i.e. "tags only" and "group by tag" options)?

So instead of this:
````
v BUG
  BUG foo bar
v TODO
  TODO baz qux
  TODO qux quux
v TEST
  TEST test foo
  TEST test bar
````

To show this instead:
````
v BUG
  foo bar
v TODO
  baz qux
  qux quux
v TEST
  test foo
  test bar
````

Reasons: 1) showing tags adds no value as the group already shows the tag, and 2) it makes the line longer and harder to read (requires scrolling).

I couldn't find the right combo to make it work. :laughing:

If there's no way to do this, it would be a great idea to have an option `hideTagsWhenGroupedByTag` (similar to `hideIconsWhenGroupedByTag`).

**Comment by Gruntfuggly** [comment]
You can customise the label that is displayed in the tree, e.g. change,
```
 "todo-tree.tree.labelFormat": "${tag} ${after}",
```
to
```
 "todo-tree.tree.labelFormat": "${after}",
```

There is a list of available placeholders in the READMD.md (https://github.com/Gruntfuggly/todo-tree#configuration).

**Comment by lonix1** [comment]
Really useful option, thanks!
