### ISSUE TITLE
[Feature Request] add issues from remote repository to TODO tree

### ISSUE THREAD

**Issue by xsro** [Gruntfuggly/todo-tree#430]
A lot of todo are in remote repository as issues. Will the extension include them?

**Comment by Gruntfuggly** [comment]
What do you mean by remote repository? It uses a file system search, so if the remote repository is 'visible' to the filing system it should be able to find them.

**Comment by xsro** [comment]
I mean something like issues in github. Just a idea, in fact, this is a feature of [GitHub Pull Requests and Issues](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github).

**Comment by Gruntfuggly** [comment]
I'm not sure how it would work? The extension searches for 'TODO' already in the files. I think "GitHub Pull Requests and Issues" can create issues from TODOs in the code, but they still need to exist first.

**Comment by xsro** [comment]
I just think the extension can fetch the issues from its github repo via Github API and put them together with TODOs. I am also not very sure about whether this is necessary or not. Thanks a lot.

**Comment by Gruntfuggly** [comment]
That would be completely different functionality for the this extension - this one search files for TODOs. It's doesn't talk to github at all. 

The "GitHub Pull Requests and Issues" extension already lists issues and allows you to browse them, so I don't understand what it has to do with this extension?

**Comment by xsro** [comment]
Yes, I find it's not very necessary. Thanks
