### ISSUE TITLE
Colour + Color

### ISSUE THREAD

**Issue by justynr** [Gruntfuggly/todo-tree#431]
As a Canadian, love the use of "Colour", but took me forever to figure out why it wasn't working.
`"iconColour": "orange",`
I often offer both spellings in multi-national projects, so either or both work.
A 'nice to have' but not necessary. 
Cheers!

**Comment by Gruntfuggly** [comment]
I can add support for it in the highlights configuration, but not the main settings as it would need multiple settings, which could end up even more confusing.

I'll add it to the highlights though.

**Comment by Gruntfuggly** [comment]
Should now allow either spelling for the iconColour in v0.0.197.
