### ISSUE TITLE
todo tree not responding 

### ISSUE THREAD

**Issue by shekari-ah** [Gruntfuggly/todo-tree#433]
my vscode was extreemly slow and when I was struggling to find the source of the problem, I encounter this:
```
[2021-02-11 15:19:09.406] [renderer1] [warning] UNRESPONSIVE extension host, 'Gruntfuggly.todo-tree' took 100% of 5161.926ms, saved PROFILE here: 'c:\Users\A-SHEK~1\AppData\Local\Temp\exthost-5803b3.cpuprofile' [{"id":"gc","total":25232,"percentage":0},{"id":"Gruntfuggly.todo-tree","total":5136502,"percentage":100},{"id":"program","total":12,"percentage":0}]
```

**Comment by Gruntfuggly** [comment]
Can you confirm by disabling the extension and seeing if it makes a difference?

Unfortunately the unresponsive extension warning are not very accurate. I quite often see them for extensions that do virtually nothing.

Can you post your todo-tree settings too please?

**Comment by shekari-ah** [comment]
I disabled the todo tree and my vscode performance problem has fixed. so I am sure the problem was because of the todo tree.
 I guess the problem only accrued on the big projects. because I have lots of other projects and I never saw the todo tree act like that.

about the settings, I didn't change the todo tree setting since I installed it, the todo tree version is v0.0.196. and my current project is the next js project.

I installed the todo tree again and the problem has fixed. I did the same a month ago when you disable the TODO tree side tab icon by default and move it to the explorer tab because the todo tree was crashing that time too.

if you need any other info just let me know

**Comment by shekari-ah** [comment]
quick question: 
is todo tree watch the files included in the .gitignore file too?
is todo tree watch the files included in the .tsconfig exclude?

**Comment by shekari-ah** [comment]
Nah, after 15 min of installing the todo tree, vscode gets really slow again

**Comment by Gruntfuggly** [comment]
How big is your workspace? How many TODO's does it find?

**Comment by Gruntfuggly** [comment]
ripgrep (which is used to do the search) should automatically ignore files from your `.gitignore`. I don't think it knows about `.tsconfig` though.

**Comment by shekari-ah** [comment]
> How big is your workspace? How many TODO's does it find?
> 
> There are few setting you could change to see if it makes a difference, and narrow down the problem:
> 
> 1. Turn off highlights (`todo-tree.highlights.enabled`)
> 2. Change the scan mode (`todo-tree.tree.scanMode`) to `workspace only` or `current file`. This will obviously reduce the size of the tree though.
> 
> Lastly, can you try the command "Todo Tree: Reset Cache" and see if that makes it responsive again.

I'll inform you after doing theme.

My project is a website, it is heavily typed with typescript and it's include 600 file and each file consists of 700 line in average 

I only have 3 or 4 todo in my whole project (we have to resolve all the todo's before before push)

**Comment by shekari-ah** [comment]
> ripgrep (which is used to do the search) should automatically ignore files from your `.gitignore`. I don't think it knows about `.tsconfig` though.

I guess .gitignore is fine. So problem is not about checking the build or node-model folder.

**Comment by Gruntfuggly** [comment]
That's really odd then - the scan may take a while with a big workspace but if there are only a few results, once the scan is done I wouldn't expect it to have any impact on performance. It should only scan the workspace at startup or when you refresh the view.

If you enable the debug view (`todo-tree.general.debug`) and go to the Output Pane, you'll find a Todo Tree option in the drop down. If you open this, you should be able to see the command that it is using to search the workspace. You can try copying this into a terminal window and running it manually to see what happens.

Actually, it might be quite useful if you post the contents of the output channel.

**Comment by Gruntfuggly** [comment]
I just remembered - there is also an option `todo-tree.tree.scanAtStartup` which you can set to `false`. Can you try that and see if it makes any difference?

**Comment by shekari-ah** [comment]
I test the todo tree with several other projects, also heavily types with typescript, and as expected the extension works fine.
I think the problem occurred only with the next js project and I don't know why.
I am going to use the debug panel to find the problem, ill tell you the result.

**Comment by Gruntfuggly** [comment]
Hi - any luck with the debug information?

**Comment by Gruntfuggly** [comment]
I'm going to close this now - feel free to reopen if you have further information.
