### ISSUE TITLE
Feature request: Add an option to show the amount of TODO in your code

### ISSUE THREAD

**Issue by Leccho** [Gruntfuggly/todo-tree#434]
I would like to see how many TODO and FIXME I have in my code just like git and problems in the following image:
![image](https://user-images.githubusercontent.com/2791678/107661428-46295300-6c57-11eb-8ed4-d9a7d549c19f.png)

**Comment by Gruntfuggly** [comment]
Hi - Unfortunately there is no support for extensions to show this at the moment (even though the documentation suggests it can 😠 ). It has been requested several times. As soon as VSCode provides the API to add it I will be adding it to the extension.

The nearest you can get at the moment is that the number is displayed in the view title.

I am going to close this issue, but I promise the feature will be added as soon as it can be. 😄 👍 

You can follow these issues to see when it happens:
https://github.com/microsoft/vscode/issues/62783
https://github.com/microsoft/vscode/issues/108496

**Comment by Leccho** [comment]
Thanks for the fast feedback! 😄

**Comment by Gruntfuggly** [comment]
No problem - it's a feature I would love to have too!

**Comment by Leccho** [comment]
It would seem that it's now available, I saw an other extension use it.  (https://github.com/microsoft/vscode/issues/62783)
