### ISSUE TITLE
Feature Request: Regex for highlighting tags

### ISSUE THREAD

**Issue by mockingjet** [Gruntfuggly/todo-tree#436]
I want to leave an issue tag in comment like this.

     // #62
     const getTags = () => { ... }

So any # followed by number ( /\#\d+/ ) can be highlighted.

This feature would be very useful!

**Comment by Gruntfuggly** [comment]
You could add it to the regex, e.g.
```
"todo-tree.regex.regex": "((//|#|<!--|;|/\\*|^)\\s*($TAGS)|^\\s*- \\[ \\]|(//\\s*#\\d+))"
```

**Comment by mockingjet** [comment]
Never knew it can be used that way, thanks.
