### ISSUE TITLE
[FR] Option to allow pluralized tags

### ISSUE THREAD

**Issue by wenfangdu** [Gruntfuggly/todo-tree#437]
Currently, if I want to highlight both `TOTO` and `TODOS`, I need to use ` "todo-tree.general.tags": ["TODO", "TODOS"]`, would be great if I could use a setting like `"todo-tree.allowPlural": true`, then `"todo-tree.general.tags": ["TODO"]` to highlight both.

I searched through the settings, but couldn't find such a setting, if it already exists, please let me know.

**Comment by Gruntfuggly** [comment]
What is the problem with using `"todo-tree.general.tags": ["TODO", "TODOS"]`?

**Comment by wenfangdu** [comment]
@Gruntfuggly Hi, it's fine. However, if there're many singular tags, and we want to make their plural form be auto supported as well, e.g. `["TODO", "LTODO", "FIXME", "LFIXME" ...]` would have same effect as `["TODO", "TODOS", "LTODO", "LTODOS", "FIXME", "FIXMES", "LFIXME", "LFIXMES" ...]`, then such setting would be useful.

**Comment by Gruntfuggly** [comment]
Yes, sorry but that would involve quite a lot off effort to save a few characters of typing. 🙂 

However - you can at least create tag groups, so you can group TODO and TODOS, etc. which saves some configuration for highlights, etc.
