### ISSUE TITLE
Highlight line number

### ISSUE THREAD

**Issue by muuvmuuv** [Gruntfuggly/todo-tree#439]
Would it be possible to also highlight the line number and its background by default?

![Bildschirmfoto 2021-02-23 um 18 10 17](https://user-images.githubusercontent.com/11534760/108880504-a4b0e280-7602-11eb-8ffd-99a8f4a8f468.png)
> So that it would make the background in the orange box also green

And is it possible to adjust the icon size? I think it would look nicer if it would be two or more pixels smaller.

**Comment by Gruntfuggly** [comment]
Sorry, but neither of those are possible (as far as I know) with the current API.

**Comment by muuvmuuv** [comment]
What a shame, would look soo nice ^^

**Comment by Gruntfuggly** [comment]
You could make a vscode feature request for styling of the line numbers, but I doubt it will get anywhere. 🙁

**Comment by muuvmuuv** [comment]
Its fine. They have enough todo with Apple SIlicon ATM. Nothing important for me ^^
