### ISSUE TITLE
Alphabetic sorting of todos is broken in 0.0.198

### ISSUE THREAD

**Issue by greeenway** [Gruntfuggly/todo-tree#444]
It works for me in version 0.0.196 (in 0.0.197 the tree does not load at all?)

my settings
``` 
"todo-tree.tree.showBadges": true,
"todo-tree.general.statusBar": "total",
"todo-tree.tree.labelFormat": "${after}",
"todo-tree.tree.sortTagsOnlyViewAlphabetically": true,
```

by the way - thanks for this great extension :) using it every day

**Comment by Gruntfuggly** [comment]
197 was a dud. Best ignore it. 😉 

I'll investigate the sorting. I simplified the sorting in the last version, so I may have overlooked something.

**Comment by Gruntfuggly** [comment]
Yeh - it's broken. It was definitely working though - will try and fix tonight.

**Comment by Gruntfuggly** [comment]
Ah - do you have `todo-tree.tree.sort` enabled? I had it turned off - with it on, the sort works as expected.

**Comment by greeenway** [comment]
Hi, yes I have `todo-tree.tree.sort` set to `true`. I think this is also the default value, but I now set it explicitly. With either false or true it does not sort yet (also in 0.0.199), but it works in 0.0.196.

**Comment by Gruntfuggly** [comment]
OK - I've just realised also that the only view which is sorted alphabetically is the "tags only" view.

Can you post a screenshot please? Have you modified any of the other todo tree settings?

**Comment by greeenway** [comment]
sure,

I only modified these settings:
```
"todo-tree.tree.showScanModeButton": false,
"todo-tree.tree.sortTagsOnlyViewAlphabetically": true,
"todo-tree.tree.sort": true,
"todo-tree.tree.showBadges": true,
"todo-tree.general.statusBar": "total",
"todo-tree.tree.labelFormat": "${after}",
```

Here are two screenshots of the same folder with version (needed to blur out the content ;) ):

196 (working)
![working_196](https://user-images.githubusercontent.com/878704/109477153-fe3c6580-7a77-11eb-9e2e-dc2d915e4778.png)


199 (broken)
![broken_199](https://user-images.githubusercontent.com/878704/109477160-009ebf80-7a78-11eb-90ba-fb6d2c1899c7.png)

**Comment by Gruntfuggly** [comment]
I think it might be because your label format setting does not include the tag. At the moment, the sorting is done based on the  tag, not the label. I can see that might be confusing though.

Can you remove the label format setting and see what it does please?

**Comment by Gruntfuggly** [comment]
I'll change it to sort by the label as it doesn't make any difference, but will be less confusing.

**Comment by greeenway** [comment]
I commented out the labelFormat setting, now they "TODO" before the label are back but they still appear unsorted

**Comment by Gruntfuggly** [comment]
Please can you post another screenshot?

**Comment by greeenway** [comment]
![broken_with_todo](https://user-images.githubusercontent.com/878704/109492172-d60a3200-7a8a-11eb-92ae-cddd0e859406.png)
sorry for the late reply.

**Comment by Gruntfuggly** [comment]
OK - they actually are sorted alphabetically, but they are all the same, so it then uses the line number. 🙂 

The fix I have added will make it work as expected though.

**Comment by Gruntfuggly** [comment]
Please try the latest version (0.0.200) - should now work as expected.

**Comment by greeenway** [comment]
Yay, my todos work again (as expected) :) Thank you very much for the quick fix!
