### ISSUE TITLE
Bad parse result

### ISSUE THREAD

**Issue by chanjsq** [Gruntfuggly/todo-tree#445]
Thank you for your work. But I found a bug, the `-->` part is redundant. I have a screenshot:

![image](https://user-images.githubusercontent.com/30150098/109396344-fee7d580-796b-11eb-9f3c-a030128ca61b.png)

**Comment by chanjsq** [comment]
The code snippet is:

```vue
<el-form inline @submit.native.prevent>
  <el-form-item>
    <el-select
      v-model="queryForm.status"
      placeholder="请选择开票状态"
      clearable
    >
      <el-option value="待审核" />
      <el-option value="审核通过" />
      <!-- TODO 和后端确认具体状态名称 -->
      <el-option value="已驳回" />
    </el-select>
  </el-form-item>
  <el-form-item>
    <el-button icon="el-icon-search" type="primary" @click="search">
      查询
    </el-button>
  </el-form-item>
</el-form>
```

**Comment by Gruntfuggly** [comment]
What is the language/type of the file? The extension uses a library to detect comment start/end based on the type of the file, so if it's not one that is supported it won't be able to remove them.

If you can tell the the type though - probably just the extension, I might be able to override it.

**Comment by Gruntfuggly** [comment]
Ah hang on - I didn't look close enough! It's a ".vue" file. I assume it should be treated like HTML? I'll see if I can make a change to support it.

**Comment by Gruntfuggly** [comment]
Should now work in the latest version (0.0.199)

**Comment by chanjsq** [comment]
Yes, we can treat the `<template>` section part as HTML. You are very nice and efficiency! I tested it again, it works! Thank you very much, again! 👍
