### ISSUE TITLE
adding a basic list to the tag group

### ISSUE THREAD

**Issue by jackalman1408** [Gruntfuggly/todo-tree#448]
Good Day! on first downloading this extension in VSCode, I thought it broken because it did not find my comment for #ToDo, I now realize why this is but I figured it would result in a lot of confusion and annoyance for new users! to that extent I wrote up a small list that I figured you might have a use for! simply add this to your "todo-tree.general.tagGroups" zone:

"FIXME": [
            "FIXME",
            "FIXIT",
            "FIX",
            "fix",
            "Fix",
            "FixME",
            "FIXMe",
            "FixIt",
            "Fixit"
        ],
        "TODO": [
            "ToDo",
            "todo",
            "toDo",
            "To_Do",
            "to_do",
            "to_Do"
        ]

this should also get new users of your brilliant extension up and running a lot faster too!

**Comment by Gruntfuggly** [comment]
You don't actually need to add all those - there is a setting `todo-tree.regex.regexCaseSensitive` you can set to false. Then you would only need 
```
"FIXME": [
"FIXME",
"FIXIT",
"FIX",
],
"TODO": [
"TODO",
"TO_DO"
]

The reason loads of things are not added by default is that people are very particular about what they like and it was always easier to allow people to add what they want rather than have to explain ways to remove stuff that they didn't.

There have been loads of requests to update the default regex and every time I have done it, it causes problems for people who use the default, so I don't make updates to it unless I really have to now (The last time I convinced myself than update wouldn't cause any problems I had to revert it the next day. 🙄 ).

**Comment by jackalman1408** [comment]
my word I'm sorry I missed that! ahh ya I can only imagine how fussy people can be! thanks for getting back to me so fast about it though!

Sincerely
Connor Musto

________________________________

**Comment by Gruntfuggly** [comment]
No problem. 🙂
