### ISSUE TITLE
"Cannot read property 'filter' of undefined" at todo-tree.regex.subTagRegex

### ISSUE THREAD

**Issue by shaedrich** [Gruntfuggly/todo-tree#449]
When I define `^:\s(.*)` at `todo-tree.regex.subTagRegex` I get the following error message:
> Cannot read property 'filter' of undefined

Am I doing it wrong?

**Comment by Gruntfuggly** [comment]
Could you post all your todo settings please - that setting on it's own works fine for me. I think something else is causing the issue.

**Comment by shaedrich** [comment]
Sure

````json
{
    "todo-tree.tree.showScanModeButton": false,
    "todo-tree.general.statusBar": "current file",
    "todo-tree.general.tagGroups": {
        "TODO": [
            "@todo"
        ]
    },
    "todo-tree.general.tags": [
        "BUG",
        "HACK",
        "FIXME",
        "TODO",
        "XXX",
        "@todo"
    ]
}
```

**Comment by Gruntfuggly** [comment]
Is that really all your settings - the subtag regex isn't there?

**Comment by Gruntfuggly** [comment]
Which version of the extension are you using?

**Comment by Gruntfuggly** [comment]
I'm going to close this, as I can't do anything without seeing your settings. Feel free to re-open.
