### ISSUE TITLE
[Feature request] Group by identical text

### ISSUE THREAD

**Issue by shaedrich** [Gruntfuggly/todo-tree#450]
Sometimes you have the same todo in multiple places. It would be nice to see in which files you have to do a certain task. 

Relates to: #419

**Comment by Gruntfuggly** [comment]
Have a look at the `todo-tree.regex.subTagRegex` setting (https://github.com/Gruntfuggly/todo-tree#configuration). It lets you extract more from the TODO. For example, setting it to `^\s*\((.*)\)` will capture anything after the tag in brackets. You can the use `Group by Sub Tag` from the context menu in the tree.

**Comment by shaedrich** [comment]
I tried that and enabled the grouping button but it doesn't show up. Am I doing something wrong or do I just looked in the wrong place (tree view context menu as you said)?

**Comment by Gruntfuggly** [comment]
If the option doesn't appear in the context menu, it's because it hasn't found any sub tags.

Could you post your settings and an example of what you are expecting it to find, so I can check it?

**Comment by Gruntfuggly** [comment]
I'm going to close this, but please feel free to re-open if you have any more information.
