### ISSUE TITLE
Tags are being highlighted where there is no leading comment.

### ISSUE THREAD

**Issue by Gruntfuggly** [Gruntfuggly/todo-tree#454]

**Comment by Gruntfuggly** [comment]
<img width="854" alt="Screenshot 2021-03-07 at 3 27 53 AM" src="https://user-images.githubusercontent.com/24704695/110221976-2bb06580-7ef5-11eb-9b87-c4b39a76e40a.png">

**Comment by Gruntfuggly** [comment]
Seems to be present from at least 0.0.183

**Comment by Gruntfuggly** [comment]
Ah OK - this behaviour is correct. The default regex matches the start of the line. If you don't want this, change the regex from
```
((//|#|<!--|;|/\\*|^)\\s*($TAGS)|^\\s*- \\[ \\])
```
to
```
((//|#|<!--|;|/\\*)\\s*($TAGS)|^\\s*- \\[ \\])
```

**Comment by deekshithanand** [comment]
Hi @Gruntfuggly , sry for the delayed response! I tried your suggestion. But for some reason it doesnt work. The whole todo list is empty and all highlight is gone. Even when I reverted back to previous regex, it failed. I had to reset the setting (remove that property from settings.json) to make it work. Seems like internally its not considering the modified regex. Not sure though. Let me know if you need anything

**Comment by deekshithanand** [comment]
And behavior-wise, I feel it shouldn't be highlighting the non commented tags. Let's say for some crazy reason, if someone has a constant by the name TODO, it will be highlighted within the code, which simply doesn't make any sense!

**Comment by deekshithanand** [comment]
Ah it worked. I replaced that string directly into settings.json!  Now it looks something like this: (Earlier it was all escaped chars!)

  `  "todo-tree.regex.regex": "((//|#|<!--|;|/\\*)\\s*($TAGS)|^\\s*- \\[ \\])"`

Looks like vs code settings UI automatically escapes the input given by the user. (Maybe need to mention this on the intro page of the extension!) Thanks for the great extension. Out of all, I found this one to be fitting into my use-case! Thanks, @Gruntfuggly!

**Comment by Gruntfuggly** [comment]
Yes - it's quite a pain because I have to guess how people are using the settings most of the time, or repeat everything twice (for example, in the wiki). 🙄 

BTW, even with the original (default) regex it will only highlight tags when they are at the start of the line. If you put any other characters (that aren't included in the regex) it won't get highlighted.

Are you OK for me to close this now?

**Comment by deekshithanand** [comment]
yeap okay.. all is good u can close...
