### ISSUE TITLE
How to set font styles?

### ISSUE THREAD

**Issue by smlombardi** [Gruntfuggly/todo-tree#455]
The documentation says:

> fontWeight, fontStyle, textDecoration - can be used to style the highlight with standard CSS values.

But when I go to setting.json I do not see those properties hinted.  Do they go beneath another property?  How are these font attributes set?

**Comment by smlombardi** [comment]
Never mind, I see they are properties per tag.

**Comment by larskuerten** [comment]
> Never mind, I see they are properties per tag.

what you mean? I am trying to make it work for dart/flutter
