### ISSUE TITLE
can it be added as an "accordion tab" to the VS code explorer?

### ISSUE THREAD

**Issue by serapath** [Gruntfuggly/todo-tree#456]
Not sure how this is called, but when i open the explorer, it has a bunch of tabs that i can toggle/untoggle clicking the "..." on top. It currently offers me:
1. open files
2. folders
3. outline
4. timeline
5. npm scripts
6. favorites (which comes from an installed extension)

It would be great if it could also have such an "accordion tab" for **TODO Tree**
* maybe with a summary counter of TODOS (total) and in (currently focused file) depends on whats possible :-)

**Comment by Gruntfuggly** [comment]
Yes, just drag it from the activity bar into the explorer pane.
