### ISSUE TITLE
Fails to start on MacOS

### ISSUE THREAD

**Issue by georgefst** [Gruntfuggly/todo-tree#457]
I've been happily using this extension for years on my Linux machines. But in MacOS Big Sur, it completely blocks the editor from starting up properly - all other extensions hang unless I disable `todo-tree`.

I can't seem to find any useful logs, so I'm at a bit of a loss for how to start debugging this.

**Comment by Gruntfuggly** [comment]
Can you post your todo tree settings please?

You could try setting `"todo-tree.tree.scanAtStartup": false` and seeing if that makes any difference?

**Comment by Gruntfuggly** [comment]
The only change to the default regex was in November last year, but that caused issues so I reverted it back the next day. Before that it hadn't changed since September 2019?
