### ISSUE TITLE
Todo Tree doesn't find numbered to-do lists in my files.

### ISSUE THREAD

**Issue by absconditus87** [Gruntfuggly/todo-tree#458]
Hi,

It works great for to-do lists that are not numbered but doesn't work for numbered lists for me. Is there any setting I can change to make it detect numbered to-do lists?

Thank you.

**Comment by Gruntfuggly** [comment]
Pleas can you give me an example of what you want it to find?

**Comment by absconditus87** [comment]
Thank you for replying.

I installed the Todo Tree extension for VSCode and ran it on markdown files. It finds to-do lists without numbers:

- [ ] todo1
- [ ] todo 2
- [ ] todo 3

but not numbered lists:

1. [ ] todo1
2. [ ] todo2
3. [ ] todo3

**Comment by Gruntfuggly** [comment]
There is a mistake in what I posted, sorry. Try
```
"todo-tree.regex.regex": "((//|#|<!--|;|/\\*|^)\\s*($TAGS)|^\\s*(-|\\d+\\.) \\[ \\])"
```
I am assuming you are changing the settings in `settings.json`. If you're changing them in the setting GUI, then you don't need the extra backslashes, e.g. set it to:
`((//|#|<!--|;|/\*|^)\s*($TAGS)|^\s*(-|\d+\.) \[ \])`

**Comment by Gruntfuggly** [comment]
The important part is `(-|\d+\.)` which tells it to match either a dash (`-`) or one or more digits (`\d+`).

**Comment by absconditus87** [comment]
> 
> 
> There is a mistake in what I posted, sorry. Try
> 
> ```
> "todo-tree.regex.regex": "((//|#|<!--|;|/\\*|^)\\s*($TAGS)|^\\s*(-|\\d+\\.) \\[ \\])"
> ```
> 
> I am assuming you are changing the settings in `settings.json`. If you're changing them in the setting GUI, then you don't need the extra backslashes, e.g. set it to:
> `((//|#|<!--|;|/\*|^)\s*($TAGS)|^\s*(-|\d+\.) \[ \])`

Works now :) How can I find the the

**Comment by Gruntfuggly** [comment]
There is a button at the top right that looks  like a document with a file. If you click it it swaps to the `settings.json` file which was the old way to modify settings. It's also the only way to modify some settings which are too complex for the GUI.

This issue has inspired me to improve the handling of markdown TODOs. In the next release there will be an option to update the regex automatically, but basically if you change the settings as follows:
```
"todo-tree.regex.regex": "(//|#|<!--|;|/\\*|^|^\\s*(-|\\d+.))\\s*($TAGS)"
"todo-tree.general.tags": [
        "BUG",
        "HACK",
        "FIXME",
        "TODO",
        "XXX",
        "[ ]",
        "[x]"
    ],
```

It will work a lot nicer - you can have custom highlights for the "done" and "not done" TODOs and it also works better with the counters in the status bar, for example, and when grouping by tag.

**Comment by Gruntfuggly** [comment]
Are you OK for me to close this issue now?

**Comment by absconditus87** [comment]
> 
> 
> Are you OK for me to close this issue now?

Yes. Thanks a lot for your help. Looking forward to the next update :)
