### ISSUE TITLE
Feature: Synchronize todo-tree and editor

### ISSUE THREAD

**Issue by schlundus** [Gruntfuggly/todo-tree#46]
Is it possible to focus and highlight the currently opened and focus file in the todotree just like the normal fileexplorer does...?

**Comment by Gruntfuggly** [comment]
I think so.

**Comment by Gruntfuggly** [comment]
Latest version should now sync the current file.

**Comment by schlundus** [comment]
Hm, it works if the tree isn't group by tag, if it's grouped by tag, nothing happens

**Comment by Gruntfuggly** [comment]
It's not really possible if you are gouped by tag because the file could be at multiple places in the tree if different tags are used...

**Comment by Gruntfuggly** [comment]
I did think about the possibility of syncing the tree if you click on the todo in the file, or possibly finding the nearest todo in the file and syncing to that, but it might make the tree jump around quite a bit as you moved through the file.

I'm open to suggestions...
