### ISSUE TITLE
Highlighting fails if "Split Editor Right" is used

### ISSUE THREAD

**Issue by DEberhardt** [Gruntfuggly/todo-tree#462]
Hello,

splitting the editor will result in interesting behaviour:
The highlighting of Tags only works on the new split window.
![image](https://user-images.githubusercontent.com/44290340/110945954-40965a00-8336-11eb-96f5-71fd3537a4ae.png)

### Steps to reproduce

1. Open any file with tags
2. Click "Split Editor right"

### Workaround
Close and re-open file
Reload window

### Caveat
This affects the unfocused side.
Closing and re-opening the file will restore functionality (or opening any other file in that side) 
Opening a different file will retain the highlighting in the other file, but then changing focus removes highlighting again:
![image](https://user-images.githubusercontent.com/44290340/110946405-bac6de80-8336-11eb-9700-d364b240acd0.png)

![image](https://user-images.githubusercontent.com/44290340/110946422-c0bcbf80-8336-11eb-889b-1a48ac09c0e1.png)

**Comment by Gruntfuggly** [comment]
Should now work properly in the latest version (0.0.205)

**Comment by DEberhardt** [comment]
Yes, can confirm, works as intended! Cheers!
