### ISSUE TITLE
option to have explorer section minimized by default

### ISSUE THREAD

**Issue by j9108c** [Gruntfuggly/todo-tree#463]
can you please add the option to have explorer section minimized by default?

**Comment by Gruntfuggly** [comment]
Unfortunately it can't be an option, it can only be set as a default on installation. It would also only apply if the view is created in the explorer pane in the first place. When it is dragged into the explorer pane, VSCode automatically expands it.

However, if you collapse it, it should remember that when the workspace is reopened.

Its a shame there isn't any API to collapse or expand the view.

**Comment by Gruntfuggly** [comment]
I'm going to close this, but I keep an eye on any changes to the API, so the Code team add the functionality to allow this I will add it to the extension.
