### ISSUE TITLE
Warning about HTML colours

### ISSUE THREAD

**Issue by emanuelenardi** [Gruntfuggly/todo-tree#464]
This warning is displayed about the HTML colours as being invalid

![image](https://user-images.githubusercontent.com/15109661/111180720-988ac600-85ad-11eb-8704-c63746d426bc.png)

but they are correctly displayed in the editor

![image](https://user-images.githubusercontent.com/15109661/111180803-a8a2a580-85ad-11eb-8a04-a4baf9c36aac.png)

**Comment by Gruntfuggly** [comment]
It's because the name check is case sensitive and it expects them to be all lower case at the moment. 

You can get rid of the warning by changing them to lowercase - I'll make the check case insensitive in the next release.

**Comment by emanuelenardi** [comment]
Thanks for the quick reply!

**Comment by Gruntfuggly** [comment]
Should no longer generate the warning in version 0.0.206
