### ISSUE TITLE
New extension tab text is a bit wide

### ISSUE THREAD

**Issue by abreis** [Gruntfuggly/todo-tree#465]
<img width="523" alt="todos" src="https://user-images.githubusercontent.com/95046/111187877-5ca33100-85ac-11eb-81c4-e4337170688a.png">

The image shows the previous tab label (green) and the new one (red).

It's so wide that VSCode will sometimes hide it under a `...`:

<img width="383" alt="image" src="https://user-images.githubusercontent.com/95046/111188216-b99ee700-85ac-11eb-9f64-b2ad4b5fe3d5.png">

Please consider reverting back to a simple `TODO` string.  
Thanks!

**Comment by Gruntfuggly** [comment]
Unfortunately it's not as easy as it looks because the view isn't created in the explorer pane anymore.

I'll try some experiments - I agree it doesn't look view nice.

**Comment by abreis** [comment]
I see, so it was a change on the VSCode side. Labels on other extensions also seem to be formatted `{name}: {panel}` now.

Renaming the extension internally seems to be possible ('GitHub Pull Requests' e.g. presents itself as just 'GitHub'), but `TODOS: TODOS` isn't great either. Perhaps `TODOS: OPEN`, or `TODOS: LIST`?

Thanks for looking into this!

**Comment by Gruntfuggly** [comment]
OK - so, I've changed it so it shows either
 "TODOS: TREE" 
 "TODOS: FLAT" 
 "TODOS: TAGS" 
depending on the view setting.

Looks much better to me and adds a bit more useful information.

**Comment by Gruntfuggly** [comment]
Please try version 0.0.206 and let me know what you think

**Comment by abreis** [comment]
Looks great to me. Thank you!
