### ISSUE TITLE
init(); causes small bug

### ISSUE THREAD

**Issue by 99toxic** [Gruntfuggly/todo-tree#468]
I noticed when you leave a todo comment after a init(); in JavaScript it causes a small bug in the tree.
![Capture](https://user-images.githubusercontent.com/11801081/111252843-63e83000-85e8-11eb-96c4-30753e207817.PNG)

**Comment by Gruntfuggly** [comment]
I think that is because it is looking for the comment at the start of the line. Can you try removing `|^` from the regex by changing it from: 
```
"((//|#|<!--|;|/\\*|^)\\s*($TAGS)|^\\s*- \\[ \\])",
```
to 
```
"((//|#|<!--|;|/\\*)\\s*($TAGS)|^\\s*- \\[ \\])",
```
If you modify it in the settings GUI, change it from 
```
((//|#|<!--|;|/\*|^)\s*($TAGS)|^\s*- \[ \])",
```
to
```
"((//|#|<!--|;|/\*)\s*($TAGS)|^\s*- \[ \])",
```
That's assuming you're still using the default.

**Comment by 99toxic** [comment]
that made it worst haha.

**Comment by 99toxic** [comment]
I am noticing that it's always after a ; and any whitespace.

**Comment by 99toxic** [comment]
Oh wait.. I got it. you were right. I just deleted the |; and had to give it more time to load.
