### ISSUE TITLE
Add option to define the ruler lane opacity per tag

### ISSUE THREAD

**Issue by redactedscribe** [Gruntfuggly/todo-tree#470]
Currently, I find it difficult to see the markings in the ruler lane which indicate a todo tag's position in the file.

For example, when hovering (the markings are left-aligned):
![ruler_lane_hover](https://user-images.githubusercontent.com/25013746/111359436-2d67ef00-8694-11eb-8156-7d9b2bf87dc3.png)

When not hovering:
![ruler_lane_no_hover](https://user-images.githubusercontent.com/25013746/111359428-2b059500-8694-11eb-8450-3cf59dc4f75f.png)

In contrast to the other, brighter markings, Todo Tree's markings do not stand out. This is due to a low `"opacity":` value for each tag, which is necessary so that the `whole-line` highlighted lines are not overly distracting when reading the code. The sacrifice is that opacity is linked to the ruler lane opacity. I initially thought the extension had a bug, and it was only on closer inspection did I realize that the blue `TODO:` tags were just very faintly visible.

Would it be possible to allow a `"rulerLaneOpacity":` in addition to the currently available `"opacity":`?

If no `"rulerLaneOpacity"` is set, `"opacity":`'s value should be used.

An alternative approach could be to make the markers use the tag's foreground color instead of its background color.

Thank you.

**Comment by Gruntfuggly** [comment]
You can set the opacity if you use an RGBA value for the colour, e.g.
`"rulerColour": "#ff000080"`

However, it would be nice to be able to specify it for all tags.

**Comment by Gruntfuggly** [comment]
Please try version 0.0.206 and let me know if it works

**Comment by redactedscribe** [comment]
I'll test it tomorrow and let you know.
