### ISSUE TITLE
Only ever show one gutter icon per comment?

### ISSUE THREAD

**Issue by redactedscribe** [Gruntfuggly/todo-tree#474]
With word wrap enabled, the types `text-and-comment`, `text`, `line`, and `whole-line` all show multiple icons, one per "line" of the word wrap.

Ideally it could be customized so that only ever one icon shows regardless of the wrapping, as happens when set to `tag` for example. This would help reduce some visual noise.

![noise](https://user-images.githubusercontent.com/25013746/111717577-f8f55e00-8860-11eb-9bbc-7e625ddba68a.png)

Thanks.

**Comment by Gruntfuggly** [comment]
Sorry, but there is no control over it. Unfortunately, the gutter icon part of the API is quite lacking. It looks like it just shows the icon on every line that is highlighted.
