### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by DEberhardt** [Gruntfuggly/todo-tree#475]
Issue Type: <b>Feature Request</b>

Thank you for enabling this feature! May it have to be used as little as possible for bugs :)
Thank you for this wonderful extension without which I will probably have lost the will to code. Tracking things is now easy and fun!

(no issue, just wanted to use this function and convey my thanks! - Cheers) 

Extension version: 0.0.206
VS Code version: Code 1.54.2 (fd6f3bce6709b121a895d042d343d71f317d74e7, 2021-03-11T00:56:19.848Z)
OS version: Windows_NT x64 10.0.19042

**Comment by Gruntfuggly** [comment]
It's working 🙂 

Thanks for the kind words - if you have a minute, a positive review on the marketplace would be great!

**Comment by DEberhardt** [comment]
But of course :)

**Comment by Gruntfuggly** [comment]
Thanks!
