### ISSUE TITLE
Comment in PS code "<#...#> messes with Display in Tree

### ISSUE THREAD

**Issue by DEberhardt** [Gruntfuggly/todo-tree#477]
Issue Type: <b>Bug</b>

Hello,

found something weird:
![image](https://user-images.githubusercontent.com/44290340/111877294-9607e200-899a-11eb-9aed-93f401e5a1fa.png)

When using Comment blocks in PowerShell, the enumeration of ToDos works fine, but once clicked it expands and messes up the display:
![image](https://user-images.githubusercontent.com/44290340/111877299-9acc9600-899a-11eb-9df9-8bdcc7831f70.png)

the Comment in question:
![image](https://user-images.githubusercontent.com/44290340/111877305-a5872b00-899a-11eb-8c53-6220f200756f.png)

happens for multiple comments, prior and afterwards it is displayed fine, just in a file with a Comment Block this is "misinterpreted".
I have a feeling the confusion is due to the Regex not excluding in the "<#"?

Here are my settings
```json
    "todo-tree.filtering.useBuiltInExcludes": "file and search excludes",
    "todo-tree.general.tagGroups": {
        "BODGE": [
            "BODGE",
            "HACK"
        ],
        "DOC": [
            "DOC",
            "WRITE",
            "NOTE"
        ],
        "FIXME": [
            "FIXME",
            "FIXIT",
            "FIX"
        ],
        "TEST": [
            "VALIDATE",
            "TEST"
        ]
    },
    "todo-tree.general.tags": [
        "BUG",
        "TODO",
        "BODGE",
        "HACK",
        "FIXME",
        "FIXIT",
        "FIX",
        "DOC",
        "WRITE",
        "NOTE",
        "CHECK",
        "TEST",
        "VALIDATE",
        "IMPROVE",
        "[ ]",
        "[x]"
    ],
    "todo-tree.highlights.customHighlight": {
        "BODGE": {
            "background": "magenta",
            "foreground": "white",
            "gutterIcon": true,
            "icon": "tools",
            "iconColour": "magenta"
        },
        "BUG": {
            "background": "red",
            "foreground": "white",
            "gutterIcon": true,
            "iconColour": "red",
            "type": "line"
        },
        "CHECK": {
            "background": "blue",
            "foreground": "white",
            "gutterIcon": true,
            "icon": "pulse",
            "iconColour": "blue"
        },
        "DOC": {
            "background": "darkgrey",
            "foreground": "black",
            "gutterIcon": true,
            "icon": "note",
            "iconColour": "grey"
        },
        "[ ]": {
            "background": "white",
            "foreground": "black",
            "gutterIcon": false,
            "icon": "book",
            "iconColour": "white",
            "type": "tag"
        },
        "[x]": {
            "background": "darkgrey",
            "foreground": "black",
            "gutterIcon": false,
            "icon": "repo",
            "iconColour": "grey",
            "type": "tag"
        },
        "FIXME": {
            "background": "orange",
            "foreground": "black",
            "gutterIcon": true,
            "iconColour": "orange"
        },
        "IMPROVE": {
            "background": "lightblue",
            "foreground": "black",
            "icon": "sync",
            "iconColour": "lightblue"
        },
        "TEST": {
            "background": "cyan",
            "foreground": "black",
            "gutterIcon": true,
            "icon": "beaker",
            "iconColour": "cyan"
        },
        "TODO": {
            "background": "green",
            "foreground": "white",
            "gutterIcon": true,
            "icon": "clippy",
            "iconColour": "green"
        }
    },
    "todo-tree.highlights.defaultHighlight": {
        "icon": "location",
        "iconColour": "yellow",
        "type": "text"
    },
    "todo-tree.tree.hideIconsWhenGroupedByTag": true,
    "todo-tree.tree.showScanModeButton": false,
```

Thanks,
David

Extension version: 0.0.207
VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.87GB (16.80GB free)|
|Process Argv|--crash-reporter-id efc3d77d-4b9d-44d6-894f-bd5aee3260eb|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554:30277037
pythontbcf:30265426
vscoresta800cf:30276762
vspre833:30267464
vsfjg287:30275553
vshan820:30276952

```

</details>

**Comment by Gruntfuggly** [comment]
Is this the same as #476 ? I think I broke something in the last release - I've got a fix though. Just testing it.

**Comment by DEberhardt** [comment]
Potentially, just added screenshots to illustrate where I experienced it.

**Comment by Gruntfuggly** [comment]
Yes - looks like the same thing.

**Comment by Gruntfuggly** [comment]
I've reverted the change I made as I don't think it was even required. Please let me know if 0.0.208 works properly.

**Comment by DEberhardt** [comment]
Resolved :)
