### ISSUE TITLE
`rulerColour` doesn't support theme colors

### ISSUE THREAD

**Issue by redactedscribe** [Gruntfuggly/todo-tree#479]
`rulerColour` doesn't support theme colors.

(Opened an issue for it to be tracked. [Original comment](https://github.com/Gruntfuggly/todo-tree/issues/472#issuecomment-802222333).)

Todo Tree v0.0.206

**Comment by Gruntfuggly** [comment]
This should have been fixed in 0.0.207. (although 0.0.207 had other issues). Are you still seeing it in 0.0.208?

**Comment by redactedscribe** [comment]
I wasn't aware that a newer version had been released. I had been checking, but it appears the issue is that the Open VSX repo hasn't been updated. I just tested the v0.0.208 .vsix from the VS Marketplace and the bug is indeed squashed.

**Comment by Gruntfuggly** [comment]
Ah - fair point. I haven't release to Open VSX yet.

**Comment by redactedscribe** [comment]
I've pointed my flavor of VS Code to the VS Marketplace now, so I shouldn't have a problem in the long run. [1](https://github.com/eclipse/openvsx/wiki/Using-Open-VSX-in-VS-Code), [2](https://github.com/microsoft/vscode/commit/51fe52b6184202c9ab07c4743ad192639f17f2b4#diff-285888428ebaab4e7985b695829cc9e47f98d2857505070ccacae3432b7b11dc).
