### ISSUE TITLE
Feature: Ability to, temporarily, add an includedGlobs

### ISSUE THREAD

**Issue by kkckkc** [Gruntfuggly/todo-tree#482]
Looking at the source code it seems there is a capability to filter the tree based on an arbitrary list of globs in the `workspaceState`. However, it seems the only way to affect this is through the "Only Show This Folder" or "Only Show This Folder And Subfolders". 

My code-base is very large and I have a need to filter on for instance `**/test/*` to only show test code, or `**/integration-test/*` etc. I know I can configure these statically, but I'd like a command to set these filters. Using the "Only Show This Folder" capability is not viable when you have hundreds and folders and thousands of files.

So, I envison adding something like (I haven't tested this, since I've never worked with VSCode plugins before)

```
context.subscriptions.push( vscode.commands.registerCommand( 'todo-tree.showOnlyThisFolderPattern', function()
    {
        vscode.window.showInputBox( { prompt: "Filter tree" } ).then(
            function( term )
                {
                    context.workspaceState.update( 'includeGlobs', [ term ] );
                    rebuild();
                    dumpFolderFilter();
                } );
    } ) );
```

**Comment by Gruntfuggly** [comment]
The include/exclude globs can be modified through the settings GUI (Todo-tree > Filtering).

Adding it this way would just be doing the same thing. 

I could add an option to the context menu to open the settings GUI at those settings?

**Comment by kkckkc** [comment]
Yes, I understand I can change it through the settings window - but it’s not very convenient of efficient. A context menu to the settings GUI will not really make it any easier.

I’m looking for a quick way to change back and forth between different filters applying to the path of the files. It’s very helpful if you have thousands of files and hundreds of TODOs.

In a way the existing filter function is doing what I want, except that it filters based on the contents of the TODO, rather than the path of the file.

Let me create a PR in the coming weeks to show what I want.

**Comment by Gruntfuggly** [comment]
OK, so in the same way as you can currently show the current globs for removal, you'd like to be able to add one via the same mechanism? I can see that would be nicer than having to visit the settings GUI, although under the hood it would do the same thing.

What about allowing globs to be temporarily disabled via the dropdown? The Hide/Show this folder was always intended to be a simple way to quickly filter the view, but it's a bit too simple in some cases. Setting the globs through the preferences is going a bit too far the other way - these are intended to be more permanent.

I'll look into providing an extended globs control dialog - it might be possible to list them and provide 'remove' 'disable' and 'enable' buttons along with a button to add new ones.

**Comment by kkckkc** [comment]
I created https://github.com/Gruntfuggly/todo-tree/pull/484 to show what I want. This PR works perfectly fine - let me know if there are any adjustments needed

**Comment by kkckkc** [comment]
I think we can close this now. Thanks for merging the PR so quickly
