### ISSUE TITLE
Wrong icon size/weight when set manually

### ISSUE THREAD

**Issue by Gliptal** [Gruntfuggly/todo-tree#486]
The default icons the extension provides are crisp-looking and fit nicely in the available space:

![Code_Mg3MehdJG4](https://user-images.githubusercontent.com/3907646/112868238-1e356800-90bc-11eb-8cb9-12c97a73152b.png)

Setting that same icon (` "icon": "check-circle",` for example) results in a larger (or weightier) icon that feels blurrier and doesn't entirely fit in the available space (notice the lower portion of the circle is cut).

![Code_uB6hiVGlhp](https://user-images.githubusercontent.com/3907646/112868521-6fddf280-90bc-11eb-9be0-89f6c9d06120.png)

The same behaviour can be seen in the gutter.

**Comment by Gruntfuggly** [comment]
The `check-circle` icon is from the codicons (or octicons), and is provided by vscode, so I have no control over it unfortunately. The default is an old SVG I found a long time ago.

**Comment by Gliptal** [comment]
Ah I was under the impression they were the same icon, just loaded differently. Thanks for the quick explanation!
