### ISSUE TITLE
Highlight of selected text within TODO item

### ISSUE THREAD

**Issue by moymike** [Gruntfuggly/todo-tree#488]
I'm annotating tasks in a large project with TODO tag types, and just ran into an issue with editing and highlighting.  If I select text within the TODO text, I have no visual that shows the text I have selected.   The background/foreground remain the same as the unselected text.

It may be a setting I am missing, or something about the Theme I am using.

**Comment by Gruntfuggly** [comment]
You can specify alpha values or opacity for the highlight colours, if you use hex or RGB values.

I don't know what your current settings are, but you can try something like 
```
"todo-tree.highlights.defaultHighlight": 
{
    "background":"#ff000080"
}
```
or
```
"todo-tree.highlights.defaultHighlight": 
{
    "background":"#ff0000",
    "opacity": 0.5
}
```
should work.

**Comment by moymike** [comment]
Within my settings, I checked, and this what I currently have:
```
	"todo-tree.general.tags": ["TODO", "FIXME", "INFO"],
	"todo-tree.highlights.customHighlight": {
		"INFO": {
			"background": "yellow",
			"foreground": "black",
			"icon": "info",
			"iconColour": "yellow"
		},
	},
	"todo-tree.highlights.defaultHighlight": {
		"background": "white",
		"foreground": "red",
		"icon": "file-directory",
		"iconColour": "navy",
		"opacity": 60,
		"type": "text"
	}
```
Based on my settings, all the text in the #INFO line below is highlighted in yellow with black text.  When I select text within the highlighted text, nothing visually changes.  I tried changing themes and got the same result.

```
#INFO description goes here, shows with yellow background and black text
```

**Comment by Gruntfuggly** [comment]
You'll need to use HEX or RGB values to make the opacity work, so instead of "red", use "#ff0000" and for "yellow", use "#ffff00". With my colour scheme, an opacity of 60 allowed me to see the selection, but it's still quite faint. Dropping it to 50 worked OK.

**Comment by Gruntfuggly** [comment]
Did you manage to get it to work?

**Comment by moymike** [comment]
Yes

setting "opacity": 50
did the trick

**Comment by Cyber1000** [comment]
@Gruntfuggly Sorry for hijacking/reopening this thread but it best fits here - if I do the following it doesn't work:
```
        "TODO important": {
            "icon": "alert",
            "iconColour": "red",
            "type": "text",
            "foreground": "#FF4444",
            "background": "peekViewResult.background",
            "opacity": 50
        } 
```

I needed to change background to something like #222222, but peekViewResult.background would be my favourite setting. Any chance to get this working? I'm having the same issue as @moymike. Thanks for this extension, using TODOs heavily in my code, this is nearly the same feeeling as in Rider/VisualStudio.

**Comment by Gruntfuggly** [comment]
You can't used opacity with theme colours - there's no way to get the RGB values, so it can't add the opacity to it. You could try modifying the 'peekViewResult.background' to have a similar RGB with opacity and then it might apply too? But that would obviously change it for the peekView too. It that does work though, you might be able to find a theme colour which you don't personally use anywhere and modify that instead?

**Comment by Gruntfuggly** [comment]
Alternatively use a colour picker to find out exactly with the RGB values are for the peekViewResult.background and then specify them manually (with the opacity).
