### ISSUE TITLE
Can't add TODOs Tree view to Explorer Activity

### ISSUE THREAD

**Issue by kangzoel** [Gruntfuggly/todo-tree#489]
Is this the new behavior of the extension or VSCode? I can no longer add the todos tree view in my explorer activity. It's moved to it's own activity called TODOs instead.

![image](https://user-images.githubusercontent.com/48172520/113754758-c0e38b80-9739-11eb-9bfe-1e545534c1fb.png)

**Versions:**
VSCode: v1.55.0
Todo Tree: v0.0.209

**Comment by Gruntfuggly** [comment]
You can drag it into the explorer pane.

There used to be two views which made things over complicated - now that Code allows views to be moved around, it is simpler to have one which you can drag to wherever you want.

**Comment by kangzoel** [comment]
Ah, I see. Thanks for your help!
