### ISSUE TITLE
Feature Request: Show up the occurrences of `System.NotImplementedException`

### ISSUE THREAD

**Issue by hwndmaster** [Gruntfuggly/todo-tree#49]
Scenario:
During bootstrapping of the classes/services I use automatic generator of methods with `throw new System.NotImplementedException();` in the body, mainly focusing on a general workflow. When I go to details I have to keep track of methods which are still without implementation by myself.

Suggestion:
Show up all occurrences of `System.NotImplementedException` in the Todo Tree.

Thanks.

**Comment by Gruntfuggly** [comment]
Have you tried changing the configuration?

You could something like try:
`"todo-tree.regex": "((//|#|<!--|;|/\\*|^)\\s*($TAGS)|^\\s*- \\[ \\])|throw new System\\.NotImplementedException\\(\\)"`

It won't work with the grouping, but they will be shown in the tree.

**Comment by hwndmaster** [comment]
@Gruntfuggly thanks dude! For some reason I missed that option. It works like a charm!
