### ISSUE TITLE
After update to 0.0.210 I can't open the related file anymore ...

### ISSUE THREAD

**Issue by Alpengreis** [Gruntfuggly/todo-tree#491]
Hello

After update to 0.0.210 I can't open the related file anymore ...

After click to an ToDo entry, like here:
![todo_tree_prob_1a](https://user-images.githubusercontent.com/11355601/114106280-b0b0e500-98ce-11eb-9b37-da702a6ebc49.png)
it shows there the correct path. However, I receive always an error like the following:
![todo_tree_prob_1b](https://user-images.githubusercontent.com/11355601/114106320-ccb48680-98ce-11eb-9740-f91074097d4c.png)

I switched back to v0.0.209 for testing - and there it works without any problems.

Can you fix this, please?

Thank you and greetings

**Comment by 0wzZZzz6** [comment]
Same goes for me.

**Comment by ghostlhq** [comment]
Same goes for me.

**Comment by gandalivs** [comment]
yes please fix this

**Comment by Gruntfuggly** [comment]
Looks like I forgot to test on Windows 🙁 Sorry.

**Comment by jhnyang** [comment]
same problem. please fix it! thanks for useful extension

**Comment by Gruntfuggly** [comment]
Could somebody please test this for me? I don't have easy access to a Windows dev environment.
[todo-tree-0.0.211-beta.0.vsix.zip](https://github.com/Gruntfuggly/todo-tree/files/6284601/todo-tree-0.0.211-beta.0.vsix.zip)

**Comment by 0wzZZzz6** [comment]
> Could somebody please test this for me? I don't have easy access to a Windows dev environment.
> [todo-tree-0.0.211-beta.0.vsix.zip](https://github.com/Gruntfuggly/todo-tree/files/6284601/todo-tree-0.0.211-beta.0.vsix.zip)

I tested and working fine now. thanks

**Comment by jonas-kell** [comment]
Installing gave a Deprecation warning:

```
Installing extensions...
(node:22568) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Extension 'todo-tree-0.0.211-beta.0.vsix' was successfully installed.
```

However it installed and the File opening works again (at least for me on this one windows machine I happened to have avaliable at the moment.)
Didn't test anything else though.

**Comment by Gruntfuggly** [comment]
OK - that's great thanks. That was the only thing I changed, so I think it should be good for a new release.

I don't know where that deprecation warning comes from - the extension doesn't use `Buffer` directly - it may be one of it's dependencies.

**Comment by Gruntfuggly** [comment]
Should now be working in version 0.0.211

**Comment by ghostlhq** [comment]
> Should now be working in version 0.0.211

yep, it work now, thx

**Comment by Alpengreis** [comment]
Works again!

Thank you for the fast fix!

PS: Of course, thank you for your excellent extension!
