### ISSUE TITLE
Was there an icon in the sidebar? 

### ISSUE THREAD

**Issue by odhs** [Gruntfuggly/todo-tree#492]
Was there an icon in the sidebar? 
I remember having an icon that opened the TODO list

**Comment by Gruntfuggly** [comment]
There should be an icon in the sidebar, unless the view has been dragged into another pane.

If you click the View menu, select `Open View...` and then scroll down, you should be able to find `TODOs` in the list. Clicking it should then reveal the view wherever it is. You can drag it back to the activity bar (sidebar) if you want then icon back.

**Comment by Gruntfuggly** [comment]
Did that fix the issue for you?

**Comment by odhs** [comment]
Wow! I never thought of dragging anything above the sidebar!

Yea! My problem has been solved!
Thank you very much!
