### ISSUE TITLE
Does not work on remote file systems

### ISSUE THREAD

**Issue by anselal** [Gruntfuggly/todo-tree#494]
Hi there, great job on this extension.
I am using `SSH FS` to edit remote files and the extension does not recognise todo comments although it works as expected on local flies. Is there a setting for that or any clue how to make it work ?

**Comment by Gruntfuggly** [comment]
Does it work when the remote files are open in the editor? If not, then that should be fixable.

The workspace scanning will not work though as it relies on a file search to find the TODOs.

**Comment by anselal** [comment]
> Does it work when the remote files are open in the editor? If not, then that should be fixable.
> 
> The workspace scanning will not work though as it relies on a file search to find the TODOs.

no, it doesn't work even when the files are open in the editor

**Comment by Gruntfuggly** [comment]
It's probably because the URI scheme of the document is not file. I'll look into it.

**Comment by Gruntfuggly** [comment]
The latest version should now work with open files. It won't ever be able to search the workspace unfortunately.

Please let me know if open files now work as expected.

**Comment by anselal** [comment]
@Gruntfuggly you are a life safer. It works great. Also it displays TODOs from open remote files on the workspace !!!

**Comment by Gruntfuggly** [comment]
👍 Changing to use URIs instead of file paths makes everything a bit simpler, so it was worth doing.

**Comment by anselal** [comment]
Nice !!! Glad you could make user of this change. You can close this issue if you have to.

Thnx again !!!

Stay safe !!!!

**Comment by bjornasm** [comment]
> Does it work when the remote files are open in the editor? If not, then that should be fixable.
> 
> The workspace scanning will not work though as it relies on a file search to find the TODOs.

Is this a fact even if the extension is installed on the remote server as well?
