### ISSUE TITLE
Can I create my own tags?

### ISSUE THREAD

**Issue by toshi-ue** [Gruntfuggly/todo-tree#496]
Can I create my own tags?
Where and how should I write the settings if possible?

I added it to `.settings.json` as below, but it didn't work.

```json
  "todo-tree.general.tags": {
    "FEATURE"
  },
```

**Comment by Gruntfuggly** [comment]
Simplest way is to use the `Todo Tree: Add Tag` command, but you should also be able to use the settings like you've shown. If there is a problem, have you changed any of your other settings?

**Comment by Gruntfuggly** [comment]
I assume you got them working - is it OK to close this now?
