### ISSUE TITLE
Is possible to disable the dropdown style when the group contain only one item?

### ISSUE THREAD

**Issue by CA10C3SAR** [Gruntfuggly/todo-tree#497]
Is possible to when there's only one item inside the group, it don't display as a dropdown

This:
![image](https://user-images.githubusercontent.com/6724006/115134910-bef7b300-9fea-11eb-8bba-fbf3119abd9a.png)

To this:
![image](https://user-images.githubusercontent.com/6724006/115134925-ec446100-9fea-11eb-86a9-a620acbf2eb8.png)

**Comment by Gruntfuggly** [comment]
Can you post your settings? It shouldn't create a "TODO" item with a "TODO" inside it unless, maybe you have "Group by Tag" enabled?

**Comment by Gruntfuggly** [comment]
Do you see this in this tree title bar 
![image](https://user-images.githubusercontent.com/376658/115153729-59013f00-a06f-11eb-8a6b-12d11c85199e.png)
or this
![image](https://user-images.githubusercontent.com/376658/115153773-864ded00-a06f-11eb-85b0-1997957a38f5.png)

**Comment by CA10C3SAR** [comment]
This what?

**Comment by Gruntfuggly** [comment]
Which icon is shown in the titlebar? If it's the lower one, please click it to turn off "group by tag"

**Comment by Gruntfuggly** [comment]
Are you using github dark mode? Unfortunately the icons are black.

**Comment by CA10C3SAR** [comment]
Yes, i figured it now lol haha, i cant see your icons
Btw
![image](https://user-images.githubusercontent.com/6724006/115154177-e765c880-a04f-11eb-9154-274d366b8d09.png)

**Comment by Gruntfuggly** [comment]
OK - it's in "group by tag" mode - click the icon to switch back to normal mode.

**Comment by CA10C3SAR** [comment]
![image](https://user-images.githubusercontent.com/6724006/115154234-31e74500-a050-11eb-89b7-ca1c3ba929c6.png)
Its not possible to keep the group and only display the dropdown when there's more than one match?

**Comment by Gruntfuggly** [comment]
Not currently - I'll see what I can do

**Comment by Gruntfuggly** [comment]
I've finally got round to uploading a new version which should fix this. Please let me know if it works as expected.
