### ISSUE TITLE
Option to make status bar use tag icons instead of tag names on each count

### ISSUE THREAD

**Issue by geekley** [Gruntfuggly/todo-tree#499]
You could have an option to make the status bar of Todo Tree use the icons (same as in side view, but without color), similar to the one that shows Errors/Warnings/Info.
![image](https://user-images.githubusercontent.com/38332912/115314934-97206080-a14c-11eb-9320-edae98538dd1.png)

So, for example, if you had `"todo-tree.general.statusBar": "tags"` and enable this option, you'd show:
(fixme-icon) 3 (todo-icon) 42 (test-icon) 1
Instead of:
(checkmark) FIXME: 3, TODO: 42, TEST: 1

You can also make an option for the status bar to follow the tag order (since you may want to associate tags with importance, similar to how errors are more urgent than warnings), instead of sorting by amount of items. I'd even recommend making that the default, if you implement the icons.

By the way, "Group by Tag" is also not following tag order, at least in tree view. I wonder what order it's using.

**Comment by Gruntfuggly** [comment]
The current order is based on the number of each todo - it should show
TODO:42, FIXME:3, TEST:1

I can add an option to use tag order.
Adding the icons seems like a good idea.

Group by tag is probably alphabetical order. You can make the tags only view order by tag order. I'll add it to the tree view too.

**Comment by Gruntfuggly** [comment]
I've added a setting `todo-tree.general.showIconsInsteadOfTagsInStatusBar` which shows the icons in the status bar (if they've been defined).

The tree and flat views now show groups in tag order and when showing all the tags on the status bar, that will be in tag order.

**Comment by geekley** [comment]
Oddly not all icons seem to work... "check-circle" for example, works in side bar, but not status bar.

Also, some icons are different on side bar and status bar (flame icon for example), so I think it's using codicons on status bar and octicons on side bar. For example, testing with:
`"todo-tree.highlights.customHighlight": { "TODO?": { "icon": "checklist" } }`
I get different icons. I tried `"icon": "$(checklist)"`, but that seems to just not work (as per README, that should make it use codicons? unless I misunderstood it).

In any case, I guess I'll just use a different icon, so thanks for adding this!

**Comment by Gruntfuggly** [comment]
I don't think octicons will work in the status bar any more - only codicons/theme icons. 

There was a bug though which wasn't handling the icon properly, and another which was failing to validate the colours properly (which may have been contributing). 

I've fixed the errors and changed the commas to spaces. I've also double spaced each item to make it easer to read:
Now if you specify an octicon for the todo, it will try to use the corresponding codicon, but may end up blank - I'll add octicon/codicon validation.

![image](https://user-images.githubusercontent.com/376658/116219206-465bc980-a743-11eb-89d9-708554c322e9.png)

**Comment by Gruntfuggly** [comment]
Please try the latest version. If you specify an octicon it will try to use the equivalent codicon.

**Comment by geekley** [comment]
Ah, cool, that fixed the `$()`, now I can use it to have consistent codicons in both places. Thanks!
With space, it looks much better too: ![image](https://user-images.githubusercontent.com/38332912/116301692-b0da2d00-a776-11eb-9a44-35c5566ac6c1.png)
