### ISSUE TITLE
Not recursing into subfolders

### ISSUE THREAD

**Issue by somewhatabstract** [Gruntfuggly/todo-tree#50]
I cannot seem to persuade this extension to look recursively into all folders of the workspace. I think the glob patterns need to be applied recursively.

UPDATE: I think this is actually an issue with limits. We have a lot of TODOs and things in our codebase and I think we're maxing out on how many the tree can show. Is this a hard limit or something that can be increased?

UPDATE 2: Turns out this is a buffer size issue for the ripgrep process that is launched. See comment thread for info. PR #53 addresses this.

**Comment by Gruntfuggly** [comment]
There aren't any limits in the extension itself and there are no globs applied by default. ripgrep can have limits applied, but again there's nothing applied by default.

Does it work if you set `todo-tree.rootFolder` to something with a limited number of subfolders?

**Comment by Gruntfuggly** [comment]
Have you set `todo-tree.rootFolder` to something other than the default? I've noticed that there is an issue on windows, where including a trailing slash on the folder causes ripgrep to fail.

**Comment by somewhatabstract** [comment]
Some more details just in case they're useful:

1. MacOS 10.13.5
2. VSCode 1.25
3. TodoTree 0.0.68 (updated today)

I'll try setting the rootFolder now and see if that works. Thanks for responding! I love this extension.

**Comment by somewhatabstract** [comment]
OK, I set the `rootFolder` to the root of my repository and I still don't see all the files that have matching TODOs in them. It looks like it is not recursing into subfolders, but we have so many TODOs in the codebase, I wonder if its just hitting some sort of limit.

I will try adding a glob pattern for looking into subfolders and see if that works, but I think that relies on globs being applied recursively, which is down to the code interpreting the glob.

**Comment by Gruntfuggly** [comment]
There are no limits in the extension and the glob pattern is empty by default, so I don't think that will make any difference. Ripgrep has options to ignore VCS ignore files, but again, these aren't applied by default.

Another thing you can try is enabling the debug console, by setting `todo-tree.debug` to **true** and restarting. You should then find an extra output channel in the output window (called todo-tree) which will show a bunch of output, including the commands being generated for the search. 

Can you post the contents of the output window here?

**Comment by somewhatabstract** [comment]
Yes, I'll give that a go!

**Comment by Gruntfuggly** [comment]
Do you see all the matches you'd expect after the commands? It should log an entry for each one.

**Comment by Gruntfuggly** [comment]
Normally ripgrep errors are inhibited - if you set `todo-tree.ripgrepArgs` to **"--messages" you should see any errors logged in the developer console (I need to capture this and put it in the todo-tree output panel too).

**Comment by somewhatabstract** [comment]
In VSCode, I see just short of 3000 matches.

In bash, I get just short of 13000 matches.

**Comment by Gruntfuggly** [comment]
Is that coming from the output panel saying "Found XXX items?"

**Comment by somewhatabstract** [comment]
Yes, that's right, it also seems to match the number I would get if subfolders were not looked at (based off the bash results).

The `--messages` change did not show any errors or difference in the output.

**Comment by somewhatabstract** [comment]
And the matches in the output don't include anything in nested subfolders, only things at the root level and one level down in the folder hierarchy. Very strange.

**Comment by Gruntfuggly** [comment]
Curious. When you tried the command in the bash, were you in the root folder or somewhere else?

**Comment by somewhatabstract** [comment]
Ah yes, I was in the root. Let me try it from a different dir

**Comment by somewhatabstract** [comment]
Different dir gives the same results with the bash run.

**Comment by somewhatabstract** [comment]
Is there a way I can debug this on my side? perhaps I can spot the issue if I debug locally.

**Comment by somewhatabstract** [comment]
I'll see if I can make a little repo that exhibits the issue. That might help too. Thanks again for the help and for the extension :)

**Comment by Gruntfuggly** [comment]
If you want, you can clone the repository from here:
https://github.com/Gruntfuggly/todo-tree
If you then open the folder in code, you should be able to run it under the debugger in vscode. The extension comprises 3 main parts - extension.js which does the bulk of it and interfaces with vscode, dataProvider.js which handles building the tree and ripgrep.js which handles the searching. Try sticking a breakpoint at line 121 of ripgrep.js and see if you can hit it...

**Comment by Gruntfuggly** [comment]
You might find that you need a configuration file for the debugger - put the following in `.vscode/launch.json`
```
// A launch configuration that launches the extension inside a new window
{ 
    "version": "0.1.0",
    "configurations": [
        {
            "name": "Launch Extension",
            "type": "extensionHost",
            "request": "launch",
            "runtimeExecutable": "${execPath}",
            "args": ["--extensionDevelopmentPath=${workspaceRoot}" ],
            "stopOnEntry": false
        },
        {
            "name": "Launch Tests",
            "type": "extensionHost",
            "request": "launch",
            "runtimeExecutable": "${execPath}",
            "args": ["--extensionDevelopmentPath=${workspaceRoot}", "--extensionTestsPath=${workspaceRoot}/test" ],
            "stopOnEntry": false
        }
    ]
}
```

**Comment by Gruntfuggly** [comment]
Good luck - it would be good to get to the bottom of this. 8-)

**Comment by somewhatabstract** [comment]
Thanks! I'll update this issue with anything I discover. I just tried creating a simple repo to exhibit the issue and it didn't, so I am guessing this has something to do with:

1. The sheer number of TODOs, HACKs, etc. in the repo I am working on
2. The file paths being funky somehow

**Comment by Gruntfuggly** [comment]
I suspect it's something slightly different in the context of how the command is being called in the ripgrep module. You should be able to see where it generates the command, executes it and captures the results. If the results are what you'd expected then there's obviously a problem with how the extension then interprets them, but I think it may be something else. One thing that has just sprung to mind is whether or not the process is able to pass back the entire output? You could try manually modifying the command to pipe the output to a file and see if that contains everything.

**Comment by somewhatabstract** [comment]
Ah, yes, good point. I'll poke around and see what I find.

**Comment by somewhatabstract** [comment]
OK, I know what's happening now. I'll look at writing a fix.

`"stdout maxBuffer exceeded"`

**Comment by somewhatabstract** [comment]
I think expanding the buffer will only postpone this happening again, so I am going to try moving to use this: https://stackoverflow.com/a/26995407/23234

**Comment by somewhatabstract** [comment]
OK, `child_process.spawn` won't work. Errors out with EONENT; just doesn't like spawning that file and I cannot work out why. However, I think pushing the buffer size up for `exec` is an adequate workaround, in lieu of `spawn` not working.

**Comment by Gruntfuggly** [comment]
Thanks for this - out of interest, how does vscode cope with so many todos? Do you think there should be some indication that it is processing them (if that's possible)?

**Comment by somewhatabstract** [comment]
It seems to work pretty well. I didn't see anything untoward. Definitely a bit of a delay, but I didn't feel like it was a major problem. I do think the codebase I experienced this on is an anomaly (I hope). :)

**Comment by Gruntfuggly** [comment]
I had to make a small change - the error flag gets set if ripgrep doesn't find anything, so I had to filter them out.
Glad you've got it sorted - sounds like your codebase needs some TLC 8-)

**Comment by Gruntfuggly** [comment]
I've just uploaded a new version which handles the buffering slightly differently - it might mean that the buffer size parameter isn't needed anymore. Let me know if it works or breaks for you (sorry if it does).

**Comment by somewhatabstract** [comment]
Nice, I didn't think those events worked unless `spawn` was used and I couldn't get that working, so I ditched it. Sadly, because `exec` buffers the results, it still needs a bigger buffer size even when using the streaming calls. If I reset the buffer size back to default, it runs out of space and only returns about 2000 of the 13000 things.

**Comment by Gruntfuggly** [comment]
No, I didn't know you could do that either. Good job I left the buffer size in then 8-). Looks like the event handlers fixed this problem: https://github.com/Gruntfuggly/todo-tree/issues/55 and the buffer works for you. Hopefully that covers everybody!
