### ISSUE TITLE
Feature: Show some context lines from file when hovering TODO item in list

### ISSUE THREAD

**Issue by geekley** [Gruntfuggly/todo-tree#500]
The text in TODO comments alone is very often not enough to describe the task without some of the surrounding code as context.
For example:
```cs
//FIXME this is taking too long, improve efficiency
public string GenerateOutput() {
```
```cs
public int GetID() {
  throw new NotImplementedException(); //TODO stub
}
```

It would be great to have options to select how many lines of context (before and after) to show when hovering a task item in the list/tree. This code would be shown in the tooltip, below the file path (or whatever is in `todo-tree.tree.tooltipFormat`), as formatted text (same monospace font as in the text editor). Even better if you're able to add line numbers and syntax-highlighting.

This would greatly improve productivity, since you won't have to click every item to remember its details, or worry about typing exactly what you want TODO when context is self-explanatory.

For example, you could have options like:
```jsonc
"todo-tree.tree.tooltipContextLinesBefore": 2, // includes TODO line + 1 line above
"todo-tree.tree.tooltipContextLinesAfter": 1, // 1 line below TODO
```

**Comment by Gruntfuggly** [comment]
I previously resisted doing this as it would require a load of extra processing of the ripgrep results, but I'll have another look to see if it's possible.

**Comment by Gruntfuggly** [comment]
This will be too complex to add unfortunately (certainly for the file scan), so I'm going to close this.
