### ISSUE TITLE
Feature : TODO/FIXME snippet

### ISSUE THREAD

**Issue by jawa0919** [Gruntfuggly/todo-tree#501]
xx.code.snippets
```json
{
  "todo": {
    "prefix": "todo",
    "body": [
      "// TODO $CURRENT_YEAR-$CURRENT_MONTH-$CURRENT_DATE $CURRENT_HOUR:$CURRENT_MINUTE:$CURRENT_SECOND $1"
    ],
    "description": "new TODO snippet"
  },
  "fixme": {
    "prefix": "fixme",
    "body": [
      "// FIXME $CURRENT_YEAR-$CURRENT_MONTH-$CURRENT_DATE $CURRENT_HOUR:$CURRENT_MINUTE:$CURRENT_SECOND $1"
    ],
    "description": "new FIXME snippet"
  },  
}
```

**Comment by Gruntfuggly** [comment]
Why would you need it integrated - are they standard snippets?

**Comment by jawa0919** [comment]
Tools just show Todo, maybe someone wants to build a Todo, like me

**Comment by Gruntfuggly** [comment]
OK, but why does it need to be in the extension - they're just snippets? What would the extension do?

**Comment by Gruntfuggly** [comment]
I'm going to close this - if you can explain what you want the extension to do, that is not covered by the standard snippets, please reopen.
