### ISSUE TITLE
Todo-Tree: Cannot read property 'fsPath' of undefined

### ISSUE THREAD

**Issue by tjventurini** [Gruntfuggly/todo-tree#503]
Since this morning I get the following error after I open vscode.

```
Todo-Tree: Cannot read property 'fsPath' of undefined
```

Does anyone know what's causing this? Is it a misconfiguration on my side or is it actually a but? 🤔

Thank you!

**Comment by Gruntfuggly** [comment]
Bug probably. I just uploaded a new version which uses URIs instead of file paths.

Please can you post your settings so I can try to recreate it here.

Also, is there anything in the developer tools log?

You can install the previous version from the extensions panel if it continues to cause an issue.

**Comment by tjventurini** [comment]
Going back to version v0.0.211 solved the issue for now. Thank you :+1:

**Comment by Gruntfuggly** [comment]
Is there any chance you could post your settings? I'd like to be able to fix the issue and I don't see it here. The extension is way too configurable 🙁

**Comment by yialo** [comment]
I have this bug with such a trace in devtools:

```
ERR Cannot read property 'fsPath' of undefined: TypeError: Cannot read property 'fsPath' of undefined
at e (c:\Users\user\.vscode\extensions\gruntfuggly.todo-tree-0.0.212\dist\extension.js:34:59089)
at c:\Users\user\.vscode\extensions\gruntfuggly.todo-tree-0.0.212\dist\extension.js:34:59683
at Array.map (<anonymous>)
at e (c:\Users\user\.vscode\extensions\gruntfuggly.todo-tree-0.0.212\dist\extension.js:34:59596)
at t.TreeNodeProvider.add (c:\Users\user\.vscode\extensions\gruntfuggly.todo-tree-0.0.212\dist\extension.js:34:59740)
at c:\Users\user\.vscode\extensions\gruntfuggly.todo-tree-0.0.212\dist\extension.js:39:6800
at Array.map (<anonymous>)
at Object.e.exports.addToTree (c:\Users\user\.vscode\extensions\gruntfuggly.todo-tree-0.0.212\dist\extension.js:39:6766)
at O (c:\Users\user\.vscode\extensions\gruntfuggly.todo-tree-0.0.212\dist\extension.js:22:21474)
at c:\Users\user\.vscode\extensions\gruntfuggly.todo-tree-0.0.212\dist\extension.js:22:26849
at a (c:\Users\user\.vscode\extensions\gruntfuggly.todo-tree-0.0.212\dist\extension.js:22:25926)
at c:\Users\user\.vscode\extensions\gruntfuggly.todo-tree-0.0.212\dist\extension.js:22:26243
at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by Gruntfuggly** [comment]
Thanks - that narrows it down. Could you open the TODO tree output channel (you may need to set `todo-tree.general.debug: true`) and paste the contents so I can see your search results?

**Comment by yialo** [comment]
There is no any errors in output.
With regular search by project I found 149 items that should be found and processed by extension. According to output, extension processes only 138 items.

**Comment by yialo** [comment]
Error notification occurs only at project opening in new window, and not in evey project.

**Comment by Gruntfuggly** [comment]
Thanks - you've given me enough to recreate it - it's because of multiline todos. I'll get it fixed...

**Comment by tjventurini** [comment]
Sorry, just came back to it :sweat_smile: 

Thank you, seems to work perfectly :grin: :+1:
