### ISSUE TITLE
Adding a borderWidth property

### ISSUE THREAD

**Issue by pilouk** [Gruntfuggly/todo-tree#504]
I wish i could add some padding to the TAG and i think there is not such thing in the VS Code API.
However, i think adding a **borderWidth** property would permit such thing.
The borderWidth by default would be like 1px and the same color as the default.

What you guys think about this ?

Look the image below, i try to achieve "Chip" looking but really miss some padding/margin

![image](https://user-images.githubusercontent.com/1840762/116450208-04a54e80-a829-11eb-8fbc-c285ffe12e2b.png)

**Comment by Gruntfuggly** [comment]
I've tried doing this before before, but it doesn't work.
1px border:
![image](https://user-images.githubusercontent.com/376658/116525620-9ddb7000-a8d0-11eb-81b9-8c0101527f7a.png)
5px border:
![image](https://user-images.githubusercontent.com/376658/116525850-da0ed080-a8d0-11eb-9837-6d636e597d7d.png)

Unfortunately I don't think there is any way to achieve it. 🙁

**Comment by pilouk** [comment]
> I've tried doing this before before, but it doesn't work.
> 1px border:
> ![image](https://user-images.githubusercontent.com/376658/116525620-9ddb7000-a8d0-11eb-81b9-8c0101527f7a.png)
> 5px border:
> ![image](https://user-images.githubusercontent.com/376658/116525850-da0ed080-a8d0-11eb-9837-6d636e597d7d.png)
> 
> Unfortunately I don't think there is any way to achieve it. 🙁

Can you try with a combination of outline like this:
  ```
outline-color: red;
  outline-style: solid;
  outline-width: thick;
```

Thank you for taking the time :P

**Comment by Gruntfuggly** [comment]
![image](https://user-images.githubusercontent.com/376658/116554897-a3967d00-a8f3-11eb-8d65-ee560784c025.png)
🙁

**Comment by pilouk** [comment]
Man...if we could get the borderRadius work on the outline it would have work !

**Comment by Gruntfuggly** [comment]
There's not even a standard outline radius property in CSS.

**Comment by danemtsov** [comment]
There is hope: https://bugs.chromium.org/p/chromium/issues/detail?id=81556

Firefox 88 already implemented this.

**Comment by Gruntfuggly** [comment]
If it gets added to VSCode at some point, I'll add support for it. 🙂 

Feel free to reopen this if you spot that they've added it before I do!
