### ISSUE TITLE
Allow seeing full TODO in a title when hovering over it in the tree

### ISSUE THREAD

**Issue by mitar** [Gruntfuggly/todo-tree#505]
Currently one sees file path and line. I would prefer to be able to see the full TODO contents. Filename I can get by hovering on the file entry in the tree, and line number is not very useful without some context shown (which I get when I click on the entry).

**Comment by Gruntfuggly** [comment]
You can customise what is shown using `todo-tree.tree.tooltipFormat`.
for example,
```
"todo-tree.tree.tooltipFormat": "${filepath}:${line}\n${tag} ${after}"
```

See https://github.com/Gruntfuggly/todo-tree#configuration for details.

**Comment by Gruntfuggly** [comment]
Did you have any luck trying this?
