### ISSUE TITLE
To Many Gutter Icons for Unchecked Task List Items

### ISSUE THREAD

**Issue by WeirdBeardDev** [Gruntfuggly/todo-tree#507]
I added a gutter icon for the unchecked and checked task lists, `- [ ]` and `- [x]`.  The unchecked task list seems to run amok with the gutter icons and even overrides other gutter icons setup for other TODO items.  The attached screenshot shows several issues.

1. The unchecked gutter icons starts at the header `# Task List` and continues until the task list even when there are no tasks present, lines 91-95.
2. The unchecked gutter icons override the TODO gutter icon, lines 98-105.
3. The unchecked gutter icons override the checked gutter icon, lines 109-116.

I did limited testing and it doesn't appear to do this with other gutter icons, just the unchecked one.

![Screenshot 2021-05-03 110320](https://user-images.githubusercontent.com/26331356/116893642-36d6f780-abff-11eb-984e-22857cdd57b2.png)

**Comment by Gruntfuggly** [comment]
Could you post your settings and that piece of code (to save me typing it in) and I'll see if I can recreate it here.

**Comment by WeirdBeardDev** [comment]
Here's everything from the settings.json file for todo-tree:

```json
    "todo-tree.tree.showScanModeButton": false,
    "todo-tree.general.tags": [
        "BUG",
        "HACK",
        "FIXME",
        "FIX",
        "TODO",
        "FORMULA",
        "REFACTOR",
        "TEMP",
        "INFO",
        "FIXIT",
        "[ ]",
        "[x]"
    ],
    "todo-tree.general.tagGroups": {
        "FIX": [
            "FIXME",
            "FIX",
            "FIXIT"
        ],
    },
    "todo-tree.highlights.customHighlight": {
        "BUG": {
            "foreground": "red",
            "gutterIcon": true
        },
        "HACK": {
            "icon": "zap",
            "foreground": "yellow",
            "gutterIcon": true
        },
        "FIX": {
            "icon": "flame",
            "foreground": "red",
            "gutterIcon": true
        },
        "TODO": {
            "foreground": "#FF8C00",
            "icon": "clippy",
            "gutterIcon": true
        },
        "FORMULA": {
            "icon": "graph",
            "foreground": "green",
            "gutterIcon": true
        },
        "REFACTOR": {
            "icon": "beaker",
            "foreground": "magenta",
            "gutterIcon": true
        },
        "INFO": {
            "icon": "info",
            "foreground": "green",
            "gutterIcon": true
        },
        "TEMP": {
            "icon": "trash",
            "foreground": "DeepSkyBlue",
            "background": "navy",
            "gutterIcon": true
        },
        "[ ]": {
            "foreground": "red",
            "type": "tag-and-comment",
            "icon": "bookmark",
            "gutterIcon": true
        },
        "[x]": {
            "foreground": "green",
            "type": "line",
            "icon": "bookmark-fill",
            "gutterIcon": true
        }
    },
    "todo-tree.general.statusBar": "current file",
    "todo-tree.highlights.enabled": true,
    "todo-tree.general.statusBarClickBehaviour": "cycle",
    "todo-tree.tree.buttons.export": true,
    "todo-tree.tree.buttons.refresh": false,
    "todo-tree.regex.regex": "(//|#|<!--|;|/\\*|^|^\\s*(-|\\d+.))\\s*($TAGS)",
```

and the markdown from the picture:

```markdown
---

# Task List 


- [ ] not done
- [ ] not done


// TODO and work on this
// FIX fix this

// TODO work on this


- [ ] not done
- [ ] not done

---

- [x] done

- [x] done
- [ ]  not done


- [ ] not done
- [ ] done


```

**Comment by Gruntfuggly** [comment]
It's because you're using `"type": "tag-and-comment"`. Removing that works properly. 
I'm not sure why it's going wrong though - I'll look into it.

**Comment by Gruntfuggly** [comment]
Looks like the regex needs a slight tweak:
change it from 
```
(//|#|<!--|;|/\\*|^|^\\s*(-|\\d+.))\\s*($TAGS)
```
to 
```
(//|#|<!--|;|/\\*|^|^[ \\t]*(-|\\d+.))\\s*($TAGS)
```

**Comment by WeirdBeardDev** [comment]
I updated the regex and added the "type": "tag-and-comment" back to see the results and now it doesn't work at all.  Even after I reverted the regex and removed the "type" statement it still doesn't work.  I've tried reloading the window as well as restarting VS Code.

![image](https://user-images.githubusercontent.com/26331356/117056516-631b7280-acea-11eb-83d3-21fa4287aafa.png)

**Comment by WeirdBeardDev** [comment]
I made that last comment just a bit too soon.  It appears that if you enter the regex via the Settings screen then the slashes get escaped therefore breaking the regex.  I entered the regex directly in the json file and it works with and without the "type" statement.  Thanks!

![image](https://user-images.githubusercontent.com/26331356/117057130-17b59400-aceb-11eb-95f1-1ed68198692e.png)
Screenshot with new regex and "type": "tag-and-comment"

**Comment by Gruntfuggly** [comment]
Yes, it's a pain that the slashes have to be escaped. Usually I try to post the settings both ways, but I assumed you'd update the json as you'd posted it earlier. 

Anyway - I'm glad it's now working. Are you OK for me to close this now?

**Comment by WeirdBeardDev** [comment]
BTW this is a great extension, keep up the good work and thanks for the assist!
