### ISSUE TITLE
[Question] Can I disable in-file highlighting?

### ISSUE THREAD

**Issue by Timmiej93** [Gruntfuggly/todo-tree#508]
I've already got another extension setup, doing all the highlighting for me. For some reason, this extension seems to combine or overwrite those settings, and turns all background highlights to white. They show up as the correct color (set in the other extension) for a second, and then turn white. I tried making `none` the only entry in the `Highlights: Background Colour Scheme` setting, but that didn't do anything.

Is there a simple way to disable background and foreground highlighting, while keeping all the other features?

**Comment by Gruntfuggly** [comment]
Try:

Todo-tree > Highlights: **Enabled**

or in the JSON settings:

```
    "todo-tree.highlights.enabled": false
```

**Comment by Timmiej93** [comment]
It always amazes me how good I am in overlooking things when I'm looking for them. Thanks!

**Comment by Gruntfuggly** [comment]
No problem!
