### ISSUE TITLE
[Feature request]: Ignore files present in .gitignore

### ISSUE THREAD

**Issue by Leccho** [Gruntfuggly/todo-tree#509]
Would be nice if you'd look for `.gitignore` files and ignore those files too in the extension.
![image](https://user-images.githubusercontent.com/2791678/118029179-e879d500-b331-11eb-965e-66a913f4d118.png)

**Comment by Gruntfuggly** [comment]
It should honour .gitignore files out of the box. What settings are you using?

**Comment by Leccho** [comment]
@Gruntfuggly It does work now, I didn't think to reload vs code. My guess is that an error occurred while loading the extension.
