### ISSUE TITLE
InformationMessage in Markdown will also appear when you press Never Show This Again.

### ISSUE THREAD

**Issue by ChenCMD** [Gruntfuggly/todo-tree#510]
![image](https://user-images.githubusercontent.com/46134240/118374311-56562300-b5f6-11eb-99a1-2000fc654a9b.png)

**Comment by Gruntfuggly** [comment]
Which version of the extension do you have installed? The dialog should look like this:

![image](https://user-images.githubusercontent.com/376658/118376503-2a1faf80-b5c0-11eb-91de-dd9e88651656.png)

**Comment by Gruntfuggly** [comment]
Ah - OK, it only looks like that when your settings are still the default.

I'm not sure why it is still popping up. For some reason, it looks like your global state is not setting stored properly. As a work around, you could modify the regex as per the link in the "More Info".

If I create a temporary version of the extension with some debug messages in, would you be prepared to test it for me?

**Comment by ChenCMD** [comment]
Let's test it.

**Comment by Gruntfuggly** [comment]
I've finally uploaded a new version which should fix this.
