### ISSUE TITLE
[Bug Report] Doesn't work with settings.json opened from Command Palette

### ISSUE THREAD

**Issue by laggardkernel** [Gruntfuggly/todo-tree#513]
todo-tree doesn't work with `settings.json` opened from Command Palette or by shortcuts.

If opened with `code /path/to/settings.json`, the problem disappears.

**Comment by Gruntfuggly** [comment]
What doesn't work? Does the tree view appear in the side bar? Or is it that you don't see any TODOs from the settings.json file?

**Comment by Gruntfuggly** [comment]
I'm not sure why opening code in a different way causes the issue, but there is some buggy code which sometimes tries to ignore TODOs in the `settings.json` file.

Can you try setting the scan mode to 'Workspace Only' (from the context menu) and see if it makes any difference?

**Comment by laggardkernel** [comment]
@Gruntfuggly Changing to "workspace only" doesn't make any difference. Formerly I used "current file".

I don't think `settings.json` does not belong to the workspace. It's the json file of your VSCode preference `Preferences: Open Settings (JSON)`. Maybe I didn't made my description clear enough.

**Comment by Gruntfuggly** [comment]
Please add `vscode-userdata` to `todo-tree.general.schemes`

**Comment by laggardkernel** [comment]
> Please add `vscode-userdata` to `todo-tree.general.schemes`

Thanks, this solves my problem.
