### ISSUE TITLE
Markdown Preview Enhanced

### ISSUE THREAD

**Issue by generic-user** [Gruntfuggly/todo-tree#514]
Hi, looks like there are some performance issues introduced that are not there in the original repository ... care to investigate?

### MPE

![image](https://user-images.githubusercontent.com/1516035/119227382-cf310f80-bb0d-11eb-8a9f-3bef57fad0f0.png)

### Dendron MPE

![image](https://user-images.githubusercontent.com/1516035/119227460-3e0e6880-bb0e-11eb-89f9-c2622de1e3c2.png)

**Comment by generic-user** [comment]
Euh wrong repository ... sorry.

**Comment by Gruntfuggly** [comment]
Lol - I was worried for a minute there!
