### ISSUE TITLE
`TODO` in .sql file not show on window table

### ISSUE THREAD

**Issue by daidai21** [Gruntfuggly/todo-tree#515]
![image](https://user-images.githubusercontent.com/36124626/119638795-92d11c80-be49-11eb-952f-a5aeeebe536b.png)

other type file is ok.

**Comment by Gruntfuggly** [comment]
You need to modify the regex to match `--`, e.g. 
```
(--|//|#|<!--|;|/\*|^|^[ \t]*(-|\d+.))\s*($TAGS)
```
or in the settings.json
```
"todo-tree.regex.regex": "(--|//|#|<!--|;|/\\*|^|^[ \\t]*(-|\\d+.))\\s*($TAGS)",
```

**Comment by daidai21** [comment]
I understand.

tks!
