### ISSUE TITLE
Detect todonotes in LaTeX 

### ISSUE THREAD

**Issue by michidk** [Gruntfuggly/todo-tree#516]
The https://ctan.org/pkg/todonotes package in LaTeX allows inserting ToDo's into documents with the `\todo` command. Would be great if it actually shows up in todo-tree.

E.g.: `\todo{Replace figure with custom one}`

**Comment by Gruntfuggly** [comment]
Please see the wiki for an example config for LaTeX

https://github.com/Gruntfuggly/todo-tree/wiki/Configuration-Examples

**Comment by Gruntfuggly** [comment]
You'll also need to add `todo` as a tag, or set "todo-tree.regex.regexCaseSensitive" to false.

**Comment by michidk** [comment]
> You'll also need to add `todo` as a tag, or set `"todo-tree.regex.regexCaseSensitive"` to false.

Thank you, that was the missing part. Would be awesome, if this extension would automatically apply this configuration when detecting a LaTeX file.

**Comment by Gruntfuggly** [comment]
There are so many potential configurations depending on the language that I think I'd be here forever trying to make it work automatically for them all.

I guess it wouldn't be a massive change to ask once for LaTeX though. I'll see if I can add something for the next release.

**Comment by tobiasdiez** [comment]
Maybe it's worthwhile to have language-specific defaults as described here: https://code.visualstudio.com/api/references/contribution-points#Configuration-default-example

**Comment by Gruntfuggly** [comment]
I'm going to close this as it's possible to do with configuration.
