### ISSUE TITLE
Doesn't Work within Blade Comments

### ISSUE THREAD

**Issue by Kaynite** [Gruntfuggly/todo-tree#517]
Doesn't Work within Blade Comments
{{-- --}}

**Comment by Gruntfuggly** [comment]
You just need to update the regex, probably something like:
```
(\\{\\{--|//|#|<!--|;|/\\*|^|^[ \\t]*(-|\\d+.))\\s*($TAGS)
```
in settings.json or 
```
(\{\{--|//|#|<!--|;|/\*|^|^[ \t]*(-|\d+.))\s*($TAGS)
```
in the settings GUI.

**Comment by Gruntfuggly** [comment]
Did you get this to work?

**Comment by Kaynite** [comment]
> Did you get this to work?

Yes, Thank You
