### ISSUE TITLE
Enable set type to icon or set background to false

### ISSUE THREAD

**Issue by shaonianruntu** [Gruntfuggly/todo-tree#520]
In some cases, for some unimportant tags, I don't want it to affect my overall reading of the document. At this point, I don't want to highlight this tag, or highlight the line on which the tag is located and undermine the simplicity of the document, but rather to bookmark it as a location without intrusively, so that it simply displays an icon in gutter.

But at the moment the todo-tree plug-in has to select a highlight for the tag, and I want to know if I can do it without setting it up, supporting just a simple icon.

**Comment by Gruntfuggly** [comment]
Please see the README.md (https://github.com/Gruntfuggly/todo-tree).

You can define `customHighlight` for particular tags. Set `background` to `#00000000` to disable it, or you can set `type` to `none`, which will work - just ignore the warning in the settings (I need to make 'none' a valid value).

**Comment by shaonianruntu** [comment]
> Please see the README.md (https://github.com/Gruntfuggly/todo-tree).
> 
> You can define `customHighlight` for particular tags. Set `background` to `#00000000` to disable it, or you can set `type` to `none`, which will work - just ignore the warning in the settings (I need to make 'none' a valid value).

Setting `type` to `none` will not show the icon in gutter. 
Setting `background` to `#00000000` is what I want, and it works. Hope to support `none` value to `background ` as a abbreviation of `#00000000`.

![截屏2021-06-09 at 21 10 36](https://user-images.githubusercontent.com/16336682/121360621-284ecf00-c967-11eb-9df7-b26acaa984fc.png)

**Comment by Gruntfuggly** [comment]
Adding 'none' and 'transparent' as valid colours seems like a good idea.

**Comment by AndrewLaganaro** [comment]
Came here looking for this. I like the color highlighting but just it, I do not want a background as it distracts me from the code. "transparent" should be good, but I'll try #00000000 when configuring the extension again. Thank you

**Comment by Gruntfuggly** [comment]
'transparent' and 'none' will be valid named colours in the next version (0.0.225).
