### ISSUE TITLE
[BUG] It locks *.asar files

### ISSUE THREAD

**Issue by zardoy** [Gruntfuggly/todo-tree#521]
Via Extension bisect I've found that this extension blocks *.asar files on Windows, on macOS everything works fine.

How to reproduce:

1. Create new folder and open it with VSCode
2. Install Electron: `yarn init -yp && yarn add electron`
3. Install this extension and click Refresh in TODOS: TREE view
4. And you'll see via [LockHunter](https://lockhunter.com/) that `node_modules\electron\dist\resources\default_app.asar` got instantly locked by VSCode extension host

This issue makes me unable to use yarn.

Mabye this issue https://github.com/microsoft/vscode-eslint/issues/739 can relate to this problem

**Comment by Gruntfuggly** [comment]
Could you try adding `**/*.asar` to the exclude globs and see if it fixes it? The extension doesn't know anything about any particular file types - it just scans (using ripgrep), so all you can do is tell it to ignore that file type.

e.g.
```
"todo-tree.filtering.excludeGlobs": [ 
    "**/*.asar" 
]
```

**Comment by zardoy** [comment]
Sorry for the latency. This setting is already set to **/node_modules, but this extension locks all *.asar files in the workspace, regardless of the settings

**Comment by zardoy** [comment]
I meant that even with default settings this extension shouldn't look into `node_modules` folder, but as I wrote in the first comment, the file was in `node_modules\electron\dist\resources\default_app.asar`, hope you got me.

`

> ```
> "todo-tree.filtering.excludeGlobs": [ 
>     "**/*.asar" 
> ]
> ```

Of course I tried this setting, but it still keep locking *.asar files.

**BUT** It seems that setting the Scan Mode to **open files** solved the issue.

**Comment by Gruntfuggly** [comment]
Ah, sorry - you mean it still scans the node_modules folder even when it is excluded?

Please could you enable the debug output (`"todo-tree.general.debug": true`) and look in the output pane (Todo Tree should be in the drop down) and see what command is being generated for the search?

**Comment by Gruntfuggly** [comment]
Did you ever get a chance to try the above?

**Comment by zardoy** [comment]
Oh, sorry. I didn't have much time to do it, i was using Todo+ for a while (maybe because of default startup setting). But if you wish, I'll into source code and try to say whats wrong here!

**Comment by Gruntfuggly** [comment]
If it's not really an issue any more, then don't worry. I was interested to see why it wasn't ignoring you excludes though.

Ideally, if you could post your settings and then the contents of the output pane, that would be handy.

**Comment by zardoy** [comment]
Yes, I reviewed it and this is not an issue anymore, probably it was somehow related to the envirnonmet of previous versions of vscode.

>  I was interested to see why it wasn't ignoring you excludes though.

Your exclude globs worked as expected there was a vscode-specific issue with handling asar files. Probably it got fixed with electron update.

**Comment by mrbeardad** [comment]
@Gruntfuggly `"todo-tree.filtering.ignoreGitSubmodules": true` cause lock the asar files

**Comment by zardoy** [comment]
Yes it's an issue with some of vscode extensions again very aaboying why happens in the first place?

**Comment by mrbeardad** [comment]
How about reopen this issue?

**Comment by zardoy** [comment]
It's not that important the question is who would fix it
