### ISSUE TITLE
[FR] Support `staged changes` diff editor tag highlighting

### ISSUE THREAD

**Issue by wenfangdu** [Gruntfuggly/todo-tree#523]
Currently, tags are not highlighted in the `staged changes` diff editor, would be great if it's supported.

![image](https://user-images.githubusercontent.com/28700378/123194544-42e18600-d4d9-11eb-8a66-73a1200c268a.png)

**Comment by Gruntfuggly** [comment]
If you add "git" to `todo-tree.general.schemes` it should show them in the diffs.

**Comment by wenfangdu** [comment]
@Gruntfuggly Awesome!
