### ISSUE TITLE
fileWatcher& includeGlobs: newly created items are shown even if it is outside includeGlobs

### ISSUE THREAD

**Issue by abceleung** [Gruntfuggly/todo-tree#524]
Hello.
I have enabled fileWatcher and filters by includeGlobs.
![image](https://user-images.githubusercontent.com/82202780/123602454-467e5100-d7e8-11eb-8a10-946efbd587a6.png)

When I build my application, temp files are generated and they are added to the todo-tree interface even though they are all outside my includeGlobs directory.
![image](https://user-images.githubusercontent.com/82202780/123602599-72013b80-d7e8-11eb-830c-907e61af8e85.png)

These files disappear from the interface if I open them.

Is this intended? Can I prevent the temp files from showing up in the interface?

**Comment by Gruntfuggly** [comment]
I expected they are being added because of the file watcher. Do you actually need the file watcher enabled?

**Comment by abceleung** [comment]
> 
> 
> I expected they are being added because of the file watcher. Do you actually need the file watcher enabled?

I disabled file watcher and they stopped showing up. 
Thanks for your help.

**Comment by Gruntfuggly** [comment]
No problem - the file watcher isn't really that useful to be honest.
