### ISSUE TITLE
How to write a regex that supports `todo@某某`?

### ISSUE THREAD

**Issue by wenfangdu** [Gruntfuggly/todo-tree#526]
Need to be based on `((//|#|<!--|;|/\\*)\\s*($TAGS)|^\\s*- \\[ \\])`, i.e. need to support markdown `[ ]`.

Notice the subject after `todo` needs to support UTF-8, basically a non-space.

**Comment by Gruntfuggly** [comment]
Can you give me an example of what you would like it to match?

Does adding `@` after `($TAGS)` work?

You might be better using the new format for the default regex:

`(//|#|<!--|;|/\\*|^|^[ \\t]*(-|\\d+.))\\s*($TAGS)`

e.g.

`(//|#|<!--|;|/\\*|^|^[ \\t]*(-|\\d+.))\\s*($TAGS)@`

**Comment by wenfangdu** [comment]
@Gruntfuggly I want to match for example `TODO@某人` in `TODO@某人 some text`. I just tried `(//|#|<!--|;|/\\*|^|^[ \\t]*(-|\\d+.))\\s*($TAGS)@`, broke all the tag highlightings, event simple `todo`s won't be highlighted.

**Comment by Gruntfuggly** [comment]
Can you post your settings - add the `@` worked for me - this: `(//|#|<!--|;|/\\*|^|^[ \\t]*(-|\\d+.))\\s*($TAGS)@`

![image](https://user-images.githubusercontent.com/376658/123822659-656a0980-d8f4-11eb-8f31-dae015d5d279.png)

**Comment by Gruntfuggly** [comment]
Alternatively, just adding `TODO@某人` as a tag works with the default regex:
![image](https://user-images.githubusercontent.com/376658/123823818-6cdde280-d8f5-11eb-9fde-5d00b76a4e88.png)

**Comment by wenfangdu** [comment]
@Gruntfuggly Thanks, after some attempts, currently, I settled just using the new regex you mentioned `(//|#|<!--|;|/\\*|^|^[ \\t]*(-|\\d+.))\\s*($TAGS)`, do you consider update it to the readme?

**Comment by Gruntfuggly** [comment]
The default regex has now been updated (and the README.md will also be updated soon), so I'm going to close this. Thanks!
