### ISSUE TITLE
Feature Request - Code/regex highlighting

### ISSUE THREAD

**Issue by jschank** [Gruntfuggly/todo-tree#527]
I think it would be nice if there was a way to highlight specific code in my files.
For example: each occurrence of "throw", or logging statements like: "this.logger.warn" or "this.logger.info", and things like highlighting all console.* calls.

I know there are other projects that attempt to do this, but todo-tree has a better foundation of features, than those other projects. todo-tree does things I like, such as specifying the colors used for foreground/background highlighting. and the icon in the gutter.

anyway, its a thought.

**Comment by Gruntfuggly** [comment]
To be honest, there is nothing stopping you changing the regex to match anything you want.

You could update the regex to
```
($TAGS)
```
and then add `console.log` to the tag list, for example.

It will then find them all and highlight them.

**Comment by jschank** [comment]
Agreed, and that is what I do right now.. However, there are some weaknesses. (or at least I don't understand how to specify correct regexs)

In this example, the highlight and gutter include the last char in the previous line. (not sure why, and it doesn't always happen)

the tag, in settings.json is: "this.logger.", and the match doesn't work if I don't include the 'this.'

<img width="1118" alt="logger-example" src="https://user-images.githubusercontent.com/30314/124131694-0c15ed80-da4e-11eb-9f7a-ca73405327e7.png">

can a tag be a regex, itself?

**Comment by Gruntfuggly** [comment]
What is your regex set to?

**Comment by jschank** [comment]
The default installation regex, I think you mean this property...

    "todo-tree.regex.regex": "(//|#|<!--|;|/\\*|^|^\\s*(-|\\d+.))\\s*($TAGS)",

**Comment by Gruntfuggly** [comment]
And what tags do you have configured and what highlight settings? 

With your code sample and this regex, 

```
    "todo-tree.regex.regex": "(//|#|<!--|;|/\\*|^|^[ \\t]*(-|\\d+.))\\s*($TAGS)|(console\\.log|this\\.logger\\.warn)"
```
I get this highlighted:
![image](https://user-images.githubusercontent.com/376658/124153558-7483bf80-da8c-11eb-8863-e600514ec69f.png)

**Comment by jschank** [comment]
Here is what I had...
Does it matter that you're example above is not using the $TAGS? or is the key the escaped '.' in your regex?

>    
    "todo-tree.general.enableFileWatcher": true,
    "todo-tree.tree.showScanModeButton": false,
    "todo-tree.tree.showCountsInTree": true,
    "todo-tree.general.statusBar": "current file",
    "todo-tree.general.statusBarClickBehaviour": "reveal",
    "todo-tree.general.revealBehaviour": "end of todo",
    "todo-tree.tree.autoRefresh": true,
    "todo-tree.filtering.excludeGlobs": [
        "**/*.sql",
        "**/*.xml",
        "**/*.json"
    ],
    "todo-tree.highlights.defaultHighlight": {
        "icon": "alert",
        "type": "text",
        "foreground": "red",
        // "background": "white",
        "opacity": 100,
        "iconColour": "black",
        "gutterIcon": true
    },
    "todo-tree.general.tags": [
      "console.",
      "BUG",
      "HACK",
      "FIXME",
      "FIX",
      "FIXIT",
      "TODO",
      "NOTE",
      "DELETE",
      "JFS",
      "[ ]",
      "[x]",
      "this.logger.",
      "this.logger.error"
    ],
    "todo-tree.general.tagGroups": {
        "FIXME": [
            "FIXME",
            "FIX",
            "FIXIT"
        ]
    },
    "todo-tree.highlights.customHighlight": {
        "this.logger.": {
          "icon": "megaphone",
          "type": "text-and-comment",
          "foreground": "green",
          "background": "#90EE9080",
          "iconColour": "DarkGreen"
        },
        "this.logger.error": {
          "icon": "megaphone",
          "type": "text-and-comment",
          "foreground": "DarkRed",
          "background": "#FFE4E180",
          "iconColour": "Crimson"
        },
        "console.": {
            "icon": "issue-opened",
            "type": "text-and-comment",
            "foreground": "#d4308a",
            "iconColour": "#d4308a"
        },
        "FIXME": {
            "icon": "tools",
            "type": "text-and-comment",
            "foreground": "#FFFFFF",
            "background": "#FF1493",
            "iconColour": "red"
        },
        "BUG": {
            "icon": "bug",
            "type": "text-and-comment",
            "foreground": "#B22222",
            "background": "#FFB6C1",
            "iconColour": "red"
        },
        "TODO": {
            "icon": "tasklist",
            "type": "text-and-comment",
            "foreground": "white",
            "background": "#FF8C00",
            "iconColour": "#FF8C00"
        },
        "NOTE": {
            "icon": "pencil",
            "type": "text-and-comment",
            "foreground": "#0000FF",
            "background": "#ADD8E6",
            "iconColour": "blue"
        },
        "HACK": {
            "type": "text-and-comment",
            "foreground": "#000000",
            "background": "#FFFF00",
            // "iconColour": "yellow"
        },
        "DELETE": {
            "icon": "flame",
            "type": "text-and-comment",
            "foreground": "white",
            "background": "red",
            "iconColour": "red"
        },
        "JFS": {
            "type": "text-and-comment",
            "icon": "person",
            "foreground": "white",
            "background": "#800080",
            "iconColour": "#800080",
            "opacity": 100
        }
    },

**Comment by Gruntfuggly** [comment]
I'm going to close this as I think the currently functionality does what you need. Please feel free to re-open if you disagree.
