### ISSUE TITLE
Icon colors should match VS Code theme, not use foreground color

### ISSUE THREAD

**Issue by ffxsam** [Gruntfuggly/todo-tree#528]
I have the following color settings:

```json
  "todo-tree.highlights.customHighlight": {
    "TODO": {
      "icon": "check",
      "background": "#ff9c00",
      "foreground": "#000"
    },
    "FIXME": {
      "icon": "flame",
      "background": "#c00",
      "foreground": "#fff"
    }
  }
```

This looks great in my code:

<img width="231" alt="image" src="https://user-images.githubusercontent.com/12532733/124151855-9a8f6c80-da58-11eb-8b0c-6122785e0b19.png">

But the icons seem to be colored based on the `foreground` color above:

<img width="335" alt="CleanShot 2021-07-01 at 10 39 42" src="https://user-images.githubusercontent.com/12532733/124151920-a9761f00-da58-11eb-8956-a39f9bf9e762.png">

I'd expect the icons to be styled based on the VS Code theme. I could just pick different colors so that I can use a foreground of white, but then that wouldn't work when my VS Code theme automatically switches at sunset:

<img width="339" alt="image" src="https://user-images.githubusercontent.com/12532733/124152115-d9bdbd80-da58-11eb-9a27-fc8becff8a76.png">

**Comment by Gruntfuggly** [comment]
You can set `"iconColour"` to set the colour explicitly. You can also set it to a theme colour, e.g. "editorError.foreground".

**Comment by ffxsam** [comment]
Thanks, that works! For some reason, every single theme color variable is green. 🤔 But it works well enough.

**Comment by Gruntfuggly** [comment]
That sounds wrong - what have you set it to?

**Comment by ffxsam** [comment]
```json
  "todo-tree.highlights.customHighlight": {
    "TODO": {
      "icon": "check",
      "iconColour": "editorError.foreground",
      "background": "#ff9c00",
      "foreground": "#000"
    },
    "FIXME": {
      "icon": "flame",
      "iconColour": "editorError.foreground",
      "background": "#c00",
      "foreground": "#fff"
    }
  }
```

I went through several different [color variables](https://code.visualstudio.com/api/references/theme-color) and they're all either green or black.

**Comment by Gruntfuggly** [comment]
Ah - use `"$(flame)"` instead. Without the `$(` it uses octicons, which don't support theme colours.

**Comment by Gruntfuggly** [comment]
You can only set the colour using hex (or rgb) for octicons because it uses a library to provide SVGs for the images. Conversely, codicons can only use theme colours because it's handled by VSCode itself.

**Comment by ffxsam** [comment]
Aha, thank you!
