### ISSUE TITLE
Highlighting stops working on all tags if using "type": "tag-and-subtag"

### ISSUE THREAD

**Issue by roman-balzer** [Gruntfuggly/todo-tree#530]
TodoTree works great for except for subTags.
If I set 1 tag to `"type": "tag-and-subtag"` and use it in a file, the highlighting of all other tags stops working in that file.

In this screenshot everthing work as intended.
![sshot-317](https://user-images.githubusercontent.com/16666597/124763197-00399800-df34-11eb-887c-a6582829e181.png)

If I change the type to `tag-and-subtag` or `tag-and-subTag`, the highlighting on all tag stop working in the first file, while still working on the second.
![sshot-316](https://user-images.githubusercontent.com/16666597/124763145-ee57f500-df33-11eb-9390-c72a26806131.png)

I'm not 100% sure if this is a bug, or i'm doing something wrong.

**Comment by Gruntfuggly** [comment]
Sounds like a bug - I'll look into it.

Would you mind posting your settings as code and that code fragment? It will make it easier for me to reproduce and fix.

**Comment by roman-balzer** [comment]
```
"todo-tree.general.tags": [
    "@todo",
    "@optimize",
    "🚀TCL",
    "@bug",
    "@deprecated",
  ],
  "todo-tree.highlights.defaultHighlight": {
    "fontWeight": "bold",
    "type": "text",
    "gutterIcon": true
  },
  "todo-tree.highlights.customHighlight": {
    "@todo": {
      "icon": "tasklist",
      "iconColour": "#28BE41",
      "foreground": "#084A13",
      "background": "#28BE41"
    },
    "@optimize": {
      "icon": "code-review",
      "iconColour": "#037FE4",
      "foreground": "#004178",
      "background": "#037FE4",
      "type": "tag-and-subtag",
    },
    "🚀TCL": {
      "icon": "note",
      "iconColour": "Fuchsia",
      "foreground": "Fuchsia",
      "background": "#DA77F2",
      "opacity": 20,
      "type": "whole-line"
    },
    "@bug": {
      "icon": "bug",
      "iconColour": "#D83434",
      "foreground": "#780F0F",
      "background": "#D83434"
    }
  },
  "todo-tree.regex.subTagRegex": "^:\\s*",
```


This code will not work (also not in a empty file)
```
// @todo some random text here
// @optimize:test1 some random text here
// @optimize:test2 some random text here
// @optimize:test2 some random text here
// @optimize:test1 some random text here
// @bug some random text here
// @deprecated some random text here
// @todo
```


This code should work 
```
// @todo some random text here
// @bug some random text here
// @deprecated some random text here
// @todo
```

**Comment by disfated** [comment]
@Gruntfuggly could you kindly look into it.
Seems like `subtag` functionality is completely broken currently.
At least, I wasn't able to make it work in any way.

**Comment by roman-balzer** [comment]
Just checked if subtags are working, and they do. So, this issue can be closed
