### ISSUE TITLE
Unrecognized Escape Sequence in tag regex

### ISSUE THREAD

**Issue by Awbmilne** [Gruntfuggly/todo-tree#531]
I keep having the issue of there being a "unrecognized escape sequence" error in my regex

Here is the regex I am using:
```regex
(?:##[ \t]?($TAGS)(?::|: | )([^\n\r\t]*)(?:\r?\n##[ \t]{2,}[^\n\r\t]*)*)|(?:%%[ \t]?($TAGS)(?::|: | )([^\n\r\t]*)(?:\r?\n%%[ \t]{2,}[^\n\r\t]*)*)|(?:\/\/[ \t]?($TAGS)(?::|: | )([^\n\r\t]*)(?:\r?\n\/\/[ \t]{2,}[^\n\r]*)*)|(?:\/\*[ \t]?($TAGS)(?::|: | )(?:(?!\/)|[^*])*\*\/)
```
To make it easier to read, here it is broken up a bit:
```regex
(?:##[ \t]?($TAGS)(?::|: | )([^\n\r\t]*)(?:\r?\n##[ \t]{2,}[^\n\r\t]*)*)|
(?:%%[ \t]?($TAGS)(?::|: | )([^\n\r\t]*)(?:\r?\n%%[ \t]{2,}[^\n\r\t]*)*)|
(?:\/\/[ \t]?($TAGS)(?::|: | )([^\n\r\t]*)(?:\r?\n\/\/[ \t]{2,}[^\n\r]*)*)|
(?:\/\*[ \t]?($TAGS)(?::|: | )(?:\*(?!\/)|[^*])*\*\/)
```
Each of these lines handles a different type of comment, all supporting multiline.

It is expected to recognize any/all of these comments styles:
```
## TAG: Python comments

## TAG Python comments
##  Second line extension

%% TAG: Matlab, TeX, etc. Comments
%%  Second line extension

// TAG: C/C++ style comment
//  Second line extension

/* TAG: C/C++ style block comment
This can conver how ever much text is needed
until the comment close is added.

Even blank lines and such*/
```

The regex seems to work fine when I [test it on Regexr](https://regexr.com/61jtt)
The only thing I can image is that it is an issue with `\t`, but that seems crazy.

**Comment by Awbmilne** [comment]
Nevermind. I see now that the regex is Rust based, not Javascript based.

Thanks kinda a bummer. I cant use lookahead/around

**Comment by Awbmilne** [comment]
My updated regex is as follows:

```
(?:##[ \t]?($TAGS)(?::|: | )([^\n\r\t]*)(?:\r?\n##[ \t]{2,}[^\n\r\t]*)*)|(?:%%[ \t]?($TAGS)(?::|: | )([^\n\r\t]*)(?:\r?\n%%[ \t]{2,}[^\n\r\t]*)*)|(?://[ \t]?($TAGS)(?::|: | )([^\n\r\t]*)(?:\r?\n//[ \t]{2,}[^\n\r]*)*)|(?:/\*[ \t]?($TAGS)(?::|: | )(?:\*[^/]|[^*])*\*/)
```
or
```
(?:##[ \t]?($TAGS)(?::|: | )([^\n\r\t]*)(?:\r?\n##[ \t]{2,}[^\n\r\t]*)*)|
(?:%%[ \t]?($TAGS)(?::|: | )([^\n\r\t]*)(?:\r?\n%%[ \t]{2,}[^\n\r\t]*)*)|
(?://[ \t]?($TAGS)(?::|: | )([^\n\r\t]*)(?:\r?\n//[ \t]{2,}[^\n\r]*)*)|
(?:/\*[ \t]?($TAGS)(?::|: | )(?:\*[^/]|[^*])*\*/)
```
 The changes made to this expression are as follows:
 - The `/` character does not need to be escaped for Rust regex. `\/` -> `/`
 - Rust regex does not support lookbehind, specifically the chunk `\*(?!\/)` in `(?:\/\*[ \t]?($TAGS)(?::|: | )(?:\*(?!\/)|[^*])*\*\/)` which looks for a `*` _not_ followed by a `/`. This was replaced with a _(Less correct)_ `\*[^/]`. This leads to errors in specific comments like this:
     ```C++
     /* TAG: C style block comment
     with a * next to the end comment string.
     **/
     ```
     This issue occurs for any comment with an odd number of `*` directly before the `*/` string. This is just a result of the limited functionality, but should not be a huge issue for my use case (I tend to have newlines before the `*\` anyway).

**Comment by Awbmilne** [comment]
\close

**Comment by mrtnbrst** [comment]
`  "todo-tree.regex.regex": "(?:##[ \\t]?($TAGS)(?::|: | )([^\\n\\r\\t]*)(?:\\r?\\n##[ \\t]{2,}[^\\n\\r\\t]*)*)|(?:%[ \\t]?($TAGS)(?::|: | )([^\\n\\r\\t]*)(?:\\r?\\n%%[ \\t]{2,}[^\\n\\r\\t]*)*)|(?:%%[ \\t]?($TAGS)(?::|: | )([^\\n\\r\\t]*)(?:\\r?\\n%[ \\t]{2,}[^\\n\\r\\t]*)*)|(?://[ \\t]?($TAGS)(?::|: | )([^\\n\\r\\t]*)(?:\\r?\\n//[ \\t]{2,}[^\\n\\r]*)*)|(?:/\\*[ \\t]?($TAGS)(?::|: | )(?:\\*[^/]|[^*])*\\*/)",
  "todo-tree.filtering.includeGlobs": ["**/*"]`

I ended up using this adaption instead, as it also works for single "%" comment that are also possible in matlab

**Comment by Awbmilne** [comment]
Long time update, I have found that this regex can be really bad for deep repos, or more specifically opening deep configuration file directories for applications as it creates a pile up of very heavy regex calculations. Discovered by running VsCode over SSH on synology box, viewing docker Plex config. Slammed by CPU at 100% with ripgrep calls seemingly indefinitely.
