### ISSUE TITLE
Todo Tree panel doesn't show up in Explorer pane

### ISSUE THREAD

**Issue by gijsbeijer** [Gruntfuggly/todo-tree#532]
I'm having the same problem as described in #131.

I have version 0.0.213 installed but the panel still does not show up. Anyone else experiencing this?

Regards Gijs

**Comment by Gruntfuggly** [comment]
If you want the panel shown in the explorer pane, you can just drag it from the activity bar into the explorer pane.

Historically, there used to be two views (one on the explorer pane, and one in a separate view in the activity bar) but now that views can be dragged anywhere in the window, there is no need for multiple views.

**Comment by gijsbeijer** [comment]
Wow I can't believe I didn't know about this!

Seriously, sorry to have bothered you with this 🙈

**Comment by Gruntfuggly** [comment]
😁 No problem  - thanks for opening an issue rather than leaving a 1 star review (as somebody else did 🙁 ) for exactly the same problem.

**Comment by singhravi1** [comment]
I have my activity bar hidden, which led me to this issue. Thanks for the suggestion!
