### ISSUE TITLE
Does not recognize FIX or FIXIT as the FIXME node

### ISSUE THREAD

**Issue by MayankMurali** [Gruntfuggly/todo-tree#533]
Hi, first of all, I really appreciate this extension. It helps me well with my work. 
I have _v0.0.213_ installed on my VS Code (Windows) and I've noticed the tags `FIXIT` or `FIX` doesn't get recognized as the `FIXME` node on the tree. 

Thanks.

**Comment by Gruntfuggly** [comment]
Have you added `FIXIT` and `FIX` as tags? If not, you can add them easily using `Todo Tree: Add Tag`.

**Comment by MayankMurali** [comment]
Ah, I see. Sorry I did not add them beforehand. It works now. 
Thanks!

**Comment by Gruntfuggly** [comment]
If you want to treat them all as "FIXME" (for configuring highlights, for example) you can use:
```
    "todo-tree.general.tagGroups": {
        "FIXME": [
            "FIXME",
            "FIXIT",
            "FIX",
        ]
    },
```
