### ISSUE TITLE
Why is my status Unresponsive  

### ISSUE THREAD

**Issue by YangZhaocool** [Gruntfuggly/todo-tree#537]
![image](https://user-images.githubusercontent.com/31984495/127121208-dd191d10-6fe4-4191-bd26-5e36e6e47bfb.png)
Why is my status Unresponsive  
win 10
vscode 1.58.2

**Comment by Gruntfuggly** [comment]
Sorry, I have no idea - can you post your todo-tree settings?

**Comment by YangZhaocool** [comment]
`  "vetur.validation.template": false,  
  // 默认的突出显示  
  "todo-tree.highlights.defaultHighlight": {  
    "icon": "alert", // 默认字体  
    //"type": "text", // 默认高亮类型  
    //"foreground": "red", //文字颜色  
    //"background": "white", //背景颜色  
    "opacity": 10, //透明度  
    "iconColour": "blue", //默认图标颜色  
    // "fontWeight": "bold",  
    // "type": "text",  
    "gutterIcon": true // 图标是否在代码插槽中显示  
  },  
  // 显示的标签列表  
  "todo-tree.general.tags": [  
    "BUG",  
    "HACK",  
    "FIXME",  
    "TODO",  
    "XXX",  
    "!",  
    "??",  
  ],  
  // 显示的配置  
  "todo-tree.highlights.customHighlight": {  
    "BUG": {  
      "icon": "bug"  
    },  
    "FIXME": {  
      "icon": "flame"  
    },  
    "TODO": {  
      "icon": "check",  
      //"foreground": "#FF8C00", 
      "iconColour": "yellow", 
      // "type": "line"
    },
    "!": {  
      "icon": "alert",  
      "iconColour": "RED",  
      "color": "#0000ff",
      "backgroundColor": "#ff0000",
      //"type": "text"
    },
    "??": {
      "icon": "book",
      "iconColour": "#F60",
      "color": "#0000ff",
      "backgroundColor": "#ff0000",
    },
  },
  "todo-tree.filtering.ignoreGitSubmodules": true,
  "todo-tree.general.revealBehaviour": "start of line",
  "todo-tree.tree.scanMode": "workspace",
  "todo-tree.regex.regex": "((//|#|<!--|;|/\\*|\\*|^)\\s*($TAGS)|^\\s*- \\[ \\])",
  "todo-tree.general.enableFileWatcher": true,
  "todo-tree.ripgrep.ripgrepMaxBuffer": 2000,
  "todo-tree.filtering.includeGlobs": [
    "**/src/*",
    "**/src/**/*"
  ],
  "todo-tree.tree.autoRefresh": false,`

**Comment by YangZhaocool** [comment]
"todo-tree.highlights.defaultHighlight": {
    "icon": "alert",
    "opacity": 10, 
    "iconColour": "blue", 
    "gutterIcon": true 
  },
  "todo-tree.general.tags": [
    "BUG",
    "HACK",
    "FIXME",
    "TODO",
    "XXX",
    "!",
    "??",
  ],

  "todo-tree.highlights.customHighlight": {
    "BUG": {
      "icon": "bug"
    },
    "FIXME": {
      "icon": "flame"
    },
    "TODO": {
      "icon": "check",
      "iconColour": "yellow", 
    },
    "!": {
      "icon": "alert",
      "iconColour": "RED",
      "color": "#0000ff",
      "backgroundColor": "#ff0000",
    },
    "??": {
      "icon": "book",
      "iconColour": "#F60",
      "color": "#0000ff",
      "backgroundColor": "#ff0000",
    },
  },
  "todo-tree.filtering.ignoreGitSubmodules": true,
  "todo-tree.general.revealBehaviour": "start of line",
  "todo-tree.tree.scanMode": "workspace",
  "todo-tree.regex.regex": "((//|#|<!--|;|/\\*|\\*|^)\\s*($TAGS)|^\\s*- \\[ \\])",
  "todo-tree.general.enableFileWatcher": true,
  "todo-tree.ripgrep.ripgrepMaxBuffer": 2000,
  "todo-tree.filtering.includeGlobs": [
    "**/src/*",
    "**/src/**/*"
  ],
  "todo-tree.tree.autoRefresh": false,

**Comment by YangZhaocool** [comment]
Thanks

**Comment by Gruntfuggly** [comment]
Try turning off the filewatcher - it's not really needed unless files are being modified outside of vscode.
```
todo-tree.general.enableFileWatcher": false
```

**Comment by Gruntfuggly** [comment]
Also, are you include globs working correctly? They should be absolute paths, so unless you have a root folder on your machine `/src`, they won't be working. You probably want `**/src/**` instead, if you really want to limit the search to the src folder.

**Comment by YangZhaocool** [comment]
> Also, are you include globs working correctly? They should be absolute paths, so unless you have a root folder on your machine `/src`, they won't be working. You probably want `**/src/**` instead, if you really want to limit the search to the src folder.

Sorry I copied it wrong   in fact  "**/src/*", "**/src/**/*"

**Comment by YangZhaocool** [comment]
> Try turning off the filewatcher - it's not really needed unless files are being modified outside of vscode.
> 
> ```
> todo-tree.general.enableFileWatcher": false
> ```

I did that but the problem remained

**Comment by YangZhaocool** [comment]
I don't know why the problem appears but it doesn't seem to affect the use

**Comment by Gruntfuggly** [comment]
It may just be that the search is blocking the thread. If it's still working OK, then I probably wouldn't worry about it. The extensions host seems to report odd things that don't always make much sense to me.

You could trying commenting out all the settings and use the defaults and see if that makes any difference.

**Comment by Gruntfuggly** [comment]
Regarding the include globs - my comment is still valid. They should be absolute paths - they are not relative to the workspace.

**Comment by YangZhaocool** [comment]
Thank you very much for your reply.
