### ISSUE TITLE
Grouping by tag yields different results

### ISSUE THREAD

**Issue by DEberhardt** [Gruntfuggly/todo-tree#538]
Issue Type: <b>Bug</b>

Hello,

sometimes, the counters seem to reset? (but not all)
![image](https://user-images.githubusercontent.com/44290340/127735558-c31c83a4-4f14-4e13-913c-b15b150c9381.png)

Here a screenshot
![image](https://user-images.githubusercontent.com/44290340/127735564-7167130f-f175-4d17-89c4-1d5d691a1db4.png)

Workaround: Click ungroup by tag, Group by Tag for recalculation (Refresh doesn't do it)

apologies, don't know how to describe this any better....

as far as bugs go, this is low priority, but I'm curious as to what would cause things like this.

Thank you for your work!

Extension version: 0.0.213
VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (23.06GB free)|
|Process Argv|--crash-reporter-id efc3d77d-4b9d-44d6-894f-bd5aee3260eb|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490

```

</details>

**Comment by Gruntfuggly** [comment]
I've just uploaded a new version which has some fixes for grouping by tag. Could you please try it and let me know if it is still an issue?

**Comment by DEberhardt** [comment]
Hello, no changes when clicking around manually. I have failed to record when exactly that happens, but I think you've successfully squashed this bug :)

Happy to close

**Comment by Gruntfuggly** [comment]
OK thanks - feel free to reopen if you find any problems.
