### ISSUE TITLE
Feature request: ability to unset highlight settings

### ISSUE THREAD

**Issue by baincd** [Gruntfuggly/todo-tree#539]
Many many thanks again for creating this extension.

I have a use case where I would like to unset (or reset) highlight settings.  Let me explain:

I have the following highlight configuration in my User settings:

![image](https://user-images.githubusercontent.com/5075659/128782974-10442ff7-8afa-461b-bfa2-2a43a15a6326.png)

However, I have one workspace where I do not want this todo to be highlighted (though I still want Todo Tree to find the todo so it will display in the Todo Tree sidebar).  So I want a way to be able to "unset" (or "reset") some or all the highlight settings for the todo.  

One idea would be to use the value of null to mean there is no setting, like in the following mockup (the left is the User settings - same as above, and the right is the workspace settings)

![image](https://user-images.githubusercontent.com/5075659/128783320-ce305d1a-3f50-4145-a245-0d141084bdf1.png)

(note the above is a mockup - setting highlight options to null causes errors and the todo sidebar to not work).

I used null as an idea, but it would be helpful to have any way to be able to unset highlight values

**Comment by Gruntfuggly** [comment]
You should be able to do this by setting the colours to `"#00000000"` - setting the alpha channel to 0 means that the colour is totally transparent.

**Comment by baincd** [comment]
For the background, `"#00000000"` works.  But for the foreground, it makes the text invisible:

![image](https://user-images.githubusercontent.com/5075659/128859884-52542a71-bf74-4d09-8cf5-f5b2ae0b88ae.png)

(and ignore iconColour - I shouldn't have included that in my example, I don't think there is a use case for unsetting that)

**Comment by Gruntfuggly** [comment]
Ah yes - you're right, it won't work for the foreground. The problem is the way that VSCode provides the settings to the extension - it merges the various settings from the user/workspace settings. I'll see if there is a way to make it work.

**Comment by baincd** [comment]
This is a nice-to-have but a low priority.  It's kind of a unique use case, and there is a workaround (I can set the foreground to be the same color as the theme I'm using).

**Comment by baincd** [comment]
I actually don't need this feature anymore, and it doesn't seem to impact others.  I don't see this being enough of a priority to keep open, therefore I'm closing this issue.
