### ISSUE TITLE
Error: stdout maxBuffer exceeded

### ISSUE THREAD

**Issue by honzabilek4** [Gruntfuggly/todo-tree#54]
Hi, 
this extension doesn't work for me at all. It displays an error and then shows an empty list.

![screen shot 2018-07-15 at 18 09 32](https://user-images.githubusercontent.com/7890555/42735779-617d1d96-885a-11e8-9d50-4a7e11e2c206.png)

![screen shot 2018-07-15 at 18 11 07](https://user-images.githubusercontent.com/7890555/42735787-78b5ee34-885a-11e8-919e-f485ad6b6ab5.png)

I'm not sure how to debug this extension, so reach me out if you need to retireve more info.

**VSCode Version 1.25.1**
**macOS High Sierra 10.13.6**

**Comment by Gruntfuggly** [comment]
Do you have a lot of todo's in your workspace? It looks like it's finding a lot of stuff. You could either try limiting where it is searching using `todo-tree.rootFolder` or increase the buffer size with `todo-tree. ripgrepMaxBuffer`. By detault it is 200Kb, so try increasing it to see if that helps.

**Comment by honzabilek4** [comment]
Thanks!
There was a stats file generated by `webpack-bundle-analyzer` wich I didn't notice at a first glance. 
Deleted the file and changed the `rootFolder` to my `./src` folder. All good now.
