### ISSUE TITLE
Highlighting looks bad in dark mode

### ISSUE THREAD

**Issue by gerroon** [Gruntfuggly/todo-tree#540]
Please see the picture

![Screenshot at 02-43-20](https://user-images.githubusercontent.com/8519469/129322321-c491b01f-3283-40c9-afef-2a38491fd98b.png)

**Comment by Gruntfuggly** [comment]
That is just the default highlight - the colours are fully customisable. It would be impossible to have a default that worked well with every theme.

You can try enabling `todo-tree.highlights.useColourScheme` to get some basic colours as a started, or look at `todo-tree.highlights.defaultHighlight` and `todo-tree.highlights.customHighlight` for more advanced features. 
https://github.com/Gruntfuggly/todo-tree#highlighting

**Comment by gerroon** [comment]
Hey thanks for the pointers. I will givem them a try
