### ISSUE TITLE
(Missing?) Feature request: Custom highlight type - Capture groups

### ISSUE THREAD

**Issue by SentientCoffee** [Gruntfuggly/todo-tree#541]
I've seen in other issues (namely [#506](https://github.com/Gruntfuggly/todo-tree/issues/506#issuecomment-829179788) and [#511](https://github.com/Gruntfuggly/todo-tree/issues/511#issuecomment-841842026)) that you can apparently highlight by capture group based on your regex. However, looking through the repository on the master branch I don't see any code that would relate to this, or any place where this kind of custom highlighting would apply.

Is this something that is coming in a later update? I see the comment was in April of this year, and that the last commit was 4 months ago, maybe it was a feature that was in master and then got scrapped? I'd really like to see this in VS Code, since it seems to be super useful for me and my weird comment tags.

-----------------------------------------------------------------------------------------------------------------
For example, I'd like to be able to get something like this working:
```cs
//
// @Note: Usage below
// @Note: Type is the return type of the function, params is the parameters the function receives
//

/* @Note(SentientCoffee):
 * Any and all arrays inside structs marshalled to C++ must be initialized before trying to read data
 * back from the plugin, otherwise when the pointer is marshalled, the pointed-to struct will not have enough space
 * to store the data. This is sorta cursed, but I can't think of a better way to do it. */

//
// @Reference: https://docs.microsoft.com/en-us/dotnet/framework/interop/marshaling-classes-structures-and-unions
// @Reference: https://www.codeproject.com/Questions/299085/Marshal-structures-passed-as-pointers-to-functions
//
// @Todo(SentientCoffee): Change this to binary format
// @Random(SentientCoffee): This should not highlight the comment itself...
//
// @brief: This is a brief
// @param a: Param A
// @param b: Param B
// @return: Return value(s)
//
// @Temp: This should be in red...
// @Temporary; This is fine.
//
// @Test,
// @Testing?
//
//NOTE: Leaps between leapTo and leapFrom transforms
//TODO: Split this by map type
//
// @brief: Places, scales and activates all viewports according to the number of players currently active.
// @param: Number of players
// @param: List of each player's camera
//
```
where I can denote things like `brief`, `param`, `note`, `return`, `todo`, `temp`, `test`, etc. in my `general.tags` config, while still being able to highlight things like the `Random` line. It should also highlight the tag regardless whether or not there is a `@` symbol before the tag, or a `,`, `;`, `:`, or `?` after (but if there is, it should highlight them too). Anything in between parentheses after the tag should also be highlighted, up to the `,`, `;`, `:`, or `?`, but not anything after it. However some kinds of tags I would like to highlight the rest of the line so I capture it too.

I already have the regex for this:
```cs
"(?<!://)(?<=//|/\\*|///|/\\*\\*|#|<!--)[^\\S\\r\\n]*((?:(?:@?($TAGS)[,:;?]?)|(?:@(\\w+|@+)[,:;?]?))(\\(\\w+\\)[,:;?]?)?)(.*)"
```

but I would like to capture groups 1 (tags with optional `@` and `[,:;?]`) and 4 (parentheses) by default for highlighting, and for things like `temp` and `reference` to also capture group 5 (anything after `,`, `;`, `:` or `?`).

**Comment by Gruntfuggly** [comment]
The capture groups highlighting is contained within the code for handling "subtags".

See `todo-tree.regex.subTagRegex` (https://github.com/Gruntfuggly/todo-tree#configuration). You'll need to scroll down a bit, but if the subTagRegex contains a capture group it can be used.

It maybe too limited for what you want though - I think it only allows one capture group at the moment.

I've had to deal with some personal issues over the last few months, so haven't had much time to work on the extension. 🙁

**Comment by Gruntfuggly** [comment]
I've finally got round to making a few changes. There was a commit in my local repo, which wasn't in the previous version, that might help now. Please try the latest (0.0.214) version and see if it improves things.

**Comment by SentientCoffee** [comment]
Just tried out the new features, they work great on my end. Thanks for everything, and I hope things are okay with the personal issues you mentioned.

**Comment by Gruntfuggly** [comment]
Thank you  - yes all resolved now.
