### ISSUE TITLE
[Feature Request] Option to show the TODO tree in the file explorer tab

### ISSUE THREAD

**Issue by vernonranis** [Gruntfuggly/todo-tree#543]
Awesome extension! Not sure if this is already requested before but can we have an option to put the TODO tree in the explorer tab where the workspace is?

see picture below.

https://ibb.co/hLNC1br

**Comment by danemtsov** [comment]
See #489 or #532.

You can drag the tree view into any pane of the activity bar, or even into the panel:

![Tree view in panel](https://user-images.githubusercontent.com/49734973/130326630-1dbf1cfd-856d-44d0-ac4b-2d7f74e87645.png)

**Comment by vernonranis** [comment]
Got it working. Thanks!

![image](https://user-images.githubusercontent.com/60091485/130335918-55489a98-4102-4a89-8eb6-e721ddee478a.png)
