### ISSUE TITLE
Support for SQL comments

### ISSUE THREAD

**Issue by Leccho** [Gruntfuggly/todo-tree#545]
It doesn't seems to work with SQL comments unless you add `//`:
![image](https://user-images.githubusercontent.com/2791678/130808762-7a124187-27ac-4d03-b11f-413ef2534f58.png)

**Comment by Gruntfuggly** [comment]
Yes, as kanlukasz says, trying to cater for everything is impossible, so the default covers a simple set of cases.
There is an example for PSQL in the wiki (https://github.com/Gruntfuggly/todo-tree/wiki) but if you think it needs more information, please post your suggested config and I'll update it.
