### ISSUE TITLE
question：What do I set for todo-tree.ripgrep.ripgrep

### ISSUE THREAD

**Issue by WangShuoran** [Gruntfuggly/todo-tree#546]
Hello, in readme, I know:  

```
todo-tree.ripgrep.ripgrep ("")
Normally, the extension will locate ripgrep itself as and when required.
If you want to use an alternate version of ripgrep, set this to point to wherever it is installed.
```

But, I don't know what I should set. Is it a file or a folder? or other?

Thank you for your advice!

**Comment by Gruntfuggly** [comment]
You don't need to set it unless you have a different version of ripgrep installed that you want to use. VSCode ships with a version that the extension also uses.

If you do want to set it to something else, it should point to the executable.

**Comment by WangShuoran** [comment]
Thank you for your attention!  
I need to choose it. Because I use it in similar vscode software. So I need to specify it.
In you comment, I need to point to the executable.

My computer operating system is Windows. Do I need open https://github.com/BurntSushi/ripgrep?
And download ripgrep-13.0.0-i686-pc-windows-msvc? And extract it.
After those operations. I need set todo-tree.ripgrep.ripgrep to extract file rg.exe?

I wish you a good mood every day!

**Comment by Gruntfuggly** [comment]
Can you explain what you mean by "similar vscode software" ?  The extension should work correctly with the version of ripgrep that is built into vscode, so if you haven't already installed it, it should already work.

If you really do want to install it, then yes, download and install and then set the setting to the full path to the rg.exe.

**Comment by WangShuoran** [comment]
I mentioned "similar vscode software" is "微信开发者工具", Vscode is embeded in this software. This software is used to develop wechat small app(a web program). I need rg.exe to give todo-tree work properly.

**Comment by WangShuoran** [comment]
One more thing: the rg.exe is in https://github.com/BurntSushi/ripgrep
