### ISSUE TITLE
show tree or flat list don't work

### ISSUE THREAD

**Issue by ppazos** [Gruntfuggly/todo-tree#547]
Just executed the commands and to nothing.

**Comment by Gruntfuggly** [comment]
Could you provide some more information please? Does it show anything in the normal tree view? A screen shot would be really useful.

**Comment by ppazos** [comment]
Let me check, though nothing opens when I try to execute the commands from the command picker.

**Comment by Gruntfuggly** [comment]
The commands are not really intended to be used directly - they are used by buttons in the tree view header. The commands should still change the view though, if you want to use them.

They won't open the view - they just change it's layout.

**Comment by Gruntfuggly** [comment]
Did you manage to get it working?

**Comment by FooNagi** [comment]
I think the issue here is he's using the TODO tree with a single file and not with a workspace open that could have multiple folders in it

![image](https://user-images.githubusercontent.com/43235725/134769902-3a80d29c-a508-4de0-8b63-cd1f95709099.png)

**Comment by Gruntfuggly** [comment]
Yes, that's how flat mode is intended to work. The original issue is not clear at all though.

Unless there is some more information forthcoming, I'll close the issue in a few days.

**Comment by FooNagi** [comment]
I believe I ran into the same issue before when I was using the TODO tree for a single file open in the editor, when I clicked tree/flat it just shows the same layout, however I discovered that it was primarily intended for multiple files and folders.

**Comment by Gruntfuggly** [comment]
It doesn't make much sense to have a tree view of files when there is only one file 8-)
