### ISSUE TITLE
Wiki pages word editable

### ISSUE THREAD

**Issue by om4csaba** [Gruntfuggly/todo-tree#549]
Hi, 

I meant to be helpful and updated the Wiki's php example based on the latest changes (v0.0.214).

It turned out I was successful, but I think you should limit the editing capabilities to collaborators.

Here is the relevant documentation: https://docs.github.com/en/communities/documenting-your-project-with-wikis/changing-access-permissions-for-wikis

**Comment by Gruntfuggly** [comment]
Thanks for your contribution - to be honest, it would be great if people updated the wiki, so I'm happy to leave it open at the moment. If it causes a problem I can also revert it.

I don't think many people find the wiki anyway 🙁

**Comment by om4csaba** [comment]
I totally understand what you're saying. I would love to see a Wikipedia type "moderation after the edit" feature.

Speaking of the discoverability of the Wiki, I think some edits in the README can help. Unfortunately, I don't realy have time right now, but within a couple of weeks, I can give it a try if you are interested.

**Comment by Gruntfuggly** [comment]
Hi - I'm going to close this to try and keep the number of open issues manageable. Feel free to suggest any updates to the README. Anything that might help people get started instead of leaving a 1 star review (:disappointed:) would be much appreciated!
