### ISSUE TITLE
[Feature] Sharing configurations

### ISSUE THREAD

**Issue by IamLeTea** [Gruntfuggly/todo-tree#550]
Hi there, I love this extension. I'm not sure is an opportunity to enable sharing configurations like prettier? It could be used for multiple projects and multiple members with one configuration, thanks.🙂

https://prettier.io/docs/en/configuration.html#sharing-configurations

**Comment by Gruntfuggly** [comment]
I'm not sure I understand - how would this be a feature of the extension? I'm not sure what you want to add?

**Comment by joshmeads** [comment]
You can share your config via the `.vscode/settings.json` file, just commit it to git. Though ensure there is nothing you don't want shared in there.

**Comment by Gruntfuggly** [comment]
I'm going to close this because I think it was opened in the wrong repo. In any case, it doesn't really have anything to do with todo-tree.
