### ISSUE TITLE
Folders in .gitignore are checked when they are created

### ISSUE THREAD

**Issue by tanguyMichardiere** [Gruntfuggly/todo-tree#551]
I have a NextJS project (though my problem happens in other projects too), when running `npm run dev` the code is bundled into `.next`. This extension then searches (and finds) TODOs in this folder, even though it is in `.gitignore`. When I click the refresh button in the extension's view, the TODOs found in `.next` go away.

I tried setting `todo-tree.general.rootFolder` to the absolute path of my project, no luck.

Here is the normal debug output (when i click the refresh button):
```
16:40:40.453 Searching /Users/tanguy/programs/web_presence/resume...
16:40:40.453 Writing pattern file:/Users/tanguy/Library/Application Support/Code/User/workspaceStorage/6cc114d18360563ad0883b6c4e6d97f0/Gruntfuggly.todo-tree/10o4sxia9j.txt
16:40:40.454 Pattern:(//|#|<!--|/\*|^\s*\*)\s*(XXX|TODO|HACK|FIXME|BUG)
16:40:40.454 Command: /opt/homebrew/bin/rg --no-messages --vimgrep -H --column --line-number --color never --max-columns=1000 --no-config  -f "/Users/tanguy/Library/Application Support/Code/User/workspaceStorage/6cc114d18360563ad0883b6c4e6d97f0/Gruntfuggly.todo-tree/10o4sxia9j.txt" -g "!**/node_modules" "/Users/tanguy/programs/web_presence/resume"
16:40:40.467 Search results:
/Users/tanguy/programs/web_presence/resume/src/pages/_app.tsx:8:1:// TODO: check memo

16:40:40.474  Match (File): {"fsPath":"/Users/tanguy/programs/web_presence/resume/src/pages/_app.tsx","line":8,"column":1,"match":"// TODO: check memo","uri":{"$mid":1,"path":"/Users/tanguy/programs/web_presence/resume/src/pages/_app.tsx","scheme":"file"}}
16:40:40.475 Found 1 items
16:40:40.475 Applying globs to 1 items...
16:40:40.475 Remaining items: 1
```

The debug output when it searches in ignored folders is 1785 lines long so I put it on [pastebin](https://pastebin.com/vNTppTPg) but here is a part with a ripgrep invocation:
```
16:42:07.175 Searching /Users/tanguy/programs/web_presence/resume/.next/server/pages-manifest.json...
16:42:07.176 Writing pattern file:/Users/tanguy/Library/Application Support/Code/User/workspaceStorage/6cc114d18360563ad0883b6c4e6d97f0/Gruntfuggly.todo-tree/2rp48lfzmq.txt
16:42:07.176 Pattern:(//|#|<!--|/\*|^\s*\*)\s*(XXX|TODO|HACK|FIXME|BUG)
16:42:07.176 Command: /opt/homebrew/bin/rg --no-messages --vimgrep -H --column --line-number --color never --max-columns=1000 --no-config  -f "/Users/tanguy/Library/Application Support/Code/User/workspaceStorage/6cc114d18360563ad0883b6c4e6d97f0/Gruntfuggly.todo-tree/2rp48lfzmq.txt" -g "!**/node_modules" "/Users/tanguy/programs/web_presence/resume/.next/server/pages-manifest.json"
16:42:07.209 Searching /Users/tanguy/programs/web_presence/resume/.next/server/pages/_error.js...
16:42:07.209 Writing pattern file:/Users/tanguy/Library/Application Support/Code/User/workspaceStorage/6cc114d18360563ad0883b6c4e6d97f0/Gruntfuggly.todo-tree/1x3n4zido3.txt
16:42:07.209 Pattern:(//|#|<!--|/\*|^\s*\*)\s*(XXX|TODO|HACK|FIXME|BUG)
16:42:07.209 Command: /opt/homebrew/bin/rg --no-messages --vimgrep -H --column --line-number --color never --max-columns=1000 --no-config  -f "/Users/tanguy/Library/Application Support/Code/User/workspaceStorage/6cc114d18360563ad0883b6c4e6d97f0/Gruntfuggly.todo-tree/1x3n4zido3.txt" -g "!**/node_modules" "/Users/tanguy/programs/web_presence/resume/.next/server/pages/_error.js"
16:42:07.214 Searching /Users/tanguy/programs/web_presence/resume/.next/server/pages/_document.js...
16:42:07.215 Writing pattern file:/Users/tanguy/Library/Application Support/Code/User/workspaceStorage/6cc114d18360563ad0883b6c4e6d97f0/Gruntfuggly.todo-tree/2n6iuaj7yw.txt
16:42:07.215 Pattern:(//|#|<!--|/\*|^\s*\*)\s*(XXX|TODO|HACK|FIXME|BUG)
16:42:07.215 Command: /opt/homebrew/bin/rg --no-messages --vimgrep -H --column --line-number --color never --max-columns=1000 --no-config  -f "/Users/tanguy/Library/Application Support/Code/User/workspaceStorage/6cc114d18360563ad0883b6c4e6d97f0/Gruntfuggly.todo-tree/2n6iuaj7yw.txt" -g "!**/node_modules" "/Users/tanguy/programs/web_presence/resume/.next/server/pages/_document.js"
16:42:07.225 Searching /Users/tanguy/programs/web_presence/resume/.next/server/pages/_app.js...
16:42:07.225 Writing pattern file:/Users/tanguy/Library/Application Support/Code/User/workspaceStorage/6cc114d18360563ad0883b6c4e6d97f0/Gruntfuggly.todo-tree/2fu4le9y5q.txt
16:42:07.225 Pattern:(//|#|<!--|/\*|^\s*\*)\s*(XXX|TODO|HACK|FIXME|BUG)
16:42:07.225 Command: /opt/homebrew/bin/rg --no-messages --vimgrep -H --column --line-number --color never --max-columns=1000 --no-config  -f "/Users/tanguy/Library/Application Support/Code/User/workspaceStorage/6cc114d18360563ad0883b6c4e6d97f0/Gruntfuggly.todo-tree/2fu4le9y5q.txt" -g "!**/node_modules" "/Users/tanguy/programs/web_presence/resume/.next/server/pages/_app.js"
16:42:07.234 Search results:
/Users/tanguy/programs/web_presence/resume/.next/server/pages/_app.js:22:3437:[Omitted long line with 1 matches]
```

I should add that I'm on MacOS Big Sur, the last version, on an M1 MacBook Air. I have the last version of VS Code and of this extension, and i have ripgrep 13.0.0 (I have the extension set up to use my version, but the exact same problem occurs without it too).

**Comment by Gruntfuggly** [comment]
You should be able to add `**/*.next` to the exclude globs (`todo-tree.filtering.excludeGlobs`). For more info see https://github.com/Gruntfuggly/todo-tree#excluding-files-and-folders

**Comment by tanguyMichardiere** [comment]
So I just tried that and it didn't change, I get the same TODOs in `.next`.

I was under the impression that it's a bug because I think it's not very user friendly to have to add every build folder in the exclude globs while they are already in `.gitignore`. And ripgrep ignores them well when it's invoked in the workspace folder, it's just that it's invoked in the build folder:
```
16:42:07.209 Command: /opt/homebrew/bin/rg [options] "/Users/tanguy/programs/web_presence/resume/.next/server/pages/_error.js"
```

**Comment by Gruntfuggly** [comment]
You're correct that it should honour the `.gitignore` file by default, so something strange is going on. If the exclude glob didn't work either then maybe ripgrep is not getting the correct parameters?

Also, there is something not right with your set up - from your second chunk of debug output it looks like it is generating a ripgrep search for each file individually, which doesn't make sense.

Could you post all your todo-tree settings so I can check them? I can also try and recreate it here.

**Comment by Gruntfuggly** [comment]
In fact that may be the issue - it is explicitly searching within the `.next` folder, so it won't be able to ignore anything.

I've just looked at your pastebin, and it looks like you have the file watcher setting turned on - if so that will be the issue, because that is detected the files changing inside `.next` and then searching the explicity.

The file watcher is only useful if there are other processes running which can update files externally from vscode.

**Comment by tanguyMichardiere** [comment]
Ah, I just tried disabling the file watcher and you are right, it was causing this. I thought if I didn't enable it I would have to manually refresh to see the updates.

Thanks!

**Comment by Gruntfuggly** [comment]
I need to add a warning to the README.md about the file watcher - it has a very limited use and quite a few issues have been logged it's been enabled unnecessarily.

Glad it's working!
