### ISSUE TITLE
Ability to toggle highlights with a keybind (or otherwise dinamically)

### ISSUE THREAD

**Issue by Arxareon** [Gruntfuggly/todo-tree#553]
Hey!

A simple suggestion, as the title implies, the addition of a keyboard shortcut that could flip the value of `todo-tree.highlights.enabled` would be useful to me. I like highlights but I don't want them all the time. Also, I don't want to have to go into the settings and change it there, or, have another separate extension solution just to change this value fast.

Alternatively, if that would be possible, a setting could be added to only enable highlights while the TODO tab is viewed on the Side Bar, that'd be the best - again, if it's possible.
Or, a small button or check option within the TODOs tab in the Side Bar somewhere, at the top or in a context menu perhaps.

**Comment by Gruntfuggly** [comment]
If you set the status bar to show the total count (or one of the other options), you can also set it to toggle highlights when you click on it, e.g.
```
    "todo-tree.general.statusBar": "total",
    "todo-tree.general.statusBarClickBehaviour": "toggle highlights",
```

**Comment by Arxareon** [comment]
Aha! That works well enough for me.
Thanks you for the swift response!

**Comment by Gruntfuggly** [comment]
No problem. 🙂
