### ISSUE TITLE
侧边栏图标不显示

### ISSUE THREAD

**Issue by YSHIDM** [Gruntfuggly/todo-tree#557]
侧边栏图标不显示，如图：
![image](https://user-images.githubusercontent.com/7659872/135014553-cbe38b4c-a660-4c57-b4b2-a2169b2ea6f6.png)
是不是需要执行什么命令

**Comment by Gruntfuggly** [comment]
Has the installation worked correctly? Could you please enable `todo-tree.general.debug` and see if there is a new channel called "Todo Tree" available in the drop down or the Output window.

Also - please can you check the console log (Help -> Toggle Developer Tools, then select Console).

**Comment by chenxinJC** [comment]
14:36:49.125 Searching d:\Learn\vue...
14:36:49.227 Writing pattern file:c:\Users\Administrator\AppData\Roaming\Code\User\workspaceStorage\6a2d37063fd86c0a6920973ac9d5296c\Gruntfuggly.todo-tree\2oxjtz9itn.txt
14:36:49.244 Pattern:((%|#|//|<!--|^\s*\*)\s*(tag|note|done|TODO|FIXME)|^\s*- \[ \])
14:36:49.244 Command: "d:\Program Files\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg.exe" --no-messages --vimgrep -H --column --line-number --color never --max-columns=1000 --no-config  -i  -f "c:\Users\Administrator\AppData\Roaming\Code\User\workspaceStorage\6a2d37063fd86c0a6920973ac9d5296c\Gruntfuggly.todo-tree\2oxjtz9itn.txt" -g "!**/node_modules" "d:\Learn\vue"
14:36:49.531 Found 0 items
14:36:49.531 Applying globs to 0 items...
14:36:49.531 Remaining items: 0

**Comment by Gruntfuggly** [comment]
Hi - I'm not sure why your last post is not displayed, but I can see it in an email?

From the debug log, it looks like it is not finding anything. Could you please post your settings?

**Comment by Gruntfuggly** [comment]
I'm going to close this - please feel free to reopen if you can provide some further information.

**Comment by YSHIDM** [comment]
找到了，在侧边栏与其他功能合并到一起了

**Comment by wangliguang** [comment]
@YSHIDM  怎么解决的呢
