### ISSUE TITLE
[Feature Request] Per-file statusbar items

### ISSUE THREAD

**Issue by lonix1** [Gruntfuggly/todo-tree#558]
Hey again @Gruntfuggly. I'm using [another extension](https://marketplace.visualstudio.com/items?itemName=fooxly.provision-bar) (in addition to this one, of course) which shows "todos" in the statusbar. It shows items per-file, which is really useful as I can quickly tell what is outstanding for a particular file.

I thought it would be nice if this extension - the mother of all vscode todo extensions - would support that functionality at some point?

Please feel free to close, there's a good chance this sort of feature is out of scope. I just wanted to let you know about it. (Even so, I'd recommend it for this extension's users- this one shows all items in one convenient place, and the other shows per file... a nice combo)

Thanks as always!

**Comment by Gruntfuggly** [comment]
You can set `todo-tree.general.statusBar` to `current file`. 🙂

**Comment by lonix1** [comment]
Lol you add so many new features sometimes I don't even know about them! :smile:

`current file` is great.

Note though that the extension I linked to has nice little extra behaviours, e.g it opens the file at that tag's line, shows multiple tags in a dropdown. Check it out for yourself to see what I mean. I still think that other extension is nice to have side by side (unless this extension has those features built in someday).

**Comment by Gruntfuggly** [comment]
This one should open the file at the tag line too? 

I'll have a look at it - I might be able to steal some features 😉  Thanks!
