### ISSUE TITLE
Exclude folders from search

### ISSUE THREAD

**Issue by Tuto96** [Gruntfuggly/todo-tree#56]
It will be very useful to add the option to be able to exclude folders from adding TODO's to the list, sometimes I don't want to see the TODO's inside my imported plugins.

**Comment by Gruntfuggly** [comment]
Hi - you can use `todo-tree.globs` for that. E.g., `todo-tree.globs: "!**/node_modules"` should prevent it from enter the node_modules folder.

**Comment by Gruntfuggly** [comment]
See https://github.com/isaacs/minimatch for more details of glob matching.

**Comment by udondan** [comment]
An example of this would be great in the readme. I think mostly everyone using this super helpful extension will have a need for filtering a vendor folder.

I read the docs of the linked glob module but it was not right away obvious to me how to exactly define the pattern. Glad I found this issue.

**Comment by Gruntfuggly** [comment]
Yes, it sounds like an example would be a good idea. There is actually an example in the configuration itself, but I guess you're unlikely to get there if you don't spot the globs settings.

I'll add an example to the README.md

**Comment by ajoslin103** [comment]
this was what I had to use to keep away all the TODO's in imported modules

  "todo-tree.excludeGlobs": [
    "**/node_modules/**"
  ],

**Comment by skatestyle** [comment]
Same problem as stated from @frudman
Any solutions?

**Comment by udondan** [comment]
The glob patterns simply are wrong. The whole file path of every found TODO occurrence will be matched against the glob patterns. This will work:

```
"todo-tree.excludeGlobs": [
        "**/node_modules/**", "**/dist/**"
],
```

**Comment by lguilhermee** [comment]
> The glob patterns simply are wrong. The whole file path of every found TODO occurrence will be matched against the glob patterns. This will work:
> 
> ```
> "todo-tree.excludeGlobs": [
>         "**/node_modules/**", "**/dist/**"
> ],
> ```

thanks, solved my issue =)

**Comment by Zebiano** [comment]
It's now `todo-tree.filtering.excludeGlobs`, instead of `todo-tree.excludeGlobs`. Just as a heads-up.

**Comment by patricio-ezequiel-hondagneu-roig** [comment]
> The glob patterns simply are wrong. The whole file path of every found TODO occurrence will be matched against the glob patterns. This will work:
> 
> ```
> "todo-tree.excludeGlobs": [
>         "**/node_modules/**", "**/dist/**"
> ],
> ```

I'm from the future. This fix works like a charm. Thanks!
