### ISSUE TITLE
Duplicate entries in tree in Tags Only View, Group by Tag

### ISSUE THREAD

**Issue by baincd** [Gruntfuggly/todo-tree#562]
Steps to recreate:
1. Set Tree view to Tags Only View, Group By Tag
2. Open 2 files
3. Add a TODO to file 1
4. Add a TODO to file 2
  - As you are editing the TODO in file 2, the TODO is duplicated in the tree

![Peek 2021-10-04 18-48](https://user-images.githubusercontent.com/5075659/135935189-40f2cf25-3d99-4cfc-992c-7eb1d06d9aa9.png)

**Comment by baincd** [comment]
This started happening in 0.0.214.  It does not occur in 0.0.213.

**Comment by baincd** [comment]
Also, this occurs even with the out-of-the-box settings

**Comment by Gruntfuggly** [comment]
That's odd - only seems to happen in some files for me. Will investigate.

**Comment by baincd** [comment]
It's weird, and took me a while to reliably recreate it.  In my example above, if I edit any TODO in file1 it does _not_ add duplicate entries to the tree.  However every TODO edited in file2 does create duplicate entries.

**Comment by mtoigo** [comment]
This happens to me as well in tree view. I can help to reproduce or troubleshoot if you want. When I hit the refresh button all of the duplicates go away. This is a GREAT extension and thank you so much for the work 👍

**Comment by mtoigo** [comment]
Lately this seems to have changed where hitting the refresh button doesn't clear up the issue. Thanks for addressing.

**Comment by iyigunform3** [comment]
This happens even if only a single file is opened for me. Refreshing the tree view clears most of the duplicate entries, but sometimes there's one or two duplicates remaining even after refreshing repeatedly.

**Comment by baincd** [comment]
@Gruntfuggly I found commit bf6458622fd60f864386c4a8f9089c794f49ed52 introduced this issue.

This issue only happens in the Tags Only View with Group By Tag enabled.  In this state, when the first TODO tag is created in file1 created, 2 tree nodes are created:
- The parent node with type='path' and fsPath=/path/to/file1
- The child node with type='todo' and fspath=/path/to/file1

When the TODO is added to file2, a new child node is created:
- The child node with type='todo' and fspath=/path/to/file2

After this point, when the TODO in file2 is edited the `child.fsPath === fullPath` condition is not true for the parent node and therefore the child nodes for file2 are not removed.  Each change to the TODO in file2 adds a child node without removing the previous child nodes.

Note that this does not happen when the TODO in file1 is edited because  `child.fsPath === fullPath` is true.

Reverting bf6458622fd60f864386c4a8f9089c794f49ed52 (changing the condition back to `child.fsPath === fullPath || child.isRootTagNode`) fixes this issue as the child nodes for file2 are removed when file2 is edited.

I'm not sure the reason bf6458622fd60f864386c4a8f9089c794f49ed52 was made.  The commit says "Fix group by tag", but I wasn't able to find any issues when I reverted the change (though I definitely did not do exhaustive testing).

Could this commit be reverted?  Or now that the root cause has been identified, maybe there is another way to fix this issue?  I'm happy to help anyway I can, please just let me know.

Thank you again for this awesome extension!

**Comment by mtoigo** [comment]
Thanks @baincd for figuring out the issue. If we put up a PR removing the change @Gruntfuggly would you be alright releasing a new version with the fix. This is a GREAT extension and it'll be awesome to have this bug solved.

**Comment by mtoigo** [comment]
@Gruntfuggly I have a PR up at https://github.com/Gruntfuggly/todo-tree/pull/660 for the change that @baincd suggested and also tested it locally and it looks to resolve the issue so I'm all set. The tests pass, but I'm not overall familiar enough with the code to say the overall impact. 

If this doesn't get fixed in this repo and anyone finds this bug you can just do the following on OS X:

1. Clone this repo, make the suggested change above in the source, `npm install` and then `npm run vscode:prepublish`
2. move out the installed todo-tree plugin from ~/.vscode/extensions and then just symlink in the checked out repo and maintain the original directory name.
3. Quit and restart VSCode

**Comment by baincd** [comment]
This issue is fixed in version 0.0.220 via #660. :tada:
