### ISSUE TITLE
Unknown configuration setting caused by non-visible characters

### ISSUE THREAD

**Issue by agov** [Gruntfuggly/todo-tree#57]
Copying the configuration keys from the extension description either from marketplace WebUI or VS Code description contains unexpected characters that are only visible when running cat -vet:

```
echo "todo‑tree.ripgrepMaxBuffer" | cat -vet
todo�M-^@M-^Qtree.ripgrepMaxBuffer$
```

The reason is possibly originating from README.md raw containing:
`todo&#8209;tree.ripgrepMaxBuffer`

`&#8209;` resolves to a hyphen in markdown, even the HTML source shows it correctly. But VS Code can not handle it as it seems

Using "Copy to Settings" in VS Code User Settings works fine

Using VS Code 1.25.1 and Chrome 67.0.3396.99 (Official Build) (64-bit)

**Comment by Gruntfuggly** [comment]
It's because at one point the README.md file would not display properly in the marketplace. I think it turned out to be fixed font formatting, but I was trying everything I could think of at the time.

Thanks for the PR - I'll include it in the next release.
