### ISSUE TITLE
Stable and/or configurable tag order in tree

### ISSUE THREAD

**Issue by memeplex** [Gruntfuggly/todo-tree#574]
Could you add a way to specify the tag order in the tree when grouping by tag? Or, short of that, maybe sort tags lexicographically so at least the order is stable? Sometimes when the tree is refreshed tags get reordered in arbitrary fashion. Thank you very much.

BTW, this extension is very well documented, has a lot of options and, from a cursory glance, your code is really clean, so kudos for the high quality of your work.

**Comment by Gruntfuggly** [comment]
Going to close this now due to inactivity. I think an update last year may have already addresses the issue, but feel free to re-open if you still have problems.
