### ISSUE TITLE
Markdown checkboxes no longer working

### ISSUE THREAD

**Issue by mhkeller** [Gruntfuggly/todo-tree#577]
This plugin used to find things like

```
- [ ] this line was highlighted as a todo
- [x] this was already done and was not picked up 
```

For example it shows up in this person's issue as working correctly https://github.com/Gruntfuggly/todo-tree/issues/256

I'm using version 0.0.214 and these are no longer being detected. Is this a bug or did something change in the regex?

**Comment by Gruntfuggly** [comment]
Can you post your todo tree settings?

**Comment by mhkeller** [comment]
```json
{
  "todo-tree.highlights.defaultHighlight": {
        "foreground": "#fff",
        "background": "#00a1ff",
        "iconColour": "#00a1ff",
    },
  "todo-tree.tree.hideTreeWhenEmpty": true,
  "todo-tree.filtering.excludeGlobs": [
        "**/node_modules",
        "**/site-packages",
        "**/env",
        "**/venv"
    ],
  "todo-tree.filtering.ignoreGitSubmodules": true,
    "todo-tree.tree.flat": true,
    "todo-tree.highlights.highlightDelay": 133,
    "todo-tree.general.statusBar": "total",
    "todo-tree.general.debug": true,
    "todo-tree.general.tags": [
        "BUG",
        "HACK",
        "FIXME",
        "TODO",
        "XXX",
        "@TODO", 
        "@todo"
    ]
}
```

I have a temporary fix adding `- [ ]` to my tags list

**Comment by mhkeller** [comment]
I dropped the default regular expression into regexpal.com with some sample text and it correctly highlighted the `- [ ] ` line so I'm not sure why it's not getting highlighted in the doc or showing up in the tree.

```
Version: 1.61.2 (Universal)
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
Date: 2021-10-19T15:49:28.381Z (2 wks ago)
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 19.6.0
```

**Comment by Gruntfuggly** [comment]
Yes, the default regex was updated in 0.0.214, so that it handles markdown in a more logical way. It expects `[ ]` and `[-]` to be added as tags. I had done this as a pop up option previously - now the default has changed I should have added the tags automatically. 🤦 

Sorry about that - I will add them in the next release.

**Comment by mhkeller** [comment]
Thanks for looking into it!

**Comment by Gruntfuggly** [comment]
This should be fixed in the latest version
