### ISSUE TITLE
Possible to mark files in explorer with TODO counts?

### ISSUE THREAD

**Issue by mhkeller** [Gruntfuggly/todo-tree#578]
A linter I use will flag files that have errors in them in the file explorer and vs code will also flag untracked git files and things like that in the file explorer. is it possible for this plugin to also surface which files have todos in them directly in the file explorer? Thanks for such a useful plugin!

**Comment by Gruntfuggly** [comment]
Could you post a screen shot of the errors in the file explorer?

**Comment by mhkeller** [comment]
Here's an example where it's surfacing 3 errors in `index.js` with the number `3` next to the file name:
<img width="1136" alt="Screen Shot 2021-11-08 at 11 49 07 AM" src="https://user-images.githubusercontent.com/498744/140783777-99b82ef3-74ff-4b5e-bf67-292d06d3a2f0.png">


And here's an example of it adding `U` to untracked files once git is enabled
<img width="1136" alt="Screen Shot 2021-11-08 at 11 51 02 AM" src="https://user-images.githubusercontent.com/498744/140783948-e549c342-d46d-4f33-9f04-1f53eff428df.png">
.

**Comment by Gruntfuggly** [comment]
Hi - sorry for the delayed response.

I don't think it's actually possible. The only way it might work would be to create "problems" for TODOs. I did look at doing this a while back, but never finished it because it's quite a lot of work for a pretty small result. I'll revisit it though, to see if it can do what you are looking for.

**Comment by mhkeller** [comment]
Thanks for looking into it!

**Comment by Gruntfuggly** [comment]
Don't think I'll ever get round to supporting this by defining "problems". I don't really think it's the right way to do it either. Open to pull requests if somebody else wants to take it on though!
