### ISSUE TITLE
add some `TODO+` functionality

### ISSUE THREAD

**Issue by cjwijtmans** [Gruntfuggly/todo-tree#583]
In the `vscode` `TODO+` extension you can right click to mark a box done or cancelled or to mark a line is a box. I would like to have this in here as well. As well as colouring the to do list in plain text for better viewing experience.

**Comment by Gruntfuggly** [comment]
That would mean modifying the file itself and the extension was never designed for that. You're probably better off using both extensions.

Can you elaborate on what you mean by "colouring the to do list in plain text" ?  The tree itself can't be coloured unfortunately, but the todos can be highlighted in the editor. See https://github.com/Gruntfuggly/todo-tree#highlighting

**Comment by Gruntfuggly** [comment]
I'm closing this as it's not really something that the extension is intended to do - you can always use both extensions in parallel.
