### ISSUE TITLE
highlighting not working in "JSON with Comments" file type

### ISSUE THREAD

**Issue by j9108c** [Gruntfuggly/todo-tree#584]
is this expected behavior? can you allow highlighting within the "JSON with Comments" file type?

**Comment by HirayClay** [comment]
definitely no,it is not usual

**Comment by Gruntfuggly** [comment]
Can you post an example of what you are expecting to be highlighted? And also, any settings you've changed from the defaults.

**Comment by j9108c** [comment]
update: actually, it only doesnt highlight within vscode's settings files such as `settings.json`, `keybindings.json`, and `global.code-snippets`, which are of the "JSON with Comments" file type. but it does highlight in other files of the "JSON with Comments" file type.

but i'd like it to work inside vscode's settings files if possible. other extensions work inside them so i dont see why not this one.

example of what i expect to be highlighted (this is in `settings.json`)::
![image](https://user-images.githubusercontent.com/31039318/144427785-27aa7b80-972e-4724-8e5c-3fd7ed8373a2.png)

<br/>

all my todo-tree settings::
```
"todo-tree.filtering.excludeGlobs": [
	"**/node_modules/*",
	"**/virtual_environment/*",
	"**/.svelte-kit/*",
	"**/build/*"
],
"todo-tree.general.tags": [
	"TODO",
	"NOTE",
	"BUG",
	"FIXME",
	"HACK",
	"XXX",
	"[ ]",
	"[x]"
],
"todo-tree.highlights.enabled": true,
"todo-tree.regex.regex": "(//|#|<!--|;|/\\*|^|^\\s*(-|\\d+.))\\s*($TAGS)"
```

**Comment by Gruntfuggly** [comment]
Try adding `vscode-userdata` to `todo-tree.general.schemes`. That should then highlight in settings files. The one thing it doesn't do is automatically refresh the settings.json file though as this gets a bit confusing. You can manually refresh the tree though and highlights should still work correctly.

**Comment by j9108c** [comment]
thanks, it worked. i'll close the issue now.
