### ISSUE TITLE
[feat] List TODOs in the (common) Problem Panel

### ISSUE THREAD

**Issue by quazardous** [Gruntfuggly/todo-tree#586]
Hi,

I would like to have TODOs showing up in the Problems Panel.

thx !

**Comment by Gruntfuggly** [comment]
I don't think the problems panel is the right place to put TODOs. It would take quite a lot of work when there is already a panel which can show them!  This extension is designed to provide a tree view - putting them in the problems panel should probably be a different extension altogether.

**Comment by thbeu** [comment]
Pylint shows all TODOs etc. in the problem panel. So why not to have it there as well?

![image](https://user-images.githubusercontent.com/115483027/225589931-eed09e96-5e5f-493f-b074-df60392672e5.png)

**Comment by Ka55i0peia** [comment]
https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker reports spell issues also in problem panel.

**Comment by quazardous** [comment]
TODO could show up with an INFO level (error, warning, notice, info like standard logs levels)

It's not a real "problem" but something to pay attention for (potential problem).

**Comment by Gruntfuggly** [comment]
This extension is designed to find TODOs in files and put them in a tree view - finding them and showing them as problems is a different thing. Maybe when I get some time I can create a separate extension which just creates problems based on the search - it would be a lot simpler.
