### ISSUE TITLE
Todo Tree is detecting todos in a deleted file

### ISSUE THREAD

**Issue by grandslammer** [Gruntfuggly/todo-tree#587]
I created a file which had a typo in it (extra capital letter)

I immediately deleted (didn't write any code in it) it and created a new file without the typo.

Added code to the new file and added 2 todos.

Todo Tree is somehow the old file as having todos in it along with the new file. When I click on todos Todo tree it takes me to the new file regardless of whether I click on a todo in the old file or the new one. See screenshot

Resreshing Todo Tree and restarting VS Code do not fix the issue.

![Screenshot_2](https://user-images.githubusercontent.com/18541062/145678220-8249cf05-a193-428b-98bc-c0d0a73ad66f.png)

**Comment by grandslammer** [comment]
I found a workaround:

VS Code was, for some reason, still showing the old file name in the file's tab title (even though the new file was open and the old file was deleted).

So I closed the tab and reopened it and it showed the new file name. Todo Tree was still showing the old file so I restarted VS Code and the issue seems to be resolved after the restart.

**Comment by Gruntfuggly** [comment]
As VSCode was showing the old filename, I would have to put this down to something odd with VSCode itself. I'll close this, but if you see it again, feel free to reopen.
