### ISSUE TITLE
ripgrep eats whole memory for circular symlinks

### ISSUE THREAD

**Issue by karnigen** [Gruntfuggly/todo-tree#588]
I cannot avoid circular symlinks in directory structure, and when I open code in such directory, todo-tree very quickly eats whole memory. I cannot find how to disable follow symlinks when todo-tree invoke ripgrep, seems it requires --no-follow argument or it is problem with repgrep that it cannot detect loops in directory structure.
Any suggestion?

**Comment by Gruntfuggly** [comment]
You can pass extra arguments to ripgrep using `todo-tree.ripgrep.ripgrepArgs`.

**Comment by Gruntfuggly** [comment]
Hi - Did you get this working? I'm going to close this as there has been no update, and I need to keep the issues list manageable as this is a "spare time" project. If my suggestion didn't work, please feel free to re-open.
