### ISSUE TITLE
Consistently styling colon after tag

### ISSUE THREAD

**Issue by chrismiddle10** [Gruntfuggly/todo-tree#589]
I added some basic, custom tags, but I am having difficulty styling the trailing colons. Default tags style the trailing colons, but my custom ones do not.

1. I'd like to include the trailing colon as part of my custom tag.
2. I'd like to change the forecolor of the trailing colons to be consistent with the tag forecolor.

Can someone point me in the right direction for the config option, please?

<img width="224" alt="Screen Shot 2021-12-14 at 9 10 30 AM" src="https://user-images.githubusercontent.com/7502044/146026076-83999d59-1df5-43d3-8537-77fa85d1bf2d.png">

As seen above, the TODO and FIXME tag highlights the colon, though the forecolor is not black with the tag. Additionally, my custom tags do not include the colon.

(Excluding the colon from the default tags styling would be an acceptable solution as well.)

**Comment by Gruntfuggly** [comment]
Sorry it's taken a while to look at this. Can you post your config? I'm not sure how you've managed to get it to show the colon with a different foreground colour - there should only be one decoration per tag, which should apply to the whole thing.

**Comment by chrismiddle10** [comment]
Thanks for getting back to me, but this is no longer an issue for me because I have moved on with another plugin.

**Comment by Gruntfuggly** [comment]
That's why I like VSCode - theres always an alternative extension! 😁
