### ISSUE TITLE
[Discussion] Add support for VS Live Share

### ISSUE THREAD

**Issue by lostintangent** [Gruntfuggly/todo-tree#59]
[VS Live Share](aka.ms) allows devs to collaborate with others in real time, directly from within VS Code. All of the “guests” that join a Live Share session are remotely connecting to the “host” (the person who shared), and can edit, debug, access terminals (if allowed), run tasks, etc. without needing to download any files or setup their environment.

Because “guests” are pulling their state from the “host”, and don’t have local file access, some extensions (like this one!) don’t work out of the box. However, we just [published an API](https://www.npmjs.com/package/vsls#messaging-rpc) that allows extensions to detect the presence of a Live Share session, and then use the secure connection that is established between all participants. You can then use this to send RPC messages, such as retrieving the list of TODOs, and listening for TODO updates.

It would be interesting to explore an integration between this extension and Live Share, such that if a dev had Todo Tree installed, and joined a Live Share session, they would pull the TODOs data from the host, as opposed to trying to run ripgrep locally.

**Comment by lostintangent** [comment]
@Gruntfuggly What would you think about this integration? I started a prototype that has guests pulls the todo data from the host when within a Live Share session, and I could send a WIP PR soon, since I’d love to get your input.

**Comment by Gruntfuggly** [comment]
Hi - sorry for not responding earlier! It sounds like a good idea - if you get something working I'd definitely be happy to include it.

**Comment by bhack** [comment]
@lostintangent Any news?

**Comment by RefinedSoftwareLLC** [comment]
We were so excited that this extension worked without any configuration for our host of Live Share. It instantly pulled in our existing TODOs. Then we found out that it only works for our host and none of our collaborative programmers. What is the next step to get this extension working collaboratively?

@lostintangent Could you post your code here, even if it doesn't work yet, so someone else could give a shot at it?

Are there any other links that would be useful for someone to dig into this?

https://www.npmjs.com/package/vsls#messaging-rpc

**Comment by Gruntfuggly** [comment]
I'm going to close this as the links in the original post no longer work, and I don't have the knowledge or facilities to develop this.
