### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by morgansliman** [Gruntfuggly/todo-tree#590]
It's been quite a while since any updates here, and even some open PRs have gone unacknowledged by the maintainer. Is this still being actively developed on?

**Comment by Gruntfuggly** [comment]
Hi - there are updates in the pipeline - I lost my father recently and have also changed job, so the extension has been on the back burner for a while.

**Comment by morgansliman** [comment]
Ah .. I'm very sorry to hear that. 

Not to be insensitive, but do you have plans to come back to it eventually? No rush of course, but if so then it might be worth considering adding on another maintainer to help handle the load. If not, then I'd consider forking the project entirely as many of us do find it quite helpful.

Best of luck in your life changes mate.

**Comment by Gruntfuggly** [comment]
Yes, hopefully going to make some updates over the Christmas holidays. Saying that, I'm happy for anybody else to jump onboard - most of the pull requests I get are users wanting to update the default settings to their own preferences 😀

**Comment by Gruntfuggly** [comment]
I've managed to get some time to work on the extension (due to a broken leg), so I'm going to close this.
