### ISSUE TITLE
c/c++ coding error

### ISSUE THREAD

**Issue by DoctorAnthony** [Gruntfuggly/todo-tree#591]
在gbk格式下添加标签后，侧边栏里的标签乱码，只有使用UTF-8格式才能解决。求支持C/C++。

**Comment by Gruntfuggly** [comment]
Could you please post an example and a screenshot so I can try to reproduce it?

**Comment by Gruntfuggly** [comment]
Hi - I'm going to close this as there has been no update, and I need to keep the issues list manageable as this is a spare time project. If you can add any more info, please feel free to re-open.
