### ISSUE TITLE
I am stupid

### ISSUE THREAD

**Issue by hawkiboy** [Gruntfuggly/todo-tree#592]
How do you use this plug in? I  'installed' it. I stumbled around and found some commands in the command pallet like 

TODOTREE: SCAN OPEN FILES ONLY.

Nothing happens that I can see. (of course i do have TODOs todo fixme FIXME, etc. in my comments. Isn't that the idea?
I tried pasting the sample configuration into my user workspace and reloaded the VSCode window. Nothing

Then I noticed the TODO tree cloud on the left side. Hallelujah. That only took me about 10 minutes to figure out. So I add more TODO FIXME whatever to another open file and run:

TODOTREE: SCAN OPEN FILES ONLY.

again, and NOTHING happens. The new file is not added to the list.

I sincerely wish there was a category for dummies called 'HOW TO USE'.  on all these plugins. Every time we jump straight to configuration and advanced options.

**Comment by Gruntfuggly** [comment]
By default it should find things like `// TODO`. If you look in the activity bar, there should be a "Tree" icon. If you click on it, you should be able to see any TODOs that have been found.

What language are you using?

**Comment by Gruntfuggly** [comment]
You shouldn't need to use the commands - they are there in case you don't want to use the buttons on the tree view titlebar.

**Comment by hawkiboy** [comment]
Thank you, wow that was fast. I am using Dart. I just found the tree view. But it does not add any new TODOs that I create. even after I rescan. Not sure what I am missing.
Apparently the //TODO has to be inside the code body and can not be outside of a class or function.

**Comment by Gruntfuggly** [comment]
Can you post an example of a dart comment?

**Comment by hawkiboy** [comment]
As usual it is working fine now that I have spend 30 minutes and asked for help. Not sure why it wasn't showing my comments on the rescan etc, but now it seems to be showing them right away. I don't know if any of the code gods care if more people use plug ins , but I typically don't have time to learn how to use them so I can save tons of time! I end up doing things in more primitive ways. I really like stuff that explains the basics 'as if' there were people out there that are kind of simple, like me.... :)

**Comment by Gruntfuggly** [comment]
If your comments are `// TODO something` they should be found. There is a debug output which might be helpful - if you enable `todo-tree.general.debug` and the go to the Output window, you should find "Todo Tree" in the drop down. If you select it, it will show what's going on.

However, if you've run the command `Scan Open File Only` that will change how it works - you probably want `Scan Workspace and Open Files` to search you workspace folder too.

**Comment by Gruntfuggly** [comment]
I think where you went wrong was running the first command you found before seeing the "view". I'll update the README.md to make it obvious where to go to find the TODOs to start with - that would probably have help you out.

**Comment by Gruntfuggly** [comment]
The extension tries to do the basics out of the box, but because VSCode supports so many languages, it's impossible to set it up to work with all of them, so most users end up having to do a bit of configuration to tailor it to their own use.  Once you get it working though, there is lots you can configure to get it to work how you want.

**Comment by Gruntfuggly** [comment]
Did you get very far through the README.md ? There is a section that explains what the commands do (https://github.com/Gruntfuggly/todo-tree#folder-filter-context-menu) but there's quite a lot of info, so I think a lot of people give up before they get there and just try it out.

**Comment by Gruntfuggly** [comment]
I've updated the README.md with a new screenshot which should hopefully help with locating the view.
