### ISSUE TITLE
label-name in the tree view  support textDecoration?

### ISSUE THREAD

**Issue by OceanBelongsToMe** [Gruntfuggly/todo-tree#593]
label-name in the tree view  support textDecoration?

**Comment by Gruntfuggly** [comment]
Sorry, I'm not sure what you mean? If you does the tree view allow text decorations, then no unfortunately. There is very little styling available for the tree view via the API.

**Comment by OceanBelongsToMe** [comment]
Well, if you can see a column of underlined data at a glance, it will enrich a lot :)

**Comment by Gruntfuggly** [comment]
Sorry - I still don't follow. Could you mock me up an example? Bear in mind that you can't underline anything in the tree view.

**Comment by Gruntfuggly** [comment]
Hi - I'm going to close this as there has been no update, and I need to keep the issues list manageable as this is a "spare time" project. If you can add any more info, please feel free to re-open.
