### ISSUE TITLE
Todo-Tree: Failed to find vscode-ripgrep

### ISSUE THREAD

**Issue by Dovernh** [Gruntfuggly/todo-tree#595]
Todo-Tree: Failed to find vscode-ripgrep - please install ripgrep manually and set 'todo-tree.ripgrep' to point to the executable. using insiders, happened after an update to insiders

**Comment by Tyriar** [comment]
![image](https://user-images.githubusercontent.com/2193314/149156188-abc99b32-7848-4468-8d2e-282426b7757c.png)

Version: 1.64.0-insider (user setup)
Commit: 753319a08f8e74700b1dba3a29bf0a6af7c2953f
Date: 2022-01-12T05:16:42.486Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by Tyriar** [comment]
Oh I think this is probably because we migrated the module to `@vscode/ripgrep`

**Comment by smlombardi** [comment]
@Tyriar so what should we end-users do?

**Comment by MariaSolOs** [comment]
I'm having the same issue :/

**Comment by roblourens** [comment]
@Gruntfuggly I wasn't expecting an extension to try to load a node module from the vscode install. Can you update the extension to point to `@vscode/ripgrep` instead?

For users, it looks like there is a setting `todo-tree.ripgrep` where you can point to your own ripgrep binary or point to `node_modules/@vscode/ripgrep` in your vscode install

**Comment by Tyriar** [comment]
I guess the best would be requiring based on the version of vscode, so >= 1.64 would use `@vscode/ripgrep`, that way you can remove the old case when the vscodeEngine is updated to 1.64+. We don't consider the modules shipped with VS Code public API but I know some extensions do it, created https://github.com/microsoft/vscode/issues/140585 for discussion

**Comment by Tyriar** [comment]
That doesn't includes the majority of those 7 pages of results, and also doesn't include if the function/mechanism they used was not named exactly `getCoreNodeModule`

**Comment by connor4312** [comment]
See https://github.com/Gruntfuggly/todo-tree/issues/596

**Comment by Gruntfuggly** [comment]
@Dovernh Please can you try the latest version and see if it works with the new insiders build? (it did for me, but it's always good to get confirmation from somebody else! 😄 )

**Comment by MariaSolOs** [comment]
@Gruntfuggly It works for me! :)

**Comment by selrond** [comment]
Works now

**Comment by Dovernh** [comment]
@Gruntfuggly Yes no errors this morning and the todo's now show

**Comment by geekley** [comment]
@Gruntfuggly Can you update open-vsx with latest version, please? Thanks.

**Comment by Gruntfuggly** [comment]
Done.
