### ISSUE TITLE
Simplify and clearify the documentation

### ISSUE THREAD

**Issue by serhioV** [Gruntfuggly/todo-tree#597]
When a new user installs the extension, it expects two things to happen: or it will work immediately after the installation, or there is need to configure something first.
If there is need to configure, where and what, for a minimum to see the todos in the tree list. How we see them, if we have a huge project with a lot of files and folders?

The documentation is not clear for a newbie. It says to configure or use some directives, but any idea where to use them, in what config json file, not if there is need to configure something initially... 

I have a C#+JS(angular) project, I know I have todos, but don't know exactly where... how to find a list of all todos, like Visual Studio does?

**Comment by Gruntfuggly** [comment]
The extension should work out of the box for many languages, without any configuration. It will find things like `// TODO Fix this` or `# FIXME`. Unfortunately it can't work for every possible language by default, so for some languages you'll need to configure the extension. The configuration is set exactly the same way as for any other extension or for VSCode itself.

After you installed, did you see the new view in the activity bar? If you click that it should show any TODOs it has found. The screenshot in the README.me shows the view icon highlighted.

If you have suggestions for where the documentation can be improved, please let me know.

**Comment by serhioV** [comment]
I didn't know where to look. The Todo List in Visual Studio appears in the bottom in a list, to the Visual Studio Code left panel was completely unfamiliar, discovered only much later

**Comment by Jimgitsit** [comment]
Oh my god yes, please do this. I see lots of configuration options but where do they go?!

**Comment by Gruntfuggly** [comment]
What do you mean "where do they go"?  I'm closing the as I think the documentation is about as clear as I can make it. Feel free to re-open if anybody has any actual suggestions for improvements.
