### ISSUE TITLE
Regex not working for vscode-insider's own settings.json

### ISSUE THREAD

**Issue by hopezh** [Gruntfuggly/todo-tree#598]
I have the following specified in the **settings.json** of **vscode-insider** according to [configuraton examples](https://github.com/Gruntfuggly/todo-tree/wiki/Configuration-Examples#javadoc) for JavaDoc, JS, BASH, PHP, HTML, CSS, MD, JSON, XML.

`"todo-tree.regex.regex": "(//|#|<!--|/\\*|^\\s*\\*)\\s*($TAGS)", `

However, none of the todo tags is identified by todo-tree in this settings.json file itself. 

![Image 4](https://user-images.githubusercontent.com/23435810/151125220-014bb660-cb3c-4af2-bf7c-b1c13e6bfe73.png)

![Image 5](https://user-images.githubusercontent.com/23435810/151125251-bbf46e7a-8b55-4b0c-9aa2-4796423ee56b.png)

![Image 7](https://user-images.githubusercontent.com/23435810/151125676-0e6086aa-72c2-4f6d-af8f-b95b694154ca.png)

Strangely, it works for other json files in which I added customized todo tags. 

![Image 1](https://user-images.githubusercontent.com/23435810/151125276-b235d1c1-b864-4eaa-99ee-73cc75ad37a6.png)

![Image 3](https://user-images.githubusercontent.com/23435810/151125300-ed47edd6-5611-4b7f-b964-64327a36120c.png)

May I ask how to show todo-tree tags for vscode's own settings.json or keybindings.json files? 

Thanks.

**Comment by Gruntfuggly** [comment]
To search those files you can add "vscode-userdata" to `todo-tree.general.schemes`.

**Comment by hopezh** [comment]
Thank you, @Gruntfuggly. It works like a charm, as show below. 

![Screen Shot 2022-01-26 at 21 49 08 PM](https://user-images.githubusercontent.com/23435810/151175413-9977ba53-a67d-437c-81c6-a20068867614.png)

![Screen Shot 2022-01-26 at 21 49 26 PM](https://user-images.githubusercontent.com/23435810/151175435-c6d28036-372b-451f-a467-643c3c97f294.png)

I really like your ToDo Tree, and I used it most of the time to add "customized tags" to mark the major structure for my code, rather than just to mark todos etc, kinda like creating a "Table of Contents" for the code. 

It is far better than using vscode's native "outline" function to navigate the code base, especially when the project is getting larger and larger. 

I only hope vim/neovim has plugins that offer similar functions.

**Comment by Gruntfuggly** [comment]
Thank you - I'm glad you're finding it useful! :smile:
