### ISSUE TITLE
improve warning `Todo Tree: There is now an improved method of locating markdown TODOs.`

### ISSUE THREAD

**Issue by tjx666** [Gruntfuggly/todo-tree#604]
```jsonc
  // https://github.com/Gruntfuggly/todo-tree/issues/255#issuecomment-574279033
  "todo-tree.regex.regex": "(?:(?://|#|<!--|;|/\\*\\*?|\\*|(-|\\d+.))\\s*($TAGS)|^\\s*- \\[ \\])",
  "todo-tree.general.tags": ["TODO:", "FIXME:", "NOTE:", "[ ]", "[x]"],
```

Should not appear this warning because I have configure as describled in readme.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/152859698-455c4c18-93de-4650-8523-fa9e68352988.png">

**Comment by Gruntfuggly** [comment]
If you click "Never Show This Again" does it keep coming back?

**Comment by tjx666** [comment]
I haven't try it. For now, if I click `Never Show`, it's very complex to let this notification show again when I change todo-tree regex again.

**Comment by Gruntfuggly** [comment]
If you click "Never Show This Again" it should stop popping up. Please try it - if it keeps popping up after clicking it, I'll investigate.

**Comment by Gruntfuggly** [comment]
Or simply remove `|^\\s*- \\[ \\]` from the end of the regex.

**Comment by tjx666** [comment]
I change the regexp to 

```
  "todo-tree.regex.regex": "(?:(?://|#|<!--|;|/\\*\\*?|\\*|(-|\\d+.))\\s*($TAGS))",
```
