### ISSUE TITLE
possible error with java language

### ISSUE THREAD

**Issue by NoelTejeda** [Gruntfuggly/todo-tree#605]
Issue Type: Performance
Extension Name: todo-tree
Extension Version: v.0.0.215  - 2022-01-04
OS Version: windows pro 64 bits
VS Code version: 1.64.2

hello greetings, I have a problem the pluggins todo tree with the java language does not work correctly; that is; when I comment //TODO example, everything is underlined to me as if it were a mistake. but using the //TODO comment in another language like javascript doesn't underline me as if it were a mistake.

the same thing happens to me with FIXME the others are not underlined as if it were an error

my configuration is this:

 //CONFIGURACION PARA TODO TREE
    "todo-tree.highlights.defaultHighlight": {
        "icon": "alert",
        "type": "text-and-comment",
        "foreground": "red",
        //"background": "#2a1f1f",
        "opacity": 50,
        "iconColour": "yellow"
    },
    "todo-tree.highlights.customHighlight": {
        "COMPLETE": {
            "icon":"verified",
            "foreground": "yellow",
            "iconColour": "yellow",
            "gutterIcon": true
        },
        "TODO": {
            "icon": "check",
            "type": "line",
            "foreground": "#ee00b2",
            "iconColour": "#ee00b2",
            "gutterIcon": true
        },
        "FIXME": {
            "icon":"flame",
            "foreground": "yellow",
            "iconColour": "yellow",
            "gutterIcon": true
        },
        "BUG": {
            "icon":"bug",
            "foreground": "red",
            "iconColour": "red",
            "gutterIcon": true
          }
    },
    "todo-tree.general.tags":[
        "COMPLETE",
        "TODO",
        "FIXME",
        "BUG",
    ]

![vista](https://user-images.githubusercontent.com/45132528/153693352-ad6acc82-d6b9-4ac4-9cc6-ec6068527932.JPG)

**Comment by NoelTejeda** [comment]
I have disabled the extension java and I stop checking. but the idea is to leave it active

Language Support for Java is required. Please install and enable it.

**Comment by Gruntfuggly** [comment]
Please can you hover over the "errors" and see what message is displayed? `//` should be valid comments in Java, so I don't know why it's showing them as problems. If I add `// TODO` in a Java file, I don't see any problems. Are you using a Java extension?

**Comment by NoelTejeda** [comment]
hello greetings,

 I hadn't answered you, because I wanted to test the extension in my workspace, to check if it was a problem with my configuration. but in the same way the problem persists, the solution I found is to change the word "TODO" and replace it with another as "TODOS"

 Although I think it should be like a reserved word, something like that, because in the same way when commenting without the extension it throws me error.

![imagen](https://user-images.githubusercontent.com/45132528/154136278-e7fe2a96-60c0-4a86-81e6-1fc8dae16047.png)

**Comment by Gruntfuggly** [comment]
Sorry, I don't understand why the Java extension is flagging it as a problem? Maybe it knows that "TODO" is something that needs to be looked a?

Can you point me to the extension so I can try it out. I don't think it is anything to do with the todo-tree extension.

**Comment by Gruntfuggly** [comment]
Closing due to lack of updates - feel free to re-open if it's still an issue.
