### ISSUE TITLE
When a line has an asterisk before a tag, it doesn't see it

### ISSUE THREAD

**Issue by vartiovaara** [Gruntfuggly/todo-tree#607]
![Screenshot_2022-02-26_14-34-54](https://user-images.githubusercontent.com/64323553/155843402-8d724d3b-fe97-420e-9f84-cde0d2f576a5.png)
In this picture, the line has an asterisk and a space before "TODO" (this is a fairly common style of multi-line comments in C).
You can see that the extension doesn't find the tag, and it doesn't show up in the tags on the left (under defs.h)

![Screenshot_2022-02-26_14-35-04](https://user-images.githubusercontent.com/64323553/155843404-ad1e57b3-ad01-4ff3-8f0e-2f54af1cb901.png)
In this picture, the line lacks the asterisk, and it finds the "TODO" tag correctly.
You can see that the tags are found, and can be seen on the left.

**Comment by Gruntfuggly** [comment]
Yes, the default regex won't match your first example. You can configure it by changing `todo-tree.regex.regex` to include `\*` in the first part of the regex, e.g.
```
(\\*|//|#|<!--|;|/\\*|^|^[ \\t]*(-|\\d+.))\\s*($TAGS)"
```
(Note the double slash needed if you change the regex in the settings.json - use a single slash if you use the settings GUI).

For more examples of configuring the regex, please take a look at the wiki:
https://github.com/Gruntfuggly/todo-tree/wiki/Configuration-Examples

**Comment by donatasben** [comment]
Hi. Came here with the same issue/question. The solution worked for me - now it's highlighting it inside a larger block comment!
Thanks!

**Comment by raminudelman** [comment]
I have a markdown file and I added a TODO in brackets `(` `)` like so:

```md
some text (TODO: My cool task) rest of the text
```

And the parser didn't catch that.

Only after adding `\\` before the `TODO` (i.e., `\\TODO`) the parser caught it.

**Comment by Gruntfuggly** [comment]
Closing as this is all covered by modifying the regex. @donatasben The default regex is just a starting point - it would be impossible to provide one that covers all languages, so users need to modify it for their own needs.
