### ISSUE TITLE
Feature request for mark as completed 

### ISSUE THREAD

**Issue by bboysnick5** [Gruntfuggly/todo-tree#614]
Add function to mark to-do as completion (and delete the to-do comment)

**Comment by Gruntfuggly** [comment]
Hi - thanks, but the problem with this is that it would modify the files - currently the extension doesn't make any changes.

This feature probably belongs to a separate extension for managing TODO's, not just finding them.

To be honest, when you click on a TODO in the tree it should place the cursor at the start of the TODO in the file, so you could just add a shortcut key to `Delete All Right` and it will do what you want.
