### ISSUE TITLE
Weird overlay and text color on all tags

### ISSUE THREAD

**Issue by Tosh0kan** [Gruntfuggly/todo-tree#619]
For some reason, all tags, both standard and custom ones, have this weird gray overlay on them, and the text color changes to a dark gray, like in this image(https://i.imgur.com/oUFQIuQ.png), and I have no clue why. I have already tried reinstalling the extension and nothing.

**Comment by Gruntfuggly** [comment]
That's just the default highlight. You can customize the colours (`todo-tree.highlights.defaultHighlight`), or just disable them with by setting `todo-tree.highlights.enabled` to false. There are loads of ways to configure the highlights if you want to, see https://github.com/Gruntfuggly/todo-tree#highlighting.

**Comment by Tosh0kan** [comment]
Ahhhhhh. Sorry. I thought for certain the default tags would look like something else, and this was the result of some weird conflict. Thank you for clarifying.
