### ISSUE TITLE
How to docs?

### ISSUE THREAD

**Issue by hivemall** [Gruntfuggly/todo-tree#62]
I am new to this and the docs are sparse.
I installed on vscode, how to open tasklist with found kewords in the project and also hightlight them in the code. eg: //TODO still remains the same color in index.js
(similar to task list in eclipse)

**Comment by Gruntfuggly** [comment]
Hi - you shouldn't really need to do anything else. If it finds anything, it should show a tree view in the explorer pane on the left. Alternatively, you can select "View" from the main menu and then "Open View...", which should show a list - click on TODOs to open a new sidebar. If this shows "Nothing Found" then it sounds like there is a problem with the search.

There is a configuration setting "todo-tree.debug". If you set this to "true" and restart vscode, you should find a new log in the "Output" pane, called "todo-tree". If you copy the contents and paste it here, I'll see if I can work out why you're not seeing anything.

**Comment by hivemall** [comment]
there is no such thing: Open Views -> view todos/TODO*/foo 
nothing in the explorer either: openeditors, untilted wokspace, outline?

**Comment by Gruntfuggly** [comment]
If there is nothing in the Open View menu, then maybe the extension has failed to install? If you open the developer tools, is there anything in the console?

Does the open view menu just show the standard views, eg Explorer, Search, Source Control, Debug and Extensions?

**Comment by hivemall** [comment]
the todo tree is now showing up please see earlier comment, sorry for the consfusion, a little note in the readme on how to access for newbs. 
Thank you for you help

**Comment by Gruntfuggly** [comment]
OK, glad you got it working! 8-)

You have to reload the window to make any installed extension active, but I'll add a note in the installation instructions.
