### ISSUE TITLE
Add jetbrains intellij idea style markdown todo

### ISSUE THREAD

**Issue by ICHx** [Gruntfuggly/todo-tree#629]
Idea support markdown todo in such tag by default 
```md
[//]: # "TODO: xyz"
```

but not 

```md
TODO: xyz
```
https://youtrack.jetbrains.com/issue/IDEA-214308

**Comment by Gruntfuggly** [comment]
You'll need to update the regex to make it work. Please see the Wiki (https://github.com/Gruntfuggly/todo-tree/wiki/Configuration-Examples) for some examples.
