### ISSUE TITLE
Search in files in different encodings?

### ISSUE THREAD

**Issue by Serega124** [Gruntfuggly/todo-tree#63]
Hi.
I'm seeing problems with displaying TODOs from files in different encodings:
![1](https://user-images.githubusercontent.com/5006548/43676196-0276a5c4-97f5-11e8-9702-2259449779b0.png)
But built-in VSCode search (based on same ripgrep) just work fine:
![2](https://user-images.githubusercontent.com/5006548/43676216-80d9b56e-97f5-11e8-9a39-1bccd46ab60d.png)
Any ideas to fix it?

**Comment by Gruntfuggly** [comment]
Could you send me a fragment of the file so I can test it? It may be because of something I'm doing to the text when processing it.

**Comment by Serega124** [comment]
Created folder for test
[TestFolder.zip](https://github.com/Gruntfuggly/todo-tree/files/2259596/TestFolder.zip)
![3](https://user-images.githubusercontent.com/5006548/43678102-a91b6d22-9815-11e8-8efe-f1b1ec125bf6.png)

**Comment by Serega124** [comment]
It seems that ripgrep does not convert results into Unicode before output to stdout and does not have any settings for this.
![4](https://user-images.githubusercontent.com/5006548/44039617-20d20016-9f22-11e8-810f-3ba43e738f1b.png)
.. or automatic encoding detection does not work at all.
![5](https://user-images.githubusercontent.com/5006548/44039647-2b277a8c-9f22-11e8-87da-5108bf33c0dc.png)

**Comment by Serega124** [comment]
Built-in VSCode search [uses](https://github.com/Microsoft/vscode/blob/bbd54cb673382d74dbc252c2ffb85e5eadcc4bd8/extensions/search-rg/src/ripgrepTextSearch.ts#L177) a [string_decoder](https://nodejs.org/api/string_decoder.html) module to handle ripgrep output.

**Comment by BurntSushi** [comment]
@Serega124 ripgrep outputs whatever it gets. There is no transformation there. "automatic" encoding is effectively limited to BOM sniffing, and is documented in [the guide](https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#file-encoding). For more exotic encoding needs, you need to explicitly specify the encoding. It is transcoded to UTF-8, searched and printed (as UTF-8).

**Comment by BurntSushi** [comment]
> is there a way to search in files in different encodings in one query?

No. And there are no plans. On master there is a `--pre` flag to insert your own ad hoc processing, but this incurs a performance penalty. In general, ripgrep cannot know the encoding of a file.

**Comment by Gruntfuggly** [comment]
Closing, as I don't think there are any changes required to the extension. Please feel free to reopen if required.

**Comment by Tolik-Trek** [comment]
Hi!
Maybe the item in the settings to set the default output encoding will help?
