### ISSUE TITLE
update version of octicons

### ISSUE THREAD

**Issue by LeoJhonSong** [Gruntfuggly/todo-tree#630]
Hi, I noticed the [Octicons](https://primer.style/octicons/) is now version **v17.0.0**, so there are some more icons not included in todo-tree now. For example, [codescan-checkmark](https://primer.style/octicons/codescan-checkmark-16). could you please do an update? :laughing:

**Comment by everdrone** [comment]
friendly bump! so many icons are missing from this the [updated list](https://primer.style/octicons/)

**Comment by Gruntfuggly** [comment]
I've updated to v16 (thanks to a PR from somebody else). I'll move to v17 for the next release.

**Comment by Gruntfuggly** [comment]
Latest version should now be using v17 octicons (v0.0.221). Please try it and re-open if there are any issues.

**Comment by vepain** [comment]
May I suggest to update again the octicons please (for example, one cannot use the [`sparkles-fill`](https://primer.style/octicons/icon/sparkles-fill-24/) icon)
