### ISSUE TITLE
Feature: support for "Better Comments" Syntax

### ISSUE THREAD

**Issue by BananaAcid** [Gruntfuggly/todo-tree#632]
It would be great to have the syntax of [`aaron-bond.better-comments`](https://github.com/aaron-bond/better-comments) supported in the file overview -- and not to overwrite the keyword styling if, for example `//FIXME abc` is used.

![image](https://user-images.githubusercontent.com/1894723/165854880-712a0416-f9a9-496f-8ee7-b53fdff15c6e.png)

**Comment by Gruntfuggly** [comment]
You'll need to update the regex to make it work. Please see the Wiki (https://github.com/Gruntfuggly/todo-tree/wiki/Configuration-Examples) for some examples.
