### ISSUE TITLE
BUG: "- [x]" does not highlight in .md files 

### ISSUE THREAD

**Issue by pi314ever** [Gruntfuggly/todo-tree#633]
Following the steps from the [markdown support](https://github.com/Gruntfuggly/todo-tree#markdown-support) page, the `- [ ]` checklist item works while the `- [x]` does not appear to register as a TODO item. Removing `-` highlights it green, but markdown won't render the checkmark. A similar issue happens for both `1. [ ]` and `1. [x]`.

**Comment by Gruntfuggly** [comment]
This should work with the default settings - can you post all your todo-tree settings please?

**Comment by Gruntfuggly** [comment]
Closing as no more information available. Feel free to re-open if you need to.
