### ISSUE TITLE
Todo Tree not exclude build directory

### ISSUE THREAD

**Issue by hongz1** [Gruntfuggly/todo-tree#642]
Anyone knows how to exclude build directory?
I am running react and todo-tree keep listing "build/static/js".
I added node_modules and build but only build directory was listed.

`
"todo-tree.filtering.excludeGlobs": [
        "**/node_modules/**", "**/build/**"
  ],
`

**Comment by MarlonPassos-git** [comment]
I don't know either, here in my project it is getting the "TODOs" from "node_modules". I don't know if it would be feasible to automatically ignore directories that are in .gitignore

**Comment by svipas** [comment]
I created a PR for excluding `node_modules` properly by default: https://github.com/Gruntfuggly/todo-tree/pull/673, but for now you can use this setting:

```json
"todo-tree.filtering.excludeGlobs": ["**/node_modules/*/**"],
```

@hongz1 If you want to exclude `build` directory try this:

```json
"todo-tree.filtering.excludeGlobs": ["**/node_modules/*/**", "**/build/*/**"],
```

**Comment by HishamMubarak** [comment]
> I created a PR for excluding `node_modules` properly by default: #673, but for now you can use this setting:
> 
> ```json
> "todo-tree.filtering.excludeGlobs": ["**/node_modules/*/**"],
> ```
> 
> @hongz1 If you want to exclude `build` directory try this:
> 
> ```json
> "todo-tree.filtering.excludeGlobs": ["**/node_modules/*/**", "**/build/*/**"],
> ```

Looking forward to this PR being merged.

**Comment by Gruntfuggly** [comment]
The PR has now been merged, so I'm going to close this. Please feel free to re-open if you still believe there is an issue.
