### ISSUE TITLE
Todo tree not appearing

### ISSUE THREAD

**Issue by emisdumb** [Gruntfuggly/todo-tree#646]
I recently installed the todo-tree extension and while the extension recognizes "TODO" in my code and correctly highlights it, the todo tree is not showing and there's nothing relating to todo-tree on the activity bar either.

My extension config is simply whatever the default is - I did not edit it.

**Comment by Ygilany** [comment]
same is happening here

**Comment by Ygilany** [comment]
@emisdumb Check under the Explorer tab, you may find it collapsed at the bottom
![CleanShot 2022-06-26 at 19 08 24](https://user-images.githubusercontent.com/11262007/175837278-779f3f7b-02de-4087-a8ac-cc3da0e28c51.png)
you can also drag and drop the section to the side menu
![CleanShot 2022-06-26 at 19 09 48](https://user-images.githubusercontent.com/11262007/175837357-8cdb9cb7-95d4-4232-a2ea-5e11d2dfd8d3.gif)

**Comment by emisdumb** [comment]
Thanks! Couldn't find it before.
