### ISSUE TITLE
regex colors

### ISSUE THREAD

**Issue by Gubith** [Gruntfuggly/todo-tree#65]
Is it possible to highlight tags depending on the character after the tag?
[tag][-]   = highlight tag+remaining text on the line
[tag][!-]  = highlight just the tag
```
	
// highlight Tag	
"todo-tree.regex": "((//|#|<!--|;|/\\*|^)\\s*($TAGS)|^\\s*- \\[ \\])",

// highlight Line	
"todo-tree.regex": "((//|#|<!--|;|/\\*|^)\\s*($TAGS).*|^\\s*- \\[ \\])",

// This example highlights but does not match tag color:
"todo-tree.regex": "((//|#|<!--|;|/\\*|^)\\s*($TAGS)(\\s|-.*)|^\\s*- \\[ \\])",

```
It seems any () added after the ($TAGS) drops the colors. 
Tried many things, figured I'd ask if it's even possible.

**Comment by Gubith** [comment]
Thanks.  I was trying to make the regex where "TAG-" would do the line, "TAG " would only highlight the tag.

**Comment by Gruntfuggly** [comment]
I've just uploaded a new version where you can set the highlight to "none", "tag", "text" (for your case) or "line".

Let me know if that does the job.

**Comment by Gubith** [comment]
Thanks!
