### ISSUE TITLE
[Question] Open the panel with a keybind

### ISSUE THREAD

**Issue by jan-dh** [Gruntfuggly/todo-tree#651]
Is there a possibility to open the TODO panel with a keybind? My default view is to have all the sidebar hidden so I'd like to be able to toggle my TODO's with a keybind.

I tried the following commands:  `.reveal, .showFlatView, .showTreeView, .expand` but nothing seems to work. 

```
 {
    "key": "cmd+k cmd+o",
    "command": "todo-tree.reveal"
  },
  ```

**Comment by tbenthompson** [comment]
I'd also appreciate this!

**Comment by baincd** [comment]
The command to show the Todo-Tree sidebar is `workbench.view.extension.todo-tree-container`

**Comment by jan-dh** [comment]
Thanks this works!
