### ISSUE TITLE
Illegal argument: line must be non-negative

### ISSUE THREAD

**Issue by PurpleSwords** [Gruntfuggly/todo-tree#653]
![Snipaste_2022-07-14_14-21-01](https://user-images.githubusercontent.com/38780499/178914290-264d0bc2-b007-4dfb-b507-c3cff6914fdc.png)

This error is reported when I open the code in the folder and the tree view uses the default values ![default](https://raw.githubusercontent.com/Gruntfuggly/todo-tree/master/resources/button-icons/tree.png).

**Comment by PurpleSwords** [comment]
![Snipaste_2022-07-14_14-32-22](https://user-images.githubusercontent.com/38780499/178916130-88d4dbdc-e928-405b-9604-a51f210bfc3b.png)
![Snipaste_2022-07-14_14-33-49](https://user-images.githubusercontent.com/38780499/178916427-de6693f2-3a05-420d-8995-14a56e5142a6.png)
In this state, the tree view appears blank and the other views appear normal.

**Comment by PurpleSwords** [comment]
![Snipaste_2022-07-14_14-37-26](https://user-images.githubusercontent.com/38780499/178917052-806b2007-8136-4912-a818-97e58a924a43.png)
Here are some more console errors reported, seems to be more than one problem, hope it can help you.

**Comment by Gruntfuggly** [comment]
Hi - if this is still an issue, could you enable the debug console (`todo-tree.general.debug`) and post the contents of the output channel?

**Comment by Gruntfuggly** [comment]
Please feel free to reopen if you can give me some more information to try and fix this issue.
