### ISSUE TITLE
Error message when refreshing the todo-tree

### ISSUE THREAD

**Issue by bmaercz** [Gruntfuggly/todo-tree#655]
Hi,

when I hit the "Refresh" button in the Todo-Tree Sidebar, I get the following error message in a pop-up in VSCode:

> ENOENT: no such file or directory, mkdir '\home_share$\<user_name>\data\profile redirected folders\AppData\Code\User\globalStorage\gruntfuggly.todo-tree'

The Todo-Tree only shows the files in my workspace containing TODO Tags, but entries are not shown when the tree is expanded.

**Comment by demitrix** [comment]
Receiving the same error here.

**Comment by Gruntfuggly** [comment]
Could you share your changes? I can update the extension if it fixes it.

**Comment by bmaercz** [comment]
I'm currently working with version v0.0.222. In this version it works correctly for me.
