### ISSUE TITLE
Wrap text on the tree view (now possible)

### ISSUE THREAD

**Issue by R3uan3** [Gruntfuggly/todo-tree#656]
This feature has already been requested here:
https://github.com/Gruntfuggly/todo-tree/issues/289

@Gruntfuggly mentioned at **2020**

> Unfortunately, the API doesn't allow for wrapping

I requested it on the vscode repo and got linked to an issue where a dev demonstrated an API in which this could be achieved:
https://github.com/microsoft/vscode/issues/103403#issuecomment-666319714

![image](https://user-images.githubusercontent.com/103058225/179995833-e575a6c0-a4ef-458d-94a2-0160ad9ad4d4.png)

Could this get implemented in the extension? 🙏

**Comment by Elias-Graf** [comment]
As far as I understand, this is not intended for multiple items. Correct me if I'm wrong, but I assume you can set **one** message per panel (that in your picture), and welcome content seems to be generally designed when the tree is empty, and has a completely different layout.

**Comment by Gruntfuggly** [comment]
As stated above - that only works for the message at the top of the view. I don't think this will ever be possible.
