### ISSUE TITLE
Cover python language

### ISSUE THREAD

**Issue by HenriqueAJNB** [Gruntfuggly/todo-tree#657]
I haven't seen any coverage for Python language and this would be a great feature

**Comment by rbmarliere** [comment]
+1

**Comment by rbmarliere** [comment]
Try installing ripgrep

e.g.
# apt install ripgrep

**Comment by xelcho** [comment]
@rbmarliere 
I am not understanding your comment...
like @HenriqueAJNB  I see this page w/ all this lang specific regex...
https://github.com/Gruntfuggly/todo-tree/wiki/Configuration-Examples

I would love to see one for python.

Please share how to implement your "workaround"!
thanks!

**Comment by Gruntfuggly** [comment]
It should work out of the box with python `#` type comments, e.g.
```python
print( 'hello') # TODO change this
```

  For multi line comments using `"""` you'll need to tweak the regex. 

If somebody can come up with one, I'll happily add it to the wiki.
