### ISSUE TITLE
customHighlight.foreground overrides iconColours

### ISSUE THREAD

**Issue by vphantom** [Gruntfuggly/todo-tree#66]
Hello,

I just noticed a sort of regression with the latest update: in order to keep having highly visible background highlights in my source files, I had to change `foreground` into `background` properties in my `customHighlight`.

Unfortunately, that change left the text in its original color unlike before where it was set black or white to contrast the background color (named "foreground") automatically.  No big deal though, I added "foreground" properties to be either black or white to get the old result back by hand.

The real bug is that now in the explorer tree, all icons have become white (or black) according to `foreground` in `customHighlight` instead of the color specified in `iconColours`, which is now entirely ignored.

**Comment by Gruntfuggly** [comment]
I tried to keep the original behaviour where the single colour specified was used for the icon, but also the background of the highlight.

As you say, that means that setting the foreground colour will set the icons colour too. When I was testing I did wonder what circumstances would cause the 'default' black or white text to be shown but I was lazy and guessed it wouldn't acutally happen any more!

I guess I either need to allow separate colours for foreground, background *and* icon (which I was hoping to avoid) or to allow the default black or white colour to be used if the foreground is not specified (and therefore use the background for the icon colour).

Maybe the configuration for the icon should come out of the defaultHighlight and customHighlight altogether - it doesn't feel quite right being in there.

I'll have a look at it...

**Comment by vphantom** [comment]
I do like the idea of setting black/white by default if foreground is not specified. :)

Thanks for looking into it!  I couldn't imagine working without this extension.

**Comment by Gruntfuggly** [comment]
OK, I've changed it so that if you specify a background colour but no foreground colour, it uses the background colour for the icon and black or white for the highlight depending on the background colour.

I think that should work - let me know if it doesn't...

Unfortunately the Marketplace is broken at the moment, so unless you fancy installing manually from the git repository, you'll have to wait until it's fixed... 😞

**Comment by Gruntfuggly** [comment]
Now published...

**Comment by vphantom** [comment]
Ah ha! In order to get the behavior you describe, I had to remove my old `defaultHighlight.foreground` setting. As a bonus, I no longer need to define `iconColours` now, just my list of `customHighlight` icons and backgrounds.

Thank you!
