### ISSUE TITLE
Chinese Localization is weird

### ISSUE THREAD

**Issue by sbwww** [Gruntfuggly/todo-tree#661]
![image](https://user-images.githubusercontent.com/45259695/184500697-b2638389-980e-433f-b6ae-fb49ee845996.png)

I suppose some items are not properly translated, i.e.,

- `Filtering` -> `滤波` weird `过滤` better
- `Regex` -> `雷格克斯` transliteration, no meaning `正则表达式` proper

Maybe opening a project on [Crowdin](https://crowdin.com/) helps with the localization in different languages.

@loniceras Thanks anyway for the great effort on Chinese localization!

**Comment by loniceras** [comment]
You are right. In fact the translations listed here were not contributed by me. I made a PR a few months ago to fix these translations, see #599.

**Comment by sbwww** [comment]
Thanks, hope it gets merged soon.
