### ISSUE TITLE
TODO Tree let typing so lag.

### ISSUE THREAD

**Issue by Edemilorhea** [Gruntfuggly/todo-tree#662]
Issue Type: Performance
Extension Name: todo-tree
Extension Version: 0.0.215
OS Version: Windows 10 
VS Code version: 1.70.0
Languages : C#
framework : Asp.Net Framework 4.6.1

I use it on my project it let me typing so slowly, 
Typing can have noticeable pauses, 
I tried many time if Stop use Todo Tree My VScode  will smooth.

**Comment by Gruntfuggly** [comment]
Please post your todo-tree settings (from the settings.json).

**Comment by Gruntfuggly** [comment]
Please feel free to reopen if you can give me some more information to try and fix this issue.
