### ISSUE TITLE
Feature: collapsable fully complete TODO lists

### ISSUE THREAD

**Issue by msilveirabr** [Gruntfuggly/todo-tree#664]
If possible, it would be interesting to be able to collapse TODO Lists (configurable to collapse by default/ or not ) where all list items are complete, with some way to change the icon of a completed todo list?

Something like this (current behavior):
![Screenshot from 2022-08-27 19-22-13](https://user-images.githubusercontent.com/834010/187050032-d7376447-d7c2-4370-8423-ad1f8c910aaa.png)

Turns into this:
![collapse-todo](https://user-images.githubusercontent.com/834010/187050185-8ddf2270-c6ca-4f2f-bb07-933f0cdcf5db.png)

Great work BTW. vscode together with extensions like this are a life changer!

**Comment by Gruntfuggly** [comment]
You can change the icon (and colour) using the custom highlight settings (see README.md). 

Another alternative would be to remove `[x]` from the tags list - the would then be collapsed or removed from the tree when they are all completed. Not quite what you're after, but it might be enouigh?

**Comment by Gruntfuggly** [comment]
I'm going to close this as the feature request is very specific to markdown TODOs and doesn't have any equivalent for other types of TODO. While I can see it would be quite a nice feature, it would be quite a lot of work to implement.

Sadly, I'm trying to limit changes to the extension now as the issues list is ever growing and I don't have the time to work on it.
