### ISSUE TITLE
Tag starting with '\'

### ISSUE THREAD

**Issue by wduminy** [Gruntfuggly/todo-tree#667]
I'd like to add `\todo` to `todo-tree.general.tags`.  I tried `\todo` and `\\todo` but it does not seem to work

**Comment by Gruntfuggly** [comment]
Have you tried `\\\\` - the `\` is the escape character in a regex, so it has to be escaped itself. If you're changing the regex using the json settings editor, you need 4 backslashes because the JSON needs to escape them too!

**Comment by ct2034** [comment]
I am having the same issue and `\\\\` did not work for me either.

**Comment by ct2034** [comment]
But @wduminy , if you are trying to do what I was trying to do, working with latex, then this would be enough: https://github.com/Gruntfuggly/todo-tree/wiki/Configuration-Examples#latex it worked for me.

**Comment by wduminy** [comment]
@ct2034 Thank you!  

After adding these config items the match `\todo` works.

```
"todo-tree.regex.regex": "((//|#|<!--|;|/\\*|^|%|\\\\)\\s*($TAGS)\\{*|^\\s*- \\[ \\])",
"todo-tree.regex.regexCaseSensitive": false,
```

@Gruntfuggly Thanks for a great extension.  I am closing this issue.
