### ISSUE TITLE
yaml support

### ISSUE THREAD

**Issue by JamesDevOpsShipman** [Gruntfuggly/todo-tree#668]
Is yaml support built in and I just don't have it configured correctly or is yaml support coming soon?

**Comment by bgoewert** [comment]
Works for me. I think it should detect all todo's in `todo-tree.general.schemes` (which should include `file` for any type of file) given that it matches the `todo-tree.regex.regex`.

![image](https://user-images.githubusercontent.com/15313658/207950412-20d6c4f0-e0a8-4eb0-8e68-e0f3bb4d1a87.png)

**Comment by Gruntfuggly** [comment]
Closing as no further information provided.
