### ISSUE TITLE
*.hbs file support

### ISSUE THREAD

**Issue by ValerianExp** [Gruntfuggly/todo-tree#669]
Hi, the extension doesn't work with *.hbs files. Doesn't highlight and doesn't appear on the todo tree
![imagen](https://user-images.githubusercontent.com/74860846/189791780-6cd0101e-626a-4e55-980d-272d7b6bdb83.png)
Thanks

**Comment by Gruntfuggly** [comment]
You'll need to configure the regex to match .hbs files. Please take a look at the wiki (https://github.com/Gruntfuggly/todo-tree/wiki) for some examples.

**Comment by Gruntfuggly** [comment]
Please feel free to reopen if there is problem with the configuration.
