### ISSUE TITLE
tree is empty

### ISSUE THREAD

**Issue by Chris591** [Gruntfuggly/todo-tree#67]
if you configure any Icon in the config and don't open a git or Folder it doesn't Show anything.
![image](https://user-images.githubusercontent.com/39920986/45140313-ab3d0c80-b1b2-11e8-8f66-47895d3c32ac.png)

![image](https://user-images.githubusercontent.com/39920986/45140359-d7588d80-b1b2-11e8-9205-a6d5d3ab6f35.png)

**Comment by Gruntfuggly** [comment]
You're right - I think it's because it can't write the icon file in to the workspace settings (becuase there is no workspace). I'll investigate...

**Comment by Gruntfuggly** [comment]
I've fixed it in the latest version. It revealed another bug too, where the view settings couldn't be changed, which I've also fixed. As a bonus, the fix should make the tree view *slightly* more responsive too.
