### ISSUE TITLE
[Feature Request] Display total count of todos

### ISSUE THREAD

**Issue by mustafaabobakr** [Gruntfuggly/todo-tree#672]
## Indicator to show if any `unsolved` TODOs 

<img width="127" alt="image" src="https://user-images.githubusercontent.com/27288406/190897385-352c7d89-701c-4f4d-a579-a69bc59ddc84.png">

Thank you for awesome work @Gruntfuggly

**Comment by Gruntfuggly** [comment]
Please try the latest version (updated today) 😄

**Comment by mustafaabobakr** [comment]
> Please try the latest version (updated today) 😄

WOW THANKS 💕🎉

<img width="1087" alt="image" src="https://user-images.githubusercontent.com/27288406/195976741-edabf0cd-83ae-494b-bd33-50050ddb5b9e.png">
