### ISSUE TITLE
v0.0.216 CANNOT use API proposal: badges

### ISSUE THREAD

**Issue by Vicriss** [Gruntfuggly/todo-tree#682]
Todo-Tree: Extension 'Gruntfuggly.todo-tree' CANNOT use API proposal: badges.
Its package.json#enabledApiProposals-property declares: [] but NOT badges.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api Gruntfuggly.todo-tree

my vscode info:
![image](https://user-images.githubusercontent.com/9296808/195772478-a270e4ce-0c93-4ba8-9aaf-76f25ec3b365.png)

**Comment by rocex** [comment]
windows7 x64
vsc 1.70.2
todo-tree too

**Comment by Gruntfuggly** [comment]
Version 0.0.216 of the extension is not compatible with older versions of VCode - please revert to version 0.0.215 for now, or update VSCode to the latest (1.172).

Sorry - I forgot to set the minimum version for the extension. This will get fixed later today.

**Comment by elhe26** [comment]
Getting the same issue.

**Comment by murugappanrm** [comment]
Getting the same issue

**Comment by Gruntfuggly** [comment]
Just published version 0.0.218 which should revert back the change and remove this error.

**Comment by murugappanrm** [comment]
Seems to be good now. Tq
