### ISSUE TITLE
Change Log dates are inaccurate

### ISSUE THREAD

**Issue by sugardave** [Gruntfuggly/todo-tree#684]
I just noticed that the changelog versions starting at `0.0.217` have the year listed as `2020` while `0.0.214`-`0.0.216` list `2022`.  If you use a tool to automate the Change Log entries it might need its clock checked.

**Comment by Gruntfuggly** [comment]
No, I do it manually - will fix it for the next release. Thanks for spotting it!

**Comment by Gruntfuggly** [comment]
Now fixed. 😄

**Comment by sugardave** [comment]
Yep, fixed 🧙🏼
