### ISSUE TITLE
Comments get repeated within "TODO: Tags Pannel" when saving documents

### ISSUE THREAD

**Issue by lazercaveman** [Gruntfuggly/todo-tree#687]
I have the problem that comments are repeated when saving a document within the output - so I see one and the same comment that I made somewhere 2,3,4,5 times (depends on how often I saved) in the panel. When manually refreshing the panel, the copies go away and everything is as it should be.

![Bildschirmfoto 2022-10-24 um 15 59 57](https://user-images.githubusercontent.com/20026370/197543987-057f064e-55c8-4308-9123-0fc8edf9be46.png)

"IMPROVE: specify type" is mentioned multiple times within the panel - and within the code it exists only once.

**Comment by Gruntfuggly** [comment]
I've just merged a PR which *might* fix this. Please can you try the latest version (0.0.220) and see if it is still an issue?

**Comment by lazercaveman** [comment]
Hello @Gruntfuggly, I testet it, and it looks like the problem is solved now - thank you very much. : )
