### ISSUE TITLE
Syntax highlighting dont work in vscode 1.73

### ISSUE THREAD

**Issue by sanojkl** [Gruntfuggly/todo-tree#690]
It is not a problem with the config works fine in vscode 1.72.

works fine after downgrading back

**Comment by dafo-formacio-oberta** [comment]
Same here!

**Comment by pull-task-dev** [comment]
Not sure if is root cause or not, but VSCode indicates this plugin has the following runtime error : Class constructor Yt cannot be invoked without 'new'

**Comment by Gruntfuggly** [comment]
There is a pull request to fix this, but I just haven't had time to merge it. I'm hoping to do it over the weekend. Sorry for the delay!

**Comment by sanojkl** [comment]
yes its fixed
