### ISSUE TITLE
Scan everything at startup?

### ISSUE THREAD

**Issue by MarekFodor** [Gruntfuggly/todo-tree#691]
Is there, or will there be some option in settings to scan every file in repo for tags at startup?

**Comment by dafo-formacio-oberta** [comment]
Same here !

**Comment by Gruntfuggly** [comment]
That should be the default behaviour?

In the tree view, it should say what the scan mode is currently set to, under the title bar. Check it isn't set to 'Scan open files only'.

**Comment by Gruntfuggly** [comment]
Assuming by repo, you mean workspace?

**Comment by Gruntfuggly** [comment]
Closing due to lack of updates - feel free to re-open if this is still an issue.
