### ISSUE TITLE
Feature Request: Support root configuration file

### ISSUE THREAD

**Issue by x0vr** [Gruntfuggly/todo-tree#699]
Hi,

due to I am working in teams a lot, it would be very nice to have the possibility to have a centralized configuration file in the root directory of the project workspace (synchronized in the repository). So everybody working in the project uses the same settings, especially our custom tags and so on.

(same logic like it is for ESLint using ".eslintrc.js", or Prettier using ".prettierrc" ...)

Or maybe that's even possible today somehow?
Would be nice if not everybody has to add custom tags to his VSCode user settings.
Or should we just use the default functionality of ".vscode/settings.json" shared in the repository?

Thanks in advance 👍

**Comment by bgoewert** [comment]
ESLint `.eslintrc.js` configs, and other tool configs like this, are not specific to IDE's whereas todo-tree is. It would not make sense to have a separate config file for this. If you are all on VSCode and looking for "centralized" (i.e., shared) settings specific to todo-tree, I would say `.vscode/settings.json` is your best option.

**Comment by Gruntfuggly** [comment]
I am going to close this as it's really a feature request for VSCode itself. Please feel free to re-open if you feel differently.
