### ISSUE TITLE
add usage of hex color codes

### ISSUE THREAD

**Issue by dwuttke90** [Gruntfuggly/todo-tree#7]
Hey there,

your extension is pretty nice. i'm using it in combination with the todo highlight extension. the in code highlighting is really nice there, but the todo listing is a pain tbh ;)

to use the same colors (more colors) it would be nice if you could add hex color codes instead of those few predefined colors.

**Comment by Gruntfuggly** [comment]
Hi - I'm glad you're finding it useful. 8-) I keep meaning to add a suggestion in the read me about using it in conjunction with todo-highlight (I do the same).

Regarding the colours - this is not easy as the icons are just files, but it might be possible to create new icons on the fly - I'll look into it...

**Comment by dwuttke90** [comment]
ah ye, didnt rly think about it tbh. that makes sense. any chance u can add an orange icon then? ;)
its the color im missing ;)

**Comment by Gruntfuggly** [comment]
Wasn't as difficult as I thought - try the latest version. 8-)

**Comment by dwuttke90** [comment]
nice one. thx alot man.
