### ISSUE TITLE
Escaped tags: So awesome they threaten to destroy my life.

### ISSUE THREAD

**Issue by BStudent** [Gruntfuggly/todo-tree#70]
I was getting lots of work done, until ...

![image](https://user-images.githubusercontent.com/19792522/45313770-aa72e600-b4e4-11e8-842d-03e0e0eb9efa.png)

Below,  find aaawesometagz.py

```python
# aaawesometagz.py

# found in ~bstudent wtf

# The tags ... they change color when you "check" the "checkbox."
# instructions: 
# 1) remove the python # -style comments from the code below.
# 2) Do not remove the json comment tags.
# 3) Paste the tags into appropriate sections 
# 3a) Make sure you have commas inserted appropriately if you
#     use other tags and highlights
# 4) Tested only on Linux (Pop_OS 18.04 and RHEL 7.5) - YMMV
# 
# NB: This is a python file because it's what I was coding when the
#     spirit of the backslash chose me to reveal this thing.  Python
#     has nothing to do with the mechanics of how it works, it's
#     just what I had open and configured in vscode.
# 
# (in waspy patrician voice) "Oh, my, github highlighting looks sooo dreary now.  It's positively dreadful!"

# // place your settings here to override default settings
# {
#   // ...
#   // settings that were once relevant, but no longer
#   // ...

#   // ...
#   // other todo-tree settings
#   // ...
#   "todo-tree.tags": [
#     // ...
#     // lesser tags
#     // ...
#     // the special characters must be highlighed
#     // in "todo-tree.tags", but not others todo-tree
#     // settings, see "todo-tree.customHighlight" below  
#     "CHECK\\[\\s\\]",  // can u feel the magic? note: \\s is 'space'
#     "CHECK\\[\\?\\]",  // r u ready to \e\s\c\a\p\e to the 
#     "CHECK\\[X\\]",    // land of backslashes\?  
#     // ...
#     // more lesser tags
#     // ...
#   ],
  
#   // ... 
#   // more other todo-tree settings
#   // ...

#   // Custom configuration for highlighting
#   "todo-tree.customHighlight": {  // this is where it gets real yo
#     // ...
#     // custom highlighting of lesser tags
#     // ...    
##    // 
#     "CHECK[X]": { // DO NOT ESCAPE THE SPECIAL CHARACTERS HERE
#     "icon": "verified",
#     "iconColour": "#00FF00",
#     "foreground": "#00FF00",
#     "background": "#003300",
#     },
#     "CHECK[ ]": { // ESCAPE IN .tags SECTION? YES. **NOT** HERE IN .customHighlight
#       "icon": "unverified", 
#       "foreground": "#EFEFEF",
#       "background": "magenta"
#     },
#     "CHECK[?]": {       // Now, say it all together: "we will not escape in .customHighlight" ... 
#       "icon": "issue-reopened", // "we will not escape in .customHighlight" 
#       "foreground": "yellow",   // ** I CAN'T HEEAAAR YOOUUU!!!  SAY IT AGAIN IN ALL CAPS!!!
#       "background": "#885500",  // "WE WILL NOT ESCAPE IN .customHighlight!!! XOREAX!! XOREAX!!"
#     }                           // That's better.  OK, you've earned it. And XOREAX to you, too.
#     // ...
#     // more custom highlighting of lesser tags
#     // ...  
#   }
#   // ... more settings that are no longer relevant to my life ...
#   // etc.  now for the show ...
# }

# TODO: wait for it ...

# THIS must be the place.
# CHECK[ ]: BStudent:: Is this escaped-tag stuff cool?? Must evaluate.
# CHECK[?]: BStudent:: hmmm... concerns I might spend all day on todo-tree tags now ...
# CHECK[X]: BStudent:: WHO AM I KIDDING THIS IS FREAKIN AWESOME IN ALL CAPS. 
# NOTE: MORE: TAGZ: NAO: !!!

# three weeks later ...
# FIXME: AStudent:: Patching this code by BStudent who dropped off a couple weeks ago 
# FIXME: AStudent:: B was a strong contrib until B discovered escaped tags 
# FIXME: AStudent:: Actually, this is pretty cool.  I'm sure I can handle it ... 
# And so the cyle begins anew.  Peace, live long, and XOREAX.





# EASTER EGG for those who read this far: delete the word CHECK from tags and highlights
# you get ... naked checkboxes!
```

**Comment by BStudent** [comment]
And I just realized ... I basically wrote a program ... using nothing but comments.  Metadata doesn't count.
**ACHIEVEMENT UNLOCKED.**

**Comment by Gruntfuggly** [comment]
Hi - thanks for the 'original' bug report! :smile:

But what is the *actual* problem?

**Comment by BStudent** [comment]
It's a time management thing.  An issue for me, at least.  
...
But, now that you mention it, _**the fix for this is to add this as an example in the doc page**_.   Or something along the same lines that you or someone else can dream up.  The most interesting part of it isn't captured well except when using it live.  
(note the attached image with just checkboxes as tags - intended to portray one line changing with time)
Perhaps best would be to use an _animated_ screen cap of a single comment line changing color as different checkmarks are put between the brackets (from blank, to ?, to !, to X).  It creates a different kind of visual perception than a static tag does.
I don't know if you played with TT this way before, but having it work in this mode is very different perceptual experience than just making tags, because it "animates" the color as you change a single character inside the checkbox, which is perceived as a "unit", so you get the sense you're throwing a switch in an existing tag rather than changing tags.
The doc paints a mental picture of static text tags that are color coded. Very useful.  But used in this way, TT gains a new dimension. 
**_The point being that it's not obvious that this can be done from the docs as-is._**  For example, I knew about the regex features when I first installed TT.  But looking at them offhand, in context, I presumed that regex was strictly for parsing comments of a particular language and not screwing it up.  That's not something I would mess with unless I'm using or inventing some really obscure new language.  Which I try to avoid these days.
It took being in the right place at the right time trying to do a particular thing to spark the idea.
And there's probably lots of other better discoveries out there waiting to be done.

![image](https://user-images.githubusercontent.com/19792522/45332103-8682c500-b523-11e8-891c-88b73764cebe.png)

**Comment by BStudent** [comment]
Actually, I thought of a feature request that would go very nicely with the above.

- add a new setting, `todo-tree.groups`
-  each entry is a 3-tuple comprising:
1. The `tag`, which must be unique in this setting and must exist in todo-tree.tags
2. String or int unique identifier of the Group to which it belongs (i.e.) a Tag can only belong to one group, but a group can have multiple members,,,,,,,,,,,,,,,,,,,,,
3. an ordinal giving its relative position in the group, the rule being that no two group members can have the same value
4. *optional: Another ordinal giving the tag's order in the global group of all tags, again in this case it must be unique for each tag
5.  Now assign a hotkey (two if you have the optional global id in force).
6. while hovering over the comment, or with the cursor in the line, hit the hotkey, and that tag rotates to the next member of the group, which cycles back to the min-value ordinal tag after it's been on the max value tag of its group.
I don't know what you or others, do  but I often set up my tags so they have a logical transition from one state to another, say: TODO, CODE COMPLETE, TEST1, TEST2, VALIDATED
That would be a time-saver in cut/paste/type and it would add some additional flair.  But the ..

**Comment by Gruntfuggly** [comment]
Right - I'm with you now. Yes, the TODO's are updated whenever the document is saved and the highlights are updated on any change, so you'll get the effect you've noticed. I'll add something to the README.md so it's a bit more obvious.

The whole highlighting thing was a bolt-on so it's sort of evolved. When I first added it I didn't envisage it being as customisable as it is now. 

I like the tag groups idea. As you say, people use things differently to your expectations! I'll see if I can add it when I get some spare time. I'll have to research hover providers... :smile:

**Comment by BStudent** [comment]
Cool.  I think showing people how to use arbitrary characters by escaping
them properly will yield more unexpected results.
Probably something else neither of us has thought of yet will be even more
useful.
I've been working on a new program with many moving parts and a lot
of things that need attention scattered all over, with varying
dependencies, some more critical than others.
By the end of the night after posting that last image, my whole coding
workflow was organized around going through the checklist in the sidebar
and making the red become green...
And I did that not because I was enamored by my new toy, but because
-although I did not know it -  I really needed something like that to keep
my priorities in order, and to show me how much I'd done and how much was
left.
So that's a sign you're on a good track ....

**Comment by Gruntfuggly** [comment]
I've been doing a bit of tidying up of old issues and have realised that this one could really be implemented by a separate extension. Currently the todo-tree extension is passive in as much as it doesn't change any files - with this proposal, it would be necessary to update files with the tag changes.

I think a simple sibling extension could be written though to handle the tag progression, which would automatically work with todo-tree anyway.

**Comment by haakonstorm** [comment]
Hey, I know I'm late to the todotreehugging party, but I've come up with [yet another way to abuse your extension](https://www.reddit.com/r/vscode/comments/fr3xd6/different_font_styling_for_different_kinds_of/)! 
Perhaps it would be possible to add a way for a tag to NOT be added to the actual todo-tree? :-D Currently, your extension is super useful over here - just as long as you don't need todos :)

**Comment by Gruntfuggly** [comment]
Somebody has requested an option to hide tags from the status bar, so it could be implemented at the same time. Shouldn't take too long...

**Comment by haakonstorm** [comment]
Hey, this is awesome news! Once that is up and running, I'm going to test out @BStudent 's dynamic todo tags. 

Also - I know you have to save before the extension can pick up changes and stuff text through `ripgrep` (awesome tool!) - but perhaps it's possible for an extension to save the _current_ - unsaved - text, to a temporary file, and stuff that through `rg`? 

(By the way, @BStudent - if you haven't already - check out font ligatures in the font you are using for VS Code. You can create a custom ligature for `[x]` to be replaced by ✅ or ☑ and `[ ]` to be rendered as ☐, for example. )

**Comment by Gruntfuggly** [comment]
Actually - there already is an option to hide tags from the tree! I forgot I added it 🙄 
You can set `hideFromTree: true` in the custom highlight settings to prevent the tag showing in the tree.

**Comment by Gruntfuggly** [comment]
I've just uploaded a new version which updates the tree when you edit the file. There is a small timeout of half a second after you stop typing.

**Comment by Gruntfuggly** [comment]
Closing, as I don't think there is anything outstanding now.
