### ISSUE TITLE
Multi-Line Todos not working for python

### ISSUE THREAD

**Issue by njahncke-megaphone** [Gruntfuggly/todo-tree#700]
Hey, fantastic work on this extension; I really hope I can get it working properly. Regardless, thank you for your contribution to the community.

I've read through everything I could find regarding Multi-Line comments, and have tried the various regexes suggested on the [Configuration Examples page](https://github.com/Gruntfuggly/todo-tree/wiki/Configuration-Examples), all to no avail. I have also disabled all other running extensions on the off-chance of a conflict. Still nothing.

To be clear about the desired behavior, I have a simple config for TODO tags that applies a style, and the intent is that that style would be applied to both of the lines in the following example. At present, the style is applied only to the first line (the number of post-comment-character spaces in the second line has no impact).

```
# TODO: This is a test comment.
#       This is the second line of a test comment.
```

Here is my Todo Tree config. As I indicated above, I have tried the various regexes suggested, but none worked.

```
  // Todo Tree
  "todo-tree.regex.enableMultiLine": true,
  "todo-tree.highlights.defaultHighlight": {
    "type": "text-and-comment"
  },
  "todo-tree.highlights.customHighlight": {
    "TODO": {
      "icon": "check",
      "foreground": "#FFA500"
    }
  },
```

Unfortunately I am currently unable to find the time to create/debug my own regex, but will do so as a last resort. I hoped maybe there was something simple I was overlooking.

Thank you for your assistance!

**Comment by njahncke-megaphone** [comment]
I should have said that although I wrote the issue title as python-specific, I have tested .js files in my environment and those don't work either.

**Comment by njahncke-megaphone** [comment]
Thanks for your reply, but that regex does not solve the issue in VS Code. It apparently fails to compile.

**Comment by Gruntfuggly** [comment]
Did you put the regex above into the JSON settings page or the GUI? If you used the JSON, you'll need to escape all the backslashes.

I haven't tried it myself, but that could be one reason it didn't compile.

**Comment by njahncke-megaphone** [comment]
I did use the GUI as that should do the escaping, but it didn't for this regex. Maybe it's too long?

**Comment by Gruntfuggly** [comment]
To be honest, that is a monster regex! I tried pasting it into regex101 and it didn't work. 😞 
I don't think length should be an issue though. 

The very simplest regex I could come up with to match your example above is:
```json
"todo-tree.regex.regex": "(#)\\s*($TAGS)(.*\\n#.*)*"
```
It doesn't show the first line in the tree though, so it needs a bit more work.

**Comment by Gruntfuggly** [comment]
It looks like the latest version of ripgrep (v.13) changed the way multiline searches work, which explains why some of the issues are happening. This extension uses `--vimgrep` to make parsing the output easier, but it sounds like this no longer outputs all lines of a multi line search. I'll have to do some more digging.

**Comment by njahncke-megaphone** [comment]
That worked great! Thanks a ton. It actually does include the first line for me in the tree. Works perfectly, honestly, but my use may be much less sophisticated than other users (basically just duplicating pycharm behavior).

Thanks for the great work!

**Comment by Gruntfuggly** [comment]
I'm going to close it - I'm currently trying to reduce the number of open issues. If you find any problems, feel free to re-open. I'll probably need to find a new way to decode multi-line todos from ripgrep, but it's low priority at the moment!

**Comment by njahncke-megaphone** [comment]
Thanks a lot for the help! I really appreciate this extension.

**Comment by yCodeTech** [comment]
> I'm going to close it - I'm currently trying to reduce the number of open issues. If you find any problems, feel free to re-open. I'll probably need to find a new way to decode multi-line todos from ripgrep, but it's low priority at the moment!

I vote to reopen this. As #644 states, multiline matching highlights the whole file from the start of the tag to the end of the file, which also includes all non-comments too; and it doesn't matter which variation of regex is used.

Breaking down long TODO descriptions into multiline comment instead of one giant one, is very common and looks cleaner. The multiline issue needs to be raised to high priority.

**Comment by njahncke-megaphone** [comment]
I'm not sure why but the fix presented on January 26 no longer works for me, though I'm not experiencing the behavior described by @yCodeTech.

At present I'm forced to use the tag prefix before every line I want highlighted.
