### ISSUE TITLE
Single-line Python docstring not detected

### ISSUE THREAD

**Issue by alexreg** [Gruntfuggly/todo-tree#701]
Using a single-line Python docstring like

```python
"""TODO"""
```

does not get picked up.

On the other hand, the following does get picked up correctly.

```python
"""
TODO
"""
```

**Comment by Gruntfuggly** [comment]
What have you set the regex to?

**Comment by alexreg** [comment]
@Gruntfuggly My only config setting is the following.
```jsonc
	"todo-tree.general.tags": [
		"BUG",
		"HACK",
		"FIXME",
		"TEMP",
		"TODO",
		"XXX",
	],
```

**Comment by Gruntfuggly** [comment]
Ah OK, yes, it matches your second example due to the default regex.
You'll need to add something to the regex, e.g. 
change it from
`(\*|//|#|<!--|;|/\*|^|^[ \t]*(-|\d+.))\s*($TAGS)`
to
`("""|\*|//|#|<!--|;|/\*|^|^[ \t]*(-|\d+.))\s*($TAGS)`

**Comment by alexreg** [comment]
@Gruntfuggly That does the job, thank you. Incidentally, the `\*` wasn't there by default — what's that for?

Also, will you be adjusting the default in a future release? No worries if not.

**Comment by alexreg** [comment]
@Gruntfuggly That's fair enough. Thanks!
