### ISSUE TITLE
[feature] Only show the specified tag's count?

### ISSUE THREAD

**Issue by yunyuyuan** [Gruntfuggly/todo-tree#705]
I have a custom tag `*DEBUG`, which indicates that the following code is for debug only, I want the activity bar to show only the `*DEBUG` tag's count,so that I can pay attention to them before committing.

**Comment by Gruntfuggly** [comment]
Thats currently not possible - the count only shows the total. I could potentially add a 'hideFromBadgeCount' so you could only include the tags you're interested it.

**Comment by Gruntfuggly** [comment]
I've added support for this to the latest version - you can now specify 'hideFromActivityBar' for custom tag highlights.

Should be available in 0.0.221 shortly.

**Comment by yunyuyuan** [comment]
@Gruntfuggly Thanks a lot! Here is an example for people who find this issus:
### Set todo-tree.highlights.customHighlight
![image](https://user-images.githubusercontent.com/45785585/213952968-7e847185-075e-4923-b7cf-5246a52c5d13.png)
### Result
![image](https://user-images.githubusercontent.com/45785585/213953175-73bf92e8-4e84-48c7-81f5-bac9559562a9.png)
