### ISSUE TITLE
color always same white in julia comments

### ISSUE THREAD

**Issue by AbhimanyuAryan** [Gruntfuggly/todo-tree#706]
no matter what I use #BUG #FIX the colors is always same i.e. white in Julia code

#FIX
#BUG

**Comment by Gruntfuggly** [comment]
What settings are you using?

**Comment by AbhimanyuAryan** [comment]
@Gruntfuggly I am just using https://open-vsx.org/extension/wendreof/ufo theme with vscodium and no color. In VSCODE with https://marketplace.visualstudio.com/items?itemName=felipe-mendes.slack-theme just one color

I have not changed anything. I am just using the extension as it is....no personal configuration

**Comment by AbhimanyuAryan** [comment]
you can look at this here: 

<img width="616" alt="Screenshot 2022-12-14 at 6 26 05 PM" src="https://user-images.githubusercontent.com/8083613/207600943-9fba4b19-a569-4822-a233-bc53b5da63d5.png">

**Comment by Gruntfuggly** [comment]
Colour highlights aren't enabled by default. You can configure any colours you want (see the README.md) but the simplest way to get coloured highlights is to enable `todo-tree.highlights.useColourScheme`.

**Comment by AbhimanyuAryan** [comment]
sorry my bad. I assumed it work out of box and I liked the default scheme in README.md so had nothing to change. I'll close this.
