### ISSUE TITLE
Show count icon in menu bar icon (like branch commit files)

### ISSUE THREAD

**Issue by TheFrogDaddy** [Gruntfuggly/todo-tree#71]
<img width="60" alt="screen shot 2018-09-14 at 17 05 25" src="https://user-images.githubusercontent.com/5995357/45562200-94955600-b841-11e8-8519-83db800dad15.png">

**Comment by Gruntfuggly** [comment]
Duplicate of #22 

Unfortunately there's no API for this at the moment. If the vscode team add support for it, I'll add it to the extension.

**Comment by TheFrogDaddy** [comment]
Ah ok. No worries and thanks for the prompt feedback. Great extension btw,
