### ISSUE TITLE
The list seems not honor `.gitignore`, and (maybe) strange behavior on binary files.

### ISSUE THREAD

**Issue by yw662** [Gruntfuggly/todo-tree#711]
I noticed recently that when I build the project, TODO Tree may list files in build dir and build cache, but they would disappear after I click the refresh button.
like this: it is a binary build cache already excluded in gitignore, and it does not seem to contain any search terms.
<img width="388" alt="截屏2022-12-21 下午5 11 18" src="https://user-images.githubusercontent.com/34736747/209033150-efebcef3-b7e0-4ecc-9799-e51f68e13208.png">

It does go back to normal after I clicked the refresh button though.

**Comment by Gruntfuggly** [comment]
Could you post your todo-tree settings? There are settings to exclude specific files/folders so it might be worth trying those.

**Comment by Gruntfuggly** [comment]
ripgrep (which the extension uses) honours .gitignore by default so I'm surprised it is picking up an excluded file.

**Comment by yw662** [comment]
Sadly I can no longer reproduce it :-(

**Comment by yw662** [comment]
It happens again
```json
{
  "todo-tree.highlights.highlightDelay": 0,
  "todo-tree.general.tags": [  ],
  "todo-tree.general.tagGroups": {  },
  "todo-tree.general.statusBar": "tags",
  "todo-tree.highlights.enabled": true,
  "todo-tree.general.showIconsInsteadOfTagsInStatusBar": true,
  "todo-tree.highlights.customHighlight": { },
  "todo-tree.tree.scanMode": "workspace",
  "todo-tree.tree.expanded": true,
  "todo-tree.tree.showCountsInTree": true,
  "todo-tree.general.showActivityBarBadge": true,
}
```

It is a cf pages project using parcel. The command I run when it happens is
`wrangler pages dev --proxy NNNN -- parcel --port NNNN --no-autoinstall`

**Comment by yw662** [comment]
It does not happen with `"todo-tree.tree.scanMode": "workspace only"`

**Comment by Gruntfuggly** [comment]
Why do you have `"todo-tree.general.tags": [  ]` ? Using that with the default regex may have very confusing results because it replaces `$TAGS` in the regex with the contents of that setting.

The extension is intended to find things marked 'TODO', etc. What are you expecting it to find with your configuration?

**Comment by yw662** [comment]
Hmmm no it is not `"todo-tree.general.tags": [  ]`, it is a long tag list I am not willing to post here :-).
And the same for `tagGroups`.

**Comment by Gruntfuggly** [comment]
Are you using the default regex?

**Comment by yw662** [comment]
This is all the settings so yes.

**Comment by Gruntfuggly** [comment]
OK - first thing - set this back to false: `"todo-tree.general.enableFileWatcher": false`. It won't be helping and is highly unlikely to be useful.

Can you post an example of a file (or part of a file) with the filename and what you're expecting it to match?

**Comment by yw662** [comment]
And an example:
```ts
// file: nominal.ts
declare global {
  type Nominal<T, name extends string> = T & { __name: name }
  type Structural<N extends Nominal<unknown, string>> = Omit<N, '__name'>
}

export function nominal<N extends Nominal<T, string>, T = Structural<N>>(v: T) {
  // eslint-disable-next-line @typescript-eslint/consistent-type-assertions
  return v as unknown as N
}
```

Expecting to match: // eslint-disable-next-line @typescript-eslint/consistent-type-assertions

**Comment by Gruntfuggly** [comment]
so `eslint-disable-next-line` is one of the tags?

The file watcher setting is due to be removed as it causes way more problems than it solves.

**Comment by yw662** [comment]
Actually no. The tag is `eslint`, so it matches all `// eslint-*`.
