### ISSUE TITLE
Support TODO in block comment

### ISSUE THREAD

**Issue by nvmnghia** [Gruntfuggly/todo-tree#713]
I cannot write a TODO like this:

![image](https://user-images.githubusercontent.com/22721156/209047476-e649acaa-9e87-4d10-828d-6c81cabf8ebf.png)

I search the issues using "block comment" and "function comment" to no avail.

**Comment by Gruntfuggly** [comment]
Please have a look in the wiki for examples to do this: https://github.com/Gruntfuggly/todo-tree/wiki/Configuration-Examples
