### ISSUE TITLE
Highlight the line containing the todo

### ISSUE THREAD

**Issue by ymyke** [Gruntfuggly/todo-tree#722]
From the README: 

"Clicking a TODO within the tree will open the file and put the cursor on the line containing the TODO."

Since I don't see the cursor as long as I don't bring the focus to the editor window, it's often hard to find the todo on the page. 

Is there a setting to highlight the line with the todo? Similar to what the "Search: Find in Files" does? 

If not, would that be a worthwhile feature maybe?

Thanks for the great extension!

**Comment by yw662** [comment]
use `todo-tree.highlights.customHighlight`.

**Comment by ymyke** [comment]
I'm using that for permanent highlights, yes.

What I'm looking for is a temporary highlight (i.e., quickly flashing the line with the todo) to draw attention to it.

**Comment by Gruntfuggly** [comment]
It sounds possible, but it might be a bit tricky to do something with the current highlight. I could perhaps flash a highlight on the entire line?

I was wondering why this isn't an issue for me, but I realised it's because vscode highlights the current line. Does your not do this? I can't find a setting to turn it off.

**Comment by ymyke** [comment]
Interesting. My vscode doesn't flash the line. Tried different themes too. – It does flash/highlight when clicking on a "Find in Files" result though. 🤔

**Comment by Gruntfuggly** [comment]
sorry - it doesn't flash the line, but it does indicate the current line in the editor with a line above and below:

 
![image](https://user-images.githubusercontent.com/376658/214819639-3114fd52-80b6-4638-bc9b-d00d458d2e4d.png)

**Comment by ymyke** [comment]
I see what you mean. I have dialed that down via `"editor.renderLineHighlight": "gutter",` so in my case it is very subtle to see which line is highlighted. For me, it would be great to have a quick flash upon clicking a todo. But if I'm the only one, it's maybe not worth the effort.

**Comment by Gruntfuggly** [comment]
I think it should be fairly easy to do - should even be able to use the same colour as the find in files flash. It will make it more consistent with VSCode too. 8-)

**Comment by Gruntfuggly** [comment]
This will be in the next release.

**Comment by ymyke** [comment]
Fantastic, thank you!

**Comment by ymyke** [comment]
Works like a charm and improves UX a lot, thanks! 🙏
