### ISSUE TITLE
Please remove console logs from published extension code

### ISSUE THREAD

**Issue by jayu** [Gruntfuggly/todo-tree#724]
Hey, I have this extension installed and I've noticed it prints a ton of logs in extension development console

<img width="812" alt="image" src="https://user-images.githubusercontent.com/11561585/216596291-a14e7f43-6730-44ce-b5c0-d30dff3c59f8.png">

It makes it hard to develop other extensions with such a frequent logging.
I think this line might be the reason 

https://github.com/Gruntfuggly/todo-tree/blob/598a46be532b7d51814face262ff3ec42630664c/src/config.js#L203

Please remove logging if possible 😁 

If you want to keep console.logs for development, you could perhaps use babel plugin like https://www.npmjs.com/package/babel-plugin-transform-remove-console, but it would require some additional setup since you are using `ts-loader`

Or setup custom logger function that would just output nothing in production env.

**Comment by Gruntfuggly** [comment]
Yes - sorry, that shouldn't be there. I also hate it when extensions pollute the logs. I'll remove it for the next version (won't be too long).

**Comment by Gruntfuggly** [comment]
Should be removed in the latest version (0.0.224)
