### ISSUE TITLE
Todo tree disappeared

### ISSUE THREAD

**Issue by wimZ** [Gruntfuggly/todo-tree#725]
I have been using todo-tree for a long time now. 

I read about dragging the tree to the explorer pane.

Tried it, and it appeared there.  Then I wanted to drag it back.  
The result is that the tree is nowhere and the icon has disappeared from the activity bar.

I uninstalled, removed folder restarted reinstalled, etc.  No success  

Your help is appreciated.

**Comment by Gruntfuggly** [comment]
The easiest way to find it is **View** -> **Open View...** which should have the view in the list.

**Comment by wimZ** [comment]
That helps, it's there again.  In 'open view ... ' it showed as 'sidebar/bookmarks' happens to be accessible under another extensions icon (bookmarks) in my case. 

Uninstalled both, now all is OK again.

Thanks
