### ISSUE TITLE
Not Working for VB Scripts

### ISSUE THREAD

**Issue by irahhari** [Gruntfuggly/todo-tree#726]
As you can see from the image, TODOs which are present in a line starting with single quote, the extension is not highlighting it.
But the extension is working properly for TODO in the line which doesn't start with single quote.
![image](https://user-images.githubusercontent.com/76170080/217771253-a045cfac-55b7-484d-bf80-f5fa07ba80fc.png)

**Comment by Gruntfuggly** [comment]
Have you modified the settings to work with VB scripts? It doesn't support it out of the box. You'll need to add the single quote to the starting section of the regex. Please see the examples in the [Wiki](https://github.com/Gruntfuggly/todo-tree/wiki).

**Comment by irahhari** [comment]
I didn't know the regex, which is why I was clueless. After studying it for sometime, I got it and even posted the regex in the [Wiki](https://github.com/Gruntfuggly/todo-tree/wiki/Configuration-Examples#visual-basic-vb) page for other's reference.

**Comment by Gruntfuggly** [comment]
Thanks - I wish a few more people would do the same!
