### ISSUE TITLE
Support for tags with regex special chars

### ISSUE THREAD

**Issue by Wharenn** [Gruntfuggly/todo-tree#73]
Hi ! 

Just discovered this awesome extension and wanted to use its configurable behavior to track nasty habits like analysis exception comments. This works like a charm with standard words like `eslint-disable-line` but it seems expressions with regex chars like `$FlowFixMe` are creating a mess. I tried to escape those characters with no success.

Is there any way to make it work right away? If not, it may be a good improvement to this extension :)

**Comment by Gruntfuggly** [comment]
Hmm - I would have thought escaping them should work. I'll look into it...

**Comment by Gruntfuggly** [comment]
This seems to be a limitation of ripgrep - when I tried your example I got the error:
`alternations cannot currently contain empty sub-expressions`
Honestly, I don't know what that means.

My regexfu is not up to scratch, but I could make it work using `[$]FlowFixMe`...

If you want to experiment with the regex, you can set `todo-tree.debug: true` (and restart) and then you'll get a channel in the output window (todo-tree) which will show the ripgrep command being executed and the results...

**Comment by Wharenn** [comment]
Thanks @Gruntfuggly, the `[$]FlowFixMe` trick worked!
