### ISSUE TITLE
Support for rust `todo!()`

### ISSUE THREAD

**Issue by lylythechosenone** [Gruntfuggly/todo-tree#731]
Rust has a macro, `todo!("message")` that panics with "Not yet implemented: message". It would be nice to have a list of these. It could work just like the TODO comments, but use that syntax instead.

Do note, `todo!()` macros can also exist with no message.

**Comment by Gruntfuggly** [comment]
Does it work if you add `todo!` as a tag (with the Todo Tree: Add Tag command) ?

**Comment by lylythechosenone** [comment]
Oh, surprisingly it does! Thanks!
