### ISSUE TITLE
TODO in Remote Workspaces via ssh fs

### ISSUE THREAD

**Issue by FrankFrank9** [Gruntfuggly/todo-tree#735]
Hi,

@Gruntfuggly 

Is there any way to make it work via ssh fs? (https://marketplace.visualstudio.com/items?itemName=Kelvin.vscode-sshfs)

Regards,

**Comment by Gruntfuggly** [comment]
Not really - it uses ripgrep to search the workspace files, so that would need to be installed on the remote machine. I guess it would technically be possible but could end up being quite complicated.
