### ISSUE TITLE
No Longer Shows in Activity Bar

### ISSUE THREAD

**Issue by Greeley** [Gruntfuggly/todo-tree#736]
VSCode latest.
MacOS.

I haven't seen todo tree in my activity bar in months, It's not on the status bar, using command+shift+p and selecting any of the todo tree commands doesn't do anything.
Installing older versions doesn't make it show up either.

**Comment by Gruntfuggly** [comment]
What version of the extension do you have installed?

If you go to View -> Open View... and then select TODOs from the list, does it reveal the view somewhere?

**Comment by Gruntfuggly** [comment]
Any luck finding the view?

**Comment by ClemensJakob** [comment]
Same here ( VSC + MacOS). View nowhere to be found.

**Comment by danielthedifficult** [comment]
I'm having the same issue.

Mac OS, VSC 1.76.2
TODO Tree: v0.0.224 - 2023-02-09

Interesting fact: The activity bar indictators show when I'm in the extension page.

![TODO Showing](https://user-images.githubusercontent.com/1290033/225602185-b825e0f6-1d58-4f39-b98e-8eece16d9627.png)

But it is gone when I close the window.
![TODO Not Showing](https://user-images.githubusercontent.com/1290033/225602180-999d3229-81ad-4f3b-89d4-21109c656181.png)
Note, there is a spinning status indicator "Activating Extensions" in the activity bar just after it disappears. Then, that status indicator finishes and the TODO indicators are gone.

I enabled debug output, I just see it searching the repo and finding files/matches, no error messages. The last messages logged are:

```
12:21:49.706 Found 95 items
12:21:49.706 Applying globs to 95 items...
12:21:49.713 Remaining items: 95
```

I'd rather not paste the whole log with the filepaths and matching code, but if I can provide other information, I'm happy to.

**Comment by Gruntfuggly** [comment]
Have either of you tried what I suggested in the second comment? Is the view listed in the menu?

**Comment by ClemensJakob** [comment]
It was not listed. But reinstalling helped 👍

**Comment by danielthedifficult** [comment]
Hi @Gruntfuggly I admit I looked around to find the View menu and couldn't figure it out (admittedly after a long day..)

I'll look again.

FWIW, I did try reinstalling and that didn't fix it.

**Comment by Gruntfuggly** [comment]
The side bar *is* the activity bar. Can you please explain what the actual issue is?

**Comment by danielthedifficult** [comment]
I'm sorry, I understand now I've been using the wrong terminology.

![image](https://user-images.githubusercontent.com/1290033/226070432-6cf698f7-d756-45e4-a042-1d07045ff373.png)

According to the labeling in this image, I'm missing the indicators of Hack, Todo, etc. in the blue "side bar" at the bottom left side of the screen.

**Comment by Gruntfuggly** [comment]
Ah OK, so what you have labelled as Side Bar there is just part of the status bar (but left aligned).

There are several options for what is displayed in the status bar - have a look in the README.md at `todo-tree.general.statusBar`.

**Comment by danielthedifficult** [comment]
Thank you Nigel, I had already looked in the preferences and it was set to
"current file" but not showing anything, even in a file with todos.

However, I changed it to "top three" and it's working now, and still works
when toggled back to "current file".

Thanks!

**Comment by Gruntfuggly** [comment]
Going to close this now as I think everybody's issue has been resolved :smile:
