### ISSUE TITLE
No hover effect for sidebar icon?

### ISSUE THREAD

**Issue by niccolomineo** [Gruntfuggly/todo-tree#737]
Hi @Gruntfuggly, I [reached out](https://github.com/microsoft/vscode/issues/174031) to the guys at VSCode asking why some extensions' sidebar icons do not have a proper hover effect like the default ones, and they said it's up to the extension creator to deal with the hover effect.

Would you be able to implement it to make the UI more consistent?

This is what I am talking about:

Any default VSCode sidebar icon:

![218056442-31ae9bf2-6245-4102-91e2-a65e480b8f3f](https://user-images.githubusercontent.com/5409469/223436982-f2d31c44-504e-4831-8582-5e7bce52cf8c.png)

ToDo Tree's icon:

![218056596-17d1fe63-02ab-465b-9b29-66334c866310](https://user-images.githubusercontent.com/5409469/223437004-66a66180-c0ae-455a-ae3b-09a59565c513.png)

**Comment by Gruntfuggly** [comment]
I don't understand - what is wrong with "TODOs"? Do you mean is should be translated?

**Comment by niccolomineo** [comment]
> I don't understand - what is wrong with "TODOs"? Do you mean it should be translated?

Focus on the icon, not on the tooltip. The hover effect on the icon should be to highlight the icon with a lighter color (per the first screenshot).

**Comment by Gruntfuggly** [comment]
Ah OK - I see what you mean now. 

Interestingly I don't get the hover effect on any extensions I have installed. Can you point me to one which does work?

The extension icon follows all the guidelines specified here:
https://code.visualstudio.com/api/references/contribution-points#Icon-specifications

Can you point me to any documentation on how to make it work?

To be fair, sandy081 doesn't actually say it's possible.

**Comment by Gruntfuggly** [comment]
Also, notice that the icon is dimmed when the view is not active, but bright when active. That's entirely controlled by VSCode so I think it's a VSCode problem, not the extension.

**Comment by Gruntfuggly** [comment]
To be clear - if you can find an example I can copy, or an explanation of how to do it, I'm more than happy to try and make it work 😄

**Comment by niccolomineo** [comment]
> Ah OK - I see what you mean now.
> 
> Interestingly I don't get the hover effect on any extensions I have installed. Can you point me to one which does work?
> 
> The extension icon follows all the guidelines specified here: https://code.visualstudio.com/api/references/contribution-points#Icon-specifications
> 
> Can you point me to any documentation on how to make it work?
> 
> To be fair, sandy081 doesn't actually say it's possible.

Uhm, you are right, I clearly misread it. I guess then I'll push the guys at VSCode to even this one out.

**Comment by Gruntfuggly** [comment]
Good luck! I'll leave this open for a while in case you get them to make it possible.

**Comment by Gruntfuggly** [comment]
Just noticed the gitlens (on my work machine) works as expected, so I'll take a look at what's different.

**Comment by Gruntfuggly** [comment]
Sorry, but I don't think this is going to be possible. I don't have the time to look into creating web fonts to make it work, but if somebody wants to create a PR I'll happily merge it in.

**Comment by niccolomineo** [comment]
> Sorry, but I don't think this is going to be possible. I don't have the time to look into creating web fonts to make it work, but if somebody wants to create a PR I'll happily merge it in.

The following zip contains an .otf, .woff, .woff2. Let me know if there are any further tweaks that need to be made. This is as far as I can go to help you tackling this, I am afraid.

[ToDoTree.zip](https://github.com/Gruntfuggly/todo-tree/files/11219661/ToDoTree.zip)

**Comment by Gruntfuggly** [comment]
Thanks - I'll try it out at the weekend.

**Comment by niccolomineo** [comment]
> Thanks - I'll try it out at the weekend.

if you need some inspiration, take a look at [this](https://github.com/moshfeu/vscode-compare-folders/issues/116#issuecomment-1508938944) discussion.
