### ISSUE TITLE
have number count by icon

### ISSUE THREAD

**Issue by bobbymannino** [Gruntfuggly/todo-tree#739]
Having a badge number by the icon would be a great addition. It could disappear on 0 and show on any more than 0. Same style as the default badge (red). Would be a nice touch

**Comment by Gruntfuggly** [comment]
Please try `todo-tree.general.showActivityBarBadge`

**Comment by bblanchon** [comment]
Awesome feature! It should be enabled by default.

**Comment by bobbymannino** [comment]
Defintely should be, i didn’t realise it was a feature so would be a good default

**Comment by Gruntfuggly** [comment]
It used to be enabled by default but you get unexpected behaviour when the tree is in the explorer pane - it puts the count on the explorer icon.
