### ISSUE TITLE
tags are scrambled as of v0.0.88 - 2018-09-22

### ISSUE THREAD

**Issue by beebase** [Gruntfuggly/todo-tree#74]
I'm not sure what is causing this, but some text parts in comments start to appear randomly in my todo-tree.
example:
I have "backlog2>" defined as a tag.
In my planning.txt file there are some "backlog2" tags.
Some of them appear as "ba" "back" etc in the todo-tree, grouped by file,
although the todo-tree is set up as "groupByTag"
 
![image](https://user-images.githubusercontent.com/446089/45950681-23079580-c001-11e8-9d2e-93907d6f8223.png)

This also happens with other file types like .js .vue

**Comment by Gruntfuggly** [comment]
That's a bit rubbish. Please could you attach your `todo-tree.tags` and `todo-tree.regex` (if it's been modified) and a small sample of the code which it's matching incorrectly?

**Comment by Gruntfuggly** [comment]
Hmmm - works for me, but that's no help.

If you set `todo-tree.debug` to `true` and restart, you'll find a debug channel in the Output view (called todo-tree). Next time it goes wrong, can you cut and paste the contents of the debug channel? That way I can eliminate the ripgrep search first of all.

**Comment by beebase** [comment]
I did a clean install but that didn't help. Maybe another extension is interfering. I will post back if something comes up.
One other weird thing which seems to occur after re install. Foreground color "white" shows as black now. However all other colors like magenta, green, blue etc seem to work ok with foreground.(see screenshots)
![img2798](https://user-images.githubusercontent.com/446089/46018201-9bda2080-c0d9-11e8-9cbb-3aab42e02a20.jpg)

![img2796](https://user-images.githubusercontent.com/446089/46018330-e9568d80-c0d9-11e8-8363-55d284fd0394.jpg)

**Comment by Gruntfuggly** [comment]
Try the debug if you can.

The colour problem is because 'white' is not a defined colour for todo-tree. :grin: The predefined colours were intended to be able to work in light and dark themes, so I didn't think white made any sense.

Ironically, the fallback when it doesn't understand a colour is black!

If you definitely want white, you can use `#ffffff`.

**Comment by beebase** [comment]
FWIW Maybe returns are causing trouble...

This shows up ok in the todo tree grouped by tags.
planning.js
![img2801](https://user-images.githubusercontent.com/446089/46021305-b1067d80-c0e0-11e8-8215-e61ac79aee25.jpg)

Putting a return between the two comments causes planning.js to show up in the todo tree grouped by tags.
![img2803](https://user-images.githubusercontent.com/446089/46021329-c1b6f380-c0e0-11e8-841c-e5351520de22.jpg)

**Comment by Gruntfuggly** [comment]
Does it only go wrong when grouping by tag?

**Comment by beebase** [comment]
> The colour problem is because 'white' is not a defined colour for todo-tree. 😁

😝 

> Does it only go wrong when grouping by tag?

the error seems to occur in any combination of tree/flat grouped/ungrouped by tag



I'm running with debugger on, but I don't see any errors occur

```
Search: {"file":"/Users/maarten/projects/skilldance33/projectNotes/planning.js"}
Command: /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg --no-messages --vimgrep -H --column --line-number --color never  -e "((//|#|<!--|;|/\*|^)\s*(@proposal|@task|@bug3|@new|@open|@done|@urgent|@investigate|@backlog3|@next|@obsolete|@0.5.5|@backlog2|@backlog1|@0.5.5)|^\s*- \[ \])" -g "**/client/src/**" -g "**/projectNotes/**" -g "**/server/server.js" -g "**/server/api/**" -g "**/server/common/**" -g "**/website/src/**" -g "!**/website/src/vuex/**" "/Users/maarten/projects/skilldance33/projectNotes/planning.js"
/Users/maarten/projects/skilldance33/projectNotes/planning.js:1:1:// @backlog1
/Users/maarten/projects/skilldance33/projectNotes/planning.js:3:1:// @backlog2

 Match: {"file":"/Users/maarten/projects/skilldance33/projectNotes/planning.js","line":1,"column":1,"match":"// @backlog1"}
 Match: {"file":"/Users/maarten/projects/skilldance33/projectNotes/planning.js","line":3,"column":1,"match":"// @backlog2"}
Found 94 items
```

**Comment by Gruntfuggly** [comment]
Have you truncated that output - It says it found 94 items, but there are only 2?

Assuming you have, I think it's probably to do with the recent change to allow multiple tags on the same line.

Would you be happy to try a tiny hack to see if it fixes it?

**Comment by beebase** [comment]
yeah sure, just let me know.

**Comment by Gruntfuggly** [comment]
If you go open `~/.vscode/extensions/Gruntfuggly.todo-tree-0.0.88/ripgrep.js` and remove the "--vimgrep" from line 90, and restart. 

Let me know if that makes any difference.

**Comment by beebase** [comment]
removing --vimgrep didn't change anything.
AFAICT from the debugger, the tag matching seems to be ok everywhere, but the found results are not displaying correctly in the tree.
Shall I rollback one version just to make sure that it's a bug in v 0.0.88 or are you already convinced it is? (I'm the only one reporting this, so maybe it's something weird in my set up)

debugger:
![img2806](https://user-images.githubusercontent.com/446089/46061921-78aa8200-c168-11e8-84be-c1a08ff216dd.jpg)

code: 
![img2805](https://user-images.githubusercontent.com/446089/46061942-86600780-c168-11e8-8dba-b38790b15342.jpg)

tree grouped by tag:
![img2804](https://user-images.githubusercontent.com/446089/46061993-b27b8880-c168-11e8-9bed-699be112e86b.jpg)

**Comment by Gruntfuggly** [comment]
I've just worked out what it is - I'm an idiot. 

It's trimming labels where there is another label on the same line, but I'm not checking it's in the *same file*!

I'll have a fix ASAP...

**Comment by Gruntfuggly** [comment]
Please try the new version and let me know. Sorry for that - it's probably about time I started some unit testing...

**Comment by beebase** [comment]
yep, that worked. Thanks a lot 👍 
Bug wasn't a big deal. I love the tool.
