### ISSUE TITLE
ignore files

### ISSUE THREAD

**Issue by Protokollmaker** [Gruntfuggly/todo-tree#740]
**Issue**
I wan't to use the word TODO in my md without it showing up in my TODO list or being highlight
**Solution**
make a way to exclude spezific files from one workspace

**Comment by Gruntfuggly** [comment]
Please look at the section of the README.md about excluding files.

https://github.com/Gruntfuggly/todo-tree#excluding-files-and-folders

**Comment by Protokollmaker** [comment]
I am sorry.
