### ISSUE TITLE
Wrong encoding

### ISSUE THREAD

**Issue by Tolik-Trek** [Gruntfuggly/todo-tree#741]
Comments in cp866 encoding are not displayed correctly if file is not open in editor.
Example:
<img width="379" alt="wrong encoding" src="https://user-images.githubusercontent.com/85737314/227791600-067a7721-b64e-40ad-85a7-e61b1f5b632e.png">

UNICODE symbols for CP866 encoding:
[CP866.csv](https://github.com/Gruntfuggly/todo-tree/files/11072352/CP866.csv)
<img width="390" alt="CP866_CSV" src="https://user-images.githubusercontent.com/85737314/227791838-3aac6619-960a-4d04-a8ed-d0abc02aa3ee.png">

Test file:
[Test.txt](https://github.com/Gruntfuggly/todo-tree/files/11072359/Test.txt)
<img width="268" alt="Test_TXT" src="https://user-images.githubusercontent.com/85737314/227791858-498bcc3c-19a9-4955-a4cb-687f516e508f.png">

**Comment by Gruntfuggly** [comment]
Sadly, this is currently not possible. Please see https://github.com/Gruntfuggly/todo-tree/issues/63
