### ISSUE TITLE
The tag after `{` cannot be recognized

### ISSUE THREAD

**Issue by shaonianruntu** [Gruntfuggly/todo-tree#742]
My todo-tree configuration is as follows:
```
"todo-tree.general.tags": [
    "// TODO"
]
"todo-tree.highlights.customHighlight": {
    "// TODO": {
        "type": "text",
        "foreground": "#FF2D00",
        "icon": "pin",
        "gutterIcon": true,
        "iconColour": "#FF2D00",
        "rulerLane": "full"
      },
}
```
But in the following c++ code, the "// TODO" tag at **comment_a** cannot be recognized and highlighted by this plug-in, but **comment_b** can.
```
if (functoin_a()) {    // TODO comment_a
    // TODO commnet_b
}
```
Is there something wrong with my settings?

**Comment by Gruntfuggly** [comment]
You don't need to include "// " in the tags. The regex has a section to detect the "comment" part, e.g "//", "#", etc.

Try setting the tags to "TODO" and also remove the "// " from the customHighlight setting.

**Comment by shaonianruntu** [comment]
Thank you, you are right.
It should be:
```
"todo-tree.general.tags": [
    "TODO"
]
"todo-tree.highlights.customHighlight": {
    "TODO": {
        "type": "text-and-comment",
        "foreground": "#FF2D00",
        "icon": "pin",
        "gutterIcon": true,
        "iconColour": "#FF2D00",
        "rulerLane": "full"
      },
}
```
