### ISSUE TITLE
Accessibility question/ feature request

### ISSUE THREAD

**Issue by paj80paj** [Gruntfuggly/todo-tree#743]
I have accessibility issues which means I would like to be able to control todo tree Entirely with my keyboard Which  means that I can then control it with talon voice.

 In the search bar in VS Code I can use up and down to cycle through different search results.  Unfortunately in to do Tree, it focuses on the code editor each time.  Is there a way to maintain focus within the to do List bar. If I return focus to the bar, it goes to the top of the list -  So I haven't found a workaround which avoids mouse use. 

 In general the tool is brilliant.

**Comment by Gruntfuggly** [comment]
This will be an option in the next version - should be available in the next few days.

**Comment by Gruntfuggly** [comment]
Latest version (0.0.225) now supports a new option "leave focus in tree" for the `todo-tree.general.revealBehaviour` settings. Please give it a try and let me know if it works for you.
