### ISSUE TITLE
the sidebar icon of todo tree disappear

### ISSUE THREAD

**Issue by LeoJiang1997** [Gruntfuggly/todo-tree#746]
<img width="70" alt="image" src="https://user-images.githubusercontent.com/54826369/231033117-d9ba2fa6-045e-446a-adae-30b6fcac07e1.png">

**Comment by Gruntfuggly** [comment]
Have you dragged the view into one of the other panes? Go to **View** -> **Open View...** then select **TODOs** from the list - that should take you to wherever the view currently is. You can then drag it back to the activirty bar.
