### ISSUE TITLE
Not working with worspaces

### ISSUE THREAD

**Issue by mtxr** [Gruntfuggly/todo-tree#75]
Not showing any item in list when opening a vscode workspace file.
It would be nice to mimic explorer view to show items

**Comment by Gruntfuggly** [comment]
It won't show anything until you open a file inside a workspace - it will only show the tree from one workspace at a time, so until you choose a workspace (by selecting a file) it won't know which workspace to show.

If it still doesn't work, can you set `todo-tree.debug` to true and restart. Then there should be a new channel available in the Output view (todo-tree). Can you copy the output contents to here?

**Comment by mtxr** [comment]
Quite strange, but ok.

Is the any plan to update this behavior?

**Comment by Gruntfuggly** [comment]
How would you propose it should work? 

It could show multiple tree roots for each workspace, but then you'd need another root for files outside the workspace.

I wanted to avoid extra nodes in the tree, but I guess if you're using multiple workspaces, you'd have to expect that.

I'll look into it...

**Comment by mtxr** [comment]
I suggest to use the same behavior that File Explorer is using.

Use a workspace representation and the todo's inside of each workspace the sameway we are seeing today.

```
Workspace A
 - Todo 1
 - Todo 2
 - Todo 3
Workspace B
 - Todo 1
 - Todo 2
 - Todo 3
```
