### ISSUE TITLE
Feature request: put the selected line at screen top or in the center of it

### ISSUE THREAD

**Issue by crystalfp** [Gruntfuggly/todo-tree#76]
First, thanks for this extension! It is fantastic to navigate long sources.
I would like to ask a small enhancement. When I select a tag in the explorer pane, the selected line, when not already present on screen, appears as penultimate line of the screen. Is it possible to put it as first line of the screen or at least in the middle of it? The rationale is that I search for a tag that is always before the area of code I'm interested in.
Thanks!
mario

**Comment by Gruntfuggly** [comment]
Yes - that's easy. I don't know why I didn't do it before.

**Comment by Gruntfuggly** [comment]
Try the latest verision :+1:

**Comment by crystalfp** [comment]
Fantastic! Thanks. You can close the issue.
