### ISSUE TITLE
Dark and Light mode support

### ISSUE THREAD

**Issue by k4mp3r** [Gruntfuggly/todo-tree#761]
Please let me know if this is already possible, I didn't see anything about this in the readme or in other issues.

It would be nice if I could configure the highlighting for both dark and light mode as I switch between the two depending on my ambient light. Currently it is hard to find colors that look good in one setting without being overbearing in the other. If anyone is aware of some good hex color values that do look good in both, I'd be open to that as a workaround.

**Comment by Gruntfuggly** [comment]
You can use theme colours in the settings - that should then respect your dark/light mode.

See https://code.visualstudio.com/api/references/theme-color for a list of theme colour names that you can use.

**Comment by RokeJulianLockhart** [comment]
@k4mp3r, it already does so for me. Perhaps try reinstalling to reset to defaults.

**Comment by k4mp3r** [comment]
Sorry for the late reply, didn't see the notification. This worked, thank you!
