### ISSUE TITLE
Sort by Tag

### ISSUE THREAD

**Issue by SchRob** [Gruntfuggly/todo-tree#77]
We use a lot of different tags and it would be helpful, if could sort them in a specific way.

**Comment by Gruntfuggly** [comment]
Do you mean when using the 'group by tag' button? At the moment, they're in order of appearance so it's a bit arbitrary.

I'll sort them alphabetically.

**Comment by SchRob** [comment]
Thanks for your fast answer. You're right, I mean the list shown with active 'group by tag' button.

> I'll sort them alphabetically.

Sounds good to me as a first approach.

**Comment by Gruntfuggly** [comment]
I've just uploaded a new version which should sort alphabetically.

**Comment by crystalfp** [comment]
Is it possible to have again the tags in order of appearance and not alphabetical? I cannot find a switch to toggle the later order. Now the order of main sections (Tag ">") and their subsections (Tag ">>") is totally destroyed. Idem for the correspondence to the source order.
I normally use "Flat view" and not "Group by tag" with the latest version.
Thanks for looking!
mario

**Comment by Gruntfuggly** [comment]
Yes, the tags under a file node should be in appearance order. The alphabetical order should only apply to the top level nodes when using "group by tag".

I'll fix it...
