### ISSUE TITLE
Unable to see ToDo Tree

### ISSUE THREAD

**Issue by DarylGraves** [Gruntfuggly/todo-tree#777]
Sorry if this is a stupid thing but I'm a bit stumped... I just set up a new machine and install Visual Studio Code. I synced my previous extensions about an hour ago but ToDo Tree doesn't seem to be working correctly:

If I enabled the Debug option in ToDo Tree's, I can see this output:

> 11:13:16.875 Automatic Git refresh disabled
> 11:13:16.876 Periodic refresh disabled
> 11:13:16.887 Searching d:\Dev\NewComputerSetup...
> 11:13:16.895 Writing pattern file:c:\Users\dgrav\AppData\Roaming\Code\User\workspaceStorage\dc06843fde0b09285c4d384bb19a1540\Gruntfuggly.todo-tree\5rjf4ucc6.txt
> 11:13:16.896 Pattern:(//|#|<!--|;|/\*|^|^[ \t]*(-|\d+.))\s*(\[x\]|\[ \]|XXX|TODO|HACK|FIXME|BUG)
> 11:13:16.897 Command: "c:\Users\dgrav\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\@vscode\ripgrep\bin\rg.exe" --no-messages --vimgrep -H --column --line-number --color never --max-columns=1000 --no-config  -f "c:\Users\dgrav\AppData\Roaming\Code\User\workspaceStorage\dc06843fde0b09285c4d384bb19a1540\Gruntfuggly.todo-tree\5rjf4ucc6.txt" -g "!**/node_modules/*/**" "d:\Dev\NewComputerSetup"
> 11:13:16.990 Search results:
> d:\Dev\NewComputerSetup\NewComputerSetup.ps1:6:1:# TODO:
> d:\Dev\NewComputerSetup\NewComputerSetup.ps1:8:1:#TODO: Test
> 
> 11:13:16.992  Match (File): {"fsPath":"d:\\Dev\\NewComputerSetup\\NewComputerSetup.ps1","line":6,"column":1,"match":"# TODO:","uri":{"$mid":1,"path":"/d:/Dev/NewComputerSetup/NewComputerSetup.ps1","scheme":"file"}}
> 11:13:16.993  Match (File): {"fsPath":"d:\\Dev\\NewComputerSetup\\NewComputerSetup.ps1","line":8,"column":1,"match":"#TODO: Test","uri":{"$mid":1,"path":"/d:/Dev/NewComputerSetup/NewComputerSetup.ps1","scheme":"file"}}
> 11:13:16.993 Found 4 items
> 11:13:16.993 Applying globs to 4 items...
> 11:13:16.994 Remaining items: 4

So it looks like it's working, however, I don't have the option to right click and enable it on any pane:

![ToDo](https://github.com/Gruntfuggly/todo-tree/assets/46203429/a8d6db5e-4120-4e21-929a-f819593ed438)

Any advise would be great, I can't do without this extension. Thank you!

**Comment by DarylGraves** [comment]
I've found a workaround by going F1->View: Open View -> TODOs (under Problem). This has opened it in the Problems Pane. Still intrigued as to why I don't get the Tree on the side bar anymore!

**Comment by Gruntfuggly** [comment]
Have you managed to get this sorted out? It sounds like view has been dragged out of the activity bar accidentally maybe? You should be able to drag if from the problems panel back in the the activity bar.

**Comment by DarylGraves** [comment]
Hi, thanks for getting back to me! 

Using F1 -> View: Open View -> TODOs I was able to open it under the Problems Pane. I've just tried what you suggested and you're right, now it exists on the Problems Pane I can drag the tab back to the main side pane and drop it there to create the Tree Icon I originally expected.

No idea why it happened, maybe some sort of confusion from my profile syncing where it knows I like it on the Problems Pane but didn't display it there for some reason.

Thank you!

**Comment by vhartikainen** [comment]
I faced the same. VSCode decided apparently at some point, that the TODO Tree should be visible only under "Run and Debug" View.

Trick provided by Daryl helped me too, thanks!
F1 -> View: Open View -> TODOs

**Comment by deepnight** [comment]
Same problem, same solution. I was able to re-open the tree panel using @DarylGraves (thanks!).
At that point, I was able to drag-drop the Tree icon at the top of this panel back to my Activity Bar.

Somehow, everything disappeared like, months ago, during some update. Glad it's now back :)
