### ISSUE TITLE
Exclude Tags from Activity Bar

### ISSUE THREAD

**Issue by tgaldi** [Gruntfuggly/todo-tree#779]
Would like the be able to specify tags to be excluded from display on the activity/status bar, but still colored/shown in the tree view.

**Comment by Gruntfuggly** [comment]
There is a `customHighlight` setting allows `hideFromActivityBar` to be set on a per tag basis.
See https://github.com/Gruntfuggly/todo-tree#highlighting

**Comment by tgaldi** [comment]
Oh, excellent!
