### ISSUE TITLE
highlight line option is not working

### ISSUE THREAD

**Issue by shadiabuhilal** [Gruntfuggly/todo-tree#78]
`"todo-tree.highlight": "line"`  setting is not working.

**Comment by Gruntfuggly** [comment]
Hi - it's working for me. 

What platform are you running on?
Does it work OK for 'tag' and 'text'?

**Comment by shadiabuhilal** [comment]
Mac 10.13.6 
VS Code Version 1.27.2 (1.27.2)
 todo-tree v0.0.92

`tag` is not working, `text` I can't till if its from IDE or todo-tree extension

**Comment by Gruntfuggly** [comment]
What appears in the tree?

Could you post your todo-tree configuration please.

**Comment by shadiabuhilal** [comment]
__settings.json__
```
{
    "todo-tree.highlight": "line"
}
```

<img width="899" alt="screen shot 2018-10-04 at 2 51 26 pm" src="https://user-images.githubusercontent.com/1387462/46505166-12b39f80-c7e5-11e8-9cfa-dedff93329ae.png">

**Comment by Gruntfuggly** [comment]
Can you try this instead:
```
"todo-tree.defaultHighlight": {
        "type": "line"
    },
```

`todo-tree.highlight` is deprecated and will be removed at some point.

**Comment by shadiabuhilal** [comment]
still not working

**Comment by shadiabuhilal** [comment]
It works if I have set `foreground` and `background` values
```
"todo-tree.defaultHighlight": {
        "type": "line",
        "foreground": "black",
        "background": "green"
    }
```

<img width="1131" alt="screen shot 2018-10-04 at 3 45 22 pm" src="https://user-images.githubusercontent.com/1387462/46507268-8b6a2a00-c7ec-11e8-8091-815122a01eaa.png">

**Comment by Gruntfuggly** [comment]
Yes - that makes sense. There's no default colour. It should also work if you just set the background - it will choose a foreground automatically.
