### ISSUE TITLE
Keeps showing up as Problem

### ISSUE THREAD

**Issue by rickf2** [Gruntfuggly/todo-tree#780]
When i add a TODO or FIXME is shows up as a problem.   it should not be a problem

**Comment by Gruntfuggly** [comment]
Problems should be completely independent from this extension. What language are you using? Can you post a screenshot?

**Comment by marshall-buck** [comment]
It's happening with me with dart files.  
![Screenshot 2023-08-05 at 5 42 38 PM](https://github.com/Gruntfuggly/todo-tree/assets/105175337/fe65273a-cd5f-4861-8fc7-a5192d853ee0)

**Comment by marshall-buck** [comment]
Here is a fix that worked. add the following to the analysis_options.yaml file. 

```
analyzer:
  errors:
    todo: ignore
```

**Comment by rickf2** [comment]
sorry, i think it was my error. i have been using it okay. sorry
