### ISSUE TITLE
throws error on empty folder

### ISSUE THREAD

**Issue by jhony1104** [Gruntfuggly/todo-tree#8]
Opening an empty folder leads to the error `todo-tree: failed to execute search (No files were searched, which means ripgrep probably applied a filter you didn't expect. Try running again with --debug.`.

Could you please check if there are any files to search before assuming there is a problem.

**Comment by Gruntfuggly** [comment]
Hi - can you try the latest version. I've inhibited ripgrep's errors, as I doubt they are useful in the context of the extension.

**Comment by jhony1104** [comment]
The error does no longer appear. Thanks for the fast response.
