### ISSUE TITLE
Support Tags with a Colon Right After It

### ISSUE THREAD

**Issue by Griiid** [Gruntfuggly/todo-tree#80]
I usually write TOD like this (take Python for example):

`# TODO: Implement this function`

I put a colon after tag because it looks more clearly when using no-color-IDE.

However, in todo-tree, this item will be shown as:
`: Implement this function`

I'm trying to update the regex rule, but still not work, can you please add this feature, thx:
> Consider a tag "XXX" in the tag list, either "XXX" or "XXX:" are the same tag.

**Comment by Gruntfuggly** [comment]
I would expect it to show:

`TODO: Implement this function`

in the tree view?

What is your regex set to?

**Comment by Griiid** [comment]
My regex: `((//|#|<!--|;|/\*|^)\s*($TAGS)[:]{0,1}|^\s*- \[ \])`

And my todo tree looks like this, you can see each item has a colon before them:

<img width="277" alt="2018-10-10 11 36 54" src="https://user-images.githubusercontent.com/17796098/46711862-d074dd00-cc80-11e8-9692-b1a234fbf1bf.png">

Is this the same in Windows?  
I'm using macboook, maybe there's something different in different OS?

**Comment by Gruntfuggly** [comment]
Ah OK - it's because you're using group by tag. I would have thought you could add the colon to each tag but that seems to break it. I'll look into it...

**Comment by Gruntfuggly** [comment]
If I change the tags to
```
    "todo-tree.tags": [
        "TODO:",
        "FIXME:",
        "GROUP:"
    ],
```
It removes the colon from each entry in the tree, when grouping by tag.

Does it work for you?

**Comment by Griiid** [comment]
Yes, it works.

But I thought you can make this extension to support this feature so that if users open a project written by other developer who uses different type of tags, it still looks the same :)

Just a suggestion.

**Comment by Gruntfuggly** [comment]
Where possible, I'm trying to avoid making changes to the extension code where it can be catered for by the regex - it would be impossible to make it work for everybody "out of the box", so I expect everybody will need to tweak the regex and tags a bit.

If more people ask for the feature, or I find an easy way to implement it, I'll consider adding it.

Thanks for the suggestion though.

**Comment by xaviergonz** [comment]
I also found that in TypeScript, while
```// TODO something```
will properly show the little blue line near the minimap
```// TODO: something```
will not (even if I set the tags section on settings to "TODO:")

**Comment by Gruntfuggly** [comment]
Does the highlight work in the file?

**Comment by xaviergonz** [comment]
Nope, with either case the comments stay green

**Comment by Gruntfuggly** [comment]
Please can you attach your todo-tree settings so I can try it out.

**Comment by logdatatech** [comment]
Doesn't work either for Me.  I also use @FIRSTLAST Initial in my code not sure if that can be co-erced in.

    "todo-tree.tags": [
        "TODO:",
        "FIXME:",
        "NOTE:",
        "ORIGIN:",
        "@NK",
    ],

**Comment by logdatatech** [comment]
Jumped the Gun it Does Work for example in a MarkDown.md File just fine.

It is failing for me in a .bas File for VBA so comment begins with ' character wgucg seens to be my problem.

Congrats quite a cool extension.

**Comment by Gruntfuggly** [comment]
Have you got it working or is something not right? It's quite hard to understand from your post - sorry!

**Comment by logdatatech** [comment]
> Have you got it working or is something not right? It's quite hard to understand from your post - sorry!

Yes it works great in files like *.TXT, *.MD etc.. something is stopping it from working with .bas files in Comments only.  SO in the Following Example the First Two Entries DO NOT show in TODO Tree and the Second Two DO show but would break compiler normal way for comments is

BEGINNING OF LINE so ^ then a Single Apostrophe ' then a space.

Seems like it's just a RegEx tweak rather than code fix needed.

```vb
Option Explicit

' TODO:
' FIXME:

TODO:
FIXME:
```

**Comment by Gruntfuggly** [comment]
I got it to work by including the apostrophe in the regex:
```
((//|#|<!--|;|/\*|^|')\s*($TAGS)|^\s*- \[ \])
```
