### ISSUE TITLE
SQL language support

### ISSUE THREAD

**Issue by cryocaustik** [Gruntfuggly/todo-tree#81]
I was unable to find a list of supported languages, but in my testing, the plugin does not seem to work with `*.sql` files.

Would be nice to get some clarification on languages supported as well. 😃

**Comment by Gruntfuggly** [comment]
Hi - what format to TODO's take in SQL? There's no real language support - it's just a regular expression. 

If you're using single line comments you could try adding **--** to the regex. E.g.

`todo-tree.regex: "((//|#|--|<!--|;|/\*|^)\s*($TAGS)|^\s*- \[ \])"

If you're using multiline comments it should work out of the box, i.e. it should match

/* TODO something */

**Comment by cryocaustik** [comment]
not sure how I missed the regex part, makes much more sense now. 

I was using a style of `-- TODO`, which was not being picked up; I added a custom tag of `-- TODO` and it is working now. 

Thanks

**Comment by mosteo** [comment]
Adding the `--` starting pattern also makes it work for Ada. As of today it isn't in the default regex.

**Comment by gskoff** [comment]
Adding the ```--``` into the regex would make it work out of the box for .sql files. I added in my settings, and it works like a charm. Cool extension!
