### ISSUE TITLE
readme config example syntax error

### ISSUE THREAD

**Issue by jpmcb** [Gruntfuggly/todo-tree#82]
In the `README.md`, the example JSON has a syntax errors with a misplaced quotation mark in the customHighlight object and should appear as:
```
"defaultHighlight": {
    "icon": "alert",
    "type": "text",
    "foreground": "red",
    "background": "white",
    "iconColour": "blue"
},
"customHighlight": {
    "TODO": {
        "icon": "check",
        "type": "line"
    },
    "FIXME": {
        "foreground": "black",
        "iconColour": "yellow"
    }
}
```

Further, as a new VS code user, after installing, I found the above example alittle confusing because it was missing the todo-tree object. Would it be beneficial for the example to be more verbose and appear like this?
```
"todo-tree.defaultHighlight": {
    "icon": "alert",
    "type": "text",
    "foreground": "red",
    "background": "white",
    "iconColour": "blue"
},
"todo-tree.customHighlight": {
    "TODO": {
        "icon": "check",
        "type": "line"
    },
    "FIXME": {
        "foreground": "black",
        "iconColour": "yellow"
    }
}
```

**Comment by Gruntfuggly** [comment]
Yes, you're right. I'll fix it for the next release. Thanks.

**Comment by jpmcb** [comment]
Great! Thanks for the amazing work on this!
