### ISSUE TITLE
Tree view red filenames

### ISSUE THREAD

**Issue by shacker** [Gruntfuggly/todo-tree#84]
I've read the documentation and experimented, but can't seem to figure this out: In the tree view, some of my filenames are rendered in red text, some in yellow, while most of them are in white. The color is not affected by changing them from FIXME to TODO or vice versa, and the color is not affected by changing their level (FIXME(1), FIXME(2), TODO(3), etc.) 

If I go to an uncolored file and make some change to it and save, it goes from uncolored to red. Why?

I am using the default settings.

What does it mean when filenames appear red or yellow in the todo tree view? Maybe this needs a mention in the documentation?

**Comment by Gruntfuggly** [comment]
If they also have a letter on the right, then It's because the tree view is showing the SCM status. I'll be uploading a new version shortly which allows you to switch it on or off.

**Comment by shacker** [comment]
Ah! So it has nothing to do with the todo/fixme status - purely scm status. Got it, that makes sense. Yeah, I fully expect that in the vscode file tree view, but not at all in the fixit file tree. Thanks for the explanation.

**Comment by Gruntfuggly** [comment]
Annoyingly, it seems that the only way to turn it off means that you lose themed icons too.  :disappointed: 

You can also turn it off for everything - from the July release note:

"Custom views showing file resources will now have file decorations (Git, problems) shown. You can disable them using the settings `explorer.decorations.colors` and `explorer.decorations.badges` which disables them in File Explorer, Open Editors and Custom views."
