### ISSUE TITLE
Can we configure settings in a file under the project?

### ISSUE THREAD

**Issue by jpa95** [Gruntfuggly/todo-tree#843]
Apologies if this has been asked or if it is already possible; i could not find it.

Basically I am hoping that TODO Tree could look for a config file in the current project folder, as do many other extensions such as editor.config and prettier.

Having the configuration in the VS Code settings (regardless of project/user/workspace level)  make it impossible to share TODO-Tree config between developers on the same project easilly. In our environment, Ideally a developer would pull the configuration for all extensions as part of the code on git,.

Regards,
Joel

**Comment by lasseba** [comment]
Just want to second that idea... 
If we use TODO tree actively in the project, it is quite vital all have the same settings.

**Comment by DaveParr** [comment]
We've solved this by configuring the settings at the _workspace_ level in the `.vscode/settings.json` (both by editing the file and using the GUI). That file is then commited to git, and when the project is cloned the file comes down with it. Might that work for you @jpa95?

**Comment by jpa95** [comment]
Since i asked this question we have started working with Workspaces (abc.code-workspace) and have put the todo tree config in there. So yeah, using workspaces was the way to go for us. For other extensions there are still some settings that need to be inidivual to the developer (user settings), but most of our settings are now shared by the *.code-workspace files that we commit into git. Thanks for the reply @DaveParr!

**Comment by DaveParr** [comment]
No problem @jpa95 , glad it's all working :)
