### ISSUE TITLE
Sanitize custom tags from regex special characters

### ISSUE THREAD

**Issue by Jacajack** [Gruntfuggly/todo-tree#85]
Hi, and thanks for a great extension.

I use Doxygen to document my C++ code and I stumbled upon a problem (somewhat related to #73). 
As I use `\todo` as my TODO tag, I couldn't add `"\todo"` nor `"\\todo"` to my `todo-tree.tags` list, because it would result in regex compilation error. The only working workaround I found is to use `\\x5Ctodo` (`0x5C` stands for backslash in ASCII).

I'd suggest to sanitize the regex input or at least add some information in the readme, saying how to escape special chars by yourself.

Thanks in advance

**Comment by Jacajack** [comment]
That was quick. Thanks a lot!

**Comment by Gruntfuggly** [comment]
Hmm - just in case you were wondering, I don't think the change made it into version 0.94! The latest definitely has it though...
