### ISSUE TITLE
tagGroups not working as expected

### ISSUE THREAD

**Issue by gc-av** [Gruntfuggly/todo-tree#851]
Hey! I believe I've found an issue with the tagGroups settings. 

(And I really hope it's not me making some silly mistake when trying to set it up)

## Summary

When I turn some of my tags into tagGroups, they no longer work.

It seems like the problem is twofold:
1. When using the tagGroup's name (`FIXME`), it will be captured but the customHighlight is dismissed. Default highlight settings are used;
2. The other tags within the group (`FIX`, `FIXIT`) are not captured, and are treated as normal text.

## Additional Info

> **MacOS**
> Version 14.5 (23F79)
> 
> **Visual Studio Code**
> Version: 1.90.0 (Universal)
> Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
> Date: 2024-06-04T19:34:44.157Z
> Electron: 29.4.0
> ElectronBuildId: 9593362
> Chromium: 122.0.6261.156
> Node.js: 20.9.0
> V8: 12.2.281.27-electron.0
> OS: Darwin arm64 23.5.0
> 
> **Todo Tree**
> Version: `v0.0.226` (latest) 
> Installed via Marketplace

I have tried restarting VSCode to reload all plugins, but still no change.

I have also checked that my brackets are correctly set up, and couldn't find any issues.

### Short demo

![todoTreeBug](https://github.com/Gruntfuggly/todo-tree/assets/56302061/b920e642-8262-4409-af25-6c28609317af)

### My `settings.json`

**Working config (abridged)**
```
  "todo-tree.general.tags": [
    "BUG",
    "FIXME",
    [...]
  ]
  "todo-tree.highlights.customHighlight": {
    "BUG": {
      "icon": "bug",
      "iconColour": "#c64ff9",
      "background": "#c64ff9",
      "foreground": "#e09ffc"
    },
    "FIXME": {
      "icon": "tools",
      "iconColour": "#f91e0e",
      "background": "#f91e0e",
      "foreground": "#f998ad"
    },
    [...]
  }
```

**Failing config (abridged)**
```
  "todo-tree.general.tags": [
    "BUG",
    [...]
  ],
  "todo-tree.general.tagGroups": {
    "FIXME": [
      "FIXME",
      "FIXIT",
      "FIX",
    ],
    [...]
  },
  "todo-tree.highlights.customHighlight": {
    "BUG": {
      "icon": "bug",
      "iconColour": "#c64ff9",
      "background": "#c64ff9",
      "foreground": "#e09ffc"
    },
    "FIXME": {
      "icon": "tools",
      "iconColour": "#f91e0e",
      "background": "#f91e0e",
      "foreground": "#f998ad"
    },
    [...]
  }
```

And, from what I understand, customHighlight should apply to tags and tagGroups equally, correct?

Thanks in advance!

**Comment by Ansa211** [comment]
Doesn't the documentation say to include all tags within a group in `"todo-tree.general.tags"` as well? I think the grouping is just for the tree-view.

**Comment by gc-av** [comment]
> Doesn't the documentation say to include all tags within a group in `"todo-tree.general.tags"` as well? I think the grouping is just for the tree-view.

Yes, you're right! I'm so sorry I missed that piece of the documentation.

For those with the same problem as me, here is the solution:

```json
"todo-tree.general.tags": [
    // List all desired tags
    "FIXME",
    "FIX",
    "FIXIT",
    [...]
  ],
  "todo-tree.general.tagGroups": {
    // Add tags to group
    "FIXME": [
      "FIXME",
      "FIXIT",
      "FIX",
    ],
    [...]
  },
  "todo-tree.highlights.customHighlight": {
    // Use the tagGroup name to customise all tags in tagGroup
    "FIXME": {
      "icon": "tools",
      "iconColour": "#ef9b4c",
      "background": "#ef9b4c",
      "foreground": "#ef9b4c"
    },
    [...]
  },
```
