### ISSUE TITLE
Aggregation in Side Bar no longer working in 0.0.93+

### ISSUE THREAD

**Issue by fheinicke** [Gruntfuggly/todo-tree#86]
With the latest versions (0.0.93 and 0.0.94), the results in the **side bar** are no longer showing up ("Nothing found"). **Version 0.0.92 works flawlessly.**

Highlighting of tags in editor is working correctly.

When opening a file with TODOs, no results are shown in side bar as well. After modifying the file in editor and saving, the TODOs for that single file are shown in the side bar. When using the refresh button in side bar, the results for that file are gone.

I don't use VS Code workspaces, but a simple folder. Tried creating a workspace file, but that had no effect.

Explicitly setting the root folder to the source code folder "./src" didn't have an effect.

My settings:
````json
"todo-tree.defaultHighlight": {
    "foreground": "green",
    "type": "tag"
},
"todo-tree.customHighlight": {
    "TODO": {
        "icon": "pin",
        "foreground": "#67c651"
    },
    "FIXME": {
        "icon": "tools",
        "foreground": "#c65151"
    },
    "HACK": {
        "icon": "issue-opened",
        "foreground": "#e2e056"
    }
},
"todo-tree.tags": [
    "TODO",
    "FIXME",
    "HACK"
],
"todo-tree.regexCaseSensitive": false,
"todo-tree.showInExplorer": false,
"todo-tree.expanded": true,
````

I'm currently on VS Code 1.28.2 (user setup).

I downgraded to 0.0.92 and results are again showing up.

PS: Thanks for that extension @Gruntfuggly - really liking it.

**Comment by Gruntfuggly** [comment]
It sounds like the search is failing. Can you try setting `todo-tree.debug: true` and then having a look what shows up in the `todo-tree` output channel?

I don't use workspaces either, but it should still work normally with an 'implicit' workspace. Unfortunately it still shows the workspace folder name - I tried to hide it, but the tree view would break when you added a workspace folder. It's on my list to try and sort out...

**Comment by Gruntfuggly** [comment]
The reason it works for a single file when you save it is that it now just searches the document without using ripgrep (which seemed a bit pointless).

Is the leading '/' coming from your configuration, or from is it being inserted automatically when `todo-tree.rootFolder` is undefined?

**Comment by fheinicke** [comment]
The leading '/' is only present when ``todo-tree.rootFolder`` is undefined. When setting ``todo-tree.rootFolder`` to an absolute path (e.g. ``c:/Workspace/PROJECTFOLDER``) or to ``${workspaceFolder}``, the resulting path is correct and the ripgrep search works correctly.
So i guess it has to do with the logic of building the workspace path, probably the difference between Linux/OSX paths starting with '/' and Windows paths starting with drive letter.

**Comment by Gruntfuggly** [comment]
Found it - was using the wrong attribute for the workspace paths. Only affected Windows unfortunately. The latest version should now work as expected.

**Comment by fheinicke** [comment]
Hey @Gruntfuggly can confirm that it works again with undefined ``rootFolder``, thanks a lot!
