### ISSUE TITLE
Nothing Found

### ISSUE THREAD

**Issue by mightytyphoon** [Gruntfuggly/todo-tree#88]
Hi,

I find the idea of this extension very useful but I have an issue.

I have some problem to keep todos listed. If I save a ts file (for example) with todos inside it appears in tree view without any problem but when I refresh or quit workspace there is no more todos in todo list, it's empty with the message Nothing Found. If I go back in the files and I save them again, todos are listed but if I quit again it will loose my todos.

Any idea or quick fix ?

Regards.

**Comment by Gruntfuggly** [comment]
Can you tell me what platform you are running on and if you have changed any configuration settings?

If not, please set `todo-tree.debug` to `true` and restart. You should then find a new output channel called 'todo-tree' in the output window. Can you copy the contents here so I can have a look?

It sounds like your file search is failing for some reason.

**Comment by mightytyphoon** [comment]
# FIXED
**if you don't want to read it all, just go down to last line**

Wow ok, finally made it to work. Here the explanation :

I tried to simply run the command with rg, this is the command from the output of todo-tree :

`rg  --vimgrep -H --column --line-number --color never  -e "((//|#|<!--|;|/\*|^)\s*(TODO|FIXME)|^\s*- \[ \])" "d:\Work\hellonews\scrum\sprint1\"` 

which does not work, 

output :
```
d:\Work\hellonews\scrum\sprint1": IO error for operation on d:\Work\hellonews\scrum\sprint1": La syntaxe du nom de fichier, de répertoire ou de volume est incorrecte. (os error 123)
No files were searched, which means ripgrep probably applied a filter you didn't expect. Try running again with --debug.
```
and this command works : 

```
rg  --vimgrep -H --column --line-number --color never  -e "((//|#|<!--|;|/\*|^)\s*(TODO|FIXME)|^\s*- \[ \])" "d:\Work\hellonews\scrum\sprint1"
```
output :  (my todos)

```
d:\Work\hellonews\scrum\sprint1\DIARY.md:11:1:TODO : websocket côté serveur
d:\Work\hellonews\scrum\sprint1\server\src\controllers\email.controller.ts:5:41:const sendmail = require('sendmail')(); // TODO change send mail for nodemailer !
d:\Work\hellonews\scrum\sprint1\server\src\controllers\email.controller.ts:40:18:    sendEmail(){ // TODO : review function
d:\Work\hellonews\scrum\sprint1\server\src\controllers\websocket.controller.ts:1:1:// TODO open connections with users through ssl/tls
d:\Work\hellonews\scrum\sprint1\server\src\controllers\websocket.controller.ts:2:1:// TODO open auth connections to make authenticated requests
d:\Work\hellonews\scrum\sprint1\server\src\controllers\websocket.controller.ts:14:56:        this.wss = new WebSocket.Server({port : 5000}) // TODO create tls websocket server
d:\Work\hellonews\scrum\sprint1\server\src\controllers\websocket.controller.ts:20:9:        // TODO open websocket...
d:\Work\hellonews\scrum\sprint1\webapp\src\app\components\head-bar.ts:40:41:    console.log('TODO CHANGE LANGUES'); // TODO change languages
d:\Work\hellonews\scrum\sprint1\webapp\src\app\services\compte.ts:4:1:// TODO all compte service methods
d:\Work\hellonews\scrum\sprint1\webapp\src\app\services\compte.ts:12:22:  public create() {} // TODO simply post user to api/compte or by websocket : create-account with params
d:\Work\hellonews\scrum\sprint1\webapp\src\app\services\compte.ts:13:23:  public connect() {} // TODO get token & store it
d:\Work\hellonews\scrum\sprint1\webapp\src\app\services\compte.ts:15:36:  public authenticatedRequest() {} // TODO request with token
d:\Work\hellonews\scrum\sprint1\webapp\src\app\services\storage.ts:3:1:// TODO storage service to store token, cookies, localstorage and any informations client side, crypted or not
d:\Work\hellonews\scrum\sprint1\webapp\src\app\services\storage.ts:5:1:// TODO storage service to get tokens, cookies, localstorage etc...
```

**So what changed ?** Just the last antislash... yes. Also when I used a todo-tree.rootFolder, I put the top folder of the project with '../' but I guess it was seen as an absolute path so it made a search through all files of the pc, that's why the anti malware came in, and rg kept being in tasks.

Here is my full config file for VSCode : 

```json
{
	"folders": [
		{
			"path": "../"
		}
	],
	"settings": {
		"winopacity.opacity" : 235,
		"todo-tree.rootFolder" : "${workspaceFolder}\\",
		"todo-tree.defaultHighlight": {
			"icon": "info",
			"type": "tag",
			"foreground": "black",
			"background": "yellow",
			"iconColour": "green"
		},
		"todo-tree.debug" : true,
		"todo-tree.customHighlight": {
			"TODO": {
				"icon": "check",
				"type": "tag"
			},
			"FIXME": {
				"foreground": "black",
				"iconColour": "yellow"
			}
		}
	}
}
```

# So the fix is actually to escape the last antislash : 

```
"todo-tree.rootFolder" : "${workspaceFolder}\\",
```
Regards

**Comment by Gruntfuggly** [comment]
Thanks for the update.

It should default to the workspace folder if you don't set `todo-tree.rootFolder` to anything. Are you saying that it put the `\` on by default?

**Comment by mightytyphoon** [comment]
Yes, I just tried again to be sure, if I don't escape the last antislash it doesn't work. 

If I don't set the `todo-tree.rootFolder` the command used is : 
`rg [...] "d:\Work\hellonews\scrum\sprint1\"` (which return the IO error)
now with : `"todo-tree.rootFolder" : "${workspaceFolder}\\"` it works
`rg [...] "d:\Work\hellonews\scrum\sprint1"`

The only difference is the antislash at the end.

(I'm on windows 10)

Nice extension though, it's incredibly useful.

Regards.

**Comment by Gruntfuggly** [comment]
Odd - my windows 7 machine doesn't include a trailing slash from the workspace folder. I'll try manually adding it and stripping it off to see if I can recreate it, as I don't have access to a windows 10 machine.

At least you have a workaround. :smiley:

**Comment by Gruntfuggly** [comment]
I managed to reproduce it - ripgrep doesn't seem to like it the path is quoted and has a trailing slash.

I've just uploaded a version which removes the trailing slash. Can you let me know if it works for you (when you don't explicitly set `todo-tree.rootFolder`) ?

**Comment by mightytyphoon** [comment]
Re,

Yes your fix works, thanks a lot ! Do you have a donation link/website ? Just asking :3

Regards.
