### ISSUE TITLE
'Nothing Found' in sidebar, while Tasks are highlighted in file #bug

### ISSUE THREAD

**Issue by adityabhaskar** [Gruntfuggly/todo-tree#89]
Hi

I've had a weird problem since yesterday where tasks aren't appearing in the sidebar. They are still being highlighted in the files.

When I add a task, the tasks from that file appear in the sidebar, but not the tasks from other files in the workspace. Clicking `Refresh` removes the newly appeared tasks as well, taking back to ‘Nothing Found’.

I've attached my `todo-tree` settings, and some screenshots below - sidebar, file view, and debug output.

Cheers!

Adi

```    
    "todo-tree.customHighlight": {
        "TODO": {
            "foreground": "#ff5722",
            "background": "#ffffff88",
            "type": "text"
        },
        "FIXME": {
            "foreground": "#42a5f5",
            "background": "#ffffff88",
            "type": "text"
        },
        "MAYBE": {
            "foreground": "#FFB74D",
            "background": "#ffffff88",
            "type": "text"
        }
    },
    "todo-tree.flat": true,
    "todo-tree.defaultHighlight": {
        "foreground": "green",
        "type": "none"
    },
    "todo-tree.tags": [
        "TODO",
        "FIXME",
        "MAYBE"
    ],
    "todo-tree.autoRefresh": true.
     "todo-tree.globs": [
          "!dist",
          "!build",
          "!node_modules",
          "!Others/src"
      ],
      "todo-tree.debug": true
```

System Config: MacOS Mojave
VS Code version: 1.28.2

<img width="916" alt="screenshot 2018-10-30 at 10 37 55" src="https://user-images.githubusercontent.com/2292388/47712843-bcdde600-dc30-11e8-9bc1-c336c6664da5.png">
<img width="328" alt="screenshot 2018-10-30 at 10 38 06" src="https://user-images.githubusercontent.com/2292388/47712844-bcdde600-dc30-11e8-82a8-9035800380e7.png">
<img width="1485" alt="screenshot 2018-10-30 at 10 38 22" src="https://user-images.githubusercontent.com/2292388/47712845-bcdde600-dc30-11e8-9a80-068ed8f6e9f3.png">

**Comment by Gruntfuggly** [comment]
It looks like the ripgrep search is failing. Please can you set `todo-tree.debug` to `true` and restart. There should then be a new output channel called "todo-tree". Can you have a look at what is in the log?

**Comment by adityabhaskar** [comment]
Hi @Gruntfuggly 

The third screenshot in my original post has the output channel log. Just says "Found 0 items".

Cheers!

Adi

**Comment by Gruntfuggly** [comment]
Sorry - :man_facepalming: - I didn't look properly.

So it's definitely the ripgrep search failing, but I'm not sure why. Would you mind trying a couple of things?

1. Try without the globs defined.
2. Try copying and pasting the command into a Terminal window.

I have a mac at home, so I'll try reproducing it later too.

**Comment by adityabhaskar** [comment]
It's working again, but I'm not sure why. Or why it stopped.

The only change I made is that I installed ripgrep on my machine - to test out the commands. 

As for the command, bash was giving an error due to the `!-` in the regex. Removing that xml comment code from the regex made the direct command work on command line.

However, I haven't changed the regex in VS Code, and the sidebar is functioning again. Not sure why.

I'd already tried your suggestions above: Didn't work without the globs. Didn't even work with just `-e` and no other options. Only thing that made it work on the command line was removing the `<!--` bit from the regex.

**Comment by Gruntfuggly** [comment]
I released a new version of the extension (0.97) before I replied to earlier - but I don't think that would have made any difference as it should just trim trailing slashes on Windows.

Other people have said that the `<!--` caused them problems.

Could you trying replacing the`!` with `\x21` and see if that makes it work? I've got a feeling that the ! causes some command line substituion or something in bash.

**Comment by adityabhaskar** [comment]
Replacing `!` with `\x21` lets the regex work on command line, but no longer greps the TODO comments in HTML files. The original regex is still finding them in VSC.

**Comment by Gruntfuggly** [comment]
OK- thanks for trying it.

So as it stands, it's working OK (without using `\x21`) - we're just not sure why it stopped?

I'll leave the issue open in case it stops working again.
