### ISSUE TITLE
Feature Request: Populate Tree View in Order of appearance

### ISSUE THREAD

**Issue by patmar74** [Gruntfuggly/todo-tree#9]
As a user I would like to see all of my todo's for a file in the tree view in the order that they appear in the file, to make navigating sequential todo's significantly easier without being jumped to a potentially unrelated segment of the file.

For background I'm using the ToDo feature to navigate everything that needs to be done in a plain text file where one ToDo depends on the previous one.

**Comment by Gruntfuggly** [comment]
What order do they appear in? It always seems to do them in order for me. Is it possible to send me a copy of the file your're using, or part of it?

**Comment by patmar74** [comment]
I've attached a copy of the file I was using and a screenshot of the tree-view. The first tree-view entry corresponds with Line 3164, the second, Line 1202, the third, Line 3165, the fourth, Line 1239.

I've read that ripgrep uses parallel processing to search faster but as a result the output is not in any particular order. The -j1 option that's mentioned by BurntSushi [here](https://github.com/BurntSushi/ripgrep/issues/152) might help.
![treeview](https://user-images.githubusercontent.com/6706402/37437949-2bba2770-27c6-11e8-94df-3554c3e016b6.PNG)
[KH1_FinalMix_Guide.txt](https://github.com/Gruntfuggly/todo-tree/files/1813589/KH1_FinalMix_Guide.txt)

**Comment by Gruntfuggly** [comment]
Thanks for the file - that made it obvious what the problem was. The extension gets all the results and then sorts them before adding them to the tree - and there was a bug in the sort function. 8-)
I've uploaded a fixed version.

**Comment by patmar74** [comment]
Perfect! I just opened VS Code and got the update. It works perfectly now! Thanks for your help!
