### ISSUE TITLE
Nothing found with root folder override

### ISSUE THREAD

**Issue by CelticMinstrel** [Gruntfuggly/todo-tree#91]
At some point it seems like the root folder override setting stopped working. I set `"todo-tree.rootFolder": "${workspaceFolder}/Source"` in the workspace settings for my Unreal project, and the list says nothing is found. It works if I remove the setting.

Setting `"todo-tree.debug": true` and looking at the output suggests that the problem is with `${workspaceFolder}` &ndash; the log says `Searching undefined/Source...`.

**Comment by Gruntfuggly** [comment]
Hi - I've just uploaded a new version which should handle the case when there is no workspace folder. Can you see if it makes any difference? If not, I'll need to know a few more details about your set up. Thanks.

**Comment by CelticMinstrel** [comment]
Now it just seems to ignore the `rootFolder` setting &ndash; I get the same result with or without it.

This is a workspace file generated by UE, so it has two root folders &ndash; my project folder, which contains the workspace file, and the UE source folder. Since Epic also uses `TODO` comments in their source, I want to omit the latter folder from the scan, and since all the source is in the `Source` subfolder of my project folder, I set `rootFolder` as I mentioned in the initial description. This worked awhile ago when I first installed the plugin (perhaps a month or two ago).

**Comment by Gruntfuggly** [comment]
Ah - OK. I made changes to support multiple workspaces properly. It doesn't cater for your use case anymore. I assumed anybody using workspace folders wouldn't need to use the rootFolder setting.

The problem will be that ${workspaceFolder} could potentially resolve to any of the workspace folders.

Can you try setting it explicitly to your project folder and seeing if that works as a short term fix? 

I'll have a think about another way to do it.

**Comment by CelticMinstrel** [comment]
For what it's worth, I also tried using globs to exclude the UE source folder, but that didn't work either. I guess because it's a root folder or something.

**Comment by Gruntfuggly** [comment]
I think setting the absolute path is probably the simplest way to do this. You can also use environment variables as well as ${workspaceFolder} if you wanted a bit more control over it.

The only other way I can think of would be a configuration setting allowing the names of enabled workspaces to be enabled. Would that be worth doing?

The globs should also work - using `"todo-tree.globs": ["!**/source_folder/**/*"]` excludes the folder from the tree for me.

**Comment by CelticMinstrel** [comment]
That's the opposite of what I want &ndash; I want to include _only_ the source folder. It doesn't look like that sort of glob works minus the `!`, and even if it did, I figure it'd also match other `Source` folders within the second workspace root, which I don't want.

A setting for either disabled root folders or enabled root folders for a workspace would be nice. Alternatively, maybe some kind of variable thing like `${workspaceFolder.FolderName}` that is substituted with the path to the root named `FolderName`.

**Comment by CelticMinstrel** [comment]
I did try that, using the workspace folder's name. Maybe I was doing it wrong, but it didn't work.

**Comment by Gruntfuggly** [comment]
I've just uploaded a new version which has configuration for

`todo-tree.includedWorkspaces: []`
`todo-tree.excludedWorkspaces: []`

They should match the workspace names - you can use wildcards too.

An empty array for includedWorkspaces, includes all workspaces.

E.g. `todo-tree.includedWorkspaces: ["*tree"]` will match todo-tree, etc.

If you are going to use these, then you should remove the rootFolder setting.

**Comment by CelticMinstrel** [comment]
So these won't work together with the rootFolder setting? I guess I can try using globs to exclude the plugins folder then...

**Comment by Gruntfuggly** [comment]
If you use these, you shouldn't need to use the rootFolder setting?

Unless I've missed something and your workspace is completely different to the root folder?

I've got another change I still need to make which will apply these new includes and excludes to the rootFolder too, so if you set rootFolder to include ${workspaceFolder} it will expand the rootFolder for any workspace folders that are present and then apply the include and exclude matches.

If that doesn't give you enough configuration then I'm afraid I've failed to understand the problem :cry:

**Comment by CelticMinstrel** [comment]
I have two workspace root folders, eg `MyProject` and `UE_4.19`. In `MyProject` I only want to include the `Source` folder; there is also a `Plugins` folder in `MyProject` containing additional source files that should be excluded. I want to exclude `UE_4.19` entirely.

With the latest version, `"todo-tree.excludedWorkspaces": ["UE_4.19"]` works really well! However, I'm still seeing a few TODO entries from the Plugins folder which I'd prefer to exclude (though it's not many, so I can probably live with it). I tried `"todo-tree.globs": ["Source/**"]` but it didn't work (am I using globs wrong?).

The `Plugins` folder case isn't technically related to this issue, so as far as I'm concerned this issue can be considered fixed.

**Comment by CelticMinstrel** [comment]
Just had a thought – with multi-root workspaces, wouldn't it make sense for `${workspaceFolder}` to refer to the path where the workspace file is?

Anyway, as far as I'm concerned this issue is fixed.
