### ISSUE TITLE
Daily updates (too frequent?)

### ISSUE THREAD

**Issue by egabrum** [Gruntfuggly/todo-tree#92]
I know that it's impossible to keep everybody happy. I think it's great that this project is alive and so active. But the pace of almost daily updates is annoying me a bit to the point that I keep disabling the extension and re-enabling it after a few days.

I like to keep my extensions up to date, so I can't just ignore the update notification without checking first which one is updated.

I'd suggest bundling updates a bit more or opening a 'dev' version.
Just my 2 cents. I'll understand if the majority prefers updates as frequent as possible.

**Comment by Gruntfuggly** [comment]
Hi - there have been quite a few updates recently, so I understand that it could be irritating. I have automatic updates enabled so to be honest I don't tend to notice when extensions are updated. Unfortunately there's no easy way to have a 'dev' version with vscode (as far I know), apart from installing the extension manually - which would sort of be the opposite of what you're after.

There's one more change in the pipeline and then it should be quiet - there are no plans to add any new features, so any updates would only be bug fixes.

**Comment by egabrum** [comment]
Automatic updates might work for me. I wasn't aware that's an option. Thanks.

**Comment by Gruntfuggly** [comment]
In the extensions view, it's under the three dot menu at top right. It would be event better if you could set it per extension. I must admit, I quite like to see what has changed with some extensions - you could miss useful features unless the extension has a splash page or popup, which can get irritating in itself.

I had a look in the vscode issues and it looks like quite a few people would like to be able to offer 'beta' versions of their extensions, but it looks like it needs support fromt the marketplace. If it becomes available, I'll try to make use of it. :smile:

**Comment by Gruntfuggly** [comment]
Hope you don't mind, but I'm going to close this. Updates are definitely less frequent at the moment. :grin:
