### ISSUE TITLE
ionic3 use todo

### ISSUE THREAD

**Issue by YLQZ** [Gruntfuggly/todo-tree#93]
Using todotree in ionic 3 can't match todo in SRC folder. It can match to WWW and plugins, platforms, www.

How to use todotree in ionic3

**Comment by Gruntfuggly** [comment]
It sounds like you need to modify the regular expression which matches the tags.

Can you give me an example to the TODO that you would expect to see in the three?

**Comment by YLQZ** [comment]
you can get code here   [gitee](https://gitee.com/yu_sheng/lingyuApp)

**Comment by YLQZ** [comment]
@Gruntfuggly  you can get code here [gitee](https://gitee.com/yu_sheng/lingyuApp)

**Comment by YLQZ** [comment]
@Gruntfuggly  my settings
`
"todo-tree.defaultHighlight": {
        "foreground": "red",
        "background": "black",
        "type": "text"
    },
    "todo-tree.customHighlight": {
        "TODO": {
            "iconColour": "green"
        },
        "FIXME": {
            "foreground": "black",
            "iconColour": "red"
        }
    },
    "todo-tree.rootFolder": "",
    "todo-tree.includeGlobs": [
        // "src"
    ],
    "todo-tree.excludeGlobs": [
        "**/node_modules/**",
        "**/dist/**",
        "**/plugins/**",
        "**/platforms/**",
        "**/www/**",
        "**/bower_components/**",
        "**/build/**",
        "**/.vscode/**",
        "**/.github/**",
        "**/_output/**",
        "**/*.min.*",
        "**/*.map"
    ],
`

**Comment by Gruntfuggly** [comment]
Can you tell me a file which has a tag in? I don't really have time to search your code.

Did you try it without setting any includeGlobs or excludeGlobs first? With none defined, it should search everywhere in the folder.

You  might be able to just set includeGlobs to

`**/src/*`

**Comment by Gruntfuggly** [comment]
I think if you can point me to an example in your code that you would expect to see if would be useful.

**Comment by Gruntfuggly** [comment]
I cloned your repo, and with the default todo-tree settings, the following are displayed?

![image](https://user-images.githubusercontent.com/376658/48864375-4a41cf80-edc4-11e8-8d1c-940fd454af5a.png)

Adding  `includeGlobs: [ "**/src/pages/Home/**/*" ]

![image](https://user-images.githubusercontent.com/376658/48864558-dbb14180-edc4-11e8-9ff7-68720272b96f.png)

**Comment by Gruntfuggly** [comment]
Hi - can you let me know if this is still an issue, otherwise I'll close the this...
