### ISSUE TITLE
Duplicate tasks in sidebar

### ISSUE THREAD

**Issue by adityabhaskar** [Gruntfuggly/todo-tree#94]
For some reason, I am getting all tasks in duplicate in my sidebar - in both flat view and tree view. Screenshot:
<img width="236" alt="screenshot 2018-11-20 at 13 09 22" src="https://user-images.githubusercontent.com/2292388/48775806-0b2d5480-ecc6-11e8-9855-5d4930bd2e1f.png">
<img width="236" alt="screenshot 2018-11-20 at 13 11 07" src="https://user-images.githubusercontent.com/2292388/48775808-0bc5eb00-ecc6-11e8-9412-4d5003e1a617.png">

This may be a duplicate (or reappearance) of #4 
My settings are as below:
<img width="325" alt="screenshot 2018-11-20 at 13 06 43" src="https://user-images.githubusercontent.com/2292388/48775878-3ca62000-ecc6-11e8-9614-a2ba0d5b4150.png">
<img width="325" alt="screenshot 2018-11-20 at 13 07 05" src="https://user-images.githubusercontent.com/2292388/48775879-3d3eb680-ecc6-11e8-8623-5f659e8fa67e.png">

**Comment by Gruntfuggly** [comment]
Does it remove the duplicates if you press the refresh button (the clockwise arrow)?

**Comment by adityabhaskar** [comment]
It removes the duplicates when I switch between flat and tree layout. The
duplicates  reappear when the refresh button is pressed.

**Comment by Gruntfuggly** [comment]
ooh - that's odd.

Is it possible to grab the debug log and see what's in it?

What platform are you running on?

**Comment by adityabhaskar** [comment]
Platform: macOs Mojave

Attached a screenshot of debug log and sidebar state below.

There is double counting happening for some of the tasks. There are only 14 items in the match list, but the prompt says '17 items found'.

<img width="1170" alt="screenshot 2018-11-21 at 13 30 56" src="https://user-images.githubusercontent.com/2292388/48844505-f1594380-ed91-11e8-9d96-e4c74cc5fba5.png">

**Comment by adityabhaskar** [comment]
Btw, despite the occasional issue, I really appreciate the extension. Works brilliantly with my workflow. Thanks a lot!

I owe you a beer next time I'm in Brighton 🍺

**Comment by Furqan136** [comment]
Same problem with me in Ubuntu 18.04.1

**Comment by Gruntfuggly** [comment]
At OK - found it.
