### ISSUE TITLE
Case insensitive tags don't show in tree

### ISSUE THREAD

**Issue by Furqan136** [Gruntfuggly/todo-tree#95]
When case sensitive filter option is false, lowercase tags get highlighted but don't show in tree view.

**Comment by Gruntfuggly** [comment]
Do you mean the setting `todo-tree.filterCaseSensitive` ? This is for filtering items from the tree view (when you press the funnel button), and doesn't affect the search or the highlights.

If you want the search to be insensitive, you can set `todo-tree.regexCaseSensitive` which should match "TODO" and "todo", etc.

**Comment by Furqan136** [comment]
Ok, my bad. I tried setting todo-tree.regexCaseSensitive to false and it shows the tags in tree view but creates another dropdown for each version i.e 'TODO' and 'todo' have different dropdowns. Any solution for that?

**Comment by Gruntfuggly** [comment]
Are you using 'group by tag' ? I don't know if it would consider them to be different in this case. Or is exactly the same TODO appearing twice?

**Comment by Furqan136** [comment]
I am using 'group by tag' and the issue is with the tag group. Have a look at the attached image.
![image](https://user-images.githubusercontent.com/44787678/48864646-07492180-edef-11e8-8981-2faea1fd9bd0.png)

**Comment by Gruntfuggly** [comment]
Ah OK - so if `todo-tree.regexCaseSensitive` is false, then the tag groups should work the same way. Fair point.

**Comment by Furqan136** [comment]
yeah sure, works for me.
But if you want to leave it to the user, you can choose from the tag list in the settings and whatever is in there would become the standard.

**Comment by Gruntfuggly** [comment]
Ah - that's an idea, it should use the tag anyway. Thanks!

**Comment by Gruntfuggly** [comment]
I've just uploaded a new version with a fix for this (and your other issue).

**Comment by Furqan136** [comment]
Great!

**Comment by Gruntfuggly** [comment]
I'm not seeing this - can you post your settings?

**Comment by Furqan136** [comment]
[settings.txt](https://github.com/Gruntfuggly/todo-tree/files/2606766/settings.txt)

**Comment by Gruntfuggly** [comment]
Hi - please try the latest version. I did a really stupid change when fixing it for the insensitive tags.

**Comment by Furqan136** [comment]
Works Great now!
Really appreciate your work though. Great extension and great response.
