### ISSUE TITLE
showTagsFromOpenFilesOnly, tags remain after file is closed

### ISSUE THREAD

**Issue by Furqan136** [Gruntfuggly/todo-tree#96]
After setting showTagsFromOpenFilesOnly to true, the feature works fine with opening file but when I close any file, its tags stay in the tree until refreshed. Removing those tags from tree upon file close would be a very appreciated fix.

**Comment by Gruntfuggly** [comment]
Makes sense - I'll add it.

**Comment by Gruntfuggly** [comment]
Hmmm - struggling to reproduce this. When I close the editor, it's removed from the tree.
Have you got `autoRefresh` set to false?

**Comment by Furqan136** [comment]
I tried setting it to true in settings but the issue persists

**Comment by Furqan136** [comment]
Also, you say in the description of 'autorefresh' that it only refreshes on file save or open

**Comment by Gruntfuggly** [comment]
Yes, that's not quite true - it should work on close too.

Is there anything special about the file being closed? How are you closing it?

**Comment by Furqan136** [comment]
Nothing special, just tried on a hello world c code. Closing from the close button in explorer or ctrl+W same thing happens.

**Comment by Gruntfuggly** [comment]
Has the file ever been saved?

**Comment by Gruntfuggly** [comment]
OK - I've reproduced it.
