### ISSUE TITLE
Can't use flat view (?)

### ISSUE THREAD

**Issue by decpr** [Gruntfuggly/todo-tree#98]
Some time ago I had in the tree the possibility, to sort the list by tags and also with one click go to that line where the tag is.
For example if my tag is "TODO" and I write in the code: "//TODO Do something here" it would show me "TODO Do something here" in the tree / explorer. With a click I get to that line.
Then when I for example add "//TODO Do something more here 2" in another line, the second, "TODO Do something here 2" would be under the first in the list (alphabetically sorted).

But now - I don't know why - I get the following (when I click "Group by tag").
![img1](https://user-images.githubusercontent.com/37114784/48905319-88d99780-ee61-11e8-91ab-be42fa552ecc.JPG)

It starts with the problem, that the whole line is now in the tree. In my above example the whole "//TODO Do something here" is in the tree (instead of just "TODO Do something here"). But the bigger problem is, that it now shows the file name, then again the tag and only there I can click to go to the line.
For example:
"//TODO Do something here"
I click on it (dropdown opens)
"file.php (c:\user[...])"
I click on it (dropdown opens again...)
"Do something here"
I click on it and only then get to the line
(some clicks needed. I can "expand all" but that's a hella long list then)

In the above example all tags are sorted by tags. All TODO are together, all IMPORTANT are together etc.
If I have multiple TODO tags, they're under each other. But I always have to click multiple times to get to the line I want.

In the next I have all under each other (when I click "Ungroup by tag")
"TODO Do something here 1"
"TODO Do something here 2"
"TODO Do something here 3"
But they're sorted by line and no longer by name/tag.
For example if I have "TODO Do something here 1" in line 30 and "TODO Do something here 2" in line 40 and add "IMPORTANT Fix this" in line 33 the list looks like this
![img2](https://user-images.githubusercontent.com/37114784/48905318-88d99780-ee61-11e8-9c7e-287439bb2233.JPG)

"TODO Do something here 1"
"IMPORTANT Fix this"
"TODO Do something here 2"
"TODO Do something here 3"

How can I get back to where I have the list like in the second but sorted by tag?
When I click "Show Flat view" / "Show tree view" nothing happens.

I had that some days ago, it worked well. I don't know what happened in the meantime.

**Comment by Gruntfuggly** [comment]
This seems linked to #95. I'm looking into it.

**Comment by Gruntfuggly** [comment]
OK, I think I found the problem - I did a really stupid change to find the tag when grouping by tag. This would have been caught by unit tests - which I am in the process of adding. This has highlighting how important they are, so I need to get them integrated now.

I've just uploaded a new version - let me know if it works properly again.

Sorry for the mess!

**Comment by decpr** [comment]
Thanks for the answer! The first one seems fixed now. But the second is still sorted by line, not by tag.
So what I would like to have is the first one (with the dropdown:) but with the ability to not show the filename, instead, only the todos. I mostly work with one file only so I would not need it.

Here it is fixed (now longer much dropdowns):
![img1](https://user-images.githubusercontent.com/37114784/48931036-8bd19800-eef4-11e8-9cd8-c3ea62a5430d.JPG)

But here still sorted by line, not by tag:
![img2](https://user-images.githubusercontent.com/37114784/48931035-8bd19800-eef4-11e8-96a8-43141b029f6e.JPG)

If that would be possible, it would be awesome! I have made a little edit to show what I mean.
All tags in a expandable dropdown under each other and once I click a specific tag, I get to that line. Here how I mean it:
![img3 jpg](https://user-images.githubusercontent.com/37114784/48931189-46fa3100-eef5-11e8-9270-3bbcae45ba49.png)

Thanks and have a good day

**Comment by Gruntfuggly** [comment]
If your files are all in the same folder (i.e. no subfolders) then you won't see any difference between the tree view and the flat view.

So, are you looking for a minimal, flat, grouped view, without filenames?

**Comment by decpr** [comment]
Exactly, that would be awesome. Like I posted in my image (the last one).

**Comment by Gruntfuggly** [comment]
I've just uploaded a new version which supports a tags only view. Without grouping it will just list all tags (no tree). If you switch on grouping, they will be grouped by the tag.

To enable it, the button now goes *tree -> flat -> tags only -> tree*

Let me know what  you think. 😁

**Comment by decpr** [comment]
Yes that's right, I think it's also depending on your workflow. Like sometimes you just might want to go trough the list from top to bottom. But when for example searching a specific thing and having a big list (I don't use TODO tree as TODO only, because it's also helpful if you have several functions "marked" and have a list of all of them :P), it might be helpful to sort by name. Maybe keeping both options and adding a "Sort by name / Sort by line"-option would be great!

**Comment by decpr** [comment]
Thanks very much! Have a great day!
